### ISSUE TITLE
Cannot save Events or Campaigns with a Matrix row in 3.7.20

### ISSUE THREAD

**Issue by mark-adigital** [craftcms/cms#10099]
### Description
At some stage (likely during a recent Project YAML update) our live environment has started to throw an error when trying to save either [Events](https://verbb.io/craft-plugins/events/features) or [Campaigns](https://putyourlightson.com/plugins/campaign) which have a Matrix field in their layout.

Events:

```yii\base\ErrorException: Undefined property: craft\elements\db\MatrixBlockQuery::$Criteria in /vendor/yiisoft/yii2/base/ArrayableTrait.php:126
Stack trace:
#0 /vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined prope...', '/srv/users/becb...', 126)
#1 /vendor/yiisoft/yii2/base/ArrayableTrait.php(126): craft\web\ErrorHandler->handleError(8, 'Undefined prope...', '/srv/users/becb...', 126, Array)
#2 /vendor/craftcms/cms/src/elements/db/ElementQuery.php(1766): craft\elements\db\ElementQuery->toArray(Array, Array, false)
#3 /vendor/yiisoft/yii2/base/Component.php(140): craft\elements\db\ElementQuery->getCriteria()
#4 /vendor/craftcms/cms/src/elements/db/ElementQuery.php(538): yii\base\Component->__get('Criteria')
#5 /vendor/yiisoft/yii2/base/ArrayableTrait.php(126): craft\elements\db\ElementQuery->__get('Criteria')
#6 /vendor/craftcms/cms/src/elements/db/ElementQuery.php(1766): craft\elements\db\ElementQuery->toArray(Array, Array, false)
#7 /vendor/craftcms/cms/src/elements/db/ElementQuery.php(1739): craft\elements\db\ElementQuery->getCriteria()
#8 /vendor/craftcms/cms/src/fields/Matrix.php(520): craft\elements\db\ElementQuery->setCachedResult(Array)
#9 /vendor/craftcms/cms/src/base/Element.php(4250): craft\fields\Matrix->normalizeValue('', Object(verbb\events\elements\Event))
#10 /vendor/craftcms/cms/src/base/Element.php(3514): craft\base\Element->normalizeFieldValue('eventAttendees')
#11 /vendor/verbb/events/src/helpers/EventHelper.php(105): craft\base\Element->setFieldValuesFromRequest('fields')
#12 /vendor/verbb/events/src/controllers/EventsController.php(155): verbb\events\helpers\EventHelper::populateEventFromPost()
#13 [internal function]: verbb\events\controllers\EventsController->actionSave()
#14 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#16 /vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('save', Array)
#17 /vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('events/events/s...', Array)
#18 /vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('events/events/s...', Array)
#19 /vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /public/index.php(21): yii\base\Application->run()
#22 {main}
```

Campaign:

```yii\base\ErrorException: Undefined property: craft\elements\db\MatrixBlockQuery::$Criteria in /vendor/yiisoft/yii2/base/ArrayableTrait.php:126
Stack trace:
#0 /vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined prope...', '/srv/users/becb...', 126)
#1 /vendor/yiisoft/yii2/base/ArrayableTrait.php(126): craft\web\ErrorHandler->handleError(8, 'Undefined prope...', '/srv/users/becb...', 126, Array)
#2 /vendor/craftcms/cms/src/elements/db/ElementQuery.php(1766): craft\elements\db\ElementQuery->toArray(Array, Array, false)
#3 /vendor/yiisoft/yii2/base/Component.php(140): craft\elements\db\ElementQuery->getCriteria()
#4 /vendor/craftcms/cms/src/elements/db/ElementQuery.php(538): yii\base\Component->__get('Criteria')
#5 /vendor/yiisoft/yii2/base/ArrayableTrait.php(126): craft\elements\db\ElementQuery->__get('Criteria')
#6 /vendor/craftcms/cms/src/elements/db/ElementQuery.php(1766): craft\elements\db\ElementQuery->toArray(Array, Array, false)
#7 /vendor/craftcms/cms/src/elements/db/ElementQuery.php(1739): craft\elements\db\ElementQuery->getCriteria()
#8 /vendor/craftcms/cms/src/fields/Matrix.php(522): craft\elements\db\ElementQuery->setCachedResult(Array)
#9 /vendor/craftcms/cms/src/base/Element.php(4250): craft\fields\Matrix->normalizeValue(Array, Object(putyourlightson\campaign\elements\CampaignElement))
#10 /vendor/craftcms/cms/src/base/Element.php(3514): craft\base\Element->normalizeFieldValue('emailContent')
#11 /vendor/putyourlightson/craft-campaign/src/controllers/CampaignsController.php(481): craft\base\Element->setFieldValuesFromRequest('fields')
#12 /vendor/putyourlightson/craft-campaign/src/controllers/CampaignsController.php(281): putyourlightson\campaign\controllers\CampaignsController->_populateCampaign(Object(putyourlightson\campaign\elements\CampaignElement))
#13 [internal function]: putyourlightson\campaign\controllers\CampaignsController->actionSaveCampaign()
#14 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#16 /vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('save-campaign', Array)
#17 /vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('campaign/campai...', Array)
#18 /vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('campaign/campai...', Array)
#19 /vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /public/index.php(21): yii\base\Application->run()
#22 {main}
```

This issue isn't present on the development site (unless we pull the live DB down into dev - so it must be due to an issue in the database) and no amount of rebuilding/applying the Project Config files seems to be fix the issue. I'm aware that this may need involvement from Josh at Verbb and Ben at Put Your Lights On, but as Craft/Project Config is the common link here, I was hoping to get your take first.

### Additional info

- Craft version: 3.7.20
- PHP version: 7.4
- Database driver & version: MySQL 5.7.33-0ubuntu0.16.04.1-log
- Plugins & versions: Campaign Pro 1.22.1 & Events 1.4.20

**Comment by brandonkelly** [comment]
What are the actual errors? (Stack traces are just the steps leading up to the error.)

**Comment by mark-adigital** [comment]
Sorry - been a long day looking so led to some square eyes I think, could have sworn that was copied with the stack trace!

The error is:

`[yii\base\ErrorException:8] yii\base\ErrorException: Undefined property: craft\elements\db\MatrixBlockQuery::$Criteria in /srv/users/becbc/apps/becbc/vendor/yiisoft/yii2/base/ArrayableTrait.php:126`

**Comment by brandonkelly** [comment]
Do you have a custom field with the handle `criteria` or something? I’m having trouble following what’s going on here.

Maybe it would help if you could send your Composer files and a database backup into support@craftcms.com.

**Comment by mark-adigital** [comment]
Thanks - just sent that across.

**Comment by brandonkelly** [comment]
This ended up being due to a field with the handle `Criteria`. There was already a guard in place fol `criteria` (lowercase `c` – #7335), but that check was missed due to the uppercase `C`. Fixed now for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.21"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.22 is out now with that fix.

**Comment by mark-adigital** [comment]
That's great - thank you!
