### ISSUE TITLE
Error: Setting unknown property: craft\fieldlayoutelements\CustomField::style when applying project config

### ISSUE THREAD

**Issue by timrosskamp** [craftcms/cms#10221]
### Description

I've tried to delete the folder `compiled_classes` so far without any success.

The command `project-config/apply` fails with this error:

```
$ ./craft project-config/apply
Applying changes from your project config files ...
- updating entryTypes.e356f084-c163-4afb-9c12-2bd7ff578d18.fieldLayouts.72c42cf2-7f34-4249-8f6f-707542815ab0.tabs.0.elements.1 ... 
  - updating entryTypes.e356f084-c163-4afb-9c12-2bd7ff578d18 ... 
error: Setting unknown property: craft\fieldlayoutelements\CustomField::style
```

This is what I can find in the logs:

```
2021-12-07 16:06:55 [-][-][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: craft\fieldlayoutelements\CustomField::style in /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/BaseObject.php:163
Stack trace:
#0 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\BaseObject->__set('style', 'tip')
#1 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\fieldlayoutelements\CustomField), Array)
#2 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(59): yii\base\BaseObject->__construct(Array)
#3 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(39): craft\fieldlayoutelements\BaseField->__construct(Array)
#4 [internal function]: craft\fieldlayoutelements\CustomField->__construct(NULL, Array)
#5 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#6 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\fieldlayo...', Array, Array)
#7 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\fieldlayo...', Array, Array)
#8 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/Craft.php(67): yii\BaseYii::createObject(Array, Array)
#9 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/Fields.php(1255): Craft::createObject(Array)
#10 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/models/FieldLayoutTab.php(137): craft\services\Fields->createLayoutElement(Array)
#11 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\models\FieldLayoutTab->init()
#12 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/models/FieldLayoutTab.php(41): yii\base\BaseObject->__construct(Array)
#13 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/models/FieldLayout.php(140): craft\models\FieldLayoutTab::createFromConfig(Array)
#14 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/Sections.php(1160): craft\models\FieldLayout::createFromConfig(Array)
#15 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/base/ApplicationTrait.php(1673): craft\services\Sections->handleChangedEntryType(Object(craft\events\ConfigEvent))
#16 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(1189): craft\console\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#17 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#18 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#19 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(752): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#20 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(1179): craft\services\ProjectConfig->_processConfigChangesInternal('entryTypes.e356...')
#21 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#22 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#23 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(752): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#24 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(1308): craft\services\ProjectConfig->_processConfigChangesInternal('entryTypes.e356...', false, NULL, true)
#25 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(573): craft\services\ProjectConfig->_applyChanges(Array)
#26 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(174): craft\services\ProjectConfig->applyYamlChanges()
#27 [internal function]: craft\console\controllers\ProjectConfigController->actionApply()
#28 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#29 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#30 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('apply', Array)
#31 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/console/Controller.php(221): yii\console\Controller->runAction('apply', Array)
#32 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/Module.php(534): craft\console\Controller->runAction('apply', Array)
#33 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('project-config/...', Array)
#34 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('project-config/...', Array)
#35 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('project-config/...', Array)
#36 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#37 /httpdocs/de_st-2_graeper-dev/craft(22): yii\base\Application->run()
#38 {main}
```

A few tries earlier I also got some additional warning right before the error:

```
2021-12-07 14:22:54 [-][-][-][warning][craft\db\mysql\Schema::releaseSavepoint] Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: RELEASE SAVEPOINT LEVEL1
2021-12-07 14:22:54 [-][-][-][warning][craft\db\mysql\Schema::releaseSavepoint] Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: RELEASE SAVEPOINT LEVEL1
2021-12-07 14:22:55 [-][-][-][warning][craft\db\mysql\Schema::releaseSavepoint] Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: RELEASE SAVEPOINT LEVEL1
2021-12-07 14:22:55 [-][-][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: craft\fieldlayoutelements\CustomField::style in /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/BaseObject.php:163
Stack trace:
#0 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\BaseObject->__set('style', 'tip')
#1 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\fieldlayoutelements\CustomField), Array)
#2 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(59): yii\base\BaseObject->__construct(Array)
#3 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(39): craft\fieldlayoutelements\BaseField->__construct(Array)
#4 [internal function]: craft\fieldlayoutelements\CustomField->__construct(NULL, Array)
#5 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#6 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\fieldlayo...', Array, Array)
#7 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\fieldlayo...', Array, Array)
#8 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/Craft.php(67): yii\BaseYii::createObject(Array, Array)
#9 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/Fields.php(1255): Craft::createObject(Array)
#10 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/models/FieldLayoutTab.php(137): craft\services\Fields->createLayoutElement(Array)
#11 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\models\FieldLayoutTab->init()
#12 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/models/FieldLayoutTab.php(41): yii\base\BaseObject->__construct(Array)
#13 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/models/FieldLayout.php(140): craft\models\FieldLayoutTab::createFromConfig(Array)
#14 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/Sections.php(1160): craft\models\FieldLayout::createFromConfig(Array)
#15 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/base/ApplicationTrait.php(1673): craft\services\Sections->handleChangedEntryType(Object(craft\events\ConfigEvent))
#16 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(1189): craft\console\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#17 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#18 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#19 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(752): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#20 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(1179): craft\services\ProjectConfig->_processConfigChangesInternal('entryTypes.e356...')
#21 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#22 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#23 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(752): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#24 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(1308): craft\services\ProjectConfig->_processConfigChangesInternal('entryTypes.e356...', false, NULL, true)
#25 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(573): craft\services\ProjectConfig->_applyChanges(Array)
#26 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(174): craft\services\ProjectConfig->applyYamlChanges()
#27 [internal function]: craft\console\controllers\ProjectConfigController->actionApply()
#28 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#29 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#30 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('apply', Array)
#31 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/console/Controller.php(221): yii\console\Controller->runAction('apply', Array)
#32 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/Module.php(534): craft\console\Controller->runAction('apply', Array)
#33 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('project-config/...', Array)
#34 /httpdocs/de_st-2_graeper-dev/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('project-config/...', Array)
#35 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('project-config/...', Array)
#36 /httpdocs/de_st-2_graeper-dev/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#37 /httpdocs/de_st-2_graeper-dev/craft(22): yii\base\Application->run()
#38 {main}
```

### Steps to reproduce

1. Run `./craft project-config/apply`
2.

### Additional info

- Craft version: 3.7.24
- PHP version: 8.0
- Database driver & version: MySQL 8.0.25
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Can you, please, share your `config/project` folder over email to support@craftcms.com and reference this issue?

It'll much faster to just look at your project config to start figuring this out.

**Comment by andris-sevcenko** [comment]
We don't use the `style` property anywhere. Can you go through your git history for the file and see when it was added? Or, alternatively, you can go through the project config delta files (`storage/config-deltas`) on the origin installation and see what added that?

**Comment by timrosskamp** [comment]
Thanks for your help so far!

After saving the specific entry type again without any changes, the property `style` got removed from the project config. I still have no idea how this property got added in the first place. But applying the project config is working now.

I've sent the config delta files that show when the `style` property was added to support@craftcms.com if you'd like to look into it.

**Comment by andris-sevcenko** [comment]
Ah, sorry, so the `style` property is used by Tip and Warning UI elements. So it still sounds like a bad merge. Let me know if you run into this again.

**Comment by timrosskamp** [comment]
I've had a similar problem happen once again and it seems to be caused by something else than a bad merge. I haven't done any git merging on this one.

This is what happend: I changed the field type from `craft\fields\Url` to `typedlinkfield\fields\LinkField`. This worked fine at first, but later when working on something completely different, some settings in the project config that belonged to the original field type of `craft\fields\Url` got added to the new field type `typedlinkfield\fields\LinkField` again. I get the same `UnknownPropertyException` again, but now with the property `maxLength`.

I've sent you the project config and the most recent config deltas to support@craftcms.com in case this helps.

**Comment by brandonkelly** [comment]
When you are making changes, are you seeing the expected changes to the YAML files in `config/project/`?

**Comment by timrosskamp** [comment]
Yes, I was editing a different entry type, which changed the files in `config/project/` just the way I expected them. But alongside the change I accually made, those properties (`maxLength` and `placeholder`) got added to the field with the type `typedlinkfield\fields\LinkField` I changed earlier.

**Comment by andris-sevcenko** [comment]
@timrosskamp just to confirm - you are seeing these properties appear in a 'config/project/entryTypes/<filename>.yml` file?

**Comment by andris-sevcenko** [comment]
I'm guessing that this is local dev. What's your tech stack for this? Is Docker involved?

**Comment by timrosskamp** [comment]
Yes, I'm working local and we use Docker with this docker-compose.yml:

```
services:
  web:
    image: webdevops/php-apache-dev:8.0
    volumes:
      - ./src:/app
      - ./craft-init.sh:/opt/docker/provision/entrypoint.d/99-craft-init.sh
    ports:
      - "80:80"
    environment:
      WEB_DOCUMENT_ROOT: /app/web
      php.display_errors: "on"
      php.memory_limit: 2G
      php.max_input_vars: 5000
  database:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ***
      MYSQL_DATABASE: ***
      MYSQL_USER: ***
      MYSQL_PASSWORD: ***
```

I've had this Issue with Craft 3.7.24 and 3.7.25.1

**Comment by andris-sevcenko** [comment]
Hey Tim, sorry for the delayed response!

Curios if you could perform an experiment for me - there's been an issue sometimes on some docker environments with project config caches not being invalidated.

Can you, please:
1) Reproduce the issue to confirm it's still happening
2) Comment out these two lines:
https://github.com/craftcms/cms/blob/develop/src/services/ProjectConfig.php#L1872
and
https://github.com/craftcms/cms/blob/develop/src/services/ProjectConfig.php#L1892
3) See if you can still reproduce the issue?

After step (3), revert the changes, whether or not the changes fixed the issue or not, just so your codebase is intact.

**Comment by timrosskamp** [comment]
Hi, no worries. Have a happy new year!

Unfortunately it's difficult for me to reproduce. I have no idea which steps I've done that lead to this issue. If this happens again, I'll let you know, but I don't know what to do in order to provoke this, sorry.

**Comment by andris-sevcenko** [comment]
@timrosskamp hmm. Does reading through https://github.com/craftcms/cms/issues/7795 trigger some vague feelings of familiarity? Maybe not the exact problem but what feels like is happening?

**Comment by timrosskamp** [comment]
@andris-sevcenko It does seem to be similar. Although I don't remember that entire files are missing on my end, but changes within files. I guess the same cache related problem could cause both of these cases.

**Comment by andris-sevcenko** [comment]
Yeah. It's definitely annoying and near impossible to track down. I'll close this for now - let me know if it comes up again!
