### ISSUE TITLE
Undefined offset: 22 when accessing graphql settings in CP

### ISSUE THREAD

**Issue by jpcarpenter** [craftcms/cms#10272]
### Description

 Getting a `Undefined offset: 22` PHP error when trying to view a schema or the GraphiQL interface.

### Steps to reproduce

1. From within CP, click GraphQL > Schemas > [Schema Name] or GraphQL > GraphiQL.

### Stack trace

When clicking GraphiQL instance:
```
yii\base\ErrorException: Undefined offset: 22 in /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/services/Gql.php:1481
Stack trace:
#0 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError()
#1 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/services/Gql.php(1481): craft\web\ErrorHandler->handleError()
#2 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/services/Gql.php(700): craft\services\Gql->_getSectionSchemaComponents()
#3 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/helpers/Gql.php(319): craft\services\Gql->getAllSchemaComponents()
#4 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/controllers/GraphqlController.php(303): craft\helpers\Gql::createFullAccessSchema()
#5 [internal function]: craft\controllers\GraphqlController->actionGraphiql()
#6 /var/www/rockitscience/releases/1639771919/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 /var/www/rockitscience/releases/1639771919/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#8 /var/www/rockitscience/releases/1639771919/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#9 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction()
#10 /var/www/rockitscience/releases/1639771919/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction()
#11 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest()
#12 /var/www/rockitscience/releases/1639771919/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#13 /var/www/rockitscience/releases/1639771919/web/index.php(26): yii\base\Application->run()
#14 {main}
```

When clicking a schema:
```
yii\base\ErrorException: Undefined offset: 22 in /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/services/Gql.php:1481
Stack trace:
#0 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError()
#1 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/services/Gql.php(1481): craft\web\ErrorHandler->handleError()
#2 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/services/Gql.php(700): craft\services\Gql->_getSectionSchemaComponents()
#3 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Extension/CoreExtension.php(1511): craft\services\Gql->getAllSchemaComponents()
#4 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute()
#5 /var/www/rockitscience/shared/storage/runtime/compiled_templates/e3/e3cc964f0343162bdef365803917f5b434c296b3649e02477b4f005b2ce02717.php(117): craft\helpers\Template::attribute()
#6 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(182): __TwigTemplate_293fa538bab0b484772755b96da8db9f7bde461d55f5a8ff804a89dbd9f8a522->block_content()
#7 /var/www/rockitscience/shared/storage/runtime/compiled_templates/31/312b692241adefc8cd4be06b6140bbbf856d901c1108006d77207cc4e342d641.php(535): Twig\Template->displayBlock()
#8 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(182): __TwigTemplate_03d2fd4e474664e5629a2d9d86986a1c8839358425017c10c0691fcf6585ea29->block_main()
#9 /var/www/rockitscience/shared/storage/runtime/compiled_templates/31/312b692241adefc8cd4be06b6140bbbf856d901c1108006d77207cc4e342d641.php(346): Twig\Template->displayBlock()
#10 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(182): __TwigTemplate_03d2fd4e474664e5629a2d9d86986a1c8839358425017c10c0691fcf6585ea29->block_body()
#11 /var/www/rockitscience/shared/storage/runtime/compiled_templates/81/815f956f5753664549b61beb51911046d173b43b076c6f99f5ec9dadeb09e043.php(96): Twig\Template->displayBlock()
#12 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(405): __TwigTemplate_6e3e205fee482c7da6856f4019ddcd5ebd1b5c9da2faa77257597311712d9d1d->doDisplay()
#13 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#14 /var/www/rockitscience/shared/storage/runtime/compiled_templates/45/45cd292a48a619a81597e1cc2b30f6ad2a8da46069af422032d0747183cbd701.php(56): Twig\Template->display()
#15 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c825a43a9cede2c84f70fa1d503861cb07456f1b24dd8d9f4d7d9f41c9cffe27->doDisplay()
#16 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#17 /var/www/rockitscience/shared/storage/runtime/compiled_templates/31/312b692241adefc8cd4be06b6140bbbf856d901c1108006d77207cc4e342d641.php(165): Twig\Template->display()
#18 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(405): __TwigTemplate_03d2fd4e474664e5629a2d9d86986a1c8839358425017c10c0691fcf6585ea29->doDisplay()
#19 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#20 /var/www/rockitscience/shared/storage/runtime/compiled_templates/e3/e3cc964f0343162bdef365803917f5b434c296b3649e02477b4f005b2ce02717.php(70): Twig\Template->display()
#21 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(405): __TwigTemplate_293fa538bab0b484772755b96da8db9f7bde461d55f5a8ff804a89dbd9f8a522->doDisplay()
#22 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#23 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#24 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#25 /var/www/rockitscience/releases/1639771919/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#26 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render()
#27 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate()
#28 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate()
#29 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/controllers/GraphqlController.php(537): craft\web\Controller->renderTemplate()
#30 [internal function]: craft\controllers\GraphqlController->actionEditSchema()
#31 /var/www/rockitscience/releases/1639771919/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#32 /var/www/rockitscience/releases/1639771919/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#33 /var/www/rockitscience/releases/1639771919/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#34 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction()
#35 /var/www/rockitscience/releases/1639771919/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction()
#36 /var/www/rockitscience/releases/1639771919/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest()
#37 /var/www/rockitscience/releases/1639771919/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#38 /var/www/rockitscience/releases/1639771919/web/index.php(26): yii\base\Application->run()
#39 {main}
```

### Additional info

- Craft version: 3.7.26
- PHP version: 7.4.24
- Database driver & version: mysql 5.7

**Comment by brandonkelly** [comment]
Looks like this could occur if there is a section that somehow doesn’t have any entry types (which shouldn’t be possible but 🤷🏻). Fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.26"` and run `composer update`.

**Comment by jpcarpenter** [comment]
Thanks @brandonkelly. A colleague and I had some major project config and permission issues which I'm guessing created this odd behavior. Our fix was to restore the DB from a previous working backup and apply project config based off of the DB. Either way, happy to see you put a fix in place. Cheers!

**Comment by brandonkelly** [comment]
Ah that makes sense. Glad you got things under control.

**Comment by brandonkelly** [comment]
Craft 3.7.27 is out now with that fix.
