### ISSUE TITLE
Invalid field: title --- Dashboard Quickpost 

### ISSUE THREAD

**Issue by satcreative** [craftcms/cms#10314]
### Description

I've just updated to Craft Pro 3.7.27.1 and upon accessing the Dashboard in the backend CP I'm now receiving the below error, which documents an invalid title field in the QuickPost widget -- /srv/app/stage-hwb-sat/htdocs/vendor/craftcms/cms/src/templates/_components/widgets/QuickPost/body.html 

Any ideas how to resolve this?

```
yii\base\InvalidArgumentException: Invalid field: title in /srv/app/stage-hwb-sat/htdocs/vendor/craftcms/cms/src/models/FieldLayout.php:428
Stack trace:
#0 /srv/app/stage-hwb-sat/htdocs/vendor/twig/twig/src/Extension/CoreExtension.php(1564): craft\models\FieldLayout->getField('title')
#1 /srv/app/stage-hwb-sat/htdocs/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\models\FieldLayout), 'getField', Array, 'method', false, false)
#2 /srv/app/stage-hwb-sat/htdocs/storage/runtime/compiled_templates/9c/9cd20b5ab96572dc1ffe271201635dd0f3d1a1349e62189b000c9fa74bc68d4a.php(60): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\models\FieldLayout), 'getField', Array, 'method')
#3 /srv/app/stage-hwb-sat/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_28bfc56146727b7c3dbe16ce2b3c66d235b57a075d15d2bd3cb33f4675657fe1->doDisplay(Array, Array)
#4 /srv/app/stage-hwb-sat/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#5 /srv/app/stage-hwb-sat/htdocs/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#6 /srv/app/stage-hwb-sat/htdocs/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#7 /srv/app/stage-hwb-sat/htdocs/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#8 /srv/app/stage-hwb-sat/htdocs/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('_components/wid...', Array)
#9 /srv/app/stage-hwb-sat/htdocs/vendor/craftcms/cms/src/widgets/QuickPost.php(182): craft\web\View->renderTemplate('_components/wid...', Array)
#10 /srv/app/stage-hwb-sat/htdocs/vendor/craftcms/cms/src/controllers/DashboardController.php(505): craft\widgets\QuickPost->getBodyHtml()
#11 /srv/app/stage-hwb-sat/htdocs/vendor/craftcms/cms/src/controllers/DashboardController.php(105): craft\controllers\DashboardController->_getWidgetInfo(Object(craft\widgets\QuickPost))
#12 [internal function]: craft\controllers\DashboardController->actionIndex()
#13 /srv/app/stage-hwb-sat/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /srv/app/stage-hwb-sat/htdocs/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#15 /srv/app/stage-hwb-sat/htdocs/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#16 /srv/app/stage-hwb-sat/htdocs/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('dashboard/index', Array)
#17 /srv/app/stage-hwb-sat/htdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#18 /srv/app/stage-hwb-sat/htdocs/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest(Object(craft\web\Request))
#19 /srv/app/stage-hwb-sat/htdocs/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /srv/app/stage-hwb-sat/htdocs/web/index.php(23): yii\base\Application->run()
#21 {main}
```

### Steps to reproduce

1. Update to Craft Pro 3.7.27.1
2. Access Dashboard
3. All other areas of the CP load fine

### Additional info

- Craft version: Craft Pro 3.7.27.1
- PHP version: 7.4.25
- Database driver & version: MySQL 8.0.23
- Plugins & versions:

- Colour Swatches | 1.5.0.4
- Contact Form | 2.2.7
- Contact Form Extensions | 1.2.8
- Contact Form Honeypot | 1.0.2
- Cookies | 1.1.15
- Copy | 1.0.8
- Field Manager | 2.2.4
- fortrabbit Object Storage Volume | 2.1.0
- Imager X | v3.5.5
- Imager X Storage Driver for FortRabbit | 1.0.2
- Neo | 2.12.1
- Redactor | 2.8.8
- Redactor Custom Styles | 3.0.4
- SEOmatic | 3.4.21
- Typed link field | 1.0.25
- Webperf | 1.0.26

**Comment by joomkit** [comment]
I have just updated and get this too. Starting to dread updates now :)

**Comment by brandonkelly** [comment]
Thanks for reporting that! Not sure how I missed it as I was testing the Dashboard and am easily able to reproduce it now 🤷🏻 . Just released 3.7.28 with a fix.

**Comment by satcreative** [comment]
Thanks!

**Comment by andrewhawkes** [comment]
Just in case anyone else runs into this...

I was getting this error on `3.7.27.1`:
`[yii\base\InvalidArgumentException] yii\base\InvalidArgumentException: Invalid field: title in {server path}/craft/vendor/craftcms/cms/src/models/FieldLayout.php:428`

Updating to `3.7.30.1` fixed this for me!

**Comment by jalendport** [comment]
Currently running into this on a `3.7.48` site
