### ISSUE TITLE
Server error when searching in products in CP

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#10342]
### Description
Our client just got a server error on the AJAX request happening when you enter a search termin in /admin/commerce/products

Interestingly we (agency) could not reproduce it, so we asked the client to try again in an anonymous window. 
Then they also did NOT get the error. 

For the failing request we found the following in the log:

```

2021-12-22 10:35:55 [-][1532][kiuuhto7g9kt43ltu2fo9lraok][error][yii\db\Exception] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'score' in 'order clause' in /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
craftcms/commerce#1 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute()
craftcms/commerce#2 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal()
craftcms/commerce#3 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
craftcms/commerce#4 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all()
craftcms/commerce#5 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/services/Search.php(328): craft\db\Query->all()
craftcms/commerce#6 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/services/Search.php(238): craft\services\Search->_searchElements()
craftcms/commerce#7 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2822): craft\services\Search->searchElements()
craftcms/commerce#8 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1541): craft\elements\db\ElementQuery->_applySearchParam()
craftcms/commerce#9 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
craftcms/commerce#10 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
craftcms/commerce#11 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Query->createCommand()
craftcms/commerce#12 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all()
craftcms/commerce#13 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1619): craft\db\Query->all()
craftcms/commerce#14 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/base/Element.php(867): craft\elements\db\ElementQuery->all()
craftcms/commerce#15 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(534): craft\base\Element::indexHtml()
craftcms/commerce#16 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(135): craft\controllers\ElementIndexesController->elementResponseData()
craftcms/commerce#17 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
craftcms/commerce#18 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
craftcms/commerce#19 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
craftcms/commerce#20 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
craftcms/commerce#21 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction()
#22 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction()
craftcms/commerce#23 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest()
craftcms/commerce#24 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
craftcms/commerce#25 /data/www/XXX/web/XXX/web/index.php(19): yii\base\Application->run()
craftcms/commerce#26 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'score' in 'order clause'
The SQL being executed was: SELECT *
FROM `searchindex`
WHERE (MATCH(`keywords`) AGAINST('+mozar*' IN BOOLEAN MODE)) AND (`siteId`=1) AND (`elementId` IN (SELECT `elements`.`id`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `elements` `elements`
INNER JOIN `commerce_products` `commerce_products` ON `commerce_products`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
WHERE (`commerce_products`.`typeId` IN ('2', '3')) AND (`commerce_products`.`typeId` IN ('2', '3')) AND (`elements_sites`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)
ORDER BY `score` DESC, `postDate` DESC) `subquery`
INNER JOIN `commerce_products` `commerce_products` ON `commerce_products`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `score` DESC, `postDate` DESC)) in /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Schema.php:678
Stack trace:

```

### Steps to reproduce

1. open /admin/commerce/products
2. enter a searchterm in the search field and wait for the AJAX call
3. the AJAX call fails with a short JSON response "an error occured" (or something similar)
### Additional info

- Craft CMS version: 3.7.25.1 Pro
- Craft Commerce version: 3.4.9.2
- PHP version: 7.4

**Comment by angrybrad** [comment]
@hiasl Not sure how I missed it but looks like this was fixed in 3.7.26 (https://github.com/craftcms/cms/commit/d26f1733fb9959256c2937536ca0f11d99bd89ba).

Try updating to the latest and see if it still happens. Going to close, but if you still see it, comment back and we'll re-open.
