### ISSUE TITLE
Attempt to read property "columns" on null

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [craftcms/cms#10414]
I'm attempting to clone an existing `matrix` field with Field Manager and make a few updates and save it as a new `matrix` field.

Upon saving my new Matrix I get this:

`Stack Trace`

```
yii\base\ErrorException: Attempt to read property "columns" on null in /var/www/project/cms/vendor/craftcms/cms/src/services/Fields.php:1045
Stack trace:
#0 /var/www/project/cms/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(2, 'Attempt to read...', '/var/www/projec...', 1045)
#1 /var/www/project/cms/vendor/craftcms/cms/src/services/Fields.php(1045): craft\web\ErrorHandler->handleError(2, 'Attempt to read...', '/var/www/projec...', 1045)
#2 /var/www/project/cms/vendor/craftcms/cms/src/services/Fields.php(991): craft\services\Fields->_dropOldFieldColumns('target', 'ygqikjbo')
#3 /var/www/project/cms/vendor/craftcms/cms/src/services/Fields.php(939): craft\services\Fields->applyFieldDelete('a5fcc294-738b-4...')
#4 /var/www/project/cms/vendor/verbb/super-table/src/services/SuperTableService.php(471): craft\services\Fields->deleteField(Object(fruitstudios\linkit\fields\LinkitField))
#5 /var/www/project/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(1190): verbb\supertable\services\SuperTableService->handleDeletedBlockType(Object(craft\events\ConfigEvent))
#6 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#7 /var/www/project/cms/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#8 /var/www/project/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(747): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#9 /var/www/project/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(522): craft\services\ProjectConfig->_processConfigChangesInternal('superTableBlock...', true, 'Delete super ta...')
#10 /var/www/project/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(538): craft\services\ProjectConfig->set('superTableBlock...', NULL, 'Delete super ta...')
#11 /var/www/project/cms/vendor/verbb/super-table/src/services/SuperTableService.php(405): craft\services\ProjectConfig->remove('superTableBlock...', 'Delete super ta...')
#12 /var/www/project/cms/vendor/verbb/super-table/src/services/SuperTableService.php(662): verbb\supertable\services\SuperTableService->deleteBlockType(Object(verbb\supertable\models\SuperTableBlockTypeModel))
#13 /var/www/project/cms/vendor/verbb/super-table/src/fields/SuperTableField.php(1055): verbb\supertable\services\SuperTableService->deleteSuperTableField(Object(verbb\supertable\fields\SuperTableField))
#14 /var/www/project/cms/vendor/craftcms/cms/src/services/Fields.php(988): verbb\supertable\fields\SuperTableField->beforeApplyDelete()
#15 /var/www/project/cms/vendor/craftcms/cms/src/services/Matrix.php(298): craft\services\Fields->applyFieldDelete('acc78c93-375d-4...')
#16 /var/www/project/cms/vendor/craftcms/cms/src/base/ApplicationTrait.php(1681): craft\services\Matrix->handleChangedBlockType(Object(craft\events\ConfigEvent))
#17 /var/www/project/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(1190): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#18 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#19 /var/www/project/cms/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#20 /var/www/project/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(753): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#21 /var/www/project/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(522): craft\services\ProjectConfig->_processConfigChangesInternal('matrixBlockType...', true, 'Save matrix blo...')
#22 /var/www/project/cms/vendor/craftcms/cms/src/services/Matrix.php(228): craft\services\ProjectConfig->set('matrixBlockType...', Array, 'Save matrix blo...')
#23 /var/www/project/cms/vendor/craftcms/cms/src/services/Matrix.php(576): craft\services\Matrix->saveBlockType(Object(craft\models\MatrixBlockType), false)
#24 /var/www/project/cms/vendor/craftcms/cms/src/fields/Matrix.php(996): craft\services\Matrix->saveSettings(Object(craft\fields\Matrix), false)
#25 /var/www/project/cms/vendor/craftcms/cms/src/services/Fields.php(1873): craft\fields\Matrix->afterSave(false)
#26 /var/www/project/cms/vendor/craftcms/cms/src/services/Fields.php(896): craft\services\Fields->applyFieldSave('4e2e8f13-d433-4...', Array, 'global')
#27 /var/www/project/cms/vendor/craftcms/cms/src/base/ApplicationTrait.php(1681): craft\services\Fields->handleChangedField(Object(craft\events\ConfigEvent))
#28 /var/www/project/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(1190): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#29 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#30 /var/www/project/cms/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#31 /var/www/project/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(753): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#32 /var/www/project/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(522): craft\services\ProjectConfig->_processConfigChangesInternal('fields.4e2e8f13...', true, 'Save field \xE2\x80\x9Cg...')
#33 /var/www/project/cms/vendor/craftcms/cms/src/services/Fields.php(833): craft\services\ProjectConfig->set('fields.4e2e8f13...', Array, 'Save field \xE2\x80\x9Cg...')
#34 /var/www/project/cms/vendor/craftcms/cms/src/controllers/FieldsController.php(328): craft\services\Fields->saveField(Object(craft\fields\Matrix))
#35 [internal function]: craft\controllers\FieldsController->actionSaveField()
#36 /var/www/project/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#37 /var/www/project/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#38 /var/www/project/cms/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-field', Array)
#39 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('fields/save-fie...', Array)
#40 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('fields/save-fie...', Array)
#41 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#42 /var/www/project/cms/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#43 /var/www/project/cms/web/index.php(21): yii\base\Application->run()
#44 {main}
```

### Steps to reproduce

1.  Clone a Matrix Field
2. Make updates
3. Attempt to save it

My `matrix` setup is a bit more robust than your standard site, so if you need a db dump or access to my project that can be arranged.

### Additional info

- Craft version: 3.7.30
- PHP version: 8.0.13
- Database driver & version: MariaDB
- Plugins & versions: Field Manager 2.2.4

Thanks for the help on this one!

**Comment by timkelty** [comment]
@DynamiteGoesBoom since this is specific to Field Manager, could you start by posting to https://github.com/verbb/field-manager?
