### ISSUE TITLE
Duplicate key value violates unique constraint "fieldlayouttabs_pkey"

### ISSUE THREAD

**Issue by 3v-afranz** [craftcms/cms#10597]
I tried to save a Matrix field with one block:

![image](https://user-images.githubusercontent.com/97749528/154466137-f586a24b-72b9-4cf2-803e-ac7c6c51ed1d.png)

And I get this error.

> Duplicate key value violates unique constraint "fieldlayouttabs_pkey"

None of the handles I am using are being used for other fields.

I tried refreshing the page and using different handle names but I always get this error when saving.

The complete error log is:

```
PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "fieldlayouttabs_pkey"
DETAIL:  Key (id)=(249) already exists. in /app/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /app/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('INSERT INTO "fi...')
#2 /app/vendor/yiisoft/yii2/db/Command.php(424): yii\db\Command->queryInternal('fetch', NULL)
#3 /app/vendor/yiisoft/yii2/db/pgsql/Schema.php(646): yii\db\Command->queryOne()
#4 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\pgsql\Schema->insert('{{%fieldlayoutt...', Array)
#5 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal(NULL)
#6 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert(false, NULL)
#7 /app/vendor/craftcms/cms/src/services/Fields.php(1597): yii\db\BaseActiveRecord->save(false)
#8 /app/vendor/craftcms/cms/src/services/Matrix.php(319): craft\services\Fields->saveLayout(Object(craft\models\FieldLayout))
#9 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1681): craft\services\Matrix->handleChangedBlockType(Object(craft\events\ConfigEvent))
#10 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1190): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#11 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#12 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#13 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(750): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#14 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(522): craft\services\ProjectConfig->_processConfigChangesInternal('matrixBlockType...', true, 'Save matrix blo...')
#15 /app/vendor/craftcms/cms/src/services/Matrix.php(228): craft\services\ProjectConfig->set('matrixBlockType...', Array, 'Save matrix blo...')
#16 /app/vendor/craftcms/cms/src/services/Matrix.php(576): craft\services\Matrix->saveBlockType(Object(craft\models\MatrixBlockType), false)
#17 /app/vendor/craftcms/cms/src/fields/Matrix.php(996): craft\services\Matrix->saveSettings(Object(craft\fields\Matrix), false)
#18 /app/vendor/craftcms/cms/src/services/Fields.php(1873): craft\fields\Matrix->afterSave(false)
#19 /app/vendor/craftcms/cms/src/services/Fields.php(896): craft\services\Fields->applyFieldSave('cbba9229-f211-4...', Array, 'global')
#20 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1681): craft\services\Fields->handleChangedField(Object(craft\events\ConfigEvent))
#21 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1190): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#22 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#23 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#24 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(750): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#25 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(522): craft\services\ProjectConfig->_processConfigChangesInternal('fields.cbba9229...', true, 'Save field \xE2\x80\x9Cb...')
#26 /app/vendor/craftcms/cms/src/services/Fields.php(833): craft\services\ProjectConfig->set('fields.cbba9229...', Array, 'Save field \xE2\x80\x9Cb...')
#27 /app/vendor/craftcms/cms/src/controllers/FieldsController.php(328): craft\services\Fields->saveField(Object(craft\fields\Matrix))
#28 [internal function]: craft\controllers\FieldsController->actionSaveField()
#29 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#31 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-field', Array)
#32 /app/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('fields/save-fie...', Array)
#33 /app/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('fields/save-fie...', Array)
#34 /app/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#35 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#36 /app/public/index.php(31): yii\base\Application->run()
#37 {main}

Next yii\db\IntegrityException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "fieldlayouttabs_pkey"
DETAIL:  Key (id)=(249) already exists.
The SQL being executed was: INSERT INTO "fieldlayouttabs" ("layoutId", "sortOrder", "name", "elements", "dateCreated", "dateUpdated", "uid") VALUES (59, 1, 'Content', '[{"type":"craft\\fieldlayoutelements\\CustomField","label":null,"instructions":null,"tip":null,"warning":null,"required":false,"width":100,"fieldUid":"95fda2a4-eab7-4a65-9070-93ebf1713e91"}]', '2022-02-17 10:00:48', '2022-02-17 10:00:48', '137e1c9f-34da-478e-a427-e6822efb68ca') RETURNING "id" in /app/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO "fi...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('INSERT INTO "fi...')
#2 /app/vendor/yiisoft/yii2/db/Command.php(424): yii\db\Command->queryInternal('fetch', NULL)
#3 /app/vendor/yiisoft/yii2/db/pgsql/Schema.php(646): yii\db\Command->queryOne()
#4 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\pgsql\Schema->insert('{{%fieldlayoutt...', Array)
#5 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal(NULL)
#6 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert(false, NULL)
#7 /app/vendor/craftcms/cms/src/services/Fields.php(1597): yii\db\BaseActiveRecord->save(false)
#8 /app/vendor/craftcms/cms/src/services/Matrix.php(319): craft\services\Fields->saveLayout(Object(craft\models\FieldLayout))
#9 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1681): craft\services\Matrix->handleChangedBlockType(Object(craft\events\ConfigEvent))
#10 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1190): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#11 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#12 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#13 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(750): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#14 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(522): craft\services\ProjectConfig->_processConfigChangesInternal('matrixBlockType...', true, 'Save matrix blo...')
#15 /app/vendor/craftcms/cms/src/services/Matrix.php(228): craft\services\ProjectConfig->set('matrixBlockType...', Array, 'Save matrix blo...')
#16 /app/vendor/craftcms/cms/src/services/Matrix.php(576): craft\services\Matrix->saveBlockType(Object(craft\models\MatrixBlockType), false)
#17 /app/vendor/craftcms/cms/src/fields/Matrix.php(996): craft\services\Matrix->saveSettings(Object(craft\fields\Matrix), false)
#18 /app/vendor/craftcms/cms/src/services/Fields.php(1873): craft\fields\Matrix->afterSave(false)
#19 /app/vendor/craftcms/cms/src/services/Fields.php(896): craft\services\Fields->applyFieldSave('cbba9229-f211-4...', Array, 'global')
#20 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1681): craft\services\Fields->handleChangedField(Object(craft\events\ConfigEvent))
#21 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1190): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#22 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#23 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#24 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(750): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#25 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(522): craft\services\ProjectConfig->_processConfigChangesInternal('fields.cbba9229...', true, 'Save field \xE2\x80\x9Cb...')
#26 /app/vendor/craftcms/cms/src/services/Fields.php(833): craft\services\ProjectConfig->set('fields.cbba9229...', Array, 'Save field \xE2\x80\x9Cb...')
#27 /app/vendor/craftcms/cms/src/controllers/FieldsController.php(328): craft\services\Fields->saveField(Object(craft\fields\Matrix))
#28 [internal function]: craft\controllers\FieldsController->actionSaveField()
#29 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#31 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-field', Array)
#32 /app/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('fields/save-fie...', Array)
#33 /app/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('fields/save-fie...', Array)
#34 /app/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#35 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#36 /app/public/index.php(31): yii\base\Application->run()
#37 {main}
Additional Information:
Array
(
    [0] => 23505
    [1] => 7
    [2] => ERROR:  duplicate key value violates unique constraint "fieldlayouttabs_pkey"
DETAIL:  Key (id)=(249) already exists.
)
```

**Comment by 3v-afranz** [comment]
Removed the database and imported a backup. It now works.

**Comment by brandonkelly** [comment]
Hm strange. Not sure how that could have happened. If you see it again, please send in a database backup and your Composer files to support@craftcms.com so we can look into it.
