### ISSUE TITLE
`craft install/check` --> "Error: Invalid language code"

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#10630]
### Description

After recently updating to Craft 3.7.34, we now get an error on the server when we try to run `install/check`.

<img src="https://user-images.githubusercontent.com/5309692/155241902-ed75f2db-8f2b-4813-9ce9-fd608b5474a8.png" width="600"/>

Strangely, this seems to only be happening on the _production_ and _staging_ sites, but works just fine in the `dev` environment.

I don't believe there's anything out of place with our single site locale...

<img src="https://user-images.githubusercontent.com/5309692/155242648-0d4a3120-b574-4477-bd8b-f4c92a961b2b.png" width="491"/>

Any idea why this error message might be popping up?

### Steps to reproduce

1. Update to 3.7.34
2. Push to remote server (?)
3. Run `./craft install/check`
4. Witness error

### Additional info

- Craft version: 3.7.34
- PHP version: 7.4.16
- Database driver & version: MySQL (MariaDB)

**Comment by brandonkelly** [comment]
Is the error getting logged in `storage/logs/console.log`? What’s the full stack trace?

**Comment by lindseydiloreto** [comment]
Here's the full stack trace...

```
2022-02-22 21:40:36 [-][-][-][error][yii\base\InvalidArgumentException] yii\base\InvalidArgumentException: Invalid language code: "www.mysite.com". in /home/ploi/www.mysite.com/vendor/yiisoft/yii2/i18n/PhpMessageSource.php:138
Stack trace:
#0 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/i18n/PhpMessageSource.php(72): yii\i18n\PhpMessageSource->getMessageFilePath()
#1 /home/ploi/www.mysite.com/vendor/craftcms/cms/src/i18n/PhpMessageSource.php(31): yii\i18n\PhpMessageSource->loadMessages()
#2 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/i18n/MessageSource.php(107): craft\i18n\PhpMessageSource->loadMessages()
#3 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/i18n/MessageSource.php(87): yii\i18n\MessageSource->translateMessage()
#4 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/i18n/I18N.php(90): yii\i18n\MessageSource->translate()
#5 /home/ploi/www.mysite.com/vendor/craftcms/cms/src/i18n/I18N.php(343): yii\i18n\I18N->translate()
#6 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/BaseYii.php(538): craft\i18n\I18N->translate()
#7 /home/ploi/www.mysite.com/vendor/supercool/buttonbox/src/ButtonBox.php(112): yii\BaseYii::t()
#8 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/base/BaseObject.php(109): supercool\buttonbox\ButtonBox->init()
#9 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct()
#10 /home/ploi/www.mysite.com/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module->__construct()
#11 [internal function]: craft\base\Plugin->__construct()
#12 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#13 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#14 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#15 /home/ploi/www.mysite.com/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject()
#16 /home/ploi/www.mysite.com/vendor/craftcms/cms/src/services/Plugins.php(948): Craft::createObject()
#17 /home/ploi/www.mysite.com/vendor/craftcms/cms/src/services/Plugins.php(232): craft\services\Plugins->createPlugin()
#18 /home/ploi/www.mysite.com/vendor/craftcms/cms/src/base/ApplicationTrait.php(1487): craft\services\Plugins->loadPlugins()
#19 /home/ploi/www.mysite.com/vendor/craftcms/cms/src/console/Application.php(48): craft\console\Application->_postInit()
#20 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#21 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#22 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct()
#23 [internal function]: yii\console\Application->__construct()
#24 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#25 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#26 /home/ploi/www.mysite.com/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#27 /home/ploi/www.mysite.com/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject()
#28 /home/ploi/www.mysite.com/vendor/craftcms/cms/bootstrap/bootstrap.php(247): Craft::createObject()
#29 /home/ploi/www.mysite.com/vendor/craftcms/cms/bootstrap/console.php(51): require('/home/ploi/www....')
#30 /home/ploi/www.mysite.com/craft(21): require('/home/ploi/www....')
```

**Comment by brandonkelly** [comment]
Nothing weird AFAICT… try searching for that `www.***` value on **Utilities** → **PHP Info**. Any environment variables set to that or something?

**Comment by lindseydiloreto** [comment]
I may have traced this back to a module... one moment, I'll report back with more info.

**Comment by lindseydiloreto** [comment]
Alright, I found the culprit... and this one was 100% my fault. I have a couple of "clever" lines of code that fake some multi-site behavior, and it looks like it finally came back to bite me in the ass. I'll wrap an `isConsoleRequest` around the offending lines of code, that should take them out of the equation.

Perhaps this is a point in favor of a [safe mode](https://github.com/craftcms/cms/issues/5106) which covers modules. 😉

Thanks for the help @brandonkelly, sorry for the false alarm! 🍺

**Comment by brandonkelly** [comment]
Glad you got it sorted!
