### ISSUE TITLE
[3.7.27.1]: yii\web\BadRequestHttpException: No file was uploaded in 

### ISSUE THREAD

**Issue by JordanMed** [craftcms/cms#10823]
### Description
Can no longer upload images on craft.

2022-03-25 12:27:19 [-][1][2i99ol1tosuh670t953in8mlr1][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: No file was uploaded in /var/www/vendor/craftcms/cms/src/controllers/AssetsController.php:275
Stack trace:
#0 [internal function]: craft\controllers\AssetsController->actionUpload()
#1 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('upload', Array)
#4 /var/www/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('assets/upload', Array)
#5 /var/www/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('assets/upload', Array)
#6 /var/www/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#7 /var/www/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/html/index.php(21): yii\base\Application->run()
#9 {main}
2022-03-25 12:27:19 [-][1][2i99ol1tosuh670t953in8mlr1][info][application] $_GET = [
    'p' => 'admin/defaultactions/assets/upload'
]

### Steps to reproduce

1. enter assets 
2. upload any image
3. receive server error 

### Craft CMS version

3.7.27.1

### PHP version

7.4.21

### Database type and version

MSQL 5.7.12

### Image driver and version

GD 7.4.21

### Installed plugins and versions

- Amazon S3 -1.3.0

**Comment by JordanMed** [comment]
This was an issue with my EC2 server
