### ISSUE TITLE
[4.x]: `Twig\Environment->getGlobals()` from a console command throws an exception

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#10879]
### Description

The [Craft Autocomplete](https://github.com/nystudio107/craft-autocomplete) module calls:
```php
        $globals = Craft::$app->view->getTwig()->getGlobals();
```

ref: https://github.com/nystudio107/craft-autocomplete/blob/develop/src/generators/AutocompleteVariableGenerator.php#L76

...to do its thing. This worked fine on Craft 3.x, and works fine on Craft 4 except if the current request is a console request. Then it throws an exception:

```
devmode-queue-1       | Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getQueryParam()'
devmode-queue-1       | 
devmode-queue-1       | in /var/www/project/cms/vendor/yiisoft/yii2/base/Component.php:300
devmode-queue-1       | 
devmode-queue-1       | Stack trace:
devmode-queue-1       | #0 /var/www/project/cms/vendor/craftcms/cms/src/helpers/Cp.php(1694): yii\base\Component->__call('getQueryParam', Array)
devmode-queue-1       | #1 /var/www/project/cms/vendor/craftcms/cms/src/web/twig/CpExtension.php(32): craft\helpers\Cp::requestedSite()
devmode-queue-1       | #2 /var/www/project/cms/vendor/twig/twig/src/ExtensionSet.php(320): craft\web\twig\CpExtension->getGlobals()
devmode-queue-1       | #3 /var/www/project/cms/vendor/twig/twig/src/Environment.php(789): Twig\ExtensionSet->getGlobals()
devmode-queue-1       | #4 /var/www/project/cms/vendor/nystudio107/craft-autocomplete/src/generators/AutocompleteVariableGenerator.php(76): Twig\Environment->getGlobals()
devmode-queue-1       | #5 /var/www/project/cms/vendor/nystudio107/craft-autocomplete/src/generators/AutocompleteVariableGenerator.php(54): nystudio107\autocomplete\generators\AutocompleteVariableGenerator::generateInternal()
devmode-queue-1       | #6 /var/www/project/cms/vendor/nystudio107/craft-autocomplete/src/Autocomplete.php(128): nystudio107\autocomplete\generators\AutocompleteVariableGenerator::generate()
devmode-queue-1       | #7 [internal function]: nystudio107\autocomplete\Autocomplete->generateAutocompleteClasses(Object(yii\base\Event))
devmode-queue-1       | #8 /var/www/project/cms/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event))
devmode-queue-1       | #9 /var/www/project/cms/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'afterLoadPlugin...', Object(yii\base\Event))
devmode-queue-1       | #10 /var/www/project/cms/vendor/craftcms/cms/src/services/Plugins.php(275): yii\base\Component->trigger('afterLoadPlugin...')
devmode-queue-1       | #11 /var/www/project/cms/vendor/craftcms/cms/src/base/ApplicationTrait.php(1471): craft\services\Plugins->loadPlugins()
devmode-queue-1       | #12 /var/www/project/cms/vendor/craftcms/cms/src/console/Application.php(52): craft\console\Application->_postInit()
devmode-queue-1       | #13 /var/www/project/cms/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
devmode-queue-1       | #14 /var/www/project/cms/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
devmode-queue-1       | #15 /var/www/project/cms/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
devmode-queue-1       | #16 [internal function]: yii\console\Application->__construct(Array)
devmode-queue-1       | #17 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
devmode-queue-1       | #18 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\console\\A...', Array, Array)
devmode-queue-1       | #19 /var/www/project/cms/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
devmode-queue-1       | #20 /var/www/project/cms/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject(Array, Array)
devmode-queue-1       | #21 /var/www/project/cms/vendor/craftcms/cms/bootstrap/bootstrap.php(239): Craft::createObject(Array)
devmode-queue-1       | #22 /var/www/project/cms/vendor/craftcms/cms/bootstrap/console.php(40): require('/var/www/projec...')
devmode-queue-1       | #23 /var/www/project/cms/craft(12): require('/var/www/projec...')
devmode-queue-1       | #24 {main}
```

The error comes from: https://github.com/craftcms/cms/blob/4.0/src/web/twig/CpExtension.php#L32 which ends up calling `getQueryParam()` in `requestedSite()`: https://github.com/craftcms/cms/blob/f2ccc7f68c8a4623d3651113a28fe59a6b3764ac/src/helpers/Cp.php#L1694

Probably a check should be done to ensure that it doesn't do this if it's a console request?

### Steps to reproduce

1. Install Craft Autocomplete https://github.com/nystudio107/craft-autocomplete
2. Run a console request after clearing caches or deleting the files in `storage/runtime/compiled_classes/`
3. See the error

### Expected behavior

It shouldn't call `getQueryParam()` in `requestedSite()` if it's a console request.

### Actual behavior

Exception is thrown

### Craft CMS version

4.0.0-beta.4

### PHP version

8.0.11

### Operating system and version

macOS Monterrey 12.3.1 (21E258)

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

- Craft Autocomplete

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
