### ISSUE TITLE
[4.x]: Can't edit/open slide out for addresses anymore after update to beta.2

### ISSUE THREAD

**Issue by Nellyaa** [craftcms/cms#10888]
### Description

I updated to Commerce 4 beta.2 on Craft CMS 4 beta.4 and editing addresses in orders or carts results in a red error message 'a server error occurred'. The console logs a 500 Bad Request. 
This worked fine before the update on Commerce beta.1 (beta.3 on Craft CMS)

### Steps to reproduce

1. Open an order
2. Click on the address to open the slide out to edit it
3. Get empty slide out with red error message at the top

### Expected behavior

I can edit addresses and save them :)

### Actual behavior

![Unbenannt-3](https://user-images.githubusercontent.com/38379317/162436406-6595cd09-ed76-43bb-bd25-687dd4ff9f34.jpg)

The following error shows up after opening the error url:

`````
An Error occurred while handling another error:
TypeError: craft\services\Addresses::getAdministrativeAreaTypeLabel(): Argument craftcms/commerce#1 ($type) must be of type string, null given, called in /var/www/vendor/craftcms/cms/src/elements/Address.php on line 155 and defined in /var/www/vendor/craftcms/cms/src/services/Addresses.php:162
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/elements/Address.php(155): craft\services\Addresses->getAdministrativeAreaTypeLabel(NULL)
craftcms/commerce#1 /var/www/vendor/craftcms/cms/src/elements/Address.php(279): craft\elements\Address::addressAttributeLabel('administrativeA...', 'DE')
craftcms/commerce#2 /var/www/vendor/craftcms/cms/src/helpers/Cp.php(1338): craft\elements\Address->getAttributeLabel('administrativeA...')
craftcms/commerce#3 /var/www/vendor/craftcms/cms/src/helpers/Cp.php(1232): craft\helpers\Cp::_subdivisionField(Object(craft\elements\Address), 'administrativeA...', false, false, Array, true)
craftcms/commerce#4 /var/www/vendor/craftcms/cms/src/fieldlayoutelements/addresses/AddressField.php(154): craft\helpers\Cp::addressFieldsHtml(Object(craft\elements\Address))
craftcms/commerce#5 /var/www/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(215): craft\fieldlayoutelements\addresses\AddressField->inputHtml(Object(craft\elements\Address), false)
craftcms/commerce#6 /var/www/vendor/craftcms/cms/src/models/FieldLayout.php(681): craft\fieldlayoutelements\BaseField->formHtml(Object(craft\elements\Address), false)
craftcms/commerce#7 /var/www/vendor/craftcms/cms/src/web/View.php(1434): craft\models\FieldLayout->craft\models\{closure}()
craftcms/commerce#8 /var/www/vendor/craftcms/cms/src/models/FieldLayout.php(680): craft\web\View->namespaceInputs(Object(Closure), NULL)
craftcms/commerce#9 /var/www/vendor/craftcms/cms/src/controllers/ElementsController.php(707): craft\models\FieldLayout->createForm(Object(craft\elements\Address), false, Array)
craftcms/commerce#10 /var/www/vendor/craftcms/cms/src/controllers/ElementsController.php(416): craft\controllers\ElementsController->_prepareEditor(Object(craft\elements\Address), true, Object(craft\web\Response), 'main-form', Object(Closure), Object(Closure), Object(Closure))
craftcms/commerce#11 [internal function]: craft\controllers\ElementsController->craft\controllers\{closure}(Object(craft\web\Response), 'main-form')
craftcms/commerce#12 /var/www/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(107): call_user_func(Object(Closure), Object(craft\web\Response), 'main-form')
craftcms/commerce#13 /var/www/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(48): craft\web\CpScreenResponseFormatter->_formatTemplate(Object(craft\web\Response), Object(craft\web\CpScreenResponseBehavior))
craftcms/commerce#14 /var/www/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\CpScreenResponseFormatter->format(Object(craft\web\Response))
craftcms/commerce#15 /var/www/vendor/craftcms/cms/src/web/Response.php(275): yii\web\Response->prepare()
craftcms/commerce#16 /var/www/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
craftcms/commerce#17 /var/www/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
craftcms/commerce#18 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(185): yii\web\ErrorHandler->renderException(Object(TypeError))
craftcms/commerce#19 /var/www/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(TypeError))
craftcms/commerce#20 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(64): yii\base\ErrorHandler->handleException(Object(TypeError))
craftcms/commerce#21 [internal function]: craft\web\ErrorHandler->handleException(Object(TypeError))
#22 {main}
Previous exception:
TypeError: craft\services\Addresses::getAdministrativeAreaTypeLabel(): Argument craftcms/commerce#1 ($type) must be of type string, null given, called in /var/www/vendor/craftcms/cms/src/elements/Address.php on line 155 and defined in /var/www/vendor/craftcms/cms/src/services/Addresses.php:162
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/elements/Address.php(155): craft\services\Addresses->getAdministrativeAreaTypeLabel(NULL)
craftcms/commerce#1 /var/www/vendor/craftcms/cms/src/elements/Address.php(279): craft\elements\Address::addressAttributeLabel('administrativeA...', 'DE')
craftcms/commerce#2 /var/www/vendor/craftcms/cms/src/helpers/Cp.php(1338): craft\elements\Address->getAttributeLabel('administrativeA...')
craftcms/commerce#3 /var/www/vendor/craftcms/cms/src/helpers/Cp.php(1232): craft\helpers\Cp::_subdivisionField(Object(craft\elements\Address), 'administrativeA...', false, false, Array, true)
craftcms/commerce#4 /var/www/vendor/craftcms/cms/src/fieldlayoutelements/addresses/AddressField.php(154): craft\helpers\Cp::addressFieldsHtml(Object(craft\elements\Address))
craftcms/commerce#5 /var/www/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(215): craft\fieldlayoutelements\addresses\AddressField->inputHtml(Object(craft\elements\Address), false)
craftcms/commerce#6 /var/www/vendor/craftcms/cms/src/models/FieldLayout.php(681): craft\fieldlayoutelements\BaseField->formHtml(Object(craft\elements\Address), false)
craftcms/commerce#7 /var/www/vendor/craftcms/cms/src/web/View.php(1434): craft\models\FieldLayout->craft\models\{closure}()
craftcms/commerce#8 /var/www/vendor/craftcms/cms/src/models/FieldLayout.php(680): craft\web\View->namespaceInputs(Object(Closure), NULL)
craftcms/commerce#9 /var/www/vendor/craftcms/cms/src/controllers/ElementsController.php(707): craft\models\FieldLayout->createForm(Object(craft\elements\Address), false, Array)
craftcms/commerce#10 /var/www/vendor/craftcms/cms/src/controllers/ElementsController.php(416): craft\controllers\ElementsController->_prepareEditor(Object(craft\elements\Address), true, Object(craft\web\Response), 'main-form', Object(Closure), Object(Closure), Object(Closure))
craftcms/commerce#11 [internal function]: craft\controllers\ElementsController->craft\controllers\{closure}(Object(craft\web\Response), 'main-form')
craftcms/commerce#12 /var/www/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(107): call_user_func(Object(Closure), Object(craft\web\Response), 'main-form')
craftcms/commerce#13 /var/www/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(48): craft\web\CpScreenResponseFormatter->_formatTemplate(Object(craft\web\Response), Object(craft\web\CpScreenResponseBehavior))
craftcms/commerce#14 /var/www/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\CpScreenResponseFormatter->format(Object(craft\web\Response))
craftcms/commerce#15 /var/www/vendor/craftcms/cms/src/web/Response.php(275): yii\web\Response->prepare()
craftcms/commerce#16 /var/www/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
craftcms/commerce#17 /var/www/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
craftcms/commerce#18 /var/www/web/index.php(12): yii\base\Application->run()
craftcms/commerce#19 {main}

### Craft CMS version

4.0.0-beta.4

### Craft Commerce version

4.0.0-beta.2

### PHP version

8.1.3

### Operating system and version

Linux 5.10.16.3-microsoft-standard-WSL2

### Database type and version

MySQL 10.7.3

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
