### ISSUE TITLE
[4.x]: {% exit %} tag doesn't behave as expected

### ISSUE THREAD

**Issue by tomdavies** [craftcms/cms#10946]
### Description

According to the docs `https://craftcms.com/docs/4.x/dev/tags.html#exit` for the `{% exit %}` tag:

> This tag will prevent the rest of the template from executing, and end the request.
> 
> You can optionally set the HTTP status code that should be included with the response. If you do, Craft will look for the appropriate error template to render. For example, {% exit 404 %} will get Craft to return the 404.twig template. If the template doesn’t exist. Craft will fallback on its own template corresponding to the status code.

However, as at `4.0.0-beta.4`, creating a template with just the body `{% exit 404 %}` results in an unhandled exception

- Doesn't appear to make a difference whether or not a custom error template has been created.
- Applies to any exit status code, not just 404

### Steps to reproduce

1. `echo "{% exit 404 %}" >> templates/test.twig`
2. Browse to `/test`

### Expected behavior

Craft 404 template is rendered / Nicely formatted Yii error is shown (`devMode`)

### Actual behavior

Unhandled error is thrown:

```
An Error occurred while handling another error:
yii\web\NotFoundHttpException in /app/storage/runtime/compiled_templates/c3/c315d7aa2c8b557b731c04f59acd4925485caadbf91ff5014e772475b625816f.php:43
Stack trace:
#0 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_9e61640150963a2ea63807fa2dd2276903224a1575e3edb54aae3d3a0e346f9f->doDisplay(Array, Array)
#1 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#2 /app/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#3 /app/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#4 /app/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#5 /app/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('_short-url', Array)
#6 /app/vendor/craftcms/cms/src/web/View.php(442): craft\web\View->renderTemplate('_short-url', Array)
#7 /app/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate('_short-url', Array, 'site')
#8 /app/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#9 /app/vendor/craftcms/cms/src/web/Response.php(275): yii\web\Response->prepare()
#10 /app/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#11 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#12 /app/vendor/craftcms/cms/src/web/ErrorHandler.php(185): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#13 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#14 /app/vendor/craftcms/cms/src/web/ErrorHandler.php(64): yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#15 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#16 {main}

Next Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template (""). in /app/templates/_short-url.twig:8
Stack trace:
#0 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#1 /app/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#2 /app/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#3 /app/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#4 /app/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('_short-url', Array)
#5 /app/vendor/craftcms/cms/src/web/View.php(442): craft\web\View->renderTemplate('_short-url', Array)
#6 /app/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate('_short-url', Array, 'site')
#7 /app/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#8 /app/vendor/craftcms/cms/src/web/Response.php(275): yii\web\Response->prepare()
#9 /app/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#10 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#11 /app/vendor/craftcms/cms/src/web/ErrorHandler.php(185): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#12 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#13 /app/vendor/craftcms/cms/src/web/ErrorHandler.php(64): yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#14 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#15 {main}
Previous exception:
yii\web\NotFoundHttpException in /app/storage/runtime/compiled_templates/c3/c315d7aa2c8b557b731c04f59acd4925485caadbf91ff5014e772475b625816f.php:43
Stack trace:
#0 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_9e61640150963a2ea63807fa2dd2276903224a1575e3edb54aae3d3a0e346f9f->doDisplay(Array, Array)
#1 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#2 /app/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#3 /app/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#4 /app/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#5 /app/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('_short-url', Array)
#6 /app/vendor/craftcms/cms/src/web/View.php(442): craft\web\View->renderTemplate('_short-url', Array)
#7 /app/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate('_short-url', Array, 'site')
#8 /app/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#9 /app/vendor/craftcms/cms/src/web/Response.php(275): yii\web\Response->prepare()
#10 /app/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#11 /app/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#12 /app/web/index.php(12): yii\base\Application->run()
#13 {main}```

### Craft CMS version

4.0.0-beta.4

### PHP version

8.0.16

### Operating system and version

Nitro

### Database type and version

_No response_

### Image driver and version

_No response_

### Installed plugins and versions

_No response_

**Comment by brandonkelly** [comment]
This is working as expected. The tag is able to end the request early by throwing an HttpException with the appropriate status code. If you have Dev Mode enabled, the error handler will catch it like it catches all exceptions, and display the full error report + stack trace.

We’ll look into updating the docs to clarify this.

**Comment by tomdavies** [comment]
@brandonkelly I _really_ think there's a bug here. Any chance you can look again? I made a reduced test case for ease of replication:

https://github.com/tomdavies/craft-4-exit-debug

Branches reflect scenarios tested:

- `main` branch is Craft 3 latest <-- exhibits expected behaviour
- `craft-4` branch is beta 4 <-- has the bug as described
- `craft-4-dev` is using `4.0.x-dev` as of today <-- has the bug as described

On both beta 4 and `4.0.x-dev`, when dev mode is *not* enabled  **I get a 500 response, not a 404**. I also don't get a "friendly" error page, just a vanilla text `An internal server error occurred.`

On C3 I get correct status code and a custom error page when dev mode is not enabled'

- debug template at `/exit-test`

This the most minimal test case I could come up with - lit. just  `nitro create` then on the `craft-4` branch upgrading by following the ["Upgrading from Craft 3" instructions](https://craftcms.com/docs/4.x/upgrade.html), and setting `ENVIRONMENT=production`

## Screencaps
<img width="941" alt="Craft-3" src="https://user-images.githubusercontent.com/136308/164450074-5a58adf2-cc07-4616-85bf-9a8ef1f48354.png">
<img width="941" alt="Craft-4-beta" src="https://user-images.githubusercontent.com/136308/164450064-214648e8-3d8d-47a6-a5f2-5e56a3b923a9.png">

**Comment by brandonkelly** [comment]
Doh, sorry. Most people just see the dev mode-styled error output and assume the `{% exit %}` tag is broken :)

Fixed this for the next release! Thanks for reporting.

**Comment by tomdavies** [comment]
No drama, thanks for sorting  🙏

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
