### ISSUE TITLE
[3.7.40.1]: Exception 'yii\di\NotInstantiableException' with message 'Failed to instantiate component or class "modules\Module".'

### ISSUE THREAD

**Issue by RyanRoberts** [craftcms/cms#11114]
### Description

After upgrading Craft on multiple sites to 3.7.40.1 I can't use various Craft CLI commands such as simply listing available comments with `./craft`.

Craft 3.7.40 works as expected.

### Steps to reproduce

1. Upgrade Craft to 3.7.40.1. 
2. Use `./craft` in the CLI. 

### Expected behavior

Output commands list.

### Actual behavior

I get…

```
./craft
Exception 'yii\di\NotInstantiableException' with message 'Failed to instantiate component or class "modules\Module".'

in /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/di/Container.php:509

Caused by: Exception 'ReflectionException' with message 'Class "modules\Module" does not exist'

in /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/di/Container.php:507

Stack trace:
#0 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct('modules\\Module')
#1 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies('modules\\Module')
#2 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('modules\\Module', Array, Array)
#3 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('modules\\Module', Array)
#4 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/base/Module.php(445): yii\BaseYii::createObject('modules\\Module', Array)
#5 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/console/controllers/HelpController.php(237): yii\base\Module->getModule('my-module')
#6 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/console/controllers/HelpController.php(172): yii\console\controllers\HelpController->getModuleCommands(Object(craft\console\Application))
#7 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/console/controllers/HelpController.php(192): yii\console\controllers\HelpController->getCommands()
#8 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/console/controllers/HelpController.php(292): yii\console\controllers\HelpController->getCommandDescriptions()
#9 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#10 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#11 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('', Array)
#14 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('', Array)
#15 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('', Array)
#16 /Users/ryan/Git/clientsite/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('', Array)
#17 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('', Array)
#18 /Users/ryan/Git/clientsite/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#19 /Users/ryan/Git/clientsite/craft(23): yii\base\Application->run()
#20 {main}
```

### Craft CMS version

3.7.40.1

### PHP version

8.1.5

### Operating system and version

macOS 12.3.1

### Database type and version

MySQL 5.7.38 5.7.38

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-32)

### Composer.json

```
{
  "require": {
    "carlcs/craft-uielementfields": "1.0.0",
    "craftcms/cms": "3.7.40.1",
    "craftcms/feed-me": "4.5.1",
    "craftcms/redactor": "2.10.8",
    "mmikkel/child-me": "1.3.0",
    "mmikkel/cp-field-inspect": "1.4.3",
    "nystudio107/craft-minify": "1.2.11",
    "nystudio107/craft-similar": "1.1.5",
    "sebastianlenz/linkfield": "1.0.25",
    "vaersaagod/dospaces": "1.1.3",
    "vaersaagod/matrixmate": "1.4.2",
    "vaersaagod/seomate": "1.1.13",
    "verbb/cloner": "1.2.2",
    "verbb/default-dashboard": "1.0.8",
    "verbb/field-manager": "2.2.4",
    "verbb/formie": "1.5.16",
    "verbb/image-resizer": "2.1.1",
    "verbb/knock-knock": "1.2.16",
    "verbb/super-table": "2.7.1",
    "vlucas/phpdotenv": "^3.4.0"
  },
  "require-dev": {
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "allow-plugins": {
      "craftcms/plugin-installer": true,
      "yiisoft/yii2-composer": true
    },
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "8.0.2"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}
```

**Comment by RyanRoberts** [comment]
Should add that I don't have any custom modules, composer.json does have:
```
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
```

**Comment by brandonkelly** [comment]
The error is saying that you’re defining a module with the class `modules\Module`, which doesn’t exist.

Check `config/app.php`. You probably have something like this in there:

```php
return [
    'modules' => [
        'my-module' => modules\Module::class,
    ],
];

**Comment by RyanRoberts** [comment]
@brandonkelly Yes that's there, but it seems to be in a default Craft install too (different in C4 of course) and in 3.7.40. Did something change in 3.7.40.1 that doesn't like this?

```
return [
    'id' => App::env('CRAFT_APP_ID') ?: 'CraftCMS',
    'modules' => [
        'my-module' => \modules\Module::class,
    ],
    //'bootstrap' => ['my-module'],
];
```

**Comment by brandonkelly** [comment]
Yes, it comes by default, but so does the actual [module class](https://github.com/craftcms/craft/blob/main/modules/Module.php).
