### ISSUE TITLE
[4.x]: Craft throws an error when clicking on GraphQL "Public Schema"

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#11218]
### Description
Craft throws an error when clicking on GraphQL "Public Schema" due to invalid token

### Steps to reproduce
1. Navigate to "GraphQL" > "Schemas"2. 
2. Click "Public Schema"3. 

<img width="506" alt="CleanShot 2022-05-13 at 16 08 59@2x" src="https://user-images.githubusercontent.com/2505643/168222055-7eb015b9-6f40-489c-9d20-8829a5ff0856.png">

### Actual behavior
Invalid Argument – [yii\base\InvalidArgumentException](http://www.yiiframework.com/doc-2.0/yii-base-invalidargumentexception.html)
Invalid access token

<img width="506" alt="CleanShot 2022-05-13 at 16 08 59@2x" src="https://user-images.githubusercontent.com/2505643/168222115-507337b4-3afe-4158-b9be-49974b9d3293.png">

### Craft CMS version

4.0.2

### PHP version

8.1.5

### Operating system and version

Linux 5.4.0

### Database type and version

MySQL 8.0.29

### Image driver and version

Imagick 3.6.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Can you find that error in `storage/logs/` and post the stack trace that follows it?

**Comment by richhayler** [comment]
```
yii\base\InvalidArgumentException: Invalid access token in /craft/vendor/craftcms/cms/src/services/Gql.php:792
Stack trace:
#0 /craft/vendor/craftcms/cms/src/controllers/GraphqlController.php(562): craft\services\Gql->getTokenByAccessToken()
#1 [internal function]: craft\controllers\GraphqlController->actionEditPublicSchema()
#2 /craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#4 /craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#5 /craft/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction()
#6 /craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#7 /craft/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest()
#8 /craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#9 /craft/web/index.php(19): yii\base\Application->run()
#10 {main}
```

**Comment by danielvanc** [comment]
I am having the same issue as well. Any updates on this?

**Comment by angrybrad** [comment]
From a fresh Craft 4 installation, I'm able to reproduce this by deleting the auto-generated public token in the `gqltokens` table.

If I also delete the public schema row in the `gqlschemas` table, then reload the schema page in the control panel, a new public schema is auto-generated, but this doesn't happen for the public token.

**Comment by brandonkelly** [comment]
I was able to reproduce when the token was present in the project config, but not in the database, and believe it’s due to a project config service change in Craft 4, where changes are only processed if the value actually _changes_. `craft\services\Gql::getPublicToken()` was detecting that a public token didn’t exist in the DB, and went to create one. But `saveToken()` has a special case for the public token, where instead of saving it to the DB directly, it writes it out to the project config, and defers the DB part to `handleChangedPublicToken()`. Except `handleChangedPublicToken()` isn’t getting called if the token value hasn’t changed.

Anyway, I’ve fixed this for the next release by moving away from storing the public token in the database altogether, as there’s really no point in doing that if the exact same config data is already in the project config.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 4.0.2"` and run `composer update`.

**Comment by danielvanc** [comment]
Thanks allot @brandonkelly I can confirm, my end that that fix worked, great stuff 👍🏼

**Comment by brandonkelly** [comment]
Craft 4.0.3 is out now with that fix.
