### ISSUE TITLE
[4.x]: Type Error with QueueLogBehavior

### ISSUE THREAD

**Issue by ostark** [craftcms/cms#11213]
### Description

It does not happen all the time. Not fully sure how to reproduce it.

```
[Error] Error: Typed property craft\\queue\\QueueLogBehavior::$_jobStartedAt must not be accessed before initialization in [...]/vendor/craftcms/cms/src/queue/QueueLogBehavior.php:109
Stack trace:
#0 [...]/vendor/craftcms/cms/src/queue/QueueLogBehavior.php(64): craft\\queue\\QueueLogBehavior->_formattedDuration()
#1 [internal function]: craft\\queue\\QueueLogBehavior->afterExec(Object(yii\\queue\\ExecEvent))
#2 [...]/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\\queue\\ExecEvent))
#3 [...]/vendor/yiisoft/yii2-queue/src/Queue.php(254): yii\\base\\Component->trigger('afterExec', Object(yii\\queue\\ExecEvent))
#4 [...]/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\\queue\\Queue->handleMessage('224', 'O:34:\"craft\\\\fee...', '300', '1')
#5 [...]/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\\queue\\cli\\Queue->execute('224', 'O:34:\"craft\\\\fee...', '300', '1', '54959')
#6 [internal function]: yii\\queue\\cli\\Command->actionExec('224', '300', '1', '54959')
```

### Steps to reproduce

1. Fill the queue with jobs
2. Listen to the queue on cli

### Potential fix in QueueLogBehavior

```
private ?float $_jobStartedAt = null;
```

### Craft CMS version

4.0.2

### PHP version

8.1

### Installed plugins and versions

- relax 
- feed-me
- ~~async-queue~~

**Comment by brandonkelly** [comment]
No idea how that would happen either, but just made the `afterExec()` method defensive about the possibility that `_jobStartedAt` isn’t set.

**Comment by brandonkelly** [comment]
Craft 4.0.3 is out now with that fix.
