### ISSUE TITLE
[4.x]: Twig variable in asset folder path causes upload button to not be displayed if folder doesn't exist

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#11254]
### Description
Upload button not displayed on file selection modal due to twig variable used in sub folder path for sub folder path that doesn't exist.

![](https://user-images.githubusercontent.com/2505643/168475202-c6f84185-1c6d-4a38-bf59-9f19b56420bd.png)

### Steps to reproduce

- Create a new filesystem
- Create a new volume that references the filesystem
- Create a new field that points to the volume
- For the field settings....
- Select "restrict assets to a single location'
- Select folder location from the dropdown
- Add `{slug}` in the subfolder path
- Ensure "Allow sub folders" and "Allow uploading directly to the field" are both unchecked
- Save and assign field to entry type in a new section
- Create a new entry and click the asset file to upload a new file
- Modal is displayed without the upload button in the bottom left

<img width="441" alt="CleanShot 2022-05-18 at 13 51 44@2x" src="https://user-images.githubusercontent.com/2505643/168953644-0406688a-d35b-4b8b-9d35-cb200bbf3ffd.png">

### Expected behavior
Event though the folder for the slug doesn't appear (as this would be created when the entry is created), the upload button should be displayed in the file selection modal.

![](https://user-images.githubusercontent.com/2505643/168475524-5da68240-4f37-40ac-a3d2-78c14817a8f0.png)

### Craft CMS version

4.0.2

### PHP version

8.1.5

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 4.0.3 is out now with that fix.

**Comment by richhayler** [comment]
Should we be able to use a globalSet variable in the folder subpath - e.g. I have a globalSet named "global" with a text field, "mytext" (which is a single word, no spaces)?

<img width="559" alt="CleanShot 2022-05-22 at 15 53 19@2x" src="https://user-images.githubusercontent.com/2505643/169680951-bf2342b1-be13-4de6-9f5f-475d4364d3dc.png">

If I use `{global.mytext}` this results in an error stating that "the field’s Asset Location setting has an invalid subpath (“{global.domain}”)".

```
craft\errors\InvalidSubpathException: Could not resolve the subpath “{global.domain}”. in /craft/vendor/craftcms/cms/src/fields/Assets.php:855
Stack trace:
#0 /craft/vendor/craftcms/cms/src/fields/Assets.php(955): craft\fields\Assets->_resolveVolumePathToFolderId()
#1 /craft/vendor/craftcms/cms/src/fields/Assets.php(495): craft\fields\Assets->_determineUploadFolderId()
#2 /craft/vendor/craftcms/cms/src/fields/Assets.php(565): craft\fields\Assets->craft\fields\{closure}()
#3 /craft/vendor/craftcms/cms/src/base/Element.php(4512): craft\fields\Assets->afterElementSave()
#4 /craft/vendor/craftcms/cms/src/services/Elements.php(2696): craft\base\Element->afterSave()
#5 /craft/vendor/craftcms/cms/src/services/Elements.php(766): craft\services\Elements->_saveElementInternal()
#6 /craft/vendor/craftcms/cms/src/controllers/GlobalsController.php(221): craft\services\Elements->saveElement()
#7 [internal function]: craft\controllers\GlobalsController->actionSaveContent()
#8 /craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#9 /craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#10 /craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#11 /craft/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction()
#12 /craft/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction()
#13 /craft/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest()
#14 /craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#15 /craft/web/index.php(19): yii\base\Application->run()
#16 {main}

Next craft\errors\InvalidSubpathException: The Logo field’s Asset Location setting has an invalid subpath (“{global.domain}”). in /craft/vendor/craftcms/cms/src/fields/Assets.php:980
Stack trace:
#0 /craft/vendor/craftcms/cms/src/fields/Assets.php(495): craft\fields\Assets->_determineUploadFolderId()
#1 /craft/vendor/craftcms/cms/src/fields/Assets.php(565): craft\fields\Assets->craft\fields\{closure}()
#2 /craft/vendor/craftcms/cms/src/base/Element.php(4512): craft\fields\Assets->afterElementSave()
#3 /craft/vendor/craftcms/cms/src/services/Elements.php(2696): craft\base\Element->afterSave()
#4 /craft/vendor/craftcms/cms/src/services/Elements.php(766): craft\services\Elements->_saveElementInternal()
#5 /craft/vendor/craftcms/cms/src/controllers/GlobalsController.php(221): craft\services\Elements->saveElement()
#6 [internal function]: craft\controllers\GlobalsController->actionSaveContent()
#7 /craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#8 /craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#9 /craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#10 /craft/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction()
#11 /craft/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction()
#12 /craft/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest()
#13 /craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#14 /craft/web/index.php(19): yii\base\Application->run()
#15 {main}
```

**Comment by brandonkelly** [comment]
You would need to use normal Twig syntax for that (`{{ global.mytext }}`). The `{shorthand}` syntax is exclusively for properties of the entry being saved (or the Matrix block if the Assets field is nested in one.)

**Comment by richhayler** [comment]
Thank you for responding and providing those tips!
