### ISSUE TITLE
[4.x]: Unable to run migrations to update from Craft 3

### ISSUE THREAD

**Issue by phillmorgan28** [craftcms/cms#11302]
### Description
I am unable to complete the upgrade process from v3 to v4

### Steps to reproduce

1. Follow upgrade steps and attempt to run migrations

### Expected behavior
Migration completes

### Actual behavior
```
*** applying m210724_180756_rename_source_cols
    > rename column sourceId in table {{%drafts}} to canonicalId ...Exception: SQLSTATE[HY000]: General error: 1553 Cannot drop index 'craft_fk_qgusywotdmifjnmxiaocykcvlqekygutisfj': needed in a foreign key constraint
The SQL being executed was: ALTER TABLE `craft_drafts` CHANGE `sourceId` `canonicalId` int(11) DEFAULT NULL (/app/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /app/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `cr...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE `cr...')
#2 /app/vendor/yiisoft/yii2/db/Migration.php(405): yii\db\Command->execute()
#3 /app/vendor/craftcms/cms/src/migrations/m210724_180756_rename_source_cols.php(18): yii\db\Migration->renameColumn('{{%drafts}}', 'sourceId', 'canonicalId')
#4 /app/vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\m210724_180756_rename_source_cols->safeUp()
#5 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /app/vendor/craftcms/cms/src/console/controllers/MigrateController.php(360): yii\console\controllers\BaseMigrateController->migrateUp('m210724_180756_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /app/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('all', Array)
#11 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('all', Array)
#12 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#13 /app/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('migrate/all', Array)
#14 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#15 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /app/craft(27): yii\base\Application->run()
#17 {main}
*** failed to apply m210724_180756_rename_source_cols (time: 0.075s)
```

### Craft CMS version

3 (latest)

### PHP version

8.1

### Operating system and version

Ubuntu

### Database type and version

10.4.17-MariaDB-1:10.4.17+maria~bionic-log - mariadb.org binary distribution

### Installed plugins and versions

-

**Comment by phillmorgan28** [comment]
Issued resolved by using alternative MySQL engine

**Comment by angrybrad** [comment]
@phillmorgan28 curious what you were using and what you swapped to?
