### ISSUE TITLE
[4.x]: Migration errors upgrading to V4

### ISSUE THREAD

**Issue by mofman** [craftcms/cms#11506]
### Description
Getting the following error while upgrading to v4.0.5.2 from v3.7.45.2

```
Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (craft_mahlatini.craft_matrixblocks_owners, CONSTRAINT craft_fk_qdwmqzhedzwtyeynyodizysofejjxmrwysyh FOREIGN KEY (ownerId) REFERENCES craft_elements (id) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO craft_matrixblocks_owners (blockId, ownerId, sortOrder)
SELECT id, ownerId, sortOrder
FROM craft_matrixblocks

Migration: craft\migrations\m220213_015220_matrixblocks_owners_table

Output:

> dropping {{%matrixblocks_owners}} if it exists ... done (time: 0.107s)
> create table {{%matrixblocks_owners}} ... done (time: 0.100s)
> add foreign key craft_fk_kamleuiaizdrpoywhujjuumclmesaxdjoesm: {{%matrixblocks_owners}} (blockId) references {{%matrixblocks}} (id) ... done (time: 0.206s)
> add foreign key craft_fk_qdwmqzhedzwtyeynyodizysofejjxmrwysyh: {{%matrixblocks_owners}} (ownerId) references {{%elements}} (id) ... done (time: 0.198s)
> execute SQL: INSERT INTO {{%matrixblocks_owners}} ([[blockId]], [[ownerId]], [[sortOrder]])
SELECT [[id]], [[ownerId]], [[sortOrder]]
FROM {{%matrixblocks}} ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (craft_mahlatini.craft_matrixblocks_owners, CONSTRAINT craft_fk_qdwmqzhedzwtyeynyodizysofejjxmrwysyh FOREIGN KEY (ownerId) REFERENCES craft_elements (id) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO craft_matrixblocks_owners (blockId, ownerId, sortOrder)
SELECT id, ownerId, sortOrder
FROM craft_matrixblocks (/Users/foo/Sites/bar/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /Users/foo/Sites/bar/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO cr...')
#1 /Users/foo/Sites/bar/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('INSERT INTO cr...')
#2 /Users/foo/Sites/bar/vendor/yiisoft/yii2/db/Migration.php(219): yii\db\Command->execute()
#3 /Users/foo/Sites/bar/vendor/craftcms/cms/src/migrations/m220213_015220_matrixblocks_owners_table.php(36): yii\db\Migration->execute('INSERT INTO {{%...')
#4 /Users/foo/Sites/bar/vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\m220213_015220_matrixblocks_owners_table->safeUp()
#5 /Users/foo/Sites/bar/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#6 /Users/foo/Sites/bar/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m220213_015220_matrixblocks_owners_table))
#7 /Users/foo/Sites/bar/vendor/craftcms/cms/src/services/Updates.php(245): craft\db\MigrationManager->up()
#8 /Users/foo/Sites/bar/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(493): craft\services\Updates->runMigrations(Array)
#9 /Users/foo/Sites/bar/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /Users/foo/Sites/bar/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/foo/Sites/bar/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /Users/foo/Sites/bar/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('migrate', Array)
#14 /Users/foo/Sites/bar/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('updater/migrate', Array)
#15 /Users/foo/Sites/bar/vendor/craftcms/cms/src/web/Application.php(712): craft\web\Application->runAction('updater/migrate')
#16 /Users/foo/Sites/bar/vendor/craftcms/cms/src/web/Application.php(238): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#17 /Users/foo/Sites/bar/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/foo/Sites/bar/public/index.php(12): yii\base\Application->run()
#19 /Users/foo/.composer/vendor/laravel/valet/server.php(234): require('/Users/foo/S...')
#20 {main}
```

### Craft CMS version

4.0.5.2

### PHP version

8.1.7

### Operating system and version

MacOS 12.4

### Database type and version

MariaDB 10.8.3

### Installed plugins and versions

-

**Comment by mofman** [comment]
Files sent.

**Comment by angrybrad** [comment]
This ended up happening because the `matrixblocks` and `supertableblocks` tables had values in the `ownerId` column that didn't exist in the `elements` table's `id` column.

No idea how it got into that state, but a manual fix for this specific case would be to run these commands, which will clean up the orphaned rows.

```
DELETE FROM craft_supertableblocks WHERE ownerId NOT IN (SELECT id FROM craft_elements);
DELETE FROM craft_matrixblocks WHERE ownerId NOT IN (SELECT id FROM craft_elements);
```

Since editing the database directly is always risky, you'll want to do some testing to verify that doesn't have any unintended side effects for your site, too.
