### ISSUE TITLE
[4.x]: Error checking for updates

### ISSUE THREAD

**Issue by realjoshharrison** [craftcms/cms#11567]
### Description

After upgrading from Craft 4.0.3, the 'checking for updates' spinner on the utilities/updates screen runs continuously with a Javascript error in the console:

```
UpdatesUtility.js:27 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'allowUpdates')
    at Array.<anonymous> (UpdatesUtility.js:27:34)
    at CP.js:1053:25
```

The issue isn't there after downgrading Craft to 4.1.1, so it seems to be an issue with the changes in 4.1.2.

### Steps to reproduce

1. Update to 4.1.2
2. Visit utilities/updates screen in admin

### Expected behavior

Checking for updates completes within a few seconds maximum

### Actual behavior

Checking for updates does not complete; JavaScript error in console.

### Craft CMS version

4.1.2

### PHP version

8.0.8

### Operating system and version

MAMP Pro, Darwin 21.5.0 (MacOS 12.4)

### Database type and version

MySQL 5.7.34

### Image driver and version

ImageMagick 6.9.6-2

### Installed plugins and versions

"craftcms/contact-form": "3.0.0",                                 
"craftcms/contact-form-honeypot": "2.0.0",                        
"craftcms/redactor": "3.0.2",

**Comment by DenyEs** [comment]
I am having the same issue. Checking for updates using terminal works fine so this must be the JS issue only.

**Comment by kevindeleon** [comment]
Having the same issue after updating to 4.1.2

**Comment by Stevenlitton** [comment]
Hi, I am having this exact issue. How can I resolve this?
