### ISSUE TITLE
[4.1.2]: 

### ISSUE THREAD

**Issue by mark-wff** [craftcms/cms#11568]
### Description
This error occours after upgrade to CraftCms 4:

```
An Error occurred while handling another error:
yii\base\ErrorException: Attempt to read property "enabled" on null in /var/www/html/vendor/yiisoft/yii2/log/Dispatcher.php:190
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(77): yii\base\ErrorHandler->handleError()
#1 /var/www/html/vendor/yiisoft/yii2/log/Dispatcher.php(190): craft\web\ErrorHandler->handleError()
#2 /var/www/html/vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch()
#3 /var/www/html/vendor/yiisoft/yii2/log/Logger.php(181): yii\log\Logger->flush()
#4 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(482): yii\log\Logger->log()
#5 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(174): yii\BaseYii::beginProfile()
#6 /var/www/html/storage/runtime/compiled_templates/b8/b801741289753edede8debad133847cd.php(36): craft\helpers\Template::beginProfile()
#7 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c4f597b10c7850a25842cb9c727cafb5->doDisplay()
#8 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#9 /var/www/html/storage/runtime/compiled_templates/92/92ef61f97a5e96fbcf3f264a82fbbf0a.php(408): Twig\Template->display()
#10 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_5f58f17eee0374768776cbe409342ed8->macro_text()
#11 /var/www/html/storage/runtime/compiled_templates/3a/3a295966121d32734f7d78e8602d543b.php(71): twig_call_macro()
#12 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c62f17b40981c415b6d464645011ff61->doDisplay()
#13 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#14 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#15 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#16 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render()
#17 /var/www/html/vendor/craftcms/cms/src/web/View.php(428): Twig\Environment->render()
#18 /var/www/html/vendor/craftcms/cms/src/fields/PlainText.php(217): craft\web\View->renderTemplate()
#19 /var/www/html/vendor/craftcms/cms/src/base/Field.php(471): craft\fields\PlainText->inputHtml()
#20 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(265): craft\base\Field->getInputHtml()
#21 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(215): craft\fieldlayoutelements\CustomField->inputHtml()
#22 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(210): craft\fieldlayoutelements\BaseField->formHtml()
#23 /var/www/html/vendor/craftcms/cms/src/web/View.php(1558): craft\fieldlayoutelements\CustomField->craft\fieldlayoutelements\{closure}()
#24 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(211): craft\web\View->namespaceInputs()
#25 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(683): craft\fieldlayoutelements\CustomField->formHtml()
#26 /var/www/html/vendor/craftcms/cms/src/web/View.php(1553): craft\models\FieldLayout->craft\models\{closure}()
#27 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(682): craft\web\View->namespaceInputs()
#28 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(1194): craft\models\FieldLayout->createForm()
#29 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(693): craft\fields\Matrix->_getBlockTypeInfoForInput()
#30 /var/www/html/vendor/craftcms/cms/src/base/Field.php(471): craft\fields\Matrix->inputHtml()
#31 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(265): craft\base\Field->getInputHtml()
#32 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(215): craft\fieldlayoutelements\CustomField->inputHtml()
#33 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(210): craft\fieldlayoutelements\BaseField->formHtml()
#34 /var/www/html/vendor/craftcms/cms/src/web/View.php(1558): craft\fieldlayoutelements\CustomField->craft\fieldlayoutelements\{closure}()
#35 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(211): craft\web\View->namespaceInputs()
#36 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(683): craft\fieldlayoutelements\CustomField->formHtml()
#37 /var/www/html/vendor/craftcms/cms/src/web/View.php(1553): craft\models\FieldLayout->craft\models\{closure}()
#38 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(682): craft\web\View->namespaceInputs()
#39 /var/www/html/vendor/spicyweb/craft-neo/src/services/Blocks.php(75): craft\models\FieldLayout->createForm()
#40 /var/www/html/vendor/spicyweb/craft-neo/src/assets/InputAsset.php(170): benf\neo\services\Blocks->renderTabs()
#41 /var/www/html/vendor/spicyweb/craft-neo/src/assets/InputAsset.php(122): benf\neo\assets\InputAsset::_getBlockTypesJsSettings()
#42 /var/www/html/vendor/spicyweb/craft-neo/src/Field.php(435): benf\neo\assets\InputAsset::createInputJs()
#43 /var/www/html/vendor/craftcms/cms/src/base/Field.php(471): benf\neo\Field->inputHtml()
#44 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(265): craft\base\Field->getInputHtml()
#45 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(215): craft\fieldlayoutelements\CustomField->inputHtml()
#46 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(210): craft\fieldlayoutelements\BaseField->formHtml()
#47 /var/www/html/vendor/craftcms/cms/src/web/View.php(1558): craft\fieldlayoutelements\CustomField->craft\fieldlayoutelements\{closure}()
#48 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(211): craft\web\View->namespaceInputs()
#49 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(683): craft\fieldlayoutelements\CustomField->formHtml()
#50 /var/www/html/vendor/craftcms/cms/src/web/View.php(1553): craft\models\FieldLayout->craft\models\{closure}()
#51 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(682): craft\web\View->namespaceInputs()
#52 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(720): craft\models\FieldLayout->createForm()
#53 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(426): craft\controllers\ElementsController->_prepareEditor()
#54 [internal function]: craft\controllers\ElementsController->craft\controllers\{closure}()
#55 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(108): call_user_func()
#56 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(48): craft\web\CpScreenResponseFormatter->_formatTemplate()
#57 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\CpScreenResponseFormatter->format()
#58 /var/www/html/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#59 /var/www/html/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#60 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#61 /var/www/html/web/index.php(12): yii\base\Application->run()
#62 {main}
```

### Steps to reproduce

1.

### Craft CMS version

4.1.2

### PHP version

8.1

### Installed plugins and versions

-
"ext-mbstring": "*",
"craftcms/cms": "^4.0.0",
"craftcms/redactor": "^3.0.2",
"diginov/craft-sentry-logger": "^4.0.1",
"fortrabbit/craft-object-storage": "^3.0.0",
"nystudio107/craft-seomatic": "^4.0.6",
"spicyweb/craft-neo": "^3.1.6",
"verbb/navigation": "^2.0.3",
"verbb/super-table": "^3.0.0-beta.6",
"vlucas/phpdotenv": "^5.4.0"

**Comment by brandonkelly** [comment]
Sweet!
