### ISSUE TITLE
[4.x]: Deactivating single section for site throws craft\errors\UnsupportedSiteException if entry has matrix blocks

### ISSUE THREAD

**Issue by BlizzardWizzard** [craftcms/cms#11669]
### Description
Craft attempts to duplicate matrix blocks of a single-section entry in an unsupported site when deactivating said site for the section.

### Steps to reproduce

1. Create a multi-site Craft installation.
2. Create a section of type single with multiple sites activated.
3. Add a matrix field with blocks to the entry type of this section.
4. Save matrix blocks in the entry of this section.
5. Deactivate a site in this section where the saved entry has matrix blocks.

### Expected behavior
The entry in the deactivated site is removed.

### Actual behavior
craft\errors\UnsupportedSiteException is thrown.

### Stack Trace
```
craft\errors\UnsupportedSiteException: Attempting to duplicate an element in an unsupported site. in /app/vendor/craftcms/cms/src/services/Elements.php:1176
Stack trace:
#0 /app/vendor/craftcms/cms/src/services/Revisions.php(162): craft\services\Elements->duplicateElement(Object(craft\elements\MatrixBlock), Array)
#1 /app/vendor/craftcms/cms/src/services/Matrix.php(995): craft\services\Revisions->createRevision(Object(craft\elements\MatrixBlock), 3, NULL, Array)
#2 /app/vendor/craftcms/cms/src/fields/Matrix.php(1050): craft\services\Matrix->createRevisionBlocks(Object(craft\fields\Matrix), Object(craft\elements\Entry), Object(craft\elements\Entry))
#3 /app/vendor/craftcms/cms/src/base/Element.php(4635): craft\fields\Matrix->afterElementPropagate(Object(craft\elements\Entry), true)
#4 /app/vendor/craftcms/cms/src/elements/Entry.php(1991): craft\base\Element->afterPropagate(true)
#5 /app/vendor/craftcms/cms/src/services/Elements.php(1331): craft\elements\Entry->afterPropagate(true)
#6 /app/vendor/craftcms/cms/src/services/Revisions.php(162): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#7 /app/vendor/craftcms/cms/src/elements/Entry.php(1995): craft\services\Revisions->createRevision(Object(craft\elements\Entry), 3, NULL)
#8 /app/vendor/craftcms/cms/src/services/Elements.php(2732): craft\elements\Entry->afterPropagate(false)
#9 /app/vendor/craftcms/cms/src/services/Elements.php(765): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), false, true, true)
#10 /app/vendor/craftcms/cms/src/services/Sections.php(1509): craft\services\Elements->saveElement(Object(craft\elements\Entry), false)
#11 /app/vendor/craftcms/cms/src/services/Sections.php(767): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section), Array)
#12 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1676): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#13 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1125): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#14 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#15 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#16 /app/vendor/craftcms/cms/src/models/ProjectConfigData.php(82): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#17 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(515): craft\models\ProjectConfigData->commitChanges(Array, Array, 'sections.813638...', true, 'Save section \xE2\x80...', true)
#18 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(475): craft\services\ProjectConfig->_setInternal('sections.813638...', Array, 'Save section \xE2\x80...', true, false)
#19 /app/vendor/craftcms/cms/src/services/Sections.php(493): craft\services\ProjectConfig->set('sections.813638...', Array, 'Save section \xE2\x80...')
#20 /app/vendor/craftcms/cms/src/controllers/SectionsController.php(176): craft\services\Sections->saveSection(Object(craft\models\Section))
#21 [internal function]: craft\controllers\SectionsController->actionSaveSection()
#22 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#24 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-section', Array)
#25 /app/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('sections/save-s...', Array)
#26 /app/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('sections/save-s...', Array)
#27 /app/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#28 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#29 /app/web/index.php(26): yii\base\Application->run()
#30 {main}
```

### Craft CMS version

4.1.4.1

### PHP version

8.1.0

### Operating system and version

Linux 5.15.5-0-virt

### Database type and version

MySQL 5.5.5

### Image driver and version

Imagick 3.5.1 (ImageMagick 7.0.11-13)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I’m unable to reproduce this. Can you please send your Composer files and a database backup to support@craftcms.com, so we can try to reproduce with your own site?

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.2.1 is out with that fix.
