### ISSUE TITLE
[3.x]: Template not found error in logs and runtime error in console

### ISSUE THREAD

**Issue by danfathom** [craftcms/cms#11928]
### Description
On one of our sites, we keep getting the following in our storage/logs/web-404s.log:

2022-09-13 16:41:49 [-][-][-][error][yii\web\HttpException:404] yii\web\NotFoundHttpException: Template not found: 

AutoDiscover/autodiscover.xml in /home/websitename/vendor/craftcms/cms/src/controllers/TemplatesController.php:92
Stack trace:
#0 [internal function]: craft\controllers\TemplatesController->actionRender('AutoDiscover/au...', Array)
#1 /home/telent/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /home/telent/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#3 /home/telent/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('render', Array)
#4 /home/telent/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#5 /home/telent/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('templates/rende...', Array)
#6 /home/telent/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#7 /home/telent/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /home/telent/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /home/telent/public_html/index.php(21): yii\base\Application->run()
#10 {main}
2022-09-13 16:41:49 [-][-][-][info][application] $_GET = [
    'p' => 'AutoDiscover/autodiscover.xml'
]

I know this means a template of autodiscover.xml is missing, but we can't work out what autodiscover.xml should be, and what's trying to crawl it?

In addition to this, on every page of our website we get a runtime console error which shows the following:
![Screen Shot 2022-09-13 at 16 46 29](https://user-images.githubusercontent.com/92588022/189947251-6997b41e-32db-4a43-8ef9-1a7e7a6f49c0.png)

All pages on the site load with no issues, but we always get that console error for the current page.

If you have any idea please let me know.

Many thanks,

### Craft CMS version

Craft Solo 3.5.19.1

### PHP version

7.4.30

### Operating system and version

Linux 3.10.0-1160.53.1.el7.x86_64

### Database type and version

MySQL 5.7.39

### Image driver and version

GD 7.4.30

### Installed plugins and versions

-
Agent - 1.1.8
Breadcrumb - 1.1.0
Environment Label - 3.2.0
MobileDetect - 1.0.2
Redactor - 2.8.5
Redactor Custom Styles - 3.0.4
SEO - 3.6.2
SS Twitter Feed - 1.0.6
Super Table - 2.6.6
Typed link field - 1.0.25
Wheel Form - 2.5.6

**Comment by brianjhanson** [comment]
Those `AutoDiscover/autodiscover.xml` requests are more than likely being sent by an Outlook server trying to get some email configuration. [Here's a bit more information about that service](https://docs.microsoft.com/en-us/Exchange/architecture/client-access/autodiscover?view=exchserver-2019)

Can you post a new issue for the runtime console error with some more information? I don't think the two issues are related, but I'm always up for a surprise.

**Comment by brandonkelly** [comment]
Yeah there’s going to be a lot of junk in `web-404s.log`, from various bots/apps looking for URLs that don’t exist. In fact we don’t even log them anymore in Craft 4 since it’s nothing to worry about.
