### ISSUE TITLE
[3.x]: Exception: DateTime::__construct(): Failed to parse time string since 3.7.55 update

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#11980]
### Description
Updating from `3.7.53.1` to `3.7.55` is causing a breaking error for me:

```
Exception: DateTime::__construct(): Failed to parse time string (2020 – 07 – 18T14:00:00) at position 4 (�): Unexpected character in vendor/twig/twig/src/Extension/CoreExtension.php:546
Stack trace:
#0 vendor/twig/twig/src/Extension/CoreExtension.php(546): DateTime->__construct('2020\xE2\x80\x89\xE2\x80\x93\xE2\x80\x8907...', Object(DateTimeZone))
#1 vendor/twig/twig/src/Extension/CoreExtension.php(464): twig_date_converter(Object(craft\web\twig\Environment), '2020\xE2\x80\x89\xE2\x80\x93\xE2\x80\x8907...', Object(DateTimeZone))
#2 vendor/craftcms/cms/src/web/twig/Extension.php(905): twig_date_format_filter(Object(craft\web\twig\Environment), '2020\xE2\x80\x89\xE2\x80\x93\xE2\x80\x8907...', 'Y-m-d\\TH:i:sP', NULL)
#3 storage/runtime/compiled_templates/ca/caf460ddfc7c25a6541b472eadc89e9eb887dcc23ae1bef5956c3eb1a9f5d723.php(96): craft\web\twig\Extension->atomFilter(Object(craft\web\twig\Environment), '2020\xE2\x80\x89\xE2\x80\x93\xE2\x80\x8907...')
#4 vendor/twig/twig/src/Template.php(405): __TwigTemplate_1d3d315eb92a88b50920a4576dd5054ec4fda2f7869396f915c2639eea97b471->doDisplay(Array, Array)
#5 vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#6 storage/runtime/compiled_templates/c3/c34d819f6d8e62c4b853d30daf1c2a99cffbfd2352e9c34edca11022f81263e7.php(155): Twig\Template->display(Array)
#7 vendor/twig/twig/src/Template.php(182): __TwigTemplate_c527d625ea9734a4629d40538eb0c91f6a98c1cb36db63ed64054c559466f99b->block_content(Array, Array)
#8 storage/runtime/compiled_templates/7b/7b61410869e4d6c8b3c192b20b9e094605577ca97c6993147fef20f5614d873f.php(197): Twig\Template->displayBlock('content', Array, Array)
#9 vendor/twig/twig/src/Template.php(182): __TwigTemplate_c5f2b12f54a328b19516a57b45a054e2fa543c305e4906036affc746e9a5bdf9->block_body(Array, Array)
#10 storage/runtime/compiled_templates/e3/e3254b59643c8ed89625d6c66b04bcda5e068dd4c8252174359448427579866c.php(192): Twig\Template->displayBlock('body', Array, Array)
#11 vendor/twig/twig/src/Template.php(405): __TwigTemplate_6837eb9783d5fc4b0adb045b6e0f15f44587b556575bf21a47ec8d1a0765a4c1->doDisplay(Array, Array)
#12 vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#13 storage/runtime/compiled_templates/7b/7b61410869e4d6c8b3c192b20b9e094605577ca97c6993147fef20f5614d873f.php(63): Twig\Template->display(Array, Array)
#14 vendor/twig/twig/src/Template.php(405): __TwigTemplate_c5f2b12f54a328b19516a57b45a054e2fa543c305e4906036affc746e9a5bdf9->doDisplay(Array, Array)
#15 vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#16 storage/runtime/compiled_templates/c3/c34d819f6d8e62c4b853d30daf1c2a99cffbfd2352e9c34edca11022f81263e7.php(44): Twig\Template->display(Array, Array)
#17 vendor/twig/twig/src/Template.php(405): __TwigTemplate_c527d625ea9734a4629d40538eb0c91f6a98c1cb36db63ed64054c559466f99b->doDisplay(Array, Array)
#18 vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#19 vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#20 vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#21 vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#22 vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('_homepage/index', Array)
#23 vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('_homepage/index', Array)
#24 vendor/craftcms/cms/src/web/Controller.php(205): craft\web\View->renderPageTemplate('_homepage/index', Array, 'site')
#25 vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate('_homepage/index', Array)
#26 [internal function]: craft\controllers\TemplatesController->actionRender('_homepage/index', Array)
#27 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#28 vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#29 vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#30 vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction('templates/rende...', Array)
#31 vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#32 vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest(Object(craft\web\Request))
#33 vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#34 htdocs/index.php(21): yii\base\Application->run()
#35 {main}
```

It looks like the date (example: `2020 – 07 – 18T14:00:00`) can't be parsed anymore, while it was working on previous versions of Craft.

### Steps to reproduce

1. Create a date by combining date & time : `{{ '{date}T{hour}' | t({ date: entry.calendar[0].date | date('Y-m-d'), hour: entry.calendar[0].hour | date('H:i:s') }) | atom }}`

### Expected behavior

No error.

### Actual behavior

This is a blocking error. It looks like it's adding unwanted characters or spaces inside the written date. Adding a `l spaceless` filter don't fix this.

### Craft CMS version

3.7.55

### PHP version

7.4.25

### Database type and version

MySQL 5.7.34

### Image driver and version

Imagick 3.4.4 (ImageMagick 6.9.6-2)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that. Craft 3.7.55.1 and 4.2.5.1 are out with a fix.

**Comment by romainpoirier** [comment]
Thank you for fixing this. But I'm facing another issue while using the `| t` filter with dates.

This was working previously:
```
{{ '{date} {hour}' | t({
	date: date | date('Y-m-d'),
	hour: hour | date('H:i:sP')
}) | atom }}
```

But since the last update, this doesn't catch anymore the timezone (as defined in `general/config.php`, `timezone` setting).

**Comment by brandonkelly** [comment]
@romainpoirier At this point there shouldn’t be any differences to the `|t` filter in 3.7.55.1+ versus pre-3.7.55 releases. If you change the `craftcms/cms` requirement back to `3.7.54` and `composer update`, your template works as expected?

If so, please show me the expected output and how it’s different in 3.7.55.1+.

**Comment by romainpoirier** [comment]
Sorry, it's been a while since my last message. I don't remember where it was, so it should be fixed now. I'll let you know if the problem still occurs after the latest Craft updates. Thank you!
