### ISSUE TITLE
[4.x]: User is not authorized to perform this action while has correct permissions

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#12444]
### Description + Steps to reproduce
Users are registered by admins in the CP only, never on front-end.
These users have a dedicated _User Group_ to a Channel where currently **everything is enabled** (every checkbox is checked).
The _Default Status_ of these entries in this channel are set on _Enabled_.
On front-end, there's an Entry form based on [this official tutorial](https://craftcms.com/knowledge-base/entry-form).
On save, the user get this error, and the Entry is not saved: `User is not authorized to perform this action.`

Here's the stack trace which does not tell explicitly what's wrong:
```
2022-12-13 11:39:32 [web.ERROR] [yii\web\HttpException:403] yii\web\ForbiddenHttpException: User is not authorized to perform this action. in /vendor/craftcms/cms/src/web/Controller.php:419
Stack trace:
#0 /vendor/craftcms/cms/src/controllers/BaseEntriesController.php(60): craft\web\Controller->requirePermission('editSite:264e3c...')
#1 /vendor/craftcms/cms/src/controllers/EntriesController.php(232): craft\controllers\BaseEntriesController->enforceSitePermission(Object(craft\models\Site))
#2 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#3 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#5 /vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-entry', Array)
#6 /vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('entries/save-en...', Array)
#7 /vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('entries/save-en...', Array)
#8 /vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /htdocs/index.php(12): yii\base\Application->run()
#11 {main} {"memory":25536656,"exception":"[object] (yii\\web\\ForbiddenHttpException(code: 0): User is not authorized to perform this action. at /vendor/craftcms/cms/src/web/Controller.php:419)"} 
2022-12-13 11:39:32 [web.INFO] [application] Request context:
$_GET = []

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'entries/save-entry'
    'sectionId' => '10'
    'enabled' => '1'
    'title' => 'Topic title'
    'fields' => [
        'body' => '<p>Description of what it will be used for<a data-re-name=\"format\" data-dropdown=\"true\" href=\"https://webiste.local/#\" alt=\"Format\" rel=\"format\" role=\"button\" aria-label=\"Format\" tabindex=\"-1\" data-re-icon=\"true\"><br></a></p>'
    ]
]
```

### Craft CMS version

4.3.4

### PHP version

8.1.0

### Installed plugins and versions

-

**Comment by romainpoirier** [comment]
Finally found what was missing: the `Sites` permissions were not checked. You can close this ticket.

**Comment by i-just** [comment]
Glad you got it sorted :)
