### ISSUE TITLE
[4.x]: Uncaught TypeError: Craft.MatrixInput is not a constructor

### ISSUE THREAD

**Issue by GMConsultant** [craftcms/cms#12468]
### Description
When I create a new entry with an entry type that contains a matrix field (the matrix field contains a Redactor field), I get this error in the console:

```
Uncaught TypeError: Craft.MatrixInput is not a constructor
    at <anonymous>:1:19
    at m (jquery.js?v=1671206130:2:867)
    at Pe (jquery.js?v=1671206130:2:48866)
    at w.fn.init.append (jquery.js?v=1671206130:2:50070)
    at Object.appendBodyHtml (Craft.js:1844:18)
    at ElementEditor.js:1470:19
en.js?v=1671206220:1 Uncaught ReferenceError: Redactor is not defined
    at en.js?v=1671206220:1:1
CraftAssetImages.js:277 Uncaught ReferenceError: Redactor is not defined
    at CraftAssetImages.js:277:4
    at CraftAssetImages.js?v=1671206220:1:3658
CraftAssetFiles.js:45 Uncaught ReferenceError: Redactor is not defined
    at CraftAssetFiles.js:45:4
    at CraftAssetFiles.js?v=1671206220:1:787
CraftAssetImageEditor.js:64 Uncaught ReferenceError: Redactor is not defined
    at CraftAssetImageEditor.js:64:4
    at CraftAssetImageEditor.js?v=1671206220:1:828
CraftElementLinks.js:169 Uncaught ReferenceError: Redactor is not defined
    at CraftElementLinks.js:169:4
    at CraftElementLinks.js?v=1671206220:1:3651
RedactorOverrides.js:4 Uncaught ReferenceError: $R is not defined
    at RedactorOverrides.js:4:24
    at RedactorOverrides.js?v=1671206220:1:8757
```

**the oddity is that if i exit and save as draft and edit it, the error doesn't show up and the entry is saved normally.**

_NB: in php.ini the max_input_vars is 2000_

### Craft CMS version

Craft CMS 4.3.5 PRO

### PHP version

8.1.13

### Operating system and version

Linux 3.10.0-1160.80.1.el7.x86_64

### Database type and version

MySQL 10.11.1

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.12-69)

### Installed plugins and versions

- Amazon S3	2.0.1
- Contact Form	3.0.0
- Contact Form Extensions	4.2.2
- Logs	4.0.0
- Redactor	3.0.2
- Simple Mailchimp	2.0.0

**Comment by GMConsultant** [comment]
After a careful check I realized an incorrect configuration born from the use of the Control Panel in a specific domain. The highlighted error is gone, the only thing I saw in the console is that the **js.map files are NOT found 404 errors**, but this does NOT affect the functioning.
