### ISSUE TITLE
[3.x] PHP Fatal error:  Uncaught TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#12594]
### Description
I get this error when running any `./craft` command (example: `./craft help`) :
```
PHP Fatal error:  Uncaught TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in /craft on line 16 and defined in /vendor/vlucas/phpdotenv/src/Dotenv.php:83
Stack trace:
#0 /craft(16): Dotenv\Dotenv::create('/Users/romainpo...')
#1 {main}
  thrown in /vendor/vlucas/phpdotenv/src/Dotenv.php on line 83

Fatal error: Uncaught TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in /craft on line 16 and defined in /vendor/vlucas/phpdotenv/src/Dotenv.php:83
Stack trace:
#0 /craft(16): Dotenv\Dotenv::create('/Users/romainpo...')
#1 {main}
  thrown in /vendor/vlucas/phpdotenv/src/Dotenv.php on line 83
```

`rm -R vendor/` + `rm composer.lock` + `composer install` does not fix this.

my `htdocs/index.php` file:
```
<?php
/**
 * Craft web bootstrap file
 */

// Set path constants
define('CRAFT_BASE_PATH', dirname(__DIR__));
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// Load dotenv?
if (class_exists('Dotenv\Dotenv') && file_exists(CRAFT_BASE_PATH.'/.env')) {
    Dotenv\Dotenv::create(CRAFT_BASE_PATH)->load();
}

// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();
```
my `composer.json` require list:
```
"require": {
  "aelvan/imager": "2.4.0",
  "aelvan/mailchimp-subscribe": "3.0.3",
  "barrelstrength/sprout-encode-email": "^2.0",
  "craftcms/cms": "3.7.59",
  "craftcms/mandrill": "1.3.1",
  "craftcms/redactor": "2.10.11",
  "doublesecretagency/craft-cpcss": "2.4.0",
  "miranj/craft-obfuscator": "^1.1",
  "mmikkel/cp-field-inspect": "1.4.4",
  "mmikkel/retcon": "2.6.0",
  "nystudio107/craft-minify": "1.2.11",
  "nystudio107/craft-typogrify": "1.1.20",
  "putyourlightson/craft-dashboard-begone": "1.0.1",
  "spicyweb/craft-embedded-assets": "2.11.3",
  "studioespresso/craft-dumper": "2.0.0",
  "verbb/expanded-singles": "1.2.0",
  "verbb/super-table": "2.7.4",
  "vlucas/phpdotenv": "^5.4.0"
}
```

### Steps to reproduce

1. Run `./craft help`
2. Get the error

### Craft CMS version

3.7.59

### PHP version

7.4

### Installed plugins and versions

-

**Comment by romainpoirier** [comment]
I found out that downgrading to `"vlucas/phpdotenv": "3.4.0"` can fix it.

I don't get the previous error anymore on a `./craft help`, but I know thet this notice:
```
% ./craft help
PHP Deprecated:  Return type of Dotenv\Environment\AbstractVariables::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 162

Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 162
PHP Deprecated:  Return type of Dotenv\Environment\AbstractVariables::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 170

Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 170
PHP Deprecated:  Return type of Dotenv\Environment\AbstractVariables::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 178

Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 178
PHP Deprecated:  Return type of Dotenv\Environment\AbstractVariables::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 186

Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 186

    Craft can’t connect to the database. Check your connection settings.


This is Yii version 2.0.45.

The following commands are available:
...
```

I can't run other commands like `./craft resave/entries`, I get this error:
```
% ./craft resave/entries
PHP Deprecated:  Return type of Dotenv\Environment\AbstractVariables::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 162

Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 162
PHP Deprecated:  Return type of Dotenv\Environment\AbstractVariables::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 170

Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 170
PHP Deprecated:  Return type of Dotenv\Environment\AbstractVariables::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 178

Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 178
PHP Deprecated:  Return type of Dotenv\Environment\AbstractVariables::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 186

Deprecated: Return type of Dotenv\Environment\AbstractVariables::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/vlucas/phpdotenv/src/Environment/AbstractVariables.php on line 186

    Craft can’t connect to the database. Check your connection settings.

Exception 'craft\errors\DbConnectException' with message 'Craft CMS can’t connect to the database with the credentials in config/db.php.'

in /vendor/craftcms/cms/src/db/Connection.php:173

Caused by: Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No such file or directory'

in /vendor/yiisoft/yii2/db/Connection.php:647

Error Info:
Array
(
    [0] => HY000
    [1] => 2002
    [2] => No such file or directory
)

Caused by: Exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory'

in /vendor/yiisoft/yii2/db/Connection.php:721

Stack trace:
#0 /vendor/yiisoft/yii2/db/Connection.php(721): PDO->__construct('mysql:host=loca...', 'root', Object(SensitiveParameterValue), Array)
#1 /vendor/yiisoft/yii2/db/Connection.php(636): yii\db\Connection->createPdoInstance()
#2 /vendor/craftcms/cms/src/db/Connection.php(152): yii\db\Connection->open()
#3 /vendor/yiisoft/yii2/db/Connection.php(1066): craft\db\Connection->open()
#4 /vendor/yiisoft/yii2/db/Connection.php(1053): yii\db\Connection->getMasterPdo()
#5 /vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(406): yii\db\Connection->getSlavePdo()
#6 /vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(430): yii\db\mysql\QueryBuilder->supportsFractionalSeconds()
#7 /vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(59): yii\db\mysql\QueryBuilder->defaultTimeTypeMap()
#8 /vendor/craftcms/cms/src/db/mysql/QueryBuilder.php(27): yii\db\mysql\QueryBuilder->init()
#9 /vendor/yiisoft/yii2/base/BaseObject.php(109): craft\db\mysql\QueryBuilder->init()
#10 /vendor/yiisoft/yii2/db/QueryBuilder.php(116): yii\base\BaseObject->__construct(Array)
#11 /vendor/craftcms/cms/src/db/mysql/Schema.php(74): yii\db\QueryBuilder->__construct(Object(craft\db\Connection), Array)
#12 /vendor/yiisoft/yii2/db/Schema.php(247): craft\db\mysql\Schema->createQueryBuilder()
#13 /vendor/yiisoft/yii2/db/Connection.php(883): yii\db\Schema->getQueryBuilder()
#14 /vendor/yiisoft/yii2/db/Query.php(157): yii\db\Connection->getQueryBuilder()
#15 /vendor/yiisoft/yii2/db/Query.php(481): yii\db\Query->createCommand(Object(craft\db\Connection))
#16 /vendor/craftcms/cms/src/db/Query.php(258): yii\db\Query->queryScalar('COUNT(*)', NULL)
#17 /vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar('COUNT(*)', NULL)
#18 /vendor/craftcms/cms/src/elements/db/ElementQuery.php(1634): yii\db\Query->count('*', NULL)
#19 /vendor/craftcms/cms/src/console/controllers/ResaveController.php(459): craft\elements\db\ElementQuery->count()
#20 /vendor/craftcms/cms/src/console/controllers/ResaveController.php(382): craft\console\controllers\ResaveController->_resaveElements(Object(craft\elements\db\EntryQuery))
#21 /vendor/craftcms/cms/src/console/controllers/ResaveController.php(305): craft\console\controllers\ResaveController->resaveElements('craft\\elements\\...', Array)
#22 [internal function]: craft\console\controllers\ResaveController->actionEntries()
#23 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#25 /vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('entries', Array)
#26 /vendor/craftcms/cms/src/console/Controller.php(221): yii\console\Controller->runAction('entries', Array)
#27 /vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('entries', Array)
#28 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('resave/entries', Array)
#29 /vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('resave/entries', Array)
#30 /vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('resave/entries', Array)
#31 /vendor/craftcms/cms/src/console/Application.php(118): yii\console\Application->handleRequest(Object(craft\console\Request))
#32 /vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#33 /craft(22): yii\base\Application->run()
#34 {main}
```

However, I can confirm that the DB connection is correctly set, as I can connect and browse the admin (`/admin`).

**Comment by i-just** [comment]
Hi, thanks for getting in touch. 

It looks like your `index.php` file needs to be updated to this: https://github.com/craftcms/craft/blob/5.x/web/index.php.

And also, it's worth checking whether your `bootstrap.php` file looks like here: https://github.com/craftcms/craft/blob/5.x/bootstrap.php.

The above should work with `"vlucas/phpdotenv": "^5.4.0"`

I'm going to go ahead and close this now, but if you have any further issues with this, please feel free to reply.

**Comment by romainpoirier** [comment]
Thank you:

- I have updated my `index.php`.
- I didn't have the `bootstrap.php` file, so I created it
- I have kept `"vlucas/phpdotenv": "^5.4.0"` + run `composer update` and still get the error detailed in my first message
- Going back to `"vlucas/phpdotenv": "3.4.0"` give me the same result as described in my second message

So unfortunately, I see no change.

**Comment by i-just** [comment]
Right, one more file to check would be: https://github.com/craftcms/craft/blob/5.x/craft

**Comment by romainpoirier** [comment]
With `"vlucas/phpdotenv": "3.4.0"`, I have changed the `craft` file to this, but I unfortunately now get this error:

```
./craft help
PHP Fatal error:  Uncaught Error: Call to undefined method Dotenv\Dotenv::createUnsafeMutable() in /bootstrap.php:17
Stack trace:
#0 /craft(8): require()
#1 {main}
  thrown in /bootstrap.php on line 17

Fatal error: Uncaught Error: Call to undefined method Dotenv\Dotenv::createUnsafeMutable() in /bootstrap.php:17
Stack trace:
#0 /craft(8): require()
#1 {main}
  thrown in /bootstrap.php on line 17
```

**Comment by i-just** [comment]
Sorry, I should have been clear that I still wanted you to stay on the more up-to-date version of dotenv. Can you please try that with `"vlucas/phpdotenv": "^5.4.0"`?

**Comment by romainpoirier** [comment]
Thank you, now the error is gone.

I can make `./craft help` working, but I get this notice:
`Craft can’t connect to the database. Check your connection settings.`

The same happens for other commands, that are not ran because of this error (like `./craft resave/entries`).
I can still confirm that the DB connection is correctly set, as I can connect and browse the admin (`/admin`).

**Comment by i-just** [comment]
Great news, thanks for confirming.

So the second error (not being able to connect to the database from the command line) will be related to your development environment. Can you connect to the database via the terminal using the credentials from your `config/db.php` file: `mysql -h <your host> -u <your db name>`?

**Comment by romainpoirier** [comment]
I wasn't able using MAMP Pro (6.7):
`zsh: command not found: mysql`
But finally found out that something has changed in my config, and the prefix `php` must be added before the `craft` command (example: `php ./craft resave/entries`).
Thank you!

**Comment by i-just** [comment]
Perfect. Glad you got it sorted!

**Comment by celexus** [comment]
> Hi, thanks for getting in touch.
> 
> It looks like your `index.php` file needs to be updated to this: https://github.com/craftcms/craft/blob/v3/web/index.php.
> 
> And also, it's worth checking whether your `bootstrap.php` file looks like here: https://github.com/craftcms/craft/blob/v3/bootstrap.php.
> 
> The above should work with `"vlucas/phpdotenv": "^5.4.0"`
> 
> I'm going to go ahead and close this now, but if you have any further issues with this, please feel free to reply.

I'm experiencing the same issue but the links provided to index.php & bootstrap.php throw a 404.

Can you provide me with valid links to these files for Craft CMS 3, please: 

https://github.com/craftcms/craft/blob/v3/web/index.php.
https://github.com/craftcms/craft/blob/v3/bootstrap.php.

**Comment by i-just** [comment]
@celexus, the following links should work:
https://github.com/craftcms/craft/blob/5.x/web/index.php
https://github.com/craftcms/craft/blob/5.x/bootstrap.php
https://github.com/craftcms/craft/blob/5.x/craft
