### ISSUE TITLE
[4.3.8.1]: Issue with eager loading

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#12651]
### Description

I upgraded from to `4.3.7.1` to `4.3.8.1` and some queries with eager loading, that worked fine until now, cause errors.

As an example, this query...

`{% for link in craft.entries.section('mainNav').level('1').with(['targetPage', 'targetCat']).collect() %}`

..errors out with this stack trace:

```
yii\base\ErrorException: Undefined array key 0 in /var/www/html/vendor/craftcms/cms/src/fields/BaseRelationField.php:726
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/var/www/html/v...', 726)
#1 /var/www/html/vendor/craftcms/cms/src/fields/BaseRelationField.php(726): craft\web\ErrorHandler->handleError(2, 'Undefined array...', '/var/www/html/v...', 726)
#2 /var/www/html/vendor/craftcms/cms/src/base/Element.php(1275): craft\fields\BaseRelationField->getEagerLoadingMap(Array)
#3 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(597): craft\base\Element::eagerLoadingMap(Array, 'targetPage')
#4 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2553): craft\elements\Entry::eagerLoadingMap(Array, 'targetPage')
#5 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2517): craft\services\Elements->_eagerLoadElementsInternal('craft\\elements\\...', Array, Array)
#6 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2978): craft\services\Elements->eagerLoadElements('craft\\elements\\...', Array, Array)
#7 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1453): craft\elements\db\ElementQuery->_createElements(Array)
#8 /var/www/html/vendor/yiisoft/yii2/db/Query.php(251): craft\elements\db\ElementQuery->populate(Array)
#9 /var/www/html/vendor/craftcms/cms/src/db/Query.php(248): yii\db\Query->all(NULL)
#10 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1492): craft\db\Query->all(NULL)
#11 /var/www/html/vendor/craftcms/cms/src/db/Query.php(264): craft\elements\db\ElementQuery->all(NULL)
#12 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1607): craft\db\Query->collect()
#13 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(110): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'collect', Array, 'method', false, false)
#14 /var/www/html/storage/runtime/compiled_templates/c1/c1a00f98f74fa99e4cc628aca6408a83.php(202): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'collect', Array, 'method')
#15 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c2d04aa4bf21db0a49cc048f28451635->doDisplay(Array, Array)
#16 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /var/www/html/storage/runtime/compiled_templates/7c/7c82822d905dfbf7256a7d01982c01c6.php(47): Twig\Template->display(Array, Array)
#18 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_7164abde37974c471172f10b2b821cd9->doDisplay(Array, Array)
#19 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#21 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#22 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#23 /var/www/html/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('index', Array)
#24 /var/www/html/vendor/craftcms/cms/src/web/View.php(504): craft\web\View->renderTemplate('index', Array)
#25 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate('index', Array, 'site')
#26 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#27 /var/www/html/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#28 /var/www/html/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#29 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#30 /var/www/html/web/index.php(22): yii\base\Application->run()
#31 {main}
```
Not all eager loading causes errors, it seems depended on the fields that I'm trying to eager load. In the above query if I take out 'targetPage' there is no error, although both `targetPage` and `targetCat` are relational fields.

### Steps to reproduce

Just try to eager load stuff. Sorry, I haven't had time to investigate further. Hope the stack trace above helps to pinpoint the issue.

### Expected behavior

Page loads with no errors, as in previous versions of Craft.

### Actual behavior

Server error.

### Craft CMS version

4.3.8.1

### PHP version

8.1

### Installed plugins and versions

-

**Comment by thupsi** [comment]
Ooops, seems to be a duplicate of this issue: https://github.com/craftcms/cms/issues/12648.
