### ISSUE TITLE
[4.x]: Slowness and plugin store unavailable : ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by wuhhh** [craftcms/cms#12669]
### Description

I'm on a fresh Craft 4 install that I just moved to DDEV. I followed the install instructions in the Craft docs and spinning up / browsing for the most part is fine. The issue I have is that every so often a request (e.g. navigating to entries or some other page in the back end) grinds everything to a halt, taking longer than a minute to complete. I have no idea what's causing this - I've installed a few plugins (below), otherwise everything is as it was OOTB. 

I am attaching some screen shots of logs and errors in case it helps. A possibly related issue is that I cannot load the plugin store from my local environment - perhaps there is a general issue communicating with the mothership that's causing these slow response times ocassionally? There's an accompanying error in console of `ERR_CERT_COMMON_NAME_INVALID`

I've just realised the 'Updates' page also does not load, endless spinner there.

<img width="1434" alt="Screenshot 2023-02-13 at 09 18 05" src="https://user-images.githubusercontent.com/23365549/218424287-690dec36-1d92-49d4-8e71-de809f45516c.png">
<img width="1196" alt="Screenshot 2023-02-13 at 09 18 40" src="https://user-images.githubusercontent.com/23365549/218424298-32afa992-e9ea-48d1-b7f6-19aabd0d01bf.png">
<img width="1411" alt="Screenshot 2023-02-13 at 09 29 17" src="https://user-images.githubusercontent.com/23365549/218424304-ee3bebfc-cf7c-4001-9d72-b81b3856fd78.png">

### Craft CMS version

4.3.8.2

### PHP version

`php_version: "8.0"`

### Operating system and version

macOS Monterey 12.5.1

### Database type and version

```
database:
  type: mariadb
  version: "10.4"
```

### Image driver and version

DDEV Craft default

### Installed plugins and versions

```
Name              Handle          Package Name                Version  Installed  Enabled
----------------  --------------  --------------------------  -------  ---------  -------
Amazon S3         aws-s3          craftcms/aws-s3             2.0.1    Yes        Yes
Mix               mix             misterbk/mix                1.6.0    Yes        Yes
Redactor          redactor        craftcms/redactor           3.0.3    Yes        Yes
SEOmatic          seomatic        nystudio107/craft-seomatic  4.0.19   Yes        Yes
Super Table       super-table     verbb/super-table           3.0.7    Yes        Yes
Typed link field  typedlinkfield  sebastianlenz/linkfield     2.1.5    Yes        Yes
```

**Comment by wuhhh** [comment]
Here is the result of `ddev craft update all`

```
Fetching available updates ... Exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL: no alternative certificate subject name matches target host name 'api.craftcms.com' (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.craftcms.com/v1/updates'

in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211

Stack trace:
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /var/www/html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/www/html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /var/www/html/vendor/craftcms/cms/src/services/Api.php(125): GuzzleHttp\Client->request('GET', 'updates', Array)
#14 /var/www/html/vendor/craftcms/cms/src/services/Api.php(85): craft\services\Api->request('GET', 'updates', Array)
#15 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpdateController.php(615): craft\services\Api->getUpdates(Array)
#16 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpdateController.php(258): craft\console\controllers\UpdateController->_getUpdates(Array)
#17 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpdateController.php(162): craft\console\controllers\UpdateController->_getRequirements('all')
#18 [internal function]: craft\console\controllers\UpdateController->actionUpdate('all')
#19 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#22 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(227): yii\console\Controller->runAction('', Array)
#23 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#24 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('update', Array)
#25 /var/www/html/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('update', Array)
#26 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('update', Array)
#27 /var/www/html/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#28 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#29 /var/www/html/craft(13): yii\base\Application->run()
#30 {main}
Failed to run craft update all: exit status 1
```

**Comment by wuhhh** [comment]
Sorry for the multiple posts - but I just did a completely fresh Craft install under DDEV and the issue with the plugin store is the same there.

**Comment by brianjhanson** [comment]
It looks like the cert is good, which means this is likely an environmental issue. Do you get the same issue in all browsers and after clearing your browser caches? 

If so, can you reach out `support@craftcms.com`? We have a few more things you can try out.

I'm going to close this out, but if we find on our end in the support process I'll open it back up.
