### ISSUE TITLE
[4.x]: craft\fields\BaseRelationField::_all(): Argument #1 ($query) must be of type craft\elements\db\ElementQueryInterface, craft\elements\ElementCollection given

### ISSUE THREAD

**Issue by barnslig** [craftcms/cms#12839]
### Description

Saving an entry via `Craft::$app->elements->saveElement($entry);` sometimes fails due to the following code:

https://github.com/craftcms/cms/blob/a7aa5d6dfd061b570a4764f2a1fa05d5a7d0bb75/src/fields/BaseRelationField.php#L774-L779

Here, `$value` can either be an `ElementQuery` or a `Collection`, as noted in line 774. However, `$this->_all()` expects an `ElementQueryInterface` as first argument, which is not implemented by the `Collection` type, resulting in a TypeError.

### Expected behavior

Entry can be saved.

### Actual behavior

Saving an entry results in an exception (project-specific names are replaced by *****):

```
TypeError: craft\fields\BaseRelationField::_all(): Argument #1 ($query) must be of type craft\elements\db\ElementQueryInterface, craft\elements\ElementCollection given, called in /srv/webapps/td-ext-magentamusikvendor/craftcms/cms/src/fields/BaseRelationField.php on line 654
#19 vendor/craftcms/cms/src/fields/BaseRelationField.php(1249): craft\fields\BaseRelationField::_all
#18 vendor/craftcms/cms/src/fields/BaseRelationField.php(654): craft\fields\BaseRelationField::searchKeywords
#17 vendor/craftcms/cms/src/base/Field.php(570): craft\base\Field::getSearchKeywords
#16 vendor/craftcms/cms/src/services/Search.php(194): craft\services\Search::indexElementAttributes
#15 vendor/craftcms/cms/src/services/Elements.php(3090): craft\services\Elements::_saveElementInternal
#14 vendor/craftcms/cms/src/services/Elements.php(1039): craft\services\Elements::saveElement
#13 plugins/*****/src/services/*****.php(126): *****\*****\services\*****::update*****Entry
#12 plugins/*****/src/services/*****.php(437): *****\*****\services\*****::applyUpdates
#11 plugins/*****/src/console/controllers/ApiController.php(123): *****\*****\console\controllers\ApiController::action*****
#10 [internal](0): call_user_func_array
#9 vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#8 vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Controller::runAction
#7 vendor/yiisoft/yii2/console/Controller.php(180): yii\console\Controller::runAction
#6 vendor/yiisoft/yii2/base/Module.php(552): yii\base\Module::runAction
#5 vendor/yiisoft/yii2/console/Application.php(180): yii\console\Application::runAction
#4 vendor/craftcms/cms/src/console/Application.php(90): craft\console\Application::runAction
#3 vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application::handleRequest
#2 vendor/craftcms/cms/src/console/Application.php(121): craft\console\Application::handleRequest
#1 vendor/yiisoft/yii2/base/Application.php(384): yii\base\Application::run
#0 craft(13): null
```

### Related issues

- #12815
- #11670
- #11667

### Craft CMS version

4.4.0

### PHP version

8.1.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting. I created a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.4.1 is out now with the fix!
