### ISSUE TITLE
[4.x]: Getting unknown property: craft\records\ImageTransform::fill

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#12856]
### What happened?

Installing Craft 4.4 fails:

```
Applying changes from your project config files ...
- updating dateModified ... done
- updating imageTransforms.18c06552-58b4-44f1-94a5-4b204a6ed657 ... 🔓 Releasing lock ... done
error: Getting unknown property: craft\records\ImageTransform::fill
2023-03-09 20:23:57 [console.ERROR] [yii\base\UnknownPropertyException] Getting unknown property: craft\records\ImageTransform::fill {"trace":["#0 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\\base\\Component->__get()","#1 /app/vendor/craftcms/cms/src/services/ImageTransforms.php(263): yii\\db\\BaseActiveRecord->__get()","#2 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1714): craft\\services\\ImageTransforms->handleChangedTransform()","#3 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1125): craft\\console\\Application->craft\\base\\{closure}()","#4 [internal function]: craft\\services\\ProjectConfig->handleChangeEvent()","#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func()","#6 /app/vendor/craftcms/cms/src/models/ProjectConfigData.php(82): yii\\base\\Component->trigger()","#7 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1231): craft\\models\\ProjectConfigData->commitChanges()","#8 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1253): craft\\services\\ProjectConfig->craft\\services\\{closure}()","#9 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(577): craft\\services\\ProjectConfig->_applyChanges()","#10 /app/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(312): craft\\services\\ProjectConfig->applyExternalChanges()","#11 [internal function]: craft\\console\\controllers\\ProjectConfigController->actionApply()","#12 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()","#13 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()","#14 /app/vendor/yiisoft/yii2/console/Controller.php(180): yii\\base\\Controller->runAction()","#15 /app/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\\console\\Controller->runAction()","#16 /app/vendor/craftcms/cms/src/console/Controller.php(217): craft\\console\\Controller->traitRunAction()","#17 /app/vendor/yiisoft/yii2/base/Module.php(552): craft\\console\\Controller->runAction()","#18 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\\base\\Module->runAction()","#19 /app/vendor/craftcms/cms/src/console/Application.php(90): yii\\console\\Application->runAction()","#20 /app/vendor/yiisoft/yii2/base/Controller.php(212): craft\\console\\Application->runAction()","#21 /app/vendor/craftcms/cms/src/console/Controller.php(208): yii\\base\\Controller->run()","#22 /app/vendor/craftcms/cms/src/console/controllers/UpController.php(69): craft\\console\\Controller->run()","#23 [internal function]: craft\\console\\controllers\\UpController->actionIndex()","#24 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()","#25 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()","#26 /app/vendor/yiisoft/yii2/console/Controller.php(180): yii\\base\\Controller->runAction()","#27 /app/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\\console\\Controller->runAction()","#28 /app/vendor/craftcms/cms/src/console/Controller.php(217): craft\\console\\Controller->traitRunAction()","#29 /app/vendor/yiisoft/yii2/base/Module.php(552): craft\\console\\Controller->runAction()","#30 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\\base\\Module->runAction()","#31 /app/vendor/craftcms/cms/src/console/Application.php(90): yii\\console\\Application->runAction()","#32 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\\console\\Application->runAction()","#33 /app/vendor/craftcms/cms/src/console/Application.php(121): yii\\console\\Application->handleRequest()","#34 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\\console\\Application->handleRequest()","#35 /app/craft(20): yii\\base\\Application->run()","#36 {main}"],"memory":10198152,"exception":"[object] (yii\\base\\UnknownPropertyException(code: 0): Getting unknown property: craft\\records\\ImageTransform::fill at /app/vendor/yiisoft/yii2/base/Component.php:154)"} 
```

### Craft CMS version

4.4

### Database type and version

PostgreSQL

### Installed plugins and versions

-

**Comment by boboldehampsink** [comment]
I'm also seeing these:

```
failed to install Craft: An error occurred while executing the "craft\migrations\Install migration: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "upscale" of relation "imagetransforms" violates not-null constraint
--
  | DETAIL:  Failing row contains (1, Sponsor, sponsor, fit, center-center, 422, 192, null, 82, line, null, null, 2023-03-09 20:24:44, 2023-03-09 20:24:44, 2023-03-09 20:24:44, bd9d65bd-379e-4f1b-822a-3a0f765ffa8d).
  | The SQL being executed was: INSERT INTO "imagetransforms" ("name", "handle", "parameterChangeTime", "mode", "position", "width", "height", "quality", "interlace", "format", "fill", "upscale", "uid", "dateCreated", "dateUpdated") VALUES ('Sponsor', 'sponsor', '2023-03-09 20:24:44', 'fit', 'center-center', 422, 192, 82, 'line', NULL, NULL, NULL, 'bd9d65bd-379e-4f1b-822a-3a0f765ffa8d', '2023-03-09 20:24:44', '2023-03-09 20:24:44') RETURNING "id"
```

**Comment by boboldehampsink** [comment]
may also be related to #12855

**Comment by boboldehampsink** [comment]
Here is the migration log, as you can see the migration where it adds the fill and upscale columns says it has succeeded - howerever they appear missing in the database. I fixed the error for now by manually these columns.

```
🔒 Acquiring lock ... done
Checking for pending Craft and plugin migrations ...
Total 5 new Craft migrations to be applied:
    - m221027_160703_add_image_transform_fill
    - m221028_130548_add_canonical_id_index
    - m221118_003031_drop_element_fks
    - m230131_120713_asset_indexing_session_new_options
    - m230226_013114_drop_plugin_license_columns
Skipping database backup.
*** applying m221027_160703_add_image_transform_fill
    > add column fill string(11) NULL DEFAULT NULL to table {{%imagetransforms}} ... done (time: 0.009s)
    > add column upscale boolean NOT NULL DEFAULT TRUE to table {{%imagetransforms}} ... done (time: 0.004s)
    > execute SQL: alter table {{%imagetransforms}} drop constraint {{%imagetransforms_mode_check}}, add check ([[mode]] in ('stretch','fit','crop','letterbox')) ...    > execute SQL: alter table {{%imagetransforms}} drop constraint {{%assettransforms_mode_check}}, add check ([[mode]] in ('stretch','fit','crop','letterbox')) ...*** applied m221027_160703_add_image_transform_fill (time: 0.057s)
*** applying m221028_130548_add_canonical_id_index
    > create index idx_abzoyvjiuiggkbakxqackhnsjbqcxknjuxma on {{%elements}} (canonicalId) ... done (time: 0.247s)
*** applied m221028_130548_add_canonical_id_index (time: 0.320s)
*** applying m221118_003031_drop_element_fks
    > dropping foreign key on {{%relations}} if it exists ... done (time: 0.024s)
    > dropping foreign key on {{%structureelements}} if it exists ... done (time: 0.024s)
*** applied m221118_003031_drop_element_fks (time: 0.087s)
*** applying m230131_120713_asset_indexing_session_new_options
    > add column processIfRootEmpty boolean DEFAULT FALSE to table {{%assetindexingsessions}} ... done (time: 0.003s)
    > add column listEmptyFolders boolean DEFAULT FALSE to table {{%assetindexingsessions}} ... done (time: 0.003s)
*** applied m230131_120713_asset_indexing_session_new_options (time: 0.057s)
*** applying m230226_013114_drop_plugin_license_columns
    > execute SQL: alter table {{%plugins}} drop constraint {{%plugins_licenseKeyStatus_check}} ... done (time: 0.003s)
    > drop column licenseKeyStatus from table {{%plugins}} ... done (time: 0.003s)
    > drop column licensedEdition from table {{%plugins}} ... done (time: 0.003s)
*** applied m230226_013114_drop_plugin_license_columns (time: 0.104s)
5 migrations were applied.
Migrated up successfully.
Applying changes from your project config files ...
- updating dateModified ... done
- updating system ... done
- updating imageTransforms.0ac8abc8-34e5-483f-9774-c2986624aee5 ... 
error: Getting unknown property: craft\records\ImageTransform::fill
🔓 Releasing lock ... done
2023-03-09 19:21:57 [console.ERROR] [yii\base\UnknownPropertyException] Getting unknown property: craft\records\ImageTransform::fill {"trace":["#0 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\\base\\Component->__get()","#1 /app/vendor/craftcms/cms/src/services/ImageTransforms.php(263): yii\\db\\BaseActiveRecord->__get()","#2 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1714): craft\\services\\ImageTransforms->handleChangedTransform()","#3 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1125): craft\\console\\Application->craft\\base\\{closure}()","#4 [internal function]: craft\\services\\ProjectConfig->handleChangeEvent()","#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func()","#6 /app/vendor/craftcms/cms/src/models/ProjectConfigData.php(82): yii\\base\\Component->trigger()","#7 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1231): craft\\models\\ProjectConfigData->commitChanges()","#8 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1253): craft\\services\\ProjectConfig->craft\\services\\{closure}()","#9 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(577): craft\\services\\ProjectConfig->_applyChanges()","#10 /app/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(312): craft\\services\\ProjectConfig->applyExternalChanges()","#11 [internal function]: craft\\console\\controllers\\ProjectConfigController->actionApply()","#12 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()","#13 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()","#14 /app/vendor/yiisoft/yii2/console/Controller.php(180): yii\\base\\Controller->runAction()","#15 /app/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\\console\\Controller->runAction()","#16 /app/vendor/craftcms/cms/src/console/Controller.php(217): craft\\console\\Controller->traitRunAction()","#17 /app/vendor/yiisoft/yii2/base/Module.php(552): craft\\console\\Controller->runAction()","#18 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\\base\\Module->runAction()","#19 /app/vendor/craftcms/cms/src/console/Application.php(90): yii\\console\\Application->runAction()","#20 /app/vendor/yiisoft/yii2/base/Controller.php(212): craft\\console\\Application->runAction()","#21 /app/vendor/craftcms/cms/src/console/Controller.php(208): yii\\base\\Controller->run()","#22 /app/vendor/craftcms/cms/src/console/controllers/UpController.php(69): craft\\console\\Controller->run()","#23 [internal function]: craft\\console\\controllers\\UpController->actionIndex()","#24 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()","#25 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()","#26 /app/vendor/yiisoft/yii2/console/Controller.php(180): yii\\base\\Controller->runAction()","#27 /app/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\\console\\Controller->runAction()","#28 /app/vendor/craftcms/cms/src/console/Controller.php(217): craft\\console\\Controller->traitRunAction()","#29 /app/vendor/yiisoft/yii2/base/Module.php(552): craft\\console\\Controller->runAction()","#30 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\\base\\Module->runAction()","#31 /app/vendor/craftcms/cms/src/console/Application.php(90): yii\\console\\Application->runAction()","#32 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\\console\\Application->runAction()","#33 /app/vendor/craftcms/cms/src/console/Application.php(121): yii\\console\\Application->handleRequest()","#34 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\\console\\Application->handleRequest()","#35 /app/craft(20): yii\\base\\Application->run()","#36 {main}"],"memory":10243000,"exception":"[object] (yii\\base\\UnknownPropertyException(code: 0): Getting unknown property: craft\\records\\ImageTransform::fill at /app/vendor/yiisoft/yii2/base/Component.php:154)"} 
```

**Comment by boboldehampsink** [comment]
I should add that the migration was done on a system that uses a follower db. 

This one is in tests on multiple sites:

> I'm also seeing these:
> 
> ```
> failed to install Craft: An error occurred while executing the "craft\migrations\Install migration: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "upscale" of relation "imagetransforms" violates not-null constraint
> --
>   | DETAIL:  Failing row contains (1, Sponsor, sponsor, fit, center-center, 422, 192, null, 82, line, null, null, 2023-03-09 20:24:44, 2023-03-09 20:24:44, 2023-03-09 20:24:44, bd9d65bd-379e-4f1b-822a-3a0f765ffa8d).
>   | The SQL being executed was: INSERT INTO "imagetransforms" ("name", "handle", "parameterChangeTime", "mode", "position", "width", "height", "quality", "interlace", "format", "fill", "upscale", "uid", "dateCreated", "dateUpdated") VALUES ('Sponsor', 'sponsor', '2023-03-09 20:24:44', 'fit', 'center-center', 422, 192, 82, 'line', NULL, NULL, NULL, 'bd9d65bd-379e-4f1b-822a-3a0f765ffa8d', '2023-03-09 20:24:44', '2023-03-09 20:24:44') RETURNING "id"
> ```

**Comment by brandonkelly** [comment]
Hey @boboldehampsink, if you were impacted by #12855, I suspect that is having cascading effects for you, especially if you recreated columns manually.

Do you have a database backup from before the 4.4 update? If so can you please try reverting to that, installing Craft 4.4.1 (which contains a fix for #12855), and attempting the update again?

**Comment by boboldehampsink** [comment]
@brandonkelly the upgrade seems to work now, but still seeing this in tests when upgrading other projects:

```


> applying existing project config ... Exception: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "upscale" of relation "imagetransforms" violates not-null constraint
--
  | DETAIL:  Failing row contains (1, Block, block, crop, center-center, 1374, 1030, webp, 80, line, null, null, 2023-03-10 08:16:01, 2023-03-10 08:16:01, 2023-03-10 08:16:01, 3ce0819a-62f3-44db-860f-09b272f06e44).
  | The SQL being executed was: INSERT INTO "imagetransforms" ("name", "handle", "parameterChangeTime", "mode", "position", "width", "height", "quality", "interlace", "format", "fill", "upscale", "uid", "dateCreated", "dateUpdated") VALUES ('Block', 'block', '2023-03-10 08:16:01', 'crop', 'center-center', 1374, 1030, 80, 'line', 'webp', NULL, NULL, '3ce0819a-62f3-44db-860f-09b272f06e44', '2023-03-10 08:16:01', '2023-03-10 08:16:01') RETURNING "id" (/app/user/vendor/yiisoft/yii2/db/Schema.php:676)
  | #0 /app/user/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO "im...')
  | #1 /app/user/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('INSERT INTO "im...')
  | #2 /app/user/vendor/yiisoft/yii2/db/Command.php(424): yii\db\Command->queryInternal('fetch', NULL)
  | #3 /app/user/vendor/yiisoft/yii2/db/pgsql/Schema.php(646): yii\db\Command->queryOne()
  | #4 /app/user/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\pgsql\Schema->insert('{{%imagetransfo...', Array)
  | #5 /app/user/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal(NULL)
  | #6 /app/user/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert(false, NULL)
  | #7 /app/user/vendor/craftcms/cms/src/services/ImageTransforms.php(282): yii\db\BaseActiveRecord->save(false)
  | #8 /app/user/vendor/craftcms/cms/src/base/ApplicationTrait.php(1714): craft\services\ImageTransforms->handleChangedTransform(Object(craft\events\ConfigEvent))
  | #9 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(1125): craft\console\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
  | #10 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
  | #11 /app/user/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
  | #12 /app/user/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
  | #13 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(1231): craft\models\ProjectConfigData->commitChanges(NULL, Array, 'imageTransforms...', true, NULL, true)
  | #14 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(1253): craft\services\ProjectConfig->craft\services\{closure}('imageTransforms...', true)
  | #15 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(577): craft\services\ProjectConfig->_applyChanges(Array, Object(craft\models\ProjectConfigData), Object(craft\models\ReadOnlyProjectConfigData))
  | #16 /app/user/vendor/craftcms/cms/src/migrations/Install.php(1124): craft\services\ProjectConfig->applyExternalChanges()
  | #17 /app/user/vendor/craftcms/cms/src/migrations/Install.php(77): craft\migrations\Install->insertDefaultData()
  | #18 /app/user/vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\Install->safeUp()
  | #19 /app/user/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
  | #20 /app/user/vendor/craftcms/cms/src/console/controllers/InstallController.php(213): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
  | #21 [internal function]: craft\console\controllers\InstallController->actionCraft()
  | #22 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
  | #23 /app/user/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
  | #24 /app/user/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
  | #25 /app/user/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\console\Controller->runAction('', Array)
  | #26 /app/user/vendor/craftcms/cms/src/console/Controller.php(217): craft\console\Controller->traitRunAction('', Array)
  | #27 /app/user/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
  | #28 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
  | #29 /app/user/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('install', Array)
  | #30 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
  | #31 /app/user/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
  | #32 /app/user/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
  | #33 /app/user/craft(20): yii\base\Application->run()
  | #34 {main}
  | *** failed to install Craft: An error occurred while executing the "craft\migrations\Install migration: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "upscale" of relation "imagetransforms" violates not-null constraint
  | DETAIL:  Failing row contains (1, Block, block, crop, center-center, 1374, 1030, webp, 80, line, null, null, 2023-03-10 08:16:01, 2023-03-10 08:16:01, 2023-03-10 08:16:01, 3ce0819a-62f3-44db-860f-09b272f06e44).
  | The SQL being executed was: INSERT INTO "imagetransforms" ("name", "handle", "parameterChangeTime", "mode", "position", "width", "height", "quality", "interlace", "format", "fill", "upscale", "uid", "dateCreated", "dateUpdated") VALUES ('Block', 'block', '2023-03-10 08:16:01', 'crop', 'center-center', 1374, 1030, 80, 'line', 'webp', NULL, NULL, '3ce0819a-62f3-44db-860f-09b272f06e44', '2023-03-10 08:16:01', '2023-03-10 08:16:01') RETURNING "id"


```

**Comment by boboldehampsink** [comment]
@brandonkelly works now. The test failure is because of a project config schema update I forgot to commit.

**Comment by brandonkelly** [comment]
@boboldehampsink Excellent! Thanks for testing.
