### ISSUE TITLE
Updating to latest 3.8 results in DB migration error

### ISSUE THREAD

**Issue by shoored** [craftcms/cms#13186]
### Description
When I update my Craft CMS 3.7.65 site to the latest 3.8 then run `craft up` and apply the available migrations, this results in the following error:

```
*** applying m230226_013114_drop_plugin_license_columns
    > execute SQL: alter table {{%plugins}} drop constraint {{%plugins_licenseKeyStatus_check}} ...Exception: SQLSTATE[42704]: Undefined object: 7 ERROR:  constraint "plugins_licenseKeyStatus_check" of relation "plugins" does not exist
The SQL being executed was: alter table "plugins" drop constraint "plugins_licenseKeyStatus_check" (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'alter table "pl...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('alter table "pl...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(219): yii\db\Command->execute()
#3 /var/www/html/vendor/craftcms/cms/src/migrations/m230226_013114_drop_plugin_license_columns.php(22): yii\db\Migration->execute('alter table {{%...')
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(53): craft\migrations\m230226_013114_drop_plugin_license_columns->safeUp()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(386): yii\console\controllers\BaseMigrateController->migrateUp('m230226_013114_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('all', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('all', Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#13 /var/www/html/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#14 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(212): yii\base\Controller->run('migrate/all', Array)
#16 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(58): craft\console\Controller->run('migrate/all', Array)
#17 [internal function]: craft\console\controllers\UpController->actionIndex()
#18 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#20 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('', Array)
#21 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(221): yii\console\Controller->runAction('', Array)
#22 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#23 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#24 /var/www/html/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('up', Array)
#25 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#26 /var/www/html/vendor/craftcms/cms/src/console/Application.php(118): yii\console\Application->handleRequest(Object(craft\console\Request))
#27 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#28 /var/www/html/craft(26): yii\base\Application->run()
#29 {main}
*** failed to apply m230226_013114_drop_plugin_license_columns (time: 0.015s)
```

### Environment
- DDEV
- PHP 7.4
- Postgres 11

### Steps to reproduce

1. Run `composer update`
2. Run `php craft up`

Before running the migrations I cleared my `storage/logs` folder and after I ran the migrations only a `console.log` file was created without any stack traces or errors.

I'm don't have much Postgres experience unfortunately. Any tips greatly appreciated.

### Craft CMS version

3.7.65

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This should be fixed for the next Craft 3 and 4, via #13189.

**Comment by brandonkelly** [comment]
Craft 3.8.11 and 4.4.11 are out with that fix. Thanks for reporting!

**Comment by shoored** [comment]
Thanks for the quick actions! All is well now.
