### ISSUE TITLE
[4.x]: Database exception when running gc/run

### ISSUE THREAD

**Issue by justinmacleod** [craftcms/cms#13406]
### Description

We have a large Craft CMS site that we haven't run garbage collection on in a while. We have automatic garbage collection disabled due to a previous bug which caused data loss. We are now attempting to run it manually on a copy of our production database, but we are encountering a PDO error:

```
PDOException: SQLSTATE[HY000]: General error: 7 number of parameters must be between 0 and 65535 in /var/www/example.com/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /var/www/example.com/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /var/www/example.com/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /var/www/example.com/vendor/craftcms/cms/src/helpers/Db.php(1145): yii\db\Command->execute()
#3 /var/www/example.com/vendor/spicyweb/craft-neo/src/Plugin.php(229): craft\helpers\Db::delete()
#4 [internal function]: benf\neo\Plugin->benf\neo\{closure}()
#5 /var/www/example.com/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#6 /var/www/example.com/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#7 /var/www/example.com/vendor/craftcms/cms/src/services/Gc.php(140): yii\base\Component->trigger()
#8 /var/www/example.com/vendor/craftcms/cms/src/console/controllers/GcController.php(56): craft\services\Gc->run()
#9 [internal function]: craft\console\controllers\GcController->actionRun()
#10 /var/www/example.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#11 /var/www/example.com/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#12 /var/www/example.com/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#13 /var/www/example.com/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\console\Controller->runAction()
#14 /var/www/example.com/vendor/craftcms/cms/src/console/Controller.php(217): craft\console\Controller->traitRunAction()
#15 /var/www/example.com/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction()
#16 /var/www/example.com/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#17 /var/www/example.com/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction()
#18 /var/www/example.com/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#19 /var/www/example.com/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest()
#20 /var/www/example.com/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#21 /var/www/example.com/craft(13): yii\base\Application->run()
#22 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 7 number of parameters must be between 0 and 65535
The SQL being executed was: DELETE FROM "structures" WHERE ("id" IN (68543, 3049, 770, 770, 826, 3137, 3369, 3369, 3051, 3459, 478, 3007, 1051, 3495, 45045, 857, 771, 3518, 1068, 3369, 3008, 3008, 6225, 3369, 3369, 3009, 3369, 3459, 3370, 3053, 3011, 3019, 3033, 3495, 41549, 3021, 3021, 3028, 3030, 3035, 3036, 3536, 3518, 3370, 3055, 3013, 3022, 786, 63209, 829, 2273, 68543, 804, 837, 790, 748, 830, 756, 3371, 68543, 3459, 3495, 858, 791, 791, 858, 831, 799, 800, 800, 807, 757, 64705, 851, 768, 70193, 70193, 32477, 832, 3056, 808, 811, 6271, 838, 812, 812, 816, 819, 833, 809, 68543, 68543, 68543, 68543, ........
```

I did some digging and found this is a known [PDO limitation](https://stackoverflow.com/questions/40361164/pdoexception-sqlstatehy000-general-error-7-number-of-parameters-must-be-bet) and the query must be adjusted.

### Craft CMS version

4.4.8

### PHP version

8.2.5

### Database type and version

Postgres 14.7

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. Based on the stack trace you posted, this error is triggered by the Neo plugin (deleting orphaned Neo block structure data). I believe it happens because Neo gets the IDs of everything that should be deleted and uses them in the delete query. It would be best to raise this on Neo’s GH: https://github.com/spicywebau/craft-neo/issues.
