### ISSUE TITLE
[4.5.1]: keyboard shortcut issue: permanent focus on assets

### ISSUE THREAD

**Issue by arifje** [craftcms/cms#13601]
### What happened?

CTRL-S stops working after selecting and saving an asset in the entry.

### Steps to reproduce

- open an entry
- double click an asset
- save the asset with CTRL S
- the asset panel is closed
- now hit CTRL S again
- the asset is saved again, and again...

### Expected behavior

- entry should be saved, asset panel is closed

Also, pressing CMD (OSX) triggers this javascript error:

```
UiLayerManager.js:168 Uncaught TypeError: Cannot read properties of undefined (reading 'bubble')
    at s.constructor.triggerShortcut (UiLayerManager.js:168:30)
    at s.constructor.<anonymous> (Base.js:153:23)
    at HTMLBodyElement.o (jquery.js?v=1692888808:2:89408)
    at HTMLBodyElement.dispatch (jquery.js?v=1692888808:2:43392)
    at v.handle (jquery.js?v=1692888808:2:41387)
```

### Craft CMS version

4.5.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 4.5.2 is out with a fix.
