### ISSUE TITLE
[4.x]: Craft not sending STMP emails.

### ISSUE THREAD

**Issue by zzseba78** [craftcms/cms#13611]
### Description
Craft 4 doesn´t send emails using STMP protocol. Doesn´t send test emails from Admin section ( test email ) and doesnt send email using Contact Form plugin. The email is from the current hosting and domain. Triple check username, server, port and password. From the Craft Admin test ( Email ) the test email show as sended ( attach screenshot )

Uploaded a PHPMailer test file using same email account with SMTP and works great, on the server and in localhost.

### Update
**Tested with a clean ( no plugins at all ) latest Craft v4 install, and doesn´t work either.** Use several SMPT mails accounts that i know are working.

Log file in /storage/ folder shows this ( cleared all the file, just show this on contact form send ).

```
2023-08-25 20:10:18 [web.ERROR] [yii\web\HttpException:503]  {"trace":["#0 /home2/xxxxxx/vendor/craftcms/cms/src/web/Controller.php(175): craft\\web\\Controller->_enforceAllowAnonymous(Object(yii\\base\\InlineAction))","#1 /home2/xxxxxx/vendor/yiisoft/yii2/base/Controller.php(176): craft\\web\\Controller->beforeAction(Object(yii\\base\\InlineAction))","#2 /home2/xxxxxx/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction('robots', Array)","#3 /home2/xxxxxx/vendor/craftcms/cms/src/web/Application.php(304): yii\\base\\Module->runAction('seo/seo/robots', Array)","#4 /home2/xxxxxx/vendor/yiisoft/yii2/web/Application.php(103): craft\\web\\Application->runAction('seo/seo/robots', Array)","#5 /home2/xxxxxx/vendor/craftcms/cms/src/web/Application.php(289): yii\\web\\Application->handleRequest(Object(craft\\web\\Request))","#6 /home2/xxxxxx/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))","#7 /home2/xxxxxx/public_html/index.php(12): yii\\base\\Application->run()","#8 {main}"],"memory":1312424,"exception":"[object] (craft\\web\\ServiceUnavailableHttpException(code: 0):  at /home2/xxxxxx/vendor/craftcms/cms/src/web/Controller.php:211)"} 

2023-08-25 20:10:18 [web.WARNING] [application] Request context: {"vars":{"_GET":{"p":"robots.txt"},"_POST":[],"_FILES":[],"_COOKIE":[],"_SERVER":{"LSPHP_ENABLE_USER_INI":"on","PATH":"/usr/local/bin:/usr/bin:/bin","TEMP":"/tmp","TMP":"/tmp","TMPDIR":"/tmp","PWD":"/","HTTP_ACCEPT":"text/plain,text/html,*/*","HTTP_ACCEPT_ENCODING":"gzip, deflate, br","HTTP_CONNECTION":"keep-alive","CONTENT_LENGTH":"0","HTTP_HOST...
```

<img width="1054" alt="1" src="https://github.com/craftcms/cms/assets/5558563/b6e3a340-e1ff-442b-a9bc-da6bedb01806">
<img width="521" alt="2" src="https://github.com/craftcms/cms/assets/5558563/927cd31b-6265-48a0-b596-bf1f53b202fa">

### Craft CMS version

4.5.2

### PHP version

8.2.9

### Operating system and version

Linux 4.19.286-203.ELK.el7.x86_64

### Database type and version

MySQL 23

### Image driver and version

Imagick 3.5.0 (ImageMagick 6.9.10-68)

### Installed plugins and versions

Contact Form
3.0.1 

Contact Form Honeypot
2.0.0 

Control Panel Nav
4.0.10 
Image Resizer
3.0.7 

Minify
4.0.0-beta.2 

Redactor
3.0.4 

SEO
4.2.1

**Comment by angrybrad** [comment]
I just tested Settings->Email using SMTP settings on a fresh Craft 4.5.2 install and I received the test email successfully.

It did turn up a [UI bug](https://github.com/craftcms/cms/issues/13613), but I don't think that it is related.

Focussing on the Settings->Email test only, can you load that page in the control panel, enable DevMode, delete the contents of Craft's `storage/logs` folder, then click the "Test" button, and share a zipped `storage/logs` folder? Feel free to send to support@craftcms.com and reference issue 13611 if you don't to share publicly.

**Comment by brandonkelly** [comment]
Craft 4.5.3 is out now with a fix for that UI bug.

**Comment by angrybrad** [comment]
For posterity, it looks like the OP’s underlying issue was a blocklisted email server.
