### ISSUE TITLE
[4.x]: Changes to the project config are not possible while in read-only mode.

### ISSUE THREAD

**Issue by vkamelin** [craftcms/cms#13784]
### Description

php craft update all

```
Checking for pending Craft and plugin migrations ...
Total 10 new Craft migrations to be applied:
    - m221027_160703_add_image_transform_fill
    - m221028_130548_add_canonical_id_index
    - m221118_003031_drop_element_fks
    - m230131_120713_asset_indexing_session_new_options
    - m230226_013114_drop_plugin_license_columns
    - m230531_123004_add_entry_type_show_status_field
    - m230607_102049_add_entrytype_slug_translation_columns
    - m230710_162700_element_activity
    - m230820_162023_fix_cache_id_type
    - m230826_094050_fix_session_id_type

*** applying m221027_160703_add_image_transform_fill
    > add column fill string(11) NULL DEFAULT NULL AFTER `interlace` to table {{%imagetransforms}} ... done (time: 0.014s)
    > add column upscale boolean NOT NULL DEFAULT TRUE AFTER `fill` to table {{%imagetransforms}} ... done (time: 0.011s)
    > alter column mode in table {{%imagetransforms}} to enum('stretch','fit','crop','letterbox') NOT NULL DEFAULT 'crop' ... done (time: 0.006s)
Exception: Changes to the project config are not possible while in read-only mode. (.../vendor/craftcms/cms/src/services/ProjectConfig.php:512)
#0 .../vendor/craftcms/cms/src/services/ProjectConfig.php(484): craft\services\ProjectConfig->_setInternal()
#1 .../vendor/craftcms/cms/src/migrations/m221027_160703_add_image_transform_fill.php(59): craft\services\ProjectConfig->set()
#2 .../vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\m221027_160703_add_image_transform_fill->safeUp()
#3 .../vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#4 .../vendor/craftcms/cms/src/console/controllers/MigrateController.php(361): yii\console\controllers\BaseMigrateController->migrateUp()
#5 [internal function]: craft\console\controllers\MigrateController->actionAll()
#6 .../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 .../vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#8 .../vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#9 .../vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction()
#10 .../vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction()
#11 .../vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#12 .../vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction()
#13 .../vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#14 .../vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest()
#15 .../vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#16 .../craft(13): yii\base\Application->run()
#17 {main}
*** failed to apply m221027_160703_add_image_transform_fill (time: 0.066s)
```

### Steps to reproduce

1. Run 
`php craft update all`

### Craft CMS version

4.3.5

### PHP version

8.2

### Operating system and version

Ubuntu 22.04

### Database type and version

MySQL 8.0.34

### Installed plugins and versions

-

**Comment by vkamelin** [comment]
Anybody here?

**Comment by brandonkelly** [comment]
This is working as expected.

When admin changes are disallowed (`allowAdminChanges` is set to `false`), the project config is intentionally set to read-only.

If you hit that error during a migration, it probably mean that you ran `composer update` on a dev environment, pushed the `composer.lock` changes, without actually running the update’s migrations. You should be able to fix it by running `php craft up` locally, so the same migrations get run there (where admin changes _are_ allowed), and then push up the updated `config/project/*` files.

**Comment by vkamelin** [comment]
```
php craft up
Checking for pending Craft and plugin migrations ...
Total 10 new Craft migrations to be applied:
    - m221027_160703_add_image_transform_fill
    - m221028_130548_add_canonical_id_index
    - m221118_003031_drop_element_fks
    - m230131_120713_asset_indexing_session_new_options
    - m230226_013114_drop_plugin_license_columns
    - m230531_123004_add_entry_type_show_status_field
    - m230607_102049_add_entrytype_slug_translation_columns
    - m230710_162700_element_activity
    - m230820_162023_fix_cache_id_type
    - m230826_094050_fix_session_id_type

Apply the above migrations? (yes|no) [no]:yes
Create database backup? (yes|no) [yes]:yes
Backing up the database ... done
*** applying m221027_160703_add_image_transform_fill
    > add column fill string(11) NULL DEFAULT NULL AFTER `interlace` to table {{%imagetransforms}} ...Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'fill'
The SQL being executed was: ALTER TABLE `imagetransforms` ADD `fill` varchar(11) NULL DEFAULT NULL AFTER `interlace` (/home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException()
#1 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/db/Migration.php(376): yii\db\Command->execute()
#3 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/craftcms/cms/src/migrations/m221027_160703_add_image_transform_fill.php(21): yii\db\Migration->addColumn()
#4 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\m221027_160703_add_image_transform_fill->safeUp()
#5 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/craftcms/cms/src/console/controllers/MigrateController.php(361): yii\console\controllers\BaseMigrateController->migrateUp()
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#9 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#10 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#11 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction()
#12 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction()
#13 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#14 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction()
#15 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction()
#16 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/craftcms/cms/src/console/Controller.php(208): yii\base\Controller->run()
#17 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/craftcms/cms/src/console/controllers/UpController.php(57): craft\console\Controller->run()
#18 [internal function]: craft\console\controllers\UpController->actionIndex()
#19 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#20 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#21 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#22 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction()
#23 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/craftcms/cms/src/console/Controller.php(217): craft\console\Controller->traitRunAction()
#24 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction()
#25 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#26 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction()
#27 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#28 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest()
#29 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#30 /home/gadjet/Документы/files_2023-09-17_04 14/domains/volumestudia.com/craft(13): yii\base\Application->run()
#31 {main}
*** failed to apply m221027_160703_add_image_transform_fill (time: 0.003s)


0 from 10 migrations were applied.

Migration failed. The rest of the migrations are canceled.

```
`
'allowAdminChanges' => true,`

**Comment by vkamelin** [comment]
@brandonkelly ?
