### ISSUE TITLE
[4.5.8]: Element Index -> Edit Entry broken

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#13867]
### Description

Trying to edit entry from element index via 'Edit Entry' action or double clicking the status indicator fails with this error:

```
2023-10-21 09:54:57 [web.ERROR] [TypeError] TypeError: craft\web\View::namespaceInputs(): Argument #1 ($html) must be of type callable|string, null given, called in /var/www/html/vendor/craftcms/cms/src/web/View.php on line 1669 and defined in /var/www/html/vendor/craftcms/cms/src/web/View.php:1657
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/View.php(1669): craft\web\View->namespaceInputs(NULL, 'ovdynqznzd', true, false)
#1 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(70): craft\web\View->namespaceInputs(Object(Closure), 'ovdynqznzd')
#2 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(47): craft\web\CpScreenResponseFormatter->_formatJson(Object(craft\web\Request), Object(craft\web\Response), Object(craft\web\CpScreenResponseBehavior))
#3 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\CpScreenResponseFormatter->format(Object(craft\web\Response))
#4 /var/www/html/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#5 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#6 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#7 /var/www/html/web/index.php(11): yii\base\Application->run()
#8 {main} {"memory":6733264,"exception":"[object] (TypeError(code: 0): craft\\web\\View::namespaceInputs(): Argument #1 ($html) must be of type callable|string, null given, called in /var/www/html/vendor/craftcms/cms/src/web/View.php on line 1669 at /var/www/html/vendor/craftcms/cms/src/web/View.php:1657)"}
```

### Steps to reproduce

1. Goto Entries element index
2. Select entry
3. Select 'Edit Entry' action

/Karla

### Craft CMS version

Craft Solo 4.5.8

### PHP version

8.1.23

### Operating system and version

Linux 5.15.90.1-microsoft-standard-WSL2

### Database type and version

MariaDB 10.4.31

### Installed plugins and versions

-

**Comment by rw-ninety** [comment]
Same issue here since the last update, all the edit overlays are broken. 

"craft\\web\\View::namespaceInputs(): Argument #1 ($html) must be of type callable|string, null given, called in vendor/craftcms/cms/src/web/View.php on line 1669"

**Comment by adrianjean** [comment]
Seeing this as well:
- I have "Section A" with a Entity Reference Field for entries from "Section B" (which used to be a category, but was entrified)
- In a new entry form for Section A, clicking the Entity Reference field to select an entry from Section B, brings up the Entry selection window.
- Clicking the button to create a new entry of Section B in an overlay triggers the type error:

```
2023-10-22 22:37:33 [web.ERROR] [TypeError] craft\web\View::namespaceInputs(): Argument #1 ($html) must be of type callable|string, null given, called in /srv/www/website.com/web/vendor/craftcms/cms/src/web/View.php on line 1669 {"trace":["#0 /srv/www/website.com/vendor/craftcms/cms/src/web/View.php(1669): craft\\web\\View->namespaceInputs()","#1 /srv/www/website.com/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(70): craft\\web\\View->namespaceInputs()","#2 /srv/www/website.com/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(47): craft\\web\\CpScreenResponseFormatter->_formatJson()","#3 /srv/www/website.com/vendor/yiisoft/yii2/web/Response.php(1100): craft\\web\\CpScreenResponseFormatter->format()","#4 /srv/www/website.com/vendor/craftcms/cms/src/web/Response.php(337): yii\\web\\Response->prepare()","#5 /srv/www/website.com/vendor/yiisoft/yii2/web/Response.php(340): craft\\web\\Response->prepare()","#6 /srv/www/website.com/vendor/yiisoft/yii2/base/Application.php(390): yii\\web\\Response->send()","#7 /srv/www/website.com/web/index.php(12): yii\\base\\Application->run()","#8 {main}"],"memory":8101232,"exception":"[object] (TypeError(code: 0): craft\\web\\View::namespaceInputs(): Argument #1 ($html) must be of type callable|string, null given, called in /srv/www/website.com/vendor/craftcms/cms/src/web/View.php on line 1669 at /srv/www/website.com/vendor/craftcms/cms/src/web/View.php:1657)"} 
```


Craft CMS Pro: 
PHP: 8.2.11
MySQL: 8.0.30
OS: Linux 5.15.0-86-generic

**Comment by bossanova808** [comment]
Seeing this too editing addresses in Commerce - https://github.com/craftcms/commerce/issues/3310

**Comment by i-just** [comment]
Hi All, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Craft 4.5.9 is out with a fix for this. Thanks everyone!
