### ISSUE TITLE
[5.x]: Migration m230524_220029_global_entry_types fails

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14043]
### Description

Got this error  on an existing Craft 4 project after updating to Craft 5:

```
*** applying m230524_220029_global_entry_types
    > dropping {{%sections_entrytypes}} if it exists ... done (time: 0.013s)
    > create table {{%sections_entrytypes}} ... done (time: 0.069s)
    > add foreign key fk_raldxjxtamlyjxwhdohpfaothkesvyhrudlq: {{%sections_entrytypes}} (sectionId) references {{%sections}} (id) ... done (time: 0.154s)
    > add foreign key fk_bqbmqfmjfkmxplgkorvxoitbkjykivbfbpao: {{%sections_entrytypes}} (typeId) references {{%entrytypes}} (id) ... done (time: 0.200s)
    > insert into {{%sections_entrytypes}} ... done (time: 0.019s)
    > dropping foreign key on {{%entrytypes}} if it exists ... done (time: 0.036s)
    > dropping index on {{%entrytypes}} if it exists ... done (time: 0.042s)
    > dropping index on {{%entrytypes}} if it exists ... done (time: 0.043s)
    > dropping index on {{%entrytypes}} if it exists ... done (time: 0.038s)
    > drop column sectionId from table {{%entrytypes}} ... done (time: 0.031s)
    > drop column sortOrder from table {{%entrytypes}} ... done (time: 0.029s)
Exception: Setting unknown property: craft\records\FieldLayout::config (/var/www/html/vendor/yiisoft/yii2/base/Component.php:209)
#0 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(322): yii\base\Component->__set('config', Array)
#1 /var/www/html/vendor/craftcms/cms/src/db/ActiveRecord.php(56): yii\db\BaseActiveRecord->__set('config', Array)
#2 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(1037): craft\db\ActiveRecord->__set('config', Array)
#3 /var/www/html/vendor/craftcms/cms/src/services/Entries.php(1388): craft\services\Fields->saveLayout(Object(craft\models\FieldLayout), false)
#4 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1826): craft\services\Entries->handleChangedEntryType(Object(craft\events\ConfigEvent))
#5 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1160): craft\console\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#6 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#7 /var/www/html/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent))
#8 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(85): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#9 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(558): craft\models\ProjectConfigData->commitChanges(Array, Array, 'entryTypes.817d...', true, NULL, true)
#10 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(518): craft\services\ProjectConfig->_setInternal('entryTypes.817d...', Array, NULL, true, false)
#11 /var/www/html/vendor/craftcms/cms/src/migrations/m230524_220029_global_entry_types.php(123): craft\services\ProjectConfig->set('entryTypes.817d...', Array)
#22 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#23 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#24 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#25 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#26 /var/www/html/craft(13): yii\base\Application->run()
#27 {main}
*** failed to apply m230524_220029_global_entry_types (time: 0.696s)

```

### Steps to reproduce

1. Update to Craft 5: `"craftcms/cms": "5.0.x-dev as 5.0.0-alpha.1",`
2. Run  `craft migrate/all`

/Karla

### Craft CMS version

5.0.x-dev dbac648

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.2 is out with that fix. Thanks again!
