### ISSUE TITLE
[5.x]: Migration m230511_000000_field_layout_configs fails

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14061]
### What happened?

Testing an upgrade from Craft 4 and getting this:

```
*** applying m230511_000000_field_layout_configs
Exception: Setting unknown property: craft\fields\Matrix::localizeBlocks (/var/www/html/vendor/yiisoft/yii2/base/Component.php:209)
#0 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('localizeBlocks', false)
#1 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\fields\Matrix), Array)
#2 /var/www/html/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#3 /var/www/html/vendor/craftcms/cms/src/base/Field.php(248): craft\base\Model->__construct(Array)
#4 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(289): craft\base\Field->__construct(Array)
#5 [internal function]: craft\fields\Matrix->__construct(Array)
#6 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#7 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\fields\\Ma...', Array, Array)
#8 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\fields\\Ma...', Array, Array)
#9 /var/www/html/vendor/craftcms/cms/src/Craft.php(56): yii\BaseYii::createObject(Array, Array)
#10 /var/www/html/vendor/craftcms/cms/src/helpers/Component.php(143): Craft::createObject(Array)
#11 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(322): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#12 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(381): craft\services\Fields->createField(Array)
#13 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(469): craft\services\Fields->_field(Array)
#14 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(180): craft\services\Fields->getFieldByUid('4ef3e654-0997-4...')
#15 /var/www/html/vendor/yiisoft/yii2/base/Component.php(180): craft\fieldlayoutelements\CustomField->setFieldUid('4ef3e654-0997-4...')
#16 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('fieldUid', '4ef3e654-0997-4...')
#17 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\fieldlayoutelements\CustomField), Array)
#18 /var/www/html/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#19 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(73): craft\base\Model->__construct(Array)
#20 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(47): craft\fieldlayoutelements\BaseField->__construct(Array)
#21 [internal function]: craft\fieldlayoutelements\CustomField->__construct(NULL, Array)
#22 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#23 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\fieldlayo...', Array, Array)
#24 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\fieldlayo...', Array, Array)
#25 /var/www/html/vendor/craftcms/cms/src/Craft.php(56): yii\BaseYii::createObject(Array, Array)
#26 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(974): Craft::createObject(Array)
#27 /var/www/html/vendor/craftcms/cms/src/models/FieldLayoutTab.php(254): craft\services\Fields->createLayoutElement(Array)
#28 /var/www/html/vendor/yiisoft/yii2/base/Component.php(180): craft\models\FieldLayoutTab->setElements(Array)
#29 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('elements', Array)
#30 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\models\FieldLayoutTab), Array)
#31 /var/www/html/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#32 /var/www/html/vendor/craftcms/cms/src/models/FieldLayoutTab.php(122): craft\base\Model->__construct(Array)
#33 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(864): craft\models\FieldLayoutTab->__construct(Array)
#34 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(790): craft\services\Fields->_legacyTabsByLayoutId(Object(craft\models\FieldLayout))
#35 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(878): craft\services\Fields->_layouts()
#36 /var/www/html/vendor/craftcms/cms/src/migrations/m230511_000000_field_layout_configs.php(25): craft\services\Fields->getAllLayouts()
#37 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\m230511_000000_field_layout_configs->safeUp()
#38 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#39 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(365): yii\console\controllers\BaseMigrateController->migrateUp('m230511_000000_...')
#40 [internal function]: craft\console\controllers\MigrateController->actionAll()
#41 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#42 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#43 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#44 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('all', Array)
#45 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#46 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#47 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#48 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#49 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(208): yii\base\Controller->run('migrate/all', Array)
#50 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(66): craft\console\Controller->run('migrate/all', Array)
#51 [internal function]: craft\console\controllers\UpController->actionIndex()
#52 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#53 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#54 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#55 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('', Array)
#56 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(217): craft\console\Controller->traitRunAction('', Array)
#57 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#58 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#59 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('up', Array)
#60 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#61 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#62 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#63 /var/www/html/craft(13): yii\base\Application->run()
#64 {main}
*** failed to apply m230511_000000_field_layout_configs (time: 0.041s)
```

### Craft CMS version

5.0.0-alpha.2

### PHP version

8.0.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.3 is out with a fix for this. Thanks for reporting!
