### ISSUE TITLE
[5.0.0-alpha.4]: Can't add 'New custom source'

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14108]
### Description

Trying to add a new custom source to the entries index, there is this JS error:

```
VM270:1 Uncaught TypeError: Cannot read properties of null (reading 'closest')
    at initNode (<anonymous>:1:26220)
    at Object.processNode [as process] (<anonymous>:1:26793)
    at <anonymous>:12:6
    at m (jquery.js?v=1704394988:2:867)
    at Pe (jquery.js?v=1704394988:2:48869)
    at w.fn.init.append (jquery.js?v=1704394988:2:50073)
    at Object.<anonymous> (Craft.js:1913:13)
    at u (Craft.js:2:1)
    at Generator.<anonymous> (Craft.js:2:1)
    at Generator.next (Craft.js:2:1)
```

### Steps to reproduce

1. Goto entries index
2. -> Customize sources
3. -> New custom source -> causes error
4. Can't add filter criteria

/Karla

### Craft CMS version

5.0.0-alpha.4

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.0.0-alpha.5 is out now with a fix.
