### ISSUE TITLE
[5.x]: Invalid path alias: @craft/console/controllers

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#14189]
### Description
When running the `craft` command to get an overview of the available commands, an error is getting thrown.

```
Exception 'yii\base\InvalidArgumentException' with message 'Invalid path alias: @craft/console/controllers'

in /var/www/html/vendor/yiisoft/yii2/BaseYii.php:154

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/base/Module.php(261): yii\BaseYii::getAlias('@craft/console/...')
#1 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(245): yii\base\Module->getControllerPath()
#2 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(172): yii\console\controllers\HelpController->getModuleCommands(Object(craft\console\Application))
#3 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(192): yii\console\controllers\HelpController->getCommands()
#4 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(292): yii\console\controllers\HelpController->getCommandDescriptions()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#6 /var/www/html/vendor/craftcms/cms/src/console/controllers/HelpController.php(87): yii\console\controllers\HelpController->actionIndex(NULL)
#7 [internal function]: craft\console\controllers\HelpController->actionIndex(NULL)
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('', Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('', Array)
#13 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('', Array)
#14 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('', Array)
#15 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#17 /var/www/html/craft(13): yii\base\Application->run()
#18 {main}
```

When running a direct command eg. `craft up` everything still works fine.

### Craft CMS version

5.0.0-alpha.8

### PHP version

8.3.2

### Operating system and version

Ubuntu 22.04

### Database type and version

mysql 8.0.32

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.9 was just released with that fix. Thanks again!
