### ISSUE TITLE
[4.x]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1329758-1' for key 'revisions_sourceId_num_unq_idx'

### ISSUE THREAD

**Issue by alexanderbuergin** [craftcms/cms#14309]
### Description

Unfortunately, an error occurs when saving some entries. But with others we can save the entries without any problems.

```
Integrity constraint violation – [yii\db\IntegrityException](https://www.yiiframework.com/doc-2.0/yii-db-integrityexception.html)
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1329758-1' for key 'revisions_sourceId_num_unq_idx'
The SQL being executed was: INSERT INTO `revisions` (`canonicalId`, `creatorId`, `num`, `notes`) VALUES (1329758, 1325965, 1, NULL)
Error Info: Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry '1329758-1' for key 'revisions_sourceId_num_unq_idx'

```

### Steps to reproduce

1. One of my ideas was to remove all revisions from the DB, but unfortunately this didn't make things any better, but rather worse.
2. Save an entry as draft and then save it into the main entry

### Craft CMS version

4.7.1

### PHP version

8.1

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I’m unable to reproduce this on a clean `4.7.1` installation. Could you please send your `composer.lock`, `composer.json` and database export to support@craftcms.com and point to one or two entries that give you this error when saving so we can replicate and see what’s going on?

**Comment by i-just** [comment]
@alexanderbuergin - I replied to your email.

For posterity, it looks to be related to this one: https://github.com/spicywebau/craft-neo/issues/813

**Comment by ttempleton** [comment]
Per my comments from https://github.com/spicywebau/craft-neo/issues/813#issuecomment-1965679290, the issue is that [the garbage collection event is triggered after the deletion of orphaned draft and revision data](https://github.com/craftcms/cms/blob/4.8.0/src/services/Gc.php#L136-L144), meaning that orphaned Neo revision data is not cleared out. I believe the proper fix to this error is for Craft to delete orphaned draft and revision data after the event has been triggered. As a short term solution, running `php craft gc/run` again will clean up that old revision data.

**Comment by stillhartkonzept** [comment]
also getting this.

**Comment by DavidKabelitz** [comment]
me too

**Comment by brandonkelly** [comment]
Thanks @ttempleton! Just made that change for the next v4 and v5 releases.

**Comment by brandonkelly** [comment]
Craft 4.9.3 and 5.1.3 are out with that fix. Thanks again.

**Comment by alexanderloewe** [comment]
Thx

**Comment by aaronELBorg** [comment]
Getting this error on Craft 4.10.4.  Perhaps I'm missing something?  Any help is appreciated.

**Comment by ryssbowh** [comment]
Still an issue on 4.16.11, can someone have a look ?

**Comment by brandonkelly** [comment]
If you can send us your database backup and composer files, and steps to reproduce, we can look into it from there. (support@craftcms.com)

**Comment by ryssbowh** [comment]
I don't have a way to reproduce, it happens rarely but randomly.
All I can say is that it happens when we resave a bunch of entries at the same time.
We do that in a queue job.
We use Redis for mutex, I have a feeling it's related but can't say for sure.
It is very possible that another request is also resaving those entries at the same time.
Here is the full trace :
```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1559095-54' for key 'revisions_sourceId_num_unq_idx'
#0 /vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement::execute
#1 /vendor/yiisoft/yii2/db/Command.php(1320): yii\db\Command::internalExecute
#2 /vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command::execute
#3 /vendor/craftcms/cms/src/helpers/Db.php(978): craft\helpers\Db::insert
#4 /vendor/craftcms/cms/src/services/Revisions.php(141): craft\services\Revisions::createRevision
#5 /vendor/craftcms/cms/src/elements/Entry.php(2078): craft\elements\Entry::afterPropagate
#6 /vendor/craftcms/cms/src/services/Elements.php(3519): craft\services\Elements::_saveElementInternal
#7 /vendor/craftcms/cms/src/services/Elements.php(1108): craft\services\Elements::saveElement
#8 /modules/site/src/services/Packages.php(860): modules\site\services\Packages::resavePackages
#9 /modules/site/src/jobs/ResaveOrderPackagesJob.php(18): modules\site\jobs\ResaveOrderPackagesJob::execute
#10 /vendor/yiisoft/yii2-queue/src/Queue.php(243): yii\queue\Queue::handleMessage
#11 /vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\cli\Queue::execute
#12 /vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Command::actionExec
#13 [internal](0): call_user_func_array
#14 /vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#15 /vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Controller::runAction
#16 /vendor/yiisoft/yii2/console/Controller.php(180): yii\console\Controller::runAction
#17 /vendor/craftcms/cms/src/console/ControllerTrait.php(90): craft\queue\Command::runAction
#18 /vendor/yiisoft/yii2/base/Module.php(552): yii\base\Module::runAction
#19 /vendor/yiisoft/yii2/console/Application.php(180): yii\console\Application::runAction
#20 /vendor/craftcms/cms/src/console/Application.php(91): craft\console\Application::runAction
#21 /vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application::handleRequest
#22 /vendor/craftcms/cms/src/console/Application.php(122): craft\console\Application::handleRequest
#23 /vendor/yiisoft/yii2/base/Application.php(384): yii\base\Application::run
#24 /craft(13)

yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1559095-54' for key 'revisions_sourceId_num_unq_idx'
The SQL being executed was: INSERT INTO `revisions` (`canonicalId`, `creatorId`, `num`, `notes`) VALUES (1559095, NULL, 54, NULL)
#0 /vendor/yiisoft/yii2/db/Schema.php(676): yii\db\Schema::convertException
#1 /vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Command::internalExecute
#2 /vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command::execute
#3 /vendor/craftcms/cms/src/helpers/Db.php(978): craft\helpers\Db::insert
#4 /vendor/craftcms/cms/src/services/Revisions.php(141): craft\services\Revisions::createRevision
#5 /vendor/craftcms/cms/src/elements/Entry.php(2078): craft\elements\Entry::afterPropagate
#6 /vendor/craftcms/cms/src/services/Elements.php(3519): craft\services\Elements::_saveElementInternal
#7 /vendor/craftcms/cms/src/services/Elements.php(1108): craft\services\Elements::saveElement
#8 /modules/site/src/services/Packages.php(860): modules\site\services\Packages::resavePackages
#9 /modules/site/src/jobs/ResaveOrderPackagesJob.php(18): modules\site\jobs\ResaveOrderPackagesJob::execute
#10 /vendor/yiisoft/yii2-queue/src/Queue.php(243): yii\queue\Queue::handleMessage
#11 /vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\cli\Queue::execute
#12 /vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Command::actionExec
#13 [internal](0): call_user_func_array
#14 /vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#15 /vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Controller::runAction
#16 /vendor/yiisoft/yii2/console/Controller.php(180): yii\console\Controller::runAction
#17 /vendor/craftcms/cms/src/console/ControllerTrait.php(90): craft\queue\Command::runAction
#18 /vendor/yiisoft/yii2/base/Module.php(552): yii\base\Module::runAction
#19 /vendor/yiisoft/yii2/console/Application.php(180): yii\console\Application::runAction
#20 /vendor/craftcms/cms/src/console/Application.php(91): craft\console\Application::runAction
#21 /vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application::handleRequest
#22 /vendor/craftcms/cms/src/console/Application.php(122): craft\console\Application::handleRequest
#23 /vendor/yiisoft/yii2/base/Application.php(384): yii\base\Application::run
#24 /craft(13)
```

**Comment by angrybrad** [comment]
@ryssbowh 

> We use Redis for mutex, I have a feeling it's related but can't say for sure.

That’s likely. A stock Redis setup makes for a pretty poor distributed locking mechanism, requiring client-side libraries and server-side confirmation to work properly.

https://redis.io/docs/latest/develop/clients/patterns/distributed-locks/

This is why we don’t recommend it for a mutex. Unless you have a specific reason why you can’t, I’d suggest going with Craft’s default database-backed mutex driver.

**Comment by ryssbowh** [comment]
The reason was some rare database outages/slowness that were creating havoc if I remember correctly.
But that's good to know about Redis as mutex, we may revisit.
Thank you
