### ISSUE TITLE
[5.x]: When a new user tries to activate, it results in an error.

### ISSUE THREAD

**Issue by mersy** [craftcms/cms#14316]
### Description

I tried Spin Up Craft 5.0 Alpha.
https://github.com/khalwat/spin-up-craft-5.0-alpha

I created a new user, and copied activation URL.
I opened the link for activation, the attached error occurred.
![20240207-145528](https://github.com/craftcms/cms/assets/205165/24bcb24a-2d63-41c9-961f-d3217e674add)

### Steps to reproduce

1. Create User
2. Copy activation URL
3. Open the URL

### Expected behavior

Activate New User

### Actual behavior

Twig Runtime Error – [Twig\Error\RuntimeError](http://twig.sensiolabs.org/api/2.x/Twig/Error/RuntimeError.html)

```
Twig\Error\RuntimeError: Impossible to invoke a method ("getAutofocusPreferred") on a null variable. in /var/www/project/vendor/craftcms/cms/src/templates/_includes/forms/text.twig:20
Stack trace:
#0 /var/www/project/vendor/craftcms/cms/src/helpers/Template.php(129): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), NULL, 'getAutofocusPre...', Array, 'method', false, false)
#1 /var/www/project/storage/runtime/compiled_templates/7c/7ccb0e19528af7a57ce5c83e08ec0e0d.php(56): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), NULL, 'getAutofocusPre...', Array, 'method')
#2 /var/www/project/vendor/twig/twig/src/Template.php(394): __TwigTemplate_668ec6e08f97bcbfe4269eb56103845d->doDisplay(Array, Array)
#3 /var/www/project/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /var/www/project/storage/runtime/compiled_templates/7f/7f460ea7bf5ce4517f99cb1318bd32d9.php(40): Twig\Template->display(Array)
#5 /var/www/project/vendor/twig/twig/src/Template.php(394): __TwigTemplate_532499b3e3e880a6e4a5d8e832e74c56->doDisplay(Array, Array)
#6 /var/www/project/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /var/www/project/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#8 /var/www/project/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#9 /var/www/project/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#10 /var/www/project/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render('_includes/forms...', Array)
#11 /var/www/project/vendor/craftcms/cms/src/helpers/Cp.php(115): craft\web\View->renderTemplate('_includes/forms...', Array, 'cp')
#12 /var/www/project/vendor/craftcms/cms/src/helpers/Cp.php(1300): craft\helpers\Cp::renderTemplate('_includes/forms...', Array)
#13 /var/www/project/vendor/craftcms/cms/src/web/twig/variables/Cp.php(1110): craft\helpers\Cp::fieldHtml('template:_inclu...', Array)
#14 /var/www/project/vendor/twig/twig/src/Extension/CoreExtension.php(1607): craft\web\twig\variables\Cp->field('template:_inclu...', Array)
#15 /var/www/project/vendor/craftcms/cms/src/helpers/Template.php(129): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\twig\variables\Cp), 'field', Array, 'method', false, false)
#16 /var/www/project/storage/runtime/compiled_templates/df/df660c8fad92303314a8f854ebce3704.php(1257): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\twig\variables\Cp), 'field', Array, 'method')
#17 /var/www/project/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_7e7855cadb230b090189757c91330482->macro_field(Array, 'template:_inclu...')
#18 /var/www/project/storage/runtime/compiled_templates/df/df660c8fad92303314a8f854ebce3704.php(1347): twig_call_macro(Object(__TwigTemplate_7e7855cadb230b090189757c91330482), 'macro_field', Array, 213, Array, Object(Twig\Source))
#19 /var/www/project/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_7e7855cadb230b090189757c91330482->macro_passwordField(Array)
#20 /var/www/project/storage/runtime/compiled_templates/dd/dd7e30d5f39bba81e90103143d20179a.php(83): twig_call_macro(Object(__TwigTemplate_7e7855cadb230b090189757c91330482), 'macro_passwordF...', Array, 19, Array, Object(Twig\Source))
#21 /var/www/project/vendor/twig/twig/src/Template.php(171): __TwigTemplate_7860fa112da51086d92da961615e6aca->block_message(Array, Array)
#22 /var/www/project/storage/runtime/compiled_templates/3c/3cddf6402666f9753c3ab70bcea4aacb.php(62): Twig\Template->displayBlock('message', Array, Array)
#23 /var/www/project/vendor/twig/twig/src/Template.php(171): __TwigTemplate_38cd96582b5ae91b8d1d08b4aa61f2b3->block_body(Array, Array)
#24 /var/www/project/storage/runtime/compiled_templates/b0/b000dd781e1d2fe869d99a93b8505c1a.php(97): Twig\Template->displayBlock('body', Array, Array)
#25 /var/www/project/vendor/twig/twig/src/Template.php(394): __TwigTemplate_b70819ee3a173ba827feb845cb792ed0->doDisplay(Array, Array)
#26 /var/www/project/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#27 /var/www/project/storage/runtime/compiled_templates/3c/3cddf6402666f9753c3ab70bcea4aacb.php(48): Twig\Template->display(Array, Array)
#28 /var/www/project/vendor/twig/twig/src/Template.php(394): __TwigTemplate_38cd96582b5ae91b8d1d08b4aa61f2b3->doDisplay(Array, Array)
#29 /var/www/project/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#30 /var/www/project/storage/runtime/compiled_templates/dd/dd7e30d5f39bba81e90103143d20179a.php(54): Twig\Template->display(Array, Array)
#31 /var/www/project/vendor/twig/twig/src/Template.php(394): __TwigTemplate_7860fa112da51086d92da961615e6aca->doDisplay(Array, Array)
#32 /var/www/project/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#33 /var/www/project/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#34 /var/www/project/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#35 /var/www/project/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#36 /var/www/project/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render('setpassword.twi...', Array)
#37 /var/www/project/vendor/craftcms/cms/src/web/View.php(535): craft\web\View->renderTemplate('setpassword.twi...', Array)
#38 /var/www/project/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('setpassword.twi...', Array, 'cp')
#39 /var/www/project/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#40 /var/www/project/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#41 /var/www/project/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#42 /var/www/project/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#43 /var/www/project/web/index.php(12): yii\base\Application->run()
#44 {main}
```

### Craft CMS version

5.0.0-alpha.13

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I just raised a PR for this.

**Comment by brandonkelly** [comment]
We just tagged Craft 5.0.0-beta.1 which includes the fix for this.
