### ISSUE TITLE
[5.0.0-beta.3]: Deletion of Matrix block with nested entries causes error in revision

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14494]
### What happened?

When the author deletes a Matrix block with nested entries and later tries to go back to a revision where the block is not deleted, she is presented with an error like the one below:

```
yii\base\InvalidConfigException: Invalid owner ID: 1653 in /var/www/html/vendor/craftcms/cms/src/base/NestedElementTrait.php:117
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/base/NestedElementTrait.php(162): craft\elements\Entry->getPrimaryOwner()
#1 /var/www/html/vendor/craftcms/cms/src/base/NestedElementTrait.php(192): craft\elements\Entry->getOwner()
#2 /var/www/html/vendor/craftcms/cms/src/base/Element.php(3243): craft\elements\Entry->getField()
#3 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1636): craft\base\Element->canView()
#4 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(4138): craft\elements\Entry->canView()
#5 /var/www/html/vendor/craftcms/cms/src/helpers/Cp.php(660): craft\services\Elements->canView()
#6 /var/www/html/vendor/craftcms/cms/src/helpers/Cp.php(535): craft\helpers\Cp::baseElementAttributes()
#7 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(371): craft\helpers\Cp::elementCardHtml()
#8 [internal function]: craft\elements\NestedElementManager->craft\elements\{closure}()
#9 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(370): array_map()
#10 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(567): craft\elements\NestedElementManager->craft\elements\{closure}()
#11 /var/www/html/vendor/craftcms/cms/src/web/View.php(1669): craft\elements\NestedElementManager->craft\elements\{closure}()
#12 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(520): craft\web\View->namespaceInputs()
#13 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(345): craft\elements\NestedElementManager->createView()
#14 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(909): craft\elements\NestedElementManager->getCardsHtml()
#15 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(1046): craft\fields\Matrix->nestedElementManagerHtml()
#16 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(352): craft\fields\Matrix->getStaticHtml()
#17 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(350): craft\fieldlayoutelements\CustomField->inputHtml()
#18 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(313): craft\fieldlayoutelements\BaseField->formHtml()
#19 /var/www/html/vendor/craftcms/cms/src/web/View.php(1669): craft\fieldlayoutelements\CustomField->craft\fieldlayoutelements\{closure}()
#20 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(312): craft\web\View->namespaceInputs()
#21 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(832): craft\fieldlayoutelements\CustomField->formHtml()
#22 /var/www/html/vendor/craftcms/cms/src/web/View.php(1663): craft\models\FieldLayout->craft\models\{closure}()
#23 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(831): craft\web\View->namespaceInputs()
#24 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1635): craft\models\FieldLayout->createForm()
#25 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(129): twig_get_attribute()
#26 /var/www/html/storage/runtime/compiled_templates/be/be906b2c055e7e4aeb0542c4cc98b47c.php(114): craft\helpers\Template::attribute()
#27 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_5c7f548cd54943de9cf538eb909c86aa->doDisplay()
#28 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#29 /var/www/html/storage/runtime/compiled_templates/35/35c06fd82cabcbdfc6f4b8d6ef7f293f.php(77): Twig\Template->display()
#30 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_6b55ba24d6c725d520f52bf045425f51->doDisplay()
#31 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#32 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#33 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#34 /var/www/html/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render()
#35 /var/www/html/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render()
#36 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(1070): craft\web\View->renderTemplate()
#37 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(352): craft\fields\Matrix->getStaticHtml()
#38 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(350): craft\fieldlayoutelements\CustomField->inputHtml()
#39 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(313): craft\fieldlayoutelements\BaseField->formHtml()
#40 /var/www/html/vendor/craftcms/cms/src/web/View.php(1669): craft\fieldlayoutelements\CustomField->craft\fieldlayoutelements\{closure}()
#41 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(312): craft\web\View->namespaceInputs()
#42 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(832): craft\fieldlayoutelements\CustomField->formHtml()
#43 /var/www/html/vendor/craftcms/cms/src/web/View.php(1663): craft\models\FieldLayout->craft\models\{closure}()
#44 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(831): craft\web\View->namespaceInputs()
#45 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(923): craft\models\FieldLayout->createForm()
#46 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(397): craft\controllers\ElementsController->_prepareEditor()
#47 [internal function]: craft\controllers\ElementsController->craft\controllers\{closure}()
#48 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(124): call_user_func()
#49 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(50): craft\web\CpScreenResponseFormatter->_formatTemplate()
#50 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\CpScreenResponseFormatter->format()
#51 /var/www/html/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#52 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#53 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#54 /var/www/html/web/index.php(12): yii\base\Application->run()
#55 {main}
```

### Craft CMS version

5.0.0-beta.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! 5.0.0-beta.4 is out with a fix.
