### ISSUE TITLE
[5.x]: ReferenceError when creating new field via FLD

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14933]
### Description

When creating a new field via a field layout designer, a JS ReferenceError is thrown. Not sure if it actually affects anything.

```
FieldLayoutDesigner.js:287  Uncaught (in promise) ReferenceError: designer is not defined
    at FieldLayoutDesigner.js:287:15
    at u (FieldLayoutDesigner.js:2:1)
    at Generator.<anonymous> (FieldLayoutDesigner.js:2:1)
    at Generator.next (FieldLayoutDesigner.js:2:1)
    at asyncGeneratorStep (FieldLayoutDesigner.js:2:1)
    at s (FieldLayoutDesigner.js:2:1)
    at FieldLayoutDesigner.js:2:1
    at new Promise (<anonymous>)
    at Object.<anonymous> (FieldLayoutDesigner.js:2:1)
    at Object.handler (FieldLayoutDesigner.js:293:8)
(anonymous) @ FieldLayoutDesigner.js:287
u @ FieldLayoutDesigner.js:2
(anonymous) @ FieldLayoutDesigner.js:2
(anonymous) @ FieldLayoutDesigner.js:2
asyncGeneratorStep @ FieldLayoutDesigner.js:2
s @ FieldLayoutDesigner.js:2
(anonymous) @ FieldLayoutDesigner.js:2
(anonymous) @ FieldLayoutDesigner.js:2
(anonymous) @ FieldLayoutDesigner.js:293
trigger @ Base.js:83
handleSubmitResponse @ CpScreenSlideout.js:556
(anonymous) @ CpScreenSlideout.js:537
Promise.then (async)
submit @ CpScreenSlideout.js:536
(anonymous) @ CpScreenSlideout.js:515
setTimeout (async)
handleSubmit @ CpScreenSlideout.js:514
(anonymous) @ Base.js:153
o @ jquery.js?v=1714682107:2
dispatch @ jquery.js?v=1714682107:2
v.handle @ jquery.js?v=1714682107:2
```

### Steps to reproduce

1. Edit an entry type
2. In the entry type FLD, click "New field"
3. Create a simple Plain Text field and click "Save" in the slideout
4. See error in dev tools console

### Craft CMS version

5.1.0

### Operating system and version

macOS 14.3.1, MS Edge 124.0.2478.67

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Fixed in 5.1.1!
