### ISSUE TITLE
[5.x]: 

### ISSUE THREAD

**Issue by bhashkar007** [craftcms/cms#14938]
### Description
I upgraded a website to Craft 5 which is using tag `craft.app.sections.getSectionByHandle` to get section object and it's throwing error.
```
Twig\Error\RuntimeError: Calling unknown method: craft\web\Application::sections() in /var/www/html/templates/_objecten.twig:10
Stack trace:
#0 /var/www/html/storage/runtime/compiled_templates/12/12269de7a6db3cd1222bf27b667687ef.php(59): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\Application), 'sections', Array, 'any', false, false, false, 10)
#1 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_47453b1b76f931f8969aa8e57d575250->block_content(Array, Array)
#2 /var/www/html/storage/runtime/compiled_templates/45/45aa12ce35222bb6d77a19031c21758f.php(109): Twig\Template->displayBlock('content', Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_adf7c1a13fdb209168acbd409a036b08->doDisplay(Array, Array)
#4 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#5 /var/www/html/storage/runtime/compiled_templates/12/12269de7a6db3cd1222bf27b667687ef.php(43): Twig\Template->display(Array, Array)
#6 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_47453b1b76f931f8969aa8e57d575250->doDisplay(Array, Array)
#7 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#8 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#9 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#10 /var/www/html/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render(Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render('_objecten', Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/View.php(535): craft\web\View->renderTemplate('_objecten', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('_objecten', Array, 'site')
#14 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#15 /var/www/html/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#16 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#18 /var/www/html/web/index.php(12): yii\base\Application->run()
#19 {main}
```

### Steps to reproduce

1. Use `{% set section = craft.app.sections.getSectionByHandle("SectionHandle") %}` to get `section` object

### Expected behavior

It should return section object.

### Craft CMS version

5.1.1

### PHP version

8.2.18

### Installed plugins and versions

- Contact Form v3.1.0
- Redactor v4.0.0

**Comment by brandonkelly** [comment]
The `sections` service went away in Craft 5, and the relevant methods (including `getSectionByHandle()` were moved to the `entries` service. So you can update your code to this, to get it working again:

```twig
{% set section = craft.app.entries.getSectionByHandle("SectionHandle") %}
```
