### ISSUE TITLE
[5.x]: User Addresses causes error: Method craft\elements\ElementCollection::status does not exist

### ISSUE THREAD

**Issue by alexroper** [craftcms/cms#15021]
### Description

I'm getting the following error in the control panel when I go to the Addresses tab in a User account: 

```
BadMethodCallException

Method craft\elements\ElementCollection::status does not exist.
```

#### Stack Trace

```
BadMethodCallException: Method craft\elements\ElementCollection::status does not exist. in /var/www/html/vendor/illuminate/macroable/Traits/Macroable.php:112
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(387): Illuminate\Support\Collection->__call('status', Array)
#1 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(588): craft\elements\NestedElementManager->craft\elements\{closure}('element-index-1...', Array, 'addresses', Array)
#2 /var/www/html/vendor/craftcms/cms/src/web/View.php(1669): craft\elements\NestedElementManager->craft\elements\{closure}()
#3 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(541): craft\web\View->namespaceInputs(Object(Closure), 'addresses')
#4 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(362): craft\elements\NestedElementManager->createView(Object(craft\elements\User), Array, 'cards', Object(Closure))
#5 /var/www/html/vendor/craftcms/cms/src/controllers/UsersController.php(1033): craft\elements\NestedElementManager->getCardsHtml(Object(craft\elements\User), Array)
#6 [internal function]: craft\controllers\UsersController->craft\controllers\{closure}()
#7 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(133): call_user_func(Object(Closure))
#8 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(50): craft\web\CpScreenResponseFormatter->_formatTemplate(Object(craft\web\Response), Object(craft\web\CpScreenResponseBehavior))
#9 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\CpScreenResponseFormatter->format(Object(craft\web\Response))
#10 /var/www/html/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#11 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#12 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#13 /var/www/html/web/index.php(12): yii\base\Application->run()
#14 {main}
```

### Steps to reproduce

1. In the control panel, go to Users > any user account
2. Click the Addresses tab.

### Expected behavior

Should show addresses.

### Actual behavior

Shows an error.

### Craft CMS version

Craft Pro 5.1.3

### PHP version

8.2.18

### Operating system and version

Linux 6.6.26-linuxkit

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Anchors 3.4.0
- Asset Rev 8.0.0
- CKEditor 4.0.6
- Retcon 3.0.0
- Table of contents 3.0.0

**Comment by alexroper** [comment]
Never mind. This issue was resolved in the version 5.1.4 update (issue #15018).
