### ISSUE TITLE
[3.x]: add ownerId Filter to the query with 'not ID'. .ownderId("not 1") for example

### ISSUE THREAD

**Issue by leonwetterich** [craftcms/cms#15197]
### Description
When trying to query for the ownerId of matrix blocks and exclude with the 'not' key an error is thrown and does not exclude the provided id's

### Steps to reproduce

1. Create a Matrix block
2. Create Twig Template
3. Write a query for matrix blocks
4. add ownerId Filter to the query with 'not * id*'

Example Code:
```
{% set upcomingEventDates = craft.matrixBlocks()
    .ownerId(['not', 751352])
    .field('eventDates')
    .startDate('>= now')
    .orderBy('startDate asc')
    .all()
%}
```

### Expected behavior
Expected is that the query returns all Matrix blocks where the owner id is not equal to the one/s provided.
According to the documenation, this should work [Docs Entry](https://craftcms.com/docs/3.x/matrix-blocks.html#ownerid)

### Actual behavior
An error is thrown (Invalid ownerId param value)

### Craft CMS version

3.9.13

### PHP version

7.4.33

### Operating system and version

Linux 6.6.26-linuxkit

### Database type and version

MariaDB 5.5.5

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by michtio** [comment]
@leonwetterich could you post a stack trace of the error you are encountering?

**Comment by leonwetterich** [comment]
@michtio sure.

```
yii\base\InvalidConfigException: Invalid ownerId param value in /var/www/html/craft/vendor/craftcms/cms/src/elements/db/MatrixBlockQuery.php:564
Stack trace:
#0 /var/www/html/craft/vendor/craftcms/cms/src/elements/db/MatrixBlockQuery.php(460): craft\elements\db\MatrixBlockQuery->_normalizeOwnerId()
#1 /var/www/html/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1464): craft\elements\db\MatrixBlockQuery->beforePrepare()
#2 /var/www/html/craft/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#3 /var/www/html/craft/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\MatrixBlockQuery))
#4 /var/www/html/craft/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Query->createCommand(Object(craft\db\Connection))
#5 /var/www/html/craft/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all(NULL)
#6 /var/www/html/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1655): craft\db\Query->all(NULL)
#7 /var/www/html/craft/vendor/twig/twig/src/Extension/CoreExtension.php(1570): craft\elements\db\ElementQuery->all()
#8 /var/www/html/craft/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\MatrixBlockQuery), 'all', Array, 'method', false, false)
#9 /var/www/html/craft/storage/runtime/compiled_templates/6e/6ec085a442179636a9e574835a5f94fc298a2690cccc57844b9a5e17521b3991.php(483): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\MatrixBlockQuery), 'all', Array, 'method')
#10 /var/www/html/craft/vendor/twig/twig/src/Template.php(182): __TwigTemplate_3349db1f74d8e9379923c7c029677912809472bdf52b73b4ab6ae6351e0c6994->block_main(Array, Array)
#11 /var/www/html/craft/storage/runtime/compiled_templates/bf/bf011fe6a311981f66a6e52bffb8e12345a777fc0f33b89283b4b4c41bd3d400.php(211): Twig\Template->displayBlock('main', Array, Array)
#12 /var/www/html/craft/vendor/twig/twig/src/Template.php(405): __TwigTemplate_4a1165ad8f4fed9c240ce9c86c9f2d24c3b0d67dda2d93310ffc2f8a7397653c->doDisplay(Array, Array)
#13 /var/www/html/craft/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /var/www/html/craft/storage/runtime/compiled_templates/6e/6ec085a442179636a9e574835a5f94fc298a2690cccc57844b9a5e17521b3991.php(49): Twig\Template->display(Array, Array)
#15 /var/www/html/craft/vendor/twig/twig/src/Template.php(405): __TwigTemplate_3349db1f74d8e9379923c7c029677912809472bdf52b73b4ab6ae6351e0c6994->doDisplay(Array, Array)
#16 /var/www/html/craft/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /var/www/html/craft/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#18 /var/www/html/craft/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#19 /var/www/html/craft/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#20 /var/www/html/craft/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('offerings/_over...', Array)
#21 /var/www/html/craft/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('offerings/_over...', Array)
#22 /var/www/html/craft/vendor/craftcms/cms/src/web/Controller.php(216): craft\web\View->renderPageTemplate('offerings/_over...', Array, 'site')
#23 /var/www/html/craft/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate('offerings/_over...', Array)
#24 [internal function]: craft\controllers\TemplatesController->actionRender('offerings/_over...', Array)
#25 /var/www/html/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#26 /var/www/html/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#27 /var/www/html/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#28 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction('templates/rende...', Array)
#29 /var/www/html/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#30 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(280): yii\web\Application->handleRequest(Object(craft\web\Request))
#31 /var/www/html/craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#32 /var/www/html/craft/web/index.php(12): yii\base\Application->run()
#33 {main}
```

**Comment by brandonkelly** [comment]
Hey @leonwetterich, apologies but that syntax isn’t supported by the code. `ownerId` can only be set to a specific ID or array of IDs; no `not` prefix allowed.

The docs for the param were incorrectly stating that `'not 1'` and `['not', 1, 2]` synatxes were allowed, but there was nothing in the code to handle that.

I’ve updated the docs for the next v3, v4, and v5 releases.
