### ISSUE TITLE
[5.x]: Craft 4 to 5 staging deploy fails with "Unknown column 'fields.groupId' in 'field list'"

### ISSUE THREAD

**Issue by wuhhh** [craftcms/cms#15255]
### Description

I am upgrading a client site from 4 to 5. Went through the checklist as normal and got everything working locally without too much trouble. Made sure live and stage environments were updated as far as latest 4.x CMS and plugin versions ready to deploy the v5 updates on those.

Unfortunately I'm now stuck and unable to get a working deploy on stage (Hetzner & Laravel Forge). The auto deploy scripts running are:

```
cd /home/forge/latch.rootsy.co.uk
git pull origin $FORGE_SITE_BRANCH

$FORGE_COMPOSER install --no-dev --no-interaction --prefer-dist --optimize-autoloader

. ~/.nvm/nvm.sh
nvm use 18.20.3
npm i
npm run prod
./craft up
```

### Expected behavior

Expect the deploy to run as normal as it has done up to the point of this commit with the v4 to v5 changes

### Actual behavior

Produces the `An internal server error occurred.` message at the front end

Server log shows:

```
Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fields.groupId' in 'field list'
The SQL being executed was: SELECT `fields`.`id`, `fields`.`dateCreated`, `fields`.`dateUpdated`, `fields`.`groupId`, `fields`.`name`, `fields`.`handle`, `fields`.`context`, `fields`.`columnSuffix`, `fields`.`instructions`, `fields`.`searchable`, `fields`.`translationMethod`, `fields`.`translationKeyFormat`, `fields`.`type`, `fields`.`settings`, `fields`.`uid`
FROM `fields` `fields`
ORDER BY `fields`.`name`, `fields`.`handle` in /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException()
#1 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute()
#2 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/db/Command.php(417): yii\db\Command->queryInternal()
#3 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/db/Query.php(252): yii\db\Query->all()
#5 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/services/Fields.php(624): craft\db\Query->all()
#6 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/services/Fields.php(649): craft\services\Fields->_fields()
#7 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2236): craft\services\Fields->getAllFields()
#8 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1449): craft\elements\db\ElementQuery->customFields()
#9 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
#10 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
#11 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand()
#12 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/db/Query.php(280): yii\db\Query->one()
#13 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1655): craft\db\Query->one()
#14 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/elements/User.php(546): craft\elements\db\ElementQuery->one()
#15 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/web/User.php(699): craft\elements\User::findIdentity()
#16 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/web/User.php(500): yii\web\User->renewAuthStatus()
#17 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#18 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/web/Application.php(436): yii\web\User->getIdentity()
#19 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->debugBootstrap()
#20 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#21 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#22 [internal function]: yii\base\Application->__construct()
#23 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#24 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#25 /home/forge/latch.rootsy.co.uk/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#26 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/src/Craft.php(59): yii\BaseYii::createObject()
#27 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/bootstrap/bootstrap.php(264): Craft::createObject()
#28 /home/forge/latch.rootsy.co.uk/vendor/craftcms/cms/bootstrap/web.php(40): require('...')
#29 /home/forge/latch.rootsy.co.uk/web/index.php(11): require('...')
#30 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'fields.groupId' in 'field list'
)
```

### Craft CMS version

5.2.3

### PHP version

8.2 local, 8.3 stage

### Database type and version

MariaDB 10.5.24 local, MySQL 8.0.37 stage

**Comment by wuhhh** [comment]
Facepalm - this looks like it was caused by the php platform value in `composer.json` not matching stage, and stage not having that version installed. I installed it and presto, the error vanishes. I guess it would be better to remove this altogether as noted in the upgrade guide.
