### ISSUE TITLE
[5.x]: postgres exception during upgrade from v4 to v5 

### ISSUE THREAD

**Issue by burningchair** [craftcms/cms#15262]
### Description

Upgrade of craft4 to craft5 fails with a postgres (14) db exception (`Insufficient privilege: 7 ERROR:  permission denied`) while applying migrations

I am able to perform the upgrade if I grant the db-user superuser permissions:
`ALTER USER craftcms WITH SUPERUSER;`

### Steps to reproduce

1. Create user and db and make the user owner of the database (`create database db; create user craftcms identified by 'password'; alter database db owner craftcms; `
2. Install craft v4
3. Update to craft v5

### Expected behavior
Not needing any special permissions for upgrade (ownership of database should be enough) or some hint in the upgrade documentation

### Actual behavior
`php craft up` causes
`Exception: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied: "RI_ConstraintTrigger_c_46854" is a system trigger`

### Full Exception
```
Exception: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied: "RI_ConstraintTrigger_c_46854" is a system trigger
The SQL being executed was: ALTER TABLE "public"."addresses" DISABLE TRIGGER ALL; ALTER TABLE "public"."announcements" DISABLE TRIGGER ALL; ALTER TABLE "public"."assetindexdata" DISABLE TRIGGER ALL; ALTER TABLE "public"."assetindexingsessions" DISABLE TRIGGER ALL; ALTER TABLE "public"."assets" DISABLE TRIGGER ALL; ALTER TABLE "public"."assets_sites" DISABLE TRIGGER ALL; ALTER TABLE "public"."authenticator" DISABLE TRIGGER ALL; ALTER TABLE "public"."categories" DISABLE TRIGGER ALL; ALTER TABLE "public"."categorygroups" DISABLE TRIGGER ALL; ALTER TABLE "public"."categorygroups_sites" DISABLE TRIGGER ALL; ALTER TABLE "public"."changedattributes" DISABLE TRIGGER ALL; ALTER TABLE "public"."changedfields" DISABLE TRIGGER ALL; ALTER TABLE "public"."comments_comments" DISABLE TRIGGER ALL; ALTER TABLE "public"."comments_flags" DISABLE TRIGGER ALL; ALTER TABLE "public"."comments_subscribe" DISABLE TRIGGER ALL; ALTER TABLE "public"."comments_votes" DISABLE TRIGGER ALL; ALTER TABLE "public"."craftidtokens" DISABLE TRIGGER ALL; ALTER TABLE "public"."deprecationerrors" DISABLE TRIGGER ALL; ALTER TABLE "public"."drafts" DISABLE TRIGGER ALL; ALTER TABLE "public"."elementactivity" DISABLE TRIGGER ALL; ALTER TABLE "public"."elements" DISABLE TRIGGER ALL; ALTER TABLE "public"."elements_owners" DISABLE TRIGGER ALL; ALTER TABLE "public"."elements_sites" DISABLE TRIGGER ALL; ALTER TABLE "public"."entries" DISABLE TRIGGER ALL; ALTER TABLE "public"."entries_authors" DISABLE TRIGGER ALL; ALTER TABLE "public"."entrytypes" DISABLE TRIGGER ALL; ALTER TABLE "public"."feedme_feeds" DISABLE TRIGGER ALL; ALTER TABLE "public"."fieldlayouts" DISABLE TRIGGER ALL; ALTER TABLE "public"."fields" DISABLE TRIGGER ALL; ALTER TABLE "public"."globalsets" DISABLE TRIGGER ALL; ALTER TABLE "public"."gqlschemas" DISABLE TRIGGER ALL; ALTER TABLE "public"."gqltokens" DISABLE TRIGGER ALL; ALTER TABLE "public"."imagetransformindex" DISABLE TRIGGER ALL; ALTER TABLE "public"."imagetransforms" DISABLE TRIGGER ALL; ALTER TABLE "public"."info" DISABLE TRIGGER ALL; ALTER TABLE "public"."maps" DISABLE TRIGGER ALL; ALTER TABLE "public"."matrixblocks" DISABLE TRIGGER ALL; ALTER TABLE "public"."matrixblocks_owners" DISABLE TRIGGER ALL; ALTER TABLE "public"."matrixblocktypes" DISABLE TRIGGER ALL; ALTER TABLE "public"."migrations" DISABLE TRIGGER ALL; ALTER TABLE "public"."plugins" DISABLE TRIGGER ALL; ALTER TABLE "public"."projectconfig" DISABLE TRIGGER ALL; ALTER TABLE "public"."queue" DISABLE TRIGGER ALL; ALTER TABLE "public"."recoverycodes" DISABLE TRIGGER ALL; ALTER TABLE "public"."relations" DISABLE TRIGGER ALL; ALTER TABLE "public"."resourcepaths" DISABLE TRIGGER ALL; ALTER TABLE "public"."revisions" DISABLE TRIGGER ALL; ALTER TABLE "public"."searchindex" DISABLE TRIGGER ALL; ALTER TABLE "public"."sections" DISABLE TRIGGER ALL; ALTER TABLE "public"."sections_entrytypes" DISABLE TRIGGER ALL; ALTER TABLE "public"."sections_sites" DISABLE TRIGGER ALL; ALTER TABLE "public"."sequences" DISABLE TRIGGER ALL; ALTER TABLE "public"."sessions" DISABLE TRIGGER ALL; ALTER TABLE "public"."shunnedmessages" DISABLE TRIGGER ALL; ALTER TABLE "public"."sitegroups" DISABLE TRIGGER ALL; ALTER TABLE "public"."sites" DISABLE TRIGGER ALL; ALTER TABLE "public"."structureelements" DISABLE TRIGGER ALL; ALTER TABLE "public"."structures" DISABLE TRIGGER ALL; ALTER TABLE "public"."systemmessages" DISABLE TRIGGER ALL; ALTER TABLE "public"."taggroups" DISABLE TRIGGER ALL; ALTER TABLE "public"."tags" DISABLE TRIGGER ALL; ALTER TABLE "public"."tokens" DISABLE TRIGGER ALL; ALTER TABLE "public"."usergroups" DISABLE TRIGGER ALL; ALTER TABLE "public"."usergroups_users" DISABLE TRIGGER ALL; ALTER TABLE "public"."userpermissions" DISABLE TRIGGER ALL; ALTER TABLE "public"."userpermissions_usergroups" DISABLE TRIGGER ALL; ALTER TABLE "public"."userpermissions_users" DISABLE TRIGGER ALL; ALTER TABLE "public"."userpreferences" DISABLE TRIGGER ALL; ALTER TABLE "public"."users" DISABLE TRIGGER ALL; ALTER TABLE "public"."volumefolders" DISABLE TRIGGER ALL; ALTER TABLE "public"."volumes" DISABLE TRIGGER ALL; ALTER TABLE "public"."webauthn" DISABLE TRIGGER ALL; ALTER TABLE "public"."widgets" DISABLE TRIGGER ALL; 
```

### Craft CMS version

5.2.2

### PHP version

8.2

### Operating system and version

Ubuntu 23.10

### Database type and version

Postgres 14

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 5.2.4 is out with a fix for this. Thanks for reporting!

**Comment by burningchair** [comment]
Thanks for the fast fix, but I get another postgres error while upgrading to **5.2.4.1**:
```
> execute SQL: INSERT INTO {{%entries}} ([[id]], [[primaryOwnerId]], [[fieldId]], [[typeId]], [[postDate]], [[dateCreated]], [[dateUpdated]])
SELECT [[id]], [[primaryOwnerId]], [[fieldId]], CASE WHEN [[typeId]] = 11 THEN 28 WHEN [[typeId]] = 8 THEN 29 WHEN [[typeId]] = 9 THEN 30 WHEN [[typeId]] = 12 THEN 31 WHEN [[typeId]] = 2 THEN 32 WHEN [[typeId]] = 18 THEN 33 WHEN [[typeId]] = 20 THEN 34 WHEN [[typeId]] = 19 THEN 35 WHEN [[typeId]] = 10 THEN 36 WHEN [[typeId]] = 22 THEN 37 WHEN [[typeId]] = 24 THEN 38 WHEN [[typeId]] = 21 THEN 39 WHEN [[typeId]] = 1 THEN 40 WHEN [[typeId]] = 23 THEN 41 WHEN [[typeId]] = 13 THEN 42 WHEN [[typeId]] = 14 THEN 43 WHEN [[typeId]] = 16 THEN 44 WHEN [[typeId]] = 4 THEN 45 WHEN [[typeId]] = 5 THEN 46 WHEN [[typeId]] = 3 THEN 47 END, [[dateCreated]], [[dateCreated]], [[dateUpdated]]
FROM {{%matrixblocks}} matrixblocks
WHERE [[matrixblocks.typeId]] IN (11,8,9,12,2,18,20,19,10,22,24,21,1,23,13,14,16,4,5,3) ...Exception: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
The SQL being executed was: INSERT INTO "entries" ("id", "primaryOwnerId", "fieldId", "typeId", "postDate", "dateCreated", "dateUpdated")
SELECT "id", "primaryOwnerId", "fieldId", CASE WHEN "typeId" = 11 THEN 28 WHEN "typeId" = 8 THEN 29 WHEN "typeId" = 9 THEN 30 WHEN "typeId" = 12 THEN 31 WHEN "typeId" = 2 THEN 32 WHEN "typeId" = 18 THEN 33 WHEN "typeId" = 20 THEN 34 WHEN "typeId" = 19 THEN 35 WHEN "typeId" = 10 THEN 36 WHEN "typeId" = 22 THEN 37 WHEN "typeId" = 24 THEN 38 WHEN "typeId" = 21 THEN 39 WHEN "typeId" = 1 THEN 40 WHEN "typeId" = 23 THEN 41 WHEN "typeId" = 13 THEN 42 WHEN "typeId" = 14 THEN 43 WHEN "typeId" = 16 THEN 44 WHEN "typeId" = 4 THEN 45 WHEN "typeId" = 5 THEN 46 WHEN "typeId" = 3 THEN 47 END, "dateCreated", "dateCreated", "dateUpdated"
FROM "matrixblocks" matrixblocks
WHERE "matrixblocks"."typeId" IN (11,8,9,12,2,18,20,19,10,22,24,21,1,23,13,14,16,4,5,3) (/var/www/craft/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/craft/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException()
#1 /var/www/craft/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute()
#2 /var/www/craft/vendor/yiisoft/yii2/db/Migration.php(219): yii\db\Command->execute()
#3 /var/www/craft/vendor/craftcms/cms/src/migrations/m230617_070415_entrify_matrix_blocks.php(213): yii\db\Migration->execute()
#4 /var/www/craft/vendor/craftcms/cms/src/db/Migration.php(50): craft\migrations\m230617_070415_entrify_matrix_blocks->safeUp()
#5 /var/www/craft/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /var/www/craft/vendor/craftcms/cms/src/console/controllers/MigrateController.php(382): yii\console\controllers\BaseMigrateController->migrateUp()
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /var/www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#9 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#10 /var/www/craft/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#11 /var/www/craft/vendor/craftcms/cms/src/console/controllers/MigrateController.php(195): yii\console\Controller->runAction()
#12 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction()
#13 /var/www/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#14 /var/www/craft/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction()
#15 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction()
#16 /var/www/craft/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run()
#17 /var/www/craft/vendor/craftcms/cms/src/console/controllers/UpController.php(60): craft\console\Controller->run()
#18 [internal function]: craft\console\controllers\UpController->actionIndex()
#19 /var/www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#20 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#21 /var/www/craft/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#22 /var/www/craft/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction()
#23 /var/www/craft/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction()
#24 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction()
#25 /var/www/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#26 /var/www/craft/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction()
#27 /var/www/craft/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#28 /var/www/craft/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest()
#29 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#30 /var/www/craft/craft(27): yii\base\Application->run()
#31 {main}
*** failed to apply m230617_070415_entrify_matrix_blocks (time: 0.139s)


14 from 24 migrations were applied.

Migration failed. The rest of the migrations are canceled.

Restore a database backup before trying again.

Aborting remaining tasks.
```

The update works if I grant the db user (*craftcms*) superuser permissions

**Comment by brandonkelly** [comment]
@burningchair Thanks. Would you mind testing again with a [potential fix](https://github.com/craftcms/cms/commit/1925b9342b1fc8d34655938358c94c6c5db2b75e) in place?

To test, change your `craftcms/cms` requirement in composer.json to:

```json
"craftcms/cms": "dev-bugfix/15262-transaction as 5.2.4.1",
```

Then run `composer update`.

**Comment by burningchair** [comment]
@brandonkelly yes, now it works. thx!

**Comment by brandonkelly** [comment]
Thanks for testing! Craft 5.2.5 is out now with that fix.
