### ISSUE TITLE
[4.x]: Migration throws error relating to UserGroupEvent when removing a user group

### ISSUE THREAD

**Issue by russback** [craftcms/cms#15357]
### Description
Spotted this when working on different feature branches, so an edge case perhaps.

### Steps to reproduce

1. Create a new branch with a new user group.
2. Create a new user group and assign a user to that group (and that group only).
3. Switch to a different branch and run project config migration.

At this point, the following error is thrown in the console:

```
error: Cannot assign null to property craft\events\UserGroupEvent::$userGroup of type craft\models\UserGroup
Failed to run craft up: exit status 1
```

### Expected behavior
User group can be removed from project config without error.

### Actual behavior
Migration fails where users are assigned solely to the removed group.

### Craft CMS version

4.10.5

### PHP version

8.2.18

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Can you search for that error in `storage/logs/` and post the full stack trace that follows it?

**Comment by russback** [comment]
Does this help?

```
Stack trace:
#0 /var/www/html/deploy/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\events\UserGroupEvent), Array)
#1 /var/www/html/deploy/vendor/craftcms/cms/src/services/UserGroups.php(327): yii\base\BaseObject->__construct(Array)
#2 /var/www/html/deploy/vendor/craftcms/cms/src/base/ApplicationTrait.php(1856): craft\services\UserGroups->handleDeletedUserGroup(Object(craft\events\ConfigEvent))
#3 /var/www/html/deploy/vendor/craftcms/cms/src/services/ProjectConfig.php(1159): craft\console\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#4 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#5 /var/www/html/deploy/vendor/yiisoft/yii2/base/Component.php(641): call_user_func(Array, Object(craft\events\ConfigEvent))
#6 /var/www/html/deploy/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#7 /var/www/html/deploy/vendor/craftcms/cms/src/services/ProjectConfig.php(1271): craft\models\ProjectConfigData->commitChanges(Array, NULL, 'users.groups.21...', false, NULL, true)
#8 /var/www/html/deploy/vendor/craftcms/cms/src/services/ProjectConfig.php(1277): craft\services\ProjectConfig->craft\services\{closure}('users.groups.21...')
#9 /var/www/html/deploy/vendor/craftcms/cms/src/services/ProjectConfig.php(592): craft\services\ProjectConfig->_applyChanges(Array, Object(craft\models\ProjectConfigData), Object(craft\models\ReadOnlyProjectConfigData))
#10 /var/www/html/deploy/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(328): craft\services\ProjectConfig->applyExternalChanges()
#11 [internal function]: craft\console\controllers\ProjectConfigController->actionApply()
#12 /var/www/html/deploy/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/html/deploy/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/html/deploy/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('apply', Array)
#15 /var/www/html/deploy/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('apply', Array)
#16 /var/www/html/deploy/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('apply', Array)
#17 /var/www/html/deploy/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('apply', Array)
#18 /var/www/html/deploy/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#19 /var/www/html/deploy/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('project-config/...', Array)
#20 /var/www/html/deploy/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('project-config/...', Array)
#21 /var/www/html/deploy/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run('project-config/...', Array)
#22 /var/www/html/deploy/vendor/craftcms/cms/src/console/controllers/UpController.php(76): craft\console\Controller->run('project-config/...')
#23 [internal function]: craft\console\controllers\UpController->actionIndex()
#24 /var/www/html/deploy/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /var/www/html/deploy/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#26 /var/www/html/deploy/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#27 /var/www/html/deploy/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('', Array)
#28 /var/www/html/deploy/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('', Array)
#29 /var/www/html/deploy/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#30 /var/www/html/deploy/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#31 /var/www/html/deploy/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('up', Array)
#32 /var/www/html/deploy/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#33 /var/www/html/deploy/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#34 /var/www/html/deploy/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#35 /var/www/html/deploy/craft(23): yii\base\Application->run()
#36 {main} {"memory":21774600,"exception":"[object] (TypeError(code: 0): Cannot assign null to property craft\\events\\UserGroupEvent::$userGroup of type craft\\models\\UserGroup at /var/www/html/deploy/vendor/yiisoft/yii2/BaseYii.php:557)"} 
2024-07-15 14:46:29 [console.INFO] [nystudio107\autocomplete\Autocomplete::registerEventHandlers] Event Handlers installed {"memory":2471352} 
2024-07-15 14:46:29 [console.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=db;dbname=db;port=3306 {"memory":2617056} 
2024-07-15 14:46:29 [console.INFO] [mmikkel\cpfieldinspect\CpFieldInspect::init] CP Field Inspect plugin loaded {"memory":8144120} 
2024-07-15 14:46:29 [console.INFO] [nystudio107\seomatic\Seomatic::init] SEOmatic plugin loaded {"memory":8991912} 
2024-07-15 14:46:29 [console.INFO] [nystudio107\vite\Vite::init] Vite plugin loaded {"memory":9406160} 
2024-07-15 14:46:29 [console.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=db;dbname=db;port=3306 {"memory":9620544} 
2024-07-15 15:51:44 [console.INFO] [nystudio107\autocomplete\Autocomplete::registerEventHandlers] Event Handlers installed {"memory":2471128} 
2024-07-15 15:51:44 [console.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=db;dbname=db;port=3306 {"memory":2616832} 
2024-07-15 15:51:44 [console.INFO] [mmikkel\cpfieldinspect\CpFieldInspect::init] CP Field Inspect plugin loaded {"memory":8940080} 
2024-07-15 15:51:44 [console.INFO] [nystudio107\seomatic\Seomatic::init] SEOmatic plugin loaded {"memory":9720776} 
2024-07-15 15:51:44 [console.INFO] [nystudio107\vite\Vite::init] Vite plugin loaded {"memory":10135592} 
2024-07-15 15:51:44 [console.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=db;dbname=db;port=3306 {"memory":10415312} 
2024-07-15 15:51:44 [console.INFO] [craft\services\ProjectConfig::_applyChanges] Looking for pending changes {"memory":13953984} 
2024-07-15 15:51:44 [console.INFO] [craft\services\ProjectConfig::_applyChanges] Parsing 58 removed configuration items {"memory":13955088} 
2024-07-15 15:51:44 [console.ERROR] [yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: nystudio107\seomatic\models\MetaSitemapVars::sitemapPageSize in /var/www/html/deploy/vendor/yiisoft/yii2/base/Component.php:209
```

**Comment by russback** [comment]
Suspect this is related to multiple feature branches being in development and something getting out of sync. The process involves running `composer install` and `craft up` when deploying so in theory everything should work fine but it's possible something failed. I've seen a couple of instances where `craft up` reports it's complete, but then running `craft project-config/apply` then finds changes to deploy. Not sure why that would be, something to do with the timestamp on the yaml file perhap?

**Comment by brandonkelly** [comment]
> I've seen a couple of instances where `craft up` reports it's complete, but then running `craft project-config/apply` then finds changes to deploy. Not sure why that would be, something to do with the timestamp on the yaml file perhap?

Yeah, the `up` command will only look to see if the `dateModified` value has changed. If not, then it won’t bother running `project-config/apply`.

See https://github.com/craftcms/cms/issues/15322#issuecomment-2218678915 for an explanation of how you could have config changes that don’t include `dateModified`, and what to do about it.

That said, I’ve changed the `up` command for Craft 4.11 and 5.3+, so it will start running `project-config/apply` no matter what.

**Comment by brandonkelly** [comment]
Sorry, had to revert that change as it was causing other issues.

**Comment by jlawrence-yellostudio** [comment]
@brandonkelly I just experienced this pulling down yaml from production where the production yaml contained a deleted user group. 

An exception occurs reading: "Cannot assign null to property craft\events\UserGroupEvent::$userGroup of type craft\models\UserGroup". This occurs when applying the yaml via the control panel, but presumably whichever route you apply it.

It appears that the userGroup is NULL by the time the event is triggered, which isnt typically an issue for production, but is when applying production yaml changes (user groups / permissions) back to dev environment.

I can also confirm that the database contained the user group prior to applying the yaml. It doesn't appear that any other exception occurred, and now after the failed apply the user group has been deleted from the database, yet the error still happens each time when I attempt to apply it. 

The only way around it appears to be to manually edit the vendor to comment these out. Maybe it could be worth just checking that !is_null($group) around those event triggers.

php 8.2.29
craft 4.16.9

URI: admin/actions/config-sync/apply-yaml-changes

Stacktrace:
```
TypeError: Cannot assign null to property craft\events\UserGroupEvent::$userGroup of type craft\models\UserGroup
#24 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/helpers/App.php(1453): craft\helpers\App::configure
#23 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/base/Event.php(58): craft\base\Event::__construct
#22 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/services/UserGroups.php(327): craft\services\UserGroups::handleDeletedUserGroup
#21 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/base/ApplicationTrait.php(1810): craft\web\Application::craft\base\{closure}
#20 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/services/ProjectConfig.php(1161): craft\services\ProjectConfig::handleChangeEvent
#19 [internal](0): call_user_func
#18 /Users/Shared/Websites/xxx/vendor/yiisoft/yii2/base/Component.php(645): yii\base\Component::trigger
#17 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): craft\models\ProjectConfigData::commitChanges
#16 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/services/ProjectConfig.php(1151): craft\services\ProjectConfig::handleChangeEvent
#15 [internal](0): call_user_func
#14 /Users/Shared/Websites/xxx/vendor/yiisoft/yii2/base/Component.php(645): yii\base\Component::trigger
#13 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): craft\models\ProjectConfigData::commitChanges
#12 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/services/ProjectConfig.php(1277): craft\services\ProjectConfig::craft\services\{closure}
#11 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/services/ProjectConfig.php(1284): craft\services\ProjectConfig::_applyChanges
#10 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/services/ProjectConfig.php(593): craft\services\ProjectConfig::applyExternalChanges
#9 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/controllers/ConfigSyncController.php(60): craft\controllers\ConfigSyncController::actionApplyYamlChanges
#8 [internal](0): call_user_func_array
#7 /Users/Shared/Websites/xxx/vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#6 /Users/Shared/Websites/xxx/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Controller::runAction
#5 /Users/Shared/Websites/xxx/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Module::runAction
#4 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/web/Application.php(349): craft\web\Application::runAction
#3 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/web/Application.php(648): craft\web\Application::_processActionRequest
#2 /Users/Shared/Websites/xxx/vendor/craftcms/cms/src/web/Application.php(311): craft\web\Application::handleRequest
#1 /Users/Shared/Websites/xxx/vendor/yiisoft/yii2/base/Application.php(384): yii\base\Application::run
#0 /index.php(12): null
```
Some images from sentry:

<img width="740" height="200" alt="Image" src="https://github.com/user-attachments/assets/be104592-b511-47ea-9634-6205882efd26" />

<img width="442" height="121" alt="Image" src="https://github.com/user-attachments/assets/0a1558dd-3a9f-4fa5-82f4-e5f6e1a28368" />

**Comment by brandonkelly** [comment]
@jlawrence-yellostudio I just made that method defensive for user groups that were already deleted, for the next release.

**Comment by brandonkelly** [comment]
Craft 4.16.12 and 5.8.16 are out with that change.
