### ISSUE TITLE
[5.x]: Migration `m230511_215903_content_refactor` fails

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#15360]
### What happened?

The `m230511_215903_content_refactor` migration is failing moving from `4.10.5` to `5.2.6`.

```
> [01/10] Updating category 510 "Red" ...Exception: Array to string conversion (/var/www/html/vendor/yiisoft/yii2/db/ColumnSchema.php:173)
#0 /var/www/html/vendor/yiisoft/yii2/db/ColumnSchema.php(173): yii\base\ErrorHandler->handleError()
#1 /var/www/html/vendor/craftcms/cms/src/db/mysql/ColumnSchema.php(36): yii\db\ColumnSchema->typecast()
#2 /var/www/html/vendor/yiisoft/yii2/db/mysql/ColumnSchema.php(49): craft\db\mysql\ColumnSchema->typecast()
#3 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(651): yii\db\mysql\ColumnSchema->dbTypecast()
#4 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(630): yii\db\QueryBuilder->prepareUpdateSets()
#5 /var/www/html/vendor/yiisoft/yii2/db/Command.php(598): yii\db\QueryBuilder->update()
#6 /var/www/html/vendor/craftcms/cms/src/db/Command.php(152): yii\db\Command->update()
#7 /var/www/html/vendor/craftcms/cms/src/helpers/Db.php(1107): craft\db\Command->update()
#8 /var/www/html/vendor/craftcms/cms/src/migrations/BaseContentRefactorMigration.php(158): craft\helpers\Db::update()
#9 /var/www/html/vendor/craftcms/cms/src/migrations/m230511_215903_content_refactor.php(62): craft\migrations\BaseContentRefactorMigration->updateElements()
#10 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(50): craft\migrations\m230511_215903_content_refactor->safeUp()
#11 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#12 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(382): yii\console\controllers\BaseMigrateController->migrateUp()
#13 [internal function]: craft\console\controllers\MigrateController->actionAll()
#14 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#15 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#16 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#17 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(195): yii\console\Controller->runAction()
#18 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction()
#19 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#20 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction()
#21 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction()
#22 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run()
#23 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(60): craft\console\Controller->run()
#24 [internal function]: craft\console\controllers\UpController->actionIndex()
#25 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#26 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#27 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#28 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction()
#29 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction()
#30 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction()
#31 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#32 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction()
#33 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#34 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest()
#35 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#36 /var/www/html/craft(13): yii\base\Application->run()
#37 {main}
```

This is running locally on DDEV.

### Craft CMS version

5.2.6

### PHP version

PHP 8.3

### Database type and version

MariaDB 10.3

**Comment by joshuabaker** [comment]
Possibly helpful: It’s a color field. Logging before the [`Db::update` call](https://github.com/craftcms/cms/blob/6540a0611a8cfee78f0d511fe600d09a2fbbb549/src/migrations/BaseContentRefactorMigration.php#L158-L161) the output appears to be the first where `$content` is a populated array.

```
array(1) {
  ["8117a4d1-444f-4c10-82d8-bd144bc4f702"]=>
  string(7) "#ff5c5c"
}
```

**Comment by joshuabaker** [comment]
The version of MariaDB did not meet the minimum requirements.

For posterity, running `ddev debug migrate-database mariadb:10.11` as [documented](https://ddev.readthedocs.io/en/stable/users/extend/database-types/#other-databases-types) enabled JSON column support, which is what was needed here.

**Comment by brandonkelly** [comment]
Glad you got it sorted!

**Comment by vandres** [comment]
Thanks @joshuabaker for posting the solution!
