### ISSUE TITLE
PostgreSQL Backups Failing

### ISSUE THREAD

**Issue by leigeber** [craftcms/cms#1542]
### Description

When I try to run an update or a database backup from Utilities I get the following error with PostgreSQL.

```
2017-03-16 07:48:27 [10.0.1.1][9][mrabcn688ubfvm9hb5auv80f73][error][yii\base\Exception] yii\base\Exception: Could not create backup: The shell command "pg_dump --dbname=cms --host=127.0.0.1 --port=5432 --username=homestead --no-password --if-exists --clean --file=/home/vagrant/app/cms/storage/backups/sitename_170316_124827_hswtt3c5hr_v3.0.0-beta.7.sql --schema=public" failed with exit code 1: pg_dump: [archiver (db)] connection to database "cms" failed: fe_sendauth: no password supplied in /home/vagrant/app/vendor/craftcms/cms/src/controllers/UtilitiesController.php:375
Stack trace:
#0 [internal function]: craft\controllers\UtilitiesController->actionDbBackupPerformAction()
#1 /home/vagrant/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /home/vagrant/app/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#3 /home/vagrant/app/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('db-backup-perfo...', Array)
#4 /home/vagrant/app/vendor/craftcms/cms/src/web/Application.php(246): yii\base\Module->runAction('utilities/db-ba...', Array)
#5 /home/vagrant/app/vendor/craftcms/cms/src/web/Application.php(385): craft\web\Application->runAction('utilities/db-ba...', Array)
#6 /home/vagrant/app/vendor/craftcms/cms/src/web/Application.php(206): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#7 /home/vagrant/app/vendor/yiisoft/yii2/base/Application.php(380): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /home/vagrant/app/public/content/index.php(13): yii\base\Application->run()
#9 {main}
```

### Additional info

- Craft version: 3.0.0-beta.7
- PHP version: 7.1.1
- Database driver & version: PostgreSQL 9.6.2
- Plugins & versions: N/A

**Comment by takobell** [comment]
pg_dump won't accept the password through the command line, but there are several environmental methods you can use to make it aware of the password: http://serverfault.com/a/566212/232999
