### ISSUE TITLE
[5.x]: Unable to fresh install 5.3.1 avec CraftCMS update from Admin

### ISSUE THREAD

**Issue by romarickb** [craftcms/cms#15504]
### Description

In admin, I updated Craft CMS version from 5.2.6 to 5.3.1.
Everything went fine.

After I tried a fresh install of my project with this new version. Have errors, see Actual behavior section

### Steps to reproduce

1. Update in admin from 5.2.6 to 5.3.1
2. Try a fresh install (new database)

### Expected behavior
Project successfully installed

### Actual behavior
Have this following errors
```
*** installing Craft
...
    > create table {{%elements_bulkops}} ... done (time: 0.001s)
...
    > create table {{%projectconfig}} ... done (time: 0.002s)
...  
> applying the project config ... Exception: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "elements_bulkops" does not exist
LINE 1: DELETE FROM "elements_bulkops" WHERE "key"=$1
                    ^
The SQL being executed was: DELETE FROM "elements_bulkops" WHERE "key"='dsvkyndoxu' (/app/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /app/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException()
#1 /app/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute()
#2 /app/vendor/craftcms/cms/src/helpers/Db.php(1172): yii\db\Command->execute()
#3 /app/vendor/craftcms/cms/src/services/Elements.php(1161): craft\helpers\Db::delete()
#4 /app/vendor/craftcms/cms/src/services/Elements.php(1204): craft\services\Elements->endBulkOp()
#5 /app/vendor/craftcms/cms/src/services/Elements.php(3569): craft\services\Elements->ensureBulkOp()
#6 /app/vendor/craftcms/cms/src/services/Elements.php(1282): craft\services\Elements->_saveElementInternal()
#7 /app/vendor/craftcms/cms/src/services/Entries.php(955): craft\services\Elements->saveElement()
#8 /app/vendor/craftcms/cms/src/services/Entries.php(836): craft\services\Entries->_ensureSingleEntry()
#9 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1816): craft\services\Entries->handleChangedSection()
#10 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1179): craft\console\Application->craft\base\{closure}()
#11 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#12 /app/vendor/yiisoft/yii2/base/Component.php(641): call_user_func()
#13 /app/vendor/craftcms/cms/src/models/ProjectConfigData.php(82): yii\base\Component->trigger()
#14 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1169): craft\models\ProjectConfigData->commitChanges()
#15 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#16 /app/vendor/yiisoft/yii2/base/Component.php(641): call_user_func()
#17 /app/vendor/craftcms/cms/src/models/ProjectConfigData.php(82): yii\base\Component->trigger()
#18 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1289): craft\models\ProjectConfigData->commitChanges()
#19 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1311): craft\services\ProjectConfig->craft\services\{closure}()
#20 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(627): craft\services\ProjectConfig->_applyChanges()
#21 /app/vendor/craftcms/cms/src/migrations/Install.php(1109): craft\services\ProjectConfig->applyExternalChanges()
#22 /app/vendor/craftcms/cms/src/migrations/Install.php(84): craft\migrations\Install->insertDefaultData()
#23 /app/vendor/craftcms/cms/src/db/Migration.php(50): craft\migrations\Install->safeUp()
#24 /app/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up()
#25 /app/vendor/craftcms/cms/src/console/controllers/InstallController.php(214): craft\db\MigrationManager->migrateUp()
#26 [internal function]: craft\console\controllers\InstallController->actionCraft()
#27 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#28 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#29 /app/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#30 /app/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction()
#31 /app/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction()
#32 /app/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction()
#33 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#34 /app/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction()
#35 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#36 /app/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest()
#37 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#38 /app/craft(13): yii\base\Application->run()
#39 {main}
*** failed to install Craft: An error occurred while executing the "craft\migrations\Install migration: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "elements_bulkops" does not exist
LINE 1: DELETE FROM "elements_bulkops" WHERE "key"=$1
                    ^
The SQL being executed was: DELETE FROM "elements_bulkops" WHERE "key"='dsvkyndoxu'

Exception 'yii\db\Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "projectconfig" does not exist
LINE 1: DELETE FROM "projectconfig" WHERE "path"=$1
                    ^
The SQL being executed was: DELETE FROM "projectconfig" WHERE "path"='meta.__names__.567f09fe-99d1-462f-badb-d3242c0d8eb7''

in /app/vendor/yiisoft/yii2/db/Schema.php:676

Error Info:
Array
(
    [0] => 42P01
    [1] => 7
    [2] => ERROR:  relation "projectconfig" does not exist
LINE 1: DELETE FROM "projectconfig" WHERE "path"=$1
                    ^
)

Caused by: Exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "projectconfig" does not exist
LINE 1: DELETE FROM "projectconfig" WHERE "path"=$1
                    ^'

in /app/vendor/yiisoft/yii2/db/Command.php:1320

Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute()
#1 /app/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute()
#2 /app/vendor/craftcms/cms/src/helpers/Db.php(1172): yii\db\Command->execute()
#3 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(890): craft\helpers\Db::delete()
#4 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(855): craft\services\ProjectConfig->removeInternalConfigValuesByPaths()
#5 [internal function]: craft\services\ProjectConfig->craft\services\{closure}()
#6 /app/vendor/yiisoft/yii2/db/Connection.php(818): call_user_func()
#7 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(798): yii\db\Connection->transaction()
#8 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(416): craft\services\ProjectConfig->saveModifiedConfigData()
#9 [internal function]: craft\services\ProjectConfig->flush()
#10 /app/vendor/yiisoft/yii2/base/Component.php(641): call_user_func()
#11 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(533): yii\base\Component->trigger()
#12 /app/vendor/yiisoft/yii2/base/Application.php(387): craft\console\Application->trigger()
#13 /app/craft(13): yii\base\Application->run()
#14 {main}
```

### Craft CMS version

5.3.1

### Installed plugins and versions

- PHP 8.2
- Postgres 16

**Comment by brandonkelly** [comment]
I’m not able to reproduce that. Can you please send your Composer files and `config/project/` folder into support@craftcms.com?

**Comment by brandonkelly** [comment]
Able to reproduce this on Postgres. Looking into it…

**Comment by brandonkelly** [comment]
Craft 5.3.2 is out with a fix for this. Thanks for reporting!

**Comment by romarickb** [comment]
Everything works as expected, thank you for your quick fix and new release !
