### ISSUE TITLE
[4.11.4]: Cannot create new users

### ISSUE THREAD

**Issue by pnpaes** [craftcms/cms#15588]
### Description
When I try to create new users I get an error message :
Invalid Argument – [yii\base\InvalidArgumentException](https://www.yiiframework.com/doc-2.0/yii-base-invalidargumentexception.html)
Invalid numeric value: new

### Steps to reproduce

1. Access admin
2. Go to the list of users
3. click "+New user"

### Expected behavior
It should open the screen to add register a ne user

### Actual behavior
Throws and error message: Invalid numeric value: new
<img width="904" alt="Screenshot 2024-08-23 at 2 38 20 PM" src="https://github.com/user-attachments/assets/6e1a2576-c96e-41ef-835f-1ce5ba04d279">

### Craft CMS version

4.11.4

### PHP version

8.1.2

### Operating system and version

Linux 5.15.0-112-generic

### Database type and version

MySQL 8.0.39

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

Control Panel Body Classes	2.3.0
Feed Me	5.7.0
Mailchimp Subscribe	4.0.0
Redactor	3.1.0
Redactor Custom Styles	4.0.3
Sidebar Entry Types	2.0.1
Sprig	2.12.0
Super Table	3.0.14
Tags	2.0.0

**Comment by i-just** [comment]
Hi @pnpaes, thanks for getting in touch. I can’t replicate this. Can you please post a full stack trace for this error?

**Comment by pnpaes** [comment]
@i-just thank you for taking the time.... here it goes.
Btw, i only get this in this specific website, not in others running similar version.
I noticed this issue yesterday when I had to create a new user, so this morning I updated craftcms to the lastest version thinking that could be something with that version, but i still get the same issue.

```
yii\base\InvalidArgumentException: Invalid numeric value: new in /home/craftcms/www/vendor/craftcms/cms/src/helpers/Db.php:599
Stack trace:
#0 /home/craftcms/www/vendor/craftcms/cms/src/helpers/Db.php(850): craft\helpers\Db::parseParam()
#1 /home/craftcms/www/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1481): craft\helpers\Db::parseNumericParam()
#2 /home/craftcms/www/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
#3 /home/craftcms/www/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
#4 /home/craftcms/www/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand()
#5 /home/craftcms/www/vendor/craftcms/cms/src/db/Query.php(280): yii\db\Query->one()
#6 /home/craftcms/www/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1672): craft\db\Query->one()
#7 /home/craftcms/www/modules/restaurantproductsmodule/RestaurantProductsModule.php(165): craft\elements\db\ElementQuery->one()
#8 [internal function]: modules\restaurantproductsmodule\RestaurantProductsModule->modules\restaurantproductsmodule\{closure}()
#9 /home/craftcms/www/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#10 /home/craftcms/www/vendor/yiisoft/yii2/base/Component.php(650): yii\base\Event::trigger()
#11 /home/craftcms/www/vendor/craftcms/cms/src/web/twig/variables/Cp.php(344): yii\base\Component->trigger()
#12 /home/craftcms/www/vendor/twig/twig/src/Extension/CoreExtension.php(1635): craft\web\twig\variables\Cp->nav()
#13 /home/craftcms/www/vendor/craftcms/cms/src/helpers/Template.php(149): twig_get_attribute()
#14 /home/craftcms/www/storage/runtime/compiled_templates/72/72658efa295d0bcb20242d4e52fd0ed8.php(85): craft\helpers\Template::attribute()
#15 /home/craftcms/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_37793bf8e98d7becadd0f75c5dc30c53->doDisplay()
#16 /home/craftcms/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#17 /home/craftcms/www/storage/runtime/compiled_templates/25/25ad606c559efc1a2488ec63528c88cc.php(198): Twig\Template->display()
#18 /home/craftcms/www/vendor/twig/twig/src/Template.php(171): __TwigTemplate_d016a9cb10ba8ddd7381e770fd8214d2->block_body()
#19 /home/craftcms/www/storage/runtime/compiled_templates/99/9999104d074d6493244d7f323e92ce1a.php(94): Twig\Template->displayBlock()
#20 /home/craftcms/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_bd0a3c980dee200b48ba66074d650f22->doDisplay()
#21 /home/craftcms/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#22 /home/craftcms/www/storage/runtime/compiled_templates/6d/6d8f787a01fb70c167dd0f96cd7ae221.php(56): Twig\Template->display()
#23 /home/craftcms/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_f10a17fe75e87ba9b4689ffb29fabfcf->doDisplay()
#24 /home/craftcms/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#25 /home/craftcms/www/storage/runtime/compiled_templates/25/25ad606c559efc1a2488ec63528c88cc.php(180): Twig\Template->display()
#26 /home/craftcms/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_d016a9cb10ba8ddd7381e770fd8214d2->doDisplay()
#27 /home/craftcms/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#28 /home/craftcms/www/storage/runtime/compiled_templates/4d/4d10936c791969d653f181d60a902db4.php(116): Twig\Template->display()
#29 /home/craftcms/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_54eb3eb5e6781a4183977f2bba47d947->doDisplay()
#30 /home/craftcms/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#31 /home/craftcms/www/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#32 /home/craftcms/www/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#33 /home/craftcms/www/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render()
#34 /home/craftcms/www/vendor/craftcms/cms/src/web/View.php(495): Twig\Environment->render()
#35 /home/craftcms/www/vendor/craftcms/cms/src/web/View.php(548): craft\web\View->renderTemplate()
#36 /home/craftcms/www/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate()
#37 /home/craftcms/www/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format()
#38 /home/craftcms/www/vendor/craftcms/cms/src/web/Response.php(338): yii\web\Response->prepare()
#39 /home/craftcms/www/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#40 /home/craftcms/www/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#41 /home/craftcms/www/web/index.php(12): yii\base\Application->run()
#42 {main}
```

**Comment by pnpaes** [comment]
@i-just now that I read the whole error stack it seems to be one of my internal modules that is breaking it....
someone in the team released this without proper testing. I will do some investigation on my end and ping you if I need further support. for now I will close this.
sorry for the confusion....

**Comment by i-just** [comment]
Glad to hear you got to the bottom of it!
