### ISSUE TITLE
[5.x]: 5.4 TypeError when clicking “Entries” on the sidebar of the Control Panel

### ISSUE THREAD

**Issue by TUSAB-web** [craftcms/cms#15648]
### Description

Error pops up with stack trace when clicking “Entries” on the sidebar of the Craft CP

### Steps to reproduce

1. Click Entries on the sidebar

### Expected behavior

Entries would appear

### Actual behavior

Error with stack trace appears
[Craft 5.4 TypeError stack trace.txt](https://github.com/user-attachments/files/16853211/Craft.5.4.TypeError.stack.trace.txt)

### Craft CMS version

5.4

### PHP version

8.2.22

### Installed plugins and versions

Azure Blob
Blitz
CkEditor
CP field inspect
Calendar
Elements Panel
Environment Label
Feed Me
Freeform
Image Optimize
Knock Knock
Mailjet
Maps
SEOMatic
Sendgrid
Sprig
SuperSort
Twig Perversion
Wordsmith
OEmbed

**Comment by dlindberg** [comment]
Seeing a similar error from the CP, (admin/entries)
```
TypeError: craft\helpers\Db::parseColumnType(): Argument #1 ($columnType) must be of type string, array given, called in /var/www/html/vendor/craftcms/cms/src/base/Field.php on line 829 and defined in /var/www/html/vendor/craftcms/cms/src/helpers/Db.php:366
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/base/Field.php(829): craft\helpers\Db::parseColumnType()
#1 /var/www/html/vendor/craftcms/cms/src/services/ElementSources.php(357): craft\base\Field->getSortOption()
#2 /var/www/html/vendor/craftcms/cms/src/services/ElementSources.php(310): craft\services\ElementSources->getSortOptionsForFieldLayouts()
#3 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1740): craft\services\ElementSources->getSourceSortOptions()
#4 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(148): Twig\Extension\CoreExtension::getAttribute()
#5 /var/www/html/storage/runtime/compiled_templates/51/511718f4f2551fa766f80bcbacab6226.php(217): craft\helpers\Template::attribute()
#6 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1901): __TwigTemplate_709142a6205daf3a4e958f2287c07069->{closure}()
#7 /var/www/html/storage/runtime/compiled_templates/51/511718f4f2551fa766f80bcbacab6226.php(206): Twig\Extension\CoreExtension::captureOutput()
#8 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1278): __TwigTemplate_709142a6205daf3a4e958f2287c07069->macro_sourceLink()
#9 /var/www/html/storage/runtime/compiled_templates/51/511718f4f2551fa766f80bcbacab6226.php(133): Twig\Extension\CoreExtension::callMacro()
#10 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1901): __TwigTemplate_709142a6205daf3a4e958f2287c07069->{closure}()
#11 /var/www/html/storage/runtime/compiled_templates/51/511718f4f2551fa766f80bcbacab6226.php(44): Twig\Extension\CoreExtension::captureOutput()
#12 /var/www/html/vendor/twig/twig/src/Template.php(398): __TwigTemplate_709142a6205daf3a4e958f2287c07069->doDisplay()
#13 /var/www/html/storage/runtime/compiled_templates/ed/edf73350462352c71e7cae4985634196.php(136): Twig\Template->yield()
#14 /var/www/html/vendor/twig/twig/src/Template.php(442): __TwigTemplate_75de4be565d39b12259de43f610674f9->block_sidebar()
#15 /var/www/html/vendor/twig/twig/src/Template.php(146): Twig\Template->yieldBlock()
#16 /var/www/html/vendor/twig/twig/src/Template.php(207): Twig\Template->displayBlock()
#17 /var/www/html/storage/runtime/compiled_templates/4b/4b2477fc370a3416746bf346b996ff75.php(99): Twig\Template->renderBlock()
#18 /var/www/html/vendor/twig/twig/src/Template.php(398): __TwigTemplate_d635a3815948ab9c90d57da4b334113a->doDisplay()
#19 /var/www/html/storage/runtime/compiled_templates/ed/edf73350462352c71e7cae4985634196.php(110): Twig\Template->yield()
#20 /var/www/html/vendor/twig/twig/src/Template.php(398): __TwigTemplate_75de4be565d39b12259de43f610674f9->doDisplay()
#21 /var/www/html/storage/runtime/compiled_templates/00/00d292c525912351627e41a7e65aa444.php(63): Twig\Template->yield()
#22 /var/www/html/vendor/twig/twig/src/Template.php(398): __TwigTemplate_4ea147c44a4d61a94643de3d4bee0b24->doDisplay()
#23 /var/www/html/vendor/twig/twig/src/Template.php(354): Twig\Template->yield()
#24 /var/www/html/vendor/twig/twig/src/Template.php(369): Twig\Template->display()
#25 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#26 /var/www/html/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render()
#27 /var/www/html/vendor/craftcms/cms/src/web/View.php(501): Twig\Environment->render()
#28 /var/www/html/vendor/craftcms/cms/src/web/View.php(554): craft\web\View->renderTemplate()
#29 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate()
#30 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format()
#31 /var/www/html/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#32 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#33 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#34 /var/www/html/web/index.php(12): yii\base\Application->run()
#35 {main}
```

**Comment by brandonkelly** [comment]
Craft 5.4.0.1 is out with a fix for this. Thank you!
