### ISSUE TITLE
[4.x]: Error: Can use "yield from" only with arrays and Traversables

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#15732]
### Description

I've just updated a site from 4.11.5 to 4.12.2. When I browse the front-end of my site on my dev installation, I get the following error:

```
Error: Can use "yield from" only with arrays and Traversables.
```

Full stack trace:

```
Error: Can use "yield from" only with arrays and Traversables in /var/www/html/craft/vendor/twig/twig/src/Template.php:437
Stack trace:
#0 /var/www/html/craft/storage/runtime/compiled_templates/93/936aaaac861e2136d2dd40de90e984e1.php(82): Twig\Template->yieldBlock('siteHead', Array, Array)
#1 /var/www/html/craft/vendor/twig/twig/src/Template.php(393): __TwigTemplate_011b9f2310c96a9ed2c9fbfae7950819->doDisplay(Array, Array)
#2 /var/www/html/craft/storage/runtime/compiled_templates/f0/f0c8afc804a74a1d8b85859da2ca8feb.php(64): Twig\Template->yield(Array, Array)
#3 /var/www/html/craft/vendor/twig/twig/src/Template.php(393): __TwigTemplate_76825c855f0aa97ef2280712f5d1cc5a->doDisplay(Array, Array)
#4 /var/www/html/craft/storage/runtime/compiled_templates/06/06dc9d65081798cfbc909c0417cddef4.php(52): Twig\Template->yield(Array)
#5 /var/www/html/craft/vendor/twig/twig/src/Template.php(393): __TwigTemplate_e678a89b2665db4a58edd0d4d6628c4a->doDisplay(Array, Array)
#6 /var/www/html/craft/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#7 /var/www/html/craft/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#8 /var/www/html/craft/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#9 /var/www/html/craft/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render(Array)
#10 /var/www/html/craft/vendor/craftcms/cms/src/web/View.php(495): Twig\Environment->render('_routers/single...', Array)
#11 /var/www/html/craft/vendor/craftcms/cms/src/web/View.php(548): craft\web\View->renderTemplate('_routers/single...', Array)
#12 /var/www/html/craft/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('_routers/single...', Array, 'site')
#13 /var/www/html/craft/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#14 /var/www/html/craft/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#15 /var/www/html/craft/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#16 /var/www/html/craft/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#17 /var/www/html/public/index.php(12): yii\base\Application->run()
#18 {main}
```

Downgrading the site back to 4.11.5 brings the site back online.

Upgrading from from 4.11.5 to 4.12.0 yields the same error.

### Steps to reproduce

1.

### Craft CMS version

4.12.2

### PHP version

8.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 
It sounds like a duplicate of https://github.com/craftcms/cms/issues/15693 (which ended up being related to the Template Comments plugin). If you’re using that plugin, updating to [4.0.3](https://github.com/nystudio107/craft-templatecomments/releases/tag/4.0.3) should help.

**Comment by jonleverrier** [comment]
Thanks @i-just. This was indeed the problem!
