### ISSUE TITLE
[5.x]: 5.4.7 is breaking my site: Call to a member function getEntryTypes() on null

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#15867]
### Description

Since updating from 5.4.6 to 5.4.7 my site is breaking, seeing this error:

```
Error: Call to a member function getEntryTypes() on null in /app/user/vendor/craftcms/cms/src/elements/Entry.php:1378
Stack trace:
#0 /app/user/vendor/craftcms/cms/src/elements/Entry.php(1414): craft\elements\Entry->getAvailableEntryTypes()
#1 /app/user/vendor/craftcms/cms/src/elements/Entry.php(1300): craft\elements\Entry->getType()
#2 /app/user/vendor/craftcms/cms/src/base/Element.php(5035): craft\elements\Entry->getFieldLayout()
#3 /app/user/vendor/craftcms/cms/src/base/Element.php(2323): craft\base\Element->hasEagerLoadedElements('status')
#4 /app/user/vendor/verbb/hyper/src/base/ElementLink.php(267): craft\base\Element->__get('status')
#5 /app/user/vendor/verbb/hyper/src/base/ElementLink.php(193): verbb\hyper\base\ElementLink->_getElementCache()
#6 /app/user/vendor/verbb/hyper/src/base/Link.php(444): verbb\hyper\base\ElementLink->getLinkUrl()
#7 /app/user/vendor/verbb/hyper/src/base/Link.php(522): verbb\hyper\base\Link->getUrl()
#8 [internal function]: verbb\hyper\base\Link->getLink(Array)
#9 /app/user/vendor/verbb/hyper/src/models/LinkCollection.php(87): call_user_func_array(Array, Array)
#10 /app/user/vendor/twig/twig/src/Extension/CoreExtension.php(1754): verbb\hyper\models\LinkCollection->__call('getLink', Array)
#11 /app/user/vendor/craftcms/cms/src/helpers/Template.php(148): Twig\Extension\CoreExtension::getAttribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\hyper\models\LinkCollection), 'getLink', Array, 'method', false, false, false, 33)
#12 /tmp/storage/runtime/compiled_templates/9a/9ad686ca301a3085f9362f1a46178da2.php(123): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\hyper\models\LinkCollection), 'getLink', Array, 'method', false, false, false, 33)
#13 /app/user/vendor/twig/twig/src/Template.php(393): __TwigTemplate_5bc7e05900c2f8f48f07e842ddcdd841->doDisplay(Array, Array)
#14 /tmp/storage/runtime/compiled_templates/78/78702a0a855aecb49632289170804e23.php(80): Twig\Template->yield(Array)
#15 /app/user/vendor/twig/twig/src/Template.php(393): __TwigTemplate_7b9103f61ec21bbe15259aa889e906f9->doDisplay(Array, Array)
#16 /tmp/storage/runtime/compiled_templates/74/7467b9498591f30fc4b77cb15f1f8206.php(69): Twig\Template->yield(Array)
#17 /app/user/vendor/twig/twig/src/Template.php(437): __TwigTemplate_27a50d20589a8df34435d0a71d4438c4->block_hero(Array, Array)
#18 /tmp/storage/runtime/compiled_templates/09/099aea1042afbf0528769d5e1edddcf0.php(74): Twig\Template->yieldBlock('hero', Array, Array)
#19 /app/user/vendor/twig/twig/src/Template.php(437): __TwigTemplate_93328f652dcac9c5548e1a67014fa730->block_content(Array, Array)
#20 /app/user/vendor/twig/twig/src/Template.php(482): Twig\Template->yieldBlock('content', Array, Array, false)
#21 /tmp/storage/runtime/compiled_templates/74/7467b9498591f30fc4b77cb15f1f8206.php(105): Twig\Template->yieldParentBlock('content', Array, Array)
#22 /app/user/vendor/twig/twig/src/Template.php(437): __TwigTemplate_27a50d20589a8df34435d0a71d4438c4->block_content(Array, Array)
#23 /tmp/storage/runtime/compiled_templates/8c/8c816d6bf3fce4137510d4f4cba284fe.php(74): Twig\Template->yieldBlock('content', Array, Array)
#24 /app/user/vendor/twig/twig/src/Template.php(437): __TwigTemplate_4dd96cfd80394db323389a1c195304db->block_body(Array, Array)
#25 /tmp/storage/runtime/compiled_templates/9e/9e5ae5d3f2c09075ca6e26bb307279b7.php(110): Twig\Template->yieldBlock('body', Array, Array)
#26 /app/user/vendor/twig/twig/src/Template.php(393): __TwigTemplate_1e01f0397bc6d46659f3b1c10289259f->doDisplay(Array, Array)
#27 /tmp/storage/runtime/compiled_templates/8c/8c816d6bf3fce4137510d4f4cba284fe.php(51): Twig\Template->yield(Array, Array)
#28 /app/user/vendor/twig/twig/src/Template.php(393): __TwigTemplate_4dd96cfd80394db323389a1c195304db->doDisplay(Array, Array)
#29 /tmp/storage/runtime/compiled_templates/09/099aea1042afbf0528769d5e1edddcf0.php(60): Twig\Template->yield(Array, Array)
#30 /app/user/vendor/twig/twig/src/Template.php(393): __TwigTemplate_93328f652dcac9c5548e1a67014fa730->doDisplay(Array, Array)
#31 /tmp/storage/runtime/compiled_templates/74/7467b9498591f30fc4b77cb15f1f8206.php(51): Twig\Template->yield(Array, Array)
#32 /app/user/vendor/twig/twig/src/Template.php(393): __TwigTemplate_27a50d20589a8df34435d0a71d4438c4->doDisplay(Array, Array)
#33 /app/user/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#34 /app/user/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#35 /app/user/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#36 /app/user/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render(Array)
#37 /app/user/vendor/craftcms/cms/src/web/View.php(501): Twig\Environment->render('index', Array)
#38 /app/user/vendor/craftcms/cms/src/web/View.php(554): craft\web\View->renderTemplate('index', Array)
#39 /app/user/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('index', Array, 'site')
#40 /app/user/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#41 /app/user/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#42 /app/user/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#43 /app/user/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#44 /app/user/web/index.php(18): yii\base\Application->run()
#45 {main}
```

### Steps to reproduce

Not sure how to reproduce this, but I'm guessing it has something to do with https://github.com/craftcms/cms/issues/15796 

### Expected behavior

Worked in 5.4.6

### Actual behavior

Broken in 5.4.7

### Craft CMS version

5.4.7

### PHP version

8.3

### Database type and version

Postgres

### Installed plugins and versions

- Hyper

**Comment by iamtompickering** [comment]
I'm getting this exact same issue since updating to 5.4.7 as well!

**Comment by brandonkelly** [comment]
This should be fixed now. Can one of you test and verify?

You can test by changing your `craftcms/cms` requirement in composer.json to:

```json
"craftcms/cms": "5.x-dev as 5.4.7",
```

and running `composer update`.

**Comment by boboldehampsink** [comment]
Seems to be fixed!

**Comment by iamtompickering** [comment]
Yep looks good to me too!

**Comment by brandonkelly** [comment]
Thanks both! Craft 5.4.7.1 is out now with that fix.

**Comment by engram-design** [comment]
Should also be fixed in next Hyper release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.5"`.
