### ISSUE TITLE
[4.x]: Can't view existing user groups or create new ones.

### ISSUE THREAD

**Issue by Gs-Joel** [craftcms/cms#15866]
### Description

I'm working with a site that was originally built on craft 3 but has long since been updated to craft 4. I'm trying to add new a new user group and am getting the following error.

```
_Key "heading" for sequence/mapping with keys "normal, professional, partner" does not exist._

 in /Users/joel/Websites/sans/vendor/craftcms/cms/src/templates/_includes/permissions.twigat line 77

```
The same error is shown when trying to view existing permissions.

(normal, professional, partner are the existing user groups)

I've updated to the latest version for craft 4 Pro (4.12.6) and all plugins.

I saw [this issue](https://github.com/craftcms/cms/issues/12892) which seems to be having the same issue and it was suggested that freeforms   might be the culprit.
I know Expressform is built by the same team so I tried removing that form to test but the issue persists. 

**Update**
I am also getting this error when trying to view user profiles.
However if I set 
```
CRAFT_DEV_MODE=false
CRAFT_ALLOW_ADMIN_CHANGES=false
```
I can view user profiles without issue.

### Steps to reproduce

1. Build craft Pro site in 3.x
2. Add user groups/ permissions
3. Update to latest version of craft 4
4. Try to add/ view new user groups/ permissions

### Expected behavior

Can create and view user groups

### Actual behavior

can't create user groups or permissions

### Stacktrace

```
Twig\Error\RuntimeError: Key "heading" for sequence/mapping with keys "normal, professional, partner" does not exist. in /Users/joel/Websites/sans/vendor/craftcms/cms/src/templates/_includes/permissions.twig:77
Stack trace:
#0 /Users/joel/Websites/sans/vendor/craftcms/cms/src/helpers/Template.php(148): Twig\Extension\CoreExtension::getAttribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'heading', Array, 'any', false, false, false, 77)
#1 /Users/joel/Websites/sans/storage/runtime/compiled_templates/10/10c30a2a6a7e0f9a821c430f2a79a97c.php(88): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'heading', Array, 'any', false, false, false, 77)
#2 /Users/joel/Websites/sans/vendor/twig/twig/src/Template.php(393): __TwigTemplate_4f0b72c88f8b99778dff3a7cd7c7fc26->doDisplay(Array, Array)
#3 /Users/joel/Websites/sans/storage/runtime/compiled_templates/a7/a78e867cd1987fdd1fdd21d1492eefca.php(169): Twig\Template->yield(Array)
#4 /Users/joel/Websites/sans/vendor/twig/twig/src/Template.php(437): __TwigTemplate_1b1f36cc484883d9b8a1bc3e996fa42b->block_content(Array, Array)
#5 /Users/joel/Websites/sans/storage/runtime/compiled_templates/12/12aebf0cc44ff5b5015cf1576572bb9b.php(645): Twig\Template->yieldBlock('content', Array, Array)
#6 /Users/joel/Websites/sans/vendor/twig/twig/src/Template.php(437): __TwigTemplate_e30cb9361a0e95ee63dc8f2a63d4fd1a->block_main(Array, Array)
#7 /Users/joel/Websites/sans/storage/runtime/compiled_templates/12/12aebf0cc44ff5b5015cf1576572bb9b.php(386): Twig\Template->yieldBlock('main', Array, Array)
#8 /Users/joel/Websites/sans/vendor/twig/twig/src/Template.php(437): __TwigTemplate_e30cb9361a0e95ee63dc8f2a63d4fd1a->block_body(Array, Array)
#9 /Users/joel/Websites/sans/storage/runtime/compiled_templates/8f/8feb190bd49aeb0dd1d65353d534d40e.php(99): Twig\Template->yieldBlock('body', Array, Array)
#10 /Users/joel/Websites/sans/vendor/twig/twig/src/Template.php(393): __TwigTemplate_85df1407e55b9badd241b68628b7a191->doDisplay(Array, Array)
#11 /Users/joel/Websites/sans/storage/runtime/compiled_templates/0b/0b3183a920d19762db004352afa1e6fe.php(61): Twig\Template->yield(Array, Array)
#12 /Users/joel/Websites/sans/vendor/twig/twig/src/Template.php(393): __TwigTemplate_3e1913f028c131cefccdb557636e0890->doDisplay(Array, Array)
#13 /Users/joel/Websites/sans/storage/runtime/compiled_templates/12/12aebf0cc44ff5b5015cf1576572bb9b.php(186): Twig\Template->yield(Array, Array)
#14 /Users/joel/Websites/sans/vendor/twig/twig/src/Template.php(393): __TwigTemplate_e30cb9361a0e95ee63dc8f2a63d4fd1a->doDisplay(Array, Array)
#15 /Users/joel/Websites/sans/storage/runtime/compiled_templates/a7/a78e867cd1987fdd1fdd21d1492eefca.php(104): Twig\Template->yield(Array, Array)
#16 /Users/joel/Websites/sans/vendor/twig/twig/src/Template.php(393): __TwigTemplate_1b1f36cc484883d9b8a1bc3e996fa42b->doDisplay(Array, Array)
#17 /Users/joel/Websites/sans/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#18 /Users/joel/Websites/sans/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#19 /Users/joel/Websites/sans/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#20 /Users/joel/Websites/sans/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render(Array)
#21 /Users/joel/Websites/sans/vendor/craftcms/cms/src/web/View.php(495): Twig\Environment->render('settings/users/...', Array)
#22 /Users/joel/Websites/sans/vendor/craftcms/cms/src/web/View.php(548): craft\web\View->renderTemplate('settings/users/...', Array)
#23 /Users/joel/Websites/sans/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('settings/users/...', Array, 'cp')
#24 /Users/joel/Websites/sans/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#25 /Users/joel/Websites/sans/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#26 /Users/joel/Websites/sans/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#27 /Users/joel/Websites/sans/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#28 /Users/joel/Websites/sans/web/index.php(12): yii\base\Application->run()
#29 /Applications/Herd.app/Contents/Resources/valet/server.php(167): require('/Users/joel/Web...')
#30 {main}
```

### Craft CMS version

4.12.6

### PHP version

8.3

### Operating system and version

Mac OS Sonoma 14.5

### Database type and version

Mysql 5.8

### Installed plugins and versions

- Express forms
- Imgixer
- Cookies by NYStudio
- Seomatic
- Supertable
- Shopify
- Twigpack

**Comment by brandonkelly** [comment]
Something (probably a custom module or plugin) is registering `normal`, `professional`, and `partner` custom permissions via the `EVENT_REGISTER_PERMISSIONS` event.

That event handler will need to be updated to return an array with `heading` and `permissions` keys, as demonstrated here: https://craftcms.com/docs/4.x/extend/updating-plugins.html#registering-permissions

**Comment by Gs-Joel** [comment]
Thanks for the guidance on this one. 

The project is legacy and I was not aware of that integration.
