### ISSUE TITLE
[5.x]:  Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by DowleyDeveloped** [craftcms/cms#15875]
### Description
When updating to Craft 5.4.7.1 the front end of the site errors with "Serialization of 'Closure' is not allowed at /var/www/html/vendor/yiisoft/yii2/caching/Cache.php:113"

### Craft CMS version

5.4.7.1

### PHP version

8.3

**Comment by DowleyDeveloped** [comment]
This is the stack trace from the logs:

```sh
#0 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(113): igbinary_serialize()
#1 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(133): yii\caching\Cache->buildKey()
#2 /var/www/html/vendor/yiisoft/yii2/web/UrlManager.php(311): yii\caching\Cache->get()
#3 /var/www/html/vendor/yiisoft/yii2/web/UrlManager.php(229): yii\web\UrlManager->getBuiltRulesFromCache()
#4 /var/www/html/vendor/craftcms/cms/src/web/UrlManager.php(306): yii\web\UrlManager->buildRules()
#5 /var/www/html/vendor/yiisoft/yii2/web/UrlManager.php(211): craft\web\UrlManager->buildRules()
#6 /var/www/html/vendor/craftcms/cms/src/web/UrlManager.php(116): yii\web\UrlManager->addRules()
#7 /var/www/html/vendor/craftcms/cms/src/web/Request.php(1411): craft\web\UrlManager->parseRequest()
#8 /var/www/html/vendor/yiisoft/yii2/web/Application.php(82): craft\web\Request->resolve()
#9 /var/www/html/vendor/craftcms/cms/src/web/Application.php(318): yii\web\Application->handleRequest()
#10 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#11 /var/www/html/web/index.php(12): yii\base\Application->run()
#12 {main} {"memory":7373280,"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at /var/www/html/vendor/yiisoft/yii2/caching/Cache.php:113)"} 
```

**Comment by brandonkelly** [comment]
Are you specifying custom URL rules via `config/routes.php`?

**Comment by DowleyDeveloped** [comment]
```sh
<?php
/**
 * Site URL Rules
 */

use craft\elements\Entry;

$site = Craft::$app->getSites()->currentSite->id;
$global = Entry::find()
    ->section('globalSettings')
    ->eagerly()
    ->one();

$eventPage = $global
    ->eventsParentPage
    ->eagerly()
    ->one();

$newsPage = $global
    ->newsParentPage
    ->eagerly()
    ->one();

return [
    $eventPage->url . "/<category>" => [
        'template' => '_sections/_pages/_collection-page',
        'variables' => [
            'entry' => $eventPage,
        ]
    ],
    $newsPage->url . "/<category>" => [
        'template' => '_sections/_pages/_collection-page',
        'variables' => [
            'entry' => $newsPage,
        ]
    ],
];
```

**Comment by brandonkelly** [comment]
That’s the culprit. You can’t pass objects like entries into route parameters, as those aren’t safely serializable.

**Comment by DowleyDeveloped** [comment]
Ok, so what would be the proposed way to do a route like this for things like categorisation?

On a multisite the slug will be different so I can't hardcode anything

**Comment by DowleyDeveloped** [comment]
Dw got it working
