### ISSUE TITLE
Field::init() cannot call Plugin::getInstance()->getSettings() when running a migration

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1592]
Not sure if this is by design, but a field type cannot call it's plugins::getSettings() method.  In our case, a plugin has global settings that I would like to set as default properties on a field type.

### Steps to reproduce
From the Field:

```php
    /**
     * @inheritdoc
     */
    public function init()
    {

        parent::init();

        // Restrict limits
        if(Plugin::getInstance()->getSettings()->singleUser) {
            $this->allowLimit = true;
            $this->limit = 1;
        }

    }
```

I've only seen this occur when running a migration.  The migration will fail with 'Call to a member function getSettings() on null'

Stack trace: 
```
#0 /var/www/html/vendor/yiisoft/yii2/base/Object.php(107): flipbox\organization\fields\User->init()
#1 /var/www/html/vendor/craftcms/cms/src/helpers/Component.php(68): yii\base\Object->__construct(Array)
#2 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(435): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#3 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(479): craft\services\Fields->createField(Array)
#4 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1259): craft\services\Fields->getAllFields()
#5 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(899): craft\elements\db\ElementQuery->customFields()
#6 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(92): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#7 /var/www/html/vendor/yiisoft/yii2/db/Query.php(126): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#8 /var/www/html/vendor/yiisoft/yii2/db/Query.php(253): yii\db\Query->createCommand(Object(craft\db\Connection))
#9 /var/www/html/vendor/craftcms/cms/src/db/Query.php(135): yii\db\Query->one(NULL)
#10 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1022): craft\db\Query->one(NULL)
#11 /var/www/html/vendor/craftcms/cms/src/elements/User.php(333): craft\elements\db\ElementQuery->one()
#12 /var/www/html/vendor/yiisoft/yii2/web/User.php(657): craft\elements\User::findIdentity('216')
#13 /var/www/html/vendor/craftcms/cms/src/web/User.php(403): yii\web\User->renewAuthStatus()
#14 /var/www/html/vendor/yiisoft/yii2/web/User.php(188): craft\web\User->renewAuthStatus()
#15 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(193): yii\web\User->getIdentity()
#16 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1205): craft\web\Application->getTargetLanguage(true)
#17 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1188): craft\web\Application->_setLanguage()
#18 /var/www/html/vendor/craftcms/cms/src/web/Application.php(83): craft\web\Application->_init()
#19 /var/www/html/vendor/yiisoft/yii2/base/Object.php(107): craft\web\Application->init()
#20 /var/www/html/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(71): yii\base\Application->__construct(Array)
#22 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(220): craft\web\Application->__construct(Array)
#23 /var/www/html/vendor/craftcms/cms/bootstrap/web.php(47): require('/var/www/html/v...')
#24 /var/www/html/public/site/index.php(25): require('/var/www/html/v...')
```

- Craft version: Craft CMS 3.0.0-beta.9
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Hey @nateiler, can you send me a copy of your plugin and a database backup that will trigger the migration, to support@craftcms.com ?

**Comment by brandonkelly** [comment]
@nateiler Closing this due to lack of response. Wondering if it might be related to #1626 - maybe the plugin wasn’t actually enabled/installed at the time that this error occurred, but that didn’t stop Composer from autoloading the field type.

**Comment by nateiler** [comment]
Sorry about the radio silence.  This may be related to (haven't tested yet). #1671
