### ISSUE TITLE
[5.5.0]: Class "craft\elements\MatrixBlock" not found

### ISSUE THREAD

**Issue by tibbis** [craftcms/cms#16105]
### Description
When i'm adding a new matrixBlock field to any entryType, I can an error "Class "craft\elements\MatrixBlock" not found" on all pages and cant use control panel at all. Needed to clear drafts (craft gc) and then downgrade to be able to use craft again. 

### Steps to reproduce

1. Add a matrixBlock field type to an EntryType
2. Save Entry Type

### Expected behavior
No error

### Actual behavior
Error and unusable control panel and website.

```
Error: Class "craft\elements\MatrixBlock" not found in /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php:270
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\models\FieldLayout->init()
#1 /var/www/html/vendor/craftcms/cms/src/base/Model.php(87): yii\base\BaseObject->__construct()
#2 [internal function]: craft\base\Model->__construct()
#3 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#4 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#5 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#6 /var/www/html/vendor/craftcms/cms/src/Craft.php(70): yii\BaseYii::createObject()
#7 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(1069): Craft::createObject()
#8 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(904): craft\services\Fields->createLayout()
#9 [internal function]: craft\services\Fields->craft\services\{closure}()
#10 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(90): call_user_func()
#11 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(76): craft\base\MemoizableArray->normalizeByKey()
#12 [internal function]: craft\base\MemoizableArray->craft\base\{closure}()
#13 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(76): array_map()
#14 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(104): craft\base\MemoizableArray->normalize()
#15 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(996): craft\base\MemoizableArray->all()
#16 /var/www/html/vendor/craftcms/cms/src/Craft.php(370): craft\services\Fields->getAllLayouts()
#17 /var/www/html/vendor/craftcms/cms/src/Craft.php(242): Craft::_fields()
#18 /var/www/html/vendor/craftcms/cms/src/Craft.php(205): Craft::_autoloadCustomFieldBehavior()
#19 [internal function]: Craft::autoload()
#20 /var/www/html/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct()
#21 /var/www/html/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#22 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#23 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#24 /var/www/html/vendor/yiisoft/yii2/base/Component.php(764): yii\BaseYii::createObject()
#25 /var/www/html/vendor/yiisoft/yii2/base/Component.php(748): yii\base\Component->attachBehaviorInternal()
#26 /var/www/html/vendor/yiisoft/yii2/base/Component.php(473): yii\base\Component->ensureBehaviors()
#27 /var/www/html/vendor/craftcms/cms/src/db/Query.php(55): yii\base\Component->hasEventHandlers()
#28 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\db\Query->init()
#29 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(606): yii\base\BaseObject->__construct()
#30 /var/www/html/vendor/craftcms/cms/src/elements/User.php(276): craft\elements\db\ElementQuery->__construct()
#31 /var/www/html/vendor/craftcms/cms/src/elements/User.php(598): craft\elements\User::find()
#32 /var/www/html/vendor/yiisoft/yii2/web/User.php(699): craft\elements\User::findIdentity()
#33 /var/www/html/vendor/craftcms/cms/src/web/User.php(452): yii\web\User->renewAuthStatus()
#34 /var/www/html/vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#35 /var/www/html/vendor/craftcms/cms/src/web/Application.php(444): yii\web\User->getIdentity()
#36 /var/www/html/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->debugBootstrap()
#37 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#38 /var/www/html/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#39 [internal function]: yii\base\Application->__construct()
#40 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#41 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#42 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#43 /var/www/html/vendor/craftcms/cms/src/Craft.php(70): yii\BaseYii::createObject()
#44 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(339): Craft::createObject()
#45 /var/www/html/vendor/craftcms/cms/bootstrap/web.php(40): require('...')
#46 /var/www/html/web/index.php(11): require('...')
#47 {main}
```

### Craft CMS version

5.5

**Comment by i-just** [comment]
Hi, thanks for reporting! Sounds like it’s the same root cause as https://github.com/craftcms/cms/issues/16095. PR is already raised.

**Comment by brandonkelly** [comment]
Craft 5.5.0.1 is out with that fix. Thanks again!

**Comment by ryanleichty** [comment]
I had this same issue and the latest patch resolved it for me
