### ISSUE TITLE
[4.x]: Fatal PHP error after upgrade to 4.13.1

### ISSUE THREAD

**Issue by d--j** [craftcms/cms#16142]
### Steps to reproduce

1. Upgrade CraftCMS from 4.13.0 to 4.13.1
2. `ddev craft`

### Expected behavior

Output list of commands

### Actual behavior

```
PHP Fatal error:  Uncaught Error: Class "Craft" not found in /var/www/html/vendor/craftcms/cms/src/helpers/App.php:276
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(31): craft\helpers\App::cliOption('--vendorPath', true)
#1 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(35): {closure}('--vendorPath', 'CRAFT_VENDOR_PA...')
#2 /var/www/html/vendor/craftcms/cms/bootstrap/console.php(42): require('/var/www/html/v...')
#3 /var/www/html/craft(12): require('/var/www/html/v...')
#4 {main}
  thrown in /var/www/html/vendor/craftcms/cms/src/helpers/App.php on line 276
Fatal error: Uncaught Error: Class "Craft" not found in /var/www/html/vendor/craftcms/cms/src/helpers/App.php:276
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(31): craft\helpers\App::cliOption('--vendorPath', true)
#1 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(35): {closure}('--vendorPath', 'CRAFT_VENDOR_PA...')
#2 /var/www/html/vendor/craftcms/cms/bootstrap/console.php(42): require('/var/www/html/v...')
#3 /var/www/html/craft(12): require('/var/www/html/v...')
#4 {main}
  thrown in /var/www/html/vendor/craftcms/cms/src/helpers/App.php on line 276
Failed to run craft : exit status 255
```

### Craft CMS version

4.13.1

### PHP version

8.2

### Operating system and version

ddev

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Doh, thanks for reporting that. Fixed in 4.13.1.1.
