### ISSUE TITLE
[5.x]: User is not authorized to perform this action

### ISSUE THREAD

**Issue by mariuswestgaard** [craftcms/cms#16284]
### Description
The user I'm signed in with is Admin. But, I'm unable to remove a nested entry in a matrix field. I can update the content in the selected nested entry. The matrix can add max 1 entry. The entry type selected in the matrix is updateable after creating, but I can't remove the nested element. Whenever I click remove in the options for the field, I get the following error even though my user is Admin: `User is not authorized to perform this action` 

Trace:
```
2024-12-05 21:07:09 [web.ERROR] [yii\web\HttpException:403] yii\web\ForbiddenHttpException: User is not authorized to perform this action in /app/backend/vendor/craftcms/cms/src/controllers/NestedElementsController.php:65
Stack trace:
#0 /app/backend/vendor/yiisoft/yii2/base/Controller.php(176): craft\controllers\NestedElementsController->beforeAction(Object(yii\base\InlineAction))
#1 /app/backend/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('delete', Array)
#2 /app/backend/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction('nested-elements...', Array)
#3 /app/backend/vendor/craftcms/cms/src/web/Application.php(649): craft\web\Application->runAction('nested-elements...', Array)
#4 /app/backend/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#5 /app/backend/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#6 /app/backend/web/index.php(12): yii\base\Application->run()
#7 {main} {"memory":4049240,"exception":"[object] (yii\\web\\ForbiddenHttpException(code: 0): User is not authorized to perform this action at /app/backend/vendor/craftcms/cms/src/controllers/NestedElementsController.php:65)"} 
```

### Steps to reproduce

1. Login to the cms as an admin account.
2. Add a matrix field to a sections entry type, and allow it to add max 1 entry type.
3. Add the entry type to the matrix field in the entry, and save. It worked saving.
4. Try to remove the nested entry type.
5. It fails with the errors described.

### Expected behavior
I would expect that the nested were deleted, and I could then add a new nested entry.

### Actual behavior
I can't delete the nested entry.

### Craft CMS version

5.5.5

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I’m not able to reproduce this. 
What view mode is this matrix field using? Could you also please turn on the [`safeMode`](https://craftcms.com/docs/5.x/reference/config/general.html#safemode) and see if you’re still getting the same behaviour?

**Comment by hotnunstar** [comment]
Hello.
Have you solved this issue? I'm getting exactly the same behavior.
Thank you.

**Comment by mateoamilia** [comment]
I am currently getting this error "Unauthorized - User is not authorized to perform this action"
when we write a blog post, and set the post date to upload in the future, say a week from today. 
The preview button and the View buttons don't work anymore. this is only since the recent critical update, and we are now on craft cms 4.15.2

But if I change the post date to yesterday, its live, and both of those buttons work.

**Comment by brandonkelly** [comment]
@mateoamilia I’m not able to reproduce that. If you go to `/admin/utilities/php-info?foo=bar`, and search the page for `$_REQUEST['foo']` and `$_GET['foo']`, are the values both set to `bar`? And if you search for `$_SERVER['QUERY_STRING']`, do you get `foo=bar`?

**Comment by mateoamilia** [comment]
@brandonkelly indeed, we get those expected values.

**Comment by brandonkelly** [comment]
Have you tried enabling [safeMode](https://craftcms.com/docs/5.x/reference/config/general.html#safemode) as @i-just previously suggested? That can help narrow down whether it’s a Craft or plugin issue.
