### ISSUE TITLE
[5.x]: Typed property craft\web\Application::$edition must not be accessed before initialization

### ISSUE THREAD

**Issue by bartrylant** [craftcms/cms#16288]
### Description
I've updated Craft to 5.5.5 and updated some other plugins as well. At first I thought it was an issue with Blitz, but when I downgraded Craft back to 5.5.4 te issue was gone.

When I add a new field and save, I get the error page shown in the attachment to this post. The error doesn't go away anymore. As soon as I visit any other CP page, it shows everywhere.

### Steps to reproduce

1. Update to Craft 5.5.5
2. Make a new field
3. Hit the save button

![Image](https://github.com/user-attachments/assets/74a8a5b9-9e62-4c38-a874-cc3ed3765c77)

### Craft CMS version

5.5.5

### PHP version

8.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I’m not able to reproduce that.

Make sure you’re running the latest version of Blitz. If you’re still seeing the error, please search for it within `storage/logs/web.log` and post the full stack trace.

**Comment by denisyilmaz** [comment]
We are experiencing this same error with the Verbb Navigation Plugin. here is our Stack Trace: 

```bash
Error: Typed property craft\web\Application::$edition must not be accessed before initialization in /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php:593
Stack trace:
#0 /var/www/html/vendor/verbb/navigation/src/Navigation.php(103): craft\web\Application->getEdition()
#1 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): verbb\navigation\Navigation->init()
#2 /var/www/html/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct(Array)
#3 /var/www/html/vendor/craftcms/cms/src/base/Plugin.php(125): yii\base\Module->__construct('navigation', Object(craft\web\Application), Array)
#4 [internal function]: craft\base\Plugin->__construct('navigation', Object(craft\web\Application), Array)
#5 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#6 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('verbb\\navigatio...', Array, Array)
#7 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('verbb\\navigatio...', Array, Array)
#8 /var/www/html/vendor/craftcms/cms/src/Craft.php(70): yii\BaseYii::createObject(Array, Array)
#9 /var/www/html/vendor/craftcms/cms/src/services/Plugins.php(950): Craft::createObject(Array, Array)
#10 /var/www/html/vendor/craftcms/cms/src/services/Plugins.php(235): craft\services\Plugins->createPlugin('navigation', Array)
#11 /var/www/html/vendor/craftcms/cms/src/services/Plugins.php(813): craft\services\Plugins->loadPlugins()
#12 /var/www/html/vendor/craftcms/cms/src/helpers/Component.php(68): craft\services\Plugins->isPluginEnabled('icon-picker')
#13 /var/www/html/vendor/craftcms/cms/src/helpers/Component.php(133): craft\helpers\Component::validateComponentClass('verbb\\iconpicke...', 'craft\\base\\Fiel...', true)
#14 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(417): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#15 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(444): craft\services\Fields->createField(Array)
#16 [internal function]: craft\services\Fields->craft\services\{closure}(Array, 3)
#17 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(90): call_user_func(Object(Closure), Array, 3)
#18 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(76): craft\base\MemoizableArray->normalizeByKey(3)
#19 [internal function]: craft\base\MemoizableArray->craft\base\{closure}(3)
#20 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(76): array_map(Object(Closure), Array)
#21 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(104): craft\base\MemoizableArray->normalize(Array)
#22 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(468): craft\base\MemoizableArray->all()
#23 /var/www/html/vendor/craftcms/cms/src/Craft.php(389): craft\services\Fields->getAllFields(false)
#24 /var/www/html/vendor/craftcms/cms/src/Craft.php(241): Craft::_fields()
#25 /var/www/html/vendor/craftcms/cms/src/Craft.php(204): Craft::_autoloadCustomFieldBehavior()
#26 [internal function]: Craft::autoload('craft\\behaviors...')
#27 /var/www/html/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct('craft\\behaviors...')
#28 /var/www/html/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies('craft\\behaviors...')
#29 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\behaviors...', Array, Array)
#30 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\behaviors...', Array, Array)
#31 /var/www/html/vendor/yiisoft/yii2/base/Component.php(768): yii\BaseYii::createObject(Array)
#32 /var/www/html/vendor/yiisoft/yii2/base/Component.php(752): yii\base\Component->attachBehaviorInternal('customFields', Array)
#33 /var/www/html/vendor/yiisoft/yii2/base/Component.php(477): yii\base\Component->ensureBehaviors()
#34 /var/www/html/vendor/craftcms/cms/src/db/Query.php(55): yii\base\Component->hasEventHandlers('init')
#35 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\db\Query->init()
#36 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(626): yii\base\BaseObject->__construct(Array)
#37 /var/www/html/vendor/craftcms/cms/src/elements/User.php(282): craft\elements\db\ElementQuery->__construct('craft\\elements\\...')
#38 /var/www/html/vendor/craftcms/cms/src/elements/User.php(628): craft\elements\User::find()
#39 /var/www/html/vendor/yiisoft/yii2/web/User.php(699): craft\elements\User::findIdentity(7309)
#40 /var/www/html/vendor/craftcms/cms/src/web/User.php(548): yii\web\User->renewAuthStatus()
#41 /var/www/html/vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#42 /var/www/html/vendor/yiisoft/yii2/web/User.php(367): yii\web\User->getIdentity()
#43 /var/www/html/vendor/craftcms/cms/src/web/User.php(226): yii\web\User->getIsGuest()
#44 /var/www/html/vendor/craftcms/cms/src/services/Sites.php(1272): craft\web\User->getIsGuest()
#45 /var/www/html/vendor/craftcms/cms/src/services/Sites.php(664): craft\services\Sites->_allSites(NULL)
#46 /var/www/html/vendor/craftcms/cms/src/filters/SiteFilterTrait.php(51): craft\services\Sites->getSiteByHandle('site_en')
#47 /var/www/html/vendor/craftcms/cms/src/filters/SiteFilterTrait.php(43): craft\filters\Cors->getSiteId('site_en')
#48 [internal function]: craft\filters\Cors->craft\filters\{closure}('site_en')
#49 /var/www/html/vendor/craftcms/cms/src/filters/SiteFilterTrait.php(43): array_map(Object(Closure), Array)
#50 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(159): craft\filters\Cors->setSite(Array)
#51 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(557): yii\base\BaseObject->__set('site', Array)
#52 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\filters\Cors), Array)
#53 [internal function]: yii\base\BaseObject->__construct(Array)
#54 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#55 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\filters\\C...', Array, Array)
#56 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\filters\\C...', Array, Array)
#57 /var/www/html/vendor/yiisoft/yii2/base/Component.php(198): yii\BaseYii::createObject(Array)
#58 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(557): yii\base\Component->__set('corsFilter', Array)
#59 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\web\Application), Array)
#60 /var/www/html/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#61 [internal function]: yii\base\Application->__construct(Array)
#62 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#63 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#64 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#65 /var/www/html/vendor/craftcms/cms/src/Craft.php(70): yii\BaseYii::createObject(Array, Array)
#66 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(306): Craft::createObject(Array)
#67 /var/www/html/vendor/craftcms/cms/bootstrap/web.php(35): require('/var/www/html/v...')
#68 /var/www/html/web/index.php(11): require('/var/www/html/v...')
#69 {main}
```

this is happening in Craft 5.8.17

**Comment by denisyilmaz** [comment]
@brandonkelly as a additional info: the error is only thrown if we are editing the project (editing sections, entries or fields). When disabling the Navigation Plugin we can save the changes.

**Comment by i-just** [comment]
Thanks for the stack trace, @denisyilmaz! I can reproduce this now. 

It looks to be related to `SiteFilterTrait`, which is used by the [`Cors` filter](https://craftcms.com/docs/5.x/reference/config/app.html#cors). If I add `as corsFilter` via `config/app.php`, in that filter use `'site' => ['default']` and then try to create a new field, I get the edition error when I try to save that new field.

We’ll look into it.

**Comment by denisyilmaz** [comment]
@i-just Thanks for the details! That actually explains a lot. We were scratching our heads about when this bug first showed up (since we didn’t update any dependencies). Turns out it started right after we implemented the `as corsFilter` feature in `app.web.php` last week.  

For now, I’ve disabled the site-specific scoping, and I’m able to save again.

**Comment by i-just** [comment]
It looks like if you use site IDs (not handles) in your cors filter, you shouldn’t encounter this error. I'm working on a proper solution.

**Comment by brandonkelly** [comment]
Craft 5.8.18 is out with a fix for this. Thanks again!
