### ISSUE TITLE
Unknown Property thrown when modifying elements query via field type

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#2081]
### Description
I'm modifying the elements query to add an additional order option for my field type:
```php
$query->addSelect("$haversine AS [[distance]]");
```
Which is causing Craft to throw an Unknown Property error on `ElementQuery.php:2007`. The issue appears to be `Yii::configure` not checking to see if a property exists before trying to set it.

### Steps to reproduce

1. Modify the elements query and add an additional select (`$query->addSelect('(0) AS example'`) that does not exist on the element type you are querying.
2. Attempt to run an element query.

### Additional info

- Craft version: Craft Pro 3.0.0-beta.30
- PHP version: 7.1.8
- Database driver & version: PostgreSQL 10.0
- Plugins & versions: 

[SimpleMap (WIP)](https://github.com/ethercreative/simplemap/tree/v3-dev) | 3.0.0
-- | --

**Comment by takobell** [comment]
Is `$haversine` an actual variable?  If it's an actual column name, it should be `$query->addSelect(['haversine as distance]);`  If it's a variable name because the column is dynamic, then `$query->addSelect([$haversine. ' as distance]);`

**Comment by Tam** [comment]
Yeah, it's a calculation to find a location within a given radius.

Changing `$query->addSelect("$haversine AS [[distance]]");` to `$query->addSelect([$haversine.' as distance']);` still causes the same error.

**Comment by Tam** [comment]
Here's the full stack trace:
```
yii\base\UnknownPropertyException: Setting unknown property: craft\elements\Entry::distance in /Users/tam/Sites/3.dev/vendor/yiisoft/yii2/base/Component.php:201

Stack trace:
#0 /Users/tam/Sites/3.dev/vendor/yiisoft/yii2/BaseYii.php(529): yii\base\Component->__set('distance', 0)
#1 /Users/tam/Sites/3.dev/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(craft\elements\Entry), Array)
#2 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2007): yii\base\Object->__construct(Array)
#3 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1932): craft\elements\db\ElementQuery->_createElement(Array)
#4 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/elements/db/ElementQuery.php(978): craft\elements\db\ElementQuery->_createElements(Array)
#5 /Users/tam/Sites/3.dev/vendor/yiisoft/yii2/db/Query.php(214): craft\elements\db\ElementQuery->populate(Array)
#6 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/db/Query.php(119): yii\db\Query->all(NULL)
#7 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1004): craft\db\Query->all(NULL)
#8 /Users/tam/Sites/3.dev/vendor/twig/twig/lib/Twig/Extension/Core.php(1595): craft\elements\db\ElementQuery->all()
#9 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/helpers/Template.php(76): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\elements\db\EntryQuery), 'all', Array, 'method', false, false)
#10 /Users/tam/Sites/3.dev/storage/runtime/compiled_templates/95/95960983c952014396f87734675f1ee5daacd036c938a689541a3b4a3487285c.php(22): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\elements\db\EntryQuery), 'all', Array, 'method')
#11 /Users/tam/Sites/3.dev/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_db8001e9072690f27f2eecc8ed7bd0f5eca19003cdab40d37159db115dd2eb2e->doDisplay(Array, Array)
#12 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#13 /Users/tam/Sites/3.dev/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#14 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#15 /Users/tam/Sites/3.dev/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#16 /Users/tam/Sites/3.dev/vendor/twig/twig/lib/Twig/Environment.php(288): Twig_Template->render(Array)
#17 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/web/View.php(296): Twig_Environment->render('index', Array)
#18 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/web/View.php(344): craft\web\View->renderTemplate('index', Array)
#19 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/web/Controller.php(101): craft\web\View->renderPageTemplate('index', Array)
#20 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/controllers/TemplatesController.php(79): craft\web\Controller->renderTemplate('index', Array)
#21 [internal function]: craft\controllers\TemplatesController->actionRender('index', Array)
#22 /Users/tam/Sites/3.dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /Users/tam/Sites/3.dev/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#24 /Users/tam/Sites/3.dev/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('render', Array)
#25 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/web/Application.php(242): yii\base\Module->runAction('templates/rende...', Array)
#26 /Users/tam/Sites/3.dev/vendor/yiisoft/yii2/web/Application.php(102): craft\web\Application->runAction('templates/rende...', Array)
#27 /Users/tam/Sites/3.dev/vendor/craftcms/cms/src/web/Application.php(207): yii\web\Application->handleRequest(Object(craft\web\Request))
#28 /Users/tam/Sites/3.dev/vendor/yiisoft/yii2/base/Application.php(380): craft\web\Application->handleRequest(Object(craft\web\Request))
#29 /Users/tam/Sites/3.dev/web/index.php(21): yii\base\Application->run()
#30 {main}
```

**Comment by brandonkelly** [comment]
It’s specifically complaining because the resulting row contains a `distance` column value, but the element doesn’t have a `$distance` property. What are you expecting `$element->distance` to resolve to?

**Comment by Tam** [comment]
I wasn't expecting `$element->distance` at all! 

I've added the `distance` column to allow users to order their entries by distance from a given location, it's not meant for anything else (unless there's a way to pass the value to the field's model to save me re-calculating the distance later on).

`distance` shouldn't be passed to the element, it should only be being used in the query.

Modifying [`ElementQuery.php:2007`](https://github.com/craftcms/cms/blob/68b2ff09d8a1e8da904e46e54f241cec11dd082c/src/elements/db/ElementQuery.php#L2007) to filter out any properties that don't exist on the element seems to fix the issue:

```php
        /** @var Element $element */
//      $element = new $class($row);
        $element = new $class(array_filter(
	        $row,
	        function ($key) use ($class) {
		        return property_exists($class, $key);
	        },
	        ARRAY_FILTER_USE_KEY
        ));
```

**Comment by brandonkelly** [comment]
If you don’t want it in the element, then why are you selecting it in the query? (You don’t need to select it to use it in your conditions.)

**Comment by Tam** [comment]
It's the only way I could get it to work!

How would I go about ordering without adding a select? I've tried replacing the `distance` order, but it is always reset back to `distance`.

**Comment by Tam** [comment]
I've experimented some more and I've landed on something that works:

```php
if (array_key_exists('distance', $query->orderBy)) {
	$nextOrder = [];

	foreach ($query->orderBy as $order => $sort) {
		if ($order == 'distance') $nextOrder[$haversine] = $sort;
		else $nextOrder[$order] = $sort;
	}

	$query->orderBy($nextOrder);
}
```

Can I confirm this is the correct way of doing it (and not super hacky)?

**Comment by brandonkelly** [comment]
Yeah that could work if you want people to type `orderBy('distance')` rather than whatever the actual column is called.

**Comment by Tam** [comment]
Thanks!
