### ISSUE TITLE
"Save as a new entry" fails on EVENT_BEFORE_SAVE  returning `isValid = false` 

### ISSUE THREAD

**Issue by noandrea** [craftcms/cms#2237]
### Description

I have an event function (triggered by `EVENT_BEFORE_SAVE`) that returns `isValid` false when an entry with the same title already exists.

What I am experiencing is:
- case 1: new entry and there is no entry with the same title
- case 2: new entry and there is already an entry with the same title 
- case 3: old entry + save as a new entry and there is no entry with the same title
- case 4: old entry + save as a new entry and there is already an entry with the same title 

case 1,2,3 are ok, case 4 fails with the following stack trace:

```
yii\base\Exception: Element 6 could not be duplicated for site 1 in /mycraftprj/vendor/craftcms/cms/src/services/Elements.php:588
Stack trace:
#0 /mycraftprj/vendor/craftcms/cms/src/controllers/EntriesController.php(465): craft\services\Elements->duplicateElement(Object(craft\elements\Entry))
#1 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#2 /mycraftprj/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /mycraftprj/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /mycraftprj/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('save-entry', Array)
#5 /mycraftprj/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#6 /mycraftprj/vendor/craftcms/cms/src/web/Application.php(242): yii\base\Module->runAction('entries/save-en...', Array)
#7 /mycraftprj/vendor/craftcms/cms/src/web/Application.php(420): craft\web\Application->runAction('entries/save-en...', Array)
#8 /mycraftprj/vendor/craftcms/cms/src/web/Application.php(202): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /mycraftprj/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /mycraftprj/web/index.php(21): yii\base\Application->run()
#11 {main}

Next yii\web\ServerErrorHttpException: An error occurred when duplicating the entry. in /mycraftprj/vendor/craftcms/cms/src/controllers/EntriesController.php:467
Stack trace:
#0 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#1 /mycraftprj/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /mycraftprj/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /mycraftprj/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('save-entry', Array)
#4 /mycraftprj/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#5 /mycraftprj/vendor/craftcms/cms/src/web/Application.php(242): yii\base\Module->runAction('entries/save-en...', Array)
#6 /mycraftprj/vendor/craftcms/cms/src/web/Application.php(420): craft\web\Application->runAction('entries/save-en...', Array)
#7 /mycraftprj/vendor/craftcms/cms/src/web/Application.php(202): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /mycraftprj/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /mycraftprj/web/index.php(21): yii\base\Application->run()
#10 {main}
```

the exception generates in [Elements.php#L585](https://github.com/craftcms/cms/blob/develop/src/services/Elements.php#L585) and looks like is due to the function `saveElement` at [Elements.php#L365](https://github.com/craftcms/cms/blob/develop/src/services/Elements.php#L365) that returns `false` when my plugin sets the `isValid` field to `false`. 

### Additional info

- Craft version: 3.0.0-RC3
- PHP version: 7.1.7
- Database driver & version: MySQL 5.7.20
- Plugins & versions: None

**Comment by brandonkelly** [comment]
This is expected behavior; it’s not really feasible for Craft to fail gracefully when something goes wrong while duplicating an element. It duplicates it across all the sites, so it wouldn’t be possible to show just a single Edit page with any validation errors.

Why are you setting `isValid` to `false` in the first place?

**Comment by noandrea** [comment]
I have an extension that prevents to create an entry of the same type having a field with the same value. For example let's say you have a section of entries "Authors" and every author has a different name and you want to make sure that authors do not get duplicated (especially when you insert them from a related entry). 

With craft 2.6.x the extension set the `$event->performAction` to `false` for the [`onBeforeSaveElement`](https://craftcms.com/docs/plugins/events-reference#elements-onBeforeSaveElement) event and that was working in all the 4 cases.

I ask in the slack channel what was the craft 3 way to achieve the same and I was pointed to the use of `isValid` with the `EVENT_BEFORE_SAVE`, and I assumed the behaviour was consistent with the 2.6.x. 

What will be then the 3.x way for the scenario described in the issue?

thanks

**Comment by brandonkelly** [comment]
That is the Craft 3 equivalent, yes. The difference is that more things go through `saveElement()` in Craft 3, including element duplication, and propagating an element’s content across other sites. So your plugin just has to be aware of those scenarios.

**Comment by noandrea** [comment]
well, I am aware now that the behaviour of the API is inconsistent, since the `isValid` will cause an exception only when you click the interface button "save as new entry" (no error if I click new entry and then save). 

What does it mean that "your plugin just has to be aware of those scenarios" ?  Should I use other API? There is a way to work around that or should just tell the users that the "save as new entry" isn't supported anymore for this scenario?

**Comment by brandonkelly** [comment]
Sorry for being curt. In Craft 2, when you click “Save as new entry”, it basically just submits the form like the “Save” button does, but the entry’s ID is discarded, so Craft takes the POST data and creates a new entry from it. If there were any validation errors, or if `performAction` was set to `false`, then the Edit Entry page would be reloaded with a “Couldn’t save entry” message – for the _new, unsaved_ entry.

The issue with that approach is, if the entry had multiple locales, you would lose all of your translations in the process, because those other locales’ data aren’t part of the POST data, and Craft isn’t capable of saving new locale data for more than one locale at a time.

So in Craft 3, the solution to that is that clicking “Save as a new entry” actually begins by fully duplicating the entry, across all its sites. Only after that is done will it take the POST data and re-save the duplicated entry, for the currently-selected site.

But that leads us to this issue. If there are any problems with duplicating the entry (such as `isValid` getting set to `false` on the before-save event), then the whole operation is cancelled.

Now that I think about it, I suppose we could handle the error a bit better. Even reverting to Craft 2 behavior would be better than just allowing the exception message to surface: Re-display the Edit Entry page, for the unsaved duplicate entry, with a “Couldn’t save entry” message, and at that point if they save it, they will lose other sites’ data (if there is any).

**Comment by brandonkelly** [comment]
…and fixed for the next release. Thanks for the nudge :)

You can either wait for RC4 to be released (planned for Jan 2), or change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.0.0-RC99"`, and then run `composer update`.

**Comment by noandrea** [comment]
great, thanks! 
I'll wait for the next RC to come out. 

and happy new year 🎆 !

**Comment by brandonkelly** [comment]
You too!
