### ISSUE TITLE
[exception.Craft\HttpException.404] exception

### ISSUE THREAD

**Issue by aashish-pixere** [craftcms/cms#2247]
I  am using GoDaddy shared hosting and using Craft CMS 2.6.2791 (Pro)
Could anyone help us to sort out?

```
2017/12/28 06:50:28 [error] [exception.Craft\HttpException.404] exception 'Craft\HttpException' in /home/xxxxxx/public_html/sitefolder/craft/app/controllers/TemplatesController.php:59
Stack trace:
#0 [internal function]: Craft\TemplatesController->actionRender('favicon.ico', Array)
#1 /home/xxxxxx/public_html/sitefolder/craft/app/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(Craft\TemplatesController), Array)
#2 /home/xxxxxx/public_html/sitefolder/craft/app/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(Craft\TemplatesController), Object(ReflectionMethod), Array)
#3 /home/xxxxxx/public_html/sitefolder/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/xxxxxx/public_html/sitefolder/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/xxxxxx/public_html/sitefolder/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/xxxxxx/public_html/sitefolder/craft/app/framework/web/CWebApplication.php(282): CController->run('render')
#7 /home/xxxxxx/public_html/sitefolder/craft/app/framework/web/CWebApplication.php(141): CWebApplication->runController('templates/rende...')
#8 /home/xxxxxx/public_html/sitefolder/craft/app/etc/web/WebApp.php(288): CWebApplication->processRequest()
#9 /home/xxxxxx/public_html/sitefolder/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#10 /home/xxxxxx/public_html/sitefolder/craft/app/index.php(62): CApplication->run()
#11 /home/xxxxxx/public_html/sitefolder/html/index.php(19): require_once('/home/xxxxxx/p...')
#12 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=https://domain/admin/login
```

**Comment by brandonkelly** [comment]
This is normal. Craft 2 logs all exceptions, including 404s, in `craft.log`. Browsers always try to load /favicon.ico when visiting a site, to load the site’s favicon. You can fix by giving your site a favicon.

This is less awkward in Craft 3, though, as 404s are now logged in their own `web-404s.log` file.
