### ISSUE TITLE
Update to 3.0.0-RC7 pushes ReflectionException when trying to view assets

### ISSUE THREAD

**Issue by lenchantin** [craftcms/cms#2344]
### Description

The system updated to 3.0.0-RC7. When I click on Assets in the menu bar, I get the following error:

ReflectionException
Class craft\web\assets\imageeditor\ImageEditorAsset does not exist

Stack trace at bottom of message.

### Steps to reproduce

1. Run the updater and update to 3.0.0-RC7.
2. Click on Assets in the left-hand menu.

### Additional info

- Craft version: Craft Client 3.0.0-RC7
- PHP version: 7.1.13
- Database driver & version: MySQL 5.7.21
- Plugins & versions: 
SimpleMap v3.1.3
Contact Form 2.1.1
Contact Form Honeypot 1.0.2
CKEditor 1.0.0-Beta2
Inventory 2.0.0
Store Hours 2.0.6

Stack Trace
`ReflectionException: Class craft\web\assets\imageeditor\ImageEditorAsset does not exist in /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/di/Container.php:426
Stack trace:
#0 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/di/Container.php(426): ReflectionClass->__construct('craft\\web\\asset...')
#1 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->getDependencies('craft\\web\\asset...')
#2 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\asset...', Array, Array)
#3 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\asset...', Array, Array)
#4 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/web/AssetManager.php(266): yii\BaseYii::createObject(Array)
#5 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/web/AssetManager.php(239): yii\web\AssetManager->loadBundle('craft\\web\\asset...', Array, true)
#6 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/web/View.php(286): yii\web\AssetManager->getBundle('craft\\web\\asset...')
#7 /home/dev/sites/tranquilminds.life/current/vendor/twig/twig/lib/Twig/Extension/Core.php(1595): yii\web\View->registerAssetBundle('craft\\web\\asset...')
#8 /home/dev/sites/tranquilminds.life/current/vendor/craftcms/cms/src/helpers/Template.php(76): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method', false, false)
#9 /home/dev/sites/tranquilminds.life/current/storage/runtime/compiled_templates/65/653dd0ede332dfc296353f5fd614cb49617e7ce6fc3016307c80d8b07d0a8f93.php(30): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method')
#10 /home/dev/sites/tranquilminds.life/current/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_f62ba5769323984d6856955b4051fcbc1396d4fb9426406f1b279f3b37f9d5f1->doDisplay(Array, Array)
#11 /home/dev/sites/tranquilminds.life/current/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#12 /home/dev/sites/tranquilminds.life/current/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#13 /home/dev/sites/tranquilminds.life/current/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#14 /home/dev/sites/tranquilminds.life/current/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#15 /home/dev/sites/tranquilminds.life/current/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#16 /home/dev/sites/tranquilminds.life/current/vendor/craftcms/cms/src/web/View.php(308): Twig_Environment->render('assets', Array)
#17 /home/dev/sites/tranquilminds.life/current/vendor/craftcms/cms/src/web/View.php(356): craft\web\View->renderTemplate('assets', Array)
#18 /home/dev/sites/tranquilminds.life/current/vendor/craftcms/cms/src/web/Controller.php(121): craft\web\View->renderPageTemplate('assets', Array)
#19 /home/dev/sites/tranquilminds.life/current/vendor/craftcms/cms/src/controllers/TemplatesController.php(79): craft\web\Controller->renderTemplate('assets', Array)
#20 [internal function]: craft\controllers\TemplatesController->actionRender('assets', Array)
#21 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#23 /home/dev/sites/tranquilminds.life/current/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('render', Array)
#24 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#25 /home/dev/sites/tranquilminds.life/current/vendor/craftcms/cms/src/web/Application.php(251): yii\base\Module->runAction('templates/rende...', Array)
#26 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#27 /home/dev/sites/tranquilminds.life/current/vendor/craftcms/cms/src/web/Application.php(216): yii\web\Application->handleRequest(Object(craft\web\Request))
#28 /home/dev/sites/tranquilminds.life/current/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#29 /home/dev/sites/tranquilminds.life/current/web/index.php(21): yii\base\Application->run()
#30 {main}`

**Comment by lenchantin** [comment]
**Solved by clearing cache and updating asset index.**

Had my heart going there for a moment. Thanks for your hard work, fellas! Loving 3 muchly.
