### ISSUE TITLE
UpdateElementSlugsAndUris job fails when queue runs on the Console

### ISSUE THREAD

**Issue by ostark** [craftcms/cms#2347]
### Description

One stack trace says more than a thousand words:

```
2018-01-24 23:24:50 [-][-][-][error][yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: craft\console\Request::getHostInfo() in [...]/yiisoft/yii2/base/Component.php:294

Stack trace:
#0 [...]/craftcms/cms/src/helpers/UrlHelper.php(337): yii\base\Component->__call('getHostInfo', Array)
#1 [...]/craftcms/cms/src/helpers/UrlHelper.php(404): craft\helpers\UrlHelper::baseUrl()
#2 [...]/craftcms/cms/src/helpers/UrlHelper.php(236): craft\helpers\UrlHelper::_createUrl('login', '', NULL, false, false)
#3 [...]/craftcms/cms/src/web/twig/Extension.php(798): craft\helpers\UrlHelper::siteUrl('login')
#4 [...]/twig/twig/lib/Twig/ExtensionSet.php(337): craft\web\twig\Extension->getGlobals()
#5 [...]/twig/twig/lib/Twig/Environment.php(898): Twig_ExtensionSet->getGlobals()
#6 [...]/twig/twig/lib/Twig/Environment.php(918): Twig_Environment->getGlobals()
#7 [...]/twig/twig/lib/Twig/Template.php(366): Twig_Environment->mergeGlobals(Array)
#8 [...]/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#9 [...]/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#10 [...]/craftcms/cms/src/web/View.php(473): Twig_Template->render(Array)
#11 [...]/craftcms/cms/src/helpers/ElementHelper.php(197): craft\web\View->renderObjectTemplate('services/{{obje...', Object(stdClass))
#12 [...]/craftcms/cms/src/helpers/ElementHelper.php(68): craft\helpers\ElementHelper::doesUriFormatHaveSlugTag('services/{slug}')
#13 [...]/craftcms/cms/src/services/Elements.php(632): craft\helpers\ElementHelper::setUniqueUri(Object(craft\elements\Entry))
#14 [...]/craftcms/cms/src/queue/jobs/UpdateElementSlugsAndUris.php(129): craft\services\Elements->updateElementSlugAndUri(Object(craft\elements\Entry), true, false, false)
#15 [...]/craftcms/cms/src/queue/jobs/UpdateElementSlugsAndUris.php(79): craft\queue\jobs\UpdateElementSlugsAndUris->_processElements(Object(craft\queue\Queue), Object(craft\elements\db\EntryQuery))
#16 [...]/yiisoft/yii2-queue/src/Queue.php(213): craft\queue\jobs\UpdateElementSlugsAndUris->execute(Object(craft\queue\Queue))
#17 [...]/yiisoft/yii2-queue/src/cli/Queue.php(154): yii\queue\Queue->handleMessage('431', 'O:42:"craft\\que...', '300', '1')
#18 [...]/yiisoft/yii2-queue/src/cli/Command.php(128): yii\queue\cli\Queue->execute('431', 'O:42:"craft\\que...', '300', '1', '')
```

### Steps to reproduce

1. Disable auto queue handling
2. Trigger an Element Update
3. Run `php craft queue/run -v`

### Additional info

- Craft version: RC7 
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Thanks!
