### ISSUE TITLE
Public registration verification link does not work

### ISSUE THREAD

**Issue by steveooo9** [craftcms/cms#2358]
### Description
When enabling public user registrations and using the default form from the craftcms.com docs, 
a email get's send with this url: `https://foobar.de/zkr-admin/actions/users/verifyemail?code=GhiOgRrqICJFM4VF63%7EllmmMO%7Ep%7EZ5nx&id=7a468332-12a5-402f-b6c5-77babc158480`. But when opening this link, you get redirected to the login page of the backend and if you want to login, it says that the account isn't verified.

Funny thing: If you enter your username and click "forget password" and then you get a password reset link send that works and also with that, the account get's activated. So it seems that verifyemail Link somehow is buggy.

### Additional info

- Craft version: 2.6.3005
- PHP version: 7.1

**Comment by angrybrad** [comment]
Can you share the contents of your `craft/config/general.php` file?  You can redact out any sensitive bits of info you need to.  Also, does the user that is clicking the link has "Access the Control Panel" permissions assigned to them?

**Comment by steveooo9** [comment]
@angrybrad Here is a `.env.php` file:
```<?php

if (isset($_SERVER['HTTPS']) && (strcasecmp($_SERVER['HTTPS'], 'on') === 0 || $_SERVER['HTTPS'] == 1)
  || isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strcasecmp($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') === 0) {
  $proto = 'https';
} else {
  $proto = 'http';
}
$siteUrl = $proto.'://'.$_SERVER['SERVER_NAME'].'/';
$baseUrl = $siteUrl;
$basePath = realpath(__DIR__).'/public/';

$vars = [
  'CRAFT_ENV' => 'local', // 'local' | 'stage' | 'live'
  'DB_HOST' => 'localhost',
  'DB_NAME' => 'scotchbox',
  'DB_USER' => 'root',
  'DB_PASSWORD' => 'root',
  'DB_PORT' => '3306',
  'SITE_URL' => $siteUrl,
  'BASE_URL' => $baseUrl,
  'BASE_PATH' => $basePath,
  // Optional
  'DEV_MODE' => true,
];

foreach ($vars as $key => $value) {
  putenv($key.'='.$value);
}
```

And here is the `general.php`:
```<?php

/**
 * General Configuration
 *
 * All of your system's general configuration settings go in here.
 * You can see a list of the default settings in craft/app/etc/config/defaults/general.php
 */

$devMode = (getenv('DEV_MODE') !== false ? !!getenv('DEV_MODE') : false);

return [
  '*' => [
    'craftEnv' => CRAFT_ENVIRONMENT,
    'allowAutoUpdates' => false,
    'enableTemplateCaching' => true,
    'devMode' => $devMode,
    'cacheDuration' => 'P30M',
    'userSessionDuration' => 'PT2H',
    'timezone' => 'Europe/Berlin',
    'siteUrl' => [
      'de' => getenv('SITE_URL'),
      'en' => getenv('SITE_URL').'en/',
    ],
    'environmentVariables' => [
      'baseUrl' => getenv('BASE_URL'),
      'basePath' => getenv('BASE_PATH'),
    ],
    'langMap' => [
      'de' => 'de',
      'en' => 'en',
    ],
    'omitScriptNameInUrls' => true,
    'limitAutoSlugsToAscii' => true,
    'convertFilenamesToAscii' => true,
    'generateTransformsBeforePageLoad' => true,
    'pageTrigger' => 'seite-',
    'cpTrigger' => 'foobar-admin',
    'defaultCpLanguage' => 'de',
    'defaultSearchTermOptions' => [
      'subLeft' => true,
      'subRight' => true,
    ],
    'defaultWeekStartDay' => 1,
    'defaultImageQuality' => 90,
    'sendPoweredByHeader' => false,
  ],
  'local' => [
    'allowAutoUpdates' => true,
    'enableTemplateCaching' => false,
  ],
  'stage' => [],
  'live' => [],
];
```

Yes, this setting "Access the Control Panel" was assigned.

**Comment by angrybrad** [comment]
Hrm... can you reproduce the issue with devMode enabled, then share your `storage/logs/web.log` file?

**Comment by steveooo9** [comment]
@angrybrad I am using Craft 2. The log path you wrote isn't there..

**Comment by angrybrad** [comment]
Sorry... it'll be `craft/storage/runtime/logs/craft.log` on Craft 2.

**Comment by steveooo9** [comment]
@angrybrad Here is the log: ```2018/01/24 14:27:28 [error] [application] Unable to determine if PATH_INFO is enabled on the server: Client error response
[status code] 401
[reason phrase] Unauthorized
[url] https://foobar-project.dev.fooagency.de/index.php/testPathInfo

******************************************************************************************************
2018/01/24 14:27:29 [error] [exception.Craft\HttpException.404] Craft\HttpException in /var/www/foobar-project/htdocs/craft/app/controllers/TemplatesController.php:72
Stack trace:
#0 [internal function]: Craft\TemplatesController->actionRender('foundation/dist...', Array)
#1 /var/www/foobar-project/htdocs/craft/app/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(Craft\TemplatesController), Array)
#2 /var/www/foobar-project/htdocs/craft/app/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(Craft\TemplatesController), Object(ReflectionMethod), Array)
#3 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/foobar-project/htdocs/craft/app/framework/web/CWebApplication.php(282): CController->run('render')
#7 /var/www/foobar-project/htdocs/craft/app/framework/web/CWebApplication.php(141): CWebApplication->runController('templates/rende...')
#8 /var/www/foobar-project/htdocs/craft/app/etc/web/WebApp.php(290): CWebApplication->processRequest()
#9 /var/www/foobar-project/htdocs/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#10 /var/www/foobar-project/htdocs/craft/app/index.php(62): CApplication->run()
#11 /var/www/foobar-project/htdocs/public/index.php(29): require_once('/var/www/foobar-project...')
#12 {main}
REQUEST_URI=/foundation/dist/assets/img/favicon.ico
---

******************************************************************************************************
2018/01/24 14:27:30 [error] [exception.Craft\HttpException.404] Craft\HttpException in /var/www/foobar-project/htdocs/craft/app/controllers/TemplatesController.php:72
Stack trace:
#0 [internal function]: Craft\TemplatesController->actionRender('foundation/dist...', Array)
#1 /var/www/foobar-project/htdocs/craft/app/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(Craft\TemplatesController), Array)
#2 /var/www/foobar-project/htdocs/craft/app/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(Craft\TemplatesController), Object(ReflectionMethod), Array)
#3 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/foobar-project/htdocs/craft/app/framework/web/CWebApplication.php(282): CController->run('render')
#7 /var/www/foobar-project/htdocs/craft/app/framework/web/CWebApplication.php(141): CWebApplication->runController('templates/rende...')
#8 /var/www/foobar-project/htdocs/craft/app/etc/web/WebApp.php(290): CWebApplication->processRequest()
#9 /var/www/foobar-project/htdocs/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#10 /var/www/foobar-project/htdocs/craft/app/index.php(62): CApplication->run()
#11 /var/www/foobar-project/htdocs/public/index.php(29): require_once('/var/www/foobar-project...')
#12 {main}
REQUEST_URI=/foundation/dist/assets/img/favicon.png
---

******************************************************************************************************
2018/01/24 14:27:51 [error] [exception.Craft\HttpException.404] Craft\HttpException in /var/www/foobar-project/htdocs/craft/app/controllers/TemplatesController.php:72
Stack trace:
#0 [internal function]: Craft\TemplatesController->actionRender('foundation/dist...', Array)
#1 /var/www/foobar-project/htdocs/craft/app/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(Craft\TemplatesController), Array)
#2 /var/www/foobar-project/htdocs/craft/app/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(Craft\TemplatesController), Object(ReflectionMethod), Array)
#3 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/foobar-project/htdocs/craft/app/framework/web/CWebApplication.php(282): CController->run('render')
#7 /var/www/foobar-project/htdocs/craft/app/framework/web/CWebApplication.php(141): CWebApplication->runController('templates/rende...')
#8 /var/www/foobar-project/htdocs/craft/app/etc/web/WebApp.php(290): CWebApplication->processRequest()
#9 /var/www/foobar-project/htdocs/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#10 /var/www/foobar-project/htdocs/craft/app/index.php(62): CApplication->run()
#11 /var/www/foobar-project/htdocs/public/index.php(29): require_once('/var/www/foobar-project...')
#12 {main}
REQUEST_URI=/foundation/dist/assets/img/favicon.ico
HTTP_REFERER=https://foobar-project.dev.fooagency.de/
---

******************************************************************************************************
2018/01/24 14:32:23 [error] [exception.Craft\Exception] Craft\Exception: Die Aktualisierung konnte nicht installiert werden. :( <br /><br />The Mcrypt extension is required.<br /> in /var/www/foobar-project/htdocs/craft/app/controllers/TemplatesController.php:140
Stack trace:
#0 /var/www/foobar-project/htdocs/craft/app/framework/web/actions/CInlineAction.php(49): Craft\TemplatesController->actionRequirementsCheck()
#1 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#2 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#3 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /var/www/foobar-project/htdocs/craft/app/framework/web/CWebApplication.php(282): CController->run('requirementsche...')
#5 /var/www/foobar-project/htdocs/craft/app/etc/web/WebApp.php(880): CWebApplication->runController('templates/requi...')
#6 /var/www/foobar-project/htdocs/craft/app/etc/web/WebApp.php(212): Craft\WebApp->_processRequirementsCheck()
#7 /var/www/foobar-project/htdocs/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#8 /var/www/foobar-project/htdocs/craft/app/index.php(62): CApplication->run()
#9 /var/www/foobar-project/htdocs/public/index.php(29): require_once('/var/www/foobar-project...')
#10 {main}
REQUEST_URI=/zkr-admin/entries/homepage/2-homepage
HTTP_REFERER=https://foobar-project.dev.fooagency.de/
---

******************************************************************************************************
2018/01/24 14:35:21 [error] [application] There was a problem getting the update feed for “Delete All Entry Versions”, so it was skipped: Client error response
[status code] 404
[reason phrase] Not Found
[url] https://github.com/carlcs/craft-deleteallentryversions/raw/master/releases.json
2018/01/24 14:35:21 [error] [application] There was a problem getting the update feed for “Element API”, so it was skipped: Client error response
[status code] 404
[reason phrase] Not Found
[url] https://raw.githubusercontent.com/pixelandtonic/ElementAPI/master/releases.json
2018/01/24 14:35:21 [warning] [application] A “Formulare” release was skipped because it is invalid:
 - Missing required attributes (version, downloadUrl, date, notes)

******************************************************************************************************
2018/01/24 14:35:23 [error] [application] Tried to read the folder contents of /var/www/foobar-project/htdocs/craft/storage/runtime/cache/, but could not.
2018/01/24 14:35:23 [error] [application] Could not clear the contents of /var/www/foobar-project/htdocs/craft/storage/runtime/assets because the source folder does not exist.
2018/01/24 14:35:23 [error] [application] Could not clear the contents of /var/www/foobar-project/htdocs/craft/storage/runtime/temp because the source folder does not exist.

******************************************************************************************************
2018/01/24 14:35:24 [error] [application] There was a problem getting the update feed for “Delete All Entry Versions”, so it was skipped: Client error response
[status code] 404
[reason phrase] Not Found
[url] https://github.com/carlcs/craft-deleteallentryversions/raw/master/releases.json
2018/01/24 14:35:24 [error] [application] There was a problem getting the update feed for “Element API”, so it was skipped: Client error response
[status code] 404
[reason phrase] Not Found
[url] https://raw.githubusercontent.com/pixelandtonic/ElementAPI/master/releases.json
2018/01/24 14:35:24 [warning] [application] A “Formulare” release was skipped because it is invalid:
 - Missing required attributes (version, downloadUrl, date, notes)

******************************************************************************************************
2018/01/24 14:35:25 [error] [application] Unable to determine if PATH_INFO is enabled on the server: Client error response
[status code] 401
[reason phrase] Unauthorized
[url] https://foobar-project.dev.fooagency.de/index.php/testPathInfo

******************************************************************************************************
2018/01/26 14:17:08 [error] [exception.Craft\HttpException.404] Craft\HttpException in /var/www/foobar-project/htdocs/craft/app/controllers/TemplatesController.php:72
Stack trace:
#0 [internal function]: Craft\TemplatesController->actionRender('foundation/dist...', Array)
#1 /var/www/foobar-project/htdocs/craft/app/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(Craft\TemplatesController), Array)
#2 /var/www/foobar-project/htdocs/craft/app/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(Craft\TemplatesController), Object(ReflectionMethod), Array)
#3 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/foobar-project/htdocs/craft/app/framework/web/CWebApplication.php(282): CController->run('render')
#7 /var/www/foobar-project/htdocs/craft/app/framework/web/CWebApplication.php(141): CWebApplication->runController('templates/rende...')
#8 /var/www/foobar-project/htdocs/craft/app/etc/web/WebApp.php(290): CWebApplication->processRequest()
#9 /var/www/foobar-project/htdocs/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#10 /var/www/foobar-project/htdocs/craft/app/index.php(62): CApplication->run()
#11 /var/www/foobar-project/htdocs/public/index.php(29): require_once('/var/www/foobar-project...')
#12 {main}
REQUEST_URI=/foundation/dist/assets/img/favicon.ico
HTTP_REFERER=https://foobar-project.dev.fooagency.de/
---

******************************************************************************************************
2018/01/26 14:18:10 [warning] [application] Test2 tried to log in unsuccessfully.

******************************************************************************************************
2018/01/26 14:18:39 [warning] [application] test2 tried to log in unsuccessfully.

******************************************************************************************************
2018/01/26 14:18:44 [warning] [application] Craft\UsernameModel->username failed validation: Der Benutzername darf keine Leerzeichen enthalten.
2018/01/26 14:18:44 [warning] [application] Test 2 tried to log in unsuccessfully.

******************************************************************************************************
2018/01/26 14:18:51 [warning] [application] felix@fooagency.de tried to log in unsuccessfully.

******************************************************************************************************
2018/01/26 14:19:19 [warning] [application] felix@fooagency.de tried to log in unsuccessfully.

******************************************************************************************************
2018/01/26 14:23:58 [warning] [application] Craft\PasswordModel->password failed validation: Passwort darf nicht leer sein.

******************************************************************************************************
2018/01/26 14:24:44 [warning] [application] foobar tried to log in unsuccessfully.

******************************************************************************************************
2018/01/26 14:36:11 [warning] [application] foobar tried to log in unsuccessfully.

******************************************************************************************************
2018/01/30 13:13:23 [error] [exception.Craft\HttpException.404] Craft\HttpException in /var/www/foobar-project/htdocs/craft/app/controllers/TemplatesController.php:72
Stack trace:
#0 [internal function]: Craft\TemplatesController->actionRender('foundation/dist...', Array)
#1 /var/www/foobar-project/htdocs/craft/app/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(Craft\TemplatesController), Array)
#2 /var/www/foobar-project/htdocs/craft/app/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(Craft\TemplatesController), Object(ReflectionMethod), Array)
#3 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/foobar-project/htdocs/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/foobar-project/htdocs/craft/app/framework/web/CWebApplication.php(282): CController->run('render')
#7 /var/www/foobar-project/htdocs/craft/app/framework/web/CWebApplication.php(141): CWebApplication->runController('templates/rende...')
#8 /var/www/foobar-project/htdocs/craft/app/etc/web/WebApp.php(290): CWebApplication->processRequest()
#9 /var/www/foobar-project/htdocs/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#10 /var/www/foobar-project/htdocs/craft/app/index.php(62): CApplication->run()
#11 /var/www/foobar-project/htdocs/public/index.php(29): require_once('/var/www/foobar-project...')
#12 {main}
REQUEST_URI=/foundation/dist/assets/img/favicon.ico
HTTP_REFERER=https://foobar-project.dev.fooagency.de/
---

******************************************************************************************************
2018/01/30 13:17:40 [error] [application] Tried to read the folder contents of /var/www/foobar-project/htdocs/craft/storage/runtime/cache/, but could not.
2018/01/30 13:17:40 [error] [application] Could not clear the contents of /var/www/foobar-project/htdocs/craft/storage/runtime/assets because the source folder does not exist.
2018/01/30 13:17:42 [error] [application] Could not clear the contents of /var/www/foobar-project/htdocs/craft/storage/runtime/temp because the source folder does not exist.

******************************************************************************************************
2018/01/30 13:17:43 [error] [application] Unable to determine if PATH_INFO is enabled on the server: Client error response
[status code] 401
[reason phrase] Unauthorized
[url] https://foobar-project.dev.fooagency.de/index.php/testPathInfo

******************************************************************************************************
2018/01/30 13:18:08 [error] [application] There was a problem getting the update feed for “Delete All Entry Versions”, so it was skipped: Client error response
[status code] 404
[reason phrase] Not Found
[url] https://github.com/carlcs/craft-deleteallentryversions/raw/master/releases.json
2018/01/30 13:18:09 [error] [application] There was a problem getting the update feed for “Element API”, so it was skipped: Client error response
[status code] 404
[reason phrase] Not Found
[url] https://raw.githubusercontent.com/pixelandtonic/ElementAPI/master/releases.json
2018/01/30 13:18:09 [warning] [application] A “Formulare” release was skipped because it is invalid:
 - Missing required attributes (version, downloadUrl, date, notes)

******************************************************************************************************
2018/01/30 13:18:11 [error] [application] There was a problem getting the update feed for “Delete All Entry Versions”, so it was skipped: Client error response
[status code] 404
[reason phrase] Not Found
[url] https://github.com/carlcs/craft-deleteallentryversions/raw/master/releases.json
2018/01/30 13:18:11 [error] [application] There was a problem getting the update feed for “Element API”, so it was skipped: Client error response
[status code] 404
[reason phrase] Not Found
[url] https://raw.githubusercontent.com/pixelandtonic/ElementAPI/master/releases.json
2018/01/30 13:18:11 [warning] [application] A “Formulare” release was skipped because it is invalid:
 - Missing required attributes (version, downloadUrl, date, notes)

******************************************************************************************************
2018/01/30 13:20:06 [warning] [application] Craft\PasswordModel->password failed validation: Passwort darf nicht leer sein.

******************************************************************************************************
2018/01/30 13:20:56 [warning] [application] foobar tried to log in unsuccessfully.

******************************************************************************************************
2018/01/30 13:24:57 [warning] [application] foobar tried to log in unsuccessfully.

******************************************************************************************************
```

**Comment by angrybrad** [comment]
Hrm... I'm drawing a blank.  Any chance this is on a public website we could get CP and (s)FTP/SSH access to?  If so, could you send some credentials over to support@craftcms.com so we can look around?

**Comment by steveooo9** [comment]
@angrybrad I will look into this!
