### ISSUE TITLE
Image transforms fails on multilingual site setup

### ISSUE THREAD

**Issue by MiMaMuh** [craftcms/cms#2411]
### Description
Hi, 

we are using `craft 3` and for some reasons sometimes all the `image transforms` of a entry seem to fail. It seems it happens only on our `second language site` ...

- We click on a site to load it
- It takes sometimes minutes to load the site
- Most of the image transforms failed with the following errors:

It logs a lot of the following errors per page:
```
Could not determine asset's URL (427): The file "example-shirt-red-intro.png" does not exist,
craft\errors\VolumeObjectNotFoundException: The file "example-shirt-red-intro.png" does not exist, in /jobs/site/vendor/craftcms/cms/src/services/AssetTransforms.php:880
Stack trace:
#0 /jobs/site/vendor/craftcms/cms/src/elements/Asset.php(810): craft\services\AssetTransforms->getLocalImageSource(Object(craft\elements\Asset))
#1 /jobs/site/vendor/craftcms/cms/src/services/AssetTransforms.php(1326): craft\elements\Asset->getTransformSource()
#2 /jobs/site/vendor/craftcms/cms/src/services/AssetTransforms.php(619): craft\services\AssetTransforms->_createTransformForAsset(Object(craft\elements\Asset), Object(craft\models\AssetTransformIndex))
#3 /jobs/site/vendor/craftcms/cms/src/services/AssetTransforms.php(522): craft\services\AssetTransforms->_generateTransform(Object(craft\models\AssetTransformIndex))
#4 /jobs/site/vendor/craftcms/cms/src/services/Assets.php(594): craft\services\AssetTransforms->ensureTransformUrlByIndexModel(Object(craft\models\AssetTransformIndex))
#5 /jobs/site/vendor/craftcms/cms/src/elements/Asset.php(706): craft\services\Assets->getAssetUrl(Object(craft\elements\Asset), Array)
#6 /jobs/site/vendor/twig/twig/lib/Twig/Extension/Core.php(1595): craft\elements\Asset->getUrl(Array)
#7 /jobs/site/vendor/craftcms/cms/src/helpers/Template.php(76): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\elements\Asset), 'getUrl', Array, 'method', false, false)
#8 /jobs/site/storage/runtime/compiled_templates/40/409fae6fe082bd0e9b148cae21e26c403e48aba37ca8a13ec3cd13161a8a08eb.php(431): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\elements\Asset), 'getUrl', Array, 'method')
#9 /jobs/site/storage/runtime/compiled_templates/01/01977b818780c156755b222ab8c27d4bd7bb099cf2a97066c2830eb99f91c87a.php(69): __TwigTemplate_8f74008ea36d4024f69dbc3ac0d293050e2759d93f5533796a2969f5fb6fc719->macro_croppedImage(Object(craft\elements\Asset), 560, false)
#10 /jobs/site/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_b1d894c1054e7121e5bc82232ab14ceac50a6700bb7284b4f32e3c59e3973e45->doDisplay(Array, Array)
#11 /jobs/site/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#12 /jobs/site/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#13 /jobs/site/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#14 /jobs/site/storage/runtime/compiled_templates/ec/ecdfdca9d3b3683be7bd9624b0ed8384c8d387b348579d84b8736853a8868e16.php(71): craft\web\twig\Template->display(Array)
#15 /jobs/site/vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_3565adb5d58e41e8615de34f0579c2a545c1019664ddf97ca7c94d12fb1f215b->block_content(Array, Array)
#16 /jobs/site/storage/runtime/compiled_templates/1a/1a053a80cc9ff75f1c95513881ffd9391fc9d0c9c9076e9ce647f23f9886ae75.php(68): Twig_Template->displayBlock('content', Array, Array)
#17 /jobs/site/vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_1e66c1ab23d862c3045a2fe3ab57845a469b82eb55c669ea435ed99e5264e1b0->block_body(Array, Array)
#18 /jobs/site/storage/runtime/compiled_templates/14/14ef5aa395b422680043c719dc55aee036f370457a60fe5a42164c71880d8828.php(46): Twig_Template->displayBlock('body', Array, Array)
#19 /jobs/site/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_b6e087ef9b0450a2d6505aa1ab43fa29e7b4d30b849ca05b11bd325f645a03f3->doDisplay(Array, Array)
#20 /jobs/site/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#21 /jobs/site/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#22 /jobs/site/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#23 /jobs/site/storage/runtime/compiled_templates/1a/1a053a80cc9ff75f1c95513881ffd9391fc9d0c9c9076e9ce647f23f9886ae75.php(28): craft\web\twig\Template->display(Array, Array)
#24 /jobs/site/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_1e66c1ab23d862c3045a2fe3ab57845a469b82eb55c669ea435ed99e5264e1b0->doDisplay(Array, Array)
#25 /jobs/site/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#26 /jobs/site/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#27 /jobs/site/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#28 /jobs/site/storage/runtime/compiled_templates/ec/ecdfdca9d3b3683be7bd9624b0ed8384c8d387b348579d84b8736853a8868e16.php(29): craft\web\twig\Template->display(Array, Array)
#29 /jobs/site/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_3565adb5d58e41e8615de34f0579c2a545c1019664ddf97ca7c94d12fb1f215b->doDisplay(Array, Array)
#30 /jobs/site/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#31 /jobs/site/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#32 /jobs/site/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#33 /jobs/site/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#34 /jobs/site/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#35 /jobs/site/vendor/craftcms/cms/src/web/View.php(308): Twig_Environment->render('stock/stock', Array)
#36 /jobs/site/vendor/craftcms/cms/src/web/View.php(356): craft\web\View->renderTemplate('stock/stock', Array)
#37 /jobs/site/vendor/craftcms/cms/src/web/Controller.php(121): craft\web\View->renderPageTemplate('stock/stock', Array)
#38 /jobs/site/vendor/craftcms/cms/src/controllers/TemplatesController.php(79): craft\web\Controller->renderTemplate('stock/stock', Array)
#39 [internal function]: craft\controllers\TemplatesController->actionRender('stock/stock', Array)
#40 /jobs/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#41 /jobs/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#42 /jobs/site/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('render', Array)
#43 /jobs/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#44 /jobs/site/vendor/craftcms/cms/src/web/Application.php(241): yii\base\Module->runAction('templates/rende...', Array)
#45 /jobs/site/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#46 /jobs/site/vendor/craftcms/cms/src/web/Application.php(217): yii\web\Application->handleRequest(Object(craft\web\Request))
#47 /jobs/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#48 /jobs/site/web/en/index.php(43): yii\base\Application->run()
#49 {main}
```

Also sometimes this exception is thrown:

```
Trying to get property 'inProgress' of non-object
------------------------------------------------
1. in /jobs/site/vendor/craftcms/cms/src/services/AssetTransforms.phpat line 499            
for ($safety = 0; $safety < 100; $safety++) {
                // Wait a second!
                sleep(1);
                App::maxPowerCaptain();
 
                /** @noinspection CallableParameterUseCaseInTypeContextInspection */
                $index = $this->getTransformIndexModelById($index->id);
 
                // Is it being worked on right now?
                if ($index->inProgress) { // <------------------------ throws here?
                    // Make sure it hasn't been working for more than 30 seconds. Otherwise give up on the other request.
                    $time = new DateTime();
 
                    if ($time->getTimestamp() - $index->dateUpdated->getTimestamp() < 30) {
                        continue;
                    }
 
                    $this->storeTransformIndexData($index);
                    break;
```

### Update 1:
It seems it happens after I cleared the `Asset Transform Index`-cache with `Utilities -> Clear Caches`
- After I cleared the `Asset Transform Index`-cache, a entry page takes minutes to reload, but only when it is not the `default locale`.
- When I first load the page on the `default locale` and afterwords I load a `non-default locale` it works as it seems the `indexes` are already properly set up, but ..
- when I first load a `non-default locale` site after the `index` is cleard, it has the issue with the transforms. And it has this issue until I call the `default locale` site and afterwards the `non-default locale` site.

### Update 2:
Okay, I reproduced it with a blank craft installation and the same happened as described in `update 1`.
I've made a git repo of the reproduction [here](https://github.com/MiMaMuh/craft-3-transform-bug).

### Steps to reproduce

[Reproduction project on github](https://github.com/MiMaMuh/craft-3-transform-bug)

### Additional info

- Craft version: Craft 3.0.0-RC9
- PHP version: 7.1.12
- Database driver & version: MySQL 5.7.19
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.8.9-9)
- Plugins & versions:

**Comment by brandonkelly** [comment]
The issue is that the File System Path setting in your “Uploads” volume is set to `assets/uploads/`, which is a relative path, assuming that Craft will be running from the `web/` directory.  But when accessing your `/de/` site, the actual working directory is `web/de/` – so Craft is trying to find the assets in `web/de/assets/uploads/`.

To fix this, you can either set the path to an absolute path (possibly with the help of an [alias](https://github.com/craftcms/docs/blob/v3/en/configuration.md#aliases)), or you can tell PHP to change its working directory to `web/` from `web/de/index.php`:

```php
chdir(dirname(__DIR__));
```

**Comment by brandonkelly** [comment]
@mateostabio Aliases are the Craft 3 replacement for the old `environmentVariables` config setting. So you can create a `@baseUrl` alias, and reference it from your volume’s URL setting.
