### ISSUE TITLE
SVG upload to general settings produces image TypeError

### ISSUE THREAD

**Issue by Rainbowlemon** [craftcms/cms#2435]
### Description

When trying to add an SVG logo to the general settings page, after saving and returning to the page, an error is thrown.

If I remove the `storage/rebrand/` folder, it works again.

### Steps to reproduce

1. Using Craft 3-RC10.1, on Windows 10, upload an SVG as a logo in the general settings page
2. Save and return to the general settings page
3. Error is produced and you will be unable to reach the general settings page

### Additional info

- Craft version: Craft Pro 3.0.0-RC10.1
- PHP version: 7.1.9
- Database driver & version: MySQL 5.7.19
- Plugins & versions:
  - Element API: 2.5.2
  - Preview button: 1.0.0
  - Minify: 1.2.7
  - Typed link Field: 1.0.3

The following error is output:

```
TypeError: Return value of craft\web\twig\variables\Image::getWidth() must be of the type integer, null returned in C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\variables\Image.php:76
Stack trace:
#0 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Extension\Core.php(1595): craft\web\twig\variables\Image->getWidth()
#1 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\helpers\Template.php(76): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\web\twig\variables\Image), 'width', Array, 'any', false, false)
#2 C:\Users\Aidan\src\omnibuild-pdf\storage\runtime\compiled_templates\32\3246b3d1f0b9c7aa7e57768b684a437e03ad7c0c98af7968bccac66c8b53357d.php(41): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\web\twig\variables\Image), 'width', Array)
#3 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(389): __TwigTemplate_15a54dc65dda087e7573e0caf24a684a6fb424c05e84247c61f0ee23d1b628cc->doDisplay(Array, Array)
#4 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#5 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#6 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(32): Twig_Template->display(Array, Array)
#7 C:\Users\Aidan\src\omnibuild-pdf\storage\runtime\compiled_templates\31\31da876df7c360d1243b99070bf597c4e8f0a82bbb67681b621e55af87619069.php(29): craft\web\twig\Template->display(Array, Array)
#8 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(389): __TwigTemplate_8112d0a89eddd79d3c7260171a1c98fdeff9cd568353c767f20aca273968b9c7->doDisplay(Array, Array)
#9 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#10 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#11 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(32): Twig_Template->display(Array, Array)
#12 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(374): craft\web\twig\Template->display(Array)
#13 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Extension\Core.php(1304): Twig_Template->render(Array)
#14 C:\Users\Aidan\src\omnibuild-pdf\storage\runtime\compiled_templates\f4\f464e5675f6473cb9ea97a8e902871f78d766130f25d3b5fa8e5503d522bcb7b.php(96): twig_include(Object(craft\web\twig\Environment), Array, 'settings/genera...')
#15 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(188): __TwigTemplate_37e621bdc0d591686b283e8661ce5899dcaa90cc9d64a96308113f10ea83f4c1->block_content(Array, Array)
#16 C:\Users\Aidan\src\omnibuild-pdf\storage\runtime\compiled_templates\f6\f6277aa4be77891e02a81b6cb7697344a8826d51ebb02fd83f292462f2c8f9a1.php(636): Twig_Template->displayBlock('content', Array, Array)
#17 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(188): __TwigTemplate_8c3042ab112304e8aa3356c90893456e1debfa484104abd5fbf1dd614a16dc68->block_main(Array, Array)
#18 C:\Users\Aidan\src\omnibuild-pdf\storage\runtime\compiled_templates\f6\f6277aa4be77891e02a81b6cb7697344a8826d51ebb02fd83f292462f2c8f9a1.php(533): Twig_Template->displayBlock('main', Array, Array)
#19 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(188): __TwigTemplate_8c3042ab112304e8aa3356c90893456e1debfa484104abd5fbf1dd614a16dc68->block_body(Array, Array)
#20 C:\Users\Aidan\src\omnibuild-pdf\storage\runtime\compiled_templates\ec\ec0ef6c52a3f05276a554538bbf2f9a0efc16ffd6d362f9e66a75cea68f77a93.php(53): Twig_Template->displayBlock('body', Array, Array)
#21 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(389): __TwigTemplate_4b0d5cf357edba013b63f77a6164ac6a5f4445ab921980b57b0752636ac0ed31->doDisplay(Array, Array)
#22 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#23 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#24 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(32): Twig_Template->display(Array, Array)
#25 C:\Users\Aidan\src\omnibuild-pdf\storage\runtime\compiled_templates\9c\9c4f85c947b763e3872ec2ba0e928e31cf320523e09f110bd57fc1c69a8f0567.php(36): craft\web\twig\Template->display(Array, Array)
#26 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(389): __TwigTemplate_04f83e32254d1481877ccdb11e04822d62abbd21ebcca9731a3d3dc4169e86ea->doDisplay(Array, Array)
#27 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#28 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#29 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(32): Twig_Template->display(Array, Array)
#30 C:\Users\Aidan\src\omnibuild-pdf\storage\runtime\compiled_templates\f6\f6277aa4be77891e02a81b6cb7697344a8826d51ebb02fd83f292462f2c8f9a1.php(90): craft\web\twig\Template->display(Array, Array)
#31 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(389): __TwigTemplate_8c3042ab112304e8aa3356c90893456e1debfa484104abd5fbf1dd614a16dc68->doDisplay(Array, Array)
#32 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#33 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#34 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(32): Twig_Template->display(Array, Array)
#35 C:\Users\Aidan\src\omnibuild-pdf\storage\runtime\compiled_templates\f4\f464e5675f6473cb9ea97a8e902871f78d766130f25d3b5fa8e5503d522bcb7b.php(35): craft\web\twig\Template->display(Array, Array)
#36 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(389): __TwigTemplate_37e621bdc0d591686b283e8661ce5899dcaa90cc9d64a96308113f10ea83f4c1->doDisplay(Array, Array)
#37 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#38 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#39 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\twig\Template.php(32): Twig_Template->display(Array, Array)
#40 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Template.php(374): craft\web\twig\Template->display(Array)
#41 C:\Users\Aidan\src\omnibuild-pdf\vendor\twig\twig\lib\Twig\Environment.php(289): Twig_Template->render(Array)
#42 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\View.php(308): Twig_Environment->render('settings/genera...', Array)
#43 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\View.php(356): craft\web\View->renderTemplate('settings/genera...', Array)
#44 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\Controller.php(120): craft\web\View->renderPageTemplate('settings/genera...', Array)
#45 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\controllers\SystemSettingsController.php(105): craft\web\Controller->renderTemplate('settings/genera...', Array)
#46 [internal function]: craft\controllers\SystemSettingsController->actionGeneralSettings(Object(craft\models\Info))
#47 C:\Users\Aidan\src\omnibuild-pdf\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#48 C:\Users\Aidan\src\omnibuild-pdf\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#49 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\Controller.php(80): yii\base\Controller->runAction('general-setting...', Array)
#50 C:\Users\Aidan\src\omnibuild-pdf\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('general-setting...', Array)
#51 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\Application.php(240): yii\base\Module->runAction('system-settings...', Array)
#52 C:\Users\Aidan\src\omnibuild-pdf\vendor\yiisoft\yii2\web\Application.php(103): craft\web\Application->runAction('system-settings...', Array)
#53 C:\Users\Aidan\src\omnibuild-pdf\vendor\craftcms\cms\src\web\Application.php(216): yii\web\Application->handleRequest(Object(craft\web\Request))
#54 C:\Users\Aidan\src\omnibuild-pdf\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#55 C:\Users\Aidan\src\omnibuild-pdf\web\index.php(21): yii\base\Application->run()
#56 {main}
```

**Comment by brandonkelly** [comment]
Can you please upload the SVG file, or paste its contents?

**Comment by Rainbowlemon** [comment]
Sure:

```html
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="-149 -100 500 500" enable-background="new -149 -100 500 500" xml:space="preserve">
<g transform="translate(0.000000,500.000000) scale(0.100000,-0.100000)">
	<path fill="#ED3B43" d="M988,5935c-2-1-57-5-123-9c-66-3-136-8-155-11c-192-29-256-43-405-87c-255-76-519-208-745-373
		c-30-22-57-42-60-45s-34-30-70-60c-311-261-564-624-708-1015c-74-203-123-430-139-645c-8-117-8-253,0-385c7-103,11-130,28-225
		c6-30,13-68,15-85c11-65,75-277,113-376c67-171,210-436,298-549c161-208,304-357,449-470c11-8,40-31,64-50c25-20,63-47,85-61
		s66-43,98-64c251-161,642-300,957-340c189-24,491-24,630-1c14,3,43,7,65,10c224,31,485,115,715,230c590,295,1044,832,1233,1456
		c42,140,54,187,72,293c3,15,7,39,10,55c3,15,7,50,10,77c3,28,8,68,10,90c7,55,7,361,0,408c-3,20-7,61-10,90c-5,46-11,86-30,190
		c-3,15-19,79-35,142c-187,724-737,1348-1437,1629c-101,40-221,82-263,91c-8,1-35,8-60,15c-51,14-56,15-165,35
		c-119,21-149,24-285,30c-69,4-133,8-142,9C999,5936,990,5937,988,5935z M1170,4905c421-53,793-307,1015-690c16-27,30-52,30-55
		c1-3,11-27,24-55c30-67,79-213,87-260c3-20,8-47,10-59c19-95,24-286,11-398c-41-348-219-669-495-896c-111-91-240-166-380-219
		c-111-42-204-64-332-80c-65-7-266-6-318,2c-21,3-53,8-72,11c-105,16-253,66-375,127c-55,27-184,107-212,132C43,2570,5,2606-44,2662
		c-207,238-328,558-330,868c0,72,10,211,19,250c3,14,8,41,11,60c12,70,67,227,111,314c166,330,440,571,784,690c91,31,201,55,284,63
		c33,3,61,6,63,8C904,4920,1113,4913,1170,4905z"/>
</g>
</svg>
```html

**Comment by brandonkelly** [comment]
Thanks! Was able to reproduce with that, and fixed the error for the next release.

**Comment by Rainbowlemon** [comment]
Awesome, thanks!
