### ISSUE TITLE
relation "public.queue_id_seq_id_seq" does not exist

### ISSUE THREAD

**Issue by alexmarchant** [craftcms/cms#2488]
### Description

Seeing the following stack trace my error logs. I'm not sure what it means. I believe it happens when i try to run database backups, they always fail. I do not get this error on my dev machine, only staging and production for whatever reason.

```
[19-Aug-2017 13:26:56 America/Los_Angeles] An Error occurred while handling another error:
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "public.queue_id_seq_id_seq" does not exist in /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/db/Schema.php:390
Stack trace:
#0 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/db/Schema.php(390): PDO->lastInsertId('"public"."queue...')
#1 /srv/www/photoism/releases/20170818233849/site/vendor/craftcms/cms/src/db/pgsql/Schema.php(122): yii\db\Schema->getLastInsertID('public.queue_id...')
#2 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/db/Connection.php(812): craft\db\pgsql\Schema->getLastInsertID('public.queue_id...')
#3 /srv/www/photoism/releases/20170818233849/site/vendor/craftcms/cms/src/queue/Queue.php(422): yii\db\Connection->getLastInsertID('queue_id_seq')
#4 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2-queue/src/Queue.php(146): craft\queue\Queue->pushMessage('O:42:"craft\\que...', 300, 0, NULL)
#5 /srv/www/photoism/releases/20170818233849/site/vendor/craftcms/cms/src/queue/Queue.php(148): yii\queue\Queue->push(Object(craft\queue\jobs\DeleteStaleTemplateCaches))
#6 /srv/www/photoism/releases/20170818233849/site/vendor/craftcms/cms/src/services/TemplateCaches.php(522): craft\queue\Queue->push(Object(craft\queue\jobs\DeleteStaleTemplateCaches))
#7 [internal function]: craft\services\TemplateCaches->handleResponse(Object(yii\base\Event))
#8 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/base/Component.php(545): call_user_func(Array, Object(yii\base\Event))
#9 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/web/Response.php(335): yii\base\Component->trigger('afterPrepare')
#10 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/web/ErrorHandler.php(124): yii\web\Response->send()
#11 /srv/www/photoism/releases/20170818233849/site/vendor/craftcms/cms/src/web/ErrorHandler.php(144): yii\web\ErrorHandler->renderException(Object(PDOException))
#12 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/base/ErrorHandler.php(111): craft\web\ErrorHandler->renderException(Object(PDOException))
#13 /srv/www/photoism/releases/20170818233849/site/vendor/craftcms/cms/src/web/ErrorHandler.php(72): yii\base\ErrorHandler->handleException(Object(PDOException))
#14 [internal function]: craft\web\ErrorHandler->handleException(Object(PDOException))
#15 {main}
Previous exception:
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "public.queue_id_seq_id_seq" does not exist in /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/db/Schema.php:390
Stack trace:
#0 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/db/Schema.php(390): PDO->lastInsertId('"public"."queue...')
#1 /srv/www/photoism/releases/20170818233849/site/vendor/craftcms/cms/src/db/pgsql/Schema.php(122): yii\db\Schema->getLastInsertID('public.queue_id...')
#2 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/db/Connection.php(812): craft\db\pgsql\Schema->getLastInsertID('public.queue_id...')
#3 /srv/www/photoism/releases/20170818233849/site/vendor/craftcms/cms/src/queue/Queue.php(422): yii\db\Connection->getLastInsertID('queue_id_seq')
#4 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2-queue/src/Queue.php(146): craft\queue\Queue->pushMessage('O:42:"craft\\que...', 300, 0, NULL)
#5 /srv/www/photoism/releases/20170818233849/site/vendor/craftcms/cms/src/queue/Queue.php(148): yii\queue\Queue->push(Object(craft\queue\jobs\DeleteStaleTemplateCaches))
#6 /srv/www/photoism/releases/20170818233849/site/vendor/craftcms/cms/src/services/TemplateCaches.php(522): craft\queue\Queue->push(Object(craft\queue\jobs\DeleteStaleTemplateCaches))
#7 [internal function]: craft\services\TemplateCaches->handleResponse(Object(yii\base\Event))
#8 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/base/Component.php(545): call_user_func(Array, Object(yii\base\Event))
#9 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/web/Response.php(335): yii\base\Component->trigger('afterPrepare')
#10 /srv/www/photoism/releases/20170818233849/site/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Response->send()
#11 /srv/www/photoism/releases/20170818233849/site/web/index.php(22): yii\base\Application->run()
#12 {main}
```

### Steps to reproduce

1. Unclear ???

### Additional info

- Craft version: Craft Pro 3.0.0-RC12
- PHP version: 7.2.1
- Database driver & version: PostgreSQL 10.1
- Plugins & versions:

Element API	2.5.2
Redactor	1.0.1
Amazon S3	1.0.8

**Comment by brandonkelly** [comment]
The lines numbers in your stack trace don't match the actual lines in RC12. For example, this from your stack trace:

```
#3 /srv/www/photoism/releases/20170818233849/site/vendor/craftcms/cms/src/queue/Queue.php(422): yii\db\Connection->getLastInsertID('queue_id_seq')
```

points to this line:

https://github.com/craftcms/cms/blob/71c6723668f37639dc1938d3fc6e13d627ed8a76/src/queue/Queue.php?utf8=%E2%9C%93#L422

which is obviously not a call to `getLastInsertID()`. That call is actually on line 411 these days:

https://github.com/craftcms/cms/blob/71c6723668f37639dc1938d3fc6e13d627ed8a76/src/queue/Queue.php?utf8=%E2%9C%93#L411

So as a first step, seems like you need to fix your deployment, or something. You’re not actually running RC12 even if Craft thinks it is.

**Comment by alexmarchant** [comment]
You're right, my logs were from before the update. This has been showing up in logs since the beginning, so i assume its still happening post update. Let me get new logs for you.

**Comment by alexmarchant** [comment]
I haven't seen this error in over a month and it was not what was causing the database backup issues (this was: https://github.com/craftcms/cms/issues/2567) so I'm going to close this. If it looks important to you, happy to help dig further.

**Comment by brandonkelly** [comment]
Alright, thanks for the update!
