### ISSUE TITLE
Multisite Config. I'm confused

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#2532]
I set up a multi site and I need this URL Pattern:

domain.com/country/language

```
http://foo.com
http://foo.com/at
http://foo.com/de
http://foo.com/de/en
```

### My current Settings:

**Backend Sites:**
![image](https://user-images.githubusercontent.com/764292/37024398-082670b4-2129-11e8-9433-98377ed7aea8.png)

**general.php**
```php
'siteUrl' => [
    'at_en' => getenv('CRAFTENV_SITE_URL'),
    'at' => getenv('CRAFTENV_SITE_URL') . 'at/',
    'de' => getenv('CRAFTENV_SITE_URL') . 'de/',
    'de_en' => getenv('CRAFTENV_SITE_URL') . 'de/en/'
],
```

**My Web Folder**
![image](https://user-images.githubusercontent.com/764292/37024501-552e587c-2129-11e8-896f-bfcf40aa5493.png)

**My LaravelValetDriver if it's important**
```php
<?php
class LocalValetDriver extends ValetDriver
{
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        return is_dir($sitePath . '/vendor/craftcms/cms') && file_exists($sitePath . '/web/index.php');
    }
    /**
     * Determine if the incoming request is for a static file.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string|false
     */
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        $staticFilePath = $sitePath . '/web/' . $uri;

        if ($this->isActualFile($staticFilePath)) {
            return $staticFilePath;
        }
        return false;
    }


    /**
     * Determine the name of the directory where the front controller lives.
     *
     * @param  string  $sitePath
     * @return string
     */
    public function frontControllerDirectory($sitePath)
    {
        $dirs = ['web', 'public'];
        foreach ($dirs as $dir) {
            if (is_dir($sitePath.'/'.$dir)) {
                return $dir;
            }
        }
        // Give up, and just return the default
        return is_file($sitePath.'/craft') ? 'web' : 'public';
    }

    /**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        $frontControllerDirectory = $this->frontControllerDirectory($sitePath);
        // Default index path
        $indexPath = $sitePath.'/'.$frontControllerDirectory.'/index.php';
        $scriptName = '/index.php';
        // Check if the first URL segment matches any of the defined locales
        $locales = [
            'at',
            'de',
            'de_en',
        ];
        $parts = explode('/', $uri);
        if (count($parts) > 1 && in_array($parts[1], $locales)) {
            $indexPath = $sitePath.'/'.$frontControllerDirectory.'/'.$parts[1].'/index.php';
            $scriptName = '/'.$parts[1].'/index.php';
        }
        $_SERVER['SCRIPT_FILENAME'] = $indexPath;
        $_SERVER['SERVER_NAME'] = $_SERVER['HTTP_HOST'];
        $_SERVER['SCRIPT_NAME'] = $scriptName;
        $_SERVER['PHP_SELF'] = $scriptName;
        $_SERVER['DOCUMENT_ROOT'] = $sitePath.'/'.$frontControllerDirectory;

        return $indexPath;
    }
}
```

**My index.php in web/**
```php
<?php
/**
 * Craft 3 Multi-Environment
 * Efficient and flexible multi-environment config for Craft 3 CMS
 *
 * @author    nystudio107
 * @copyright Copyright (c) 2017 nystudio107
 * @link      https://nystudio107.com/
 * @package   craft3-multi-environment
 * @since     1.0.5
 * @license   MIT
 */

/**
 * Craft web bootstrap file
 */

define('CRAFT_BASE_PATH', dirname(__DIR__));
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// Load dotenv?
if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    (new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();
}

// Load the local craft3-multi-environment
if (file_exists(CRAFT_BASE_PATH . DIRECTORY_SEPARATOR . '.env.php')) {
    require_once CRAFT_BASE_PATH . DIRECTORY_SEPARATOR . '.env.php';
}

// Default environment
if (!defined('CRAFT_ENVIRONMENT')) {
    define('CRAFT_ENVIRONMENT', getenv('CRAFTENV_CRAFT_ENVIRONMENT'));
}

// Load and run Craft
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();
```

**My index.php in web/subfolder**
```php
<?php
/**
 * Craft 3 Multi-Environment
 * Efficient and flexible multi-environment config for Craft 3 CMS
 *
 * @author    nystudio107
 * @copyright Copyright (c) 2017 nystudio107
 * @link      https://nystudio107.com/
 * @package   craft3-multi-environment
 * @since     1.0.5
 * @license   MIT
 */

/**
 * Craft web bootstrap file
 */

define('CRAFT_BASE_PATH', dirname(__DIR__, 2));
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// Load dotenv?
if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    (new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();
}

// Load the local craft3-multi-environment
if (file_exists(CRAFT_BASE_PATH . DIRECTORY_SEPARATOR . '.env.php')) {
    require_once CRAFT_BASE_PATH . DIRECTORY_SEPARATOR . '.env.php';
}

// Default environment
if (!defined('CRAFT_ENVIRONMENT')) {
    define('CRAFT_ENVIRONMENT', getenv('CRAFTENV_CRAFT_ENVIRONMENT'));
}

// Load and run Craft
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();
```

That looks like it works but I don't define `CRAFT_SITE` like this. 
```php
define('CRAFT_SITE', 'de_en');
```

When I add this to all index.php Files my site is broken on the **foo.com/de/en**

***Stack Trace***
```
 in /Users/davidhellmann/___DEV/___Fredmansky/FOO/___dist/vendor/craftcms/cms/src/controllers/TemplatesController.php

yii\web\NotFoundHttpException: Template not found: en in /Users/davidhellmann/___DEV/___Fredmansky/FOO/___dist/vendor/craftcms/cms/src/controllers/TemplatesController.php:69
Stack trace:
#0 [internal function]: craft\controllers\TemplatesController->actionRender('en', Array)
#1 /Users/davidhellmann/___DEV/___Fredmansky/FOO/___dist/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /Users/davidhellmann/___DEV/___Fredmansky/FOO/___dist/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /Users/davidhellmann/___DEV/___Fredmansky/FOO/___dist/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('render', Array)
#4 /Users/davidhellmann/___DEV/___Fredmansky/FOO/___dist/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#5 /Users/davidhellmann/___DEV/___Fredmansky/FOO/___dist/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('templates/rende...', Array)
#6 /Users/davidhellmann/___DEV/___Fredmansky/FOO/___dist/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#7 /Users/davidhellmann/___DEV/___Fredmansky/FOO/___dist/vendor/craftcms/cms/src/web/Application.php(226): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /Users/davidhellmann/___DEV/___Fredmansky/FOO/___dist/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /Users/davidhellmann/___DEV/___Fredmansky/FOO/___dist/web/de/index.php(42): yii\base\Application->run()
#10 /Users/davidhellmann/.composer/vendor/laravel/valet/server.php(133): require('/Users/davidhel...')
#11 {main}
```

Is that just a Laravel Valet Problem or is my Setup wrong on some point. :/

**Comment by hiasl** [comment]
I guess this
`define('CRAFT_BASE_PATH', dirname(__DIR__, 2));`

should be
`define('CRAFT_BASE_PATH', dirname(__DIR__, 3));`

on the /de/en index.php file

Grüße aus Wien

**Comment by davidhellmann** [comment]
Hm that's not the problem I think. Talked to another one and he said I can remove all the config stuff cause craft do the magic. No subfolders needed. But Valet can't handle it with my URL pattern.

**Comment by davidhellmann** [comment]
```
<?php
class LocalValetDriver extends ValetDriver
{
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        return is_dir($sitePath . '/vendor/craftcms/cms') && file_exists($sitePath . '/web/index.php');
    }
    /**
     * Determine if the incoming request is for a static file.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string|false
     */
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        $staticFilePath = $sitePath . '/web/' . $uri;

        if ($this->isActualFile($staticFilePath)) {
            return $staticFilePath;
        }
        return false;
    }


    /**
     * Determine the name of the directory where the front controller lives.
     *
     * @param  string  $sitePath
     * @return string
     */
    public function frontControllerDirectory($sitePath)
    {
        $dirs = ['web', 'public'];
        foreach ($dirs as $dir) {
            if (is_dir($sitePath.'/'.$dir)) {
                return $dir;
            }
        }
        // Give up, and just return the default
        return is_file($sitePath.'/craft') ? 'web' : 'public';
    }

    /**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        $frontControllerDirectory = $this->frontControllerDirectory($sitePath);
        // Default index path
        $indexPath = $sitePath.'/'.$frontControllerDirectory.'/index.php';
        $scriptName = '/index.php';

        $_SERVER['SCRIPT_FILENAME'] = $indexPath;
        $_SERVER['SERVER_NAME'] = $_SERVER['HTTP_HOST'];
        $_SERVER['SCRIPT_NAME'] = $scriptName;
        $_SERVER['PHP_SELF'] = $scriptName;
        $_SERVER['DOCUMENT_ROOT'] = $sitePath.'/'.$frontControllerDirectory;

        return $indexPath;
    }
}
```

Fixed my Valet Driver and this works

**Comment by brandonkelly** [comment]
@davidhellmann 

> That looks like it works but I don't define `CRAFT_SITE` like this.
>
> ```php
> define('CRAFT_SITE', 'de_en');
> ```

You must delete that whole file, not just the `CRAFT_SITE` constant.
