### ISSUE TITLE
Uploading an SVG as the CP icon breaks the general settings section

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2543]
### Description

When uploading an SVG as the CP icon from the general settings section, if the SVG doesn't sit well with Craft no error is thrown during the upload process, the progress bar gets to 100% and stalls. Visiting another page in the CP shows that the image upload has succeeded, but if you go back to the general settings section the following error is thrown: 

```
Image Exception – craft\errors\ImageException
The file “/srv/users/serverpilot/apps/countries/craft/storage/rebrand/icon/globe-icon.svg” does not appear to be an image.
```

<img width="1272" alt="screen shot 2018-03-07 at 00 03 45" src="https://user-images.githubusercontent.com/24975058/37065960-17339510-219b-11e8-8ca5-5b44bc05ccef.png">

### Steps to reproduce

1. Upload an SVG that shouldn't validate as the CP icon 
2. Upload shouldn't finish (no error thrown)
3. Refresh the page to see the error
4. Visit anywhere else in the CP to see the uploaded image displayed as expected

### Additional info

- Craft version: 3.0.0-RC14
- PHP version: 7.2
- Database driver & version: MySQL

**Comment by angrybrad** [comment]
Any chance you could share the offending SVG and let us know if you're using GD or Imagick?

**Comment by lukeyouell** [comment]
Sure, I can't upload the file so I've pasted the code below.

It's a standard Serverpilot setup, who use GD as far as I know.

```html
<svg viewBox="0 0 500 500" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <circle fill="#54BCE5" cx="250" cy="250" r="250"></circle>
        <path d="M116.145418,38.8155348 C117.286937,40.1448492 118.429871,41.5487855 119.574219,43.0273437 C139.373976,68.6096884 147.469944,86.7742984 153.339844,115.710937 C159.209743,144.647577 159.695313,171.214844 148.398438,185.121094 C137.101563,199.027344 88.4223748,201.038693 80.5390625,223.292969 C75.2835209,238.129152 84.4514897,263.379152 108.042969,299.042969 C170.175573,295.277634 205.646276,305.574509 214.455078,329.933594 C227.668281,366.47222 230.270291,431.712332 224.140625,457.730469 C218.010959,483.748605 207.229332,494.480851 191.980469,480.414062 C176.731606,466.347274 172.160156,426.447266 156.335938,409.828125 C140.511719,393.208984 121.181476,405.512153 99.8144531,391.167969 C78.4474298,376.823784 71,356.603025 71,336.144531 C71,322.505535 78.9407552,312.187827 94.8222656,305.191406 C71.0848247,291.333505 50.2169861,266.103036 32.21875,229.5 C22.9828601,210.716959 16.3681314,191.584573 12.3745638,172.102842 C30.5730378,116.554074 67.7067164,69.5815775 116.145418,38.8155348 Z" fill="#8DDB67"></path>
        <g transform="translate(301.000000, 6.000000)" fill="#8DDB67">
            <path d="M161.960766,112.983862 C159.42902,113.808873 156.735717,114.452273 153.880859,114.914063 C126.40381,119.358628 109.71844,99.760182 82.6445312,103.015625 C55.5706227,106.271068 34.3038036,137.267434 18.8652344,129.371094 C3.42666512,121.474754 22.7633432,99.5215799 18.8652344,70.3945313 C14.9671256,41.2674826 -2.83191436,33.400678 0.455078125,13.4433594 C1.27383416,8.4721965 3.27040878,4.20152831 6.444802,0.631354809 C72.0020619,16.0462427 127.608968,57.2653294 161.960766,112.983862 Z"></path>
        </g>
        <path d="M425.711001,427.83604 C401.756181,430.117439 388.463842,425.687717 385.833984,414.546875 C380.915932,393.712577 410.436085,332.218211 389.210938,294.681641 C367.98579,257.14507 321.85416,285.131235 301.242187,261.134766 C280.630215,237.138296 271.714912,200.077935 299.074219,180.044922 C322.606437,162.814177 408.229573,147.965831 487.212751,170.854361 C495.507654,195.727139 500,222.338948 500,250 C500,319.576046 471.577959,382.513768 425.711004,427.83604 Z" fill="#8DDB67"></path>
        <path d="M83.5046233,63.5046233 C44.0090491,107.713786 20,166.053086 20,230 C20,368.071187 131.928813,480 270,480 C333.946914,480 392.286214,455.990951 436.495377,416.495377 C390.713953,467.740571 324.124273,500 250,500 C111.928813,500 0,388.071187 0,250 C0,175.875727 32.2594289,109.286047 83.5046233,63.5046233 Z" fill-opacity="0.101477582" fill="#000000"></path>
    </g>
</svg>
```

**Comment by andris-sevcenko** [comment]
Is it possible to get a full stack trace for that exception? Unable to reproduce locally with the provided SVG.

**Comment by lukeyouell** [comment]
```
[error][craft\errors\ImageException] craft\errors\ImageException: The file “/srv/users/serverpilot/apps/xxx/craft/storage/rebrand/icon/globe-icon.svg” does not appear to be an image. in /srv/users/serverpilot/apps/xxx/craft/vendor/craftcms/cms/src/image/Raster.php:175
Stack trace:
#0 /srv/users/serverpilot/apps/xxx/craft/vendor/craftcms/cms/src/services/Images.php(213): craft\image\Raster->loadImage('/srv/users/serv...')
#1 /srv/users/serverpilot/apps/xxx/craft/vendor/craftcms/cms/src/helpers/Image.php(188): craft\services\Images->loadImage('/srv/users/serv...')
#2 /srv/users/serverpilot/apps/xxx/craft/vendor/craftcms/cms/src/web/twig/variables/Image.php(64): craft\helpers\Image::imageSize('/srv/users/serv...')
#3 /srv/users/serverpilot/apps/xxx/craft/vendor/craftcms/cms/src/web/twig/variables/Image.php(74): craft\web\twig\variables\Image->getSize()
#4 /srv/users/serverpilot/apps/xxx/craft/vendor/twig/twig/lib/Twig/Extension/Core.php(1601): craft\web\twig\variables\Image->getWidth()
#5 /srv/users/serverpilot/apps/xxx/craft/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\web\twig\variables\Image), 'width', Array, 'any', false, false)
```

**Comment by andris-sevcenko** [comment]
So for some reason https://github.com/craftcms/cms/blob/develop/src/helpers/FileHelper.php#L281 is failing to recognize that SVG file as such. Can you try adding the xml type declaration? That has helped [before](https://craftcms.stackexchange.com/questions/17752/incorrect-content-mime-type-on-s3-svg-upload)

**Comment by lukeyouell** [comment]
Yep that fixes it.

I reported the bug as it breaks a particular section of the CP, making it inaccessible until the SVG is updated manually.

**Comment by andris-sevcenko** [comment]
Got it!
