### ISSUE TITLE
PGPASSWORD needs quotes around it

### ISSUE THREAD

**Issue by alexmarchant** [craftcms/cms#2567]
### Description

I'm getting an error when trying to run database backups:

```
2018-03-13 14:43:59 [71.167.189.10][1][-][error][yii\base\Exception] yii\base\Exception: Could not create backup: The shell command "PGPASSWORD=******* pg_dump --dbname=photoism_staging --host=localhost --port=5432 --username=craft --if-exists --clean --file="/srv/www/photoism/releases/20180312220800/site/storage/backups/photoism_180313_214359_2k54a8huxa_v3.0.0-rc14.sql" --schema=public --exclude-table-data 'public.assetindexdata' --exclude-table-data 'public.assettransformindex' --exclude-table-data 'public.cache' --exclude-table-data 'public.sessions' --exclude-table-data 'public.templatecaches' --exclude-table-data 'public.templatecachecriteria' --exclude-table-data 'public.templatecacheelements'" failed with exit code 1: pg_dump: [archiver (db)] connection to database "photoism_staging" failed: FATAL:  password authentication failed for user "craft"
FATAL:  password authentication failed for user "craft" in /srv/www/photoism/releases/20180312220800/site/vendor/craftcms/cms/src/controllers/UtilitiesController.php:380
Stack trace:
#0 [internal function]: craft\controllers\UtilitiesController->actionDbBackupPerformAction()
#1 /srv/www/photoism/releases/20180312220800/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /srv/www/photoism/releases/20180312220800/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /srv/www/photoism/releases/20180312220800/site/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('db-backup-perfo...', Array)
#4 /srv/www/photoism/releases/20180312220800/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('db-backup-perfo...', Array)
#5 /srv/www/photoism/releases/20180312220800/site/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('utilities/db-ba...', Array)
#6 /srv/www/photoism/releases/20180312220800/site/vendor/craftcms/cms/src/web/Application.php(445): craft\web\Application->runAction('utilities/db-ba...', Array)
#7 /srv/www/photoism/releases/20180312220800/site/vendor/craftcms/cms/src/web/Application.php(221): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /srv/www/photoism/releases/20180312220800/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /srv/www/photoism/releases/20180312220800/site/web/photoism/index.php(22): yii\base\Application->run()
#10 {main}
```

### Steps to reproduce

1. Have a password with some special characters that need to be put inside quotes
2. Try to create a db backup from the CP

### Additional info

- Craft version: Craft Pro 3.0.0-RC14
- PHP version: 7.2.3
- Database driver & version: PostgreSQL 9.5.12
- Plugins & versions:

**Comment by alexmarchant** [comment]
PR incoming...

**Comment by alexmarchant** [comment]
This fixes database backups on my production machine: https://github.com/craftcms/cms/pull/2568
