### ISSUE TITLE
User Registration Form: Trying to get property of non-object

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#2666]
### Description
I'm getting the following error, when using the [user registration form example](https://github.com/craftcms/docs/blob/v3/en/templating/examples/user-registration-form.md#user-registration-form)

```
yii\base\ErrorException: Trying to get property of non-object in /Users/tdavis/sites/hamilton/vendor/superbig/craft-audit/src/services/AuditService.php:231
Stack trace:
#0 /Users/tdavis/sites/hamilton/vendor/superbig/craft-audit/src/services/AuditService.php(231): Raven_Breadcrumbs_ErrorHandler->handleError()
#1 /Users/tdavis/sites/hamilton/vendor/superbig/craft-audit/src/services/AuditService.php(105): superbig\audit\services\AuditService->_getStandardModel()
#2 /Users/tdavis/sites/hamilton/vendor/superbig/craft-audit/src/Audit.php(210): superbig\audit\services\AuditService->onSaveElement()
#3 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Event.php(310): superbig\audit\Audit->superbig\audit\{closure}()
#4 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Event.php(310): ::call_user_func:{/Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Event.php:310}()
#5 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger()
#6 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Elements.php(517): yii\base\Component->trigger()
#7 /Users/tdavis/sites/hamilton/vendor/craftcms/commerce/src/services/Carts.php(383): craft\services\Elements->saveElement()
#8 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Component.php(139): craft\commerce\services\Carts->getCart()
#9 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/helpers/Template.php(57): yii\base\Component->__get()
#10 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/04/04e622616ec16d8d3e084d897e14ac5448995127860afeefa5bfdcf521570f73.php(26): craft\helpers\Template::attribute()
#11 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_de9a7a8b22159cb6f52583f2dac25d965e97d9c3e8fdf0c963da878eb3fd3c7c->doDisplay()
#12 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling()
#13 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling()
#14 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display()
#15 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/65/65f6b150cd4e722c6c146756bb3306a98df0a9fa8415f2d603cc6016d8f888a7.php(31): craft\web\twig\Template->display()
#16 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_68818f0ed85e1322011bb5c15b1f537d4811f17400504ab7b3099c28db47cdcc->doDisplay()
#17 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling()
#18 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling()
#19 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display()
#20 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display()
#21 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render()
#22 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/View.php(305): Twig_Environment->render()
#23 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/View.php(352): craft\web\View->renderTemplate()
#24 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(113): craft\web\View->renderPageTemplate()
#25 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/controllers/TemplatesController.php(77): craft\web\Controller->renderTemplate()
#26 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\TemplatesController->actionRender()
#27 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#28 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#29 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction()
#30 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#31 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction()
#32 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#33 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(226): yii\web\Application->handleRequest()
#34 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#35 /Users/tdavis/sites/hamilton/public/index.php(21): yii\base\Application->run()
#36 {main}
```

This only appears to happen the first time you hit that URL. If you reload the same page, the error goes away.

### Steps to reproduce

1. Create a front-end user registration form
1. Open an incognito window
1. Visit the front-end user registration form

### Additional info

- Craft version: Craft Pro 3.0.0-RC17.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38

**Comment by Anubarak** [comment]
The error is in a plugin `superbig\audit\services\AuditService`. Maybe you should contact the developer of that

**Comment by davist11** [comment]
🤦‍♂️  duh, didn't even read the stack trace. Thanks!
