### ISSUE TITLE
Database mySQL backups failing on windows - No temp/my.cnf?

### ISSUE THREAD

**Issue by neokoenig** [craftcms/cms#2675]
### Description

Attempting to backup DB on Win10, mySQL 5.6
mysqldump is in the PATH.

Creates:
```
2018-04-04 13:40:02 [127.0.0.1][1][-][error][yii\base\Exception] yii\base\Exception: Could not create backup: The shell command "mysqldump --defaults-extra-file="D:\oms_craft\storage\runtime\temp\my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --single-transaction --no-data --result-file="D:\oms_craft\storage\backups/oxford-martin-school_180404_124002_ladgju64hl_v3.0.0-rc17.1.sql" oms_craft && mysqldump --defaults-extra-file="D:\oms_craft\storage\runtime\temp\my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --no-create-info --ignore-table=oms_craft.assetindexdata --ignore-table=oms_craft.assettransformindex --ignore-table=oms_craft.cache --ignore-table=oms_craft.sessions --ignore-table=oms_craft.templatecaches --ignore-table=oms_craft.templatecachecriteria --ignore-table=oms_craft.templatecacheelements oms_craft >> "D:\oms_craft\storage\backups/oxford-martin-school_180404_124002_ladgju64hl_v3.0.0-rc17.1.sql"" failed with exit code 1. in D:\oms_craft\vendor\craftcms\cms\src\controllers\UtilitiesController.php:380
Stack trace:
#0 [internal function]: craft\controllers\UtilitiesController->actionDbBackupPerformAction()
#1 D:\oms_craft\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#2 D:\oms_craft\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 D:\oms_craft\vendor\craftcms\cms\src\web\Controller.php(74): yii\base\Controller->runAction('db-backup-perfo...', Array)
#4 D:\oms_craft\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('db-backup-perfo...', Array)
#5 D:\oms_craft\vendor\craftcms\cms\src\web\Application.php(237): yii\base\Module->runAction('utilities/db-ba...', Array)
#6 D:\oms_craft\vendor\craftcms\cms\src\web\Application.php(445): craft\web\Application->runAction('utilities/db-ba...', Array)
#7 D:\oms_craft\vendor\craftcms\cms\src\web\Application.php(221): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 D:\oms_craft\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 D:\oms_craft\web\index.php(21): yii\base\Application->run()
#10 {main}
```

Going into the command (powershell) line and running manually, we get

```
PS C:\Users\Tom> mysqldump -v
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help

PS C:\Users\Tom> mysqldump --defaults-extra-file="D:\oms_craft\storage\runtime\temp\my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines
 --set-charset --triggers --single-transaction --no-data --result-file="D:\oms_craft\storage\backups/oxford-martin-school_180404_124002_ladgju64hl_v3.0.0-rc17.1.sql" oms_craft
 && mysqldump --defaults-extra-file="D:\oms_craft\storage\runtime\temp\my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charse
t --triggers --no-create-info --ignore-table=oms_craft.assetindexdata --ignore-table=oms_craft.assettransformindex --ignore-table=oms_craft.cache --ignore-table=oms_craft.sess
ions --ignore-table=oms_craft.templatecaches --ignore-table=oms_craft.templatecachecriteria --ignore-table=oms_craft.templatecacheelements oms_craft >> "D:\oms_craft\storage\b
ackups/oxford-martin-school_180404_124002_ladgju64hl_v3.0.0-rc17.1.sql"
At line:1 char:335
+ ... hool_180404_124002_ladgju64hl_v3.0.0-rc17.1.sql" oms_craft && mysqldu ...
+                                                                ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
```

Turns out && is not allowed in powershell - fair enough. So trying in the normal CMD and you get

```
C:\Users\Tom>mysqldump --defaults-extra-file="D:\oms_craft\storage\runtime\temp\my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --single-transaction --no-data --result-file="D:\oms_craft\storage\backups/oxford-martin-school_180404_124002_ladgju64hl_v3.0.0-rc17.1.sql" oms_craft && mysqldump --defaults-extra-file="D:\oms_craft\storage\runtime\temp\my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --no-create-info --ignore-table=oms_craft.assetindexdata --ignore-table=oms_craft.assettransformindex --ignore-table=oms_craft.cache --ignore-table=oms_craft.sessions --ignore-table=oms_craft.templatecaches --ignore-table=oms_craft.templatecachecriteria --ignore-table=oms_craft.templatecacheelements oms_craft >> "D:\oms_craft\storage\backups/oxford-martin-school_180404_124002_ladgju64hl_v3.0.0-rc17.1.sql"
Could not open required defaults file: D:\oms_craft\storage\runtime\temp\my.cnf
Fatal error in defaults handling. Program aborted

C:\Users\Tom>
```

And sure enough, no `/temp/my.cnf` exists there.

Any thoughts?

### Steps to reproduce

1. Run backup from the CP on Win 10 , mySQL 5.6

### Additional info

- Craft version:  Craft Pro 3.0.0-RC17.1
- PHP version: 7.2.1
- Database driver & version: MySQL 5.6.26
- Plugins & versions:
 Feed Me   dev-craft-3 
 Feed Me Pro 3.0.0
 Position Fieldtype 1.0.10
 Redactor 1.1.0 
 SEOmatic 3.0.0 beta 20

**Comment by neokoenig** [comment]
Just installed 3.0.2 and this issue seems to be rectified. Closing.
