### ISSUE TITLE
Number::normalizeValue can throw an exception when an ElementInterface is not included

### ISSUE THREAD

**Issue by spleenboy** [craftcms/cms#2913]
The `Field::normalizeValue` method has an optional 2nd parameter: `ElementInterface`, but the `Number` field's [override of `normalizeValue`](https://github.com/craftcms/cms/blob/1fc6afcf4f889199ffbeeaed58554b254869c10c/src/fields/Number.php#L152) calls the `isValueEmpty` method, which requires an `ElementInterface`, which can resul in a `TypeError` like the following:

```
TypeError: Argument 2 passed to craft\base\Field::isValueEmpty() must implement interface craft\base\ElementInterface, null given, called in /usr/share/nginx/craft/vendor/craftcms/cms/src/fields/Number.php on line 152 and defined in /usr/share/nginx/craft/vendor/craftcms/cms/src/base/Field.php:311
Stack trace:
#0 /usr/share/nginx/craft/vendor/craftcms/cms/src/fields/Number.php(152): craft\base\Field->isValueEmpty('24670.00', NULL)
#1 /packages/craft-csv-import/src/importers/ElementImporter.php(182): craft\fields\Number->normalizeValue('24670.00')
...
```

**Comment by brandonkelly** [comment]
Thanks for reporting!
