### ISSUE TITLE
After upgrading Craft (from RC13 to 3.0.9), submitting contact form generates a 500

### ISSUE THREAD

**Issue by lukehmu** [craftcms/cms#2939]
### Description

After upgrading Craft, we get a 500 error on contact form (https://github.com/craftcms/contact-form) submission.

```
2018-05-31 16:29:00 [176.35.121.183][1][0fc36d61a878df22b42c1b9a49409bce][error][Swift_SwiftException] Swift_SwiftException: No IDN encoder found (install the intl extension or the true/punycode package in /home/summithousingorg/nhf-events/vendor/swiftmailer/swiftmailer/lib/classes/Swift/AddressEncoder/IdnAddressEncoder.php:64
```
We haven't changed anything else and have never needed to install the intl extension before.

### Steps to reproduce

1. Have a basic contact form (can show you the code if necessary)
2. Submit it on Craft 3.0.9 without intl installed
3. 500

### Full stack trace
```
2018-05-31 16:29:00 [176.35.121.183][1][0fc36d61a878df22b42c1b9a49409bce][error][Swift_SwiftException] Swift_SwiftException: No IDN encoder found (install the intl extension or the true/punycode package in /home/summithousingorg/nhf-events/vendor/swiftmailer/swiftmailer/lib/classes/Swift/AddressEncoder/IdnAddressEncoder.php:64
Stack trace:
#0 /home/summithousingorg/nhf-events/vendor/swiftmailer/swiftmailer/lib/classes/Swift/AddressEncoder/IdnAddressEncoder.php(43): Swift_AddressEncoder_IdnAddressEncoder->idnToAscii('electricputty.c...')
#1 /home/summithousingorg/nhf-events/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(377): Swift_AddressEncoder_IdnAddressEncoder->encodeString('developer@elect...')
#2 /home/summithousingorg/nhf-events/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(478): Swift_Transport_EsmtpTransport->doMailFromCommand('developer@elect...')
#3 /home/summithousingorg/nhf-events/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(508): Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'developer@elect...', Array, Array)
#4 /home/summithousingorg/nhf-events/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(205): Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'developer@elect...', Array, Array)
#5 /home/summithousingorg/nhf-events/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(70): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#6 /home/summithousingorg/nhf-events/vendor/yiisoft/yii2-swiftmailer/src/Mailer.php(151): Swift_Mailer->send(Object(Swift_Message))
#7 /home/summithousingorg/nhf-events/vendor/yiisoft/yii2/mail/BaseMailer.php(263): yii\swiftmailer\Mailer->sendMessage(Object(craft\mail\Message))
#8 /home/summithousingorg/nhf-events/vendor/craftcms/cms/src/mail/Mailer.php(161): yii\mail\BaseMailer->send(Object(craft\mail\Message))
#9 /home/summithousingorg/nhf-events/vendor/craftcms/contact-form/src/Mailer.php(100): craft\mail\Mailer->send(Object(craft\mail\Message))
#10 /home/summithousingorg/nhf-events/vendor/craftcms/contact-form/src/controllers/SendController.php(51): craft\contactform\Mailer->send(Object(craft\contactform\models\Submission))
#11 [internal function]: craft\contactform\controllers\SendController->actionIndex()
#12 /home/summithousingorg/nhf-events/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /home/summithousingorg/nhf-events/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /home/summithousingorg/nhf-events/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('', Array)
#15 /home/summithousingorg/nhf-events/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('', Array)
#16 /home/summithousingorg/nhf-events/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('contact-form/se...', Array)
#17 /home/summithousingorg/nhf-events/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('contact-form/se...', Array)
#18 /home/summithousingorg/nhf-events/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#19 /home/summithousingorg/nhf-events/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /home/summithousingorg/nhf-events/web/index.php(65): yii\base\Application->run()
#21 {main}
2018-05-31 16:28:59 [176.35.121.183][1][0fc36d61a878df22b42c1b9a49409bce][info][application] $_GET = [
    'p' => 'sponsor/exhibit-at-the-event'
]
```

### Additional info

- Craft version: 3.0.9
- PHP version: 7.1.18
- Database driver & version: MySQL 5.6.38
- Plugins & versions: S3 / Asset Rev / Contact Form / Guest Entries / Minify / Redactor / SimpleMap / Super Table

**Comment by brandonkelly** [comment]
What version of Craft were you coming from? (You should be able to tell by checking the revision history  of `composer.json`,  or if that’s not helpful, `composer.lock`, if those are under version control.)

**Comment by lukehmu** [comment]
Hi Brandon,

We came from RC13 as per the title ^_^

We didn't (I don't think there's one available anyway) update the contact form plugin.

Thanks,
Luke

**Comment by angrybrad** [comment]
What version of the Contact Form plugin are you using?  If I install 2.1.1, the line numbers don't match up with your stack trace.  For example, I don't have the file lib/classes/Swift/AddressEncoder/IdnAddressEncoder.php file at all and EsmtpTransport.php line 377) is simply `$params = !empty($paramStr) ? explode(' ', $paramStr) : array();`

Are you running any custom configs from `config/app.php` that would be overriding the plugin components?
