### ISSUE TITLE
Exception when starting the queue via console ./craft queue 

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#3008]
### Description

We are trying to run Craft queues manually via `./craft queue/run` in our console. But whenever we run this command we receive the following error

```
Exception 'ParseError' with message 'syntax error, unexpected '?', expecting variable (T_VARIABLE)'
in vendor/symfony/process/Process.php:140
Stack trace:
#0 vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/project/...') 
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#2 vendor/yiisoft/yii2-queue/src/cli/Command.php(183): spl_autoload_call('Symfony\\Compone...')
#3 vendor/yiisoft/yii2-queue/src/cli/Command.php(125): yii\queue\cli\Command->handleMessage('7368', 'O:31:"craft\\que...', '300', 2)
#4 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}('7368', 'O:31:"craft\\que...', '300', 2)
#5 vendor/yiisoft/yii2-queue/src/cli/Queue.php(144): call_user_func(Object(Closure), '7368', 'O:31:"craft\\que...', '300', 2)
#6 vendor/craftcms/cms/src/queue/Queue.php(95): yii\queue\cli\Queue->handleMessage('7368', 'O:31:"craft\\que...', '300', 2)
#7 vendor/craftcms/cms/src/queue/Command.php(82): craft\queue\Queue->run()
#8 [internal function]: craft\queue\Command->actionRun()
#9 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('run', Array)
#12 vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array)
#13 vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array)
#14 vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array)
#15 vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 craft(22): yii\base\Application->run()
#17 {main}
```

It seems like the composer is not able to grab the correct class. There is a `Symfony\Component\Process` and Craft seems to try to access it but the composer auto loader seems to try to find it in `vendor/symfony/component/process` and not at the correct place `vendor/symfony/process/Process.php`

### Steps to reproduce

1. create a job
2. open the console and do `./craft queue`

### Additional info

- Craft version:  Craft Pro 3.0.12
- PHP version:  7.0.7

**Comment by Anubarak** [comment]
Sorry for the trouble the issue can be closed... It was not my project but from someone else and he used the wrong PHP Version 7.0.7

Craft suggest to require 7.0+ https://docs.craftcms.com/v3/requirements.html#server-requirements
But it actually requires a higher version to run the console command because of Symfony Process
