### ISSUE TITLE
MySQL: Table "searchindex" is marked as crashed and should be repaired

### ISSUE THREAD

**Issue by pabloroman** [craftcms/cms#3014]
### Description
Sometimes, the update of assets or entries from the admin panel fails and this MySQL error is thrown. So far I haven't been able to reproduce it reliably, the issue happens occasionally and unexpectedly. I will update the bug report if I find a way to reproduce it.

### Additional info

```
PDOException: SQLSTATE[HY000]: General error: 145 Table './tnw_next/searchindex' is marked as crashed and should be repaired in /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SHOW FULL COLUM...')
#2 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/mysql/Schema.php(312): yii\db\Command->queryAll()
#4 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/db/mysql/Schema.php(254): yii\db\mysql\Schema->findColumns(Object(craft\db\TableSchema))
#5 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Schema.php(744): craft\db\mysql\Schema->loadTableSchema('searchindex')
#6 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Schema.php(194): yii\db\Schema->getTableMetadata('{{%searchindex}...', 'schema', false)
#7 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/QueryBuilder.php(365): yii\db\Schema->getTableSchema('{{%searchindex}...')
#8 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(249): yii\db\QueryBuilder->prepareInsertValues('{{%searchindex}...', Array, Array)
#9 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/QueryBuilder.php(345): yii\db\mysql\QueryBuilder->prepareInsertValues('{{%searchindex}...', Array, Array)
#10 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(269): yii\db\QueryBuilder->insert('{{%searchindex}...', Array, Array)
#11 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Command.php(546): yii\db\mysql\QueryBuilder->upsert('{{%searchindex}...', Array, Array, Array)
#12 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/db/Command.php(122): yii\db\Command->upsert('{{%searchindex}...', Array, Array, Array)
#13 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/services/Search.php(322): craft\db\Command->upsert('{{%searchindex}...', Array, Array, Array, false)
#14 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/services/Search.php(137): craft\services\Search->_indexElementKeywords(52, 'field', '6', 1, 'red <p>Join 1.0...')
#15 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/services/Content.php(241): craft\services\Search->indexElementFields(52, 1, Array)
#16 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/services/Content.php(201): craft\services\Content->_updateSearchIndexes(Object(craft\elements\Entry), Object(craft\models\FieldLayout))
#17 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/services/Elements.php(480): craft\services\Content->saveContent(Object(craft\elements\Entry))
#18 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/controllers/EntriesController.php(543): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#19 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#20 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#22 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save-entry', Array)
#23 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#24 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('entries/save-en...', Array)
#25 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('entries/save-en...', Array)
#26 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#27 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#28 /home/vagrant/Code/thenextweb/tnw_next/web/index.php(21): yii\base\Application->run()
#29 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 145 Table './tnw_next/searchindex' is marked as crashed and should be repaired
The SQL being executed was: SHOW FULL COLUMNS FROM `searchindex` in /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SHOW FULL COLUM...')
#1 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SHOW FULL COLUM...')
#2 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/mysql/Schema.php(312): yii\db\Command->queryAll()
#4 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/db/mysql/Schema.php(254): yii\db\mysql\Schema->findColumns(Object(craft\db\TableSchema))
#5 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Schema.php(744): craft\db\mysql\Schema->loadTableSchema('searchindex')
#6 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Schema.php(194): yii\db\Schema->getTableMetadata('{{%searchindex}...', 'schema', false)
#7 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/QueryBuilder.php(365): yii\db\Schema->getTableSchema('{{%searchindex}...')
#8 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(249): yii\db\QueryBuilder->prepareInsertValues('{{%searchindex}...', Array, Array)
#9 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/QueryBuilder.php(345): yii\db\mysql\QueryBuilder->prepareInsertValues('{{%searchindex}...', Array, Array)
#10 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(269): yii\db\QueryBuilder->insert('{{%searchindex}...', Array, Array)
#11 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/db/Command.php(546): yii\db\mysql\QueryBuilder->upsert('{{%searchindex}...', Array, Array, Array)
#12 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/db/Command.php(122): yii\db\Command->upsert('{{%searchindex}...', Array, Array, Array)
#13 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/services/Search.php(322): craft\db\Command->upsert('{{%searchindex}...', Array, Array, Array, false)
#14 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/services/Search.php(137): craft\services\Search->_indexElementKeywords(52, 'field', '6', 1, 'red <p>Join 1.0...')
#15 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/services/Content.php(241): craft\services\Search->indexElementFields(52, 1, Array)
#16 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/services/Content.php(201): craft\services\Content->_updateSearchIndexes(Object(craft\elements\Entry), Object(craft\models\FieldLayout))
#17 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/services/Elements.php(480): craft\services\Content->saveContent(Object(craft\elements\Entry))
#18 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/controllers/EntriesController.php(543): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#19 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#20 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#22 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save-entry', Array)
#23 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#24 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('entries/save-en...', Array)
#25 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('entries/save-en...', Array)
#26 /home/vagrant/Code/thenextweb/tnw_next/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#27 /home/vagrant/Code/thenextweb/tnw_next/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#28 /home/vagrant/Code/thenextweb/tnw_next/web/index.php(21): yii\base\Application->run()
#29 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 145
    [2] => Table './tnw_next/searchindex' is marked as crashed and should be repaired
)
```

- Craft version: 3.0.12
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.22
- Plugins & versions: 
Amplify                 1.0.1
Dumper                  1.2.1
Feed Me                 3.0.0-beta.15
Google Cloud Storage    1.0.5
Mix                     1.4.3
Position Fieldtype      1.0.13
Redactor                2.1.0
Wordsmith               3.0.2

**Comment by angrybrad** [comment]
A MySQL MyISAM table can crash for any numbers of reasons, but it usually ends up being a MySQL box on a shared hosting server with limited resources or a stand-alone MySQL box that needs various config settings adjusted for more resources.  You can check and repair the table via: https://dev.mysql.com/doc/refman/5.7/en/myisam-repair.html

Alternatively, MySQL added full text search indexes to InnoDB in 5.6+, so you could convert that table to use InnoDB instead of MyISAM.  Craft 3 still supports a minimum of MySQL 5.5.

**Comment by missmatsuko** [comment]
Since 3.1.12, searching with an InnoDB craft_searchindex table causes errors:
#3862

**Comment by brandonkelly** [comment]
For posterity, #3862 is now resolved.
