### ISSUE TITLE
Redis session driver throws UnknownMethodException (getAssetBundleFlashes)

### ISSUE THREAD

**Issue by klemenb** [craftcms/cms#3084]
### Description

When trying to use Yii's Redis session driver, I get the following exception:

```
An Error occurred while handling another error:
yii\base\UnknownMethodException: Calling unknown method: yii\redis\Session::getAssetBundleFlashes() in /var/www/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/web/View.php(1421): yii\base\Component->__call('getAssetBundleF...', Array)
#1 /var/www/vendor/craftcms/cms/src/web/View.php(854): craft\web\View->registerAssetFlashes()
#2 /var/www/vendor/yiisoft/yii2/views/errorHandler/exception.php(526): craft\web\View->endBody()
#3 /var/www/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/vendor...')
#4 /var/www/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/vendor...', Array)
#5 /var/www/vendor/yiisoft/yii2/web/ErrorHandler.php(266): yii\base\View->renderFile('/var/www/vendor...', Array, Object(craft\web\ErrorHandler))
#6 /var/www/vendor/yiisoft/yii2/web/ErrorHandler.php(126): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#7 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(156): yii\web\ErrorHandler->renderException(Object(yii\base\UnknownMethodException))
#8 /var/www/vendor/yiisoft/yii2/base/ErrorHandler.php(111): craft\web\ErrorHandler->renderException(Object(yii\base\UnknownMethodException))
#9 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(71): yii\base\ErrorHandler->handleException(Object(yii\base\UnknownMethodException))
#10 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\base\UnknownMethodException))
#11 {main}
```

### Steps to reproduce

1. Install https://github.com/yiisoft/yii2-redis
2. Update configuration inside config/app.php with the following code:

```  
'components' => [
    'cache' => [
        'class' => \yii\redis\Cache::class,
    ],
    'session' => [
        'class' => \yii\redis\Session::class,
    ],
    'redis' => [
        'class' => \yii\redis\Connection::class,
        'hostname' => getenv('REDIS_SERVER'),
        'port' => getenv('REDIS_PORT'),
        'database' => getenv('REDIS_DATABASE'),
    ],
],
```

### Additional info

- Craft version: 3.0.14
- PHP version: 7.2.5
- Database driver & version: MySQL
- Plugins & versions: Commerce 2

**Comment by angrybrad** [comment]
Doing something like this from `craft/config/app.php` should work, too: https://github.com/pixelandtonic/craftnet/blob/develop/config/app.php#L108-L121
