### ISSUE TITLE
Craft deploy with empty db refuses to run, without error message or clear log

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#3270]
### Description

This is pretty straightforward; just it breaks your practice of always giving specific errors if Craft doesn't have enough configuration to run.

### Steps to reproduce

1. upload entirety of a working site to staging
2. set up .env correctly
3. however, neglect to actually load the created database, so it has no tables
4. result is that you get the site unavailable message, direct access or admin attempt
5. Thus browser screen hasn't given  you anything useful, and the relevant web.log message is as below, which talks about a rather anonymous application exception.
6. desirable would be that if you can't find tables, once the db is open, simply emit a text message saying so, as you do for various permission problems etc..

The relevant log lines:

```
2018-09-05 01:27:53 [68.6.161.158][-][cfpsuft3sfh5ub5kaia3t781ot][info][yii\db\Connection::open] Opening DB connection: mysql:host=localhost;dbname=ku_db;port=3306;
2018-09-05 01:27:53 [68.6.161.158][-][cfpsuft3sfh5ub5kaia3t781ot][profile begin][yii\db\Connection::open] Opening DB connection: mysql:host=localhost;dbname=ku_db;port=3306;
2018-09-05 01:27:53 [68.6.161.158][-][cfpsuft3sfh5ub5kaia3t781ot][profile end][yii\db\Connection::open] Opening DB connection: mysql:host=localhost;dbname=ku_db;port=3306;
2018-09-05 01:27:53 [68.6.161.158][-][cfpsuft3sfh5ub5kaia3t781ot][info][yii\db\Command::query] SHOW TABLES
2018-09-05 01:27:53 [68.6.161.158][-][cfpsuft3sfh5ub5kaia3t781ot][profile begin][yii\db\Command::query] SHOW TABLES
2018-09-05 01:27:53 [68.6.161.158][-][cfpsuft3sfh5ub5kaia3t781ot][profile end][yii\db\Command::query] SHOW TABLES
2018-09-05 01:27:53 [68.6.161.158][-][cfpsuft3sfh5ub5kaia3t781ot][error][yii\web\HttpException:503] craft\web\ServiceUnavailableHttpException in /var/www/ku/vendor/craftcms/cms/src/web/Application.php:515
Stack trace:
#0 /var/www/ku/vendor/craftcms/cms/src/web/Application.php(184): craft\web\Application->_processInstallRequest(Object(craft\web\Request))
#1 /var/www/ku/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#2 /var/www/ku/web/index.php(21): yii\base\Application->run()
#3 {main}
```

### Additional info

PHP version	7.1.20
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.1.20
Craft edition & version	Craft Pro 3.0.23
Yii version	2.0.15.1
Twig version	2.5.0
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins yes

**Comment by brandonkelly** [comment]
The Control Panel will now say "Craft isn't installed yet", but we'll leave the front-end with a generic message, as Craft can sometimes think it's uninstalled on live sites, if there's a DB connection issue, and you wouldn't want that error message showing up for site visitors.
