### ISSUE TITLE
Twig_Error_Runtime: Variable "blockTypes" does not exist

### ISSUE THREAD

**Issue by webkp** [craftcms/cms#3280]
### Description
Strange error after update from 3.0.22 => 3.0.23.1 when trying to edit an existing field (no matter what field type) when having `ENVIRONMENT="dev"` active
I cleared all caches from within the backend after the update but nothing helped. I was only able to edit fields once I changed ENVIRONMENT to something else than "dev"

```
Twig_Error_Runtime: Variable "blockTypes" does not exist. in /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/templates/_components/fieldtypes/Matrix/settings.html:12
Stack trace:
#0 /vagrant/www/_kunden/dummy.com/storage/runtime/compiled_templates/32/32e94a2c194fb1cebcb16aa4831f6c4455180e37eab092ea8808ba7150c5c96e.php(44): __TwigTemplate_25944c36e1168d1274a9c3a6b383d1bea334d9b6a3da5db233ffca54558079fd->{closure}()
#1 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_25944c36e1168d1274a9c3a6b383d1bea334d9b6a3da5db233ffca54558079fd->doDisplay(Array, Array)
#2 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#4 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#5 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#6 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#7 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('_components/fie...', Array)
#8 /vagrant/www/_kunden/dummy.com/vendor/verbb/super-table/src/services/SuperTableMatrixService.php(125): craft\web\View->renderTemplate('_components/fie...', Array)
#9 /vagrant/www/_kunden/dummy.com/vendor/verbb/super-table/src/fields/SuperTableField.php(740): verbb\supertable\services\SuperTableMatrixService->getMatrixSettingsHtml(Object(craft\fields\Matrix))
#10 /vagrant/www/_kunden/dummy.com/vendor/verbb/super-table/src/fields/SuperTableField.php(267): verbb\supertable\fields\SuperTableField->_getFieldOptionsForConfigurator()
#11 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/fields/Matrix.php(762): verbb\supertable\fields\SuperTableField->getSettingsHtml()
#12 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/fields/Matrix.php(265): craft\fields\Matrix->_getFieldOptionsForConfigurator()
#13 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Extension/Core.php(1619): craft\fields\Matrix->getSettingsHtml()
#14 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\fields\Matrix), 'getSettingsHtml', Array, 'method', false, false)
#15 /vagrant/www/_kunden/dummy.com/storage/runtime/compiled_templates/bb/bb83a1e0849d714decdd695774732d98f4a8a4d546b99ca6eb4eaf3eae8c1e01.php(246): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\fields\Matrix), 'getSettingsHtml', Array, 'method')
#16 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_74d0d0526fd4c7a8904ca61d6880cce0289ad2efe7613977190c4a98255b1d9e->block_content(Array, Array)
#17 /vagrant/www/_kunden/dummy.com/storage/runtime/compiled_templates/8d/8d5f9b6498108018a32895c80845b6066b081a28c7327db46a79236b0c5ba72a.php(639): Twig_Template->displayBlock('content', Array, Array)
#18 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_65582c7ebaee8134933e20c662410b146023e5b4e4975441e3d84c426a239df3->block_main(Array, Array)
#19 /vagrant/www/_kunden/dummy.com/storage/runtime/compiled_templates/8d/8d5f9b6498108018a32895c80845b6066b081a28c7327db46a79236b0c5ba72a.php(536): Twig_Template->displayBlock('main', Array, Array)
#20 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_65582c7ebaee8134933e20c662410b146023e5b4e4975441e3d84c426a239df3->block_body(Array, Array)
#21 /vagrant/www/_kunden/dummy.com/storage/runtime/compiled_templates/e1/e16f669e2a0513d3fdb5835d4b5c1e22ce75ef163ccf73f43937bf288d5fd7b6.php(60): Twig_Template->displayBlock('body', Array, Array)
#22 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_528677a290d18bb9255487dad0de9734f5a7caffb6e68b335508e8108f38d5e5->doDisplay(Array, Array)
#23 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#24 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#25 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#26 /vagrant/www/_kunden/dummy.com/storage/runtime/compiled_templates/67/67b4423b9516a68df9ed5d1d843a7d755dc5978286582c2b3efbbbccfd6a4b5f.php(40): craft\web\twig\Template->display(Array, Array)
#27 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_b510b59998a66217e507d814022e6341251965ece9f7ab9e66c6e4b5f6407eaa->doDisplay(Array, Array)
#28 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#29 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#30 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#31 /vagrant/www/_kunden/dummy.com/storage/runtime/compiled_templates/8d/8d5f9b6498108018a32895c80845b6066b081a28c7327db46a79236b0c5ba72a.php(94): craft\web\twig\Template->display(Array, Array)
#32 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_65582c7ebaee8134933e20c662410b146023e5b4e4975441e3d84c426a239df3->doDisplay(Array, Array)
#33 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#34 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#35 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#36 /vagrant/www/_kunden/dummy.com/storage/runtime/compiled_templates/bb/bb83a1e0849d714decdd695774732d98f4a8a4d546b99ca6eb4eaf3eae8c1e01.php(95): craft\web\twig\Template->display(Array, Array)
#37 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_74d0d0526fd4c7a8904ca61d6880cce0289ad2efe7613977190c4a98255b1d9e->doDisplay(Array, Array)
#38 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#39 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#40 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#41 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#42 /vagrant/www/_kunden/dummy.com/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#43 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('settings/fields...', Array)
#44 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('settings/fields...', Array)
#45 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/Controller.php(155): craft\web\View->renderPageTemplate('settings/fields...', Array)
#46 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/controllers/FieldsController.php(243): craft\web\Controller->renderTemplate('settings/fields...', Array)
#47 [internal function]: craft\controllers\FieldsController->actionEditField(32, Object(craft\fields\Assets), '4')
#48 /vagrant/www/_kunden/dummy.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#49 /vagrant/www/_kunden/dummy.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#50 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('edit-field', Array)
#51 /vagrant/www/_kunden/dummy.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-field', Array)
#52 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('fields/edit-fie...', Array)
#53 /vagrant/www/_kunden/dummy.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('fields/edit-fie...', Array)
#54 /vagrant/www/_kunden/dummy.com/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#55 /vagrant/www/_kunden/dummy.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#56 /vagrant/www/_kunden/dummy.com/web/index.php(21): yii\base\Application->run()
#57 {main}
```

### Steps to reproduce

1. Backend > Settings > Fields
2. Open any field when having set  ENVIRONMENT="dev" in .env file

### Additional info

- Craft version: 3.0.23.1
- PHP version: 7.0.30
- Database driver & version: MySQL 5.5.56
- Plugins & versions:

Entry Instructions 1.0.0
Expanded Singles 1.0.4
Redactor 2.1.6 
Super Table 2.0.8

**Comment by brandonkelly** [comment]
This is due to verbb/super-table#194. While we wait for a new Super Table release, can patch your install by following these instructions: https://github.com/verbb/super-table/issues/194#issuecomment-418519440
