### ISSUE TITLE
Site structure not able to create entries on root, ordering doesn't work

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/cms#3301]
### Description

Ordering doesn't  work in structures when trying to add an entry on root level it produces an error

### Steps to reproduce

1. Try to move entries in section
2. Try to create entry on root level

````
yii\db\Exception: Can not create a node when the target node is new record. in /home/rincoultrasonics_com/craft/vendor/creocoder/yii2-nested-sets/src/NestedSetsBehavior.php:379
Stack trace:
#0 /home/rincoultrasonics_com/craft/vendor/creocoder/yii2-nested-sets/src/NestedSetsBehavior.php(344): creocoder\nestedsets\NestedSetsBehavior->beforeInsertNode(NULL, 1)
#1 [internal function]: creocoder\nestedsets\NestedSetsBehavior->beforeInsert(Object(yii\base\ModelEvent))
#2 /home/rincoultrasonics_com/craft/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(yii\base\ModelEvent))
#3 /home/rincoultrasonics_com/craft/vendor/yiisoft/yii2/db/BaseActiveRecord.php(966): yii\base\Component->trigger('beforeInsert', Object(yii\base\ModelEvent))
#4 /home/rincoultrasonics_com/craft/vendor/craftcms/cms/src/db/ActiveRecord.php(56): yii\db\BaseActiveRecord->beforeSave(true)
#5 /home/rincoultrasonics_com/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(545): craft\db\ActiveRecord->beforeSave(true)
#6 /home/rincoultrasonics_com/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(520): yii\db\ActiveRecord->insertInternal(NULL)
#7 /home/rincoultrasonics_com/craft/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\db\ActiveRecord->insert(true, NULL)
#8 /home/rincoultrasonics_com/craft/vendor/creocoder/yii2-nested-sets/src/NestedSetsBehavior.php(115): yii\db\BaseActiveRecord->save(true, NULL)
#9 [internal function]: creocoder\nestedsets\NestedSetsBehavior->appendTo(Object(craft\records\StructureElement))
#10 /home/rincoultrasonics_com/craft/vendor/yiisoft/yii2/base/Component.php(297): call_user_func_array(Array, Array)
#11 /home/rincoultrasonics_com/craft/vendor/craftcms/cms/src/services/Structures.php(397): yii\base\Component->__call('appendTo', Array)
#12 /home/rincoultrasonics_com/craft/vendor/craftcms/cms/src/services/Structures.php(243): craft\services\Structures->_doIt(24, Object(craft\elements\Entry), Object(craft\records\StructureElement), 'appendTo', 'insert')
#13 /home/rincoultrasonics_com/craft/vendor/craftcms/cms/src/elements/Entry.php(1036): craft\services\Structures->appendToRoot(24, Object(craft\elements\Entry))
#14 /home/rincoultrasonics_com/craft/vendor/craftcms/cms/src/services/Elements.php(490): craft\elements\Entry->afterSave(true)
#15 /home/rincoultrasonics_com/craft/vendor/craftcms/cms/src/controllers/EntriesController.php(544): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#16 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#17 /home/rincoultrasonics_com/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /home/rincoultrasonics_com/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 /home/rincoultrasonics_com/craft/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save-entry', Array)
#20 /home/rincoultrasonics_com/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#21 /home/rincoultrasonics_com/craft/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('entries/save-en...', Array)
#22 /home/rincoultrasonics_com/craft/vendor/craftcms/cms/src/web/Application.php(541): craft\web\Application->runAction('entries/save-en...', Array)
#23 /home/rincoultrasonics_com/craft/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 /home/rincoultrasonics_com/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /home/rincoultrasonics_com/craft/web/index.php(21): yii\base\Application->run()
#26 {main}
Additional Information:
Array
(
)
````

### Additional info

- Craft version: Pro 3.0.24
- PHP version: 7.2.7
- Database driver & version: PostgreSQL 
- Plugins & versions: CraftQL, ElementApi, Redactor, TDE Geo Address Fields

**Comment by jan-thoma** [comment]
It doesn't happen with sections created after the update

**Comment by brandonkelly** [comment]
Can you please send a database backup over to support@craftcms.com and let us know which section you’re seeing this on?
