### ISSUE TITLE
Can't delete entries on a multisite installation

### ISSUE THREAD

**Issue by rjgux** [craftcms/cms#3372]
### Description

If I try and delete an entry from any section on any site in a Craft 3 multisite installation I get the error `Calling unknown method: craft\web\Request::getEntryById()`. Being called in `/craftcms/cms/src/controllers/EntriesController.php` (608: `$entry = $request->getEntryById($entryId, $siteId);`)

### Steps to reproduce

1. Trying to delete an entry from any site within a multisite installation

### Additional info

- Craft version: 3.0.27
- PHP version: 7.1.22
- Database driver & version: MySQL

### Stack trace
```
yii\base\UnknownMethodException: Calling unknown method: craft\web\Request::getEntryById() in /srv/users/serverpilot/apps/dyoung-multisite/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /srv/users/serverpilot/apps/dyoung-multisite/vendor/craftcms/cms/src/controllers/EntriesController.php(608): yii\base\Component->__call('getEntryById', Array)
#1 [internal function]: craft\controllers\EntriesController->actionDeleteEntry()
#2 /srv/users/serverpilot/apps/dyoung-multisite/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /srv/users/serverpilot/apps/dyoung-multisite/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /srv/users/serverpilot/apps/dyoung-multisite/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('delete-entry', Array)
#5 /srv/users/serverpilot/apps/dyoung-multisite/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('delete-entry', Array)
#6 /srv/users/serverpilot/apps/dyoung-multisite/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('entries/delete-...', Array)
#7 /srv/users/serverpilot/apps/dyoung-multisite/vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction('entries/delete-...', Array)
#8 /srv/users/serverpilot/apps/dyoung-multisite/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /srv/users/serverpilot/apps/dyoung-multisite/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /srv/users/serverpilot/apps/dyoung-multisite/public/index.php(28): yii\base\Application->run()
#11 {main}
```

**Comment by brandonkelly** [comment]
Thanks for reporting that @rjgux ! We just released 3.0.27.1 with a fix.
