### ISSUE TITLE
UsersController login action responds 500 Internal Server Error

### ISSUE THREAD

**Issue by blasvicco** [craftcms/cms#3458]
### Description

The `/src/controllers/UsersController.php:actionLogin()` result in `Internal Server Error` when the form submission doesn't post the field `loginName`.

```
TypeError: Argument 1 passed to craft\services\Users::getUserByUsernameOrEmail() must be of the type string, null given, called in /var/www/app/vendor/craftcms/cms/src/controllers/UsersController.php on line 128 and defined in /var/www/app/vendor/craftcms/cms/src/services/Users.php:165
Stack trace:
#0 /var/www/app/vendor/craftcms/cms/src/controllers/UsersController.php(128): craft\services\Users->getUserByUsernameOrEmail(NULL)
#1 [internal function]: craft\controllers\UsersController->actionLogin()
#2 /var/www/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/app/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('login', Array)
#5 /var/www/app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('login', Array)
#6 /var/www/app/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('users/login', Array)
#7 /var/www/app/vendor/craftcms/cms/src/web/Application.php(541): craft\web\Application->runAction('users/login', Array)
#8 /var/www/app/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /var/www/app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /var/www/app/web/index.php(98): yii\base\Application->run()
#11 {main}
```

### Expected behavior

- Error should be log.
- 400 Status Code `Bad Request Error` should be return.

### Steps to reproduce

1. `curl -X POST http://your.craft.project.com/?p=/login`

### Additional info

- Craft version: 3.0.25
- PHP version: 7.0.31

**Comment by brandonkelly** [comment]
Fixed for tomorrow’s release. Thanks for reporting!
