### ISSUE TITLE
Craft 3.1.0-beta.2 migrations errors 

### ISSUE THREAD

**Issue by michaelroper** [craftcms/cms#3504]
### Description
After updating from `3.0.32` to `3.1.0-beta.2`, I get similar SQL errors to #3295 + #3502 when accessing the CP. It appears that the migrations haven't run, but when I try to run them manually, they fail.

### Steps to reproduce
1. Changed `"craftcms/cms": "^3.1.0.32"` to `3.1.0-beta.2` and run `composer update`
2. Access CP and get SQL errors of `Column not found: 1054 Unknown column 'elements.dateDeleted'`
3. Run `./craft migrate/all` from CLI and get below errors...

```
$ ./craft migrate/all
Yii Migration Tool (based on Yii v2.0.15.1)

    > add column searchable boolean NOT NULL DEFAULT TRUE AFTER `instructions` to table {{%fields}} ... done (time: 0.050s)
    > update in {{%fields}} ... done (time: 0.090s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.001s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.001s)
    > update in {{%fields}} ... done (time: 0.001s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.001s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.040s)
    > update in {{%fields}} ... done (time: 0.001s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.041s)
Exception: Undefined offset: 7 (/Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/migrations/m180516_153000_uids_in_field_settings.php:165)
#0 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/migrations/m180516_153000_uids_in_field_settings.php(165): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/Users/michael....', 165, Array)
#1 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\m180516_153000_uids_in_field_settings->safeUp()
#2 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#3 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m180516_153000_uids_in_field_settings))
#4 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/services/Updates.php(214): craft\db\MigrationManager->up()
#5 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/console/controllers/MigrateController.php(243): craft\services\Updates->runMigrations(Array)
#6 [internal function]: craft\console\controllers\MigrateController->actionAll()
#7 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#10 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#11 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#12 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/all', Array)
#13 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#14 /Users/michael.roper/Sites/vocus-website-v3/craft(43): yii\base\Application->run()
#15 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Craft CMS.'
```

If I run it again though, the error changes to a different error/line...
```
$ ./craft migrate/all
Yii Migration Tool (based on Yii v2.0.15.1)

    > update in {{%fields}} ... done (time: 0.050s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.001s)
    > update in {{%fields}} ... done (time: 0.000s)
Exception: Undefined index: 369d012d-89ae-4d6c-9ce3-0b18e627d984 (/Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/migrations/m180516_153000_uids_in_field_settings.php:148)
#0 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/migrations/m180516_153000_uids_in_field_settings.php(148): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/michael....', 148, Array)
#1 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\m180516_153000_uids_in_field_settings->safeUp()
#2 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#3 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m180516_153000_uids_in_field_settings))
#4 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/services/Updates.php(214): craft\db\MigrationManager->up()
#5 /Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/console/controllers/MigrateController.php(243): craft\services\Updates->runMigrations(Array)
#6 [internal function]: craft\console\controllers\MigrateController->actionAll()
#7 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#10 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#11 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#12 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/all', Array)
#13 /Users/michael.roper/Sites/vocus-website-v3/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#14 /Users/michael.roper/Sites/vocus-website-v3/craft(43): yii\base\Application->run()
#15 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Craft CMS.'
```

**Comment by michaelroper** [comment]
Thanks @andris-sevcenko, will let you know how it goes for me when you roll the next release!
