### ISSUE TITLE
craft\migrations\m180520_173000_matrix_context_to_uids fails for upgrade to 3.1.0-beta.5.1

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#3592]
### Description

**One of Craft CMS’s migrations failed.**:

```
yii\base\ErrorException: Undefined offset: 37
Migration: craft\migrations\m180520_173000_matrix_context_to_uids
Output:
> update in {{%fields}} ... done (time: 0.006s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.002s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.001s)
Exception: Undefined offset: 37 (/var/www/html/vendor/craftcms/cms/src/migrations/m180520_173000_matrix_context_to_uids.php:34)
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/html/v...', 34)
#1 /var/www/html/vendor/craftcms/cms/src/migrations/m180520_173000_matrix_context_to_uids.php(34): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/html/v...', 34, Array)
#2 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\m180520_173000_matrix_context_to_uids->safeUp()
#3 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#4 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m180520_173000_matrix_context_to_uids))
#5 /var/www/html/vendor/craftcms/cms/src/services/Updates.php(214): craft\db\MigrationManager->up()
#6 /var/www/html/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(445): craft\services\Updates->runMigrations(Array)
#7 /var/www/html/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#8 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('updater/migrate', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(676): craft\web\Application->runAction('updater/migrate')
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(220): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /var/www/html/web/index.php(21): yii\base\Application->run()
#18 {main}
```
### Steps to reproduce

1. Upgrade from Craft 3.0.36 => 3.1.0-beta.5.1
2. Run required database update, and see the error.

### Additional info

- Craft version: 3.1.0-beta.5.1
- PHP version: 7.2.11

**Comment by ryanpcmcquen** [comment]
@brandonkelly, thank you, that got me further:

```
Database Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'dateDeleted'
The SQL being executed was: ALTER TABLE elements ADD dateDeleted datetime NULL DEFAULT NULL AFTER dateUpdated

Migration: craft\migrations\m180810_214439_soft_delete_elements

Output:

> add column dateDeleted datetime NULL DEFAULT NULL AFTER dateUpdated to table {{%elements}} ...Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'dateDeleted'
The SQL being executed was: ALTER TABLE elements ADD dateDeleted datetime NULL DEFAULT NULL AFTER dateUpdated (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE el...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE el...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute()
#3 /var/www/html/vendor/craftcms/cms/src/migrations/m180810_214439_soft_delete_elements.php(18): yii\db\Migration->addColumn('{{%elements}}', 'dateDeleted', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\m180810_214439_soft_delete_elements->safeUp()
#5 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#6 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m180810_214439_soft_delete_elements))
#7 /var/www/html/vendor/craftcms/cms/src/services/Updates.php(214): craft\db\MigrationManager->up()
#8 /var/www/html/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(445): craft\services\Updates->runMigrations(Array)
#9 /var/www/html/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#14 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('updater/migrate', Array)
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(676): craft\web\Application->runAction('updater/migrate')
#17 /var/www/html/vendor/craftcms/cms/src/web/Application.php(220): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /var/www/html/web/index.php(21): yii\base\Application->run()
#20 {main}
```

**Comment by ryanpcmcquen** [comment]
@brandonkelly, this should take care of it: https://github.com/craftcms/cms/pull/3593/files

**Comment by brandonkelly** [comment]
@ryanpcmcquen that error indicates that you still had some 3.1 DB changes in your database before re-updating to 3.1. Try recreating the entire DB before restoring the backup.

**Comment by ryanpcmcquen** [comment]
@brandonkelly, nope, I wrote a migration to add the field as instructed here:
https://craftcms.com/guides/craft-3-1-dev-preview-notes#support-for-other-things

Without the `dateDeleted` column I get the following error after upgrading from 3.0.x => 3.1.x-beta:

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'elements.dateDeleted' in 'where clause' in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `element...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#5 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(265): craft\db\Query->one()
#6 /var/www/html/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(763): craft\services\Elements->getElementByUri('utilities/syste...', 1, false)
#7 /var/www/html/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(140): nystudio107\seomatic\services\MetaContainers->setMatchedElement('utilities/syste...', '1')
#8 /var/www/html/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(47): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('utilities/syste...', NULL)
#9 /var/www/html/vendor/twig/twig/lib/Twig/ExtensionSet.php(339): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#10 /var/www/html/vendor/twig/twig/lib/Twig/Environment.php(903): Twig_ExtensionSet->getGlobals()
#11 /var/www/html/vendor/twig/twig/lib/Twig/Environment.php(923): Twig_Environment->getGlobals()
#12 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Environment->mergeGlobals(Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#14 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/View.php(436): Twig_Template->render(Array)
#16 /var/www/html/vendor/topshelfcraft/environment-label/src/services/Label.php(68): craft\web\View->renderString('dev // {{ curre...')
#17 /var/www/html/vendor/topshelfcraft/environment-label/src/services/Label.php(174): topshelfcraft\environmentlabel\services\Label->getRenderedText()
#18 /var/www/html/vendor/topshelfcraft/environment-label/src/EnvironmentLabel.php(68): topshelfcraft\environmentlabel\services\Label->doItBaby()
#19 [internal function]: topshelfcraft\environmentlabel\EnvironmentLabel->topshelfcraft\environmentlabel\{closure}(Object(craft\events\TemplateEvent))
#20 /var/www/html/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(craft\events\TemplateEvent))
#21 /var/www/html/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\View', 'beforeRenderPag...', Object(craft\events\TemplateEvent))
#22 /var/www/html/vendor/craftcms/cms/src/web/View.php(1349): yii\base\Component->trigger('beforeRenderPag...', Object(craft\events\TemplateEvent))
#23 /var/www/html/vendor/craftcms/cms/src/web/View.php(367): craft\web\View->beforeRenderPageTemplate('_special/dbupda...', Array)
#24 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('_special/dbupda...', Array)
#25 /var/www/html/vendor/craftcms/cms/src/controllers/TemplatesController.php(105): craft\web\Controller->renderTemplate('_special/dbupda...')
#26 [internal function]: craft\controllers\TemplatesController->actionManualUpdateNotification()
#27 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#28 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#29 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('manual-update-n...', Array)
#30 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('manual-update-n...', Array)
#31 /var/www/html/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('templates/manua...', Array)
#32 /var/www/html/vendor/craftcms/cms/src/web/Application.php(665): craft\web\Application->runAction('templates/manua...')
#33 /var/www/html/vendor/craftcms/cms/src/web/Application.php(220): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#34 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#35 /var/www/html/web/index.php(21): yii\base\Application->run()
#36 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'elements.dateDeleted' in 'where clause'
The SQL being executed was: SELECT `elements`.`id`, `elements`.`type`
FROM `elements` `elements`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
WHERE ((`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`siteId`=1)) AND (`elements_sites`.`uri`='utilities/system-report')
LIMIT 1 in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT `element...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `element...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#5 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(265): craft\db\Query->one()
#6 /var/www/html/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(763): craft\services\Elements->getElementByUri('utilities/syste...', 1, false)
#7 /var/www/html/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(140): nystudio107\seomatic\services\MetaContainers->setMatchedElement('utilities/syste...', '1')
#8 /var/www/html/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(47): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('utilities/syste...', NULL)
#9 /var/www/html/vendor/twig/twig/lib/Twig/ExtensionSet.php(339): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#10 /var/www/html/vendor/twig/twig/lib/Twig/Environment.php(903): Twig_ExtensionSet->getGlobals()
#11 /var/www/html/vendor/twig/twig/lib/Twig/Environment.php(923): Twig_Environment->getGlobals()
#12 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Environment->mergeGlobals(Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#14 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/View.php(436): Twig_Template->render(Array)
#16 /var/www/html/vendor/topshelfcraft/environment-label/src/services/Label.php(68): craft\web\View->renderString('dev // {{ curre...')
#17 /var/www/html/vendor/topshelfcraft/environment-label/src/services/Label.php(174): topshelfcraft\environmentlabel\services\Label->getRenderedText()
#18 /var/www/html/vendor/topshelfcraft/environment-label/src/EnvironmentLabel.php(68): topshelfcraft\environmentlabel\services\Label->doItBaby()
#19 [internal function]: topshelfcraft\environmentlabel\EnvironmentLabel->topshelfcraft\environmentlabel\{closure}(Object(craft\events\TemplateEvent))
#20 /var/www/html/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(craft\events\TemplateEvent))
#21 /var/www/html/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\View', 'beforeRenderPag...', Object(craft\events\TemplateEvent))
#22 /var/www/html/vendor/craftcms/cms/src/web/View.php(1349): yii\base\Component->trigger('beforeRenderPag...', Object(craft\events\TemplateEvent))
#23 /var/www/html/vendor/craftcms/cms/src/web/View.php(367): craft\web\View->beforeRenderPageTemplate('_special/dbupda...', Array)
#24 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('_special/dbupda...', Array)
#25 /var/www/html/vendor/craftcms/cms/src/controllers/TemplatesController.php(105): craft\web\Controller->renderTemplate('_special/dbupda...')
#26 [internal function]: craft\controllers\TemplatesController->actionManualUpdateNotification()
#27 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#28 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#29 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('manual-update-n...', Array)
#30 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('manual-update-n...', Array)
#31 /var/www/html/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('templates/manua...', Array)
#32 /var/www/html/vendor/craftcms/cms/src/web/Application.php(665): craft\web\Application->runAction('templates/manua...')
#33 /var/www/html/vendor/craftcms/cms/src/web/Application.php(220): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#34 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#35 /var/www/html/web/index.php(21): yii\base\Application->run()
#36 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'elements.dateDeleted' in 'where clause'
)
```

**Comment by brandonkelly** [comment]
@ryanpcmcquen those docs are for plugins that want to add soft delete support to their own things. You should not be manually altering Craft’s own database tables.

**Comment by ryanpcmcquen** [comment]
@brandonkelly, that's fine ... why is a nonexistent column expected in core code here and how should I work around it?

**Comment by brandonkelly** [comment]
Can you send a database backup (pre-3.1 update) and your `composer.json` and `composer.lock` files over to support@craftcms.com?

**Comment by ryanpcmcquen** [comment]
@brandonkelly, just sent it over, let me know how I can help.
