### ISSUE TITLE
Saving Entry without Required Field Creates Internal Server Error

### ISSUE THREAD

**Issue by jonlongnecker** [craftcms/cms#3627]
### Description
I have an entry with two required fields - Date and Category. If I leave either blank and try to save the entry, I get the Craft Styled "Internal Server Error."

Based on a few discussions in the Slack chat this isn't normal behavior - it should gracefully degrade and show which field is required.

This site is live not in dev mode.

### Additional info

- Craft version: 3.0.37
- PHP version: 7.2.12
- Database driver & version: MySQL 5.7.24

**Comment by brandonkelly** [comment]
Try deleting your `storage/logs/` folder, then reproduce the error, and search `storage/logs/web.log` for `[error]`. That should give you the actual error message and a stack trace for it. Can you post those?

**Comment by jonlongnecker** [comment]
Thanks Brandon, I tried looking in my logs and there was too much stuff! Deleting the folder helped a lot. Seems like it has something to do with Dukts' Analytics field type, I'm just not sure what. Should I move this over to his issues section? Or is it something Craft is doing?

```2019-01-15 08:16:11 [-][1][22engudhakk8oh8locia58os7m][error][TypeError] TypeError: Argument 1 passed to craft\services\Elements::getElementById() must be of the type integer, null given, called in /home/forge/site.com/vendor/dukt/analytics/src/services/Analytics.php on line 60 and defined in /home/forge/site.com/vendor/craftcms/cms/src/services/Elements.php:182
Stack trace:
#0 /home/forge/site.com/vendor/dukt/analytics/src/services/Analytics.php(60): craft\services\Elements->getElementById(NULL, NULL, '1')
#1 /home/forge/site.com/vendor/dukt/analytics/src/fields/Report.php(76): dukt\analytics\services\Analytics->getElementUrlPath(NULL, '1')
#2 /home/forge/site.com/vendor/twig/twig/lib/Twig/Extension/Core.php(1626): dukt\analytics\fields\Report->getInputHtml(NULL, Object(craft\elements\Entry))
#3 /home/forge/site.com/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(dukt\analytics\fields\Report), 'getInputHtml', Array, 'method', false, false)
#4 /home/forge/site.com/storage/runtime/compiled_templates/31/31a6af94a76cb7bb53d92ce8781872091ef4d42129715054e8dbfa849256369f.php(83): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(dukt\analytics\fields\Report), 'getInputHtml', Array, 'method')
#5 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_2353d3a86f32eec4c4fc9aaca30231dd82973a8d1347816e267f7471d88b5e38->doDisplay(Array, Array)
#6 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#7 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#8 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#9 /home/forge/site.com/storage/runtime/compiled_templates/6e/6ea9885c7f076ce664d2548e48ef83e1869e12120d758bea7413be4574ba0c8e.php(47): craft\web\twig\Template->display(Array)
#10 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_19db285aebfa4f4dc1cf2b40b17616050928c65508bfc4ab5ee840f6e4d3c245->doDisplay(Array, Array)
#11 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#12 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#13 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#14 /home/forge/site.com/storage/runtime/compiled_templates/0f/0f01202eaebb9460448a7519f9c0e7de4635383ced94c5c126849224d934ee17.php(59): craft\web\twig\Template->display(Array)
#15 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_5db02370606cd53173a77f107f98a73eca39c1a384a42850346bf84e0228e2d8->doDisplay(Array, Array)
#16 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#17 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#18 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#19 /home/forge/site.com/storage/runtime/compiled_templates/8b/8bbf5d3d5de631e04c656eba3099374d143549a0a0a6849292773a9ee3ce58ba.php(433): craft\web\twig\Template->display(Array)
#20 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_212c6f345a8394b689151f5fa8d4601a4b8c231aafbed2b0dee43572883e62e6->block_content(Array, Array)
#21 /home/forge/site.com/storage/runtime/compiled_templates/06/0674d4cd8862b0b78b2b40c82f8e7458821cadaf1c758fdb35c55cbf3f6563e1.php(648): Twig_Template->displayBlock('content', Array, Array)
#22 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_64a634b70b60be99e6c8b8b9f8e89223fb870662f1d05c9c6b4af0364b89c168->block_main(Array, Array)
#23 /home/forge/site.com/storage/runtime/compiled_templates/06/0674d4cd8862b0b78b2b40c82f8e7458821cadaf1c758fdb35c55cbf3f6563e1.php(533): Twig_Template->displayBlock('main', Array, Array)
#24 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_64a634b70b60be99e6c8b8b9f8e89223fb870662f1d05c9c6b4af0364b89c168->block_body(Array, Array)
#25 /home/forge/site.com/storage/runtime/compiled_templates/07/07d1b2547181338b43015e4403987245f77ca747e31ef6584f8e85e719bf04a6.php(60): Twig_Template->displayBlock('body', Array, Array)
#26 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_f5f63f9de9ce2da46a7b9008eb3e2698ac1a74c20ca732bb2bfa165f832881da->doDisplay(Array, Array)
#27 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#28 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#29 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#30 /home/forge/site.com/storage/runtime/compiled_templates/5e/5e585a5726d2fb1a4d220c69e03cf6006e550ec9a6d18670caf684cbbe4eddcb.php(40): craft\web\twig\Template->display(Array, Array)
#31 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_7e1f483030821a6cdda280cdb244ef54ba6d58c2e15a7efc0d100e61b8d19190->doDisplay(Array, Array)
#32 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#33 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#34 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#35 /home/forge/site.com/storage/runtime/compiled_templates/06/0674d4cd8862b0b78b2b40c82f8e7458821cadaf1c758fdb35c55cbf3f6563e1.php(95): craft\web\twig\Template->display(Array, Array)
#36 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_64a634b70b60be99e6c8b8b9f8e89223fb870662f1d05c9c6b4af0364b89c168->doDisplay(Array, Array)
#37 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#38 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#39 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#40 /home/forge/site.com/storage/runtime/compiled_templates/8b/8bbf5d3d5de631e04c656eba3099374d143549a0a0a6849292773a9ee3ce58ba.php(62): craft\web\twig\Template->display(Array, Array)
#41 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_212c6f345a8394b689151f5fa8d4601a4b8c231aafbed2b0dee43572883e62e6->doDisplay(Array, Array)
#42 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#43 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#44 /home/forge/site.com/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#45 /home/forge/site.com/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#46 /home/forge/site.com/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#47 /home/forge/site.com/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('entries/_edit', Array)
#48 /home/forge/site.com/vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('entries/_edit', Array)
#49 /home/forge/site.com/vendor/craftcms/cms/src/web/Controller.php(156): craft\web\View->renderPageTemplate('entries/_edit', Array)
#50 /home/forge/site.com/vendor/craftcms/cms/src/controllers/EntriesController.php(385): craft\web\Controller->renderTemplate('entries/_edit', Array)
#51 [internal function]: craft\controllers\EntriesController->actionEditEntry('events', NULL, NULL, NULL, NULL, Object(craft\elements\Entry))
#52 /home/forge/site.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#53 /home/forge/site.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#54 /home/forge/site.com/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('edit-entry', Array)
#55 /home/forge/site.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#56 /home/forge/site.com/vendor/craftcms/cms/src/web/Application.php(284): yii\base\Module->runAction('entries/edit-en...', Array)
#57 /home/forge/site.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#58 /home/forge/site.com/vendor/craftcms/cms/src/web/Application.php(273): yii\web\Application->handleRequest(Object(craft\web\Request))
#59 /home/forge/site.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#60 /home/forge/site.com/web/index.php(42): yii\base\Application->run()
#61 {main}
```

**Comment by jonlongnecker** [comment]
Oh weird, I thought I grabbed that, sorry:

```2019-01-15 08:16:11 [-][1][22engudhakk8oh8locia58os7m][error][TypeError] TypeError: Argument 1 passed to craft\services\Elements::getElementById() must be of the type integer, null given, called in /home/forge/camdenmilitary.com/vendor/dukt/analytics/src/services/Analytics.php on line 60 and defined in /home/forge/camdenmilitary.com/vendor/craftcms/cms/src/services/Elements.php:182```

**Comment by brandonkelly** [comment]
OK, yeah that’s definitely going to be an Analytics issue. Please post that same info over at https://github.com/dukt/analytics/issues . Thanks!

**Comment by jonlongnecker** [comment]
Will do - though I have multiple issues into Dukt about Analytics and haven't heard anything for months :-/

**Comment by jonlongnecker** [comment]
Haha thanks :)
