### ISSUE TITLE
Craft update 3.0.37 to 3.1 - 

### ISSUE THREAD

**Issue by mdominguez** [craftcms/cms#3641]
### Description

Getting this after upgrading Craft update 3.0.37 to 3.1 
[view screenshot](https://cl.ly/8644dc7f95c5)

```
yii\base\ErrorException: Undefined offset: 1

Migration: craft\migrations\m180516_153000_uids_in_field_settings

Output:

Exception: Undefined offset: 1 (/Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/migrations/m180516_153000_uids_in_field_settings.php:45)
#0 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/Users/Mattias/...', 45)
#1 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/migrations/m180516_153000_uids_in_field_settings.php(45): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/Users/Mattias/...', 45, Array)
#2 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\m180516_153000_uids_in_field_settings->safeUp()
#3 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#4 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m180516_153000_uids_in_field_settings))
#5 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/services/Updates.php(215): craft\db\MigrationManager->up()
#6 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(445): craft\services\Updates->runMigrations(Array)
#7 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#8 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#9 /Users/Mattias/Sites/techbox/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/Mattias/Sites/techbox/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#12 /Users/Mattias/Sites/techbox/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#13 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#14 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#15 /Users/Mattias/Sites/techbox/vendor/craftcms/cms/src/web/Application.php(223): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#16 /Users/Mattias/Sites/techbox/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/Mattias/Sites/techbox/web/index.php(21): yii\base\Application->run()
#18 /Users/Mattias/.composer/vendor/laravel/valet/server.php(151): require('/Users/Mattias/...')
#19 {main}
```

### Additional info

- Craft version: 3.0.37 -> 3.1
- PHP version: PHP 7.3.1 (cli) (built: Jan 10 2019 13:15:37) ( NTS )
- Database driver & version: MariaDB 10.3.12
- Plugins & versions:

**Comment by elfacht** [comment]
Getting this:

```
Unknown Property: Getting unknown property: craft\redactor\Field::contentTable

Migration: craft\migrations\m190108_113000_asset_field_setting_change
```

**Comment by andris-sevcenko** [comment]
@elfacht that's an unrelated issue and was fixed in 717a04a766f32a1f433146c8a6fc52f178a154c7. There should be a release later today!

**Comment by Delonvdv** [comment]
Im having the same issue when upgrading from Craft v 2.7.4 to 3. Logs below

yii\base\ErrorException: Undefined index: defaultUploadLocationSource
Migration: craft\migrations\m180516_153000_uids_in_field_settings
Output:
Exception: Undefined index: defaultUploadLocationSource (/Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/migrations/m180516_153000_uids_in_field_settings.php:45) #0 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/00005201...', 45) #1 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/migrations/m180516_153000_uids_in_field_settings.php(45): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/Users/00005201...', 45, Array) #2 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\m180516_153000_uids_in_field_settings->safeUp() #3 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true) #4 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m180516_153000_uids_in_field_settings)) #5 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/services/Updates.php(215): craft\db\MigrationManager->up() #6 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(445): craft\services\Updates->runMigrations(Array) #7 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db') #8 [internal function]: craft\controllers\UpdaterController->actionMigrate() #9 /Users/00005201/Documents/projects/corpweb3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #10 /Users/00005201/Documents/projects/corpweb3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #11 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array) #12 /Users/00005201/Documents/projects/corpweb3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array) #13 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array) #14 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate') #15 /Users/00005201/Documents/projects/corpweb3/vendor/craftcms/cms/src/web/Application.php(223): craft\web\Application->_processUpdateLogic(Object(craft\web\Request)) #16 /Users/00005201/Documents/projects/corpweb3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request)) #17 /Users/00005201/Documents/projects/corpweb3/web/index.php(21): yii\base\Application->run() #18 {main}

**Comment by joshuabaker** [comment]
We’re also running into issues with the `defaultUploadLocationSource`, `singleUploadLocationSource` and `source` related migration, upgrading from 2.7.4 to 3.1.1.

**Comment by carlcs** [comment]
@andris-sevcenko there is one more migration affected

```
Exception: Undefined index: singleUploadLocationSource (/Users/Christian/Websites/foo/vendor/craftcms/cms/src/migrations/m190108_113000_asset_field_setting_change.php:47)
#0 /Users/Christian/Websites/foo/vendor/craftcms/cms/src/migrations/m190108_113000_asset_field_setting_change.php(47): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/Christia...', 47, Array)
#1 /Users/Christian/Websites/foo/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\m190108_113000_asset_field_setting_change->safeUp()
#2 /Users/Christian/Websites/foo/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#3 /Users/Christian/Websites/foo/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m190108_113000_asset_field_setting_change))
#4 /Users/Christian/Websites/foo/vendor/craftcms/cms/src/services/Updates.php(215): craft\db\MigrationManager->up()
#5 /Users/Christian/Websites/foo/vendor/craftcms/cms/src/console/controllers/MigrateController.php(243): craft\services\Updates->runMigrations(Array)
#6 [internal function]: craft\console\controllers\MigrateController->actionAll()
#7 /Users/Christian/Websites/foo/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Users/Christian/Websites/foo/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /Users/Christian/Websites/foo/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#10 /Users/Christian/Websites/foo/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#11 /Users/Christian/Websites/foo/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#12 /Users/Christian/Websites/foo/vendor/craftcms/cms/src/console/Application.php(99): yii\console\Application->runAction('migrate/all', Array)
#13 /Users/Christian/Websites/foo/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#14 /Users/Christian/Websites/foo/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /Users/Christian/Websites/foo/craft(22): yii\base\Application->run()
#16 {main}
```

**Comment by andris-sevcenko** [comment]
Grrrrr.

**Comment by carlcs** [comment]
> `Migrated up successfully.`

Thanks @andris-sevcenko

**Comment by brandonkelly** [comment]
3.1.2 is out now with the fix for this.
