### ISSUE TITLE
Error when creating a new site in 3.1

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#3670]
### Description

It’s not possible in 3.1 to create new sites.

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'groupId' cannot be null
The SQL being executed was: INSERT INTO `sites` (`uid`, `groupId`, `name`, `handle`, `language`, `hasUrls`, `baseUrl`, `primary`, `sortOrder`, `dateCreated`, `dateUpdated`) VALUES ('92bad291-d966-4cea-9931-f790b13cb13b', NULL, 'German', 'german', 'de', 1, '@web/', 0, 2, '2019-01-18 16:29:34', '2019-01-18 16:29:34')
```

### Additional info

- Craft version: 3.1.1

**Comment by carlcs** [comment]
Seems like it not just didn’t create the new site, it also corrupted site settings in general. I now get this error for any request:

```
An Error occurred while handling another error:
craft\errors\SiteNotFoundException: No primary site exists in /Users/Christian/Websites/craft3/vendor/craftcms/cms/src/services/Sites.php:496
Stack trace:
#0 /Users/Christian/Websites/craft3/vendor/craftcms/cms/src/web/Request.php(1133): craft\services\Sites->getPrimarySite()
#1 /Users/Christian/Websites/craft3/vendor/craftcms/cms/src/web/Request.php(172): craft\web\Request->_requestedSite(Object(craft\services\Sites))
#2 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Request->init()
#3 [internal function]: yii\base\BaseObject->__construct(Array)
#4 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#5 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Reque...', Array, Array)
#6 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Reque...', Array, Array)
#7 /Users/Christian/Websites/craft3/vendor/craftcms/cms/src/config/app.web.php(13): yii\BaseYii::createObject(Array)
#8 [internal function]: {closure}()
#9 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/di/Container.php(503): call_user_func_array(Object(Closure), Array)
#10 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#11 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#12 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('request', true)
#13 /Users/Christian/Websites/craft3/vendor/craftcms/cms/src/web/Application.php(348): yii\base\Module->get('request', true)
#14 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/di/ServiceLocator.php(74): craft\web\Application->get('request')
#15 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/web/ErrorHandler.php(499): yii\di\ServiceLocator->__get('request')
#16 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/web/ErrorHandler.php(115): yii\web\ErrorHandler->shouldRenderSimpleHtml()
#17 /Users/Christian/Websites/craft3/vendor/craftcms/cms/src/web/ErrorHandler.php(132): yii\web\ErrorHandler->renderException(Object(craft\errors\SiteNotFoundException))
#18 /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/base/ErrorHandler.php(111): craft\web\ErrorHandler->renderException(Object(craft\errors\SiteNotFoundException))
#19 /Users/Christian/Websites/craft3/vendor/craftcms/cms/src/web/ErrorHandler.php(63): yii\base\ErrorHandler->handleException(Object(craft\errors\SiteNotFoundException))
#20 [internal function]: craft\web\ErrorHandler->handleException(Object(craft\errors\SiteNotFoundException))
#21 {main}
```

**Comment by carlcs** [comment]
I now started fresh with `'useProjectConfigFile' => false` this time and ran into the same issue. It seems like it tried to create a new site group.

This is the config from info table, new site (or group) weren’t created in sites or sitegroups tables.

```
s:10:"siteGroups";a:2:{s:36:"9c865392-4573-4c15-b362-dfc0b665c2ec";a:1:{s:4:"name";s:6:"German";}s:36:"be961959-f9f3-40b9-b111-580ebf1effef";a:1:{s:4:"name";s:7:"English";}}s:5:"sites";a:2:{s:36:"3aed229d-af87-46b6-abc7-b62a28ba24f7";a:8:{s:7:"baseUrl";s:8:"@web/en/";s:6:"handle";s:7:"english";s:7:"hasUrls";s:1:"1";s:8:"language";s:2:"en";s:4:"name";s:7:"English";s:7:"primary";s:1:"1";s:9:"siteGroup";s:36:"be961959-f9f3-40b9-b111-580ebf1effef";s:9:"sortOrder";s:1:"1";}s:36:"e4db205b-c8cb-4f75-bd07-bf437849f09d";a:8:{s:7:"baseUrl";s:7:"@web/de";s:6:"handle";s:6:"german";s:7:"hasUrls";s:1:"1";s:8:"language";s:2:"de";s:4:"name";s:6:"German";s:7:"primary";s:1:"0";s:9:"siteGroup";s:36:"9c865392-4573-4c15-b362-dfc0b665c2ec";s:9:"sortOrder";s:1:"2";}}
```

**Comment by carlcs** [comment]
OK, it happend because I had site URLs defined in my general.php

```php
'siteUrl' => [
    'english' => getenv('SITE_URL_EN'),
    'german' => getenv('SITE_URL_DE'),
],
```

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Are you able to come up with specific steps to reproduce from a fresh install?

If not, please send a database dump, your `config/project.yaml`, `config/general.php`, `composer.json`, and `composer.lock` files, over to support@craftcms.com and we’ll see if we can figure out what went wrong.

**Comment by carlcs** [comment]
Hm I can’t reproduce it again. I tried it a couple of times, but there’s so many moving parts and many things happened on this install since I ran into it, it’s also not within the 50 yml backups any more.

Sorry, but I think I’ll have to close the issue.
