### ISSUE TITLE
Next Twig_Error_Runtime: An exception has been thrown during the rendering of a template

### ISSUE THREAD

**Issue by rinusvandam** [craftcms/cms#3704]
### Description

I have a structured section called pages with a few entry types (default page, page with table, etc.). 
I decided to move some pages away from this structure and set them up as singles because I don't want my client to edit them. I setup the singles and removed the entry types from the pages section. 

When I go to entries and visit the pages section my pages are gone that had the removed entry types. When I click the dropdown to see the thrashed pages I get multiple ‘An unknown error occurred’ messages. When I visit another section I get multiple ‘An unknown error occurred’ messages. A hard browser refresh makes my pages appear again.

### Stack trace

```
Next Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Invalid entry type ID: 16"). in /sites/pwr/craft/vendor/craftcms/cms/src/templates/_elements/tableview/elements.html:25
Stack trace:
#0 /sites/pwr/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#1 /sites/pwr/craft/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#2 /sites/pwr/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#3 /sites/pwr/craft/storage/runtime/compiled_templates/38/3812c747e905baf9c4a9fb8bb39cc0b5cadcc7f57fe484b4350f525b7c6c6d4b.php(81): craft\web\twig\Template->display(Array)
#4 /sites/pwr/craft/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_ccd268acc06c46450b8d43cf672a7c9ad727b91f75b0a48dab65641af780bea9->doDisplay(Array, Array)
#5 /sites/pwr/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#6 /sites/pwr/craft/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#7 /sites/pwr/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#8 /sites/pwr/craft/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#9 /sites/pwr/craft/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#10 /sites/pwr/craft/vendor/craftcms/cms/src/web/View.php(337): Twig_Environment->render('_elements/table...', Array)
#11 /sites/pwr/craft/vendor/craftcms/cms/src/base/Element.php(449): craft\web\View->renderTemplate('_elements/table...', Array)
#12 /sites/pwr/craft/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(385): craft\base\Element::indexHtml(Object(craft\elements\db\EntryQuery), Array, Array, 'section:129dc3e...', 'index', true, true)
#13 /sites/pwr/craft/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(121): craft\controllers\ElementIndexesController->_elementResponseData(true, true)
#14 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
#15 /sites/pwr/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /sites/pwr/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /sites/pwr/craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('get-elements', Array)
#18 /sites/pwr/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-elements', Array)
#19 /sites/pwr/craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('element-indexes...', Array)
#20 /sites/pwr/craft/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('element-indexes...', Array)
#21 /sites/pwr/craft/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /sites/pwr/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /sites/pwr/web/index.php(21): yii\base\Application->run()
#24 {main}
```

### Steps to reproduce

1. Create a structured section with different entry types
2. Create pages inside this section and attach different entry types to different pages
3. Go to settings > sections > edit entry types > and remove entry types that are attached to pages
4. Visit entries > the structured section with pages and choose Trashed from the dropdown
5. Error messages appear

### Additional info

- Craft version: Craft Pro 3.1.3
- PHP version: 7.3.0
- Database driver & version: MySQL 5.7.23
- oEmbed: 1.0.4
- Read Time: 1.4.0
- Redactor: 2.3.0
- SEO: 3.5.3
- SimpleMap: 3.3.4

**Comment by brandonkelly** [comment]
Can you please send a database backup, your `composer.json` and `composer.lock` files, and you `storage/config-backups/` folder, all over to support@craftcms.com ?
