### ISSUE TITLE
Unknown Property Error after upgrade to 3.1.3 from 3.0.37

### ISSUE THREAD

**Issue by TonyDeStefano** [craftcms/cms#3706]
### Description

```
yii\base\UnknownPropertyException: Setting unknown property: craft\models\Info::config in /var/www/html/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('config', 'a:16:{s:14:"cat...')
#1 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\models\Info), Array)
#2 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(539): yii\base\BaseObject->__construct(Array)
#3 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1167): craft\web\Application->getInfo()
#4 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1136): craft\web\Application->_setTimeZone()
#5 /var/www/html/vendor/craftcms/cms/src/web/Application.php(108): craft\web\Application->_preInit()
#6 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#7 /var/www/html/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#8 /var/www/html/vendor/craftcms/cms/src/web/Application.php(99): yii\base\Application->__construct(Array)
#9 [internal function]: craft\web\Application->__construct(Array)
#10 /var/www/html/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#11 /var/www/html/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#12 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#13 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(252): yii\BaseYii::createObject(Array)
#14 /var/www/html/vendor/craftcms/cms/bootstrap/web.php(42): require('/var/www/html/v...')
#15 /var/www/html/web/index.php(20): require('/var/www/html/v...')
#16 {main}
```

### Steps to reproduce

1. Upgrade to 3.1.3
2. Reload website

### Additional info

- Craft version: 3.1.3
- PHP version: 7.2.11
- Database driver & version: MySql 5.5.5
- Plugins & versions:

**Comment by ryanpcmcquen** [comment]
The error messaging could be improved when there is an absence of a `project.yaml` though.
