### ISSUE TITLE
Installer fails: No primary site exists

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#3763]
### Description

The installer fails with the following message:

```
> applying existing project config ... done
Exception: No primary site exists (/app/user/vendor/craftcms/cms/src/services/Sites.php:496)
```

I have an existing project.yaml with 3 sites. One of which has `primary: true`. None of them have the `default` handle.

Full stack trace:

```
web_1         |     > applying existing project config ... done
web_1         | Exception: No primary site exists (/app/user/vendor/craftcms/cms/src/services/Sites.php:496)
web_1         | #0 /app/user/vendor/craftcms/cms/src/migrations/Install.php(1043): craft\services\Sites->getPrimarySite()
web_1         | #1 /app/user/vendor/craftcms/cms/src/migrations/Install.php(70): craft\migrations\Install->insertDefaultData()
web_1         | #2 /app/user/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\Install->safeUp()
web_1         | #3 /app/user/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
web_1         | #4 /app/user/vendor/craftcms/cms/src/console/controllers/InstallController.php(161): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
web_1         | #5 [internal function]: craft\console\controllers\InstallController->actionCraft()
web_1         | #6 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
web_1         | #7 /app/user/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
web_1         | #8 /app/user/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
web_1         | #9 /app/user/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
web_1         | #10 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
web_1         | #11 /app/user/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('install', Array)
web_1         | #12 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
web_1         | #13 /app/user/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
web_1         | #14 /app/user/craft(23): yii\base\Application->run()
web_1         | #15 {main}
```

This seems to be happening since 3.1.7

### Steps to reproduce

1. Create a project.yaml with 3 sites (1 of which primay, none of them with the `default` handle)
2. Try to install a fresh site with this project.yaml

### Additional info

- Craft version: 3.1.7
- PHP version: 7.3.1
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: N/A

**Comment by andris-sevcenko** [comment]
Can you send over the project.yaml file you are using to support@craftcms.com?

**Comment by boboldehampsink** [comment]
This seems to have been fixed with the aws plugin update. It might've been that that error caused another error down the line.

**Comment by andris-sevcenko** [comment]
That explains why I wasn't able to reproduce this :)
