### ISSUE TITLE
Unable to save entries

### ISSUE THREAD

**Issue by jwb009** [craftcms/cms#3811]
### Description
Struggling with my upgrade from Craft 2 to 3.1. I thought everything went fine, but it turns out I can't save entries. The error is `Twig_Error_Runtime: Variable "entry" does not exist in "__string_template__820a705f8d8680b23c62d8187993934b4613ddc29657be106240b7b1b4a2de81" at line 1. `

Full trace:
```
Twig_Error_Runtime: Variable "entry" does not exist in "__string_template__820a705f8d8680b23c62d8187993934b4613ddc29657be106240b7b1b4a2de81" at line 1. in /home/vagrant/code/ks3/storage/runtime/compiled_templates/13/134bdd7e7e2056269543c31d11aa552580dabec14eea3c26ec6faf70dbd8129f.php:27
Stack trace:
#0 /home/vagrant/code/ks3/storage/runtime/compiled_templates/13/134bdd7e7e2056269543c31d11aa552580dabec14eea3c26ec6faf70dbd8129f.php(27): __TwigTemplate_afca4129222a6b20b03ed76af018ae10fea31260c4a309b908139b4c98ae6cba->{closure}()
#1 /home/vagrant/code/ks3/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_afca4129222a6b20b03ed76af018ae10fea31260c4a309b908139b4c98ae6cba->doDisplay(Array, Array)
#2 /home/vagrant/code/ks3/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /home/vagrant/code/ks3/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#4 /home/vagrant/code/ks3/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#5 /home/vagrant/code/ks3/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#6 /home/vagrant/code/ks3/vendor/craftcms/cms/src/web/View.php(525): Twig_Template->render(Array)
#7 /home/vagrant/code/ks3/vendor/craftcms/cms/src/helpers/ElementHelper.php(145): craft\web\View->renderObjectTemplate('expertise/{{ (_...', Object(craft\elements\Entry), Array)
#8 /home/vagrant/code/ks3/vendor/craftcms/cms/src/helpers/ElementHelper.php(92): craft\helpers\ElementHelper::_renderUriFormat('expertise/{expe...', Object(craft\elements\Entry))
#9 /home/vagrant/code/ks3/vendor/craftcms/cms/src/validators/ElementUriValidator.php(49): craft\helpers\ElementHelper::setUniqueUri(Object(craft\elements\Entry))
#10 /home/vagrant/code/ks3/vendor/yiisoft/yii2/validators/Validator.php(267): craft\validators\ElementUriValidator->validateAttribute(Object(craft\elements\Entry), 'uri')
#11 /home/vagrant/code/ks3/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#12 /home/vagrant/code/ks3/vendor/craftcms/cms/src/services/Elements.php(429): yii\base\Model->validate()
#13 /home/vagrant/code/ks3/vendor/craftcms/cms/src/controllers/EntriesController.php(551): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#14 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#15 /home/vagrant/code/ks3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /home/vagrant/code/ks3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /home/vagrant/code/ks3/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-entry', Array)
#18 /home/vagrant/code/ks3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#19 /home/vagrant/code/ks3/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('entries/save-en...', Array)
#20 /home/vagrant/code/ks3/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('entries/save-en...', Array)
#21 /home/vagrant/code/ks3/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /home/vagrant/code/ks3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /home/vagrant/code/ks3/web/index.php(37): yii\base\Application->run()
#24 {main}
```

Any ideas? Thank you.

### Steps to reproduce

1. Upgrade from Craft 2 to 3.1
2. Try to save an entry

### Additional info

- Craft version: 3.1.8
- PHP version: 7.2.11
- Database driver & version: MySQL 5.7.23
- Plugins & versions:

**Comment by brandonkelly** [comment]
Probably an issue with your section’s Entry URI Format. What is that set to?

**Comment by jwb009** [comment]
I believe you're correct. The URI is set to: `expertise/{expertise.first.slug}/{slug}{% if entry.buildingName|length %}-{{ entry.buildingName }}{% endif %}` 
This was set by a previous developer...doesn't throw any errors in C2, though.

**Comment by brandonkelly** [comment]
Huh… Craft 2 didn’t support an `entry` variable there IIRC. Try changing to:

```twig
expertise/{expertise.one().slug}/{slug}{% if buildingName|length %}-{{ buildingName }}{% endif %}
```

**Comment by jwb009** [comment]
Yea, I didn't think it did (I thought it was just `object`). Your suggestion also failed. Maybe it's because the section has `Show the Title Field` checked, so I'm trying to make something dynamic that shouldn't be?

Either way, I think I'm just going to go about it a different way and remove the conditional completely.  Feel free to close it.
