### ISSUE TITLE
Craft CMS 3 Update failure

### ISSUE THREAD

**Issue by hegrobler** [craftcms/cms#3976]
### Description
I was doing what I thought would be a routine update via the Cpanel but the migration has failed. 
I've never run into this type of error and have no idea how to proceed. 
I've tried to resolve this multiple times by resetting to my previous backup but continue to run into the following migration error: 

```
yii\base\UnknownMethodException: Calling unknown method: craft\web\Application::getProjectConfig()

Migration: craft\migrations\m180521_173000_initial_yml_and_snapshot

Output:

> add column config mediumtext NULL DEFAULT NULL AFTER maintenance to table {{%info}} ... done (time: 0.043s)
> add column configMap mediumtext NULL DEFAULT NULL AFTER config to table {{%info}} ... done (time: 0.068s)
Exception: Calling unknown method: craft\web\Application::getProjectConfig() (/var/www/momster/vendor/yiisoft/yii2/base/Component.php:300)
#0 /var/www/momster/vendor/craftcms/cms/src/migrations/m180521_173000_initial_yml_and_snapshot.php(29): yii\base\Component->__call('getProjectConfi...', Array)
#1 /var/www/momster/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\m180521_173000_initial_yml_and_snapshot->safeUp()
#2 /var/www/momster/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#3 /var/www/momster/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m180521_173000_initial_yml_and_snapshot))
#4 /var/www/momster/vendor/craftcms/cms/src/services/Updates.php(207): craft\db\MigrationManager->up()
#5 /var/www/momster/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(519): craft\services\Updates->runMigrations(Array)
#6 /var/www/momster/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#7 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#8 /var/www/momster/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/momster/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/momster/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('migrate', Array)
#11 /var/www/momster/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#12 /var/www/momster/vendor/craftcms/cms/src/web/Application.php(284): yii\base\Module->runAction('updater/migrate', Array)
#13 /var/www/momster/vendor/craftcms/cms/src/web/Application.php(670): craft\web\Application->runAction('updater/migrate')
#14 /var/www/momster/vendor/craftcms/cms/src/web/Application.php(215): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#15 /var/www/momster/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /var/www/momster/public_html/index.php(20): yii\base\Application->run()
#17 {main}
```

**Comment by michtio** [comment]
@hegrobler the solution right now would be clearing your composer cache, rolling back the update, delete your vendor folder, and reupdate.
