### ISSUE TITLE
Exception: Changes to the project config are not possible while in read-only mode. 

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#4001]
### Description
When running migrations in our deploy script, Craft complains about config changes. I guess this is correct because the environment is production, but it's while doing migrations through the console.

Is there a way to let Craft now to run them anyway? Even though `allowAdminChanges` is disabled?

Stack trace:

```
./craft migrate/all
Yii Migration Tool (based on Yii v2.0.16.1)
    > add column expiryDate datetime AFTER `uri` to table {{%blitz_caches}} ... done (time: 0.055s)
    > create index blitz_caches_expiryDate_idx on {{%blitz_caches}} (expiryDate) ... done (time: 0.013s)
    > create table {{%blitz_cachetags}} ... done (time: 0.009s)
    > create index blitz_cachetags_tag_idx on {{%blitz_cachetags}} (tag) ... done (time: 0.006s)
    > add foreign key blitz_cachetags_cacheId_fk: {{%blitz_cachetags}} (cacheId) references {{%blitz_caches}} (id) ... done (time: 0.022s)
    > add column isArchived boolean NOT NULL DEFAULT FALSE AFTER `propagateNodes` to table {{%navigation_navs}} ... done (time: 0.048s)
    > add column dateArchived datetime AFTER `isArchived` to table {{%navigation_navs}} ... done (time: 0.041s)
    > create index navigation_navs_isArchived_idx on {{%navigation_navs}} (isArchived) ... done (time: 0.029s)
    > update in {{%elements_sites}} ... done (time: 0.004s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.002s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.004s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > update in {{%elements_sites}} ... done (time: 0.001s)
    > drop foreign key navigation_nodes_elementSiteId_fk from table navigation_nodes ... done (time: 0.003s)
    > drop column elementSiteId from table {{%navigation_nodes}} ... done (time: 0.047s)
    > add column dateDeleted datetime NULL DEFAULT NULL AFTER `dateUpdated` to table {{%navigation_navs}} ... done (time: 0.072s)
    > create index navigation_navs_dateDeleted_idx on {{%navigation_navs}} (dateDeleted) ... done (time: 0.011s)
    > add column deletedWithNav boolean NULL DEFAULT NULL AFTER `newWindow` to table {{%navigation_nodes}} ... done (time: 0.049s)
    > add column parentId integer AFTER `navId` to table {{%navigation_nodes}} ... done (time: 0.046s)
    > drop column isArchived from table {{%navigation_navs}} ... done (time: 0.299s)
    > drop column dateArchived from table {{%navigation_navs}} ... done (time: 0.053s)
Exception: Changes to the project config are not possible while in read-only mode. 
```

### Additional info

- Craft version: 3.1.18
- PHP version: 7.2

**Comment by brandonkelly** [comment]
That exception should only occur when a new change is introduced to the project config – not when simply syncing changes from a `project.yaml` file.

In this case, it looks like a Blitz plugin migration is the culprit. I’ve passed this along to Ben.

For posterity, all migrations that make changes to the project config should do so defensively, only if the plugin’s schema version in `project.yaml` indicates that the migration hasn’t already had a chance to make its changes on it. (See the [Project Config Migrations](https://docs.craftcms.com/v3/extend/project-config.html#project-config-migrations) section of the [Supporting Project Config](https://docs.craftcms.com/v3/extend/project-config.html) docs for more info.)

**Comment by putyourlightson** [comment]
Thanks @brandonkelly, fixed in Blitz 2.0.2 https://github.com/putyourlightson/craft-blitz/commit/247e4155870c82bb875ac5c6b4cb958da6880689

**Comment by brandonkelly** [comment]
Sorry, this is actually not a Blitz issue. It’s coming from whatever change follows this one:

```
drop column dateArchived from table {{%navigation_navs}}
```

Perhaps Verbb navigation, but it's hard to tell. The script could have moved onto another plugin after that.

@Rias500 Is there a full stack trace anywhere in the output?

**Comment by Rias500** [comment]
@brandonkelly Full stack change after the notice:

```
Exception: Changes to the project config are not possible while in read-only mode. (/var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/craftcms/cms/src/services/ProjectConfig.php:350)
#0 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/verbb/navigation/src/migrations/m190315_000000_project_config.php(21): craft\services\ProjectConfig->set('navigation.navs', Array)
#1 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/craftcms/cms/src/db/Migration.php(56): verbb\navigation\migrations\m190315_000000_project_config->safeUp()
#2 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#3 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(verbb\navigation\migrations\m190315_000000_project_config))
#4 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#5 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/craftcms/cms/src/console/controllers/MigrateController.php(252): craft\services\Updates->runMigrations(Array)
#6 [internal function]: craft\console\controllers\MigrateController->actionAll()
#7 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#10 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#11 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#12 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#13 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#14 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/craft(22): yii\base\Application->run()
#16 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Navigation.'
in /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/craftcms/cms/src/services/Updates.php:233
Stack trace:
#0 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/craftcms/cms/src/console/controllers/MigrateController.php(252): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#5 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#8 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /var/www/vhosts/wiese-europe.com.staging.php02.marblessite.be/httpdocs/craft(22): yii\base\Application->run()
#11 {main}
```

**Comment by Rias500** [comment]
Seems to be from Verbb navigation then

**Comment by brandonkelly** [comment]
Yeah

**Comment by engram-design** [comment]
Sorry @Rias500 ill get onto fixing that

**Comment by engram-design** [comment]
Should be fixed in https://github.com/verbb/navigation/commit/e69b1df4886151a2401f83a7ad819eefc66bbfeb @Rias500

**Comment by Rias500** [comment]
Thanks @engram-design!
