### ISSUE TITLE
Craft::$app->entryRevisions->getDraftById() fails when parent entry is (soft) deleted)

### ISSUE THREAD

**Issue by phoob** [craftcms/cms#4013]
### Description

When trying to get a draft, but the parent entry is marked as deleted, that triggers the following error: 

```
Argument 2 passed to craft\services\EntryRevisions::_configureRevisionWithEntryProperties() must be an instance of craft\elements\Entry, null given, called in /var/www/site/craft/vendor/craftcms/cms/src/services/EntryRevisions.php on line 104
```

### Additional info

- Craft version: 3.1.17.2
- PHP version: 7.2.15

Stack trace:

```
TypeError: Argument 2 passed to craft\services\EntryRevisions::_configureRevisionWithEntryProperties() must be an instance of craft\elements\Entry, null given, called in /var/www/site/craft/vendor/craftcms/cms/src/services/EntryRevisions.php on line 104
#18 /var/www/site/craft/vendor/craftcms/cms/src/services/EntryRevisions.php(573): craft\services\EntryRevisions::_configureRevisionWithEntryProperties
#17 /var/www/site/craft/vendor/craftcms/cms/src/services/EntryRevisions.php(104): craft\services\EntryRevisions::getDraftById
#16 /var/www/site/craft/modules/elasticsearchmodule/src/jobs/ElasticJob.php(60): modules\elasticsearchmodule\jobs\ElasticJob::modules\elasticsearchmodule\jobs\{closure}
#15 [internal](0): array_map
#14 /var/www/site/craft/modules/elasticsearchmodule/src/jobs/ElasticJob.php(64): modules\elasticsearchmodule\jobs\ElasticJob::execute
#13 /var/www/site/craft/vendor/yiisoft/yii2-queue/src/Queue.php(214): yii\queue\Queue::handleMessage
#12 /var/www/site/craft/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\cli\Queue::handleMessage
#11 /var/www/site/craft/vendor/craftcms/cms/src/queue/Queue.php(96): craft\queue\Queue::run
#10 /var/www/site/craft/vendor/putyourlightson/craft-campaign/src/console/controllers/SendoutsController.php(37): putyourlightson\campaign\console\controllers\SendoutsController::actionRunPendingSendouts
#9 [internal](0): call_user_func_array
#8 /var/www/site/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#7 /var/www/site/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Controller::runAction
#6 /var/www/site/craft/vendor/yiisoft/yii2/console/Controller.php(148): yii\console\Controller::runAction
#5 /var/www/site/craft/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Module::runAction
#4 /var/www/site/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\console\Application::runAction
#3 /var/www/site/craft/vendor/craftcms/cms/src/console/Application.php(93): craft\console\Application::runAction
#2 /var/www/site/craft/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application::handleRequest
#1 /var/www/site/craft/vendor/yiisoft/yii2/base/Application.php(386): yii\base\Application::run
#0 /var/www/site/craft/craft(27): null
```

**Comment by brandonkelly** [comment]
I wouldn’t expect drafts of soft-deleted entries to be accessible anywhere… how are you even accessing it? Programmatically?

**Comment by phoob** [comment]
Yes, I index all elements and drafts (including their content) to elasticsearch for later retrieval by the front end. On save and such, but I also have to run a “reindex all” command at regular intervals. There I have to get all drafts with a query I borrowed from _getAllDrafts (I think) in the entry revision service.

**Comment by brandonkelly** [comment]
Just updated `getDraftById()` and `getVersionById()` to return `null` if `getEntryById()` comes back as `null`, for the next release.

**Comment by phoob** [comment]
Thanks!
