### ISSUE TITLE
mysqldump fails on Windows hosted Nanobox environment

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#4031]
### Description

Any DB backup related action performed using `mysqldump` through Craft fails on my Nanobox environment. Nanobox by default doesn't include mysqldump, but I added it as a dev package, so it's available and in PATH. However this is the error I get when DB backup actions are attempted:

```
craft\errors\ShellCommandException: The shell command "mysqldump --defaults-extra-file="/app/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --single-transaction --no-data --result-file="/app/storage/backups/nottingham-college_190321_224042_ilbrntexmb_v3.1.19.sql" gonano && mysqldump --defaults-extra-file="/app/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --no-create-info --ignore-table=gonano.craft_assetindexdata --ignore-table=gonano.craft_assettransformindex --ignore-table=gonano.craft_sessions --ignore-table=gonano.craft_templatecaches --ignore-table=gonano.craft_templatecachequeries --ignore-table=gonano.craft_templatecacheelements --ignore-table=gonano.craft_cache --ignore-table=gonano.craft_templatecachecriteria gonano >> "/app/storage/backups/nottingham-college_190321_224042_ilbrntexmb_v3.1.19.sql"" failed with exit code 2: Warning: World-writable config file '/app/storage/runtime/temp/my.cnf' is ignored
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) when trying to connect in /app/vendor/craftcms/cms/src/db/Connection.php:581
Stack trace:
#0 /app/vendor/craftcms/cms/src/db/Connection.php(277): craft\db\Connection->_executeDatabaseShellCommand(Object(mikehaertl\shellcommand\Command))
#1 /app/vendor/craftcms/cms/src/db/Connection.php(239): craft\db\Connection->backupTo('/app/storage/ba...')
#2 /app/vendor/verbb/super-table/src/controllers/PluginController.php(42): craft\db\Connection->backup()
#3 [internal function]: verbb\supertable\controllers\PluginController->actionResaveFields()
#4 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /app/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('resave-fields', Array)
#7 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('resave-fields', Array)
#8 /app/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('super-table/plu...', Array)
#9 /app/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('super-table/plu...', Array)
#10 /app/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#11 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /app/web/index.php(21): yii\base\Application->run()
#13 {main}
```

What's interesting is:

```mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) when trying to connect```

Nanobox doesn't use a Unix socket, instead it connects via TCP/IP. This is configured in `config/db.php` and works fine for non Shell command actions i.e. Admin CP, but it doesn't appear the mysqldump command is using anything in the `db.php` file.

As an additional note, no `my.cnf` file is present at the path `storage/runtime/temp`. This is where Nanobox is ultimately pointing to a Windows FS mountpoint.

How can I get mysqldump to work correctly in a Nanobox environment?

### Steps to reproduce

1. Run Craft in a Nanobox environment hosted on Windows
2. Configure `boxfile.yml` with dev package mysql-client-5.6.39.25.22nb1 (or 5.7, depending on version)
3. Attempt DB backup through Admin CP, Utilities > Database backup
4. `mysqldump` command will fail.

### Additional info

- Craft version: 3.1.19
- PHP version: 7.1
- Database driver & version: MySQL 5.6

**Comment by jamesmacwhite** [comment]
```World-writable config file '/app/storage/runtime/temp/my.cnf'```

Seems to be suspect, this file looks like it's being auto-generated by the process, but the permissions on it, seem to suggest it's being ignored.

**Comment by jamesmacwhite** [comment]
I did some more testing on this. If I comment out: https://github.com/craftcms/cms/blob/develop/src/db/mysql/Schema.php#L325 and prevent Craft from writing the `my.cnf` file and instead replace it with my own `my.cnf` as read-only:

```
[client]                                                                                                                                                                                         user=nanobox                                                                                                                                                                                     password=**********                                                                                                                                                                             host=172.21.0.10                                                                                                                                                                                 port=3306
```

This works, however, I then trip on an additional Windows related issue which I reported in #3990. Where the `unlink()` call fails and throws an error from Yii. If I was to remove the three lines below, everything then works.

https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFileHelper.php#L406-L408

I believe, it's because of the fact the environment Craft is running in Unix based (nanobox) but underlying share of the app/storage folders are on a Windows FS. My PHP directory separator is `/` because ultimately PHP is running on Linux.

I think this is possibly crossing over to being partly a Yii issue, but I'm no expert!

**Comment by jamesmacwhite** [comment]
This is going very deep I hope the information is useful for someone else if they ever have the pleasure of going through the same pain I have!

Ultimately, it looks like the errors are down to the fact that my Nanobox mount is using the built in VirtualBox driver. The `netfs` mount type is better, but I've had problems using that since day one, and just gave up and used the native option. However, I did finally get it working after figuring out why it always failed (SMBv1!!!!!!!!!!) and when running under this mount type, all the FS related issues go away.
