### ISSUE TITLE
Date input value is now required

### ISSUE THREAD

**Issue by ccchapman** [craftcms/cms#4063]
### Description

Before Craft CMS 3.1.20, passing a value to the date form input was optional (as it used null-coalescing.)

As of https://github.com/craftcms/cms/commit/ed7878596157804cd40e485ffccfa620278d395f, an error occurs when including this template w/o a value.

Related:

- https://github.com/craftcms/cms/issues/4041
- https://github.com/solspace/craft3-calendar/blob/c3ac0ef2abef956ffff0c06dffd74de43eccab5d/src/templates/view/calendar.html#L28

### Steps to reproduce

1. Installation of Craft CMS 3.1.19 with Solspace Calendar 2.0.17
2. Update to Craft CMS 3.1.20
3. View /admin/calendar/view/month

```
Twig\Error\RuntimeError: Variable "value" does not exist. in /home/vagrant/app/vendor/craftcms/cms/src/templates/_includes/forms/date.html:3
Stack trace:
#0 /home/vagrant/app/storage/runtime/compiled_templates/0b/0b871adeda252194405a6e35459a39e50a33c2bdb8b5c4c5a45e45ade858e4b6.php(39): __TwigTemplate_c14e7617ffef2a8b734fb10ba33835fb760c87bcc057bfc37cf85f9ea1b9daf3->{closure}()
#1 /home/vagrant/app/vendor/twig/twig/src/Template.php(379): __TwigTemplate_c14e7617ffef2a8b734fb10ba33835fb760c87bcc057bfc37cf85f9ea1b9daf3->doDisplay(Array, Array)
#2 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#3 /home/vagrant/app/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#4 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#5 /home/vagrant/app/storage/runtime/compiled_templates/14/14ae71924f7301a8068512b8c095461cb91f42a39b64396f64edf75fb644f328.php(305): craft\web\twig\Template->display(Array)
#6 /home/vagrant/app/storage/runtime/compiled_templates/42/424ca61c715653543e0b4cde792973f6ecdf97b5265be00e1671cb9554edb804.php(326): __TwigTemplate_dda498a764261d7faf06638d96e23cd70ae775543c97befaa11bb6d0b7bf85f2->macro_date(Array)
#7 /home/vagrant/app/storage/runtime/compiled_templates/42/424ca61c715653543e0b4cde792973f6ecdf97b5265be00e1671cb9554edb804.php(127): __TwigTemplate_25feb190c1725ee62aa9169289f91313d09678908c5bfb1e92d7a341931a44c0->macro_dateTimeField('startDate', 'Start Date', 'M d, Y', 'h:mm:s tt')
#8 /home/vagrant/app/vendor/twig/twig/src/Template.php(184): __TwigTemplate_25feb190c1725ee62aa9169289f91313d09678908c5bfb1e92d7a341931a44c0->block_content(Array, Array)
#9 /home/vagrant/app/storage/runtime/compiled_templates/fa/fa5bd811c2bb90060036ed0772a51ba7af65f74cf39224a0cb99c872729b2a2e.php(660): Twig\Template->displayBlock('content', Array, Array)
#10 /home/vagrant/app/vendor/twig/twig/src/Template.php(184): __TwigTemplate_eacca64f9650edd4976581c2ba802a7271db8bdb19d76fcd7a9f31de02a8dcf1->block_main(Array, Array)
#11 /home/vagrant/app/storage/runtime/compiled_templates/fa/fa5bd811c2bb90060036ed0772a51ba7af65f74cf39224a0cb99c872729b2a2e.php(545): Twig\Template->displayBlock('main', Array, Array)
#12 /home/vagrant/app/vendor/twig/twig/src/Template.php(184): __TwigTemplate_eacca64f9650edd4976581c2ba802a7271db8bdb19d76fcd7a9f31de02a8dcf1->block_body(Array, Array)
#13 /home/vagrant/app/storage/runtime/compiled_templates/a4/a4573d00fefb53d10d3c401edcfb98b61863001e0ce1cc7a07273a3218fdb5e8.php(72): Twig\Template->displayBlock('body', Array, Array)
#14 /home/vagrant/app/vendor/twig/twig/src/Template.php(379): __TwigTemplate_1220484c040c44b8e4721eadc1e8eec387f239905948cc9747aa58d2bd16fab9->doDisplay(Array, Array)
#15 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /home/vagrant/app/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#17 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#18 /home/vagrant/app/storage/runtime/compiled_templates/63/6368fa68ec06f1bc82247132e6bb33966b9d4e5c6f39229217fd7f98a508d220.php(52): craft\web\twig\Template->display(Array, Array)
#19 /home/vagrant/app/vendor/twig/twig/src/Template.php(379): __TwigTemplate_77e395c05fc0a6a9bf55d9be61562ace8ffb06ba9b6fd9a4720d3766b5470a2d->doDisplay(Array, Array)
#20 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /home/vagrant/app/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#22 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#23 /home/vagrant/app/storage/runtime/compiled_templates/fa/fa5bd811c2bb90060036ed0772a51ba7af65f74cf39224a0cb99c872729b2a2e.php(107): craft\web\twig\Template->display(Array, Array)
#24 /home/vagrant/app/vendor/twig/twig/src/Template.php(379): __TwigTemplate_eacca64f9650edd4976581c2ba802a7271db8bdb19d76fcd7a9f31de02a8dcf1->doDisplay(Array, Array)
#25 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /home/vagrant/app/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#27 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#28 /home/vagrant/app/storage/runtime/compiled_templates/3f/3fc2c493f6e0b6d52a387794d3edf6971b15bcdc4050d323b390f2115eab3f7f.php(44): craft\web\twig\Template->display(Array, Array)
#29 /home/vagrant/app/vendor/twig/twig/src/Template.php(379): __TwigTemplate_99cf4b8a7f0bcdd60d94c0bb04aab4afaab05ca997c66ffd35b62d9a538d2e87->doDisplay(Array, Array)
#30 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#31 /home/vagrant/app/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#32 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#33 /home/vagrant/app/storage/runtime/compiled_templates/42/424ca61c715653543e0b4cde792973f6ecdf97b5265be00e1671cb9554edb804.php(56): craft\web\twig\Template->display(Array, Array)
#34 /home/vagrant/app/vendor/twig/twig/src/Template.php(379): __TwigTemplate_25feb190c1725ee62aa9169289f91313d09678908c5bfb1e92d7a341931a44c0->doDisplay(Array, Array)
#35 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#36 /home/vagrant/app/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#37 /home/vagrant/app/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#38 /home/vagrant/app/vendor/twig/twig/src/Template.php(364): craft\web\twig\Template->display(Array)
#39 /home/vagrant/app/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#40 /home/vagrant/app/vendor/twig/twig/src/Environment.php(319): Twig\TemplateWrapper->render(Array)
#41 /home/vagrant/app/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('calendar/view/c...', Array)
#42 /home/vagrant/app/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('calendar/view/c...', Array)
#43 /home/vagrant/app/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('calendar/view/c...', Array)
#44 /home/vagrant/app/vendor/solspace/craft3-calendar/src/Controllers/ViewController.php(128): craft\web\Controller->renderTemplate('calendar/view/c...', Array)
#45 [internal function]: Solspace\Calendar\Controllers\ViewController->actionTargetTime('month', NULL, NULL, NULL)
#46 /home/vagrant/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#47 /home/vagrant/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#48 /home/vagrant/app/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('target-time', Array)
#49 /home/vagrant/app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('target-time', Array)
#50 /home/vagrant/app/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('calendar/view/t...', Array)
#51 /home/vagrant/app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('calendar/view/t...', Array)
#52 /home/vagrant/app/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#53 /home/vagrant/app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#54 /home/vagrant/app/web/index.php(21): yii\base\Application->run()
#55 {main}
```

### Additional info

- Craft version: 3.1.20
- Plugins & versions: solspace/craft3-calendar 2.0.17

**Comment by brandonkelly** [comment]
Thanks for pointing that out. Just released 3.1.20.1 with a fix for this.
