### ISSUE TITLE
Unknown Errors in CP

### ISSUE THREAD

**Issue by loshose** [craftcms/cms#4092]
### Description
I get random "Unknown Errors" in CP. Mostly it seems to happen if I've left the browser idle for a while.

Browser console says error 500 for "admin/actions/element-indexes/get-elements", and in web.log I have at least these errors:

```
2019-04-03 15:42:55 [-][15][-][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: Unable to verify your data submission. in C:\sitepath\craft\vendor\yiisoft\yii2\web\Controller.php:166
Stack trace:
#0 C:\sitepath\craft\vendor\craftcms\cms\src\web\Controller.php(88): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 C:\sitepath\craft\vendor\craftcms\cms\src\controllers\ElementIndexesController.php(79): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#2 C:\sitepath\craft\vendor\yiisoft\yii2\base\Controller.php(155): craft\controllers\ElementIndexesController->beforeAction(Object(yii\base\InlineAction))
#3 C:\sitepath\craft\vendor\craftcms\cms\src\web\Controller.php(109): yii\base\Controller->runAction('get-elements', Array)
#4 C:\sitepath\craft\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('get-elements', Array)
#5 C:\sitepath\craft\vendor\craftcms\cms\src\web\Application.php(297): yii\base\Module->runAction('element-indexes...', Array)
#6 C:\sitepath\craft\vendor\craftcms\cms\src\web\Application.php(561): craft\web\Application->runAction('element-indexes...', Array)
#7 C:\sitepath\craft\vendor\craftcms\cms\src\web\Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 C:\sitepath\craft\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 C:\sitepath\index.php(21): yii\base\Application->run()
#10 {main}
2019-04-03 15:42:54 [-][15][-][info][application] $_GET = [
    'p' => 'admin/actions/element-indexes/get-elements'
]
```

and

```
Next Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Unsupported DB driver value: "). in C:\sitepath\craft\vendor\craftcms\cms\src\templates\_layouts\base.html:5
Stack trace:
#0 C:\sitepath\craft\vendor\craftcms\cms\src\web\twig\Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#1 C:\sitepath\craft\vendor\twig\twig\src\Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#2 C:\sitepath\craft\vendor\craftcms\cms\src\web\twig\Template.php(34): Twig\Template->display(Array, Array)
#3 C:\sitepath\craft\storage\runtime\compiled_templates\ea\ea9a5ebddf0e05f59a44d54885e88b6a30d06cf4be90a06b0ea3dc65b585b95a.php(45): craft\web\twig\Template->display(Array, Array)
#4 C:\sitepath\craft\vendor\twig\twig\src\Template.php(379): __TwigTemplate_af139ab34c19f42361237fc3168509a09695d90b157abded2c24468d0cd8e01d->doDisplay(Array, Array)
#5 C:\sitepath\craft\vendor\craftcms\cms\src\web\twig\Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#6 C:\sitepath\craft\vendor\twig\twig\src\Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#7 C:\sitepath\craft\vendor\craftcms\cms\src\web\twig\Template.php(34): Twig\Template->display(Array, Array)
#8 C:\sitepath\craft\storage\runtime\compiled_templates\a4\a4fd84312dee71d4aa4a2be5db97d723070e6606f8bb643e4632d9e0eb1b584c.php(43): craft\web\twig\Template->display(Array, Array)
#9 C:\sitepath\craft\vendor\twig\twig\src\Template.php(379): __TwigTemplate_3b4e8884d8048284b737ca4b97eca5d9cdbcd2fbaeae1b1de15e6eabe8a80a1b->doDisplay(Array, Array)
#10 C:\sitepath\craft\vendor\craftcms\cms\src\web\twig\Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#11 C:\sitepath\craft\vendor\twig\twig\src\Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 C:\sitepath\craft\vendor\craftcms\cms\src\web\twig\Template.php(34): Twig\Template->display(Array, Array)
#13 C:\sitepath\craft\vendor\twig\twig\src\Template.php(364): craft\web\twig\Template->display(Array)
#14 C:\sitepath\craft\vendor\twig\twig\src\TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#15 C:\sitepath\craft\vendor\twig\twig\src\Environment.php(319): Twig\TemplateWrapper->render(Array)
#16 C:\sitepath\craft\vendor\craftcms\cms\src\web\View.php(343): Twig\Environment->render('503', Array)
#17 C:\sitepath\craft\vendor\craftcms\cms\src\web\View.php(393): craft\web\View->renderTemplate('503', Array)
#18 C:\sitepath\craft\vendor\craftcms\cms\src\web\Controller.php(161): craft\web\View->renderPageTemplate('503', Array)
#19 C:\sitepath\craft\vendor\craftcms\cms\src\controllers\TemplatesController.php(229): craft\web\Controller->renderTemplate('503', Array)
#20 [internal function]: craft\controllers\TemplatesController->actionRenderError()
#21 C:\sitepath\craft\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#22 C:\sitepath\craft\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#23 C:\sitepath\craft\vendor\craftcms\cms\src\web\Controller.php(109): yii\base\Controller->runAction('render-error', Array)
#24 C:\sitepath\craft\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('render-error', Array)
#25 C:\sitepath\craft\vendor\craftcms\cms\src\web\Application.php(297): yii\base\Module->runAction('templates/rende...', Array)
#26 C:\sitepath\craft\vendor\yiisoft\yii2\web\ErrorHandler.php(108): craft\web\Application->runAction('templates/rende...')
#27 C:\sitepath\craft\vendor\craftcms\cms\src\web\ErrorHandler.php(137): yii\web\ErrorHandler->renderException(Object(craft\web\ServiceUnavailableHttpException))
#28 C:\sitepath\craft\vendor\yiisoft\yii2\base\ErrorHandler.php(111): craft\web\ErrorHandler->renderException(Object(craft\web\ServiceUnavailableHttpException))
#29 C:\sitepath\craft\vendor\craftcms\cms\src\web\ErrorHandler.php(68): yii\base\ErrorHandler->handleException(Object(craft\web\ServiceUnavailableHttpException))
#30 [internal function]: craft\web\ErrorHandler->handleException(Object(craft\web\ServiceUnavailableHttpException))
#31 {main}
2019-04-03 12:34:04 [-][-][b85e789260b6aa675de67da81e79ed20][info][application] $_GET = [
    'p' => 'admin/actions/element-indexes/get-elements'
]
```

and

```
2019-04-03 12:37:43 [-][-][-][error][craft\base\ApplicationTrait::getIsDbConnectionValid] There was a problem connecting to the database: Unsupported DB driver value: 
2019-04-03 12:37:43 [-][-][-][info][yii\web\Session::open] Session started
2019-04-03 12:37:43 [-][-][-][error][yii\web\HttpException:503] craft\web\ServiceUnavailableHttpException: Craft isn’t installed yet. in C:\sitepath\craft\vendor\craftcms\cms\src\web\Application.php:539
Stack trace:
#0 C:\sitepath\craft\vendor\craftcms\cms\src\web\Application.php(187): craft\web\Application->_processInstallRequest(Object(craft\web\Request))
#1 C:\sitepath\craft\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#2 C:\sitepath\index.php(21): yii\base\Application->run()
#3 {main}
2019-04-03 12:37:43 [-][-][-][profile begin][craft\web\View::renderTemplate] 503
2019-04-03 12:37:43 [-][-][-][profile begin][craft\web\twig\Environment::compileSource] 503
2019-04-03 12:37:43 [-][-][-][profile end][craft\web\twig\Environment::compileSource] 503
2019-04-03 12:37:43 [-][-][-][profile begin][craft\web\twig\Environment::compileSource] _layouts/message
2019-04-03 12:37:43 [-][-][-][profile end][craft\web\twig\Environment::compileSource] _layouts/message
2019-04-03 12:37:43 [-][-][-][profile begin][craft\web\twig\Environment::compileSource] _layouts/base
2019-04-03 12:37:43 [-][-][-][profile end][craft\web\twig\Environment::compileSource] _layouts/base
2019-04-03 12:37:43 [-][-][-][profile begin][craft\web\twig\Template::display] 503
2019-04-03 12:37:43 [-][-][-][profile begin][craft\web\twig\Template::display] _layouts/message
2019-04-03 12:37:43 [-][-][-][profile begin][craft\web\twig\Template::display] _layouts/base
2019-04-03 12:37:43 [-][-][-][info][application] $_GET = [
    'p' => 'admin/categories'
]
```

I dont understand why it's complaining about the "Unsupported DB driver value:" without even showing the value. I looked at the source code, and it's supposed to show the value but in the error message the DB driver is empty.

Also the "Craft isn’t installed yet" is frequently shown in web.log.

### Steps to reproduce

1. Navigate to "Entries"
2. "Unknown Error" pops up, entries list is blank

Way to fix it is to navigate somewhere else, ie. "Assets", and then back to "Entries".

### Additional info

- Craft version: Craft Pro 3.1.19
- PHP version: 7.3.3
- Database driver & version: mysql, MariaDB 10
- Plugins & versions: Cache Flag 1.0.3, Child Me 1.0.4, Contact Form 2.2.3, Contact Form Extensions 1.1.1, Cookies 1.1.11, Imager 2.1.7, Position Fieldtype 1.0.14, Redactor 2.3.2
- Browsers: Chrome and Firefox

Site has been installed from scratch using composer. Host is Windows 2012 R2.

.env-file has:
```
# The database driver that will be used ('mysql' or 'pgsql')
DB_DRIVER="mysql"
```

config\db.php  has:
```
return [
    'driver' => getenv('DB_DRIVER'),
    'server' => getenv('DB_SERVER'),
    'user' => getenv('DB_USER'),
    'password' => getenv('DB_PASSWORD'),
    'database' => getenv('DB_DATABASE'),
    'schema' => getenv('DB_SCHEMA'),
    'tablePrefix' => getenv('DB_TABLE_PREFIX'),
    'port' => getenv('DB_PORT')
];
```

**Comment by loshose** [comment]
I also noticed:

```
2019-04-04 10:00:54 [-][-][d68feb9d49084a712dcb308088627c14][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: craft\web\Request::cookieValidationKey must be configured with a secret key. in ...\craft\vendor\yiisoft\yii2\web\Request.php:1579
```

I'm having an idea this might have to do something with getenv-function? Google has some mentions of getenv not always working on Apache.

I've now replaced all mentions of getenv in the config-files and replaced them with the actual config parameters.

I'll report back if this helps.

**Comment by loshose** [comment]
Well, after changing the getenv calls to the actual config parameters, and changing variables_order in php.ini from "GPCS" to "EGPCS", we're not getting the same errors anymore. I guess either one of those changes would have been enough.

So - not a bug in Craft CMS, but rather a configuration issue due to the use of get_env() in combination with the php.ini default production value "GPCS".

I don't know if Craft should detect the "variables_order" or maybe you should add a mention in the install instructions?

Hopefully this will help any fellow Crafters in the future.
