### ISSUE TITLE
Installation of missing plugins fails

### ISSUE THREAD

**Issue by dwhoban** [craftcms/cms#4140]
### Description
I am building a new version of an existing site.  After activating the Existing license (Pro) the plugin screen shows the "missing" plugins related to that account. Installation is currently failing.

### Steps to reproduce

1. Add license.key to ./config folder
2. Reactivate Pro license
3. Navigate to Settings > Plugins
4. Click on settings dropdown and select Install fo missing plugin.

### Additional info

- Craft version: 3.1.22
- PHP version: 7.2.14
- Database driver & version: 15.1 Distrib 10.3.14-MariaDB
- Plugins & versions: none

### Error Log
 ```
yii\web\BadRequestHttpException: Request missing required body param in /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/web/Request.php:612
Stack trace:
#0 /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/controllers/pluginstore/InstallController.php(147): craft\web\Request->getRequiredBodyParam('edition')
#1 /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(104): craft\controllers\pluginstore\InstallController->initialData()
#2 [internal function]: craft\controllers\BaseUpdaterController->actionIndex()
#3 /home/vagrant/sites/allinseason.com.au/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /home/vagrant/sites/allinseason.com.au/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('', Array)
#6 /home/vagrant/sites/allinseason.com.au/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('', Array)
#7 /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('pluginstore/ins...', Array)
#8 /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('pluginstore/ins...', Array)
#9 /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /home/vagrant/sites/allinseason.com.au/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /home/vagrant/sites/allinseason.com.au/web/index.php(21): yii\base\Application->run()
#12 {main}
```

**Comment by dwhoban** [comment]
Also when clicking "Install" from the plugin store, the license key for that plugin disappears and needs to be re-typed into the field

**Comment by brandonkelly** [comment]
Thanks for reporting @dwhoban. Already fixed for the next release, but it was caught without a GH issue for it, so the release note is now linking here in case anyone wants more context.

**Comment by dwhoban** [comment]
Thanks @brandonkelly - knew you were on it
