### ISSUE TITLE
[3.2] Integrity constraint violation while creating an entry

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#4363]
### Description
I brought this up on Discord, but investigated a little further afterwards. Turns out, this scenario occurs in multi-site installs. I was able to reproduce it multiple times.

### Steps to reproduce

1. Create a fresh install of Craft
2. Create a new site, you can leave everything as defaults
3. Create a new section, leave everything as default. (I created one called blog, it generated the default URIs)
4. Try to create an entry
5. Receive the following stacktrace:

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'dabb2b4a-b83c-41e3-b48e-16e0b94d8824' for key 'craft_elements_uid_unq_idx' in /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/Command.php:1290
Stack trace:
#0 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute()
#1 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('UPDATE `craft_e...')
#2 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/ActiveRecord.php(332): yii\db\Command->execute()
#3 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/BaseActiveRecord.php(810): yii\db\ActiveRecord::updateAll(Array, Array)
#4 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/ActiveRecord.php(676): yii\db\BaseActiveRecord->updateInternal(NULL)
#5 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/BaseActiveRecord.php(681): yii\db\ActiveRecord->update(false, NULL)
#6 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/services/Elements.php(563): yii\db\BaseActiveRecord->save(false)
#7 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/services/Elements.php(952): craft\services\Elements->saveElement(Object(craft\elements\Entry), false, false)
#8 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/services/Revisions.php(163): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#9 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/elements/Entry.php(1203): craft\services\Revisions->createRevision(Object(craft\elements\Entry), '1', NULL)
#10 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/services/Elements.php(642): craft\elements\Entry->afterPropagate(true)
#11 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/controllers/EntriesController.php(146): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#12 [internal function]: craft\controllers\EntriesController->actionCreateEntry(Object(craft\models\Section), Object(craft\models\Site))
#13 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/web/Controller.php(186): yii\base\Controller->runAction('create-entry', Array)
#16 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('create-entry', Array)
#17 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/web/Application.php(298): yii\base\Module->runAction('entries/create-...', Array)
#18 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/create-...', Array)
#19 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/web/Application.php(283): yii\web\Application->handleRequest(Object(craft\web\Request))
#20 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /Users/ransom/Projects/Work/craft3-plugindev/web/index.php(22): yii\base\Application->run()
#22 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'dabb2b4a-b83c-41e3-b48e-16e0b94d8824' for key 'craft_elements_uid_unq_idx'
The SQL being executed was: UPDATE `craft_elements` SET `revisionId`=1, `enabled`=0, `archived`=0, `dateUpdated`='2019-06-05 12:48:03', `uid`='dabb2b4a-b83c-41e3-b48e-16e0b94d8824' WHERE `id`=3 in /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'UPDATE `craft_e...')
#1 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('UPDATE `craft_e...')
#2 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/ActiveRecord.php(332): yii\db\Command->execute()
#3 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/BaseActiveRecord.php(810): yii\db\ActiveRecord::updateAll(Array, Array)
#4 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/ActiveRecord.php(676): yii\db\BaseActiveRecord->updateInternal(NULL)
#5 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/db/BaseActiveRecord.php(681): yii\db\ActiveRecord->update(false, NULL)
#6 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/services/Elements.php(563): yii\db\BaseActiveRecord->save(false)
#7 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/services/Elements.php(952): craft\services\Elements->saveElement(Object(craft\elements\Entry), false, false)
#8 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/services/Revisions.php(163): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#9 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/elements/Entry.php(1203): craft\services\Revisions->createRevision(Object(craft\elements\Entry), '1', NULL)
#10 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/services/Elements.php(642): craft\elements\Entry->afterPropagate(true)
#11 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/controllers/EntriesController.php(146): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#12 [internal function]: craft\controllers\EntriesController->actionCreateEntry(Object(craft\models\Section), Object(craft\models\Site))
#13 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/web/Controller.php(186): yii\base\Controller->runAction('create-entry', Array)
#16 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('create-entry', Array)
#17 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/web/Application.php(298): yii\base\Module->runAction('entries/create-...', Array)
#18 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/create-...', Array)
#19 /Users/ransom/Projects/Work/craft3-plugindev/vendor/craftcms/cms/src/web/Application.php(283): yii\web\Application->handleRequest(Object(craft\web\Request))
#20 /Users/ransom/Projects/Work/craft3-plugindev/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /Users/ransom/Projects/Work/craft3-plugindev/web/index.php(22): yii\base\Application->run()
#22 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry 'dabb2b4a-b83c-41e3-b48e-16e0b94d8824' for key 'craft_elements_uid_unq_idx'
)
```

Here is the full relevant log excerpt:
https://gist.github.com/Mosnar/e88117ca9e89cfb5ea481a2317352e21

### Additional info

- Craft version: 3.2 Beta 1
- PHP version: 7.2.13
- Database driver & version: MySQL 5.7.23
- Plugins & versions: N/A

**Update**
I updated to 3.2-dev and it seems to be fixed, so I suppose this ticket can be closed out.

**Update x2**
I take it back, still not fixed.

**Comment by brandonkelly** [comment]
Just fixed this for the next release, thanks for reporting!
