### ISSUE TITLE
[3.2] Matrix block is missing its owner ID

### ISSUE THREAD

**Issue by rinusvandam** [craftcms/cms#4429]
### Description

When saving an entry with a filled matrix field I get the following error: “matrix block is missing its owner ID”. When leaving the matrix field empty and save the entry everything works fine.

#### In the web.log it says:

`2019-06-21 06:51:14 [-][1][ni0moa5mdl92splg7l4fclbl48][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 73 in /sites/sitename/craft/vendor/craftcms/cms/src/elements/MatrixBlock.php:286`

#### Full trace: 

```
#0 /sites/sitename/craft/vendor/craftcms/cms/src/helpers/ElementHelper.php(302): craft\elements\MatrixBlock->getOwner()
#1 /sites/sitename/craft/vendor/craftcms/cms/src/helpers/ElementHelper.php(316): craft\helpers\ElementHelper::rootElement(Object(craft\elements\MatrixBlock))
#2 /sites/sitename/craft/vendor/craftcms/cms/src/services/Elements.php(632): craft\helpers\ElementHelper::isDraftOrRevision(Object(craft\elements\MatrixBlock))
#3 /sites/sitename/craft/vendor/craftcms/cms/src/services/Elements.php(960): craft\services\Elements->saveElement(Object(craft\elements\MatrixBlock), false, false)
#4 /sites/sitename/craft/vendor/craftcms/cms/src/services/Matrix.php(771): craft\services\Elements->duplicateElement(Object(craft\elements\MatrixBlock), Array)
#5 /sites/sitename/craft/vendor/craftcms/cms/src/fields/Matrix.php(774): craft\services\Matrix->saveField(Object(craft\fields\Matrix), Object(craft\elements\Entry))
#6 /sites/sitename/craft/vendor/craftcms/cms/src/base/Element.php(2050): craft\fields\Matrix->afterElementSave(Object(craft\elements\Entry), true)
#7 /sites/sitename/craft/vendor/craftcms/cms/src/elements/Entry.php(1193): craft\base\Element->afterSave(true)
#8 /sites/sitename/craft/vendor/craftcms/cms/src/services/Elements.php(629): craft\elements\Entry->afterSave(true)
#9 /sites/sitename/craft/vendor/craftcms/cms/src/services/Elements.php(906): craft\services\Elements->saveElement(Object(craft\elements\Entry), true, false)
#10 /sites/sitename/craft/vendor/craftcms/cms/src/services/Revisions.php(163): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#11 /sites/sitename/craft/vendor/craftcms/cms/src/elements/Entry.php(1203): craft\services\Revisions->createRevision(Object(craft\elements\Entry), '1', 'Applied \xE2\x80\x9CDraf...')
#12 /sites/sitename/craft/vendor/craftcms/cms/src/services/Elements.php(967): craft\elements\Entry->afterPropagate(false)
#13 /sites/sitename/craft/vendor/craftcms/cms/src/services/Drafts.php(237): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#14 /sites/sitename/craft/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(372): craft\services\Drafts->applyDraft(Object(craft\elements\Entry))
#15 [internal function]: craft\controllers\EntryRevisionsController->actionPublishDraft()
#16 /sites/sitename/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /sites/sitename/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#18 /sites/sitename/craft/vendor/craftcms/cms/src/web/Controller.php(186): yii\base\Controller->runAction('publish-draft', Array)
#19 /sites/sitename/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('publish-draft', Array)
#20 /sites/sitename/craft/vendor/craftcms/cms/src/web/Application.php(298): yii\base\Module->runAction('entry-revisions...', Array)
#21 /sites/sitename/craft/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('entry-revisions...', Array)
#22 /sites/sitename/craft/vendor/craftcms/cms/src/web/Application.php(277): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#23 /sites/sitename/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#24 /sites/sitename/web/index.php(21): yii\base\Application->run()
#25 {main}
```

### Steps to reproduce

1. Add a matrix field to an entry
2. Edit the entry and fill in the matrix field
3. Hit save entry

### Additional info

- Craft version: Craft Pro 3.2.0-beta.3
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Plugins & versions: No plugins are enabled.

**Comment by brandonkelly** [comment]
Try updating Craft to 6e8c5b41fd744f92070cad474c6a2f2aac074673, and see if that fixes it.

To do that, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.2.x-dev#6e8c5b41fd744f92070cad474c6a2f2aac074673 as 3.2.0-beta.3",
  "...": "..."
}
```

Then run `composer update`.

If you’re still seeing this error, please send your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com.

**Comment by rinusvandam** [comment]
Thanks Brandon. The update fixed it.

**Comment by brandonkelly** [comment]
@rinusvandam Sweet! Were you seeing the error on a multi-site Craft install as well?

**Comment by rinusvandam** [comment]
Yes, the site is a multi-site Craft install.

**Comment by anchovy** [comment]
@brandonkelly I'm having the same issue:

`2021-04-14 15:19:03 [-][1][kn8kjibskv0qt0lol0l5drrksn][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 84613 in /home/forge/SITE/vendor/craftcms/cms/src/elements/MatrixBlock.php:311
`

PHP version: 7.4.14
Craft Pro 3.5.19.1
Database driver & version: MySQL 8.0.23
Yii version: 2.0.38

```
Stack trace:
#0 /home/forge/SITE/vendor/nav33d/craft-relations/src/services/Relations.php(55): craft\elements\MatrixBlock->getOwner()
#1 /home/forge/SITE/vendor/nav33d/craft-relations/src/fields/Relations.php(51): nav33d\relations\services\Relations->get()
#2 /home/forge/SITE/vendor/craftcms/cms/src/base/Element.php(3345): nav33d\relations\fields\Relations->normalizeValue()
#3 /home/forge/SITE/vendor/craftcms/cms/src/base/Element.php(2658): craft\base\Element->normalizeFieldValue()
#4 /home/forge/SITE/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(240): craft\base\Element->getFieldValue()
#5 /home/forge/SITE/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(202): craft\fieldlayoutelements\CustomField->inputHtml()
#6 /home/forge/SITE/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(227): craft\fieldlayoutelements\BaseField->formHtml()
#7 /home/forge/SITE/vendor/craftcms/cms/src/models/FieldLayout.php(476): craft\fieldlayoutelements\CustomField->formHtml()
#8 /home/forge/SITE/vendor/craftcms/cms/src/controllers/CategoriesController.php(708): craft\models\FieldLayout->createForm()
#9 /home/forge/SITE/vendor/craftcms/cms/src/controllers/CategoriesController.php(260): craft\controllers\CategoriesController->_prepEditCategoryVariables()
#10 [internal function]: craft\controllers\CategoriesController->actionEditCategory()
#11 /home/forge/SITE/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#12 /home/forge/SITE/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#13 /home/forge/SITE/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#14 /home/forge/SITE/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#15 /home/forge/SITE/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#16 /home/forge/SITE/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#17 /home/forge/SITE/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest()
#18 /home/forge/SITE/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#19 /home/forge/SITE/web/index.php(21): yii\base\Application->run()
#20 {main}
```

**Comment by brandonkelly** [comment]
@anchovy Per your stack trace, that error is coming from the [Relations](https://plugins.craftcms.com/relations) plugin, which is marked as abandoned. The developer suggests using [Reverse Relations](https://plugins.craftcms.com/reverserelations) instead.

**Comment by anchovy** [comment]
@brandonkelly awesome - thanks. disabled and worked a treat... you've also taught me how to interpret a stacktrace!
