### ISSUE TITLE
Error in query after updating forked repo

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#4432]
### Description

FYI; I am running my local dev-install of Craft on my Git forked repository. So I can fix bugs when I found them (not often ;-)).
I use this install to develop generic plugins etc.
To stay up to date I update my fork everytime when I start working with my dev-install.

Something went terribly wrong when I update to the latest upstream version. See this stack trace;
I tried switching develop/master, a re-install (re-created the database) and I even removed my fork and re-forked to avoid any issues with the upstream merge.
Nothing helped, still getting this. Hope you can help me! Thanks.

```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`id`, `elements`.`fieldLayoutId` AS `elements`.`fieldLayoutId`, `elements`.`uid' at line 1 in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1290
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT `users`....')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /var/www/_git/craft-v3/src/db/Query.php(178): yii\db\Query->one(NULL)
#5 /var/www/_git/craft-v3/src/elements/db/ElementQuery.php(1220): craft\db\Query->one(NULL)
#6 /var/www/_git/craft-v3/src/elements/User.php(366): craft\elements\db\ElementQuery->one()
#7 /var/www/html/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity(1)
#8 /var/www/_git/craft-v3/src/web/User.php(491): yii\web\User->renewAuthStatus()
#9 /var/www/html/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#10 /var/www/html/vendor/yiisoft/yii2/web/User.php(360): yii\web\User->getIdentity()
#11 /var/www/_git/craft-v3/src/web/User.php(193): yii\web\User->getIsGuest()
#12 /var/www/_git/craft-v3/src/web/Application.php(259): craft\web\User->getIsGuest()
#13 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#14 /var/www/html/web/index.php(23): yii\base\Application->run()
#15 {main}

Next yii\db\Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`id`, `elements`.`fieldLayoutId` AS `elements`.`fieldLayoutId`, `elements`.`uid' at line 1
The SQL being executed was: SELECT `users`.`password`, `elements`.`id` AS `elements`.`id`, `elements`.`fieldLayoutId` AS `elements`.`fieldLayoutId`, `elements`.`uid` AS `elements`.`uid`, `elements`.`enabled` AS `elements`.`enabled`, `elements`.`archived` AS `elements`.`archived`, `elements`.`dateCreated` AS `elements`.`dateCreated`, `elements`.`dateUpdated` AS `elements`.`dateUpdated`, `elements_sites`.`slug` AS `elements_sites`.`slug`, `elements_sites`.`uri` AS `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `users`.`username`, `users`.`firstName`, `users`.`lastName`, `users`.`email`, `users`.`admin`, `users`.`locked`, `users`.`pending`, `users`.`suspended`, `users`.`lastLoginDate`, `users`.`lockoutDate`, `users`.`photoId`, `users`.`hasDashboard`, `content`.`id` AS `contentId`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `craft_elements` `elements`
INNER JOIN `craft_users` `users` ON `users`.`id` = `elements`.`id`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `craft_content` `content` ON `content`.`elementId` = `elements`.`id`
WHERE (`elements_sites`.`siteId`='1') AND (`content`.`siteId`='1') AND (`elements`.`id`=1) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL)
ORDER BY `users`.`username`
LIMIT 1) `subquery`
INNER JOIN `craft_users` `users` ON `users`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `craft_content` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `users`.`username` in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT `users`....')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT `users`....')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /var/www/_git/craft-v3/src/db/Query.php(178): yii\db\Query->one(NULL)
#5 /var/www/_git/craft-v3/src/elements/db/ElementQuery.php(1220): craft\db\Query->one(NULL)
#6 /var/www/_git/craft-v3/src/elements/User.php(366): craft\elements\db\ElementQuery->one()
#7 /var/www/html/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity(1)
#8 /var/www/_git/craft-v3/src/web/User.php(491): yii\web\User->renewAuthStatus()
#9 /var/www/html/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#10 /var/www/html/vendor/yiisoft/yii2/web/User.php(360): yii\web\User->getIdentity()
#11 /var/www/_git/craft-v3/src/web/User.php(193): yii\web\User->getIsGuest()
#12 /var/www/_git/craft-v3/src/web/Application.php(259): craft\web\User->getIsGuest()
#13 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#14 /var/www/html/web/index.php(23): yii\base\Application->run()
#15 {main}
Additional Information:
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`id`, `elements`.`fieldLayoutId` AS `elements`.`fieldLayoutId`, `elements`.`uid' at line 1
)
```

### Steps to reproduce

1. git fetch upstream
2. git merge upstream/master
3. git push origin

### Additional info

- Craft version: 3.1.31
- PHP version: 7.3
- Database driver & version: MySQL 8.0.15
- Plugins & versions: ---

**Comment by gtettelaar** [comment]
I was having this as well. It was fixed as of 861bf2c4e27158575406f32db092d9b432550099. The Craft automatic test builds were getting the same [error](https://travis-ci.com/craftcms/cms/jobs/209442629). You can see the fix in action in the latest [build](https://travis-ci.com/craftcms/cms/jobs/210101582)

Can you remove your `vendor/` dir and `composer.lock` file? Then run `composer install` with the latest commit of 3.2 as a requirement. This should resolve the issue.

Getting the latest commit should mean adding the following to the `require` section of `composer.json`
` "craftcms/cms": "3.2.x-develop#65e145007106376fef668b42ae1abee95b905970 as 3.2.0-beta.3"`

**Comment by brandonkelly** [comment]
Right, forgot to update Craft’s `composer.lock` when bumping the Yii requirement, partly because the Yii update happened on the `develop` branch, and we’ve only committed a `composer.lock` to the `3.2` branch, so it was just overlooked when merging `develop => 3.2`.

@bertoost In the future please ensure that a bug exists on this repo before posting; had it not been for @gtettelaar’s response, I would have just immediately closed this with a comment about how we aren’t going to support your fork.

**Comment by bertoost** [comment]
@brandonkelly I think that's not totally fair to say. I have nothing custom in my own fork and even re-forked from the latest develop. It's kinda weird that develop is broken at all. Even with a fresh install of Craft. So, whether it was my fork or your version, that didn't matter.
I still think that develop and master should work without the tricks as described above.

**Comment by brandonkelly** [comment]
> I have nothing custom in my own fork and even re-forked from the latest develop.

That might be true in your case but the point of having a fork is because you are maintaining changes. This is basic bug reporting 101 -- if you are maintaining a fork of something and find a bug, make sure the bug also exists on the main repo before reporting it.
