### ISSUE TITLE
Default testCraftEdition functional test has 404 error code

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#4466]
### Description
After generating the test suite and copying the main `.env` file to `tests/.env` the default `testCraftEdition` functional test fails with a 404 status code.

### Steps to reproduce

1. Install the latest RC2 and Codeception using composer
2. Run `./craft tests/setup`
3. Copy your `.env` to `tests/.env`
4. Run `php vendor/bin/codecept build`
5. Run `php vendor/bin/codecept run functional`

Here's the full output if I add the `--debug` flag:
```log
❯ php vendor/bin/codecept run functional --debug
Codeception PHP Testing Framework v3.0.2
Powered by PHPUnit 6.5.14 by Sebastian Bergmann and contributors.
Running with seed: 


Functional Tests (1) --------------------------------------------------------------------------------------------------------
Modules: \craft\test\Craft, \Helper\Functional
-----------------------------------------------------------------------------------------------------------------------------
ExampleFunctionalCest: Test craft edition
Signature: myprojecttests\ExampleFunctionalCest:testCraftEdition
Test: tests/functional/ExampleFunctionalCest.php:testCraftEdition
Scenario --
  Destroying application
  Starting application
  [ConnectionWatcher] watching new connections
  [Fixtures] Loading fixtures
  [Fixtures] Done
  [TransactionForcer] watching new connections
 I am on page "?p=/"
  [Request Headers] []
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=localhost;dbname=REDACTED;port=3306;'
  [ConnectionWatcher] Connection opened!
  [TransactionForcer] Connection opened!
  [TransactionForcer] Transaction started for: mysql:host=localhost;dbname=REDACTED;port=3306;
  [yii\web\HttpException:404] 'yii\\web\\NotFoundHttpException: Template not found:  in /PATH_TO_MY_SITE/vendor/craftcms/cms/src/controllers/TemplatesController.php:87
  Stack trace:
  #0 [internal function]: craft\\controllers\\TemplatesController->actionRender(\'\', Array)
  #1 /PATH_TO_MY_SITE/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
  #2 /PATH_TO_MY_SITE/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)
  #3 /PATH_TO_MY_SITE/vendor/craftcms/cms/src/web/Controller.php(186): yii\\base\\Controller->runAction(\'render\', Array)
  #4 /PATH_TO_MY_SITE/vendor/yiisoft/yii2/base/Module.php(528): craft\\web\\Controller->runAction(\'render\', Array)
  #5 /PATH_TO_MY_SITE/vendor/craftcms/cms/src/web/Application.php(298): yii\\base\\Module->runAction(\'templates/rende...\', Array)
  #6 /PATH_TO_MY_SITE/vendor/yiisoft/yii2/web/Application.php(103): craft\\web\\Application->runAction(\'templates/rende...\', Array)
  #7 /PATH_TO_MY_SITE/vendor/craftcms/cms/src/web/Application.php(283): yii\\web\\Application->handleRequest(Object(craft\\web\\Request))
  #8 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Lib/Connector/Yii2.php(332): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))
  #9 /PATH_TO_MY_SITE/vendor/symfony/browser-kit/Client.php(315): Codeception\\Lib\\Connector\\Yii2->doRequest(Object(Symfony\\Component\\BrowserKit\\Request))
  #10 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php(201): Symfony\\Component\\BrowserKit\\Client->request(\'GET\', \'https://localho...\', Array, Array, Array, NULL, true)
  #11 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Module/Yii2.php(657): Codeception\\Lib\\InnerBrowser->clientRequest(\'GET\', \'?p=/\', Array, Array, Array, NULL, true)
  #12 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php(249): Codeception\\Module\\Yii2->clientRequest(\'GET\', \'?p=/\', Array, Array, Array, NULL)
  #13 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php(353): Codeception\\Lib\\InnerBrowser->_loadPage(\'GET\', \'?p=/\')
  #14 [internal function]: Codeception\\Lib\\InnerBrowser->amOnPage(\'?p=/\')
  #15 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Step.php(265): call_user_func_array(Array, Array)
  #16 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Scenario.php(72): Codeception\\Step->run(Object(Codeception\\Lib\\ModuleContainer))
  #17 /PATH_TO_MY_SITE/tests/_support/_generated/FunctionalTesterActions.php(742): Codeception\\Scenario->runStep(Object(Codeception\\Step\\Condition))
  #18 /PATH_TO_MY_SITE/tests/functional/ExampleFunctionalCest.php(22): FunctionalTester->amOnPage(\'?p=/\')
  #19 [internal function]: myprojecttests\\ExampleFunctionalCest->testCraftEdition(Object(FunctionalTester))
  #20 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Lib/Di.php(127): ReflectionMethod->invokeArgs(Object(myprojecttests\\ExampleFunctionalCest), Array)
  #21 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Test/Cest.php(138): Codeception\\Lib\\Di->injectDependencies(Object(myprojecttests\\ExampleFunctionalCest), \'testCraftEditio...\', Array)
  #22 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Test/Cest.php(150): Codeception\\Test\\Cest->invoke(\'testCraftEditio...\', Array)
  #23 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Test/Cest.php(82): Codeception\\Test\\Cest->executeTestMethod(Object(FunctionalTester))
  #24 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Test/Test.php(88): Codeception\\Test\\Cest->test()
  #25 /PATH_TO_MY_SITE/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): Codeception\\Test\\Test->run(Object(PHPUnit\\Framework\\TestResult))
  #26 /PATH_TO_MY_SITE/vendor/codeception/phpunit-wrapper/src/Runner.php(110): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
  #27 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/SuiteManager.php(158): Codeception\\PHPUnit\\Runner->doEnhancedRun(Object(Codeception\\Suite), Object(PHPUnit\\Framework\\TestResult), Array)
  #28 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Codecept.php(193): Codeception\\SuiteManager->run(Object(Codeception\\PHPUnit\\Runner), Object(PHPUnit\\Framework\\TestResult), Array)
  #29 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Codecept.php(160): Codeception\\Codecept->runSuite(Array, \'functional\', NULL)
  #30 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Command/Run.php(496): Codeception\\Codecept->run(\'functional\')
  #31 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Command/Run.php(391): Codeception\\Command\\Run->runSuites(Array, Array)
  #32 /PATH_TO_MY_SITE/vendor/symfony/console/Command/Command.php(264): Codeception\\Command\\Run->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
  #33 /PATH_TO_MY_SITE/vendor/symfony/console/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
  #34 /PATH_TO_MY_SITE/vendor/symfony/console/Application.php(228): Symfony\\Component\\Console\\Application->doRunCommand(Object(Codeception\\Command\\Run), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
  #35 /PATH_TO_MY_SITE/vendor/symfony/console/Application.php(130): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
  #36 /PATH_TO_MY_SITE/vendor/codeception/codeception/src/Codeception/Application.php(107): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
  #37 /PATH_TO_MY_SITE/vendor/codeception/codeception/codecept(43): Codeception\\Application->run()
  #38 {main}'
  [Page] ?p=/
  [Response] 404
  [Request Cookies] []
  [Response Headers] {"x-powered-by":["Craft CMS"],"content-type":["text/html; charset=UTF-8"]}
 I see response code is 200
 FAIL 

  [TransactionForcer] Transaction cancelled; all changes reverted.
  [TransactionForcer] no longer watching new connections
  Destroying application
  [ConnectionWatcher] no longer watching new connections
  [ConnectionWatcher] closing all (1) connections
  Suite done, restoring $_SERVER to original
-----------------------------------------------------------------------------------------------------------------------------


Time: 8.41 seconds, Memory: 28.00MB

There was 1 failure:

---------
1) ExampleFunctionalCest: Test craft edition
 Test  tests/functional/ExampleFunctionalCest.php:testCraftEdition
 Step  See response code is 200
 Fail  Expected HTTP Status Code: 200 (OK). Actual Status Code: 404 (Not Found)
Failed asserting that 404 matches expected 200.

Scenario Steps:

 2. $I->seeResponseCodeIs(200) at tests/functional/ExampleFunctionalCest.php:23
 1. $I->amOnPage("?p=/") at tests/functional/ExampleFunctionalCest.php:22

Artifacts:

Response: /PATH_TO_MY_SITE/tests/_output/myprojecttests.ExampleFunctionalCest.testCraftEdition.fail.html

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

### Additional info

- Craft version: RC2
- PHP version: 7.2.12
- Database driver & version: MySQL 5.7.24
- **EDIT**: Local dev environment: Laravel Valet

**Comment by gtettelaar** [comment]
@aaronbushnell Can you manually add an `index.twig` file to your `tests/_craft/templates` directory, re-run the tests and see if just the `ExampleFunctionalCest` passes then?

**Comment by aaronbushnell** [comment]
Thanks, @gtettelaar, that fixed my issue! It looks like—out of the box—the `example.twig` file should get renamed to `index.twig`, perhaps?

Also—and I'm happy to add a different issue for this—creating a `tests/_craft/templates/news/index.twig` template and running
```php
$I->amOnPage('/news');
$I->see('News');
```
Seems to fail. For some reason the functional test renders the `index.twig` template when I call `amOnPage('/news')`:

```
Functional Tests (2) --------------------------------------------------------------------------------------------------------
✔ ExampleFunctionalCest: Test craft edition (0.04s)
✖ ExampleFunctionalCest: Test news page (0.02s)
-----------------------------------------------------------------------------------------------------------------------------


Time: 8.45 seconds, Memory: 30.00MB

There was 1 failure:

---------
1) ExampleFunctionalCest: Test news page
 Test  tests/functional/ExampleFunctionalCest.php:testNewsPage
 Step  See "News"
 Fail  Failed asserting that  on page /news
--> Im a twig template and here's a random number 33104370 
--> contains "News".

Scenario Steps:

 3. $I->see("News") at tests/functional/ExampleFunctionalCest.php:33
 2. $I->seeResponseCodeIs(200) at tests/functional/ExampleFunctionalCest.php:32
 1. $I->amOnPage("/news") at tests/functional/ExampleFunctionalCest.php:31

Artifacts:

Response: tests/_output/myprojecttests.ExampleFunctionalCest.testNewsPage.fail.html

FAILURES!
Tests: 2, Assertions: 3, Failures: 1.
```

**Comment by gtettelaar** [comment]
@aaronbushnell This looks like a problem we had in the Craft test suite aswell - we edited the `codeception.yml` file - Seems I didn't propagate those changes into the example suite. 

Long story short, Craft's routing seems to fail if you pass in the `entryScript` param to your `codeception.yml` and run functional tests without the `?p=` path param. Can you remove `entryScript` and change the `entryUrl` to `https://whateveryousetyoursiteurlto.test/index.php`. So append the `/index.php` to the `entryUrl` param?

**Comment by aaronbushnell** [comment]
All good, @gtettelaar! Thanks so much for the quick help. I went ahead and created a pull request to fix these in case it's useful to you. If you'd like me to modify anything here just let me know! 😄

**Comment by gtettelaar** [comment]
@aaronbushnell Awsome!! Thanks a bunch!

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/cms/pull/4467
