### ISSUE TITLE
An unknown error occurred when deleting image transform

### ISSUE THREAD

**Issue by rinusvandam** [craftcms/cms#4473]
### Description

When deleting an image transform I get ‘An unknown error occurred’.

#### web.log
```
[-][1][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: craft\events\AssetTransformEvent::transform in /sites/sitename/craft/vendor/yiisoft/yii2/base/BaseObject.php:163
```

#### Stack trace
```
#0 /sites/sitename/craft/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\BaseObject->__set('transform', Object(craft\models\AssetTransform))
#1 /sites/sitename/craft/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\events\AssetTransformEvent), Array)
#2 /sites/sitename/craft/vendor/craftcms/cms/src/services/AssetTransforms.php(364): yii\base\BaseObject->__construct(Array)
#3 /sites/sitename/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(884): craft\services\AssetTransforms->handleDeletedTransform(Object(craft\events\ConfigEvent))
#4 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#5 /sites/sitename/craft/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#6 /sites/sitename/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(572): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#7 /sites/sitename/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(421): craft\services\ProjectConfig->processConfigChanges('imageTransforms...', true)
#8 /sites/sitename/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(436): craft\services\ProjectConfig->set('imageTransforms...', NULL)
#9 /sites/sitename/craft/vendor/craftcms/cms/src/services/AssetTransforms.php(342): craft\services\ProjectConfig->remove('imageTransforms...')
#10 /sites/sitename/craft/vendor/craftcms/cms/src/services/AssetTransforms.php(312): craft\services\AssetTransforms->deleteTransform(Object(craft\models\AssetTransform))
#11 /sites/sitename/craft/vendor/craftcms/cms/src/controllers/AssetTransformsController.php(173): craft\services\AssetTransforms->deleteTransformById(3)
#12 [internal function]: craft\controllers\AssetTransformsController->actionDeleteTransform()
#13 /sites/sitename/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /sites/sitename/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /sites/sitename/craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('delete-transfor...', Array)
#16 /sites/sitename/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('delete-transfor...', Array)
#17 /sites/sitename/craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('asset-transform...', Array)
#18 /sites/sitename/craft/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('asset-transform...', Array)
#19 /sites/sitename/craft/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /sites/sitename/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /sites/sitename/web/index.php(21): yii\base\Application->run()
#22 {main}
```

### Steps to reproduce

1. Create image transforms
2. Generate image transforms
3. Delete transforms

#### Environment
- Craft version: Craft Pro 3.1.32.1
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25

#### Plugins & versions:
- Amazon S3: 1.2.3
- Forms: 3.1.0
- Maps: 3.5.2
- Redactor: 2.3.3.2
- SEOMate: 1.0.3
- Video Embedder: 1.1.3

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#53712ead1d35a94ba3643677a26ef1658b0c474c as 3.1.32.1",
  "...": "..."
}
```

Then run `composer update`.
