### ISSUE TITLE
Relation 'info' does not exist after trying to update to 3.1.34

### ISSUE THREAD

**Issue by semonje** [craftcms/cms#4563]
### Description
Before updating from `3.1.30` to `3.1.34` I made a backup of my database and hit update. The update seemingly failed and made the site return a few errors, so instead of looking too much into it I figured I'd downgrade Craft to what it was before the update, and recover the DB backup. But, when recovering that DB backup, I get this error:

```An Error occurred while handling another error:
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "info" does not exist
LINE 2: FROM "info"
             ^ in /craft-install/vendor/yiisoft/yii2/db/Command.php:1290
Stack trace:
#0 /craft-install/vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute()
#1 /craft-install/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT *\nFROM "...')
#2 /craft-install/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /craft-install/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /craft-install/vendor/craftcms/cms/src/db/Query.php(248): yii\db\Query->one(NULL)
#5 /craft-install/vendor/craftcms/cms/src/base/ApplicationTrait.php(542): craft\db\Query->one()
#6 /craft-install/vendor/craftcms/cms/src/services/Updates.php(306): craft\web\Application->getInfo()
#7 /craft-install/vendor/craftcms/cms/src/web/Request.php(195): craft\services\Updates->getIsCraftDbMigrationNeeded()
#8 /craft-install/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Request->init()
#9 [internal function]: yii\base\BaseObject->__construct(Array)
#10 /craft-install/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#11 /craft-install/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Reque...', Array, Array)
#12 /craft-install/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Reque...', Array, Array)
#13 /craft-install/vendor/craftcms/cms/src/config/app.web.php(13): yii\BaseYii::createObject(Array)
#14 [internal function]: {closure}()
#15 /craft-install/vendor/yiisoft/yii2/di/Container.php(508): call_user_func_array(Object(Closure), Array)
#16 /craft-install/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#17 /craft-install/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#18 /craft-install/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('request', true)
#19 /craft-install/vendor/craftcms/cms/src/web/Application.php(348): yii\base\Module->get('request', true)
#20 /craft-install/vendor/yiisoft/yii2/di/ServiceLocator.php(74): craft\web\Application->get('request')
#21 /craft-install/vendor/yiisoft/yii2/web/ErrorHandler.php(502): yii\di\ServiceLocator->__get('request')
#22 /craft-install/vendor/yiisoft/yii2/web/ErrorHandler.php(115): yii\web\ErrorHandler->shouldRenderSimpleHtml()
#23 /craft-install/vendor/craftcms/cms/src/web/ErrorHandler.php(137): yii\web\ErrorHandler->renderException(Object(yii\db\Exception))
#24 /craft-install/vendor/yiisoft/yii2/base/ErrorHandler.php(111): craft\web\ErrorHandler->renderException(Object(yii\db\Exception))
#25 /craft-install/vendor/craftcms/cms/src/web/ErrorHandler.php(68): yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#26 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\db\Exception))
#27 {main}

Next yii\db\Exception: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "info" does not exist
LINE 2: FROM "info"
             ^
The SQL being executed was: SELECT *
FROM "info"
LIMIT 1 in /craft-install/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /craft-install/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT *\nFROM "...')
#1 /craft-install/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT *\nFROM "...')
#2 /craft-install/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /craft-install/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /craft-install/vendor/craftcms/cms/src/db/Query.php(248): yii\db\Query->one(NULL)
#5 /craft-install/vendor/craftcms/cms/src/base/ApplicationTrait.php(542): craft\db\Query->one()
#6 /craft-install/vendor/craftcms/cms/src/services/Updates.php(306): craft\web\Application->getInfo()
#7 /craft-install/vendor/craftcms/cms/src/web/Request.php(195): craft\services\Updates->getIsCraftDbMigrationNeeded()
#8 /craft-install/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Request->init()
#9 [internal function]: yii\base\BaseObject->__construct(Array)
#10 /craft-install/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#11 /craft-install/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Reque...', Array, Array)
#12 /craft-install/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Reque...', Array, Array)
#13 /craft-install/vendor/craftcms/cms/src/config/app.web.php(13): yii\BaseYii::createObject(Array)
#14 [internal function]: {closure}()
#15 /craft-install/vendor/yiisoft/yii2/di/Container.php(508): call_user_func_array(Object(Closure), Array)
#16 /craft-install/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#17 /craft-install/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#18 /craft-install/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('request', true)
#19 /craft-install/vendor/craftcms/cms/src/web/Application.php(348): yii\base\Module->get('request', true)
#20 /craft-install/vendor/yiisoft/yii2/di/ServiceLocator.php(74): craft\web\Application->get('request')
#21 /craft-install/vendor/yiisoft/yii2/web/ErrorHandler.php(502): yii\di\ServiceLocator->__get('request')
#22 /craft-install/vendor/yiisoft/yii2/web/ErrorHandler.php(115): yii\web\ErrorHandler->shouldRenderSimpleHtml()
#23 /craft-install/vendor/craftcms/cms/src/web/ErrorHandler.php(137): yii\web\ErrorHandler->renderException(Object(yii\db\Exception))
#24 /craft-install/vendor/yiisoft/yii2/base/ErrorHandler.php(111): craft\web\ErrorHandler->renderException(Object(yii\db\Exception))
#25 /craft-install/vendor/craftcms/cms/src/web/ErrorHandler.php(68): yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#26 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\db\Exception))
#27 {main}
Additional Information:
Array
(
    [0] => 42P01
    [1] => 7
    [2] => ERROR:  relation "info" does not exist
LINE 2: FROM "info"
             ^
)

Previous exception:
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "info" does not exist
LINE 2: FROM "info"
             ^ in /craft-install/vendor/yiisoft/yii2/db/Command.php:1290
Stack trace:
#0 /craft-install/vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute()
#1 /craft-install/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT *\nFROM "...')
#2 /craft-install/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /craft-install/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /craft-install/vendor/craftcms/cms/src/db/Query.php(248): yii\db\Query->one(NULL)
#5 /craft-install/vendor/craftcms/cms/src/base/ApplicationTrait.php(542): craft\db\Query->one()
#6 /craft-install/vendor/craftcms/cms/src/services/Updates.php(306): craft\web\Application->getInfo()
#7 /craft-install/vendor/craftcms/cms/src/web/Request.php(195): craft\services\Updates->getIsCraftDbMigrationNeeded()
#8 /craft-install/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Request->init()
#9 [internal function]: yii\base\BaseObject->__construct(Array)
#10 /craft-install/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#11 /craft-install/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Reque...', Array, Array)
#12 /craft-install/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Reque...', Array, Array)
#13 /craft-install/vendor/craftcms/cms/src/config/app.web.php(13): yii\BaseYii::createObject(Array)
#14 [internal function]: {closure}()
#15 /craft-install/vendor/yiisoft/yii2/di/Container.php(508): call_user_func_array(Object(Closure), Array)
#16 /craft-install/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#17 /craft-install/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#18 /craft-install/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('request', true)
#19 /craft-install/vendor/craftcms/cms/src/web/Application.php(348): yii\base\Module->get('request', true)
#20 /craft-install/vendor/yiisoft/yii2/web/Application.php(160): craft\web\Application->get('request')
#21 /craft-install/vendor/craftcms/cms/src/helpers/App.php(487): yii\web\Application->getRequest()
#22 /craft-install/vendor/craftcms/cms/src/config/app.php(207): craft\helpers\App::logConfig()
#23 [internal function]: {closure}()
#24 /craft-install/vendor/yiisoft/yii2/di/Container.php(508): call_user_func_array(Object(Closure), Array)
#25 /craft-install/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#26 /craft-install/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#27 /craft-install/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('log', true)
#28 /craft-install/vendor/craftcms/cms/src/web/Application.php(348): yii\base\Module->get('log', true)
#29 /craft-install/vendor/yiisoft/yii2/base/Application.php(508): craft\web\Application->get('log')
#30 /craft-install/vendor/craftcms/cms/src/base/ApplicationTrait.php(1221): yii\base\Application->getLog()
#31 /craft-install/vendor/craftcms/cms/src/web/Application.php(109): craft\web\Application->_preInit()
#32 /craft-install/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#33 /craft-install/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#34 /craft-install/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
#35 [internal function]: craft\web\Application->__construct(Array)
#36 /craft-install/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#37 /craft-install/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#38 /craft-install/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#39 /craft-install/vendor/craftcms/cms/bootstrap/bootstrap.php(248): yii\BaseYii::createObject(Array)
#40 /craft-install/vendor/craftcms/cms/bootstrap/web.php(52): require('/Users/semonje/...')
#41 /craft-install/web/index.php(20): require('/Users/semonje/...')
#42 /Users/semonje/.composer/vendor/laravel/valet/server.php(158): require('/Users/semonje/...')
#43 {main}

Next yii\db\Exception: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "info" does not exist
LINE 2: FROM "info"
             ^
The SQL being executed was: SELECT *
FROM "info"
LIMIT 1 in /craft-install/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /craft-install/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT *\nFROM "...')
#1 /craft-install/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT *\nFROM "...')
#2 /craft-install/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /craft-install/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /craft-install/vendor/craftcms/cms/src/db/Query.php(248): yii\db\Query->one(NULL)
#5 /craft-install/vendor/craftcms/cms/src/base/ApplicationTrait.php(542): craft\db\Query->one()
#6 /craft-install/vendor/craftcms/cms/src/services/Updates.php(306): craft\web\Application->getInfo()
#7 /craft-install/vendor/craftcms/cms/src/web/Request.php(195): craft\services\Updates->getIsCraftDbMigrationNeeded()
#8 /craft-install/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Request->init()
#9 [internal function]: yii\base\BaseObject->__construct(Array)
#10 /craft-install/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#11 /craft-install/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Reque...', Array, Array)
#12 /craft-install/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Reque...', Array, Array)
#13 /craft-install/vendor/craftcms/cms/src/config/app.web.php(13): yii\BaseYii::createObject(Array)
#14 [internal function]: {closure}()
#15 /craft-install/vendor/yiisoft/yii2/di/Container.php(508): call_user_func_array(Object(Closure), Array)
#16 /craft-install/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#17 /craft-install/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#18 /craft-install/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('request', true)
#19 /craft-install/vendor/craftcms/cms/src/web/Application.php(348): yii\base\Module->get('request', true)
#20 /craft-install/vendor/yiisoft/yii2/web/Application.php(160): craft\web\Application->get('request')
#21 /craft-install/vendor/craftcms/cms/src/helpers/App.php(487): yii\web\Application->getRequest()
#22 /craft-install/vendor/craftcms/cms/src/config/app.php(207): craft\helpers\App::logConfig()
#23 [internal function]: {closure}()
#24 /craft-install/vendor/yiisoft/yii2/di/Container.php(508): call_user_func_array(Object(Closure), Array)
#25 /craft-install/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#26 /craft-install/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#27 /craft-install/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('log', true)
#28 /craft-install/vendor/craftcms/cms/src/web/Application.php(348): yii\base\Module->get('log', true)
#29 /craft-install/vendor/yiisoft/yii2/base/Application.php(508): craft\web\Application->get('log')
#30 /craft-install/vendor/craftcms/cms/src/base/ApplicationTrait.php(1221): yii\base\Application->getLog()
#31 /craft-install/vendor/craftcms/cms/src/web/Application.php(109): craft\web\Application->_preInit()
#32 /craft-install/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#33 /craft-install/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#34 /craft-install/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
#35 [internal function]: craft\web\Application->__construct(Array)
#36 /craft-install/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#37 /craft-install/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#38 /craft-install/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#39 /craft-install/vendor/craftcms/cms/bootstrap/bootstrap.php(248): yii\BaseYii::createObject(Array)
#40 /craft-install/vendor/craftcms/cms/bootstrap/web.php(52): require('/Users/semonje/...')
#41 /craft-install/web/index.php(20): require('/Users/semonje/...')
#42 /Users/semonje/.composer/vendor/laravel/valet/server.php(158): require('/Users/semonje/...')
#43 {main}
Additional Information:
Array
(
    [0] => 42P01
    [1] => 7
    [2] => ERROR:  relation "info" does not exist
LINE 2: FROM "info"
             ^
)
```

It seems it's complaining that the `info` table is empty, and it is indeed. But as far as I can tell, this should be the exact DB that Craft was working with earlier.

After searching around I tried downgrading Postgres from `v11` to `v10`, but that didn't make any difference.

### Steps to reproduce

I'm not currently able to reproduce, so I'm probably missing a few details here, but:
1. Install Craft `v1.3.30` and make a backup of the DB
2. Update Craft to `v1.3.34`
3. Install Craft `v1.3.30` again
4. Try to import the DB backup

### Additional info

- Craft version: `3.1.30`
- PHP version: `7.3.5`
- Database driver & version: `postgresql@10 v10.9`
- Plugins & versions:
    - "anubarak/craft-relabel": "1.3.1",
    - "clubstudioltd/craft-asset-rev": "6.0.2",
    - "clubstudioltd/craft-inline-svg": "0.1.1",
    - "craftcms/feed-me": "4.1.0",
    - "craftcms/google-cloud": "1.3.0",
    - "craftcms/redactor": "2.3.3.2",
    - "dgrigg/craft-migration-assistant": "3.1.2",
    - "fruitstudios/linkit": "1.1.11",
    - "pierrestoffe/craft-language-redirector": "1.1.3",
    - "spicyweb/craft-neo": "2.3.5",
    - "verbb/field-manager": "2.1.0"

**Comment by semonje** [comment]
I'm having a trouble understanding the error message as the table _does_ exist. I can confirm that the CMS is hooked up to the correct database, as it returns other (more obvious) errors if I change its credentials.

**Comment by semonje** [comment]
Found the fix now. So, somehow, Postgres had managed to revoke the DB user of its privileges to alter the public schema, although it could query it directly… Seems like it might be a bug in PSQL, if anything.

Anyway, if anyone else happens to stumble upon this, the fix was to revoke all privileges to the public schema and re-grant them again. This fixed it:

```
REVOKE ALL
ON ALL TABLES IN SCHEMA public 
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public 
TO user_name;
```

**Comment by brandonkelly** [comment]
Weird, but glad you got it sorted!
