### ISSUE TITLE
Craft installation on empty database fails if a project.yaml with Matrix field is provided

### ISSUE THREAD

**Issue by N0ps32** [craftcms/cms#4789]
### Description
Craft installation on empty database fails if a project.yaml with Matrix field is provided

### Steps to reproduce

1. Have existing project yaml
2. Try to restore project using said project.yaml
3. Press install button with a completely empty database

Result:
```
    > add foreign key users_photoId_fk: {{%users}} (photoId) references {{%assets}} (id) ... done (time: 0.149s)
    > add foreign key volumefolders_parentId_fk: {{%volumefolders}} (parentId) references {{%volumefolders}} (id) ... done (time: 0.108s)
    > add foreign key volumefolders_volumeId_fk: {{%volumefolders}} (volumeId) references {{%volumes}} (id) ... done (time: 0.126s)
    > add foreign key volumes_fieldLayoutId_fk: {{%volumes}} (fieldLayoutId) references {{%fieldlayouts}} (id) ... done (time: 0.109s)
    > add foreign key widgets_userId_fk: {{%widgets}} (userId) references {{%users}} (id) ... done (time: 0.084s)
    > populating the info table ... done
    > installing redactor ... done
    > applying existing project config ... Exception: Getting unknown property: craft\fields\Entries::contentTable (/app/vendor/yiisoft/yii2/base/Component.php:154)
#0 /app/vendor/craftcms/cms/src/services/Matrix.php(343): yii\base\Component->__get('contentTable')
#1 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(865): craft\services\Matrix->handleChangedBlockType(Object(craft\events\ConfigEvent))
#2 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#3 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#4 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(545): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#5 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(859): craft\services\ProjectConfig->processConfigChanges('matrixBlockType...')
#6 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#7 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#8 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(545): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#9 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(944): craft\services\ProjectConfig->processConfigChanges('matrixBlockType...')
#10 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(435): craft\services\ProjectConfig->_applyChanges(Array)
#11 /app/vendor/craftcms/cms/src/migrations/Install.php(1022): craft\services\ProjectConfig->applyYamlChanges()
#12 /app/vendor/craftcms/cms/src/migrations/Install.php(73): craft\migrations\Install->insertDefaultData()
#13 /app/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\Install->safeUp()
#14 /app/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#15 /app/vendor/craftcms/cms/src/controllers/InstallController.php(302): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
#16 [internal function]: craft\controllers\InstallController->actionInstall()
#17 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 /app/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('install', Array)
#20 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install', Array)
#21 /app/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('install/install', Array)
#22 /app/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('install/install', Array)
#23 /app/vendor/craftcms/cms/src/web/Application.php(528): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 /app/vendor/craftcms/cms/src/web/Application.php(194): craft\web\Application->_processInstallRequest(Object(craft\web\Request))
#25 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /app/web/index.php(21): yii\base\Application->run()
#27 {main}

2019-08-21 15:15:14 [-][-][-][error][craft\errors\MigrationException] yii\base\UnknownPropertyException: Getting unknown property: craft\fields\Entries::contentTable in /app/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /app/vendor/craftcms/cms/src/services/Matrix.php(343): yii\base\Component->__get('contentTable')
#1 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(865): craft\services\Matrix->handleChangedBlockType(Object(craft\events\ConfigEvent))
#2 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#3 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#4 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(545): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#5 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(859): craft\services\ProjectConfig->processConfigChanges('matrixBlockType...')
#6 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#7 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#8 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(545): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#9 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(944): craft\services\ProjectConfig->processConfigChanges('matrixBlockType...')
#10 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(435): craft\services\ProjectConfig->_applyChanges(Array)
#11 /app/vendor/craftcms/cms/src/migrations/Install.php(1022): craft\services\ProjectConfig->applyYamlChanges()
#12 /app/vendor/craftcms/cms/src/migrations/Install.php(73): craft\migrations\Install->insertDefaultData()
#13 /app/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\Install->safeUp()
#14 /app/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#15 /app/vendor/craftcms/cms/src/controllers/InstallController.php(302): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
#16 [internal function]: craft\controllers\InstallController->actionInstall()
#17 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 /app/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('install', Array)
#20 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install', Array)
#21 /app/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('install/install', Array)
#22 /app/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('install/install', Array)
#23 /app/vendor/craftcms/cms/src/web/Application.php(528): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 /app/vendor/craftcms/cms/src/web/Application.php(194): craft\web\Application->_processInstallRequest(Object(craft\web\Request))
#25 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /app/web/index.php(21): yii\base\Application->run()
#27 {main}

Next craft\errors\MigrationException: An error occurred while executing the "craft\migrations\Install migration: Getting unknown property: craft\fields\Entries::contentTable in /app/vendor/craftcms/cms/src/db/MigrationManager.php:260
Stack trace:
#0 /app/vendor/craftcms/cms/src/controllers/InstallController.php(302): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
#1 [internal function]: craft\controllers\InstallController->actionInstall()
#2 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /app/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('install', Array)
#5 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install', Array)
#6 /app/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('install/install', Array)
#7 /app/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('install/install', Array)
#8 /app/vendor/craftcms/cms/src/web/Application.php(528): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /app/vendor/craftcms/cms/src/web/Application.php(194): craft\web\Application->_processInstallRequest(Object(craft\web\Request))
#10 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /app/web/index.php(21): yii\base\Application->run()
#12 {main}

```

### Additional info

- Craft version: Craft Solo 3.2.10
- PHP version: 7.3
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Redactor 2.3.3.2

**Comment by brandonkelly** [comment]
Can you please send your `composer.json`, `composer.lock`, and `config/project.yaml` files over to support@craftcms.com so we can look into this?

**Comment by PBader** [comment]
Any update on this? I´m running into the same issue.

**Comment by brandonkelly** [comment]
@PBader [Same request](https://github.com/craftcms/cms/issues/4789#issuecomment-523692558) to you. It works in our own testing.

**Comment by alinnert** [comment]
@brandonkelly I'm having the same issue while installing a project I checked out from git on a new machine. My error message is slightly different though but still very similar to OP's issue:

~~~
An error occurred while executing the "craft\migrations\Install migration: The following config paths could not be processed successfully: matrixBlockTypes.c522e5b5-4fb6-4f14-8f1c-102033d2860d
~~~

Steps to reproduce are:

- `git clone ...`
- `composer install`
- open `index.php?p=admin/install`

I'd like to give you the `project.yaml` or access to the repo so you can try it out. But it's a private repo. As far as I can see I can only give you read permissions on GitLab. I'd have to pay for that on GitHub. Or do you have another idea?

**Comment by brandonkelly** [comment]
@alinnert We don’t need access to your whole repo, you can just email us those 3 files.

**Comment by alinnert** [comment]
@brandonkelly alright. I've sent you the email.

**Comment by richardcalahan** [comment]
Same issue here. I was able to get past the error by temporarily setting the following in `config/general.php`

```
useProjectConfigFile => false,
allowAdminChanges => true
```

I ran `./craft setup` and `./craft project-config/rebuild` separately. All good. In theory the web UI would work too.

**Comment by AshtonKem** [comment]
I've had the same exact issue twice this month.

**Comment by alinnert** [comment]
@AshtonKem as far as I can recall you have to import a database backup into your database. After doing so you just have to "finish the update" instead of installing a fresh copy. This should work fine (or at least it did for me). Then you can update Craft to the latest version and keep the imported data or reinstall it without a database import.

This seems to be related to a bug in how the `project.yaml` gets processed. So this is only necessary if you jump over a specific version. It should work fine without a db import after that.

I hope this works for you.

**Comment by dillonbailey** [comment]
Upvoting this one, will send `composer` files and `project.yml` to support 👍 

In our case we were also hitting similar errors with plugins (https://github.com/Anubarak/craft-relabel/issues/11)

It seems like the workaround is to do a fresh install (sans project.yml) and then once you're all setup, copy/paste your project.yml back in and run a sync?

**Comment by brandonkelly** [comment]
@dillonbailey that shouldn’t be necessary. If you send your `composer.json`, `composer.lock`, and `project.yaml` you are trying to install Craft with over to support@craftcms.com we can look into it from there.

**Comment by dillonbailey** [comment]
@brandonkelly no stress! I've emailed through to support but haven't received a confirmation yet (if that's a thing 👍 )

**Comment by brandonkelly** [comment]
@dillonbailey Hm, we didn't receive anything from you. (Checked spam as well.) You will receive an autoresponder if it makes its way to us. Maybe it was caught by a mail server because of the attachments; you may have better luck if you share the files via WeTransfer or something.

**Comment by dillonbailey** [comment]
@brandonkelly just sent via wetransfer!

**Comment by andris-sevcenko** [comment]
@dillonbailey that definitely highlighted one of the problems, which is now fixed for the next release.

Found some more, looking into them.

**Comment by andris-sevcenko** [comment]
@dillonbailey two more issues with the project config:
1) There are inconsistent data stored for the Relabel plugin. See anubarak/craft-relabel#12
2) A more complicated loop of a Matrix block type (X) depending on a Super Table block type (Y) depending on a Matrix block type (Z) which belongs to a field that's no longer a Matrix field (leading to Z not being added to the DB and making X and Y unprocessable). See https://github.com/craftcms/cms/issues/4736 (which is also the case when deleting a Matrix field)

Solutions:
1) Remove the `relabel.df7a1cf5-4ef3-4c6f-8991-01b188b9bf7f` key from the `project.yaml` file.
2) Remove the `superTableBlockTypes.1afcfe40-13e9-41db-bcee-717bd92dcebf` and `matrixBlockTypes.638e7b01-1f2a-4870-b5d9-ab8c1b15f06a` keys from the `project.yaml` file.

**Comment by dillonbailey** [comment]
@andris-sevcenko thanks heaps for this - after removing the problem lines from `project.yml` should I also upgrade to the latest release and then test the fresh install?

**Comment by andris-sevcenko** [comment]
@dillonbailey yep, you should be on Craft 3.3.14 for that.

**Comment by ParallelUniv3rse** [comment]
Installing a project freshly cloned from a git repo here. Craft 3.4.11. 
Install fails on applying changes from a `project.yaml` when it contains supertables.
```
An error occurred while executing the \"craft\\migrations\\Install migration: The following config paths could not be processed successfully:\nsuperTableBlockTypes.803836f9-5f44-4886-9b56-224d3d5ea53a"
```

Install runs fine when I delete the project config file, but when trying to snyc back the changes, it errors out for the same reason.

**Comment by brandonkelly** [comment]
@ParallelUniv3rse Sounds like Super Table bug. Make sure your `project.yaml` file was created using the latest version of Super Table, and maybe run `./craft project-config/rebuild` for good measure. If the file is still giving you the same error for new installations, you can report it here: https://github.com/verbb/super-table/issues
