### ISSUE TITLE
Craft update 3.0.41.1 to 3.2.10

### ISSUE THREAD

**Issue by xavianaxw** [craftcms/cms#4812]
### Description
Trying to update one of the client's Craft version from `3.0.41.1` to `3.2.10` but running into some issues.

```
vagrant@the-well:~/code/craft$ ./craft migrate/all
Yii Migration Tool (based on Yii v2.0.21)

    > alter column line in table {{%deprecationerrors}} to smallint UNSIGNED ... done (time: 0.005s)
    > add column searchable boolean NOT NULL DEFAULT TRUE AFTER `instructions` to table {{%fields}} ... done (time: 0.155s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.006s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.006s)
    > update in {{%fields}} ... done (time: 0.011s)
    > update in {{%fields}} ... done (time: 0.006s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.011s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.011s)
    > update in {{%fields}} ... done (time: 0.007s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.012s)
    > update in {{%fields}} ... done (time: 0.007s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.007s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.011s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.006s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.007s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.018s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.011s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.001s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.011s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%systemsettings}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.007s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.006s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.018s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.007s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.012s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.006s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.006s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.007s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.006s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.007s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.002s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.002s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.007s)
    > update in {{%userpermissions}} ... done (time: 0.006s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.007s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.013s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.027s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.006s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.007s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.016s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.006s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.007s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.006s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.006s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.002s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.014s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.004s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.011s)
    > update in {{%userpermissions}} ... done (time: 0.003s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.008s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.009s)
    > update in {{%userpermissions}} ... done (time: 0.007s)
    > update in {{%userpermissions}} ... done (time: 0.010s)
    > update in {{%userpermissions}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.007s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.018s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.007s)
    > update in {{%fields}} ... done (time: 0.006s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.006s)
    > update in {{%fields}} ... done (time: 0.006s)
    > update in {{%fields}} ... done (time: 0.036s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.005s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.010s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.008s)
    > update in {{%fields}} ... done (time: 0.009s)
    > update in {{%fields}} ... done (time: 0.007s)
    > add column config mediumtext NULL DEFAULT NULL AFTER `maintenance` to table {{%info}} ... done (time: 0.104s)
    > add column configMap mediumtext NULL DEFAULT NULL AFTER `config` to table {{%info}} ... done (time: 0.111s)
Exception: Undefined index:  (/home/vagrant/code/craft/vendor/craftcms/cms/src/migrations/m180521_173000_initial_yml_and_snapshot.php:383)
#0 /home/vagrant/code/craft/vendor/craftcms/cms/src/migrations/m180521_173000_initial_yml_and_snapshot.php(383): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/home/vagrant/c...', 383, Array)
#1 /home/vagrant/code/craft/vendor/craftcms/cms/src/migrations/m180521_173000_initial_yml_and_snapshot.php(80): craft\migrations\m180521_173000_initial_yml_and_snapshot->_getMatrixBlockTypeData()
#2 /home/vagrant/code/craft/vendor/craftcms/cms/src/migrations/m180521_173000_initial_yml_and_snapshot.php(43): craft\migrations\m180521_173000_initial_yml_and_snapshot->_getProjectConfigData()
#3 /home/vagrant/code/craft/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\m180521_173000_initial_yml_and_snapshot->safeUp()
#4 /home/vagrant/code/craft/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#5 /home/vagrant/code/craft/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m180521_173000_initial_yml_and_snapshot))
#6 /home/vagrant/code/craft/vendor/craftcms/cms/src/services/Updates.php(217): craft\db\MigrationManager->up()
#7 /home/vagrant/code/craft/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#8 [internal function]: craft\console\controllers\MigrateController->actionAll()
#9 /home/vagrant/code/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /home/vagrant/code/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /home/vagrant/code/craft/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#12 /home/vagrant/code/craft/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#13 /home/vagrant/code/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /home/vagrant/code/craft/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#15 /home/vagrant/code/craft/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#16 /home/vagrant/code/craft/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /home/vagrant/code/craft/craft(22): yii\base\Application->run()
#18 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Craft CMS.'

in /home/vagrant/code/craft/vendor/craftcms/cms/src/services/Updates.php:233

Stack trace:
#0 /home/vagrant/code/craft/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /home/vagrant/code/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /home/vagrant/code/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /home/vagrant/code/craft/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#5 /home/vagrant/code/craft/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /home/vagrant/code/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /home/vagrant/code/craft/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#8 /home/vagrant/code/craft/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /home/vagrant/code/craft/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /home/vagrant/code/craft/craft(22): yii\base\Application->run()
#11 {main}
```

### Steps to reproduce

1. Craft version `3.0.41.1`
2. Run `composer require craftcms/cms:3.2.10 --update-with-all-dependencies`
3. Run `./craft migration/all`

### Additional info

- Craft version: `3.0.41.1`
- PHP version: `7.1.31`
- Database driver & version: `MySQL 5.7.27`
- Plugins & versions: 

![Screen Shot 2019-08-26 at 2 47 49 pm](https://user-images.githubusercontent.com/8082158/63665856-7f29f980-c810-11e9-84be-73ce5181e900.png)

**Comment by andris-sevcenko** [comment]
That sounds like some missing data for matrix block field layouts. Can you send over a database dump, your composer.json, and your composer.lock files to support@craftcms.com and reference this issue?

**Comment by xavianaxw** [comment]
@andris-sevcenko i've sent support@craftcms.com an email with the requested files.

Thank you

**Comment by olivierbon** [comment]
Leftover fields in the DB, fixed in support.
