### ISSUE TITLE
3.3.0.1 Creating a new entry in 1 section only fails with Internal Server Error screen

### ISSUE THREAD

**Issue by icreatestuff** [craftcms/cms#4883]
### Description
Creating a new entry fails with internal server error (Error stack trace below from logs). It only happens when creating an entry for 1 particular section (a channel). Other channels, singles, structures seem unaffected.

**Stack Trace**
```
2019-09-04 10:47:55 [-][1][mp74vguv08o1qqgtv8n7ma9qs2][error][yii\base\Exception] yii\base\Exception: Unable to save entry in /var/www/vhosts/thedomain.org.uk/httpdocs/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php:128
Stack trace:
#0 [internal function]: craft\controllers\EntryRevisionsController->actionCreateDraft(Object(craft\models\Section), Object(craft\models\Site))
#1 /var/www/vhosts/thedomain.org.uk/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/vhosts/thedomain.org.uk/httpdocs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/vhosts/thedomain.org.uk/httpdocs/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('create-draft', Array)
#4 /var/www/vhosts/thedomain.org.uk/httpdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('create-draft', Array)
#5 /var/www/vhosts/thedomain.org.uk/httpdocs/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('entry-revisions...', Array)
#6 /var/www/vhosts/thedomain.org.uk/httpdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entry-revisions...', Array)
#7 /var/www/vhosts/thedomain.org.uk/httpdocs/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/vhosts/thedomain.org.uk/httpdocs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/vhosts/thedomain.org.uk/httpdocs/web/index.php(21): yii\base\Application->run()
#10 {main}
2019-09-04 10:47:55 [-][1][mp74vguv08o1qqgtv8n7ma9qs2][info][application] $_GET = [
    'p' => 'admin/entries/stories/new'
    'site' => 'default'
]
```

This site was initially built on 3.1.33 and I've since taken it through 3.2 and now to 3.3. There were no errors shown during any update.

### Steps to reproduce

1. Login to control panel
2. Go to 'Entries' from sidebar navigation
3. Choose channel from list
4. Click 'Create New' button from top right

### Additional info

- Craft: 3.3.0.1
- PHP: 7.2.21
- Database: MySQL 5.5.62

**Plugins:** 
- Button Box 2.0.4
- CP Field Inspect 1.0.6
- Control Panel CSS: 2.2.0
- Cookies: 1.1.11
- Dumper: 2.0.0
- Image Resizer: 2.0.5
- Imager: 2.1.10
- Inline SVG: 0.1.2
- Queue Manager: 1.1.0
- Redactor: 2.3.3.2
- Redirect plugin for Craft 3: 1.0.23
- SEO: 3.6.2
- Similar: 1.0.6
- Super Table: 2.2.1

**Comment by brandonkelly** [comment]
I’ve just updated that exception to provide more detail. Can you please update to b6e3b37e10d10661c5ddb03d44bfb85254101e5b and let me know what error you get after that? 

To update, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#b6e3b37e10d10661c5ddb03d44bfb85254101e5b as 3.3.0.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by icreatestuff** [comment]
Thanks @brandonkelly I've updated Craft and the error in the logs now show as

```
2019-09-04 17:41:15 [-][1][4ga5k6lsoppicofr2a0b4vi8jh][error][yii\base\Exception] yii\base\Exception: Unable to save entry as a draft: Could not generate a unique URI based on the URI format. in /var/www/vhosts/thestoryproject.org.uk/httpdocs/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php:127
Stack trace:
#0 [internal function]: craft\controllers\EntryRevisionsController->actionCreateDraft(Object(craft\models\Section), Object(craft\models\Site))
#1 /var/www/vhosts/thestoryproject.org.uk/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/vhosts/thestoryproject.org.uk/httpdocs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/vhosts/thestoryproject.org.uk/httpdocs/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('create-draft', Array)
#4 /var/www/vhosts/thestoryproject.org.uk/httpdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('create-draft', Array)
#5 /var/www/vhosts/thestoryproject.org.uk/httpdocs/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('entry-revisions...', Array)
#6 /var/www/vhosts/thestoryproject.org.uk/httpdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entry-revisions...', Array)
#7 /var/www/vhosts/thestoryproject.org.uk/httpdocs/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/vhosts/thestoryproject.org.uk/httpdocs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/vhosts/thestoryproject.org.uk/httpdocs/web/index.php(21): yii\base\Application->run()
#10 {main}
2019-09-04 17:41:14 [-][1][4ga5k6lsoppicofr2a0b4vi8jh][info][application] $_GET = [
    'p' => 'admin/entries/stories/new'
    'site' => 'default'
]
```

**Comment by brandonkelly** [comment]
What is the section’s URI format set to?

**Comment by icreatestuff** [comment]
`stories/{uniqueId}` where uniqueID is a custom plaintext field.

**Comment by brandonkelly** [comment]
Alright that makes sense, since that field isn’t going to have a value when you first create an entry. So if you have already saved an entry in that section without a value in the field, then you will run into that unique URI constraint.

Maybe try changing the URI format to `stories/{uniqueId ?: 'temp-'~random()}` to ensure that some sort of value gets in there when the `uniqueId` field doesn’t have a value yet.

**Comment by icreatestuff** [comment]
Thanks @brandonkelly that works great. Something must have changed between 3.1 » 3.2/3.3 though because I didn't need to define a fallback value before. Good to know for the future.

**Comment by brandonkelly** [comment]
Yeah the difference is that in 3.2, an entry element is created right away when you click “New entry”.
