### ISSUE TITLE
Migration error after updating fom 3.3.5 to 3.3.6

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#5013]
### Description

After `composer update` the `./craft migrate/all` command throws this error:

```
    Craft isn’t installed yet!

Yii Migration Tool (based on Yii v2.0.21)

Exception 'craft\errors\DbConnectException' with message 'Craft CMS can’t connect to the database with the credentials in config/db.php.'

in /Users/elfacht/htdocs/myproject/app/vendor/craftcms/cms/src/db/Connection.php:190
```

The CP and website are running correctly, but this error occurs when I run `./craft project-config/sync` locally and on the staging server.

Full stack trace:

```
Stack trace:
#0 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/db/Connection.php(1012): craft\db\Connection->open()
#1 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/db/Connection.php(999): yii\db\Connection->getMasterPdo()
#2 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/db/Command.php(253): yii\db\Connection->getSlavePdo()
#3 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/db/Command.php(1153): yii\db\Command->prepare(true)
#4 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#5 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/db/mysql/Schema.php(319): yii\db\Command->queryAll()
#6 /Users/elfacht/htdocs/myproject/app/vendor/craftcms/cms/src/db/mysql/Schema.php(248): yii\db\mysql\Schema->findColumns(Object(craft\db\TableSchema))
#7 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/db/Schema.php(744): craft\db\mysql\Schema->loadTableSchema('hcm_migrations')
#8 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/db/Schema.php(194): yii\db\Schema->getTableMetadata('{{%migrations}}', 'schema', false)
#9 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/db/Connection.php(868): yii\db\Schema->getTableSchema('{{%migrations}}', false)
#10 /Users/elfacht/htdocs/myproject/app/vendor/craftcms/cms/src/db/Connection.php(406): yii\db\Connection->getTableSchema('{{%migrations}}')
#11 /Users/elfacht/htdocs/myproject/app/vendor/craftcms/cms/src/db/MigrationManager.php(491): craft\db\Connection->columnExists('{{%migrations}}', 'version', true)
#12 /Users/elfacht/htdocs/myproject/app/vendor/craftcms/cms/src/db/MigrationManager.php(325): craft\db\MigrationManager->_createMigrationQuery()
#13 /Users/elfacht/htdocs/myproject/app/vendor/craftcms/cms/src/db/MigrationManager.php(420): craft\db\MigrationManager->getMigrationHistory()
#14 /Users/elfacht/htdocs/myproject/app/vendor/craftcms/cms/src/services/Updates.php(180): craft\db\MigrationManager->getNewMigrations()
#15 /Users/elfacht/htdocs/myproject/app/vendor/craftcms/cms/src/console/controllers/MigrateController.php(241): craft\services\Updates->getPendingMigrationHandles(true)
#16 [internal function]: craft\console\controllers\MigrateController->actionAll()
#17 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#20 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#21 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#22 /Users/elfacht/htdocs/myproject/app/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#23 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#24 /Users/elfacht/htdocs/myproject/app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#25 /Users/elfacht/htdocs/myproject/app/craft(22): yii\base\Application->run()
#26 {main}
```

**Comment by elfacht** [comment]
Ok, this can be closed. I updated the PHP version, but was still using the old terminal window … m(

**Comment by brandonkelly** [comment]
Glad you got it sorted!

**Comment by sameerast** [comment]
> Ok, this can be closed. I updated the PHP version, but was still using the old terminal window … m(

What the version that issue was given and what is the version it was fixed?
