### ISSUE TITLE
Dropdown field optgroup bug

### ISSUE THREAD

**Issue by valeryvkrukov** [craftcms/cms#5014]
### Description
After installing updates have an error when save dropdown field with optgroups.
It looks like just simple typo in craftcms/cms/src/fields/BaseOptionsField.php at line 121

https://github.com/craftcms/cms/blob/8cf2d3e18005e6fb44bb25f7d5238babba60b470/src/fields/BaseOptionsField.php#L121

Stack trace:
```
yii\base\ErrorException: Undefined index: label in /home/valery/PhpstormProjects/site-clone-1/vendor/craftcms/cms/src/fields/BaseOptionsField.php:125
Stack trace:
#0 /home/valery/PhpstormProjects/site-clone-1/vendor/yiisoft/yii2/validators/InlineValidator.php(72): craft\fields\Dropdown->validateOptions()
#1 /home/valery/PhpstormProjects/site-clone-1/vendor/yiisoft/yii2/validators/InlineValidator.php(72): ::call_user_func:{/home/valery/PhpstormProjects/site-clone-1/vendor/yiisoft/yii2/validators/InlineValidator.php:72}()
#2 /home/valery/PhpstormProjects/site-clone-1/vendor/yiisoft/yii2/validators/Validator.php(257): yii\validators\InlineValidator->validateAttribute()
#3 /home/valery/PhpstormProjects/site-clone-1/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\InlineValidator->validateAttributes()
#4 /home/valery/PhpstormProjects/site-clone-1/vendor/craftcms/cms/src/services/Fields.php(767): craft\fields\Dropdown->validate()
#5 /home/valery/PhpstormProjects/site-clone-1/vendor/craftcms/cms/src/controllers/FieldsController.php(275): craft\services\Fields->saveField()
#6 /home/valery/PhpstormProjects/site-clone-1/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\FieldsController->actionSaveField()
#7 /home/valery/PhpstormProjects/site-clone-1/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/home/valery/PhpstormProjects/site-clone-1/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#8 /home/valery/PhpstormProjects/site-clone-1/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#9 /home/valery/PhpstormProjects/site-clone-1/vendor/craftcms/cms/src/web/Controller.php(187): craft\controllers\FieldsController->runAction()
#10 /home/valery/PhpstormProjects/site-clone-1/vendor/yiisoft/yii2/base/Module.php(528): craft\controllers\FieldsController->runAction()
#11 /home/valery/PhpstormProjects/site-clone-1/vendor/craftcms/cms/src/web/Application.php(299): craft\web\Application->runAction()
#12 /home/valery/PhpstormProjects/site-clone-1/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction()
#13 /home/valery/PhpstormProjects/site-clone-1/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest()
#14 /home/valery/PhpstormProjects/site-clone-1/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#15 /home/valery/PhpstormProjects/site-clone-1/web/index.php(21): craft\web\Application->run()
#16 {main}
```

### Steps to reproduce

1. save field with dropdown type with optgroups after updating

### Additional info

- Craft version: 3.3.6
- PHP version: 7.3

**Comment by SwiseWeb** [comment]
Confirming that I'm also experiencing this issue

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks for reporting!

**Comment by LouisCuvelier** [comment]
Hi,
This error came back with Craft 3.4

**Comment by brandonkelly** [comment]
@LouisCuvelier I’m not able to reproduce given the above steps, and the bugfix added in 011d78eb6c2bc10111fc5e1c7b0fb4b989d82e9e still exists in 3.4. Can you please come up with some steps to reproduce and post as a new issue?
