### ISSUE TITLE
Consistent project config read-only errors

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#5078]
### Description
We're getting the following error relatively consistently across nearly all of our sites in production environments, where `allowAdminChanges` is false, when we try to deploy.

```
Applying changes from project.yaml ... error: Changes to the project config are not possible while in read-only mode.
```

Our deploy script runs `./craft project-config/sync --force`.

If I run `project-config/rebuild` both locally and on the server (when the environment is set to dev) the only difference between the two regenerated files is the modified date. As far as I can tell there is no reason for Craft making changes to the project config when in the production environment, it should only ever be reading from it.

This is the stack-trace from our most recent failed deployment:
```
2019-10-10 13:38:38 [-][-][-][error][yii\base\NotSupportedException] yii\base\NotSupportedException: Changes to the project config are not possible while in read-only mode. in /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php:354
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/services/Matrix.php(305): craft\services\ProjectConfig->set('matrixBlockType...', Array)
#1 /var/www/html/vendor/craftcms/cms/src/services/Matrix.php(630): craft\services\Matrix->saveBlockType(Object(craft\models\MatrixBlockType), false)
#2 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(865): craft\services\Matrix->saveSettings(Object(craft\fields\Matrix), false)
#3 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(1567): craft\fields\Matrix->afterSave(false)
#4 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(832): craft\services\Fields->applyFieldSave('0ee7edda-b9f6-4...', Array, 'global')
#5 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(865): craft\services\Fields->handleChangedField(Object(craft\events\ConfigEvent))
#6 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#7 /var/www/html/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#8 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(553): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#9 /var/www/html/vendor/craftcms/cms/src/helpers/ProjectConfig.php(64): craft\services\ProjectConfig->processConfigChanges('fields.0ee7edda...')
#10 /var/www/html/vendor/craftcms/cms/src/services/Sections.php(594): craft\helpers\ProjectConfig::ensureAllFieldsProcessed()
#11 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(865): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#12 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#13 /var/www/html/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#14 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(553): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#15 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(859): craft\services\ProjectConfig->processConfigChanges('sections.367e2a...')
#16 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#17 /var/www/html/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#18 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(553): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#19 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(940): craft\services\ProjectConfig->processConfigChanges('sections.367e2a...')
#20 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(435): craft\services\ProjectConfig->_applyChanges(Array)
#21 /var/www/html/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(87): craft\services\ProjectConfig->applyYamlChanges()
#22 [internal function]: craft\console\controllers\ProjectConfigController->actionSync()
#23 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#25 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('sync', Array)
#26 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('sync', Array)
#27 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('sync', Array)
#28 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#29 /var/www/html/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('project-config/...', Array)
#30 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#31 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#32 /var/www/html/craft(22): yii\base\Application->run()
#33 {main}
```

### Additional info

- Craft version: 3.3.8
- PHP version: 7.3.9
- Database driver & version: PostgreSQL 11.5

**Comment by andris-sevcenko** [comment]
Can you send over a DB dump, `composer.lock` file, `composer.json` file, and the `project.yaml` file you're trying to apply to support@craftcms.com, referencing this ticket, please?

**Comment by Tam** [comment]
@andris-sevcenko I don't have a db dump to hand that would be of any use to you atm since we re-synced it manually (sorry!). When one crops up I'll send it to you!

**Comment by andris-sevcenko** [comment]
Alright, closing this for now, then. If this happens again, just email us with the files mentioned above. Maybe it's also worth to include the `storage/config-backups` folder.

**Comment by dillonbailey** [comment]
@andris-sevcenko can this please be re-opened? We are currently experiencing the exact same issue and should be able to provide all of the requested files.

**Comment by andris-sevcenko** [comment]
Sure, can you send the files over, please?

**Comment by colinmeinke** [comment]
@andris-sevcenko same issue for me. `./craft project-config/sync` on an env where `allowAdminChanges` is `false` regularly results in `error: Changes to the project config are not possible while in read-only mode`.

If I run `./craft project-config/sync` a second time it works successfully, no error.

If I run `./craft project-config/sync` on the same db dump in an env where `allowAdminChanges` is `true` it works successfully first time, and makes no changes to the `project.yaml`.

**Comment by colinmeinke** [comment]
@andris-sevcenko sure, already sent :) Let me know if you need anything else.

**Comment by andris-sevcenko** [comment]
Thanks, all fixed for the next release!

To get the fix early, change your `craftcms/cms` requirement in `composer.json` to:

```
"require": {
  "craftcms/cms": "dev-develop#01a30d86ac7a6d096a4af246cc234d208297ea97 as 3.3.14",
  "...": "..."
}
```

Then run `composer update`.

**Comment by colinmeinke** [comment]
@andris-sevcenko thank you!
