### ISSUE TITLE
Setup error when running "composer create-project craftcms/craft"

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#5083]
Simply following the [installation instructions](https://docs.craftcms.com/v3/installation.html), running `composer create-project craftcms/craft <Path>`errors.

```
@php craft setup/welcome
Exception 'craft\errors\DbConnectException' with message 'Craft CMS can’t connect to the database with the credentials in config/db.php.'
```

```
Script @php craft setup/welcome handling the post-create-project-cmd event returned with error code 1
```

I don't think that the `create-project` command should be running any setup commands by default, as users wouldn't have yet had a chance to add their environmental settings yet. If this is intended, installation docs should be updated to reflect the new install process.

Not yet sure if these errors affect anything with the install process. I assume I can just ignore the error and continue my setup as normal.

**Comment by jsunsawyer** [comment]
It looks like a `SECURITY_KEY` is not being set as part of the install process.

**Comment by aryazar86** [comment]
I've also started getting this issue.

**Comment by aryazar86** [comment]
From my Docker logs: 

```
16:05:09 Writing lock file
16:05:09 Generating optimized autoload files
16:05:09 > @php -r "copy('.env.example', '.env');"
16:05:09 > @php -r "unlink('composer.json');"
16:05:09 > @php -r "unlink('LICENSE.md');"
16:05:09 > @php -r "unlink('README.md');"
16:05:09 > @php -r "rename('composer.json.default', 'composer.json');"
16:05:09 Generating optimized autoload filesGenerated optimized autoload files containing 3385 classes
16:05:09 > @php craft setup/welcome
16:05:09 Exception 'craft\errors\DbConnectException' with message 'Craft CMS can’t connect to the database with the credentials in config/db.php.'
16:05:09 
16:05:09 in /app/vendor/craftcms/cms/src/db/Connection.php:193
16:05:09 
16:05:09 Stack trace:
16:05:09 #0 /app/vendor/yiisoft/yii2/db/Connection.php(1012): craft\db\Connection->open()
16:05:09 #1 /app/vendor/yiisoft/yii2/db/Connection.php(999): yii\db\Connection->getMasterPdo()
16:05:09 #2 /app/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(380): yii\db\Connection->getSlavePdo()
16:05:09 #3 /app/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(399): yii\db\mysql\QueryBuilder->supportsFractionalSeconds()
16:05:09 #4 /app/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(57): yii\db\mysql\QueryBuilder->defaultTimeTypeMap()
16:05:09 #5 /app/vendor/craftcms/cms/src/db/mysql/QueryBuilder.php(27): yii\db\mysql\QueryBuilder->init()
16:05:09 #6 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\db\mysql\QueryBuilder->init()
16:05:09 #7 /app/vendor/yiisoft/yii2/db/QueryBuilder.php(116): yii\base\BaseObject->__construct(Array)
16:05:09 #8 /app/vendor/craftcms/cms/src/db/mysql/Schema.php(70): yii\db\QueryBuilder->__construct(Object(craft\db\Connection), Array)
16:05:09 #9 /app/vendor/yiisoft/yii2/db/Schema.php(249): craft\db\mysql\Schema->createQueryBuilder()
16:05:09 #10 /app/vendor/yiisoft/yii2/db/Connection.php(846): yii\db\Schema->getQueryBuilder()
16:05:09 #11 /app/vendor/yiisoft/yii2/db/Query.php(146): yii\db\Connection->getQueryBuilder()
16:05:09 #12 /app/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Query->createCommand(Object(craft\db\Connection))
16:05:09 #13 /app/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
16:05:09 #14 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(567): craft\db\Query->one()
16:05:09 #15 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(256): craft\console\Application->getInfo(true)
16:05:09 #16 /app/vendor/craftcms/cms/src/helpers/App.php(534): craft\console\Application->getIsInstalled()
16:05:09 #17 /app/vendor/craftcms/cms/src/config/app.php(231): craft\helpers\App::projectConfigConfig()
16:05:09 #18 [internal function]: {closure}()
16:05:09 #19 /app/vendor/yiisoft/yii2/di/Container.php(508): call_user_func_array(Object(Closure), Array)
16:05:09 #20 /app/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
16:05:09 #21 /app/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
16:05:09 #22 /app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('projectConfig', true)
16:05:09 #23 /app/vendor/craftcms/cms/src/console/Application.php(162): yii\base\Module->get('projectConfig', true)
16:05:09 #24 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1205): craft\console\Application->get('projectConfig')
16:05:09 #25 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1368): craft\console\Application->getProjectConfig()
16:05:09 #26 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1329): craft\console\Application->_setTimeZone()
16:05:09 #27 /app/vendor/craftcms/cms/src/console/Application.php(63): craft\console\Application->_preInit()
16:05:09 #28 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
16:05:09 #29 /app/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
16:05:09 #30 /app/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
16:05:09 #31 /app/vendor/craftcms/cms/src/console/Application.php(54): yii\console\Application->__construct(Array)
16:05:09 #32 [internal function]: craft\console\Application->__construct(Array)
16:05:09 #33 /app/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
16:05:09 #34 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\console\\A...', Array, Array)
16:05:09 #35 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\console\\A...', Array, Array)
16:05:09 #36 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(244): yii\BaseYii::createObject(Array)
16:05:09 #37 /app/vendor/craftcms/cms/bootstrap/console.php(34): require('/app/vendor/cra...')
16:05:09 #38 /app/craft(21): require('/app/vendor/cra...')
16:05:09 #39 {main}
16:05:09 Script @php craft setup/welcome handling the post-create-project-cmd event returned with error code 1
16:05:09 The command '/bin/sh -c rm -rf /app/ &&   /tmp/composer.phar create-project craftcms/craft /app/' returned a non-zero code: 1
16:05:09 ERROR: exit status 1
```

**Comment by aghull** [comment]
:+1:

**Comment by aghull** [comment]
@brandonkelly Seems like introduced here https://github.com/craftcms/cms/commit/0dfd3b4cee3681f8178f3970bb9a355d35c5c49a#diff-d425917d44ba312029cbb04807d3472f

**Comment by brandonkelly** [comment]
Thanks all, just got this fixed for the next release – we’ll get that out ASAP.

In the meantime to get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#6c488c021a5f08ff7506d34415c3885cc01b34e0 as 3.3.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by Samuel91** [comment]
Same error today by installing craft via composer.

**Comment by brandonkelly** [comment]
@Samuel91 Please write into support@craftcms.com with details about what’s going wrong – we can help you from there.
