### ISSUE TITLE
json_encode filter fails on console requests

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#5150]
https://github.com/craftcms/cms/blob/6bcc6538dcabfa2601b851a461b055efc779015c/src/web/twig/Extension.php#L394

The `json_encode` Twig filter appears to be calling `getContentType()` on the Response object, which results in an exception if the request happens to be a console request. I encountered this on multiple failed _Updating Search Indexes_ jobs.

```
2019-10-23 11:20:51 [-][-][-][error][craft\queue\QueueLogBehavior::afterError]  [2435] Updating search indexes (attempt: 1) - Error (time: 0.586s): An exception has been thrown during the rendering of a template ("Calling unknown method: yii\console\Response::getContentType()").
2019-10-23 11:20:51 [-][-][-][error][Twig\Error\RuntimeError] yii\base\UnknownMethodException: Calling unknown method: yii\console\Response::getContentType() in …/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 …/vendor/craftcms/cms/src/web/twig/Extension.php(393): yii\base\Component->__call('getContentType', Array)
#1 …/storage/runtime/compiled_templates/fa/faf275a266167ab2b1f7c1deaaf20beeb9b6fd21c20989b9d39b5b0e4bf2a284.php(54): craft\web\twig\Extension->jsonEncodeFilter(Array)
#2 …/vendor/twig/twig/src/Extension/CoreExtension.php(1537): __TwigTemplate_d9aefefa425a456506e2f7b88518406db646cccb7550c03cda4f0a872c9046ba->{closure}(Object(craft\models\Section), 5)
#3 …/storage/runtime/compiled_templates/fa/faf275a266167ab2b1f7c1deaaf20beeb9b6fd21c20989b9d39b5b0e4bf2a284.php(54): twig_array_map(Array, Object(Closure))
#4 …/vendor/twig/twig/src/Template.php(407): __TwigTemplate_d9aefefa425a456506e2f7b88518406db646cccb7550c03cda4f0a872c9046ba->doDisplay(Array, Array)
#5 …/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#6 …/storage/runtime/compiled_templates/24/2425689897653b123c2f85a37119f2e6ba8888d8f7f3df2a282e1ddb1a450e46.php(38): Twig\Template->display(Array)
#7 …/vendor/twig/twig/src/Template.php(407): __TwigTemplate_ea7fae42eae34fb16b377b22aea60f4fe3260844e6def0055da42e75e4b877ce->doDisplay(Array, Array)
#8 …/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#9 …/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#10 …/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#11 …/vendor/craftcms/cms/src/web/View.php(466): Twig\TemplateWrapper->render(Array)
#12 …/vendor/lewisjenkins/craft-dynamic-fields/src/fields/Dropdown.php(49): craft\web\View->renderString('{% include '_fi...', Array)
#13 …/vendor/craftcms/cms/src/base/Element.php(2283): lewisjenkins\craftdynamicfields\fields\Dropdown->normalizeValue('{"type":"index"...', Object(craft\elements\MatrixBlock))
#14 …/vendor/craftcms/cms/src/base/Element.php(1855): craft\base\Element->normalizeFieldValue('sections')
#15 …/vendor/craftcms/cms/src/fields/Matrix.php(706): craft\base\Element->getFieldValue('sections')
...
```

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks for reporting!
