### ISSUE TITLE
Syncing project-config attempts to write to project.yaml when allowAdminChanges is false

### ISSUE THREAD

**Issue by mtwalsh** [craftcms/cms#5157]
### Description

When running `./craft project-config/sync` the command seems to fail as the process tries to write to the `project.yaml` file. I don't understand why this would be attempted as the environment has `allowAdminChanges` set to false.

### Steps to reproduce

In an environment where `'allowAdminChanges' => false` in general.php.

1. Run `./craft project-config/sync`
2. Observe similar output to below:

```
Applying changes from project.yaml ... done
PHP Warning 'yii\base\ErrorException' with message 'file_put_contents(/websites/project-name/releases/1/config/project.yaml): failed to open stream: Permission denied'

in /websites/project-name/releases/1/vendor/craftcms/cms/src/helpers/FileHelper.php:376

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'file_put_conten...', '/websites/project-...', 376, Array)
#1 /websites/project-name/releases/1/vendor/craftcms/cms/src/helpers/FileHelper.php(376): file_put_contents('/websites/project-...', 'assets:\n  tempV...', 0)
#2 /websites/project-name/releases/1/vendor/craftcms/cms/src/services/ProjectConfig.php(614): craft\helpers\FileHelper::writeToFile('/websites/project-...', 'assets:\n  tempV...')
#3 [internal function]: craft\services\ProjectConfig->saveModifiedConfigData(Object(yii\base\Event))
#4 /websites/project-name/releases/1/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(yii\base\Event))
#5 /websites/project-name/releases/1/vendor/yiisoft/yii2/base/Application.php(389): yii\base\Component->trigger('afterRequest')
#6 /websites/project-name/releases/1/craft(27): yii\base\Application->run()
#7 {main}
```

### Additional info

- Craft version: 3.3.11
- PHP version: 7.1.28
- Database driver & version: MySQL 5.7.27

**Comment by andris-sevcenko** [comment]
Are you actually using the `project.yaml` file in the first place? Does it exist before you run this command?

**Comment by jamiewade** [comment]
@andris-sevcenko Yes, and yes 😃 Michael is away for a few days so let me know if you need anything else!

**Comment by andris-sevcenko** [comment]
@jamiewade Huh. Do you have a site where you can reproduce this right now? If so, can you send over a DB dump and your `composer.json`, `composer.lock` and `project.yaml` files to support@craftcms.com and reference this issue? Thank you!

**Comment by verbeeksteven** [comment]
I also have this issue. My hosting environment is read only so I have the above settings and fairly often while doing project config it just does a bunch of 

```
- childBlocks:
-      - header
-      - text
-      - images
-      - buttonBlock
+ childBlocks: '["header","text","images","buttonBlock"]'
```

And if I do a project-config/rebuild it then does

```
+ childBlocks:
+      - header
+      - text
+      - images
+      - buttonBlock
- childBlocks: '["header","text","images","buttonBlock"]'
```

I've got about 50 commits of nothing but this going back and forth. In my particular instance it does seem to be only neo blocks, not sure if that is the same for you.

But basically it does want to write "changes" to project.yaml on `project-config/sync` which should ONLY sync the file to the database, there shouldn't be any instance where the file would need to be updated. Because if it fails, the database will be out of sync and will need to be resync'd. If it succeeds there shouldn't be any differences.

**Comment by mtwalsh** [comment]
@verbeeksteven The project we hit this issue on was not using Neo and we haven't had any repeat occurrences recently.

**Comment by andris-sevcenko** [comment]
@verbeeksteven Have you tried running rebuild locally to normalize the way `childBlocks` is stored in the project config?

Also, try updating to the latest versions of everything and, if the issue still persists, can you send over a DB dump, the `composer.json` and `composer.lock` files of the site where this is happening as well as the `project.yaml` file you're trying to sync?

**Comment by andris-sevcenko** [comment]
Closing due to inactivity.

**Comment by jedimonkey** [comment]
I have this happen all the time with one project, and yet to work out what's causing it. It pretty much consistently occurs when I run the sync through the web browser, if I run it through the cli, it's generally fine, however it gave me this error today:
```
Applying changes from project.yaml ... done
PHP Warning 'yii\base\ErrorException' with message 'file_put_contents(/usr/share/nginx/storage/config-deltas/delta.yaml): failed to open stream: Permission denied'

in /usr/share/nginx/vendor/craftcms/cms/src/services/ProjectConfig.php:1588

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'file_put_conten...', '/usr/share/ngin...', 1588, Array)
#1 /usr/share/nginx/vendor/craftcms/cms/src/services/ProjectConfig.php(1588): file_put_contents('/usr/share/ngin...', 'dateApplied: '2...')
#2 /usr/share/nginx/vendor/craftcms/cms/src/services/ProjectConfig.php(827): craft\services\ProjectConfig->_storeYamlHistory(Array)
#3 [internal function]: craft\services\ProjectConfig->saveModifiedConfigData(Object(yii\base\Event))
#4 /usr/share/nginx/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(yii\base\Event))
#5 /usr/share/nginx/vendor/yiisoft/yii2/base/Application.php(389): yii\base\Component->trigger('afterRequest')
#6 /usr/share/nginx/craft(22): yii\base\Application->run()
#7 {main}
```

Ran the the sync again and it worked.... Happy to supply you with details to debug it.

**Comment by andris-sevcenko** [comment]
@jedimonkey if you get to a point where you can reliably reproduce it, we'd appreciate DB dump, `composer.json`, `composer.lock`, and the `project.yaml` file that is causing the issue over at support@craftcms.com or delivered otherwise.

As far as the permission issue goes - the projet config change delta is saved after all the changes have been applied already, so the next time around Craft wouldn't attempt to write that file.

The `storage` folder [needs write permissions](https://docs.craftcms.com/v3/installation.html#step-2-set-the-file-permissions), though.
