### ISSUE TITLE
Throws error when saving dropdown field by function

### ISSUE THREAD

**Issue by pdaleramirez** [craftcms/cms#5172]
### Description
I am trying to create a dropdown field within my code but whenever i pass a integer value it throws this error `Object of class craft\fields\data\SingleOptionFieldData could not be converted to int`
Here is the code:

### Steps to reproduce
Step 1: Run this and save the field
```
$config = [
            "type"    => Dropdown::class,
            "name"    => "Release Dates",
            "handle"  => 'releaseDate',
            "groupId" => 1,
            'settings' => [
                'options' => [
                    [
                        'label' => 2017,
                        'value' => 2017
                    ],
                    [
                        'label' => 2018,
                        'value' => 2018
                    ],
                    [
                        'label' => 2019,
                        'value' => 2019
                    ]
                ]
            ]
        ];

        $fieldByHandle = Craft::$app->getFields()->createField($config);

        Craft::$app->getFields()->saveField($fieldByHandle);
```
Step 2: Save the field with value to an entry
```
        $entry = new Entry();
        $entry->sectionId = 11;
        $entry->typeId = 11;
        $entry->setFieldValue('releaseDate', 2017);
        Craft::$app->getElements()->saveElement($entry);
```
This is where it throws the error but when make the option value to string from 2017 to '2017', 2018 to '2018' and 2019 to '2019' the error won't be thrown.
### Additional info

- Craft version: 3.3.1
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Please search for that error in your logs (`storage/logs/web.log` or `console.log` depending on the request type), and post the stack trace that follows it.

**Comment by pdaleramirez** [comment]
Here's the Stack trace:
```
2019-10-31 07:50:51 [-][1][39bc3bad3ffeef2af1c61b4780b047f4][error][yii\base\ErrorException:8] yii\base\ErrorException: Object of class craft\fields\data\SingleOptionFieldData could not be converted to int in C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\helpers\BaseArrayHelper.php:829
Stack trace:
#0 C:\MAMP_\htdocs\craft3\vendor\craftcms\cms\src\web\ErrorHandler.php(80): yii\base\ErrorHandler->handleError(8, 'Object of class...', 'C:\\MAMP_\\htdocs...', 829)
#1 [internal function]: craft\web\ErrorHandler->handleError(8, 'Object of class...', 'C:\\MAMP_\\htdocs...', 829, Array)
#2 C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\helpers\BaseArrayHelper.php(829): in_array(Object(craft\fields\data\SingleOptionFieldData), Array, false)
#3 C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\validators\RangeValidator.php(84): yii\helpers\BaseArrayHelper::isIn(Object(craft\fields\data\SingleOptionFieldData), Array, false)
#4 C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\validators\Validator.php(303): yii\validators\RangeValidator->validateValue(Object(craft\fields\data\SingleOptionFieldData))
#5 C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\validators\RangeValidator.php(99): yii\validators\Validator->validateAttribute(Object(craft\elements\Entry), 'field:releaseDa...')
#6 C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\validators\Validator.php(257): yii\validators\RangeValidator->validateAttribute(Object(craft\elements\Entry), 'field:releaseDa...')
#7 C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\base\Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#8 C:\MAMP_\htdocs\craft3\vendor\craftcms\cms\src\services\Elements.php(1914): yii\base\Model->validate()
#9 C:\MAMP_\htdocs\craft3\vendor\craftcms\cms\src\services\Elements.php(525): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true)
#10 C:\MAMP_\htdocs\craft3\localplugins\pdaleramirez\super-filter\src\controllers\SuperFilterController.php(133): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#11 [internal function]: pdaleramirez\superfilter\controllers\SuperFilterController->actionTest()
#12 C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#13 C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 C:\MAMP_\htdocs\craft3\vendor\craftcms\cms\src\web\Controller.php(187): yii\base\Controller->runAction('test', Array)
#15 C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('test', Array)
#16 C:\MAMP_\htdocs\craft3\vendor\craftcms\cms\src\web\Application.php(299): yii\base\Module->runAction('super-filter/su...', Array)
#17 C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\web\Application.php(103): craft\web\Application->runAction('super-filter/su...', Array)
#18 C:\MAMP_\htdocs\craft3\vendor\craftcms\cms\src\web\Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#19 C:\MAMP_\htdocs\craft3\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 C:\MAMP_\htdocs\craft3\web\index.php(21): yii\base\Application->run()
#21 {main}
```

**Comment by brandonkelly** [comment]
Thanks, just got that fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#cd546df024ba03eb0b1d9bbd74ca6b3fc0cbf7f1 as 3.3.14",
  "...": "..."
}
```

Then run `composer update`.

**Comment by pdaleramirez** [comment]
Thank you
