### ISSUE TITLE
project-config/rebuild fails after craft 2 upgrade (missing system block)

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5189]
Following a craft 2 upgrade, I tried to build a fresh `project.yaml` via `craft project-config/rebuild`.

Got this error:

```
$ docker-compose exec app bin/craft project-config/rebuild
Rebuilding the project config from the current state ... error: Undefined index: system
[2019-10-31 12:42:47] craftcms.ERROR: yii\base\ErrorException: Undefined index: system in /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php:900 Stack trace: #0 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(900): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/app/vendor/com...', 900, Array) #1 /app/vendor/composer/craftcms/cms/src/console/controllers/ProjectConfigController.php(112): craft\services\ProjectConfig->rebuild() #2 [internal function]: craft\console\controllers\ProjectConfigController->actionRebuild() #3 /app/vendor/composer/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #4 /app/vendor/composer/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #5 /app/vendor/composer/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('rebuild', Array) #6 /app/vendor/composer/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('rebuild', Array) #7 /app/vendor/composer/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('rebuild', Array) #8 /app/vendor/composer/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array) #9 /app/vendor/composer/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('project-config/...', Array) #10 /app/vendor/composer/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array) #11 /app/vendor/composer/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request)) #12 /app/bin/craft(7): yii\base\Application->run() #13 {main} {"trace":[],"memory":24057584,"category":"yii\\base\\ErrorException:8","exception":"[object] (yii\\base\\ErrorException(code: 8): Undefined index: system at /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php:900)"} []
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Turns out, after the migration, I had to go the CP and "reactivate" my edition to Pro, then it worked.

**Comment by andris-sevcenko** [comment]
@timkelty any chance you saved the stack trace that appeared in your log files? :)

**Comment by timkelty** [comment]
@andris-sevcenko I think I can reproduce it…if I do I'll post it here.

FYI I also discovered the issues weren't isolate to pro/trial. Other things missing from `system` caused things barf in the CP.

**Comment by andris-sevcenko** [comment]
And this is just in scenarios when upgrading from Craft 2. Is this to the latest version of Craft? (3.3.14)

**Comment by timkelty** [comment]
yep, so far. (yes lastest).

**Comment by andris-sevcenko** [comment]
I'd be very interested in that stack trace :)

**Comment by timkelty** [comment]
@andris-sevcenko I'll see if I can recreate the process…but to be clear: the only error log trace I'm going  see is from that `project-config/rebuild` command - which you should be able to reproduce by deleting your `system` block from project.yaml.

There weren't any errors from the migration or initial project.yaml creation (made on first request after migration).

**Comment by andris-sevcenko** [comment]
Yeah, the point is that `system` block should not ever be deleted.

**Comment by andris-sevcenko** [comment]
I'll spin up a Craft 2 install and I'll see what happens as I bring it up to 3.3.14

**Comment by andris-sevcenko** [comment]
@timkelty is it safe to assume that this is fixed when updating to 3.4?

**Comment by timkelty** [comment]
@andris-sevcenko indeed, close 'er up.

**Comment by andris-sevcenko** [comment]
Gladly!
