### ISSUE TITLE
PostgreSQL 12: obsolete pg_constraint.consrc column is no more

### ISSUE THREAD

**Issue by DavidOliver** [craftcms/cms#5245]
### Description

Fresh installation fails when using PostgreSQL 12.

```
    > populating the info table ... done
    > saving default site data ... done
    > saving the first user ... done
Exception: SQLSTATE[42703]: Undefined column: 7 ERROR:  column c.consrc does not exist
LINE 10:     "c"."consrc" AS "check_expr"
             ^
HINT:  Perhaps you meant to reference the column "c.conkey" or the column "c.conbin".
The SQL being executed was: SELECT
    "c"."conname" AS "name",
    "a"."attname" AS "column_name",
    "c"."contype" AS "type",
    "ftcns"."nspname" AS "foreign_table_schema",
    "ftc"."relname" AS "foreign_table_name",
    "fa"."attname" AS "foreign_column_name",
    "c"."confupdtype" AS "on_update",
    "c"."confdeltype" AS "on_delete",
    "c"."consrc" AS "check_expr"
FROM "pg_class" AS "tc"
INNER JOIN "pg_namespace" AS "tcns"
    ON "tcns"."oid" = "tc"."relnamespace"
INNER JOIN "pg_constraint" AS "c"
    ON "c"."conrelid" = "tc"."oid"
INNER JOIN "pg_attribute" AS "a"
    ON "a"."attrelid" = "c"."conrelid" AND "a"."attnum" = ANY ("c"."conkey")
LEFT JOIN "pg_class" AS "ftc"
    ON "ftc"."oid" = "c"."confrelid"
LEFT JOIN "pg_namespace" AS "ftcns"
    ON "ftcns"."oid" = "ftc"."relnamespace"
LEFT JOIN "pg_attribute" "fa"
    ON "fa"."attrelid" = "c"."confrelid" AND "fa"."attnum" = ANY ("c"."confkey")
WHERE "tcns"."nspname" = 'public' AND "tc"."relname" = 'userpreferences'
ORDER BY "a"."attnum" ASC, "fa"."attnum" ASC (/m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT\n    "c"....')
#1 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT\n    "c"....')
#2 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/pgsql/Schema.php(673): yii\db\Command->queryAll()
#4 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/pgsql/Schema.php(205): yii\db\pgsql\Schema->loadTableConstraints('userpreferences', 'primaryKey')
#5 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/Schema.php(744): yii\db\pgsql\Schema->loadTablePrimaryKey('userpreferences')
#6 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/ConstraintFinderTrait.php(101): yii\db\Schema->getTableMetadata('{{%userpreferen...', 'primaryKey', false)
#7 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/QueryBuilder.php(574): yii\db\pgsql\Schema->getTablePrimaryKey('{{%userpreferen...')
#8 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/QueryBuilder.php(546): yii\db\QueryBuilder->getTableUniqueColumnNames('{{%userpreferen...', Array, Array)
#9 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/pgsql/QueryBuilder.php(337): yii\db\QueryBuilder->prepareUpsertColumns('{{%userpreferen...', Array, Array)
#10 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/pgsql/QueryBuilder.php(323): yii\db\pgsql\QueryBuilder->newUpsert('{{%userpreferen...', Array, Array, Array)
#11 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/db/Command.php(546): yii\db\pgsql\QueryBuilder->upsert('{{%userpreferen...', Array, Array, Array)
#12 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/db/Command.php(124): yii\db\Command->upsert('{{%userpreferen...', Array, Array, Array)
#13 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/services/Users.php(303): craft\db\Command->upsert('{{%userpreferen...', Array, Array, Array, false)
#14 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/migrations/Install.php(1076): craft\services\Users->saveUserPreferences(Object(craft\elements\User), Array)
#15 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/migrations/Install.php(73): craft\migrations\Install->insertDefaultData()
#16 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/db/Migration.php(58): craft\migrations\Install->safeUp()
#17 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
#18 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/controllers/InstallController.php(161): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
#19 [internal function]: craft\console\controllers\InstallController->actionCraft()
#20 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#22 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#23 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('', Array)
#24 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
#25 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
#26 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('install', Array)
#27 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/controllers/SetupController.php(124): craft\console\Application->runAction('install')
#28 [internal function]: craft\console\controllers\SetupController->actionIndex()
#29 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#31 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#32 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('', Array)
#33 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
#34 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('setup', Array)
#35 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('setup', Array)
#36 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('setup', Array)
#37 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#38 /m/projects/f1_sound/project-craft3/craft(22): yii\base\Application->run()
#39 {main}
Exception 'craft\errors\MigrationException' with message 'An error occurred while executing the "craft\migrations\Install migration: SQLSTATE[42703]: Undefined column: 7 ERROR:  column c.consrc does not exist
LINE 10:     "c"."consrc" AS "check_expr"
             ^
HINT:  Perhaps you meant to reference the column "c.conkey" or the column "c.conbin".
The SQL being executed was: SELECT
    "c"."conname" AS "name",
    "a"."attname" AS "column_name",
    "c"."contype" AS "type",
    "ftcns"."nspname" AS "foreign_table_schema",
    "ftc"."relname" AS "foreign_table_name",
    "fa"."attname" AS "foreign_column_name",
    "c"."confupdtype" AS "on_update",
    "c"."confdeltype" AS "on_delete",
    "c"."consrc" AS "check_expr"
FROM "pg_class" AS "tc"
INNER JOIN "pg_namespace" AS "tcns"
    ON "tcns"."oid" = "tc"."relnamespace"
INNER JOIN "pg_constraint" AS "c"
    ON "c"."conrelid" = "tc"."oid"
INNER JOIN "pg_attribute" AS "a"
    ON "a"."attrelid" = "c"."conrelid" AND "a"."attnum" = ANY ("c"."conkey")
LEFT JOIN "pg_class" AS "ftc"
    ON "ftc"."oid" = "c"."confrelid"
LEFT JOIN "pg_namespace" AS "ftcns"
    ON "ftcns"."oid" = "ftc"."relnamespace"
LEFT JOIN "pg_attribute" "fa"
    ON "fa"."attrelid" = "c"."confrelid" AND "fa"."attnum" = ANY ("c"."confkey")
WHERE "tcns"."nspname" = 'public' AND "tc"."relname" = 'userpreferences'
ORDER BY "a"."attnum" ASC, "fa"."attnum" ASC'

in /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/db/MigrationManager.php:256

Stack trace:
#0 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/controllers/InstallController.php(161): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
#1 [internal function]: craft\console\controllers\InstallController->actionCraft()
#2 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#5 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('', Array)
#6 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
#7 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
#8 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('install', Array)
#9 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/controllers/SetupController.php(124): craft\console\Application->runAction('install')
#10 [internal function]: craft\console\controllers\SetupController->actionIndex()
#11 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#14 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('', Array)
#15 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
#16 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('setup', Array)
#17 /m/projects/f1_sound/project-craft3/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('setup', Array)
#18 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('setup', Array)
#19 /m/projects/f1_sound/project-craft3/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#20 /m/projects/f1_sound/project-craft3/craft(22): yii\base\Application->run()
#21 {main}
```

### Additional info

- Craft version: 3.3.15
- PHP version: 7.3.11-1+ubuntu18.04.1+deb.sury.org+1
- Database driver & version: pgsql, 12.1-1.pgdg18.04+1

This seems to be the issue: https://github.com/sqlalchemy/sqlalchemy/issues/4463

> Reflection of check constraints against PostgreSQL databases queries the pg_constraint.consrc column. This has been deprecated in PostgreSQL 12, so constraint reflection will fail against that version.

https://www.postgresql.org/docs/12/release-12.html

https://www.postgresql.org/docs/12/catalog-pg-constraint.html

**Comment by brandonkelly** [comment]
Looks like this was fixed in Yii 2.0.29 per https://github.com/yiisoft/yii2/commit/09eacd8dc1120113032976099fd07290a4d37cd3, so I’ve just bumped Craft’s Yii requirement for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#7c12caed2f627e9939986a69dd86dab8a4a2ae11 as 3.3.15",
  "...": "..."
}
```

Then run `composer update`.
