### ISSUE TITLE
Channel without a URL is claiming undefined variable: previewTargets

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#5264]
### Description
I created a channel for client testimonials on a client site, but these are reusable component entries so they do not have their own page URIs or template.

I haven't set anything up to do with previewing for this project because I'm on a solo licence working locally.

When I go to edit one, I get the following stacktrace:

```
yii\base\ErrorException: Undefined variable: previewTargets in /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/base/Element.php:1558
Stack trace:
#0 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(8, 'Undefined varia...', '/Users/jaycolle...', 1558)
#1 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/base/Element.php(1558): craft\web\ErrorHandler->handleError(8, 'Undefined varia...', '/Users/jaycolle...', 1558, Array)
#2 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Extension/CoreExtension.php(1495): craft\base\Element->getPreviewTargets()
#3 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\Entry), 'getPreviewTarge...', Array, 'method', false, false)
#4 /Users/jaycollett/Sites/jaycollett/project-name/build/storage/runtime/compiled_templates/5d/5d4c08369ff61ce6373d1f34b4f9fad615ee4e5cd1e51739ed3087557717bdd0.php(62): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\Entry), 'getPreviewTarge...', Array, 'method')
#5 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_fa9e34f1189c76a6473e46fa203ab79d1287a81cfc2e3f11cc0d986b93a8cb7d->doDisplay(Array, Array)
#6 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /Users/jaycollett/Sites/jaycollett/project-name/build/storage/runtime/compiled_templates/44/44edae9fa4b0b49b01fcf58104c9a9a1a650933b815c3aa8fb5ee5e7371c8684.php(120): Twig\Template->display(Array, Array)
#8 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_8542f41a2bd3a386e8c2440d40b5c34e62f9d743a35b7cde47ea702036e113e5->doDisplay(Array, Array)
#9 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#11 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#12 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#13 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/View.php(400): Twig\Environment->render('entries/_edit', Array)
#14 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('entries/_edit', Array)
#15 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/Controller.php(244): craft\web\View->renderPageTemplate('entries/_edit', Array, 'cp')
#16 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/controllers/EntriesController.php(261): craft\web\Controller->renderTemplate('entries/_edit', Array)
#17 [internal function]: craft\controllers\EntriesController->actionEditEntry(Object(craft\models\Section), 60, NULL, NULL, Object(craft\models\Site), Object(craft\elements\Entry))
#18 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#20 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('edit-entry', Array)
#21 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#22 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('entries/edit-en...', Array)
#23 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#24 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#25 /Users/jaycollett/Sites/jaycollett/project-name/build/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /Users/jaycollett/Sites/jaycollett/project-name/build/public/index.php(21): yii\base\Application->run()
#27 {main}
```

### Steps to reproduce
1. Create new channel with some fields
2. Do not give this channel a URI or template URL
3. Go to edit an entry in the channel

### Additional info

- Craft version: 3.4.0-alpha.1
- PHP version: 7.3.8

**Comment by JayBox325** [comment]
UPDATE: This is happening for all channels, but not my structure.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed – run `composer update` and you’ll be back in business.

**Comment by JayBox325** [comment]
Thanks for the quick fix, @brandonkelly
