### ISSUE TITLE
"An unknown error occurred." error message on Trashed status.

### ISSUE THREAD

**Issue by Saboteur777** [craftcms/cms#5287]
### Description

I receive an `An unknown error occurred.` flash message when I try to view the trashed entries of a section. 

I found this in the logs: 

```
2019-11-30 13:16:03 [-][1][-][error][Twig\Error\RuntimeError] yii\base\InvalidConfigException: Invalid author ID: 128 in /var/www/vendor/craftcms/cms/src/elements/Entry.php:888
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/elements/Entry.php(1016): craft\elements\Entry->getAuthor()
#1 /var/www/vendor/craftcms/cms/src/base/Element.php(2132): craft\elements\Entry->tableAttributeHtml('author')
#2 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1495): craft\base\Element->getTableAttributeHtml('author')
#3 /var/www/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\Entry), 'getTableAttribu...', Array, 'method', false, false)
#4 /var/www/storage/runtime/compiled_templates/60/600768a44383860a411d17f8273cda20db99a146a5c6b9fa24eea24d280db23e.php(157): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\Entry), 'getTableAttribu...', Array, 'method')
#5 /var/www/vendor/twig/twig/src/Template.php(407): __TwigTemplate_a27f32da4d861b9d2ffe1e9a99c287b7836b39a9d356e4777132e9ae90a035ba->doDisplay(Array, Array)
#6 /var/www/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /var/www/storage/runtime/compiled_templates/87/8741abebb48dd343fd0a5472f630d8bc09b5398e0e9a2b68f447e241a0cebb5a.php(96): Twig\Template->display(Array)
#8 /var/www/vendor/twig/twig/src/Template.php(407): __TwigTemplate_89bc8c3edebf50ef6aabea6e8d4271fd1c9886d22ab53e45e657caec6f1d57e4->doDisplay(Array, Array)
#9 /var/www/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /var/www/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#11 /var/www/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#12 /var/www/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#13 /var/www/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('_elements/table...', Array)
#14 /var/www/vendor/craftcms/cms/src/base/Element.php(550): craft\web\View->renderTemplate('_elements/table...', Array)
#15 /var/www/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(473): craft\base\Element::indexHtml(Object(craft\elements\db\EntryQuery), Array, Array, 'section:a32a8ae...', 'index', true, true)
#16 /var/www/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(130): craft\controllers\ElementIndexesController->elementResponseData(true, true)
#17 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
#18 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#20 /var/www/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('get-elements', Array)
#21 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-elements', Array)
#22 /var/www/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('element-indexes...', Array)
#23 /var/www/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('element-indexes...', Array)
#24 /var/www/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#25 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /var/www/web/index.php(21): yii\base\Application->run()
#27 {main}

Next Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Invalid author ID: 128"). in /var/www/vendor/craftcms/cms/src/templates/_elements/tableview/elements.html:25
Stack trace:
#0 /var/www/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#1 /var/www/storage/runtime/compiled_templates/87/8741abebb48dd343fd0a5472f630d8bc09b5398e0e9a2b68f447e241a0cebb5a.php(96): Twig\Template->display(Array)
#2 /var/www/vendor/twig/twig/src/Template.php(407): __TwigTemplate_89bc8c3edebf50ef6aabea6e8d4271fd1c9886d22ab53e45e657caec6f1d57e4->doDisplay(Array, Array)
#3 /var/www/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /var/www/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#5 /var/www/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#6 /var/www/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#7 /var/www/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('_elements/table...', Array)
#8 /var/www/vendor/craftcms/cms/src/base/Element.php(550): craft\web\View->renderTemplate('_elements/table...', Array)
#9 /var/www/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(473): craft\base\Element::indexHtml(Object(craft\elements\db\EntryQuery), Array, Array, 'section:a32a8ae...', 'index', true, true)
#10 /var/www/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(130): craft\controllers\ElementIndexesController->elementResponseData(true, true)
#11 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
#12 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('get-elements', Array)
#15 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-elements', Array)
#16 /var/www/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('element-indexes...', Array)
#17 /var/www/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('element-indexes...', Array)
#18 /var/www/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#19 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /var/www/web/index.php(21): yii\base\Application->run()
#21 {main}

```

### Steps to reproduce

1. Create a user. 
2. Create an entry with that user. 
3. Delete the entry. 
4. Delete the user. 
5. Go to Entries, select the Section of the deleted entry. 
6. Set status to `Trashed`. 
7. Error happens.

### Additional info

- Craft version: Craft Pro 3.3.16.3
- PHP version: 7.3.6
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

Plugin | Version
-- | --
Activity | 1.0.1
Bugsnag | 2.0.5
Concierge | 2.1.0
Country Select | 1.1.3
CP Field Inspect | 1.0.7
DigitalOcean Spaces Volume | 1.1.2
Environment Label | 3.1.5
Imager | v2.3.0
Image Resizer | 2.0.6
Imager Pretransform | 2.0.3
Imager Storage Driver for DigitalOcean Spaces | 1.0.0
Mailgun | 1.4.2
Maps | 3.7.3
Navigation | 1.1.14.1
Notifications | 1.1.1
Redactor | 2.4.0
SEO | 3.2.35
Snitch | 3.0.0
Splash | 3.0.5
Twigpack | 1.1.12
Twig Profiler | 1.0.1

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Please send your `composer.json` and `composer.lock` files, and a database backup, over to support@craftcms.com, and we can look into it from there.

**Comment by Saboteur777** [comment]
Thanks, sent it!

**Comment by thisisjamessmith** [comment]
This was the same error I reported here before Brandon changed the title and focus of the issue: https://github.com/craftcms/cms/issues/5293

My log file reported that there was an "unknown user" when attempting to list trashed entries.

**Comment by brandonkelly** [comment]
Thanks, we figured out how to reproduce and got it fixed for today’s release.

**Comment by Saboteur777** [comment]
:100:
