### ISSUE TITLE
LogicException Error show when accessing to Settings > Plugins

### ISSUE THREAD

**Issue by mersy** [craftcms/cms#5307]
### Description

LogicException Error show when accessing to Settings > Plugins （ /bpanel/settings/plugins ）
So I can't uninstall plugins.
Another Settings menu show well.

This error maybe occured around 3.3.15 and after some plugin installed.

<img width="1265" alt="Screen Shot 2019-12-05 at 13 05 03" src="https://user-images.githubusercontent.com/205165/70203389-1f70b200-1760-11ea-82ef-77f5b49bb4be.png">

Let me know what I check something , and how to uninstall some plugins on Craft CLI.

### Steps to reproduce

1. Access to Settings > System:Plugins

### Additional info

```
PHP version | 7.2.24
Linux 3.10.0-962.3.2.lve1.5.25.8.el7.x86_64
MySQL 5.5.5
GD 7.2.24
Craft Pro 3.3.17
```

```
LogicException: Cannot add self usage in /home/example.com/vendor/enshrined/svg-sanitize/src/ElementReference/Subject.php:97
Stack trace:
#0 /home/example.com/vendor/enshrined/svg-sanitize/src/ElementReference/Resolver.php(101): enshrined\svgSanitize\ElementReference\Subject->addUse(Object(enshrined\svgSanitize\ElementReference\Subject))
#1 /home/example.com/vendor/enshrined/svg-sanitize/src/ElementReference/Resolver.php(27): enshrined\svgSanitize\ElementReference\Resolver->processReferences()
#2 /home/example.com/vendor/enshrined/svg-sanitize/src/Sanitizer.php(211): enshrined\svgSanitize\ElementReference\Resolver->collect()
#3 /home/example.com/vendor/craftcms/cms/src/web/twig/Extension.php(1027): enshrined\svgSanitize\Sanitizer->sanitize('<?xml version="...')
#4 /home/example.com/storage/runtime/compiled_templates/46/46486432b77b7927a66da7be87691770839251fcbbe84996e9a03d3b83643372.php(108): craft\web\twig\Extension->svgFunction('<?xml version="...', true, true)
#5 /home/example.com/vendor/twig/twig/src/Template.php(184): __TwigTemplate_8c15c824e372a1cf12189927d3d22f3ccf607778362800d889ac771e01293c6a->block_content(Array, Array)
#6 /home/example.com/storage/runtime/compiled_templates/28/2864adbe69c8dbdc6cc1f0362dbb00c97deecb8923f59657f756091f8bfc28c3.php(727): Twig\Template->displayBlock('content', Array, Array)
#7 /home/example.com/vendor/twig/twig/src/Template.php(184): __TwigTemplate_fb0fcc48532d3dad2c1e04aeddeea8feabcb585284da9cf31ee88f024927838d->block_main(Array, Array)
#8 /home/example.com/storage/runtime/compiled_templates/28/2864adbe69c8dbdc6cc1f0362dbb00c97deecb8923f59657f756091f8bfc28c3.php(576): Twig\Template->displayBlock('main', Array, Array)
#9 /home/example.com/vendor/twig/twig/src/Template.php(184): __TwigTemplate_fb0fcc48532d3dad2c1e04aeddeea8feabcb585284da9cf31ee88f024927838d->block_body(Array, Array)
#10 /home/example.com/storage/runtime/compiled_templates/79/794ecb3d4a342159c00616753836aaf0a4ab634f04a932c27141cfa206c3a4cc.php(75): Twig\Template->displayBlock('body', Array, Array)
#11 /home/example.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_6572a2f06fafd33452790c73ea64c29a04b7f8c373d79e850c5d9cc813b5fd0a->doDisplay(Array, Array)
#12 /home/example.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /home/example.com/storage/runtime/compiled_templates/7a/7a6bb7b0d4bd09f3bf841539998116074b9bbd20b743b2ce387f7fd3de855d89.php(56): Twig\Template->display(Array, Array)
#14 /home/example.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_3569a6397bbc51cc31c0cd83f98ef46b8bdfccf930970af2973ba50d211fea51->doDisplay(Array, Array)
#15 /home/example.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /home/example.com/storage/runtime/compiled_templates/28/2864adbe69c8dbdc6cc1f0362dbb00c97deecb8923f59657f756091f8bfc28c3.php(118): Twig\Template->display(Array, Array)
#17 /home/example.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_fb0fcc48532d3dad2c1e04aeddeea8feabcb585284da9cf31ee88f024927838d->doDisplay(Array, Array)
#18 /home/example.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /home/example.com/storage/runtime/compiled_templates/46/46486432b77b7927a66da7be87691770839251fcbbe84996e9a03d3b83643372.php(65): Twig\Template->display(Array, Array)
#20 /home/example.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_8c15c824e372a1cf12189927d3d22f3ccf607778362800d889ac771e01293c6a->doDisplay(Array, Array)
#21 /home/example.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /home/example.com/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#23 /home/example.com/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#24 /home/example.com/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#25 /home/example.com/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('settings/plugin...', Array)
#26 /home/example.com/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('settings/plugin...', Array)
#27 /home/example.com/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('settings/plugin...', Array)
#28 /home/example.com/vendor/craftcms/cms/src/controllers/TemplatesController.php(101): craft\web\Controller->renderTemplate('settings/plugin...', Array)
#29 [internal function]: craft\controllers\TemplatesController->actionRender('settings/plugin...', Array)
#30 /home/example.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#31 /home/example.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#32 /home/example.com/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array)
#33 /home/example.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#34 /home/example.com/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array)
#35 /home/example.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#36 /home/example.com/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#37 /home/example.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#38 /home/example.com/web/index.php(21): yii\base\Application->run()
#39 {main}
```

**Comment by brandonkelly** [comment]
Looks like it is coming from svg-sanitizer while trying to sanitize one of your plugins’ icons.

If you send your `composer.json` and `composer.lock` files over to support@craftcms.com, we can try reproducing with those.

**Comment by mersy** [comment]
Thanks!
I'll send two files to that address later.

**Comment by angrybrad** [comment]
This looks to be a problem with the SVG icon the [Importable plugin](https://github.com/markdrzy/craft3-importable/) that is installed is using and the [SVG Sanitizer](https://github.com/darylldoyle/svg-sanitizer/) library that Craft is using.

I've created an issue in the latter's repo here to track the problem: https://github.com/darylldoyle/svg-sanitizer/issues/35

We've temporarily disabled this plugin in the Plugin Store until this can get resolved but in the meantime, you can remove it via Composer if you want by running this from your project's root:

    composer remove markdrzy/importable
