### ISSUE TITLE
Unable to delete all trashed items

### ISSUE THREAD

**Issue by daveyjones** [craftcms/cms#5309]
### Description

```
david@craft:/var/www/flexbuildinggroup/production$ ./craft gc
Delete all trashed items? (yes|no) [no]:yes
Running garbage collection ... Exception 'TypeError' with message 'Argument 1 passed to craft\services\Elements::deleteElement() must implement interface craft\base\ElementInterface, null given, called in /var/www/flexbuildinggroup/production/vendor/craftcms/cms/src/services/Drafts.php on line 330'

in /var/www/flexbuildinggroup/production/vendor/craftcms/cms/src/services/Elements.php:1187

Stack trace:
#0 /var/www/flexbuildinggroup/production/vendor/craftcms/cms/src/services/Drafts.php(330): craft\services\Elements->deleteElement(NULL, true)
#1 /var/www/flexbuildinggroup/production/vendor/craftcms/cms/src/services/Gc.php(57): craft\services\Drafts->purgeUnsavedDrafts()
#2 /var/www/flexbuildinggroup/production/vendor/craftcms/cms/src/console/controllers/GcController.php(56): craft\services\Gc->run(true)
#3 [internal function]: craft\console\controllers\GcController->actionRun()
#4 /var/www/flexbuildinggroup/production/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /var/www/flexbuildinggroup/production/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /var/www/flexbuildinggroup/production/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('', Array)
#7 /var/www/flexbuildinggroup/production/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('', Array)
#8 /var/www/flexbuildinggroup/production/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
#9 /var/www/flexbuildinggroup/production/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('gc', Array)
#10 /var/www/flexbuildinggroup/production/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('gc', Array)
#11 /var/www/flexbuildinggroup/production/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('gc', Array)
#12 /var/www/flexbuildinggroup/production/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#13 /var/www/flexbuildinggroup/production/craft(22): yii\base\Application->run()
#14 {main}
```

### Steps to reproduce

1. `./craft gc --delete-all-trashed=1`

### Additional info

- Craft version: 3.3.17
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.28
- Plugins & versions:

Contact Form	2.2.5
Cookies	1.1.11
Country Select	1.1.2
Do It Yourself widget	2.0.1
Imager	v2.3.0
Redactor	2.4.0

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, and the logic looks sound to me, so not sure how it would happen. Can you please send your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com, so we can look into it?

**Comment by daveyjones** [comment]
@brandonkelly sent!

**Comment by daveyjones** [comment]
Looks like I had missed some drafts when deleting entries manually—I deleted those and now we're good to go.
