### ISSUE TITLE
Seemingly random 404 on entry pages

### ISSUE THREAD

**Issue by nicbou** [craftcms/cms#5333]
### Description

I am using Craft 3.3.17, and I keep encountering weird 404 pages in the admin. The 404 pages differ between identical environments (docker running locally vs on a server, no config differences).

In this ticket, I'm describing a 404 page I get when creating one and only one type of entries from the Entries page. I can still create the entries from another entry type ("Add new place" button), then edit it without issues. You can see the log entry below.

Earlier this week, there's a single entry of a different type I couldn't edit. Now I can edit it again without issues.

Perhaps it could be an issue with my Apache config? The .htaccess redirects are untouched, but I added caching and compression to Craft.

### Steps to reproduce

1. I'm afraid I don't know

### Additional info

- Craft version: 3.3.17
- PHP version:
- Database driver & version:
- Plugins & versions:

```
2019-12-13 10:41:46 [-][1][...][error][yii\web\HttpException:404] yii\web\NotFoundHttpException: Entry not found in /var/vendor/craftcms/cms/src/controllers/EntriesController.php:588
Stack trace:
#0 /var/vendor/craftcms/cms/src/controllers/EntriesController.php(81): craft\controllers\EntriesController->_prepEditEntryVariables(Array)
#1 [internal function]: craft\controllers\EntriesController->actionEditEntry('places', 9579, 13, NULL, NULL, NULL)
#2 /var/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('edit-entry', Array)
#5 /var/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
...
2019-12-13 10:41:46 [-][1][...][info][application] $_GET = [
    'p' => 'admin/entries/places/9579'
    'draftId' => '13'
    'fresh' => '1'
]

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => []
    '1031b8c41dfff97a311a7ac99863bdc5__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5__id' => '1'
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 1576237306
    'bd62416aa8538ede709019a5e113eea5__auth_access' => [
        0 => 'previewElement:6964'
        1 => 'previewDraft:13'
        2 => 'previewElement:9580'
        3 => 'previewElement:79'
        4 => 'saveAssetInVolume:1'
        5 => 'previewElement:556'
        6 => 'previewDraft:14'
        7 => 'previewElement:491'
        8 => 'previewElement:721'
        9 => 'previewElement:827'
        10 => 'previewElement:1070'
        11 => 'previewElement:1528'
        12 => 'previewElement:1730'
        13 => 'previewDraft:15'
        14 => 'saveAssetInVolume:3'
    ]
]

$_SERVER = [
    'REDIRECT_HTTPS' => 'on'
    'REDIRECT_SSL_TLS_SNI' => 'allaboutberlin.com'
    'REDIRECT_STATUS' => '200'
    'HTTPS' => 'on'
    'SSL_TLS_SNI' => 'allaboutberlin.com'
    'HTTP_HOST' => 'allaboutberlin.com'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_PRAGMA' => 'no-cache'
    'HTTP_CACHE_CONTROL' => 'no-cache'
    ...
    'SERVER_SIGNATURE' => ''
    'SERVER_SOFTWARE' => 'Apache/2.4.41 (Unix)'
    'SERVER_NAME' => 'allaboutberlin.com'
    'SERVER_ADDR' => '172.18.0.2'
    'SERVER_PORT' => '443'
    'REMOTE_ADDR' => '91.64.153.123'
    'DOCUMENT_ROOT' => '/var/www/html'
    'REQUEST_SCHEME' => 'https'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => '/var/www/html'
    'SERVER_ADMIN' => 'contact@nicolasbouliane.com'
    'SCRIPT_FILENAME' => '/var/www/html/index.php'
    'REMOTE_PORT' => '57491'
    'REDIRECT_URL' => '/admin/entries/places/9579'
    'REDIRECT_QUERY_STRING' => 'p=admin/entries/places/9579&draftId=13&fresh=1'
    ...
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => 'p=admin/entries/places/9579&draftId=13&fresh=1'
    'REQUEST_URI' => '/admin/entries/places/9579?draftId=13&fresh=1'
    'SCRIPT_NAME' => '/index.php'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1576233706.091
    'REQUEST_TIME' => 1576233706
    'argv' => [
        0 => 'p=admin/entries/places/9579&draftId=13&fresh=1'
    ]
    'argc' => 1
    'ENVIRONMENT' => 'dev'
    'SECURITY_KEY' => '••••••••••••••••••••'
]
```

**Comment by brandonkelly** [comment]
Please send a database backup and your `composer.json` and `composer.lock` files over to support@craftcms.com, and reference this issue. Also specify which user you are logged in as when this happens.

**Comment by nicbou** [comment]
I found the issue, and it's my fault. I fiddled with cache headers settings. If I open Chrome developer tools and disable caching, it works just fine.

The issue was caused by setting `session.cache_limiter=public` in php.ini. It speeds up the public site, but it breaks the admin site.
