### ISSUE TITLE
Fields UI showing "Internal Server Error"

### ISSUE THREAD

**Issue by somethingconcon** [craftcms/cms#5336]
### Description
Internal Server Error page when viewing.

The stack trace in the logs is reported as: 

```
2019-12-13 13:04:45 [-][14630][djhnqen27p8f802bpvakuoo55b][error][TypeError] TypeError: Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given, called in path-to-craftcms/cms/src/base/Field.php on line 447 and defined in /path-to-craftcms/cms/src/services/Fields.php:238
Stack trace:
#0 /path-to-craftcms/cms/src/base/Field.php(447): craft\services\Fields->getGroupById(NULL)
```

On inspecting the fields table to see if there's been any updates.  The last update the fields was in July.  Is there any way I would be able to figure out what the offending field is?

### Steps to reproduce

1. login to craft admin console
2. naviate to oursite.com/admin/settings/fields

### Additional info

- Craft version: Craft Pro 3.1.29
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5
- Plugins & versions: [

Cache Flag 	1.0.3
Cookies 	1.1.11
Eager Beaver 	1.0.4
Element Index Defaults 	1.0.3
Field Manager 	2.1.0
Incognito Field 	1.1.1.1
Minify 	1.2.9
Position Fieldtype 	1.0.14
Preparse Field 	v1.0.6
Redactor 	2.3.3.2
Redirects 	3.1.15
SEO 	3.2.7
Similar 	1.0.6
Site Duplicate 	1.0.3
Snitch 	2.1.2
Super Table 	2.1.20
Table Maker 	2.0.1
Tags 	1.0.5
Typed link field 	1.0.19
WHMCS Connector 	1.0.1

]

**Comment by brandonkelly** [comment]
There have been a lot of bug fixes since 3.1.29 – please try updating to the latest release.

**Comment by internetztube** [comment]
We got the bug today with Craft 3.3... It seems that the problem is not fixed. 

```
PHP version	7.2.24
OS version	Linux 4.15.0-64-generic
Database driver & version	MySQL 8.0.19
Image driver & version	GD 7.2.24
Craft edition & version	Craft Pro 3.3.18.1
Yii version	2.0.30
Twig version	2.12.2
Guzzle version	6.5.0
Imagine version	1.2.3-dev
```
```
2020-01-29 14:56:22 [-][476][f0ibss123mmstuma8rcpfi7h7g][error][TypeError] TypeError: Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given, called in /path/to/craft/vendor/craftcms/cms/src/base/Field.php on line 478 and defined in /path/to/craft/vendor/craftcms/cms/src/services/Fields.php:240
Stack trace:
#0 /path/to/craft/vendor/craftcms/cms/src/base/Field.php(478): craft\services\Fields->getGroupById(NULL)
#1 /path/to/craft/vendor/yiisoft/yii2/base/Component.php(139): craft\base\Field->getGroup()
#2 /path/to/craft/vendor/craftcms/cms/src/helpers/Template.php(89): yii\base\Component->__get('group')
#3 /path/to/craft/storage/runtime/compiled_templates/af/aff6cc283acac8d3c425f91f1644b8704d4652db44a301e81c384bd3b4b850d9.php(307): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\fields\Matrix), 'group', Array)
#4 /path/to/craft/vendor/twig/twig/src/Template.php(184): __TwigTemplate_ebf1bd4b29a86d5921abf2af52af7a00b0486718e909f60aaf99a2a14da6cfdb->block_content(Array, Array)
#5 /path/to/craft/storage/runtime/compiled_templates/72/7204753040a30a720f46661b66773d3b4af6ae6f2f5f50ba5347d4186ad14a1e.php(727): Twig\Template->displayBlock('content', Array, Array)
#6 /path/to/craft/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c1e0f919a5413be13dfcd65bfa15f8fb959e8341940b07bb5a5b3d7e8d79f844->block_main(Array, Array)
#7 /path/to/craft/storage/runtime/compiled_templates/72/7204753040a30a720f46661b66773d3b4af6ae6f2f5f50ba5347d4186ad14a1e.php(576): Twig\Template->displayBlock('main', Array, Array)
#8 /path/to/craft/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c1e0f919a5413be13dfcd65bfa15f8fb959e8341940b07bb5a5b3d7e8d79f844->block_body(Array, Array)
#9 /path/to/craft/storage/runtime/compiled_templates/de/de4c8362bc1e31725a77b1bb7f4aee8b9afa9a729b3a3357a6668aa1db2c8b6f.php(75): Twig\Template->displayBlock('body', Array, Array)
#10 /path/to/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_e411ffc4c4db07fe06e7b63c37effec6ad60ca39fe14382c49db3b423473f6b4->doDisplay(Array, Array)
#11 /path/to/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /path/to/craft/storage/runtime/compiled_templates/9e/9eab13eb6339ba3f4c8d8c3fe88aa91adea73ec46d5c0586fd907af631d4f38e.php(56): Twig\Template->display(Array, Array)
#13 /path/to/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_9845b3ccabfc2040f32e7e5953bb48cab2b790e791ec0b6c8adec2f62fb26f98->doDisplay(Array, Array)
#14 /path/to/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /path/to/craft/storage/runtime/compiled_templates/72/7204753040a30a720f46661b66773d3b4af6ae6f2f5f50ba5347d4186ad14a1e.php(118): Twig\Template->display(Array, Array)
#16 /path/to/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_c1e0f919a5413be13dfcd65bfa15f8fb959e8341940b07bb5a5b3d7e8d79f844->doDisplay(Array, Array)
#17 /path/to/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /path/to/craft/storage/runtime/compiled_templates/af/aff6cc283acac8d3c425f91f1644b8704d4652db44a301e81c384bd3b4b850d9.php(82): Twig\Template->display(Array, Array)
#19 /path/to/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_ebf1bd4b29a86d5921abf2af52af7a00b0486718e909f60aaf99a2a14da6cfdb->doDisplay(Array, Array)
#20 /path/to/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /path/to/craft/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#22 /path/to/craft/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#23 /path/to/craft/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#24 /path/to/craft/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('settings/fields', Array)
#25 /path/to/craft/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('settings/fields', Array)
#26 /path/to/craft/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('settings/fields', Array)
#27 /path/to/craft/vendor/craftcms/cms/src/controllers/TemplatesController.php(101): craft\web\Controller->renderTemplate('settings/fields', Array)
#28 [internal function]: craft\controllers\TemplatesController->actionRender('settings/fields', Array)
#29 /path/to/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /path/to/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#31 /path/to/craft/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array)
#32 /path/to/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#33 /path/to/craft/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array)
#34 /path/to/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#35 /path/to/craft/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#36 /path/to/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#37 /path/to/craft/web/index.php(42): yii\base\Application->run()
#38 {main}
```

**Comment by brandonkelly** [comment]
@internetztube “Internal server error” is a generic error message so there are hundreds of ways it could theoretically occur. 

It’s hard to tell from your stack trace what’s going on, but you could try running `./craft project-config/rebuild` and see if that helps. Otherwise, please send your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com with steps to reproduce the error, and we can try to look into it from there?
