### ISSUE TITLE
Error occurred when renaming sites group

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#5337]
### Description

When you want to rename a sites group name, it shows an error box at the top with "Unknown error occurred"

From the log:

```
2019-12-13 21:03:49 [-][1][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: craft\models\SiteGroup::name” in /var/www/html/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/services/Sites.php(260): yii\base\Component->__get('name\xE2\x80\x9D')
#1 /var/www/html/vendor/craftcms/cms/src/controllers/SitesController.php(112): craft\services\Sites->saveGroup(Object(craft\models\SiteGroup))
#2 [internal function]: craft\controllers\SitesController->actionSaveGroup()
#3 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save-group', Array)
#6 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-group', Array)
#7 /var/www/html/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('sites/save-grou...', Array)
#8 /var/www/html/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('sites/save-grou...', Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /var/www/html/web/index.php(21): yii\base\Application->run()
#12 {main}
```

### Steps to reproduce

1. Navigate to sites in the CP
2. Click the group
3. Click on the cog icon to rename the group
4. Change the name

### Additional info

- Craft version: 3.4-beta.3
- PHP version: 7.3.10
- Database driver & version: mysql 8.0
- Plugins & versions: none (fresh clean install)

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just got it fixed for the next 3.4 Beta release.
