### ISSUE TITLE
attr filter (regex?) bug

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#5364]
Encountering an "Undefined offset: 3" error when the `iframe` tag contains the `frameborder` attribute.

### Steps to reproduce

```twig
{% set tag = "<iframe frameborder='0' scrolling='no'></iframe>" %}
{{ tag|attr({ height: '100%' }) }}
```

### Stack trace

```
yii\base\ErrorException: Undefined offset: 3 in ./vendor/craftcms/cms/src/helpers/Html.php:273
Stack trace:
#0 ./vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '...', 273)
#1 ./vendor/craftcms/cms/src/helpers/Html.php(273): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '...', 273, Array)
#2 ./vendor/craftcms/cms/src/helpers/Html.php(225): craft\helpers\Html::parseTagAttributes('    <iframe fra...', 0, 11, NULL, true)
#3 ./vendor/craftcms/cms/src/web/twig/Extension.php(581): craft\helpers\Html::modifyTagAttributes('    <iframe fra...', Array)
#4 ./storage/runtime/compiled_templates/f3/f307af5b13335b6b4c528de2de459a8d407826df377e1c674e73bff6976a1d6e.php(46): craft\web\twig\Extension->attrFilter('    <iframe fra...', Array)
#5 ./vendor/twig/twig/src/Template.php(407): __TwigTemplate_3c452723d4616fa40cdb67dcd9ac56fad690f98a734cc36f23927d03a2db3735->doDisplay(Array, Array)
#6 ./vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#7 ./vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#8 ./vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#9 ./vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#10 ./vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('test.twig', Array)
#11 ./vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('test.twig', Array)
#12 ./vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('test.twig', Array)
#13 ./vendor/craftcms/cms/src/controllers/TemplatesController.php(101): craft\web\Controller->renderTemplate('test.twig', Array)
#14 [internal function]: craft\controllers\TemplatesController->actionRender('test.twig', Array)
#15 ./vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 ./vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 ./vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array)
#18 ./vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#19 ./vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array)
#20 ./vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#21 ./vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#22 ./vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 ./web/index.php(24): yii\base\Application->run()
#24 {main}
```

### Additional info

- Craft version: 3.3.16.3
- PHP version: 7.1.19

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#b477926c5a08beda878cfa4c713afaaf457c83e6 as 3.3.18.3",
  "...": "..."
}
```

Then run `composer update`.
