### ISSUE TITLE
CSecurityManager requires PHP mcrypt extension to be loaded [2.8.0.2]

### ISSUE THREAD

**Issue by michaelroper** [craftcms/cms#5417]
Hey team! Have just noticed that when trying to access my Email settings in the CP, I now get the following error:

>**Internal Server Error**
>CSecurityManager requires PHP mcrypt extension to be loaded in order to use data encryption feature.

Not sure if this is a recent regression, because I thought that v2.7 onwards should work on PHP7.2 servers without `mcrypt` installed, because you added `mcrypt_compat`? (cf. https://craftcms.com/blog/craft-2-7-released-with-php-7-2-compatibility). The Server Info checklist still lists "Mcrypt extension" with a green tick against it, even though there is no mention of mcrypt on the PHP Info tab.

Admittedly, i haven't checked my email settings in a while, but I am sure I have checked that screen since we were using 2.7+7.2, and didn't get the error.

### Steps to reproduce

1. Access _Settings -> Email_ in the Admin CP on a v2.8.0.2 install
2. Get shown internal error above.

### Additional info

- Craft version: 2.8.0.2
- PHP version: 7.2.26

**Comment by angrybrad** [comment]
Weird... just tried on PHP 7.2.25 and Craft 2.8.0.2 and I'm not able to reproduce.

Can you reproduce with devMode enabled, then share the full stack trace?

**Comment by michaelroper** [comment]
Huh... I ran into the same error on both my local env (Valet w/homebrew PHP 7.4.1) and on my production server (Forge-provisioned PHP 7.2.6).. neither has the pecl mcrypt installed, but both still have mcrypt as ticked on the Server Info page.

Full stack trace from local:

```
2020/01/11 06:45:10 [error] [exception.Twig\Error\RuntimeError] CException: CSecurityManager requires PHP mcrypt extension to be loaded in order to use data encryption feature. in /craft/app/framework/base/CSecurityManager.php:276
Stack trace:
#0 /craft/app/framework/base/CSecurityManager.php(223): CSecurityManager->openCryptModule()
#1 /craft/app/helpers/StringHelper.php(738): CSecurityManager->encrypt('AurcxqtGZtVFPcH...')
#2 /craft/app/etc/templating/twigextensions/CraftTwigExtension.php(140): Craft\StringHelper::encenc('AurcxqtGZtVFPcH...')
#3 /craft/storage/runtime/compiled_templates/7b/7bb17579eaf1f0fef5a049a55cb7029386eb978548523fbaf0b55f4713f2a4d6.php(130): Craft\CraftTwigExtension->encencFilter('AurcxqtGZtVFPcH...')
#4 /craft/app/vendor/twig/twig/src/Template.php(217): __TwigTemplate_1f35aea319ad75e8c02e553199076498efa59316fca77d730e9b6f03ae02fdf8->block_content(Array, Array)
#5 /craft/storage/runtime/compiled_templates/70/70adb422105066411ebd46826f6519a20e4dedfb3b055a76130a6321a81fd52a.php(751): Twig\Template->displayBlock('content', Array, Array)
#6 /craft/app/vendor/twig/twig/src/Template.php(217): __TwigTemplate_37e0aa615aa671f4ad56f3bb4b51a9b6703b19ebc95a99ab452c5e350f87f8b1->block_body(Array, Array)
#7 /craft/storage/runtime/compiled_templates/c1/c189a6b9db7a9771edd9fac750670416d1fa4e51c70f3161ed5f28aa3a93160e.php(56): Twig\Template->displayBlock('body', Array, Array)
#8 /craft/app/vendor/twig/twig/src/Template.php(456): __TwigTemplate_825800bbbe202ad9c1026b8995d22e23eb2931d04e3632c4a1a2700706424c65->doDisplay(Array, Array)
#9 /craft/app/etc/templating/BaseTemplate.php(26): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /craft/app/vendor/twig/twig/src/Template.php(423): Craft\BaseTemplate->displayWithErrorHandling(Array, Array)
#11 /craft/storage/runtime/compiled_templates/5e/5eeba8bd0305885b8aa494abba3fbb49c5bb4aca389351f8c679fc54f7e1c2b3.php(145): Twig\Template->display(Array, Array)
#12 /craft/app/vendor/twig/twig/src/Template.php(456): __TwigTemplate_a00ef2c147ad433df2cb9958c61b05fb573b58c243b8f7b238c82e85004bad41->doDisplay(Array, Array)
#13 /craft/app/etc/templating/BaseTemplate.php(26): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /craft/app/vendor/twig/twig/src/Template.php(423): Craft\BaseTemplate->displayWithErrorHandling(Array, Array)
#15 /craft/storage/runtime/compiled_templates/70/70adb422105066411ebd46826f6519a20e4dedfb3b055a76130a6321a81fd52a.php(180): Twig\Template->display(Array, Array)
#16 /craft/app/vendor/twig/twig/src/Template.php(456): __TwigTemplate_37e0aa615aa671f4ad56f3bb4b51a9b6703b19ebc95a99ab452c5e350f87f8b1->doDisplay(Array, Array)
#17 /craft/app/etc/templating/BaseTemplate.php(26): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /craft/app/vendor/twig/twig/src/Template.php(423): Craft\BaseTemplate->displayWithErrorHandling(Array, Array)
#19 /craft/storage/runtime/compiled_templates/a3/a3839967c3a50d1c2a5165a2c13c2e87f5cfc51b755e6338e5ca19b8b52ad613.php(49): Twig\Template->display(Array, Array)
#20 /craft/app/vendor/twig/twig/src/Template.php(456): __TwigTemplate_34219dcb215ff5daf2ea1bf14a7cb74d6b767b583b665307704d9863f8bfb7e0->doDisplay(Array, Array)
#21 /craft/app/etc/templating/BaseTemplate.php(26): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /craft/app/vendor/twig/twig/src/Template.php(423): Craft\BaseTemplate->displayWithErrorHandling(Array, Array)
#23 /craft/storage/runtime/compiled_templates/7b/7bb17579eaf1f0fef5a049a55cb7029386eb978548523fbaf0b55f4713f2a4d6.php(69): Twig\Template->display(Array, Array)
#24 /craft/app/vendor/twig/twig/src/Template.php(456): __TwigTemplate_1f35aea319ad75e8c02e553199076498efa59316fca77d730e9b6f03ae02fdf8->doDisplay(Array, Array)
#25 /craft/app/etc/templating/BaseTemplate.php(26): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /craft/app/vendor/twig/twig/src/Template.php(423): Craft\BaseTemplate->displayWithErrorHandling(Array, Array)
#27 /craft/app/vendor/twig/twig/src/Template.php(435): Twig\Template->display(Array)
#28 /craft/app/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template->render(Array, Array)
#29 /craft/app/vendor/twig/twig/src/Environment.php(384): Twig\TemplateWrapper->render(Array)
#30 /craft/app/services/TemplatesService.php(256): Twig\Environment->render('settings/email', Array)
#31 /craft/app/controllers/BaseController.php(74): Craft\TemplatesService->render('settings/email', Array)
#32 /craft/app/controllers/TemplatesController.php(68): Craft\BaseController->renderTemplate('settings/email', Array)
#33 [internal function]: Craft\TemplatesController->actionRender('settings/email', Array)
#34 /craft/app/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(Craft\TemplatesController), Array)
#35 /craft/app/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(Craft\TemplatesController), Object(ReflectionMethod), Array)
#36 /craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#37 /craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#38 /craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#39 /craft/app/framework/web/CWebApplication.php(282): CController->run('render')
#40 /craft/app/framework/web/CWebApplication.php(141): CWebApplication->runController('templates/rende...')
#41 /craft/app/etc/web/WebApp.php(291): CWebApplication->processRequest()
#42 /craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#43 /craft/app/index.php(73): CApplication->run()
#44 /public/index.php(36): require_once('...')
#45 .composer/vendor/laravel/valet/server.php(158): require('...')
#46 {main}
```

**Comment by angrybrad** [comment]
Super weird... any chance we can get some Craft CP and SSH access to that production box to poke around?  If so, can you send over to support@craftcms.com?

**Comment by michaelroper** [comment]
Can do, have sent an email. 👍

**Comment by angrybrad** [comment]
The issue is that your CSecurityManager is different than the one that the last Craft 2 version shipped with.  I'd suggest downloading a fresh copy of the latest Craft 2 release (https://craftcms.com/latest-v2.zip, then replacing your existing `craft/app` folder with the fresh one and that should solve the issue.

**Comment by michaelroper** [comment]
Thanks Brad, that did the trick! I usually do the updates from within the CP, so not sure how that all got out of sync, but that wasn't the only file that was different between the fresh app folder and my install... ¯\_(ツ)_/¯
