### ISSUE TITLE
[3.4] Update: Matrix Fields with Redactor lost content

### ISSUE THREAD

**Issue by DavidKabelitz** [craftcms/cms#5534]
### Description
After updating to 3.4 all Matrix fields that are named copy (Redactor Fields) in our setup are still there but the content is gone. Looks like its related to Redactor.

### Steps to reproduce

1. Update to 3.4
2. All Modules on the pages

### Additional info

- Craft version: Craft Pro 3.4.0.2
- PHP version: 7.2.24
- Database driver & version:
- Plugins & versions: Redactor 2.5.0

**Comment by dubcanada** [comment]
> are named copy (Redactor Fields)

Not sure what you mean by that?

What version did you update from?

**Comment by DavidKabelitz** [comment]
We have a Matrix Field  Setup and in that is a Redactor Field named "Copy"...on our local system everything went well, updating and database migration.

On our stating version, database migration also worked but project.yaml update caused an error...site still running but all Copy Fields are empty. 

Some Errors from the logs:

```
2020-01-29 19:11:36 [-][-][-][warning][craft\db\mysql\Schema::releaseSavepoint] Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: RELEASE SAVEPOINT LEVEL1
2020-01-29 19:11:36 [-][-][-][info][craft\db\MigrationManager::migrateUp] Applied m200127_172522_queue_channels (time: 1.069s). Output:
    > drop index queue_fail_timeUpdated_timePushed_idx on {{%queue}} ... done (time: 0.135s)
    > drop index queue_fail_timeUpdated_delay_idx on {{%queue}} ... done (time: 0.104s)
    > add column channel string NOT NULL DEFAULT 'queue' AFTER `id` to table {{%queue}} ... done (time: 0.532s)
    > create index queue_channel_fail_timeUpdated_timePushed_idx on {{%queue}} (channel,fail,timeUpdated,timePushed) ... done (time: 0.131s)
    > create index queue_channel_fail_timeUpdated_delay_idx on {{%queue}} (channel,fail,timeUpdated,delay) ... done (time: 0.155s)
```

```
2020-01-29 19:11:47 [-][-][-][warning][craft\db\mysql\Schema::releaseSavepoint] Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: RELEASE SAVEPOINT LEVEL1
```

```
Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Copy-410' for key 'matrixblocktypes_name_fieldId_unq_idx'
The SQL being executed was: INSERT INTO `matrixblocktypes` (`fieldId`, `name`, `handle`, `sortOrder`, `uid`, `fieldLayoutId`, `dateCreated`, `dateUpdated`) VALUES (410, 'Copy', 'copy', 2, 'f14c68c0-bd9b-480d-ae6b-0f99a502f48b', 203, '2020-01-29 18:12:01', '2020-01-29 18:12:01') in /var/www/craft/vendor/yiisoft/yii2/db/Schema.php:674
Stack trace:
#0 /var/www/craft/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `ma...')
#1 /var/www/craft/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO `ma...')
#2 /var/www/craft/vendor/yiisoft/yii2/db/Schema.php(432): yii\db\Command->execute()
#3 /var/www/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert('{{%matrixblockt...', Array)
#4 /var/www/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#5 /var/www/craft/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(false, NULL)
#6 /var/www/craft/vendor/craftcms/cms/src/services/Matrix.php(396): yii\db\BaseActiveRecord->save(false)
#7 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(1083): craft\services\Matrix->handleChangedBlockType(Object(craft\events\ConfigEvent))
#8 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#9 /var/www/craft/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#10 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(657): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#11 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(1073): craft\services\ProjectConfig->processConfigChanges('matrixBlockType...')
#12 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#13 /var/www/craft/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#14 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(657): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#15 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(1171): craft\services\ProjectConfig->processConfigChanges('matrixBlockType...')
#16 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(525): craft\services\ProjectConfig->_applyChanges(Array)
#17 /var/www/craft/vendor/craftcms/cms/src/controllers/ConfigSyncController.php(52): craft\services\ProjectConfig->applyYamlChanges()
#18 [internal function]: craft\controllers\ConfigSyncController->actionApplyYamlChanges()
#19 /var/www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#21 /var/www/craft/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('apply-yaml-chan...', Array)
#22 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('apply-yaml-chan...', Array)
#23 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('config-sync/app...', Array)
#24 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(684): craft\web\Application->runAction('config-sync/app...')
#25 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(247): craft\web\Application->_processConfigSyncLogic(Object(craft\web\Request))
#26 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#27 /var/www/craft/web/index.php(21): yii\base\Application->run()
#28 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry 'Copy-410' for key 'matrixblocktypes_name_fieldId_unq_idx'
)
```

**Comment by DavidKabelitz** [comment]
We were updating from Craft Pro 3.3.17

**Comment by brandonkelly** [comment]
Please send a **pre-3.4 update** database backup, along with your `composer.json` and `composer.lock` files, over to support@craftcms.com, and reference this issue URL, and we’ll look into it from there.

**Comment by DavidKabelitz** [comment]
Thanks Brandon, done!

**Comment by DavidKabelitz** [comment]
Any idea for this one, also we lost some settings of other matrix fields...we can add everything again but just want to double check what you think about this issue.

**Comment by andris-sevcenko** [comment]
@DavidKabelitz I responded to you over email a while ago, can you double-check?

**Comment by DavidKabelitz** [comment]
sorry...yes - will try out

**Comment by DavidKabelitz** [comment]
We can close this, your solution worked out. Thanks a lot.

**Comment by brandonkelly** [comment]
Good to hear!
