### ISSUE TITLE
File or directory to be published does not exist

### ISSUE THREAD

**Issue by keyurshah** [craftcms/cms#5537]
### Description
Getting an error while trying to login to the admin 

```
yii\base\InvalidArgumentException: The file or directory to be published does not exist: D:\myfiles\laragon\www\mystore\vendor\craftcms\cms\lib/deepmerge in D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\web\AssetManager.php:455
Stack trace:
#0 D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\web\AssetBundle.php(185): yii\web\AssetManager->publish('D:\\myfiles\\lara...', Array)
craftcms/commerce#1 D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\web\AssetManager.php(266): yii\web\AssetBundle->publish(Object(craft\web\AssetManager))
craftcms/commerce#2 D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\web\AssetManager.php(237): yii\web\AssetManager->loadBundle('craft\\commerce\\...', Array, true)
craftcms/commerce#3 D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\web\View.php(287): yii\web\AssetManager->getBundle('craft\\commerce\\...')
craftcms/commerce#4 D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\web\View.php(292): yii\web\View->registerAssetBundle('craft\\commerce\\...', NULL)
craftcms/commerce#5 D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\web\View.php(292): yii\web\View->registerAssetBundle('craft\\commerce\\...', NULL)
craftcms/commerce#6 D:\myfiles\laragon\www\mystore\vendor\craftcms\commerce\src\widgets\Orders.php(104): yii\web\View->registerAssetBundle('craft\\commerce\\...')
craftcms/commerce#7 D:\myfiles\laragon\www\mystore\vendor\craftcms\cms\src\controllers\DashboardController.php(68): craft\commerce\widgets\Orders->getSettingsHtml()
craftcms/commerce#8 [internal function]: craft\controllers\DashboardController->actionIndex()
craftcms/commerce#9 D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
craftcms/commerce#10 D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
craftcms/commerce#11 D:\myfiles\laragon\www\mystore\vendor\craftcms\cms\src\web\Controller.php(178): yii\base\Controller->runAction('index', Array)
craftcms/commerce#12 D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('index', Array)
craftcms/commerce#13 D:\myfiles\laragon\www\mystore\vendor\craftcms\cms\src\web\Application.php(290): yii\base\Module->runAction('dashboard/index', Array)
craftcms/commerce#14 D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\web\Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
craftcms/commerce#15 D:\myfiles\laragon\www\mystore\vendor\craftcms\cms\src\web\Application.php(275): yii\web\Application->handleRequest(Object(craft\web\Request))
craftcms/commerce#16 D:\myfiles\laragon\www\mystore\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
craftcms/commerce#17 D:\myfiles\laragon\www\mystore\web\index.php(21): yii\base\Application->run()
craftcms/commerce#18 {main}
```

### Steps to reproduce

1. Upgraded to Commerce 3 from Commerce 2 on Windows

### Additional info

* this is on windows
* also attempted to remove vendor folder and reinstall all files from scratch
* I am using S3 for regular assets, not sure if this has anything to do with this issue. 

- Craft version: 3.4.0.2
- PHP version: 7.3.6
- Database driver & version: mysql 5.7.24
- Plugins & versions:

**Comment by lukeholder** [comment]
Doesn't look Commerce related and @keyurshah said he upgraded to Craft 3.4 at the same time (from discord).
