### ISSUE TITLE
Failed migration: update_preview_targets (upgrading from 3.3.20.1 to 3.4.3)

### ISSUE THREAD

**Issue by jrrdnx** [craftcms/cms#5594]
### Description

Failed migration during a `composer update`.

### Steps to reproduce

1. Ran `composer update` and craftcms/cms was updated from `3.3.20.1` to `3.4.3`.
2. Navigate to /admin to run updates.

### Additional info

- Craft version: 3.3.20.1 -> 3.4.3 update
- PHP version: 7.2.24
- Database driver & version: MySQL 5.6.42
- Plugins & versions:
Amazon S3: 1.2.7
Cookies: 1.1.11
Entry GPS Coordinates: 1.3.0
Feed Me: 4.2.0.1
Google reCAPTCHA for Sprout Forms: 1.1.0
Redactor: 2.4.0
SEO: 3.6.3
Sprout Forms: 3.7.1.1
Super Table: 2.3.3
US States Field for Sprout Forms: 1.0.7

### Full error output

```
yii\base\ErrorException: Declaration of craft\queue\Queue::handleError(yii\queue\ExecEvent $event) should be compatible with yii\queue\Queue::handleError($id, $job, $ttr, $attempt, $error)

Migration: craft\migrations\m190913_152146_update_preview_targets

Output:

Exception: Declaration of craft\queue\Queue::handleError(yii\queue\ExecEvent $event) should be compatible with yii\queue\Queue::handleError($id, $job, $ttr, $attempt, $error) (/var/www/vhosts/domain.com/vendor/craftcms/cms/src/queue/Queue.php:35)
#0 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(2, 'Declaration of ...', '/var/www/vhosts...', 35)
#1 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/queue/Queue.php(35): craft\web\ErrorHandler->handleError(2, 'Declaration of ...', '/var/www/vhosts...', 35, Array)
#2 /var/www/vhosts/domain.com/vendor/composer/ClassLoader.php(444): include('/var/www/vhosts...')
#3 /var/www/vhosts/domain.com/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/vhosts...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('craft\\queue\\Que...')
#5 [internal function]: spl_autoload_call('craft\\queue\\Que...')
#6 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/di/Container.php(447): ReflectionClass->__construct('craft\\queue\\Que...')
#7 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/di/Container.php(374): yii\di\Container->getDependencies('craft\\queue\\Que...')
#8 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\queue\\Que...', Array, Array)
#9 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\queue\\Que...', Array, Array)
#10 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#11 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('queue', true)
#12 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/web/Application.php(340): yii\base\Module->get('queue', true)
#13 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/base/ApplicationTrait.php(1123): craft\web\Application->get('queue')
#14 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/services/Elements.php(2181): craft\web\Application->getQueue()
#15 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#16 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/services/Sections.php(1545): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#17 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/services/Sections.php(755): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section), Array)
#18 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/services/ProjectConfig.php(1084): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#19 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#20 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#21 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/services/ProjectConfig.php(658): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#22 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/services/ProjectConfig.php(1074): craft\services\ProjectConfig->processConfigChanges('sections.8df85d...')
#23 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#24 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#25 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/services/ProjectConfig.php(655): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#26 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/services/ProjectConfig.php(478): craft\services\ProjectConfig->processConfigChanges('sections.8df85d...', true, '')
#27 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/migrations/m190913_152146_update_preview_targets.php(54): craft\services\ProjectConfig->set('sections.8df85d...', Array)
#28 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m190913_152146_update_preview_targets->safeUp()
#29 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#30 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m190913_152146_update_preview_targets))
#31 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#32 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#33 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#34 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#35 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#36 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#37 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#38 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#39 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('updater/migrate', Array)
#40 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/web/Application.php(645): craft\web\Application->runAction('updater/migrate')
#41 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/web/Application.php(222): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#42 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#43 /var/www/vhosts/domain.com/web/index.php(24): yii\base\Application->run()
#44 {main}
```

**Comment by brandonkelly** [comment]
Looks like Composer hadn’t finished doing its thing before you attempted to run migrations, or perhaps OPcache was returning an old copy of `vendor/yiisoft/yii2-queue/src/Queue.php`. Try restoring a database backup from before the update, and then click “Finish up” again.
