### ISSUE TITLE
 Issues when trying to update from 3.1.34 to 3.4.4 in staging env

### ISSUE THREAD

**Issue by leobauza** [craftcms/cms#5596]
### Description

Relate to: https://github.com/craftcms/cms/issues/5391#issuecomment-582606458

I am able to perform this update locally but when I push to my staging environment I get and "internal server error occurred"

Some more details:

- We are using the project config so one of the differences is that allowAdminChanges is set to false in staging (I know that was mentioned earlier in #5391, not sure if it's relevant.)
- I am using the same DB locally and in my staging environment
- I tried to run project-config/rebuild in before the upgrade to 3.4.4 since it was mentioned in the changelog

### Steps to reproduce

1. Update from 3.1.34 to 3.4.4

### Additional info

- Craft version: 3.1.34 - 3.4.4
- PHP version: 7.2.24

### Logs

Error when running `./craft migrate/all`:

```
Exception 'yii\db\Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config' in 'field list'
The SQL being executed was: SELECT `config`
FROM `info`
LIMIT 1'

in /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/db/Schema.php:674

Error Info:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'config' in 'field list'
)

Stack trace:
#0 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT `config`...')
#1 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT `config`...')
#2 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/db/Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/db/Query.php(291): yii\db\Command->queryScalar()
#4 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/db/Query.php(188): yii\db\Query->scalar(NULL)
#5 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/ProjectConfig.php(1711): craft\db\Query->scalar()
#6 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/ProjectConfig.php(1605): craft\services\ProjectConfig->_loadInternalConfigData()
#7 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/ProjectConfig.php(1594): craft\services\ProjectConfig->_getStoredConfig()
#8 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/ProjectConfig.php(397): craft\services\ProjectConfig->_getLoadedConfig()
#9 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/Plugins.php(1369): craft\services\ProjectConfig->get('plugins.calenda...')
#10 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/Plugins.php(206): craft\services\Plugins->_getPluginConfigData('calendar')
#11 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/base/ApplicationTrait.php(1351): craft\services\Plugins->loadPlugins()
#12 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/console/Application.php(59): craft\console\Application->_postInit()
#13 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#14 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#15 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#16 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/console/Application.php(48): yii\console\Application->__construct(Array)
#17 [internal function]: craft\console\Application->__construct(Array)
#18 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#19 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array)
#20 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#21 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array)
#22 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/bootstrap/console.php(43): require('/var/www/nea/st...')
#23 /var/www/nea/staging/releases/20200205173514/craft(21): require('/var/www/nea/st...')
#24 {main}
```

Error I see as things are deploying:

```
Exception: unlink(/var/www/nea/staging/releases/20200205173514/storage/runtime/compiled_templates/39/398a0e4080ab9b4b5cc6e4cb25279a0f687ac54d0ed50ceeaec5615e59f59393.php): Permission denied (/var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:416)
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'unlink(/var/www...', '/var/www/nea/st...', 416, Array)
#1 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(416): unlink('/var/www/nea/st...')
#2 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(391): yii\helpers\BaseFileHelper::unlink('/var/www/nea/st...')
#3 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/helpers/FileHelper.php(92): yii\helpers\BaseFileHelper::removeDirectory('/var/www/nea/st...', Array)
#4 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/helpers/FileHelper.php(462): craft\helpers\FileHelper::removeDirectory('/var/www/nea/st...', Array)
#5 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/migrations/m190820_003519_flush_compiled_templates.php(21): craft\helpers\FileHelper::clearDirectory('/var/www/nea/st...')
#6 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m190820_003519_flush_compiled_templates->safeUp()
#7 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#8 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m190820_003519_flush_compiled_templates))
#9 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#10 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#11 [internal function]: craft\console\controllers\MigrateController->actionAll()
#12 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#15 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#16 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#17 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#18 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#19 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#20 /var/www/nea/staging/releases/20200205173514/craft(22): yii\base\Application->run()
#21 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Craft CMS.'

in /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/Updates.php:241

Stack trace:
#0 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#5 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#8 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /var/www/nea/staging/releases/20200205173514/craft(22): yii\base\Application->run()
#11 {main}
  ○ sync project config
Exception 'yii\db\Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config' in 'field list'
The SQL being executed was: SELECT `config`
FROM `info`
LIMIT 1'

in /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/db/Schema.php:674

Error Info:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'config' in 'field list'
)

Stack trace:
#0 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT `config`...')
#1 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT `config`...')
#2 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/db/Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/db/Query.php(291): yii\db\Command->queryScalar()
#4 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/db/Query.php(188): yii\db\Query->scalar(NULL)
#5 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/ProjectConfig.php(1711): craft\db\Query->scalar()
#6 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/ProjectConfig.php(1605): craft\services\ProjectConfig->_loadInternalConfigData()
#7 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/ProjectConfig.php(1594): craft\services\ProjectConfig->_getStoredConfig()
#8 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/ProjectConfig.php(397): craft\services\ProjectConfig->_getLoadedConfig()
#9 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/Plugins.php(1369): craft\services\ProjectConfig->get('plugins.calenda...')
#10 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/services/Plugins.php(206): craft\services\Plugins->_getPluginConfigData('calendar')
#11 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/base/ApplicationTrait.php(1351): craft\services\Plugins->loadPlugins()
#12 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/console/Application.php(59): craft\console\Application->_postInit()
#13 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#14 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#15 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#16 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/src/console/Application.php(48): yii\console\Application->__construct(Array)
#17 [internal function]: craft\console\Application->__construct(Array)
#18 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#19 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array)
#20 /var/www/nea/staging/releases/20200205173514/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#21 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array)
#22 /var/www/nea/staging/releases/20200205173514/vendor/craftcms/cms/bootstrap/console.php(43): require('/var/www/nea/st...')
#23 /var/www/nea/staging/releases/20200205173514/craft(21): require('/var/www/nea/st...')
#24 {main}
```

**Comment by brandonkelly** [comment]
That `Unknown column 'config' in 'field list'` error indicates that the database has already been partially migrated to 3.4. You need to restore a database backup that was created **before** you ever attempted to update to Craft 3.4, then try again.

**Comment by leobauza** [comment]
I did restore the database. I restored it to our production database which is at `3.1.34`. I've restored it it back to that DB before updating every time I've tried to do this update and I get the same error. So it has never been partially migrated to `3.4` we haven't ever tried to update production.

**Comment by brandonkelly** [comment]
Try re-importing that database backup, and then check your `info` table. Does it have a `config` column?

**Comment by leobauza** [comment]
Reimported the db backup into our staging environment and rolled everything back to how it was before attempting the update to 3.4.4 and the `info` table does have a `config` column. Screenshot below:

<img width="948" alt="Screenshot 2020-02-05 19 49 26" src="https://user-images.githubusercontent.com/1823027/73896336-b2a59100-4850-11ea-922e-0f2929584724.png">

**Comment by brandonkelly** [comment]
OK, and are you already getting the `config` column error? I’d assume not. Do you get the “Finish up” button when you visit the control panel? If you click it, do you get an error? What is **that** error? I’m assuming not the same `config` column error – until you try reloading the control panel or something _after_ getting that initial error.

**Comment by leobauza** [comment]
We tracked down the problem to an issue with our server that was messing things up during the migration part of our deployment script. Fixed on our end 👍 

Thanks for your help/patience/responses 🙏

**Comment by brandonkelly** [comment]
Awesome, glad you got it sorted!
