### ISSUE TITLE
Error when running `./craft project-config/sync`

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#5660]
### Description
Been working locally on a large feature for a site. Was ready for others to check it out, so I pushed my changes, changed the staging server over to the feature branch & ran `git pull`, `composer install`, & `./craft project-config/sync`. The first two completed without a hitch, but the last one returned this error:

`error: Getting unknown property: craft\redactor\Field::contentTable`

And now many of the new fields I'm expecting to see in the backend aren't there.

### Additional info

- Craft version: 3.3.18.3
- PHP version: 7.2.24
- Database driver & version:
- Plugins & versions: See image (Craft could stand to have a built-in "Export software info for support" button...)

![control_settings_plugins](https://user-images.githubusercontent.com/1027523/74610857-9f6fac80-50ff-11ea-86d5-ff0ba410ada4.png)

**Comment by andris-sevcenko** [comment]
Sounds like you might be hitting #5419. Can you update Craft to the latest 3.3.x version and then try again?

**Comment by proimage** [comment]
Herp derp!

```bash
> composer require craftcms/cms:3.3.20.1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: yiisoft/yii2[2.0.31, 2.0.30].
    - Can only install one of: yiisoft/yii2[2.0.31, 2.0.30].
    - Can only install one of: yiisoft/yii2[2.0.31, 2.0.30].
    - craftcms/cms 3.3.20.1 requires yiisoft/yii2 ~2.0.31.0 -> satisfiable by yiisoft/yii2[2.0.31].
    - Installation request for craftcms/cms 3.3.20.1 -> satisfiable by craftcms/cms[3.3.20.1].
    - Installation request for yiisoft/yii2 (locked at 2.0.30) -> satisfiable by yiisoft/yii2[2.0.30].


Installation failed, reverting ./composer.json to its original content.
```

Yii is locked. Why is Yii locked? Yii being locked does not help. Help me make Yii not locked. 😛

**Comment by jamiewade** [comment]
@proimage Instead of updating Craft by using `composer require ....`, try using `composer update`.

In your `composer.json` file, change your Craft package version to `"craftcms/cms": "3.3.*"`, then run:

`composer update craftcms/cms --with-dependencies`.

Changing your package to `3.3.*` will always update you to the latest version of Craft 3.3, and won't update you to 3.4.

The `--with-dependencies` flag updates the package you requested, plus its dependencies, in this case Yii.

Hope that helps.

**Comment by proimage** [comment]
@jamiewade Thanks, that resolved that part. I'll figure out composer one of these lifetimes.

**Comment by proimage** [comment]
Ok, marginally different now:

```
error: Getting unknown property: craft\fields\Assets::contentTable
```

**Comment by andris-sevcenko** [comment]
Which Caft version are we talking about here, @proimage?

**Comment by proimage** [comment]
3.3.20.1, both locally and remotely.

**Comment by andris-sevcenko** [comment]
Is it possible that you have a field that used to be a super table field and is now an Assets field?

**Comment by proimage** [comment]
Yes, that's quite possible...

**Comment by andris-sevcenko** [comment]
Perhaps you still have the stack trace in your error logs? That would help pinpoint it more accurately.

**Comment by proimage** [comment]
I'll see what I can find.

**Comment by proimage** [comment]
Found a couple. One was in `web.log`:

```
2020-02-21 05:02:52 [-][-][-][error][yii\web\HttpException:503] craft\web\ServiceUnavailableHttpException in /var/www/_________/htdocs/vendor/craftcms/cms/src/web/Application.php:697
Stack trace:
#0 /var/www/_________/htdocs/vendor/craftcms/cms/src/web/Application.php(256): craft\web\Application->_processConfigSyncLogic(Object(craft\web\Request))
#1 /var/www/_________/htdocs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#2 /var/www/_________/htdocs/web/index.php(21): yii\base\Application->run()
#3 {main}
2020-02-21 05:02:52 [-][-][-][info][application] $_GET = []
```

Then there's this one from `console.log`, which is probably what we're actually looking for, seeing as the error is in the console:

```
2020-02-21 05:03:01 [-][-][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2020-02-21 05:03:01 [-][-][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: craft\fields\Assets::contentTable in /var/www/_________/htdocs/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/_________/htdocs/vendor/verbb/super-table/src/services/SuperTableService.php(370): yii\base\Component->__get(‘contentTable’)
#1 /var/www/_________/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(872): verbb\supertable\services\SuperTableService->handleChangedBlockType(Object(craft\events\ConfigEvent))
#2 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#3 /var/www/_________/htdocs/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#4 /var/www/_________/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(551): yii\base\Component->trigger(‘addItem’, Object(craft\events\ConfigEvent))
#5 /var/www/_________/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(866): craft\services\ProjectConfig->processConfigChanges(‘superTableBlock...’)
#6 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#7 /var/www/_________/htdocs/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#8 /var/www/_________/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(551): yii\base\Component->trigger(‘addItem’, Object(craft\events\ConfigEvent))
#9 /var/www/_________/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(957): craft\services\ProjectConfig->processConfigChanges(‘superTableBlock...’)
#10 /var/www/_________/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(441): craft\services\ProjectConfig->_applyChanges(Array)
#11 /var/www/_________/htdocs/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(87): craft\services\ProjectConfig->applyYamlChanges()
#12 [internal function]: craft\console\controllers\ProjectConfigController->actionSync()
#13 /var/www/_________/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /var/www/_________/htdocs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /var/www/_________/htdocs/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction(‘sync’, Array)
#16 /var/www/_________/htdocs/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction(‘sync’, Array)
#17 /var/www/_________/htdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction(‘sync’, Array)
#18 /var/www/_________/htdocs/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction(‘project-config/...’, Array)
#19 /var/www/_________/htdocs/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction(‘project-config/...’, Array)
#20 /var/www/_________/htdocs/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction(‘project-config/...’, Array)
#21 /var/www/_________/htdocs/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#22 /var/www/_________/htdocs/craft(22): yii\base\Application->run()
#23 {main}
```

**Comment by andris-sevcenko** [comment]
@engram-design any chance you could see what Matrix field has done here and implement similar safeguards in SuprTable?

**Comment by engram-design** [comment]
@andris-sevcenko Will do, thanks for the heads-up!

**Comment by andris-sevcenko** [comment]
Closing, as this is an issue with SuperTable.

**Comment by paragonn** [comment]
Thanks all! @engram-design -- Is there an issue link that we can link too from this thread? Thanks!

**Comment by engram-design** [comment]
@paragonn There's not a Super Table issue for this yet. I haven't been following along with this issue, but it sounds like a field was changed from a Super Table field to an asset field?

The content table fixer for Super Table should also sort this out.

**Comment by paragonn** [comment]
Thanks @engram-design -- we will give that a try and let you know how it goes.
