### ISSUE TITLE
Array to string conversion - HTML Purifier Config

### ISSUE THREAD

**Issue by clarknelson** [craftcms/cms#5664]
### Description

I'm having a problem with the new craft and my redactor config.

``` json
{
  "AutoFormat" : {
    "RemoveEmpty": true
  },
  "HTML": {
    "AllowedElements": ["p", "strong", "em", "a", "ul", "ol", "li", "br"]
  },
  "Attr": {
    "AllowedFrameTargets": ["_blank"]
  }
}
```

Shows the message above, "Array to string conversion" which strange enough does not go away after removing the arrays. There might be some kind of update with how redactor is reading these files in 3.4.5? Thanks

### Additional info

- Craft version: 3.4.5
- PHP version: 7.3
- Database driver & version: mysql
- Plugins & versions: Redactor

**Comment by brandonkelly** [comment]
Try to find that error in `storage/logs/web.log`, and post the stack trace that follows it.

**Comment by clarknelson** [comment]
Is this stack trace any help?

```
2020-02-18 13:29:53 [-][1][27pk96tlp2u8t8u8apm546aog4][error][yii\base\ErrorException:8] yii\base\ErrorException: Array to string conversion in /Users/clarknelson/Documents/xxxx/live/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php:302
Stack trace:
#0 /Users/clarknelson/Documents/xxxx/live/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'Array to string...', '/Users/clarknel...', 302)
#1 /Users/clarknelson/Documents/xxxx/live/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php(302): craft\web\ErrorHandler->handleError(8, 'Array to string...', '/Users/clarknel...', 302, Array)
#2 /Users/clarknelson/Documents/xxxx/live/vendor/craftcms/redactor/src/Field.php(833): HTMLPurifier_Config->set('AutoFormat', NULL)
#3 /Users/clarknelson/Documents/xxxx/live/vendor/craftcms/redactor/src/Field.php(478): craft\redactor\Field->_getPurifierConfig()
#4 /Users/clarknelson/Documents/xxxx/live/vendor/craftcms/cms/src/base/Element.php(1424): craft\redactor\Field->serializeValue('<p>One of the c...', Object(craft\elements\Entry))
#5 [internal function]: craft\base\Element->validateCustomFieldContentSize('pageDescription', NULL, Object(yii\validators\InlineValidator))
#6 /Users/clarknelson/Documents/xxxx/live/vendor/yiisoft/yii2/validators/InlineValidator.php(72): call_user_func(Array, 'pageDescription', NULL, Object(yii\validators\InlineValidator))
#7 /Users/clarknelson/Documents/xxxx/live/vendor/yiisoft/yii2/validators/Validator.php(257): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\Entry), 'pageDescription')
#8 /Users/clarknelson/Documents/xxxx/live/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#9 /Users/clarknelson/Documents/xxxx/live/vendor/craftcms/cms/src/services/Elements.php(1981): yii\base\Model->validate()
#10 /Users/clarknelson/Documents/xxxx/live/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, NULL)
#11 /Users/clarknelson/Documents/xxxx/live/vendor/craftcms/cms/src/controllers/EntriesController.php(365): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#12 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#13 /Users/clarknelson/Documents/xxxx/live/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /Users/clarknelson/Documents/xxxx/live/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /Users/clarknelson/Documents/xxxx/live/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-entry', Array)
#16 /Users/clarknelson/Documents/xxxx/live/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#17 /Users/clarknelson/Documents/xxxx/live/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('entries/save-en...', Array)
#18 /Users/clarknelson/Documents/xxxx/live/vendor/craftcms/cms/src/web/Application.php(558): craft\web\Application->runAction('entries/save-en...', Array)
#19 /Users/clarknelson/Documents/xxxx/live/vendor/craftcms/cms/src/web/Application.php(269): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /Users/clarknelson/Documents/xxxx/live/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /Users/clarknelson/Documents/xxxx/live/web/index.php(21): yii\base\Application->run()
#22 /Users/clarknelson/.composer/vendor/laravel/valet/server.php(158): require('/Users/clarknel...')
#23 {main}
```

**Comment by brandonkelly** [comment]
Ah… yep that helps. Issue appears to be a JSON syntax error in your HTML Purifier config. Try removing the space in `"AutoFormat" :`.

**Comment by clarknelson** [comment]
Thank you!
