### ISSUE TITLE
Craft CLI gives "unknown method: craft\console\Request::getHeaders()"

### ISSUE THREAD

**Issue by robbue** [craftcms/cms#5700]
### Description
I'm having trouble running the `./craft` command and can not figure out what is wrong. I updated from 3.1 to 3.4 so that may have something to do with the problem.

```
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getHeaders()'

in /app/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /app/config/element-api.php(9): yii\base\Component->__call('getHeaders', Array)
#1 /app/vendor/craftcms/cms/src/services/Config.php(202): include('/app/config/ele...')
#2 /app/vendor/craftcms/cms/src/services/Plugins.php(890): craft\services\Config->getConfigFromFile('element-api')
#3 /app/vendor/craftcms/cms/src/services/Plugins.php(228): craft\services\Plugins->createPlugin('element-api', Array)
#4 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1376): craft\services\Plugins->loadPlugins()
#5 /app/vendor/craftcms/cms/src/console/Application.php(59): craft\console\Application->_postInit()
#6 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#7 /app/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#8 /app/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#9 /app/vendor/craftcms/cms/src/console/Application.php(48): yii\console\Application->__construct(Array)
#10 [internal function]: craft\console\Application->__construct(Array)
#11 /app/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#12 /app/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array)
#13 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#14 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array)
#15 /app/vendor/craftcms/cms/bootstrap/console.php(43): require('/app/vendor/cra...')
#16 /app/craft(21): require('/app/vendor/cra...')
#17 {main}
```

### Additional info

- Craft version: 3.4.7.1
- PHP version: 7.3.2

**Comment by jamesmacwhite** [comment]
Not official Craft support but the stack trace seems to be related to the Element API plugin, possibly something in config/element-api.php?

**Comment by brandonkelly** [comment]
Looks like your `config/element-api.php` file is calling `Craft::$app->request->getHeaders()`, which is a function that is only available for web requests.

Hard to know the best way to solve this without seeing your code, but you have two options:

1. Move custom logic into the endpoint callback functions:
   ```php
   'your-uri-pattern' => function() {
       $headers = Craft::$app->request->getHeaders();
       // ...
   },
   ```

2. Just be a little more careful about the type of request before calling web request-specific methods:
   ```php
   if (!Craft::$app->request->isConsoleRequest) {
       $headers = Craft::$app->request->getHeaders();
       // ...
   }
   ```

**Comment by robbue** [comment]
Thanks for helping my end-of-week-eyes to find the issue!

Checking `isConsoleRequest` 
```php
!Craft::$app->request->isConsoleRequest
```
 fixed it in `config/element-api.php`

**Comment by Friksel** [comment]
Had the exact same issue. And chacking isConsoleRequest is a nice fix for it! Thanks for this!
