### ISSUE TITLE
Deprecator->log() shouldn't throw an exception for long messages

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#5738]
### Description

If you try to log something via `Deprecator->log()` that's > 255 characters, it throws an exception:

```
[28-Feb-2020 13:21:28 America/New_York] An Error occurred while handling another error:
PDOException: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255) in /home/forge/devmode.fm/cms/vendor/yiisoft/yii2/db/Command.php:1290
Stack trace:
#0 /home/forge/devmode.fm/cms/vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute()
#1 /home/forge/devmode.fm/cms/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO "de...')
#2 /home/forge/devmode.fm/cms/vendor/craftcms/cms/src/services/Deprecator.php(133): yii\db\Command->execute()
#3 /home/forge/devmode.fm/cms/vendor/nystudio107/craft-twigpack/src/helpers/Manifest.php(138): craft\services\Deprecator->log('craft.twigpack....', 'craft.twigpack....')
```

...as least with Posgres. It feels like the `log()` method should truncate to 255 characters rather than throwing an exception that brings the site down?

### Steps to reproduce

1. Try logging something long, such as:

```php
        Craft::$app->getDeprecator()->log('craft.twigpack.includeCssRelPreloadPolyfill()', 'craft.twigpack.includeCssRelPreloadPolyfill() has been deprecated, this function now does nothing. Using the new media="print" pattern for loading CSS eliminates the need for a polyfill. You can safely remove craft.twigpack.includeCssRelPreloadPolyfill() from your templates.');
```

### Additional info

- Craft version: 3.4.8
- PHP version: 7.1.x
- Database driver & version: Postgres
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just released Craft 3.4.9 with a fix.

**Comment by khalwat** [comment]
You're the best!

**Comment by brandonkelly** [comment]
_You’re_ the best!
