### ISSUE TITLE
Issue with project.yaml trying to apply changes for a not yet added site

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#5790]
### Description
For some reason, after adding new site we've had an issue with the updates not being applied anymore.

```
2020-03-13 08:23:22 [-][-][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: 06849a96-b41c-4d54-9a18-a8e0b9e1e9fd in /app/vendor/craftcms/cms/src/services/Categories.php:392
Stack trace:
#0 /app/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/app/vendor/cra...', 392)
#1 /app/vendor/craftcms/cms/src/services/Categories.php(392): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/app/vendor/cra...', 392, Array)
#2 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1092): craft\services\Categories->handleChangedCategoryGroup(Object(craft\events\ConfigEvent))
#3 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#4 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#5 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(666): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#6 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1082): craft\services\ProjectConfig->processConfigChanges('categoryGroups....')
#7 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#8 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#9 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(663): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#10 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(480): craft\services\ProjectConfig->processConfigChanges('categoryGroups....', true, 'Copy site setti...')
#11 /app/vendor/craftcms/cms/src/services/Sites.php(762): craft\services\ProjectConfig->set('categoryGroups....', Array, 'Copy site setti...')
#12 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1092): craft\services\Sites->handleChangedSite(Object(craft\events\ConfigEvent))
#13 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#14 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#15 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(663): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#16 /app/vendor/craftcms/cms/src/helpers/ProjectConfig.php(89): craft\services\ProjectConfig->processConfigChanges('sites.019a5897-...')
#17 /app/vendor/craftcms/cms/src/services/Sections.php(595): craft\helpers\ProjectConfig::ensureAllSitesProcessed()
#18 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1092): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#19 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#20 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#21 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(666): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#22 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1082): craft\services\ProjectConfig->processConfigChanges('sections.2fd011...')
#23 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#24 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#25 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(666): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#26 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1180): craft\services\ProjectConfig->processConfigChanges('sections.2fd011...', false, NULL, true)
#27 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(527): craft\services\ProjectConfig->_applyChanges(Array)
#28 /app/vendor/craftcms/cms/src/controllers/ConfigSyncController.php(52): craft\services\ProjectConfig->applyYamlChanges()
#29 [internal function]: craft\controllers\ConfigSyncController->actionApplyYamlChanges()
#30 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#31 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#32 /app/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('apply-yaml-chan...', Array)
#33 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('apply-yaml-chan...', Array)
#34 /app/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('config-sync/app...', Array)
#35 /app/vendor/craftcms/cms/src/web/Application.php(685): craft\web\Application->runAction('config-sync/app...')
#36 /app/vendor/craftcms/cms/src/web/Application.php(248): craft\web\Application->_processConfigSyncLogic(Object(craft\web\Request))
#37 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#38 /app/web/index.php(21): yii\base\Application->run()
```

**Project.yaml is available upon request.**

### Additional info

- Craft version: 3.4.9
- PHP version: 7.3
- Database driver & version: Postgres 11

**Comment by brandonkelly** [comment]
Please send your `compsoer.json`, `composer.lock`, and a `project.yaml` file with changes that aren’t getting applied, plus a database backup, over to support@craftcms.com. We can try to look into it from there.

**Comment by jdsimcoe** [comment]
Hey @brandonkelly I'm seeing something similar when trying to run `./craft project-config/sync` on my Laravel Forge deploys:

```
Status: error
Response: {"error":"A server error occurred."}
```
I just sent an email with my files to the above email.

**Comment by brandonkelly** [comment]
Just got word that this has already been fixed via afbeb27762378203100697cb4cb5ec9a3d6a49c7. We’ll get 3.4.10 out early next week with that.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#5828d0b6124e35868cc4498db4965c7dde6d5357",
  "...": "..."
}
```

Then run `composer update`.

@jdsimcoe That seems like an unrelated issue.

**Comment by jdsimcoe** [comment]
Ok @brandonkelly should I duplicate my details and open a new Issue?

**Comment by brandonkelly** [comment]
@jdsimcoe Most likely an environmental issue, so we’ll just work with you over support.

**Comment by jdsimcoe** [comment]
@brandonkelly I tried the [afbeb27](https://github.com/craftcms/cms/commit/afbeb27762378203100697cb4cb5ec9a3d6a49c7) fix above and my `project.yaml` syncing issue was resolved just now when it deployed to `Laravel Forge`.

**Comment by brandonkelly** [comment]
@jdsimcoe Ah great, happy to be proven wrong :)

**Comment by jdsimcoe** [comment]
Haha @brandonkelly wasn't trying to prove you wrong but thought it was worth giving it a try! 😆

**Comment by brandonkelly** [comment]
3.4.10 is out now with the fix.

**Comment by umkasanki** [comment]
I have same issue during sync (dev > prod) after updating Craft from 3.4.23 to 3.5.9
Configuration files sent to support@craftcms.com

**Comment by davidhellmann** [comment]
I run in the same issue yesterday with Craft 3.7.28

```
22:51:10 Applying changes from your project config files ...

22:51:25 error: Could not acquire a lock to apply project config changes.
```

It's on the stage env. Locally with the same DB it runs without problems.

**Comment by brandonkelly** [comment]
@davidhellmann I have a feeling it can happen if a previous lock was not released properly. Try restarting the database server and see if that helps.

**Comment by davidhellmann** [comment]
@brandonkelly 
Thanks for reply. You're right. DB Server restart fixed it. What not in my hands to do that but the DevOps Team did it the next morning.
