### ISSUE TITLE
Unable to sync project config (Argument 1 passed to craft\services\Fields::restoreLayoutById() must be of the type int, null given)

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#5915]
### Description

```
2020-04-13 13:58:47 [-][-][-][error][TypeError] TypeError: Argument 1 passed to craft\services\Fields::restoreLayoutById() must be of the type int, null given, called in /var/www/html/vendor/craftcms/cms/src/elements/GlobalSet.php on line 237 and defined in /var/www/html/vendor/craftcms/cms/src/services/Fields.php:1400
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/elements/GlobalSet.php(237): craft\services\Fields->restoreLayoutById(NULL)
#1 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1386): craft\elements\GlobalSet->afterRestore()
#2 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1287): craft\services\Elements->restoreElements(Array)
#3 /var/www/html/vendor/craftcms/cms/src/services/Globals.php(423): craft\services\Elements->restoreElement(Object(craft\elements\GlobalSet))
#4 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1102): craft\services\Globals->handleChangedGlobalSet(Object(craft\events\ConfigEvent))
#5 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#6 /var/www/html/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#7 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(675): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#8 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1204): craft\services\ProjectConfig->processConfigChanges('globalSets.491d...', false, NULL, true)
#9 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(539): craft\services\ProjectConfig->_applyChanges(Array)
#10 /var/www/html/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(87): craft\services\ProjectConfig->applyYamlChanges()
#11 [internal function]: craft\console\controllers\ProjectConfigController->actionSync()
#12 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('sync', Array)
#15 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(187): yii\console\Controller->runAction('sync', Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('sync', Array)
#17 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#18 /var/www/html/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('project-config/...', Array)
#19 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#20 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#21 /var/www/html/craft(22): yii\base\Application->run()
#22 {main}
```

### Steps to reproduce

1. Make some project config changes.
2. Try a sync or force sync.

### Additional info

- Craft version: 3.4.15
- PHP version: 7.3.x

**Comment by brandonkelly** [comment]
Thanks for reporting that. Looks like this happened because the `project.yaml` file contained a global set that was soft-deleted on the target database. Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#309d06c97a84750bb02bfadc46467aeb27052234 as 3.4.15",
  "...": "..."
}
```

Then run `composer update`.

**Comment by ryanpcmcquen** [comment]
Ah, the old soft-delete bait and switch. Thanks for the quick fix!

**Comment by ryanpcmcquen** [comment]
By the way, that fix worked for us.

**Comment by brandonkelly** [comment]
Thanks for letting me know!

**Comment by brandonkelly** [comment]
Craft 3.4.16 is out now with that fix.
