### ISSUE TITLE
m190913_152146_update_preview_targets migration fails

### ISSUE THREAD

**Issue by brianjhanson** [craftcms/cms#5943]
### Description
I'm in the process of updating a Craft site from  2.6.3019 to 3.5 (the 3.5 version is slightly unintentional and I don't believe related to the issue). When running the first migration with `./craft migrate/up --type=app` it consistently fails on the `m190913_152146_update_preview_targets` migration with the error
```
Exception: Setting unknown property: craft\records\Site::enabled (/home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/Component.php:209)
```

<details><summary><strong>Stack Trace</strong></summary>
<p>

```
Exception: Setting unknown property: craft\records\Site::enabled (/home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/Component.php:209)
#0 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set()
#1 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/db/ActiveRecord.php(41): yii\db\BaseActiveRecord->__set()
#2 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/services/Sites.php(717): craft\db\ActiveRecord->__set()
#3 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/services/ProjectConfig.php(1099): craft\services\Sites->handleChangedSite()
#4 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#5 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/Component.php(627): call_user_func()
#6 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/services/ProjectConfig.php(675): yii\base\Component->trigger()
#7 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/helpers/ProjectConfig.php(89): craft\services\ProjectConfig->processConfigChanges()
#8 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/services/Sections.php(595): craft\helpers\ProjectConfig::ensureAllSitesProcessed()
#9 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/services/ProjectConfig.php(1099): craft\services\Sections->handleChangedSection()
#10 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#11 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/Component.php(627): call_user_func()
#12 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/services/ProjectConfig.php(678): yii\base\Component->trigger()
#13 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/services/ProjectConfig.php(1089): craft\services\ProjectConfig->processConfigChanges()
#14 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#15 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/Component.php(627): call_user_func()
#16 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/services/ProjectConfig.php(675): yii\base\Component->trigger()
#17 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/services/ProjectConfig.php(489): craft\services\ProjectConfig->processConfigChanges()
#18 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/migrations/m190913_152146_update_preview_targets.php(54): craft\services\ProjectConfig->set()
#19 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m190913_152146_update_preview_targets->safeUp()
#20 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): craft\db\Migration->up()
#21 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(200): yii\console\controllers\BaseMigrateController->migrateUp()
#22 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/console/controllers/MigrateController.php(314): yii\console\controllers\BaseMigrateController->actionUp()
#23 [internal function]: craft\console\controllers\MigrateController->actionUp()
#24 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#25 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#26 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction()
#27 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#28 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#29 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction()
#30 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#31 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#32 /home/vagrant/code/fn-migrate/craft(22): yii\base\Application->run()
#33 {main}
```
</p>

</details>

### Steps to reproduce
1. Import DB from 2.6.3019 site into 3.5 codebase
2. run `craft migrate/up --type=app`

### Additional info

- Craft version: 3.5 (778e4eef957877b42d5c6cb4ef9f5435a9e7bf6d)
- PHP version: 7.4.4
- Database driver & version: 5.7.29-0ubuntu0.18.04.1 (homestead)

**Comment by brandonkelly** [comment]
Please send a database backup over to support@craftcms.com so we can test with that.

**Comment by olivierbon** [comment]
Closed in support - project specific error.
