### ISSUE TITLE
Running commands via cron doesn't work

### ISSUE THREAD

**Issue by aNickzz** [craftcms/cms#6102]
### Description
If I run `./craft` I get the expected list of commands. If I don the exact same thing in a cron job, I get an error.

I also tried explicitly specifying the path to `php` but that made no difference, and the system that I'm on doesn't have a `php-cli` executable.

I ran a few different cron jobs and worked out that `PHP_SAPI === 'cgi-fcgi'` as noted [here](https://www.php.net/manual/en/function.php-sapi-name.php#89858), and that the output of `phpinfo();` is formatted as HTML when run via cron but not via bash (which is something I've raised with my VPS provider).

```text
Status: 500 Internal Server Error
X-Powered-By: PHP/7.2.30
Content-type: text/html; charset=UTF-8

Exception 'yii\base\InvalidConfigException' with message 'Unable to determine the entry script file path.'

in /.../site/vendor/yiisoft/yii2/base/Request.php:64

Stack trace:
#0 /.../site/vendor/craftcms/cms/src/console/Request.php(32): yii\base\Request->getScriptFile()
#1 /.../site/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Request->init()
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /.../site/vendor/yiisoft/yii2/di/Container.php(392): ReflectionClass->newInstanceArgs(Array)
#4 /.../site/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\R...', Array, Array)
#5 /.../site/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('craft\\console\\R...', Array)
#6 /.../site/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject('craft\\console\\R...')
#7 /.../site/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('request', true)
#8 /.../site/vendor/craftcms/cms/src/console/Application.php(156): yii\base\Module->get('request', true)
#9 /.../site/vendor/yiisoft/yii2/console/Application.php(219): craft\console\Application->get('request')
#10 /.../site/vendor/craftcms/cms/src/helpers/App.php(512): yii\console\Application->getRequest()
#11 /.../site/vendor/craftcms/cms/src/config/app.php(219): craft\helpers\App::logConfig()
#12 [internal function]: {closure}()
#13 /.../site/vendor/yiisoft/yii2/di/Container.php(524): call_user_func_array(Object(Closure), Array)
#14 /.../site/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->invoke(Object(Closure), Array)
#15 /.../site/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#16 /.../site/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('log', true)
#17 /.../site/vendor/craftcms/cms/src/console/Application.php(156): yii\base\Module->get('log', true)
#18 /.../site/vendor/yiisoft/yii2/base/Application.php(508): craft\console\Application->get('log')
#19 /.../site/vendor/craftcms/cms/src/base/ApplicationTrait.php(1355): yii\base\Application->getLog()
#20 /.../site/vendor/craftcms/cms/src/console/Application.php(57): craft\console\Application->_preInit()
#21 /.../site/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#22 /.../site/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#23 /.../site/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#24 /.../site/vendor/craftcms/cms/src/console/Application.php(48): yii\console\Application->__construct(Array)
#25 [internal function]: craft\console\Application->__construct(Array)
#26 /.../site/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#27 /.../site/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array)
#28 /.../site/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#29 /.../site/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array)
#30 /.../site/vendor/craftcms/cms/bootstrap/console.php(43): require('/...')
#31 /.../site/craft(20): require('/...')
#32 {main}
```

If I manually set the `SCRIPT_FILENAME` by prefixing it to the command
`SCRIPT_FILENAME="/.../site/craft" /.../site/craft`
I get a different error

```text
Status: 500 Internal Server Error
X-Powered-By: PHP/7.2.30
Content-type: text/html; charset=UTF-8

Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: craft\console\User::enableSession'

in /.../site/vendor/yiisoft/yii2/base/Component.php:154

Stack trace:
#0 /.../site/vendor/craftcms/cms/src/helpers/App.php(513): yii\base\Component->__get('enableSession')
#1 /.../site/vendor/craftcms/cms/src/config/app.php(219): craft\helpers\App::logConfig()
#2 [internal function]: {closure}()
#3 /.../site/vendor/yiisoft/yii2/di/Container.php(524): call_user_func_array(Object(Closure), Array)
#4 /.../site/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->invoke(Object(Closure), Array)
#5 /.../site/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#6 /.../site/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('log', true)
#7 /.../site/vendor/craftcms/cms/src/console/Application.php(156): yii\base\Module->get('log', true)
#8 /.../site/vendor/yiisoft/yii2/base/Application.php(508): craft\console\Application->get('log')
#9 /.../site/vendor/craftcms/cms/src/base/ApplicationTrait.php(1355): yii\base\Application->getLog()
#10 /.../site/vendor/craftcms/cms/src/console/Application.php(57): craft\console\Application->_preInit()
#11 /.../site/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#12 /.../site/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#13 /.../site/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#14 /.../site/vendor/craftcms/cms/src/console/Application.php(48): yii\console\Application->__construct(Array)
#15 [internal function]: craft\console\Application->__construct(Array)
#16 /.../site/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#17 /.../site/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array)
#18 /.../site/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#19 /.../site/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array)
#20 /.../site/vendor/craftcms/cms/bootstrap/console.php(43): require('/...')
#21 /.../site/craft(20): require('/...')
#22 {main}
```

To get around this I thought I could try `$request->setIsConsoleRequest(true);` but the error occurs before any of my code executes.

### Steps to reproduce

1. Create a cron job that runs the `craft` executable eg. `~/site/craft`

### Additional info

- Craft version: Craft Pro 3.4.9
- PHP version: 7.2.30
- Database driver & version: MySQL 5.7.29
- Plugins & versions: Available on request

**Comment by brandonkelly** [comment]
Thanks for reporting that! I’ve just updated the default Craft project to explicitly set the script filename, and inform Craft that it’s a console request, when accessed through the `craft` executable. That’s a project file though, not something that can be included in a normal Craft update – so you will need to make the same change manually to your own `craft` executable.

To make the change, open your `craft` executable, and find this line:

```php
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/console.php';
```

Add these two lines right after it:

```php
$app->getRequest()->setIsConsoleRequest(true);
$app->getRequest()->setScriptFile(__FILE__);
```

**Comment by aNickzz** [comment]
Hi @brandonkelly, the last line of both stack traces show that exceptions occur within line 20, or if you include the shebang, line 21, https://github.com/craftcms/craft/blob/bc85b197556538e97d226959d9f980d57b5d87f3/craft#L21
This means that adding code after that line won't help as execution won't reach it.

In lines 25 and 15 in the stack traces above you can see that it's throwing before the Application __constructor completes so perhaps there needs to be some constants defined before that line in the `craft` executable that can seed the `$_isConsoleRequest` and `$_scriptFile` fields during the construction of the request object.

**Comment by brandonkelly** [comment]
Sorry yeah you’re right. I just worked around these errors within Craft’s core code instead.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#1be005c6c5cbab8580962e987077058f1febdbc2 as 3.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with those changes.
