### ISSUE TITLE
[3.5 beta 2] :empty: / :notempty: failing

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#6135]
### Description

Trying to query an entry with a relation field not empty.
Working fine in 3.4, failing in 3.5 beta 2.

```
{% set entries = craft.entries({
  section: 'posts',
  myRelationField: ':notempty:',
  orderBy: 'postDate desc',
  limit: 2
})
```

Logs:

```
2020-05-25 11:05:41 [-][1][vqjrkurk8ssmoe9nmkd39al7r7][error][Error] Error: Class 'craft\fields\TableName' not found in /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/fields/BaseRelationField.php:451
Stack trace:
#0 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2095): craft\fields\BaseRelationField->modifyElementsQuery()
#1 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1337): craft\elements\db\ElementQuery->_joinContentTable()
#2 /home/ubuntu/sites/vlp.test/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
#3 /home/ubuntu/sites/vlp.test/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
#4 /home/ubuntu/sites/vlp.test/vendor/yiisoft/yii2/db/Query.php(248): yii\db\Query->createCommand()
#5 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all()
#6 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1466): craft\db\Query->all()
#7 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Extension/CoreExtension.php(1499): craft\elements\db\ElementQuery->all()
#8 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/helpers/Template.php(95): twig_get_attribute()
#9 /home/ubuntu/sites/vlp.test/storage/runtime/compiled_templates/bb/bb2b1caa80bb9d15a32e3c5db12806dc06fa133c518b15e639351e6a17fd9a00.php(292): craft\helpers\Template::attribute()
#10 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(184): __TwigTemplate_2989396281bfd075ccde6fab3cd502ff32ab4529133f70c84225fc3477886d29->block_detail_main()
#11 /home/ubuntu/sites/vlp.test/storage/runtime/compiled_templates/bb/bb2b1caa80bb9d15a32e3c5db12806dc06fa133c518b15e639351e6a17fd9a00.php(117): Twig\Template->displayBlock()
#12 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(407): __TwigTemplate_2989396281bfd075ccde6fab3cd502ff32ab4529133f70c84225fc3477886d29->doDisplay()
#13 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#14 /home/ubuntu/sites/vlp.test/storage/runtime/compiled_templates/d6/d611d0ba643e5b7ce70bcfc261079882e665864d32bfceda67b8463106795c3f.php(41): Twig\Template->display()
#15 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(407): __TwigTemplate_2b751a2753e3a4c583dbce68426ffcbce20fd62c18cb52e8e027eef6d539db70->doDisplay()
#16 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#17 /home/ubuntu/sites/vlp.test/storage/runtime/compiled_templates/3e/3e65dc6812d0b3dcd269e56e7de8a024362b5b1d12257bd97e178d48f8c0ec95.php(86): Twig\Template->display()
#18 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(184): __TwigTemplate_16778a5352005d30e11013c44f16fae45719b2371ca621bb70d1624c6bb3b2dd->block_main()
#19 /home/ubuntu/sites/vlp.test/storage/runtime/compiled_templates/72/72aa7441e64ae3185857dc0b5803d447cc1830953a7048019ebd95576cc235e4.php(74): Twig\Template->displayBlock()
#20 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(184): __TwigTemplate_2394c6ddb31bc8fa63e27fd09d7531ccef3f2a19d060e38358cd80cd86e5fa66->block_body()
#21 /home/ubuntu/sites/vlp.test/storage/runtime/compiled_templates/2b/2bfa75e604854fdd8cb68381e2a3be3e14648d4e236824f13f174d2361002fbb.php(63): Twig\Template->displayBlock()
#22 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(407): __TwigTemplate_06f1093aa0bb550891c7a665e9d44b985ad0a68064894c823eb740524934895f->doDisplay()
#23 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#24 /home/ubuntu/sites/vlp.test/storage/runtime/compiled_templates/72/72aa7441e64ae3185857dc0b5803d447cc1830953a7048019ebd95576cc235e4.php(50): Twig\Template->display()
#25 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(407): __TwigTemplate_2394c6ddb31bc8fa63e27fd09d7531ccef3f2a19d060e38358cd80cd86e5fa66->doDisplay()
#26 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#27 /home/ubuntu/sites/vlp.test/storage/runtime/compiled_templates/3e/3e65dc6812d0b3dcd269e56e7de8a024362b5b1d12257bd97e178d48f8c0ec95.php(70): Twig\Template->display()
#28 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(407): __TwigTemplate_16778a5352005d30e11013c44f16fae45719b2371ca621bb70d1624c6bb3b2dd->doDisplay()
#29 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#30 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Template.php(392): Twig\Template->display()
#31 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#32 /home/ubuntu/sites/vlp.test/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#33 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/web/View.php(406): Twig\Environment->render()
#34 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/web/View.php(467): craft\web\View->renderTemplate()
#35 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate()
#36 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/controllers/TemplatesController.php(98): craft\web\Controller->renderTemplate()
#37 [internal function]: craft\controllers\TemplatesController->actionRender()
#38 /home/ubuntu/sites/vlp.test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#39 /home/ubuntu/sites/vlp.test/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#40 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#41 /home/ubuntu/sites/vlp.test/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#42 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/web/Application.php(289): yii\base\Module->runAction()
#43 /home/ubuntu/sites/vlp.test/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#44 /home/ubuntu/sites/vlp.test/vendor/craftcms/cms/src/web/Application.php(274): yii\web\Application->handleRequest()
#45 /home/ubuntu/sites/vlp.test/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#46 /home/ubuntu/sites/vlp.test/web/index.php(21): yii\base\Application->run()
#47 {main}
```

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next beta release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.5.x-dev",
  "...": "..."
}
```

Then run `composer update`.
