### ISSUE TITLE
Project Config syncing fails due to missing UserAgend when changing Single Sections

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#6182]
### Description
Not sure if that's already solved by a newer Craft Version but we stuck on Craft Pro 3.3.20.1 due to the heavy amount of breaking changes in the last years. I changed the field layout of a single entry and wanted to sync the project config to a new environment. Then the error appears

> error: Calling unknown method: craft\console\Request::getUserAgent()

That's because you assume there is a User in your [Revisions Service](https://github.com/craftcms/cms/blob/develop/src/services/Revisions.php#L117)
Craft tries to create a Revision and set the creatorId based on the CurrentUser but since it's a console request there is none.

### Steps to reproduce

1. have an older version of Craft
2. change the field layout of a single section
3. sync it via console request

```
2020-06-04 13:43:09 [-][-][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2020-06-04 13:43:09 [-][-][-][error][yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: craft\console\Request::getUserAgent() in /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/web/User.php(561): yii\base\Component->__call('getUserAgent', Array)
#1 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/web/User.php(470): craft\web\User->_validateUserAgentAndIp()
#2 /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#3 /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/web/User.php(370): yii\web\User->getIdentity()
#4 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/services/Revisions.php(123): yii\web\User->getId()
#5 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/elements/Entry.php(1276): craft\services\Revisions->createRevision(Object(craft\elements\Entry), NULL, NULL)
#6 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/services/Elements.php(2043): craft\elements\Entry->afterPropagate(false)
#7 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/services/Elements.php(529): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false)
#8 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/services/Sections.php(1569): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#9 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/services/Sections.php(1274): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section))
#10 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(872): craft\services\Sections->handleChangedEntryType(Object(craft\events\ConfigEvent))
#11 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#12 /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#13 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(559): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#14 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(866): craft\services\ProjectConfig->processConfigChanges('sections.7ffe90...')
#15 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#16 /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#17 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(546): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#18 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(943): craft\services\ProjectConfig->processConfigChanges('sections.7ffe90...')
#19 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/services/ProjectConfig.php(441): craft\services\ProjectConfig->_applyChanges(Array)
#20 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(87): craft\services\ProjectConfig->applyYamlChanges()
#21 [internal function]: craft\console\controllers\ProjectConfigController->actionSync()
#22 /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#24 /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('sync', Array)
#25 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('sync', Array)
#26 /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('sync', Array)
#27 /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#28 /var/www/myspa/staging/htdocs/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('project-config/...', Array)
#29 /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#30 /var/www/myspa/staging/htdocs/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#31 /var/www/myspa/staging/htdocs/craft(22): yii\base\Application->run()
```

### Additional info

- Craft version: 3.3.20.1

**Comment by brandonkelly** [comment]
This doesn’t really make any sense… looks like somehow your `user` component is set to `craft\web\User`, but your `request` component is set to `craft\console\Request`. If it’s a console request, the `user` component should be `craft\console\User`, not `craft\web\User`. Are you overriding the `user` component yourself from `config/app.php` or something?

**Comment by brandonkelly** [comment]
You can move your original config over to `app.web.php`, and then it will only apply to web requests.
