### ISSUE TITLE
Exception when trying to save a page with Neo field

### ISSUE THREAD

**Issue by stefangallas** [craftcms/cms#6205]
I already put the bug in the issues of the Neo plugin, after other people's testing it looks like it was triggered by the last update to Craft 3.4.23.

If you copy and paste or duplicate nested Neo entries, an error is reported when saving the page. Sometimes saving works, but the next time you change this entry, the page cannot be saved anymore. If you delete the duplicated entry, it will work again. Other users also have problems when they create a Neo element on a page. For others it depends on the nesting of Neo entries, if the page could be saved or not.

Details can already be found at https://github.com/spicywebau/craft-neo/issues/363.

Stack Trace when trying to save a page:

```
2020-06-10 18:34:03 [-][152][pv3jcue6lmc0b27fk8b3etera1][error][yii\base\Exception] yii\base\Exception: There was a problem getting the parent element. in /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/services/Structures.php:243
Stack trace:
#0 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/services/Elements.php(817): craft\services\Structures->append()
#1 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/spicyweb/craft-neo/src/services/Fields.php(335): craft\services\Elements->duplicateElement()
#2 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/spicyweb/craft-neo/src/Field.php(686): benf\neo\services\Fields->duplicateBlocks()
#3 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/base/Element.php(2577): benf\neo\Field->afterElementPropagate()
#4 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/elements/Entry.php(1309): craft\base\Element->afterPropagate()
#5 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/services/Elements.php(891): craft\elements\Entry->afterPropagate()
#6 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/services/Revisions.php(160): craft\services\Elements->duplicateElement()
#7 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/elements/Entry.php(1313): craft\services\Revisions->createRevision()
#8 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/services/Elements.php(2181): craft\elements\Entry->afterPropagate()
#9 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/services/Elements.php(531): craft\services\Elements->_saveElementInternal()
#10 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/controllers/EntriesController.php(376): craft\services\Elements->saveElement()
#11 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#12 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#13 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#14 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#15 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#16 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#17 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction()
#18 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest()
#19 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#20 /home/wmf-cms/webapps/wmf-cms-prod/releases/1591783320978/web/index.php(21): yii\base\Application->run()
#21 {main}
```

**Comment by gregorterrill** [comment]
For me it wasn't specifically related to duplicating anything. Just after updating Neo + Craft to the latest versions, a handful of entries containing Neo fields refuse to preview, save, revert to a previous revision, or allow me to make changes in any way. Everything throws this "There was a problem getting the parent element" error. On a site of a few hundred entries, it's happening on only a few of them.

**Comment by ambidustrious** [comment]
I am getting this error as well

**Comment by brandonkelly** [comment]
Fixed for the next release, but will also require a Neo update. See https://github.com/spicywebau/craft-neo/issues/363#issuecomment-643274817 for details.

**Comment by brandonkelly** [comment]
Craft 3.4.24 is out now with this fix.
