### ISSUE TITLE
Error deleting a Field from Control panel

### ISSUE THREAD

**Issue by weotch** [craftcms/cms#6267]
### Description

When deleting a Field I'm getting a `500` response from the server.  I enabled the debug tool bar and saw this error in it:

```
TypeError: Argument 2 passed to craft\services\Fields::applyFieldSave() must be of the type array, null given, called in /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/services/Fields.php on line 826 and defined in /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/services/Fields.php:1432
Stack trace:
#0 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/services/Fields.php(826): craft\services\Fields->applyFieldSave()
#1 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/services/ProjectConfig.php(1102): craft\services\Fields->handleChangedField()
#2 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#3 /home/forge/domain.com/craft-cms/vendor/yiisoft/yii2/base/Component.php(627): call_user_func()
#4 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/services/ProjectConfig.php(678): yii\base\Component->trigger()
#5 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/services/ProjectConfig.php(489): craft\services\ProjectConfig->processConfigChanges()
#6 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/services/ProjectConfig.php(505): craft\services\ProjectConfig->set()
#7 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/services/Fields.php(868): craft\services\ProjectConfig->remove()
#8 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/services/Fields.php(843): craft\services\Fields->deleteField()
#9 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/controllers/FieldsController.php(338): craft\services\Fields->deleteFieldById()
#10 [internal function]: craft\controllers\FieldsController->actionDeleteField()
#11 /home/forge/domain.com/craft-cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#12 /home/forge/domain.com/craft-cms/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#13 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#14 /home/forge/domain.com/craft-cms/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#15 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#16 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction()
#17 /home/forge/domain.com/craft-cms/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest()
#18 /home/forge/domain.com/craft-cms/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#19 /home/forge/domain.com/craft-cms/web/index.php(21): yii\base\Application->run()
#20 {main}
```

### Steps to reproduce

1. Create a field
2. Delete the field in the listing view via:

![image](https://user-images.githubusercontent.com/77567/85779172-306f1980-b6d8-11ea-9e57-2df39e80465d.png)

### Additional info

- Craft version: 3.4.25
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.19
- Plugins & versions:

![Screen Shot 2020-06-25 at 11 37 47 AM](https://user-images.githubusercontent.com/77567/85779290-4da3e800-b6d8-11ea-9494-d72c0685d8ca.png)

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Please send your `composer.json` and `composer.lock` files, plus a database backup, into support@craftcms.com and we can try to look into it from there.

**Comment by weotch** [comment]
Thanks @brandonkelly, just sent that in.

**Comment by weotch** [comment]
It was magically resolved the next day ... 

![](https://media.giphy.com/media/O6kb3Pa3Kgbsc/giphy.gif)
