### ISSUE TITLE
Integrity constraint violation when updating content in Preview

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6344]
### Description
Updating content in Preview gives a little red error "A server error occurred" at the top when I delete the content of a non-required text field in a matrix block
### Steps to reproduce

1. Add content to a matrix block while Preview is open, it updates correctly
2. Empty the field. I see the red warning in Preview, then the attached error log.
3. Adding content to the field again gives the same error message and won't update any more

### Additional info

```
2020-07-08 08:36:08 [-][2022][-][profile end][yii\db\Command::query] SELECT *
FROM `craft_entries`
WHERE `id`='23109'
2020-07-08 08:36:08 [-][2022][-][info][yii\db\Command::execute] UPDATE `craft_entries` SET `typeId`=23109, `dateUpdated`='2020-07-08 07:36:08' WHERE `id`=23109
2020-07-08 08:36:08 [-][2022][-][profile begin][yii\db\Command::execute] UPDATE `craft_entries` SET `typeId`=23109, `dateUpdated`='2020-07-08 07:36:08' WHERE `id`=23109
2020-07-08 08:36:08 [-][2022][-][profile end][yii\db\Command::execute] UPDATE `craft_entries` SET `typeId`=23109, `dateUpdated`='2020-07-08 07:36:08' WHERE `id`=23109
2020-07-08 08:36:08 [-][2022][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2020-07-08 08:36:08 [-][2022][-][error][yii\db\IntegrityException] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitename`.`craft_entries`, CONSTRAINT `craft_entries_typeId_fk` FOREIGN KEY (`typeId`) REFERENCES `craft_entrytypes` (`id`) ON DELETE CASCADE) in /Users/darylknight/Sites/sitename/vendor/yiisoft/yii2/db/Command.php:1293
Stack trace:
#0 /Users/darylknight/Sites/sitename/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute()
#1 /Users/darylknight/Sites/sitename/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('UPDATE `craft_e...')
#2 /Users/darylknight/Sites/sitename/vendor/yiisoft/yii2/db/ActiveRecord.php(332): yii\db\Command->execute()
#3 /Users/darylknight/Sites/sitename/vendor/yiisoft/yii2/db/BaseActiveRecord.php(810): yii\db\ActiveRecord::updateAll(Array, Array)
#4 /Users/darylknight/Sites/sitename/vendor/yiisoft/yii2/db/ActiveRecord.php(676): yii\db\BaseActiveRecord->updateInternal(NULL)
#5 /Users/darylknight/Sites/sitename/vendor/yiisoft/yii2/db/BaseActiveRecord.php(681): yii\db\ActiveRecord->update(false, NULL)
#6 /Users/darylknight/Sites/sitename/vendor/craftcms/cms/src/elements/Entry.php(1279): yii\db\BaseActiveRecord->save(false)
#7 /Users/darylknight/Sites/sitename/vendor/craftcms/cms/src/services/Elements.php(2169): craft\elements\Entry->afterSave(false)
#8 /Users/darylknight/Sites/sitename/vendor/craftcms/cms/src/services/Elements.php(531): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#9 /Users/darylknight/Sites/sitename/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(224): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#10 [internal function]: craft\controllers\EntryRevisionsController->actionSaveDraft()
#11 /Users/darylknight/Sites/sitename/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/darylknight/Sites/sitename/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /Users/darylknight/Sites/sitename/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-draft', Array)
#14 /Users/darylknight/Sites/sitename/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-draft', Array)
#15 /Users/darylknight/Sites/sitename/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('entry-revisions...', Array)
#16 /Users/darylknight/Sites/sitename/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('entry-revisions...', Array)
#17 /Users/darylknight/Sites/sitename/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /Users/darylknight/Sites/sitename/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/darylknight/Sites/sitename/public_html/index.php(21): yii\base\Application->run()
#20 /Users/darylknight/.composer/vendor/laravel/valet/server.php(158): require('/Users/darylkni...')
#21 {main}
```

- Craft version: 3.4.27
- PHP version: 7.4
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you send your Composer files and a database backup into support@craftcms.com? And please tell us exactly where you’re seeing the error.

**Comment by brandonkelly** [comment]
We were able to reproduce with your files, and got this fixed for the next release!

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop as 3.4.28.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.29 is out now with this fix.
