### ISSUE TITLE
[3.5-dev] New field layout editor breaks Neo field's settings

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#6358]
### Description

Attempting to edit field layouts on Neo fields produces the following error:
```
Twig\Error\RuntimeError: Impossible to access an attribute ("id") on a boolean variable (""). in /Users/ransom/Projects/Work/craftcms/src/templates/_includes/forms/fieldLayoutDesigner.html:79
Stack trace:
#0 /Users/ransom/Projects/Work/craftcms/src/helpers/Template.php(90): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), false, 'id', Array, 'any', false, false)
#1 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/35/357155e5d274f3618165245f3cbef71933a09b18b377a0e897bf9f82cf16dee1.php(74): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), false, 'id', Array)
#2 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(407): __TwigTemplate_db080368b6392ca2ca9833c0f60eb12fcd88c4fb01b8635725d51ee9a7f1adc3->doDisplay(Array, Array)
#3 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/dc/dc7781c82e3ed3111b546fccdda090da44c9b177a4de44264962fa8ee2b723e6.php(809): Twig\Template->display(Array)
#5 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Extension/CoreExtension.php(1109): __TwigTemplate_58ea2609080f446651a22e3673591ce1cd248effa62b19d706071db772eaa49f->macro_fieldLayoutDesigner(Array)
#6 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/dc/dc7781c82e3ed3111b546fccdda090da44c9b177a4de44264962fa8ee2b723e6.php(1557): twig_call_macro(Object(__TwigTemplate_58ea2609080f446651a22e3673591ce1cd248effa62b19d706071db772eaa49f), 'macro_fieldLayo...', Array, 273, Array, Object(Twig\Source))
#7 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Extension/CoreExtension.php(1109): __TwigTemplate_58ea2609080f446651a22e3673591ce1cd248effa62b19d706071db772eaa49f->macro_fieldLayoutDesignerField(Array)
#8 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/66/66616f9b322a25ba38267dd6427df7a005e99d8a0b4fcc2ac7e35992a3e2b540.php(48): twig_call_macro(Object(__TwigTemplate_58ea2609080f446651a22e3673591ce1cd248effa62b19d706071db772eaa49f), 'macro_fieldLayo...', Array, 3, Array, Object(Twig\Source))
#9 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(407): __TwigTemplate_df109cfc5de63801a45d0a44d328951d26e3ebd6ed4a68ca8235ad36fe66eb9f->doDisplay(Array, Array)
#10 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#12 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#13 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#14 /Users/ransom/Projects/Work/craftcms/src/web/View.php(392): Twig\Environment->render('_includes/field...', Array)
#15 /Users/ransom/Projects/Work/craft-dev/vendor/spicyweb/craft-neo/src/assets/FieldAsset.php(112): craft\web\View->renderTemplate('_includes/field...', Array)
#16 /Users/ransom/Projects/Work/craft-dev/vendor/spicyweb/craft-neo/src/Field.php(335): benf\neo\assets\FieldAsset::createSettingsJs(Object(benf\neo\Field))
#17 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Extension/CoreExtension.php(1499): benf\neo\Field->getSettingsHtml()
#18 /Users/ransom/Projects/Work/craftcms/src/helpers/Template.php(90): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(benf\neo\Field), 'getSettingsHtml', Array, 'method', false, false)
#19 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/a2/a2339556e1fa726b5730b04248d5ee893fa2cef1c3481490e8f1d1b7cb830da5.php(46): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(benf\neo\Field), 'getSettingsHtml', Array, 'method')
#20 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(407): __TwigTemplate_bcdcf1594e1243016a82c47a812bc0fb2a741ce20f2b1a91225e03ca95530fff->doDisplay(Array, Array)
#21 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/f4/f4e1c9945eed1b532c8fb45ca5ebc4505b07837ec3298e3e19fe431708b687ae.php(255): Twig\Template->display(Array)
#23 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c048d9c168de22bc1d3ad4faadc1753193c8331cf67460b4d1fe6e822693e852->block_content(Array, Array)
#24 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/c5/c59a72810b8fe4c0fbc9c38e3958ae41e8a49ffbc8a52c42c3034a955bb08cee.php(412): Twig\Template->displayBlock('content', Array, Array)
#25 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c10beac0b1478e0c0354b82757646502fa980bd51b86c17b9c8386f7e6e9dcf3->block_main(Array, Array)
#26 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/c5/c59a72810b8fe4c0fbc9c38e3958ae41e8a49ffbc8a52c42c3034a955bb08cee.php(267): Twig\Template->displayBlock('main', Array, Array)
#27 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c10beac0b1478e0c0354b82757646502fa980bd51b86c17b9c8386f7e6e9dcf3->block_body(Array, Array)
#28 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/e5/e5261656622a4a615e01fb50d763571cfe4bd30c1ddcd00edaff7c7f5b61707d.php(79): Twig\Template->displayBlock('body', Array, Array)
#29 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(407): __TwigTemplate_5a2fa41a98c8993000100e09d5e7f3d0ad2b2af7d21d09ba8708ce92a6ba0c85->doDisplay(Array, Array)
#30 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#31 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/d3/d31e2ed0cedb8e525a2b52ef043a26610dd9a74f1fd774935a2fe1402e133933.php(57): Twig\Template->display(Array, Array)
#32 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(407): __TwigTemplate_d281f272298c4bc269f0e50c87f8135427c7e9e6107f1c3b1122be1185a5f9d3->doDisplay(Array, Array)
#33 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#34 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/c5/c59a72810b8fe4c0fbc9c38e3958ae41e8a49ffbc8a52c42c3034a955bb08cee.php(139): Twig\Template->display(Array, Array)
#35 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(407): __TwigTemplate_c10beac0b1478e0c0354b82757646502fa980bd51b86c17b9c8386f7e6e9dcf3->doDisplay(Array, Array)
#36 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#37 /Users/ransom/Projects/Work/craft-dev/storage/runtime/compiled_templates/f4/f4e1c9945eed1b532c8fb45ca5ebc4505b07837ec3298e3e19fe431708b687ae.php(111): Twig\Template->display(Array, Array)
#38 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(407): __TwigTemplate_c048d9c168de22bc1d3ad4faadc1753193c8331cf67460b4d1fe6e822693e852->doDisplay(Array, Array)
#39 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#40 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#41 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#42 /Users/ransom/Projects/Work/craft-dev/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#43 /Users/ransom/Projects/Work/craftcms/src/web/View.php(392): Twig\Environment->render('settings/fields...', Array)
#44 /Users/ransom/Projects/Work/craftcms/src/web/View.php(453): craft\web\View->renderTemplate('settings/fields...', Array)
#45 /Users/ransom/Projects/Work/craftcms/src/web/Controller.php(242): craft\web\View->renderPageTemplate('settings/fields...', Array, 'cp')
#46 /Users/ransom/Projects/Work/craftcms/src/controllers/FieldsController.php(255): craft\web\Controller->renderTemplate('settings/fields...', Array)
#47 [internal function]: craft\controllers\FieldsController->actionEditField(9, Object(benf\neo\Field), '5')
#48 /Users/ransom/Projects/Work/craft-dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#49 /Users/ransom/Projects/Work/craft-dev/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#50 /Users/ransom/Projects/Work/craftcms/src/web/Controller.php(179): yii\base\Controller->runAction('edit-field', Array)
#51 /Users/ransom/Projects/Work/craft-dev/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-field', Array)
#52 /Users/ransom/Projects/Work/craftcms/src/web/Application.php(289): yii\base\Module->runAction('fields/edit-fie...', Array)
#53 /Users/ransom/Projects/Work/craft-dev/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('fields/edit-fie...', Array)
#54 /Users/ransom/Projects/Work/craftcms/src/web/Application.php(274): yii\web\Application->handleRequest(Object(craft\web\Request))
#55 /Users/ransom/Projects/Work/craft-dev/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#56 /Users/ransom/Projects/Work/craft-dev/web/index.php(17): yii\base\Application->run()
#57 /Users/ransom/.composer/vendor/laravel/valet/server.php(191): require('/Users/ransom/P...')
#58 {main}
```

### Steps to reproduce

1. Attempt to edit a Neo field's settings

### Additional info

- Craft version: dev@10c476aedfecd32c9f8d7d426722f5ea5ec8f6b0
- PHP version: 7.4
- Database driver & version: MySQL 8
- Plugins & versions: Neo

**Comment by brandonkelly** [comment]
Fixed the exception so the page loads again, but looks like Neo is overriding the field layout designer JS, so they will have some work to do to fix compatibility.

**Comment by brandonkelly** [comment]
Posted an issue over there about it: https://github.com/spicywebau/craft-neo/issues/373
