### ISSUE TITLE
[3.5-dev] Migrating from project with project config disabled fails

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#6359]
### Description

The project I'm updating from has `useProjectConfigFile` set to `false` and as such, does not have a `project.yaml` file. Upon updating, the following error is produced:

```
yii\base\ErrorException: file_get_contents(/Users/ransom/Projects/Work/craft-dev/config/project.yaml): failed to open stream: No such file or directory

Migration: craft\migrations\m200629_112700_project_config_merge_and_split

Output:

> Creating the new project config component folder ... done
> Loading existing configuration ... Exception: file_get_contents(/Users/ransom/Projects/Work/craft-dev/config/project.yaml): failed to open stream: No such file or directory (/Users/ransom/Projects/Work/craftcms/src/migrations/m200629_112700_project_config_merge_and_split.php:49)
#0 /Users/ransom/Projects/Work/craftcms/src/web/ErrorHandler.php(75): craft\web\ErrorHandler->handleError()
#1 /Users/ransom/Projects/Work/craftcms/src/migrations/m200629_112700_project_config_merge_and_split.php(49): craft\web\ErrorHandler->handleError()
#2 /Users/ransom/Projects/Work/craftcms/src/migrations/m200629_112700_project_config_merge_and_split.php(49): ::file_get_contents()
#3 /Users/ransom/Projects/Work/craftcms/src/migrations/m200629_112700_project_config_merge_and_split.php(65): craft\migrations\m200629_112700_project_config_merge_and_split->craft\migrations\{closure:/Users/ransom/Projects/Work/craftcms/src/migrations/m200629_112700_project_config_merge_and_split.php:48-63}()
#4 /Users/ransom/Projects/Work/craftcms/src/db/Migration.php(52): craft\migrations\m200629_112700_project_config_merge_and_split->safeUp()
#5 /Users/ransom/Projects/Work/craftcms/src/db/MigrationManager.php(228): craft\migrations\m200629_112700_project_config_merge_and_split->up()
#6 /Users/ransom/Projects/Work/craftcms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp()
#7 /Users/ransom/Projects/Work/craftcms/src/services/Updates.php(220): craft\db\MigrationManager->up()
#8 /Users/ransom/Projects/Work/craftcms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations()
#9 /Users/ransom/Projects/Work/craftcms/src/controllers/UpdaterController.php(203): craft\controllers\UpdaterController->runMigrations()
#10 /Users/ransom/Projects/Work/craft-dev/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\UpdaterController->actionMigrate()
#11 /Users/ransom/Projects/Work/craft-dev/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/Users/ransom/Projects/Work/craft-dev/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#12 /Users/ransom/Projects/Work/craft-dev/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#13 /Users/ransom/Projects/Work/craftcms/src/web/Controller.php(179): craft\controllers\UpdaterController->runAction()
#14 /Users/ransom/Projects/Work/craft-dev/vendor/yiisoft/yii2/base/Module.php(528): craft\controllers\UpdaterController->runAction()
#15 /Users/ransom/Projects/Work/craftcms/src/web/Application.php(289): craft\web\Application->runAction()
#16 /Users/ransom/Projects/Work/craftcms/src/web/Application.php(645): craft\web\Application->runAction()
#17 /Users/ransom/Projects/Work/craftcms/src/web/Application.php(222): craft\web\Application->_processUpdateLogic()
#18 /Users/ransom/Projects/Work/craft-dev/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#19 /Users/ransom/Projects/Work/craft-dev/web/index.php(17): craft\web\Application->run()
#20 /Users/ransom/.composer/vendor/laravel/valet/server.php(191): ::unknown()
#21 {main}
```

I am able to resolve this issue by enabling project config and running the migration again. Note: in order to regenerate the project config while the migration is pending, I have to first revert all of the migrations and the Craft version update since my codebase is now ahead and doesn't know how to generate the old project.yaml format. 

### Additional info

Craft version: dev@10c476aedfecd32c9f8d7d426722f5ea5ec8f6b0
PHP version: 7.4
Database driver & version: MySQL 8
Plugins & versions: N/A

**Comment by andris-sevcenko** [comment]
Ah, thanks for reporting that! Fixed it on the 3.5 branch!
