### ISSUE TITLE
Syntax error or access violation: 1102 Incorrect database name (EC2)

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6364]
### Description

When trying to do anything in the control panel like saving entries or changing which columns are visible in the Entries section, I get the attached error log and an Internal Server Error.

This is environment specific. It doesn't happen locally, or on other Craft websites hosted on things like DigitalOcean. This is only happening on a site recently set up on Amazon EC2.

I am not manually referring to `#mysql50#.rocksdb` anywhere - the database name is something else. The settings in .env are correct, and the front end works - just can't change anything through the control panel.

### Additional info

```
2020-07-13 02:32:13 [-][17][-][error][yii\db\Exception] PDOException: SQLSTATE[42000]: Syntax error or access violation: 1102 Incorrect database name '#mysql50#.rocksdb' in /var/www/vendor/yiisoft/yii2/db/Command.php:1293
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute()
#1 /var/www/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute('SELECT\n    `kcu...')
#2 /var/www/vendor/yiisoft/yii2/db/Command.php(401): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /var/www/vendor/yiisoft/yii2/db/mysql/Schema.php(542): yii\db\Command->queryAll()
#4 /var/www/vendor/yiisoft/yii2/db/mysql/Schema.php(138): yii\db\mysql\Schema->loadTableConstraints('craft_elementin...', 'primaryKey')
#5 /var/www/vendor/yiisoft/yii2/db/Schema.php(754): yii\db\mysql\Schema->loadTablePrimaryKey('craft_elementin...')
#6 /var/www/vendor/yiisoft/yii2/db/ConstraintFinderTrait.php(101): yii\db\Schema->getTableMetadata('{{%elementindex...', 'primaryKey', false)
#7 /var/www/vendor/yiisoft/yii2/db/QueryBuilder.php(579): yii\db\mysql\Schema->getTablePrimaryKey('{{%elementindex...')
#8 /var/www/vendor/yiisoft/yii2/db/QueryBuilder.php(551): yii\db\QueryBuilder->getTableUniqueColumnNames('{{%elementindex...', Array, Array)
#9 /var/www/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(279): yii\db\QueryBuilder->prepareUpsertColumns('{{%elementindex...', Array, Array)
#10 /var/www/vendor/yiisoft/yii2/db/Command.php(548): yii\db\mysql\QueryBuilder->upsert('{{%elementindex...', Array, Array, Array)
#11 /var/www/vendor/craftcms/cms/src/db/Command.php(121): yii\db\Command->upsert('{{%elementindex...', Array, Array, Array)
#12 /var/www/vendor/craftcms/cms/src/services/ElementIndexes.php(126): craft\db\Command->upsert('{{%elementindex...', Array, Array)
#13 /var/www/vendor/craftcms/cms/src/controllers/ElementIndexSettingsController.php(119): craft\services\ElementIndexes->saveSettings('craft\\elements\\...', Array)
#14 [internal function]: craft\controllers\ElementIndexSettingsController->actionSaveCustomizeSourcesModalSettings()
#15 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /var/www/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-customize-...', Array)
#18 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-customize-...', Array)
#19 /var/www/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('element-index-s...', Array)
#20 /var/www/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('element-index-s...', Array)
#21 /var/www/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /var/www/html/index.php(21): yii\base\Application->run()
#24 {main}

Next yii\db\Exception: SQLSTATE[42000]: Syntax error or access violation: 1102 Incorrect database name '#mysql50#.rocksdb'
The SQL being executed was: SELECT
    `kcu`.`CONSTRAINT_NAME` AS `name`,
    `kcu`.`COLUMN_NAME` AS `column_name`,
    `tc`.`CONSTRAINT_TYPE` AS `type`,
    CASE
        WHEN NULL IS NULL AND `kcu`.`REFERENCED_TABLE_SCHEMA` = DATABASE() THEN NULL
        ELSE `kcu`.`REFERENCED_TABLE_SCHEMA`
    END AS `foreign_table_schema`,
    `kcu`.`REFERENCED_TABLE_NAME` AS `foreign_table_name`,
    `kcu`.`REFERENCED_COLUMN_NAME` AS `foreign_column_name`,
    `rc`.`UPDATE_RULE` AS `on_update`,
    `rc`.`DELETE_RULE` AS `on_delete`,
    `kcu`.`ORDINAL_POSITION` AS `position`
FROM
    `information_schema`.`KEY_COLUMN_USAGE` AS `kcu`,
    `information_schema`.`REFERENTIAL_CONSTRAINTS` AS `rc`,
    `information_schema`.`TABLE_CONSTRAINTS` AS `tc`
WHERE
    `kcu`.`TABLE_SCHEMA` = COALESCE(NULL, DATABASE()) AND `kcu`.`CONSTRAINT_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `kcu`.`TABLE_NAME` = 'craft_elementindexsettings'
    AND `rc`.`CONSTRAINT_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `rc`.`TABLE_NAME` = 'craft_elementindexsettings' AND `rc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME`
    AND `tc`.`TABLE_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `tc`.`TABLE_NAME` = 'craft_elementindexsettings' AND `tc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME` AND `tc`.`CONSTRAINT_TYPE` = 'FOREIGN KEY'
UNION
SELECT
    `kcu`.`CONSTRAINT_NAME` AS `name`,
    `kcu`.`COLUMN_NAME` AS `column_name`,
    `tc`.`CONSTRAINT_TYPE` AS `type`,
    NULL AS `foreign_table_schema`,
    NULL AS `foreign_table_name`,
    NULL AS `foreign_column_name`,
    NULL AS `on_update`,
    NULL AS `on_delete`,
    `kcu`.`ORDINAL_POSITION` AS `position`
FROM
    `information_schema`.`KEY_COLUMN_USAGE` AS `kcu`,
    `information_schema`.`TABLE_CONSTRAINTS` AS `tc`
WHERE
    `kcu`.`TABLE_SCHEMA` = COALESCE(NULL, DATABASE()) AND `kcu`.`TABLE_NAME` = 'craft_elementindexsettings'
    AND `tc`.`TABLE_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `tc`.`TABLE_NAME` = 'craft_elementindexsettings' AND `tc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME` AND `tc`.`CONSTRAINT_TYPE` IN ('PRIMARY KEY', 'UNIQUE')
ORDER BY `position` ASC in /var/www/vendor/yiisoft/yii2/db/Schema.php:674
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'SELECT\n    `kcu...')
#1 /var/www/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute('SELECT\n    `kcu...')
#2 /var/www/vendor/yiisoft/yii2/db/Command.php(401): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /var/www/vendor/yiisoft/yii2/db/mysql/Schema.php(542): yii\db\Command->queryAll()
#4 /var/www/vendor/yiisoft/yii2/db/mysql/Schema.php(138): yii\db\mysql\Schema->loadTableConstraints('craft_elementin...', 'primaryKey')
#5 /var/www/vendor/yiisoft/yii2/db/Schema.php(754): yii\db\mysql\Schema->loadTablePrimaryKey('craft_elementin...')
#6 /var/www/vendor/yiisoft/yii2/db/ConstraintFinderTrait.php(101): yii\db\Schema->getTableMetadata('{{%elementindex...', 'primaryKey', false)
#7 /var/www/vendor/yiisoft/yii2/db/QueryBuilder.php(579): yii\db\mysql\Schema->getTablePrimaryKey('{{%elementindex...')
#8 /var/www/vendor/yiisoft/yii2/db/QueryBuilder.php(551): yii\db\QueryBuilder->getTableUniqueColumnNames('{{%elementindex...', Array, Array)
#9 /var/www/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(279): yii\db\QueryBuilder->prepareUpsertColumns('{{%elementindex...', Array, Array)
#10 /var/www/vendor/yiisoft/yii2/db/Command.php(548): yii\db\mysql\QueryBuilder->upsert('{{%elementindex...', Array, Array, Array)
#11 /var/www/vendor/craftcms/cms/src/db/Command.php(121): yii\db\Command->upsert('{{%elementindex...', Array, Array, Array)
#12 /var/www/vendor/craftcms/cms/src/services/ElementIndexes.php(126): craft\db\Command->upsert('{{%elementindex...', Array, Array)
#13 /var/www/vendor/craftcms/cms/src/controllers/ElementIndexSettingsController.php(119): craft\services\ElementIndexes->saveSettings('craft\\elements\\...', Array)
#14 [internal function]: craft\controllers\ElementIndexSettingsController->actionSaveCustomizeSourcesModalSettings()
#15 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /var/www/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-customize-...', Array)
#18 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-customize-...', Array)
#19 /var/www/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('element-index-s...', Array)
#20 /var/www/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('element-index-s...', Array)
#21 /var/www/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /var/www/html/index.php(21): yii\base\Application->run()
#24 {main}
Additional Information:
Array
(
    [0] => 42000
    [1] => 1102
    [2] => Incorrect database name '#mysql50#.rocksdb'
)

2020-07-13 02:32:13 [-][17][-][info][application] $_GET = [
    'p' => 'admin/actions/element-index-settings/save-customize-sources-modal-settings'
]
```

- Craft version: 3.4.27
- PHP version: 7.2.30
- Database driver & version: MySQL (Amazon EC2)
- Plugins & versions:
Amazon S3    1.2.8
Control Panel Nav    3.0.12
Dashboard Begone    1.0.1
Linkit    1.1.11
Mix    1.5.2
Redactor    2.6.1
SEOmatic    3.3.10
Smart Map    3.3.3
Sprout Encode Email    2.0.7
Super Table    2.5.1

**Comment by darylknight** [comment]
The Discord community has pointed out that it may be this issue: https://github.com/craftcms/cms/issues/4159. Is the fix still to set `ignore-db-dir='.rocksdb'` ?

**Comment by angrybrad** [comment]
@darylknight yeah, still the fix, I'm afraid.
