### ISSUE TITLE
Unable to backup DB

### ISSUE THREAD

**Issue by johndwells** [craftcms/cms#6368]
I don't know if this is a duplicate of craftcms/nitro#139 but since the error I'm seeing is totally different, I'll just throw this one out as anew...

I'm unable to run a DB backup, fails both from the CLI and web. From the CLI the error reads:

```
Backing up the database ... error: The shell command "mysqldump --defaults-extra-file="/home/ubuntu/sites/tqm/turquoise-mountain-craft3/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --single-transaction --no-data --result-file="/home/ubuntu/sites/tqm/turquoise-mountain-craft3/storage/backups/turquoise-mountain_200610_211441_bflmrdergr_v3.4.22.1.sql" turquoisemountain && mysqldump --defaults-extra-file="/home/ubuntu/sites/tqm/turquoise-mountain-craft3/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-create-info --ignore-table=turquoisemountain.assetindexdata --ignore-table=turquoisemountain.assettransformindex --ignore-table=turquoisemountain.sessions --ignore-table=turquoisemountain.templatecaches --ignore-table=turquoisemountain.templatecachequeries --ignore-table=turquoisemountain.templatecacheelements --ignore-table=turquoisemountain.cache --ignore-table=turquoisemountain.templatecachecriteria turquoisemountain >> "/home/ubuntu/sites/tqm/turquoise-mountain-craft3/storage/backups/turquoise-mountain_200610_211441_bflmrdergr_v3.4.22.1.sql"" failed with exit code 2: mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'turquoisemountain' AND TABLE_NAME = 'assetindexdata';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
```

I'm leaving the project & db names intact, in case it's relevant - I am mounting my folder of all projects, and have databases created for each site I want to run...

I've never had reason to look into the `information_schema` table before, so I have no idea what I could be looking at, but I can confirm that there is no table named `COLUMN_STATISTICS`.

Let me know what other info I can provide. This is all running nitro 1.0.0-beta.10.

**Comment by angrybrad** [comment]
Was able to work around this in Craft itself and fix will be included in the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#eec596dcea3beaeedf4da10128aaee9b2b325d04",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.28 is out now with this fix.

**Comment by RyanRoberts** [comment]
I believe I'm getting the same problem as this with Craft 3.5.2 and Nitro beta 10. Here's the error log:

```
[-][1][5bfc5nf5mt7q99rhrt1mcrqob6][error][yii\base\Exception] yii\base\Exception: Could not create backup: The shell command "mysqldump --defaults-extra-file="/home/ubuntu/sites/client/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --single-transaction --no-data --result-file="/home/ubuntu/sites/client/storage/backups/client-rentals--2020-08-10-110337--v3.5.2.sql" client && mysqldump --defaults-extra-file="/home/ubuntu/sites/client/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --no-create-info --ignore-table=client.assetindexdata --ignore-table=client.assettransformindex --ignore-table=client.sessions --ignore-table=client.templatecaches --ignore-table=client.templatecachequeries --ignore-table=client.templatecacheelements --ignore-table=client.cache --ignore-table=client.templatecachecriteria client >> "/home/ubuntu/sites/client/storage/backups/client-rentals--2020-08-10-110337--v3.5.2.sql"" failed with exit code 127: sh: 1: mysqldump: not found in /home/ubuntu/sites/client/vendor/craftcms/cms/src/controllers/UtilitiesController.php:377
Stack trace:
#0 [internal function]: craft\controllers\UtilitiesController->actionDbBackupPerformAction()
#1 /home/ubuntu/sites/client/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#2 /home/ubuntu/sites/client/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#3 /home/ubuntu/sites/client/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction()
#4 /home/ubuntu/sites/client/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#5 /home/ubuntu/sites/client/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction()
#6 /home/ubuntu/sites/client/vendor/craftcms/cms/src/web/Application.php(597): craft\web\Application->runAction()
#7 /home/ubuntu/sites/client/vendor/craftcms/cms/src/web/Application.php(273): craft\web\Application->_processActionRequest()
#8 /home/ubuntu/sites/client/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#9 /home/ubuntu/sites/client/public/index.php(22): yii\base\Application->run()
#10 {main}
```

Can't backup from the Craft Admin or CLI, but as above `nitro db backup` works.

**Comment by angrybrad** [comment]
@RyanRoberts Can you create this as a new issue on the [Nitro repo](https://github.com/craftcms/nitro/issues)?
