### ISSUE TITLE
[3.5] type error when applying project config updates

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#6393]
### Description

I’m getting a type error when applying project config updates. Craft also didn’t notify me that there were project config updates (might be another issue), and I triggered the synchronization from the utility in the control panel.

```
TypeError: Argument 1 passed to craft\web\View::renderObjectTemplate() must be of the type string, null given, called in /app/vendor/craftcms/cms/src/helpers/ElementHelper.php on line 545
```

<details>
<summary>Stack trace</summary>

```
TypeError: Argument 1 passed to craft\web\View::renderObjectTemplate() must be of the type string, null given, called in /app/vendor/craftcms/cms/src/helpers/ElementHelper.php on line 545 and defined in /app/vendor/craftcms/cms/src/web/View.php:578
Stack trace:
#0 /app/vendor/craftcms/cms/src/helpers/ElementHelper.php(545): craft\web\View->renderObjectTemplate(NULL, Object(craft\elements\Entry))
#1 /app/vendor/craftcms/cms/src/elements/Entry.php(943): craft\helpers\ElementHelper::translationKey(Object(craft\elements\Entry), '', NULL)
#2 /app/vendor/craftcms/cms/src/services/Elements.php(2519): craft\elements\Entry->getTitleTranslationKey()
#3 /app/vendor/craftcms/cms/src/services/Elements.php(2352): craft\services\Elements->_propagateElement(Object(craft\elements\Entry), Array, Object(craft\elements\Entry))
#4 /app/vendor/craftcms/cms/src/services/Elements.php(690): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), false, true, true)
#5 /app/vendor/craftcms/cms/src/services/Sections.php(1589): craft\services\Elements->saveElement(Object(craft\elements\Entry), false)
#6 /app/vendor/craftcms/cms/src/services/Sections.php(780): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section), Array)
#7 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1057): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#8 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#9 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#10 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(649): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#11 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1047): craft\services\ProjectConfig->processConfigChanges('sections.7c025b...')
#12 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#13 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#14 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(643): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#15 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1145): craft\services\ProjectConfig->processConfigChanges('sections.7c025b...', false, NULL, true)
#16 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(507): craft\services\ProjectConfig->_applyChanges(Array)
#17 /app/vendor/craftcms/cms/src/controllers/UtilitiesController.php(167): craft\services\ProjectConfig->applyYamlChanges()
#18 [internal function]: craft\controllers\UtilitiesController->actionProjectConfigPerformAction()
#19 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /app/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#21 /app/vendor/craftcms/cms/src/web/Controller.php(199): yii\base\Controller->runAction('project-config-...', Array)
#22 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('project-config-...', Array)
#23 /app/vendor/craftcms/cms/src/web/Application.php(289): yii\base\Module->runAction('utilities/proje...', Array)
#24 /app/vendor/craftcms/cms/src/web/Application.php(558): craft\web\Application->runAction('utilities/proje...', Array)
#25 /app/vendor/craftcms/cms/src/web/Application.php(268): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#26 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#27 /app/web/index.php(21): yii\base\Application->run()
#28 {main}
```
</details>

### Additional info

- Craft version: 3.5.x-dev (533f8c7)
- PHP version: 7.3.7
- Database driver & version: PostgreSQL 11.6

**Comment by brandonkelly** [comment]
In your DB, look up the section with a UID that starts with `7c025b` (`sections` table), and then look up its entry types (`entrytypes` table). What are their `titleTranslationMethod` values?

> Craft also didn’t notify me that there were project config updates (might be another issue)

As of the next 3.5 release, Craft no longer checks for pending project config changes on each request, unless dev mode is enabled. If you want to keep your project config changes applied to your production environment automatically, you must call `./craft project-config/apply` as part of your deploy process.

**Comment by carlcs** [comment]
`titleTranslationMethod` value is empty for that single section’s entry type. For all other entry types it’s set to `site`. I can’t really tell you how this has happened, I didn’t get any errors when I applied migrations for Craft 3.5.

I went ahead and changed the value to `site`, and then my project config sync ran without errors.

**Comment by brandonkelly** [comment]
Huh, weird. Well, there’s now a guard in place so this won’t happen again.
