### ISSUE TITLE
[3.5] resave elements job fails when rendering URI formats

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#6399]
### Description

I’ve got a resave elements job that fails with the following error message.

```
An exception has been thrown during the compilation of a template
("session_set_cookie_params(): Cannot change session cookie parameters when headers already sent")
in "__string_template__373f519c28f2eef1bf9239048b32a2996b5865e612585eb82ac0b2931f8f1100"
```

<details>
<summary>Stack trace</summary>

```
2020-07-16 16:00:25 [-][2][-][error][craft\queue\QueueLogBehavior::afterError]  [1101] Resaving Services - Services entries (attempt: 1) - Error (time: 0.077s): An exception has been thrown during the compilation of a template ("session_set_cookie_params(): Cannot change session cookie parameters when headers already sent") in "__string_template__373f519c28f2eef1bf9239048b32a2996b5865e612585eb82ac0b2931f8f1100".
2020-07-16 16:00:25 [-][2][-][error][Twig\Error\SyntaxError] yii\base\ErrorException: session_set_cookie_params(): Cannot change session cookie parameters when headers already sent in /app/vendor/yiisoft/yii2/web/Session.php:399
Stack trace:
#0 /app/vendor/craftcms/cms/src/web/ErrorHandler.php(75): yii\base\ErrorHandler->handleError(2, 'session_set_coo...', '/app/vendor/yii...', 399)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'session_set_coo...', '/app/vendor/yii...', 399, Array)
#2 /app/vendor/yiisoft/yii2/web/Session.php(399): session_set_cookie_params(Array)
#3 /app/vendor/yiisoft/yii2/web/Session.php(135): yii\web\Session->setCookieParamsInternal()
#4 /app/vendor/yiisoft/yii2/web/Session.php(630): yii\web\Session->open()
#5 /app/vendor/craftcms/cms/src/config/app.php(218): yii\web\Session->get('1031b8c41dfff97...')
#6 [internal function]: {closure}()
#7 /app/vendor/yiisoft/yii2/di/Container.php(526): call_user_func_array(Object(Closure), Array)
#8 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->invoke(Object(Closure), Array)
#9 /app/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#10 /app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('locale', true)
#11 /app/vendor/craftcms/cms/src/web/Application.php(339): yii\base\Module->get('locale', true)
#12 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1084): craft\web\Application->get('locale')
#13 /app/vendor/craftcms/cms/src/config/app.php(211): craft\web\Application->getLocale()
#14 [internal function]: {closure}()
#15 /app/vendor/yiisoft/yii2/di/Container.php(526): call_user_func_array(Object(Closure), Array)
#16 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->invoke(Object(Closure), Array)
#17 /app/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#18 /app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('formatter', true)
#19 /app/vendor/craftcms/cms/src/web/Application.php(339): yii\base\Module->get('formatter', true)
#20 /app/vendor/yiisoft/yii2/base/Application.php(535): craft\web\Application->get('formatter')
#21 /app/vendor/craftcms/cms/src/web/twig/Extension.php(208): yii\base\Application->getFormatter()
#22 /app/vendor/twig/twig/src/ExtensionSet.php(433): craft\web\twig\Extension->getFilters()
#23 /app/vendor/twig/twig/src/ExtensionSet.php(423): Twig\ExtensionSet->initExtension(Object(craft\web\twig\Extension))
#24 /app/vendor/twig/twig/src/ExtensionSet.php(397): Twig\ExtensionSet->initExtensions()
#25 /app/vendor/twig/twig/src/Environment.php(966): Twig\ExtensionSet->getUnaryOperators()
#26 /app/vendor/twig/twig/src/Lexer.php(459): Twig\Environment->getUnaryOperators()
#27 /app/vendor/twig/twig/src/Lexer.php(110): Twig\Lexer->getOperatorRegex()
#28 /app/vendor/twig/twig/src/Environment.php(539): Twig\Lexer->__construct(Object(craft\web\twig\Environment))
#29 /app/vendor/twig/twig/src/Environment.php(595): Twig\Environment->tokenize(Object(Twig\Source))
#30 /app/vendor/craftcms/cms/src/web/twig/Environment.php(60): Twig\Environment->compileSource(Object(Twig\Source))
#31 /app/vendor/twig/twig/src/Environment.php(408): craft\web\twig\Environment->compileSource(Object(Twig\Source))
#32 /app/vendor/twig/twig/src/Environment.php(381): Twig\Environment->loadClass('__TwigTemplate_...', '__string_templa...', NULL)
#33 /app/vendor/craftcms/cms/src/web/twig/Environment.php(41): Twig\Environment->loadTemplate('__string_templa...', NULL)
#34 /app/vendor/twig/twig/src/Environment.php(462): craft\web\twig\Environment->loadTemplate('__string_templa...')
#35 /app/vendor/craftcms/cms/src/web/View.php(607): Twig\Environment->createTemplate('services/{{ (_v...')
#36 /app/vendor/craftcms/cms/src/helpers/ElementHelper.php(228): craft\web\View->renderObjectTemplate('services/{{ (_v...', Object(craft\elements\Entry), Array)
#37 /app/vendor/craftcms/cms/src/helpers/ElementHelper.php(141): craft\helpers\ElementHelper::_renderUriFormat('services/{slug}', Object(craft\elements\Entry))
#38 /app/vendor/craftcms/cms/src/validators/ElementUriValidator.php(55): craft\helpers\ElementHelper::setUniqueUri(Object(craft\elements\Entry))
#39 /app/vendor/yiisoft/yii2/validators/Validator.php(261): craft\validators\ElementUriValidator->validateAttribute(Object(craft\elements\Entry), 'uri')
#40 /app/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#41 /app/vendor/craftcms/cms/src/services/Elements.php(2205): yii\base\Model->validate()
#42 /app/vendor/craftcms/cms/src/services/Elements.php(754): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, false)
#43 /app/vendor/craftcms/cms/src/queue/jobs/ResaveElements.php(65): craft\services\Elements->resaveElements(Object(craft\elements\db\EntryQuery), false, true, false)
#44 /app/vendor/yiisoft/yii2-queue/src/Queue.php(246): craft\queue\jobs\ResaveElements->execute(Object(craft\queue\Queue))
#45 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage(1101, 'O:31:"craft\\que...', 300, 1)
#46 /app/vendor/craftcms/cms/src/queue/Queue.php(121): yii\queue\cli\Queue->handleMessage(1101, 'O:31:"craft\\que...', 300, 1)
#47 /app/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#48 /app/vendor/craftcms/cms/src/controllers/QueueController.php(105): craft\controllers\QueueController->actionRun()
#49 [internal function]: craft\controllers\QueueController->actionRetry()
#50 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#51 /app/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#52 /app/vendor/craftcms/cms/src/web/Controller.php(199): yii\base\Controller->runAction('retry', Array)
#53 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('retry', Array)
#54 /app/vendor/craftcms/cms/src/web/Application.php(289): yii\base\Module->runAction('queue/retry', Array)
#55 /app/vendor/craftcms/cms/src/web/Application.php(558): craft\web\Application->runAction('queue/retry', Array)
#56 /app/vendor/craftcms/cms/src/web/Application.php(268): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#57 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#58 /app/web/index.php(21): yii\base\Application->run()
#59 {main}

```
</details>

### Additional info

- Craft version: 3.5.x-dev (533f8c7)
- PHP version: 7.3.7
- Database driver & version: PostgreSQL 11.6

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now.
