### ISSUE TITLE
Cannot create a table with a Table Column with dropdown field type

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#6413]
### Description
As per the description, I get an 'a server error occurred' when trying to create a table with a Table Column with a dropdown field type. If I remove the dropdown or change to a single lie then the field aves ok.

### Steps to reproduce

1. create a new field with type as table
2. create a new table column with type as dropdown
3. Save
4.  'a server error occurred'

### Additional info

- Craft version: Craft Pro 3.4.28.1
- PHP version: 7.2.31
- Database driver & version: 	MySQL 5.5.5 (MariaDB 10.4)

**Comment by terryupton** [comment]
Not sure if these logs help?
```
FROM `information_schema`.`REFERENTIAL_CONSTRAINTS` AS `rc`
JOIN `information_schema`.`KEY_COLUMN_USAGE` AS `kcu` ON
    (
        `kcu`.`CONSTRAINT_CATALOG` = `rc`.`CONSTRAINT_CATALOG` OR
        (`kcu`.`CONSTRAINT_CATALOG` IS NULL AND `rc`.`CONSTRAINT_CATALOG` IS NULL)
    ) AND
    `kcu`.`CONSTRAINT_SCHEMA` = `rc`.`CONSTRAINT_SCHEMA` AND
    `kcu`.`CONSTRAINT_NAME` = `rc`.`CONSTRAINT_NAME`
WHERE `rc`.`CONSTRAINT_SCHEMA` = database() AND `kcu`.`TABLE_SCHEMA` = database()
AND `rc`.`TABLE_NAME` = 'craft_content' AND `kcu`.`TABLE_NAME` = 'craft_content'
2020-07-20 23:45:22 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `craft_content` CHANGE `field_training` `field_training` text
2020-07-20 23:45:22 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `craft_content` CHANGE `field_training` `field_training` text
2020-07-20 23:45:22 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `craft_content` CHANGE `field_training` `field_training` text
2020-07-20 23:45:22 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2020-07-20 23:45:22 [-][1][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined offset: 1 in /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/helpers/ProjectConfig.php:282
Stack trace:
#0 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/Users/terryupt...', 282)
#1 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/helpers/ProjectConfig.php(282): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/Users/terryupt...', 282, Array)
#2 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/helpers/ProjectConfig.php(291): craft\helpers\ProjectConfig::unpackAssociativeArray(Array, true)
#3 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/helpers/ProjectConfig.php(261): craft\helpers\ProjectConfig::unpackAssociativeArray(Array)
#4 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/services/Fields.php(1519): craft\helpers\ProjectConfig::unpackAssociativeArrays(Array)
#5 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/services/Fields.php(826): craft\services\Fields->applyFieldSave('97aaaff7-5865-4...', Array, 'global')
#6 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/services/ProjectConfig.php(1103): craft\services\Fields->handleChangedField(Object(craft\events\ConfigEvent))
#7 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#8 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#9 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/services/ProjectConfig.php(679): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#10 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/services/ProjectConfig.php(489): craft\services\ProjectConfig->processConfigChanges('fields.97aaaff7...', true, 'Save field \xE2\x80\x9Ct...')
#11 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/services/Fields.php(771): craft\services\ProjectConfig->set('fields.97aaaff7...', Array, 'Save field \xE2\x80\x9Ct...')
#12 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/verbb/field-manager/src/controllers/BaseController.php(262): craft\services\Fields->saveField(Object(craft\fields\Table))
#13 [internal function]: verbb\fieldmanager\controllers\BaseController->actionSaveField()
#14 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-field', Array)
#17 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-field', Array)
#18 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('field-manager/b...', Array)
#19 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('field-manager/b...', Array)
#20 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#21 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /Users/terryupton/Dropbox/Amasci/Websites/Roman Rangers FC/romanrangersfc.co.uk/web/index.php(21): yii\base\Application->run()
#23 /Users/terryupton/.composer/vendor/laravel/valet/server.php(158): require('/Users/terryupt...')
#24 {main}
```

**Comment by brandonkelly** [comment]
Looks like there’s something wrong with your project config. Please enable your `useProjectConfigFile` config setting (if not already), reload the control panel, and then send your `config/project.yaml` file into `support@craftcms.com` and we can try to help from there.
