### ISSUE TITLE
Editing existing matrix fields broken on 3.5-dev

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#6417]
### Description
I am getting the following error on 3.5-dev when editing a matrix field created on 3.5-beta3

```
yii\base\ErrorException: Undefined offset: 0 in /var/www/html/craft/vendor/craftcms/cms/src/fields/Matrix.php:423
Stack trace:
#0 /var/www/html/craft/vendor/craftcms/cms/src/web/ErrorHandler.php(75): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/html/c...', 423)
#1 /var/www/html/craft/vendor/craftcms/cms/src/fields/Matrix.php(423): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/html/c...', 423, Array)
#2 /var/www/html/craft/vendor/twig/twig/src/Extension/CoreExtension.php(1499): craft\fields\Matrix->getSettingsHtml()
#3 /var/www/html/craft/vendor/craftcms/cms/src/helpers/Template.php(90): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\fields\Matrix), 'getSettingsHtml', Array, 'method', false, false)
#4 /var/www/html/craft/storage/runtime/compiled_templates/84/8462a7ebd910c45d2fd2222d380b0d32648d8ee2ca29c3cb5487c9896adda8ca.php(46): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\fields\Matrix), 'getSettingsHtml', Array, 'method')
#5 /var/www/html/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_4954354ca58742ac03f78a0e8d8227eec598f03d3ac317d3399a1b9de63ba5d5->doDisplay(Array, Array)
#6 /var/www/html/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /var/www/html/craft/storage/runtime/compiled_templates/86/8615f55eb6d715241067397284e5f10e152b92bb09443a8d3d3b6bd384274e16.php(255): Twig\Template->display(Array)
#8 /var/www/html/craft/vendor/twig/twig/src/Template.php(184): __TwigTemplate_6ed2aa833bd037adb8b124bd71495a703deb9ad9cdce61a7ffc779c4461d2f04->block_content(Array, Array)
#9 /var/www/html/craft/storage/runtime/compiled_templates/37/37f042004594698bd15ba56a2dc5f446d7590559d61c90f8a3cf3fea70dc35cb.php(412): Twig\Template->displayBlock('content', Array, Array)
#10 /var/www/html/craft/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c2cae770da43875c1fd8aa1debc44ddd4ece9c522a6abeb43043e8add0204eea->block_main(Array, Array)
#11 /var/www/html/craft/storage/runtime/compiled_templates/37/37f042004594698bd15ba56a2dc5f446d7590559d61c90f8a3cf3fea70dc35cb.php(267): Twig\Template->displayBlock('main', Array, Array)
#12 /var/www/html/craft/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c2cae770da43875c1fd8aa1debc44ddd4ece9c522a6abeb43043e8add0204eea->block_body(Array, Array)
#13 /var/www/html/craft/storage/runtime/compiled_templates/ee/ee3996b52bd0025981bf258b3d7e183c4139a2e0551bcd711714dfa82622fad4.php(85): Twig\Template->displayBlock('body', Array, Array)
#14 /var/www/html/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_7b6e7be9df5f36a092d5b9be249923fb91fe2ba46f431bf059d19b91a29dc807->doDisplay(Array, Array)
#15 /var/www/html/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /var/www/html/craft/storage/runtime/compiled_templates/0b/0b130570f8b26466099d9c4a3ffe3249e957b01c950de093ecd384a386a46f0a.php(57): Twig\Template->display(Array, Array)
#17 /var/www/html/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_7df21191e0a3b353d4ba930d8d1f4da744f63444fda12814ba7b46cdce12386e->doDisplay(Array, Array)
#18 /var/www/html/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /var/www/html/craft/storage/runtime/compiled_templates/37/37f042004594698bd15ba56a2dc5f446d7590559d61c90f8a3cf3fea70dc35cb.php(139): Twig\Template->display(Array, Array)
#20 /var/www/html/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_c2cae770da43875c1fd8aa1debc44ddd4ece9c522a6abeb43043e8add0204eea->doDisplay(Array, Array)
#21 /var/www/html/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /var/www/html/craft/storage/runtime/compiled_templates/86/8615f55eb6d715241067397284e5f10e152b92bb09443a8d3d3b6bd384274e16.php(111): Twig\Template->display(Array, Array)
#23 /var/www/html/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_6ed2aa833bd037adb8b124bd71495a703deb9ad9cdce61a7ffc779c4461d2f04->doDisplay(Array, Array)
#24 /var/www/html/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /var/www/html/craft/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#26 /var/www/html/craft/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#27 /var/www/html/craft/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#28 /var/www/html/craft/vendor/craftcms/cms/src/web/View.php(391): Twig\Environment->render('settings/fields...', Array)
#29 /var/www/html/craft/vendor/craftcms/cms/src/web/View.php(452): craft\web\View->renderTemplate('settings/fields...', Array)
#30 /var/www/html/craft/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('settings/fields...', Array, 'cp')
#31 /var/www/html/craft/vendor/craftcms/cms/src/controllers/FieldsController.php(253): craft\web\Controller->renderTemplate('settings/fields...', Array)
#32 [internal function]: craft\controllers\FieldsController->actionEditField(1, Object(craft\fields\Matrix), '1')
#33 /var/www/html/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#34 /var/www/html/craft/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#35 /var/www/html/craft/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('edit-field', Array)
#36 /var/www/html/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-field', Array)
#37 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction('fields/edit-fie...', Array)
#38 /var/www/html/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('fields/edit-fie...', Array)
#39 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(280): yii\web\Application->handleRequest(Object(craft\web\Request))
#40 /var/www/html/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#41 /var/www/html/craft/web/index.php(23): yii\base\Application->run()
#42 {main}
```

### Steps to reproduce
1. Have an existing 3.5-beta3 site with a matrix block created
2. Attempt to edit it with any dev release after commit 5ad5cfc

### Additional info
Seems to be caused by this commit:
https://github.com/craftcms/cms/commit/5ad5cfc32fc1060af241bebe0325d129456f4e3e

**Comment by FreekVR** [comment]
I should note that wrapping the entire foreach-loop that uses `$tab` like this seems to work fine for me, though I'm not sure what functionality is now not being executed for this particular matrix field:

```
            $tabs = $blockType->getFieldLayout()->getTabs();
            if (!empty($tabs)) {
                foreach ($tabs[0]->elements as $element) {
                     ....
```

**Comment by FreekVR** [comment]
I was able to track down the issue to one of our matrix blocks which (on purpose) does not have any fields (and probably not any tabs). 

In our case in the frontend this is used to pull some data from elsewhere and display it visually, hence there are no fields in Craft.

At any rate, having a block type like this without fields seems to break things now.

An additional way to reproduce this for *new* Matrix blocks:

- Create a new field of type Matrix
- Add a block
- Press "delete" for the default field added to it
- Attempt to save
- You will get the following error:
`Argument 1 passed to craft\models\FieldLayout::createFromConfig() must be of the type array, null given, called in /var/www/html/craft/vendor/craftcms/cms/src/services/Matrix.php on line 353`

As mentioned, for existing Matrix fields you will get the error when opening the error screen as mentioned in the OP.

**Comment by brandonkelly** [comment]
Thanks for reporting & investigating! Just fixed this.
