### ISSUE TITLE
[3.5] Undefined index: project-config/rebuild

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6420]
Got this when trying to run `craft project-config/rebuild`.

Also tried running `craft utils/repair/project-config` first, but got the same error.

```
2020-07-21 14:20:05 [-][-][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index:  in /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php:2119
Stack trace:
#0 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(2119): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/app/vendor/com...', 2119, Array)
#1 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(1741): craft\services\ProjectConfig->_getMatrixBlockTypeData()
#2 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(1127): craft\services\ProjectConfig->_getCurrentStateData()
#3 /app/vendor/composer/craftcms/cms/src/console/controllers/ProjectConfigController.php(140): craft\services\ProjectConfig->rebuild()
#4 [internal function]: craft\console\controllers\ProjectConfigController->actionRebuild()
#5 /app/vendor/composer/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /app/vendor/composer/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#7 /app/vendor/composer/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('rebuild', Array)
#8 /app/vendor/composer/craftcms/cms/src/console/Controller.php(188): yii\console\Controller->runAction('rebuild', Array)
#9 /app/vendor/composer/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('rebuild', Array)
#10 /app/vendor/composer/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#11 /app/vendor/composer/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('project-config/...', Array)
#12 /app/vendor/composer/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#13 /app/vendor/composer/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#14 /app/bin/craft(7): yii\base\Application->run()
#15 {main}
```

### Additional info

- Craft version: 3.5.x-dev / 28f0beb51191eea424feb4b655ff4861f0a521c9

**Comment by brandonkelly** [comment]
To clarify, that line only gets executed when running `project-config/rebuild`, and from your stack trace it looks like that is in fact what you were running.

**Comment by brandonkelly** [comment]
All fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5 RC1.1 is out now with the fix.
