### ISSUE TITLE
[3.5.0-dev] Unable to delete a section

### ISSUE THREAD

**Issue by jerome2710** [craftcms/cms#6519]
### Description
I am unable to delete a section containing 3 entry-types, as the XHR call seem to fail when fetching the just deleted section.

```
Stack trace:
#0 /~~/vendor/craftcms/cms/src/services/Sections.php(1210): craft\services\Sections->getSectionByUid(NULL)
#1 /~~/vendor/craftcms/cms/src/services/ProjectConfig.php(1090): craft\services\Sections->handleChangedEntryType(Object(craft\events\ConfigEvent))
#2 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#3 /~~/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#4 /~~/vendor/craftcms/cms/src/services/ProjectConfig.php(668): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#5 /~~/vendor/craftcms/cms/src/services/ProjectConfig.php(476): craft\services\ProjectConfig->processConfigChanges('entryTypes.892a...', true, 'Delete the \xE2\x80\x9Cw...')
#6 /~~/vendor/craftcms/cms/src/services/ProjectConfig.php(492): craft\services\ProjectConfig->set('entryTypes.892a...', NULL, 'Delete the \xE2\x80\x9Cw...')
#7 /~~/vendor/craftcms/cms/src/services/Sections.php(1394): craft\services\ProjectConfig->remove('entryTypes.892a...', 'Delete the \xE2\x80\x9Cw...')
#8 /~~/vendor/craftcms/cms/src/services/Sections.php(844): craft\services\Sections->deleteEntryType(Object(craft\models\EntryType))
#9 /~~/vendor/craftcms/cms/src/services/Sections.php(816): craft\services\Sections->deleteSection(Object(craft\models\Section))
#10 /~~/vendor/craftcms/cms/src/controllers/SectionsController.php(205): craft\services\Sections->deleteSectionById(22)
#11 [internal function]: craft\controllers\SectionsController->actionDeleteSection()
#12 /~~/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /~~/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#14 /~~/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('delete-section', Array)
#15 /~~/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('delete-section', Array)
#16 /~~/vendor/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction('sections/delete...', Array)
#17 /~~/vendor/craftcms/cms/src/web/Application.php(598): craft\web\Application->runAction('sections/delete...', Array)
#18 /~~/vendor/craftcms/cms/src/web/Application.php(274): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#19 /~~/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /~~/web/index.php(40): yii\base\Application->run()
#21 {main}
2020-08-03 13:15:19 [-][1][-][info][application] $_GET = [
    'p' => 'cp/actions/sections/delete-section'
]
```

### Additional info

- Craft version: 3.5.x-dev (7b0f02d)
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.65

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send your Composer files and a database backup into support@craftcms.com?

**Comment by jerome2710** [comment]
Oli from P&T investigated my database and found out that the field layout of one of the entry types was missing. Re-saving this entry type solved the issue and I was now able to delete the section.

We are both not sure how this happened, but the solution might be helpful for others as well. Thanks @brandonkelly and @olivierbon!
