### ISSUE TITLE
Array to string conversion error after upgrading, PHP 7.4.3

### ISSUE THREAD

**Issue by circa1977** [craftcms/cms#6617]
### Description

I've deployed an upgraded site to Arcustech on a new server (PHP 7.4.3) and am receiving the following error when attempting to edit an entry. I don't see this on all entries. It's likely limited to entries that use Matrix or Super Table field types. Super Table has been upgraded as well.

I'm not receiving this error in my local (MAMP Pro) running PHP 7.3.9 with the same upgrades in place. Curiously I don't see it in my local when I switch to 7.4.2 as my PHP version, either.

```
2020-08-12 10:10:20 [-][1][hc2f51thd2mtv7rnttl4oh6nhr][error][yii\base\ErrorException:8] yii\base\ErrorException: Array to string conversion in /storage/av#####/www/public_html/vendor/yiisoft/yii2/helpers/BaseHtml.php:1972
Stack trace:
#0 /storage/av#####/www/public_html/vendor/craftcms/cms/src/web/ErrorHandler.php(75): yii\base\ErrorHandler->handleError()
#1 [internal function]: craft\web\ErrorHandler->handleError()
#2 /storage/av#####/www/public_html/vendor/yiisoft/yii2/helpers/BaseHtml.php(1972): implode()
#3 /storage/av#####/www/public_html/vendor/yiisoft/yii2/helpers/BaseHtml.php(150): yii\helpers\BaseHtml::renderTagAttributes()
#4 /storage/av#####/www/public_html/vendor/craftcms/cms/src/web/twig/Extension.php(1199): yii\helpers\BaseHtml::tag()
#5 /storage/av#####/www/public_html/storage/runtime/compiled_templates/fd/fd69122b0ad0673c1c53522839a9aa944d354aa72762eb0dfd3692634d1bcc05.php(90): craft\web\twig\Extension->tagFunction()
#6 /storage/av#####/www/public_html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_9118d407d1097383e7ca371f640619072bbdd83e16793e383c4b8cd99f3c09a2->doDisplay()
#7 /storage/av#####/www/public_html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#8 /storage/av#####/www/public_html/storage/runtime/compiled_templates/ca/ca5fc6411c0fe84fa82a14bb540295ba49315fcbf55d3d9e58999c4748234afe.php(279): Twig\Template->display()
#9 /storage/av#####/www/public_html/vendor/twig/twig/src/Extension/CoreExtension.php(1109): __TwigTemplate_3ee05e6a0df8c48882773f624f5509dc81b0942c7636fd1890dc7bc2a50f5d64->macro_text()
#10 /storage/av#####/www/public_html/storage/runtime/compiled_templates/54/54d55accdae2fccb3cb26b4a942697d174ce007b9362609d9b8c07d406d6f17e.php(68): twig_call_macro()
#11 /storage/av#####/www/public_html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_44f352235c698993819556109b91a1b471d8820b2a1ca78b5136e96ebf5dd265->doDisplay()
#12 /storage/av#####/www/public_html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#13 /storage/av#####/www/public_html/vendor/twig/twig/src/Template.php(392): Twig\Template->display()
#14 /storage/av#####/www/public_html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#15 /storage/av#####/www/public_html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#16 /storage/av#####/www/public_html/vendor/craftcms/cms/src/web/View.php(391): Twig\Environment->render()
#17 /storage/av#####/www/public_html/vendor/craftcms/cms/src/fields/PlainText.php(198): craft\web\View->renderTemplate()
#18 /storage/av#####/www/public_html/vendor/craftcms/cms/src/base/Field.php(351): craft\fields\PlainText->inputHtml()
#19 /storage/av#####/www/public_html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(232): craft\base\Field->getInputHtml()
#20 /storage/av#####/www/public_html/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(188): craft\fieldlayoutelements\CustomField->inputHtml()
#21 /storage/av#####/www/public_html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(208): craft\fieldlayoutelements\BaseField->formHtml()
#22 /storage/av#####/www/public_html/vendor/craftcms/cms/src/models/FieldLayout.php(461): craft\fieldlayoutelements\CustomField->formHtml()
#23 /storage/av#####/www/public_html/vendor/craftcms/cms/src/fields/Matrix.php(1122): craft\models\FieldLayout->createForm()
#24 /storage/av#####/www/public_html/vendor/craftcms/cms/src/fields/Matrix.php(660): craft\fields\Matrix->_getBlockTypeInfoForInput()
#25 /storage/av#####/www/public_html/vendor/craftcms/cms/src/base/Field.php(351): craft\fields\Matrix->inputHtml()
#26 /storage/av#####/www/public_html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(232): craft\base\Field->getInputHtml()
#27 /storage/av#####/www/public_html/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(188): craft\fieldlayoutelements\CustomField->inputHtml()
#28 /storage/av#####/www/public_html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(208): craft\fieldlayoutelements\BaseField->formHtml()
#29 /storage/av#####/www/public_html/vendor/craftcms/cms/src/models/FieldLayout.php(461): craft\fieldlayoutelements\CustomField->formHtml()
#30 /storage/av#####/www/public_html/vendor/twig/twig/src/Extension/CoreExtension.php(1499): craft\models\FieldLayout->createForm()
#31 /storage/av#####/www/public_html/vendor/craftcms/cms/src/helpers/Template.php(90): twig_get_attribute()
#32 /storage/av#####/www/public_html/storage/runtime/compiled_templates/8e/8e0636c3e5b22f3965128375b06bc15862a452d531f30904bba744ac3bb93a9b.php(135): craft\helpers\Template::attribute()
#33 /storage/av#####/www/public_html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_f6f9b223fec6fbc848cc64d7735a067527b1c8470e4464c784dc4c64bbb25edc->doDisplay()
#34 /storage/av#####/www/public_html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#35 /storage/av#####/www/public_html/storage/runtime/compiled_templates/af/af2a980f851ca7c9f9e40e04c9f45ab2a93608bd86ee24df2f7b2497866c2237.php(120): Twig\Template->display()
#36 /storage/av#####/www/public_html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_08972ca5f9760f68c2067352e5c7cdc9abe987c09b6aa64070f133a99250734b->doDisplay()
#37 /storage/av#####/www/public_html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#38 /storage/av#####/www/public_html/vendor/twig/twig/src/Template.php(392): Twig\Template->display()
#39 /storage/av#####/www/public_html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#40 /storage/av#####/www/public_html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#41 /storage/av#####/www/public_html/vendor/craftcms/cms/src/web/View.php(391): Twig\Environment->render()
#42 /storage/av#####/www/public_html/vendor/craftcms/cms/src/web/View.php(452): craft\web\View->renderTemplate()
#43 /storage/av#####/www/public_html/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate()
#44 /storage/av#####/www/public_html/vendor/craftcms/cms/src/controllers/EntriesController.php(248): craft\web\Controller->renderTemplate()
#45 [internal function]: craft\controllers\EntriesController->actionEditEntry()
#46 /storage/av#####/www/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#47 /storage/av#####/www/public_html/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#48 /storage/av#####/www/public_html/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction()
#49 /storage/av#####/www/public_html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#50 /storage/av#####/www/public_html/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction()
#51 /storage/av#####/www/public_html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#52 /storage/av#####/www/public_html/vendor/craftcms/cms/src/web/Application.php(279): yii\web\Application->handleRequest()
#53 /storage/av#####/www/public_html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#54 /storage/av#####/www/public_html/public/index.php(21): yii\base\Application->run()
#55 {main}
```

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.5.3
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.21
- Plugins & versions:

Super Table would be the only relevant plugin in this context.

**Comment by brandonkelly** [comment]
Please open up `/storage/av#####/www/public_html/storage/runtime/compiled_templates/fd/fd69122b0ad0673c1c53522839a9aa944d354aa72762eb0dfd3692634d1bcc05.php` and tell me two things:

1. The template name, referenced in the PHP comment at the top of the file (right before the `class` line)
2. The template line number, referenced in the PHP comment immediately before line 90 of that file

**Comment by circa1977** [comment]
```
/* _includes/forms/text */
```

```
// line 53
```

**Comment by circa1977** [comment]
@brandonkelly This is a Craft-optimized server that I'm not using if you'd like to get access to it. I just spun it up for a Staging site and deployed to a legacy server instead so we could keep working.

**Comment by brandonkelly** [comment]
Hm, that’s strange… the [_includes/forms/text](https://github.com/craftcms/cms/blob/b43974522c8a29f2e6406e8c7dde999c037df39b/src/templates/_includes/forms/text.html) template only has 46 lines in Craft 3.5.3.

So one of two things must have happened:

- The Composer update wasn’t completely successful, and you still have an old version of that template file installed
- Twig didn’t notice that the template file was updated, and is continuing to load a stale compiled PHP file for it.

Try deleting your whole `storage/runtime/compiled_templates/` folder. If that fixes it, it was the latter. Otherwise, try nuking your `vendor/` folder and running `composer install`.
