### ISSUE TITLE
Upgrade error - craft_templatecaches doesn't exist

### ISSUE THREAD

**Issue by circa1977** [craftcms/cms#6618]
### Description

I imported a mysqldump for a dev site. I cleared the caches before dumping the backup to minimize its size. When I attempted to upgrade the dev site, I received the following error.

```
Applying new migrations ... error: The command "'/storage/av#####/www/staging_html/craft' 'migrate/all' '--no-backup' '--no-content'" failed.

Exit Code: 1(General error)

Working directory: /storage/av#####/www/staging_html

Output:
================
Yii Migration Tool (based on Yii v2.0.36)

    > alter column message in table {{%deprecationerrors}} to text ... done (time: 0.079s)
    > add column enabled boolean NOT NULL DEFAULT TRUE AFTER `primary` to table {{%sites}} ... done (time: 0.119s)
    > delete from {{%templatecaches}} ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'av#####_STAGING_craft.craft_templatecaches' doesn't exist
The SQL being executed was: DELETE FROM `craft_templatecaches` (/storage/av#####/www/staging_html/vendor/yiisoft/yii2/db/Schema.php:677)
#0 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'DELETE FROM `cr...')
#1 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('DELETE FROM `cr...')
#2 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/db/Migration.php(300): yii\db\Command->execute()
#3 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/migrations/m200522_191453_clear_template_caches.php(18): yii\db\Migration->delete('{{%templatecach...')
#4 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m200522_191453_clear_template_caches->safeUp()
#5 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#6 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m200522_191453_clear_template_caches))
#7 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/services/Updates.php(220): craft\db\MigrationManager->up()
#8 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(328): craft\services\Updates->runMigrations(Array)
#9 [internal function]: craft\console\controllers\MigrateController->actionAll()
#10 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#12 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('all', Array)
#13 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#14 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#15 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#16 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#17 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#18 /storage/av#####/www/staging_html/craft(22): yii\base\Application->run()
#19 {main}


Error Output:
================
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Craft CMS.'

in /storage/av#####/www/staging_html/vendor/craftcms/cms/src/services/Updates.php:235

Stack trace:
#0 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(328): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#4 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('all', Array)
#5 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#8 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /storage/av#####/www/staging_html/craft(22): yii\base\Application->run()
#11 {main}


Output:

Yii Migration Tool (based on Yii v2.0.36)

    > alter column message in table {{%deprecationerrors}} to text ... done (time: 0.079s)
    > add column enabled boolean NOT NULL DEFAULT TRUE AFTER `primary` to table {{%sites}} ... done (time: 0.119s)
    > delete from {{%templatecaches}} ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'av#####_STAGING_craft.craft_templatecaches' doesn't exist
The SQL being executed was: DELETE FROM `craft_templatecaches` (/storage/av#####/www/staging_html/vendor/yiisoft/yii2/db/Schema.php:677)
#0 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'DELETE FROM `cr...')
#1 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('DELETE FROM `cr...')
#2 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/db/Migration.php(300): yii\db\Command->execute()
#3 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/migrations/m200522_191453_clear_template_caches.php(18): yii\db\Migration->delete('{{%templatecach...')
#4 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m200522_191453_clear_template_caches->safeUp()
#5 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#6 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m200522_191453_clear_template_caches))
#7 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/services/Updates.php(220): craft\db\MigrationManager->up()
#8 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(328): craft\services\Updates->runMigrations(Array)
#9 [internal function]: craft\console\controllers\MigrateController->actionAll()
#10 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#12 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('all', Array)
#13 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#14 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#15 /storage/av#####/www/staging_html/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#16 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#17 /storage/av#####/www/staging_html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#18 /storage/av#####/www/staging_html/craft(22): yii\base\Application->run()
#19 {main}
```

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by circa1977** [comment]
Disregard. The dump file wasn't complete.
