### ISSUE TITLE
Project config apply fails when a site is disabled for the front-end

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/cms#6799]
### Description

When running `project-config/apply` I get the following error:
"Applying changes from your project config files ... error: Undefined offset: 8"

This is the stacktrace:

````
2020-09-07 03:01:32 [-][-][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined offset: 8 in /var/www/vendor/craftcms/cms/src/helpers/ElementHelper.php:312

Stack trace:
#0 /var/www/vendor/craftcms/cms/src/helpers/ElementHelper.php(312): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/vendor...', 312, Array)
#1 /var/www/vendor/craftcms/cms/src/services/Elements.php(2182): craft\helpers\ElementHelper::supportedSitesForElement(Object(craft\elements\Entry))
#2 /var/www/vendor/craftcms/cms/src/services/Elements.php(691): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), false, true, NULL)
#3 /var/www/vendor/craftcms/cms/src/services/Sections.php(1506): craft\services\Elements->saveElement(Object(craft\elements\Entry), false)
#4 /var/www/vendor/craftcms/cms/src/services/Sections.php(1204): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section))
#5 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(1107): craft\services\Sections->handleChangedEntryType(Object(craft\events\ConfigEvent))
#6 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#7 /var/www/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#8 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(679): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#9 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(1097): craft\services\ProjectConfig->processConfigChanges('entryTypes.a36f...')
#10 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#11 /var/www/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#12 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(679): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#13 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(1206): craft\services\ProjectConfig->processConfigChanges('entryTypes.a36f...', false, NULL, true)
#14 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(539): craft\services\ProjectConfig->_applyChanges(Array)
#15 /var/www/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(137): craft\services\ProjectConfig->applyYamlChanges()
#16 [internal function]: craft\console\controllers\ProjectConfigController->actionApply()
#17 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /var/www/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#19 /var/www/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('apply', Array)
#20 /var/www/vendor/craftcms/cms/src/console/Controller.php(188): yii\console\Controller->runAction('apply', Array)
#21 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('apply', Array)
#22 /var/www/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#23 /var/www/vendor/craftcms/cms/src/console/Application.php(101): yii\console\Application->runAction('project-config/...', Array)
#24 /var/www/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#25 /var/www/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#26 /var/www/craft(22): yii\base\Application->run()
#27 {main}
````

I've tried a `project-config/rebuild`, but that didn't help.

Line 312 in the ElementHelper is looking at a siteId: `$site['siteUid'] = $siteUidMap[$site['siteId']];`

Site ID **"8"** is in our case a site that has been disabled temporarily, see screenshot:

![Schermafbeelding 2020-09-07 om 12 17 00](https://user-images.githubusercontent.com/1608184/92377529-91699380-f104-11ea-8ac7-c650f0035c87.png)

This somehow messes up the project-config apply method.

### Additional info

- Craft version: Craft CMS 3.5.8
- PHP version: 7.3

**Comment by thijskaspers** [comment]
Ah, have found some more information:

Line 312 in the ElementHelper is looking at a siteId: `$site['siteUid'] = $siteUidMap[$site['siteId']];`

Site ID **"8"** is in our case a site that has been disabled temporarily, see screenshot:

![Schermafbeelding 2020-09-07 om 12 17 00](https://user-images.githubusercontent.com/1608184/92377205-1607e200-f104-11ea-85fb-7f89c259d3b3.png)

This somehow messes up the project-config apply method

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.9 is out now with this fix.
