### ISSUE TITLE
Setting unknown property: craft\fields\PlainText::configFile after craft 2 > 3 upgrade

### ISSUE THREAD

**Issue by chrismou** [craftcms/cms#6810]
### Description

Followed the upgrade instructions for upgrading the DB from craft2 > craft3. I first it the below error when running the upgrade, and as I was stuck I harded coded the value, just to get it to finish successfully. Now it's all upgraded, everything seems to work except now hitting this error on several pages:

```
2020-09-10 13:09:35 [-][-][2hmantmqtiov71fcqicc91k4gg][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: craft\fields\PlainText::configFile in /home/mou/dev/site/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /home/mou/dev/site/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('configFile', 'Standard.json')
#1 /home/mou/dev/site/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\fields\PlainText), Array)
#2 /home/mou/dev/site/vendor/craftcms/cms/src/fields/PlainText.php(114): yii\base\BaseObject->__construct(Array)
#3 [internal function]: craft\fields\PlainText->__construct(Array)
#4 /home/mou/dev/site/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#5 /home/mou/dev/site/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\fields\\Pl...', Array, Array)
#6 /home/mou/dev/site/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\fields\\Pl...', Array, Array)
#7 /home/mou/dev/site/vendor/craftcms/cms/src/helpers/Component.php(111): yii\BaseYii::createObject(Array)
#8 /home/mou/dev/site/vendor/craftcms/cms/src/services/Fields.php(548): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#9 /home/mou/dev/site/vendor/craftcms/cms/src/services/Fields.php(573): craft\services\Fields->createField(Array)
#10 /home/mou/dev/site/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1990): craft\services\Fields->getAllFields()
#11 /home/mou/dev/site/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1351): craft\elements\db\ElementQuery->customFields()
#12 /home/mou/dev/site/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#13 /home/mou/dev/site/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\CategoryQuery))
#14 /home/mou/dev/site/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Query->createCommand(Object(craft\db\Connection))
#15 /home/mou/dev/site/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one(NULL)
#16 /home/mou/dev/site/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1496): craft\db\Query->one(NULL)
#17 /home/mou/dev/site/vendor/craftcms/cms/src/services/Elements.php(497): craft\elements\db\ElementQuery->one()
#18 /home/mou/dev/site/vendor/craftcms/cms/src/services/Elements.php(565): craft\services\Elements->getElementById(56565, 'craft\\elements\\...', 1)
#19 /home/mou/dev/site/vendor/craftcms/cms/src/web/UrlManager.php(383): craft\services\Elements->getElementByUri('electric-gate-a...', 1, true)
#20 /home/mou/dev/site/vendor/craftcms/cms/src/web/UrlManager.php(347): craft\web\UrlManager->_getMatchedElementRoute(Object(craft\web\Request))
#21 /home/mou/dev/site/vendor/craftcms/cms/src/web/UrlManager.php(113): craft\web\UrlManager->_getRequestRoute(Object(craft\web\Request))
#22 /home/mou/dev/site/vendor/craftcms/cms/src/web/Request.php(1213): craft\web\UrlManager->parseRequest(Object(craft\web\Request))
#23 /home/mou/dev/site/vendor/yiisoft/yii2/web/Application.php(82): craft\web\Request->resolve()
#24 /home/mou/dev/site/vendor/craftcms/cms/src/web/Application.php(279): yii\web\Application->handleRequest(Object(craft\web\Request))
#25 /home/mou/dev/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /home/mou/dev/site/web/index.php(25): yii\base\Application->run()
#27 {main}
```

If I hard code `public $configFile;` `craft\base\Field`, that error is replaced with:

`Setting unknown property: craft\fields\Number::columnType`

If I hard code _that_ in, everything loads OK.

The stack trace makes it look like it's trying to apply redactor config to a plain text file, but Im not sure yet

### Steps to reproduce

Hard to pinpoint exactly, but process was essentially:
1. Install Craft 3
2. Point at Craft2 DB
3. Run `./craft migrate/all`

### Additional info

- Craft version: 3.5.5
- PHP version: 7.3.20
- Database driver & version: MySQL 8.0.20
- Plugins & versions: Various, including Redactor

**Comment by brandonkelly** [comment]
Sounds like maybe the field type was changed from Redactor (which used to have a `configFile` setting) to Plain Text at some point, but just from the database rather than the Edit Field page, so the old settings stuck around.
