### ISSUE TITLE
field’s Upload Location setting has an invalid subpath

### ISSUE THREAD

**Issue by patricksantner** [craftcms/cms#6818]
### Description
when upgrading from craft 3.4.x to 3.5.y craft migration fails, tested with updates to 3.5.0 up to 3.5.9

```
One of Craft CMS’s migrations failed.

Invalid subpath: The Entry Image field’s Upload Location setting has an invalid subpath (“{site.group}”).

Migration: craft\migrations\m200620_230205_field_layout_changes

Output:

> add column elements text AFTER name to table {{%fieldlayouttabs}} ... done (time: 0.201s)
> drop column titleLabel from table {{%entrytypes}} ... done (time: 0.190s)
Exception: The Entry Image field’s Upload Location setting has an invalid subpath (“{site.group}”). (XYZ/___dist/vendor/craftcms/cms/src/fields/Assets.php:885)
#0 XYZ/___dist/vendor/craftcms/cms/src/fields/Assets.php(456): craft\fields\Assets->_determineUploadFolderId(Object(craft\elements\Entry), true)
#1 XYZ/___dist/vendor/craftcms/cms/src/fields/Assets.php(515): craft\fields\Assets->craft\fields\{closure}()
#2 XYZ/___dist/vendor/craftcms/cms/src/base/Element.php(3164): craft\fields\Assets->afterElementSave(Object(craft\elements\Entry), false)
#3 XYZ/___dist/vendor/craftcms/cms/src/elements/Entry.php(1476): craft\base\Element->afterSave(false)
#4 XYZ/___dist/vendor/craftcms/cms/src/services/Elements.php(2373): craft\elements\Entry->afterSave(false)
#5 XYZ/___dist/vendor/craftcms/cms/src/services/Elements.php(2577): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false)
#6 XYZ/___dist/vendor/craftcms/cms/src/services/Elements.php(2382): craft\services\Elements->_propagateElement(Object(craft\elements\Entry), Array, Object(craft\elements\Entry))
#7 XYZ/___dist/vendor/craftcms/cms/src/services/Elements.php(705): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), false, true, true)
#8 XYZ/___dist/vendor/craftcms/cms/src/services/Sections.php(1506): craft\services\Elements->saveElement(Object(craft\elements\Entry), false)
#9 XYZ/___dist/vendor/craftcms/cms/src/services/Sections.php(736): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section), Array)
#10 XYZ/___dist/vendor/craftcms/cms/src/services/ProjectConfig.php(1107): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#11 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#12 XYZ/___dist/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#13 XYZ/___dist/vendor/craftcms/cms/src/services/ProjectConfig.php(679): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#14 XYZ/___dist/vendor/craftcms/cms/src/services/ProjectConfig.php(1097): craft\services\ProjectConfig->processConfigChanges('sections.9726a6...')
#15 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#16 XYZ/___dist/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#17 XYZ/___dist/vendor/craftcms/cms/src/services/ProjectConfig.php(679): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#18 XYZ/___dist/vendor/craftcms/cms/src/services/ProjectConfig.php(487): craft\services\ProjectConfig->processConfigChanges('sections.9726a6...', true, '')
#19 XYZ/___dist/vendor/craftcms/cms/src/migrations/m200620_230205_field_layout_changes.php(87): craft\services\ProjectConfig->set('sections.9726a6...', Array)
#20 XYZ/___dist/vendor/craftcms/cms/src/migrations/m200620_230205_field_layout_changes.php(36): craft\migrations\m200620_230205_field_layout_changes->_updateEntryTypeFieldLayouts(Object(craft\services\ProjectConfig))
#21 XYZ/___dist/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m200620_230205_field_layout_changes->safeUp()
#22 XYZ/___dist/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#23 XYZ/___dist/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m200620_230205_field_layout_changes))
#24 XYZ/___dist/vendor/craftcms/cms/src/services/Updates.php(220): craft\db\MigrationManager->up()
#25 XYZ/___dist/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations(Array)
#26 XYZ/___dist/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#27 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#28 XYZ/___dist/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#29 XYZ/___dist/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#30 XYZ/___dist/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('migrate', Array)
#31 XYZ/___dist/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#32 XYZ/___dist/vendor/craftcms/cms/src/web/Application.php(280): yii\base\Module->runAction('updater/migrate', Array)
#33 XYZ/___dist/vendor/craftcms/cms/src/web/Application.php(671): craft\web\Application->runAction('updater/migrate')
#34 XYZ/___dist/vendor/craftcms/cms/src/web/Application.php(218): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#35 XYZ/___dist/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Ap

plication->handleRequest(Object(craft\web\Request))
#36 XYZ/___dist/web/index.php(42): yii\base\Application->run()
#37 /Users/patrick/.composer/vendor/laravel/valet/server.php(158): require('/Users/patrick/...')
#38 {main}
```

### Additional info

- Craft version: 3.4.19.1 / 3.5.9
- PHP version: 7.2.32
- Database driver & version: MySQL 8.0.18

composer.json

```json
{
  "name": "craftcms/craft",
  "description": "Craft CMS",
  "keywords": ["craft", "cms", "craftcms", "project"],
  "license": "MIT",
  "homepage": "https://craftcms.com/",
  "type": "project",
  "support": {
    "email": "support@craftcms.com",
    "issues": "https://github.com/craftcms/cms/issues",
    "forum": "https://craftcms.stackexchange.com/",
    "source": "https://github.com/craftcms/cms",
    "docs": "https://craftcms.com/docs",
    "rss": "https://craftcms.com/changelog.rss"
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "php": ">=7.2",
    "aelvan/craft-cp-element-count": "^1.0",
    "aelvan/imager": "v2.4.0",
    "angellco/spoon": "3.5.2",
    "craftcms/aws-s3": "1.2.7",
    "craftcms/cms": "3.5.9",
    "craftcms/element-api": "2.6.0",
    "craftcms/feed-me": "4.2.1.1",
    "craftcms/mailgun": "1.4.2",
    "craftcms/redactor": "2.6.1",
    "doublesecretagency/craft-cpbodyclasses": "2.2.1",
    "doublesecretagency/craft-cpcss": "^2.1",
    "dukt/videos": "^2.0",
    "ether/splash": "^3.0",
    "fruitstudios/linkit": "1.1.11",
    "jalendport/craft-lockout": "^1.0",
    "lukeyouell/craft-sentry": "^1.5",
    "marionnewlevant/twig-perversion": "2.1.0",
    "mmikkel/cp-clearcache": "^1.0",
    "mmikkel/cp-field-inspect": "^1.0",
    "monachilada/craft-matrixtoolbar": "^1.0",
    "nystudio107/craft-cookies": "^1.1",
    "nystudio107/craft-minify": "^1.2",
    "nystudio107/craft-retour": "3.1.36",
    "nystudio107/craft-seomatic": "3.3.8",
    "nystudio107/craft-typogrify": "^1.1",
    "pennebaker/craft-architect": "^2.2",
    "putyourlightson/craft-blitz": "3.6.5",
    "putyourlightson/craft-campaign": "1.14.2",
    "rias/craft-scout": "dev-master",
    "solspace/craft-freeform": "3.6.5",
    "studioespresso/craft-dumper": "2.0.0",
    "topshelfcraft/environment-label": "^3.1",
    "topshelfcraft/supersort": "^3.0",
    "ttempleton/craft-nocache": "^2.0",
    "twig/twig": "^2.6.2",
    "verbb/comments": "1.6.1",
    "verbb/expanded-singles": "^1.0",
    "verbb/image-resizer": "^2.0",
    "verbb/super-table": "2.4.6",
    "verbb/workflow": "^1.1.12",
    "vlucas/phpdotenv": "^2.4.0",
    "yiisoft/yii2-redis": "^2.0"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}
```

**Comment by brandonkelly** [comment]
Not really sure why that wouldn’t have worked. Can you please send a database backup from before the update over to support@craftcms.com?

**Comment by jules1091** [comment]
@brandonkelly we've already sent you the db backup. do you have any updates on this? Thank u!

**Comment by anthronaut** [comment]
@brandonkelly  Tagging along - Just encountered exactly the same error while trying to update from 3.4 to 3.5. 

`Exception: The Header Visual field’s Upload Location setting has an invalid subpath (“{ site.group.name | ascii | kebab `}”).``

Thanks for your efforts!

**Comment by davidhellmann** [comment]
@brandonkelly do you need something additional from our side?
We only want to go to 3.5 ASAP :)

**Comment by brandonkelly** [comment]
This is now fixed for the next release! Sorry for the delay.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
