### ISSUE TITLE
"Variable 'limit' does not exist." error message when trying to import contacts using Craft Campaign

### ISSUE THREAD

**Issue by Saboteur777** [craftcms/cms#7010]
### Description
Template error in CP, `limit` variable does not exist in 3.5.12.1: https://github.com/craftcms/cms/blob/3.5.12.1/src/templates/_includes/forms/elementSelect.html#L14

This has already been fixed in `develop` branch (https://github.com/craftcms/cms/blob/develop/src/templates/_includes/forms/elementSelect.html#L15), just wanted to notify you about this bug in current release. 

### Steps to reproduce

1. Install Craft Campaign
2. Navigate to **Campaign > Contacts > Import**
3. Select user group, click "Next".
4. See the error message. 

### Additional info

```
Twig\Error\RuntimeError: Variable "limit" does not exist. in /var/www/vendor/craftcms/cms/src/templates/_includes/forms/elementSelect.html:27
Stack trace:
#0 /var/www/storage/runtime/compiled_templates/ce/ce9c524adb14726e73d639bb18c9cf7f3da8bc17669087acebdeb3474b683508.php(119): __TwigTemplate_16f6ba801a04bd0c076030aeed53b9bca6262c445b3848006bd88ab2b9fb5208->{closure}()
#1 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_16f6ba801a04bd0c076030aeed53b9bca6262c445b3848006bd88ab2b9fb5208->doDisplay()
#2 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#3 /var/www/storage/runtime/compiled_templates/ff/ff2d9662b7929c96fb983a11890f337d4c4c5db7a49cf427b9a3c896b20bb103.php(715): Twig\Template->display()
#4 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1109): __TwigTemplate_8c5f1b4a7654a7584a318e53adbbb7e8491bef1839bfca9c56a88c9ab1a598ee->macro_elementSelect()
#5 /var/www/storage/runtime/compiled_templates/ff/ff2d9662b7929c96fb983a11890f337d4c4c5db7a49cf427b9a3c896b20bb103.php(1386): twig_call_macro()
#6 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1109): __TwigTemplate_8c5f1b4a7654a7584a318e53adbbb7e8491bef1839bfca9c56a88c9ab1a598ee->macro_elementSelectField()
#7 /var/www/storage/runtime/compiled_templates/a5/a5484e9df2ff5e5075c335e7cf05c3f763dcf3b0f6ea060f26a19d502735cf59.php(98): twig_call_macro()
#8 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_7648813055001b38717a7f3ac889fbc191604661836f4535849323f19565e675->block_content()
#9 /var/www/storage/runtime/compiled_templates/3d/3da17a35edb7a593e5e6a8182718cedbf611fdd4a626030c78d3ba2c66755c2e.php(444): Twig\Template->displayBlock()
#10 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_0e754c6d4c9751c6de36eec089cce0d8f0498ea98f5672d670123649dfe01ed7->block_main()
#11 /var/www/storage/runtime/compiled_templates/3d/3da17a35edb7a593e5e6a8182718cedbf611fdd4a626030c78d3ba2c66755c2e.php(309): Twig\Template->displayBlock()
#12 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_0e754c6d4c9751c6de36eec089cce0d8f0498ea98f5672d670123649dfe01ed7->block_body()
#13 /var/www/storage/runtime/compiled_templates/22/2258c3b8603d8947de94ab3e85fb10d9acae36795753df1da1994ca73fe1ec80.php(85): Twig\Template->displayBlock()
#14 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_913a7e5abd41e49f1e50a2c84c02b7df8d6ab4af755a9bd4579459211c4c658e->doDisplay()
#15 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#16 /var/www/storage/runtime/compiled_templates/05/0537662de34ea51946bb97a040b75859c5fe802caf7d9e37f772df3b05274ff7.php(56): Twig\Template->display()
#17 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_95fe960c4e3bcf44196287c2af54f40193582dca92003d6e751d9c44e0f16c80->doDisplay()
#18 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#19 /var/www/storage/runtime/compiled_templates/3d/3da17a35edb7a593e5e6a8182718cedbf611fdd4a626030c78d3ba2c66755c2e.php(154): Twig\Template->display()
#20 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_0e754c6d4c9751c6de36eec089cce0d8f0498ea98f5672d670123649dfe01ed7->doDisplay()
#21 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#22 /var/www/storage/runtime/compiled_templates/27/27303a1cc43a2c8bbafea607ef1db80cd7ce3efeb657b2593c20400727f81b54.php(273): Twig\Template->display()
#23 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_4cc350d8f989c187a9daa04bce8e0b1623194adf0f8759c6e55004a7c6cb8c3a->doDisplay()
#24 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#25 /var/www/storage/runtime/compiled_templates/d0/d002aa7c2b09c124c0ca24a3d663514e0a3dd1cb32c04fab772084fd31400481.php(77): Twig\Template->display()
#26 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_797286159092d82c7749facb608553bc59737752a813114961b9330ab7cfbee7->doDisplay()
#27 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#28 /var/www/storage/runtime/compiled_templates/a5/a5484e9df2ff5e5075c335e7cf05c3f763dcf3b0f6ea060f26a19d502735cf59.php(50): Twig\Template->display()
#29 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_7648813055001b38717a7f3ac889fbc191604661836f4535849323f19565e675->doDisplay()
#30 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#31 /var/www/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#32 /var/www/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#33 /var/www/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#34 /var/www/vendor/craftcms/cms/src/web/View.php(392): Twig\Environment->render()
#35 /var/www/vendor/craftcms/cms/src/web/View.php(453): craft\web\View->renderTemplate()
#36 /var/www/vendor/craftcms/cms/src/web/Controller.php(251): craft\web\View->renderPageTemplate()
#37 /var/www/vendor/putyourlightson/craft-campaign/src/controllers/ImportsController.php(354): craft\web\Controller->renderTemplate()
#38 /var/www/vendor/putyourlightson/craft-campaign/src/controllers/ImportsController.php(207): putyourlightson\campaign\controllers\ImportsController->_returnFieldsTemplate()
#39 [internal function]: putyourlightson\campaign\controllers\ImportsController->actionSelectUserGroup()
#40 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#41 /var/www/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#42 /var/www/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction()
#43 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#44 /var/www/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#45 /var/www/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction()
#46 /var/www/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest()
#47 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#48 /var/www/web/index.php(21): yii\base\Application->run()
#49 {main}
```

- Craft version: 3.5.12.1
- PHP version: 7.4.2
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Craft Campaign 1.16.3

**Comment by brandonkelly** [comment]
This was already reported by #6953 and as you noted, already fixed for the next release.

**Comment by Saboteur777** [comment]
Sorry, did not find the previous issue.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
