### ISSUE TITLE
Server Error After Deploying 3.5.15.1: craft\db\ActiveQuery

### ISSUE THREAD

**Issue by compass360** [craftcms/cms#7129]
### Description

After updating to 3.5.15.1 (along with a few plugins to most recent version), I'm getting server errors when attempting to access the CP on our staging environment. I'm not seeing these errors on local build. Relevant logs are below.

### Steps to reproduce

1. Updated craft to 3.5.15.1 (along with several plugins)
2. Test locally. All good.
3. Push to staging environment (via Craft Copy / git)
4. Front-end works fine, server error when accessing CP
5. Check logs, see error

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.4.4 (staging), 7.2.8 (local)
- Database driver & version: MySQL 5.7.30 (staging), MySQL 5.7.21 (local)
- Plugins & versions: (Paste below from composer.json)

    "aelvan/mailchimp-subscribe": "3.0.3",
    "carlcs/craft-diywidget": "2.0.2",
    "craftcms/ckeditor": "1.0.0-beta.3",
    "craftcms/cms": "3.5.15.1",
    "craftcms/element-api": "2.6.0",
    "craftcms/redactor": "2.8.3",
    "dompdf/dompdf": "^0.8.5",
    "enupal/paypal": "1.3.0",
    "enupal/snapshot": "1.2.7",
    "ether/logs": "3.0.3",
    "ether/tags": "1.0.7",
    "focuslabllc/craft-cheat-sheet": "2.0.3",
    "fortrabbit/craft-copy": "1.0.0",
    "fruitstudios/colorit": "1.0.8",
    "graftechnology/pdfshift": "1.1.0",
    "jalendport/craft-roman": "1.0.0",
    "miranj/craft-obfuscator": "1.0.4",
    "nystudio107/craft-similar": "1.0.6",
    "phenx/php-font-lib": "^0.5.1",
    "phenx/php-svg-lib": "^0.3.3",
    "rias/craft-colour-swatches": "1.2.3",
    "solspace/craft-express-forms": "1.0.8",
    "verbb/cp-nav": "3.0.13.1",
    "verbb/expanded-singles": "1.1.3",
    "verbb/field-manager": "2.2.1",
    "verbb/smith": "1.1.5",
    "verbb/super-table": "2.6.3",
    "vlucas/phpdotenv": "^2.4.0"

### Logs:

```
2020-11-12 10:30:32 [-][-][08ba9ffb13caed054e9794d713757354][error][yii\base\InvalidConfigException] ReflectionException: Class craft\db\ActiveQuery does not exist in /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/di/Container.php:453
Stack trace:
#0 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/di/Container.php(453): ReflectionClass->__construct('craft\\db\\Active...')
#1 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/di/Container.php(380): yii\di\Container->getDependencies('craft\\db\\Active...')
#2 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build('craft\\db\\Active...', Array, Array)
#3 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('craft\\db\\Active...', Array)
#4 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/db/ActiveRecord.php(42): yii\BaseYii::createObject('craft\\db\\Active...', Array)
#5 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/db/SoftDeleteTrait.php(84): craft\db\ActiveRecord::find()
#6 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/services/Categories.php(123): craft\records\CategoryGroup::find()
#7 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/services/Categories.php(145): craft\services\Categories->_groups()
#8 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/services/Categories.php(160): craft\services\Categories->getAllGroups()
#9 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/assets/cp/CpAsset.php(399): craft\services\Categories->getEditableGroups()
#10 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/assets/cp/CpAsset.php(316): craft\web\assets\cp\CpAsset->_editableCategoryGroups()
#11 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/assets/cp/CpAsset.php(99): craft\web\assets\cp\CpAsset->_craftData()
#12 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/web/View.php(267): craft\web\assets\cp\CpAsset->registerAssetFiles(Object(craft\web\View))
#13 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(1854): yii\web\View->registerAssetFiles('craft\\web\\asset...')
#14 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/web/View.php(265): craft\web\View->registerAssetFiles('craft\\web\\asset...')
#15 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(1854): yii\web\View->registerAssetFiles('verbb\\base\\asse...')
#16 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/web/View.php(265): craft\web\View->registerAssetFiles('verbb\\base\\asse...')
#17 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(1854): yii\web\View->registerAssetFiles('verbb\\cpnav\\ass...')
#18 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/web/View.php(163): craft\web\View->registerAssetFiles('verbb\\cpnav\\ass...')
#19 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(1099): yii\web\View->endBody()
#20 /srv/app/aflaflafl/htdocs/storage/runtime/compiled_templates/04/04433beee89c87b97abe51e2fd82e21cfde06d5f3f1872061fd8842b73d90c01.php(91): craft\web\View->endBody()
#21 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_4eb0e82d6db1957baf520f18104ef4e5a8326c399eb90135ca29ae4af8bbb70b->doDisplay(Array, Array)
#22 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /srv/app/aflaflafl/htdocs/storage/runtime/compiled_templates/56/562c7a7100e6f4433ef6a28ed770f99c4ada346ed62ddcb87bc07378bd9e9929.php(56): Twig\Template->display(Array, Array)
#24 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ce50255b3ad8b982a46ce73f03e0ff8394f513b8e630825eaee10d0af6695e68->doDisplay(Array, Array)
#25 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /srv/app/aflaflafl/htdocs/storage/runtime/compiled_templates/5e/5ef90eff6c58344efac95ebe62467dad7755ebaeb0986c5b2fbcd8e0859f6043.php(163): Twig\Template->display(Array, Array)
#27 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8612e4c66686a3f41ea583e9d2bbf08a3d406ea268aa6da5ab69fb163e8fa59d->doDisplay(Array, Array)
#28 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#30 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#31 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#32 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('login', Array)
#33 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(450): craft\web\View->renderTemplate('login', Array)
#34 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/Controller.php(241): craft\web\View->renderPageTemplate('login', Array, 'cp')
#35 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate('login', Array)
#36 [internal function]: craft\controllers\TemplatesController->actionRender('login', Array)
#37 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#38 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#39 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('render', Array)
#40 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#41 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('templates/rende...', Array)
#42 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#43 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#44 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#45 /srv/app/aflaflafl/htdocs/html/index.php(21): yii\base\Application->run()
#46 {main}

Next yii\base\InvalidConfigException: Failed to instantiate component or class "craft\db\ActiveQuery". in /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/di/Container.php:455
Stack trace:
#0 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/di/Container.php(380): yii\di\Container->getDependencies('craft\\db\\Active...')
#1 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build('craft\\db\\Active...', Array, Array)
#2 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('craft\\db\\Active...', Array)
#3 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/db/ActiveRecord.php(42): yii\BaseYii::createObject('craft\\db\\Active...', Array)
#4 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/db/SoftDeleteTrait.php(84): craft\db\ActiveRecord::find()
#5 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/services/Categories.php(123): craft\records\CategoryGroup::find()
#6 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/services/Categories.php(145): craft\services\Categories->_groups()
#7 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/services/Categories.php(160): craft\services\Categories->getAllGroups()
#8 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/assets/cp/CpAsset.php(399): craft\services\Categories->getEditableGroups()
#9 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/assets/cp/CpAsset.php(316): craft\web\assets\cp\CpAsset->_editableCategoryGroups()
#10 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/assets/cp/CpAsset.php(99): craft\web\assets\cp\CpAsset->_craftData()
#11 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/web/View.php(267): craft\web\assets\cp\CpAsset->registerAssetFiles(Object(craft\web\View))
#12 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(1854): yii\web\View->registerAssetFiles('craft\\web\\asset...')
#13 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/web/View.php(265): craft\web\View->registerAssetFiles('craft\\web\\asset...')
#14 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(1854): yii\web\View->registerAssetFiles('verbb\\base\\asse...')
#15 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/web/View.php(265): craft\web\View->registerAssetFiles('verbb\\base\\asse...')
#16 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(1854): yii\web\View->registerAssetFiles('verbb\\cpnav\\ass...')
#17 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/web/View.php(163): craft\web\View->registerAssetFiles('verbb\\cpnav\\ass...')
#18 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(1099): yii\web\View->endBody()
#19 /srv/app/aflaflafl/htdocs/storage/runtime/compiled_templates/04/04433beee89c87b97abe51e2fd82e21cfde06d5f3f1872061fd8842b73d90c01.php(91): craft\web\View->endBody()
#20 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_4eb0e82d6db1957baf520f18104ef4e5a8326c399eb90135ca29ae4af8bbb70b->doDisplay(Array, Array)
#21 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /srv/app/aflaflafl/htdocs/storage/runtime/compiled_templates/56/562c7a7100e6f4433ef6a28ed770f99c4ada346ed62ddcb87bc07378bd9e9929.php(56): Twig\Template->display(Array, Array)
#23 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ce50255b3ad8b982a46ce73f03e0ff8394f513b8e630825eaee10d0af6695e68->doDisplay(Array, Array)
#24 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /srv/app/aflaflafl/htdocs/storage/runtime/compiled_templates/5e/5ef90eff6c58344efac95ebe62467dad7755ebaeb0986c5b2fbcd8e0859f6043.php(163): Twig\Template->display(Array, Array)
#26 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8612e4c66686a3f41ea583e9d2bbf08a3d406ea268aa6da5ab69fb163e8fa59d->doDisplay(Array, Array)
#27 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#28 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#29 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#30 /srv/app/aflaflafl/htdocs/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#31 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('login', Array)
#32 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/View.php(450): craft\web\View->renderTemplate('login', Array)
#33 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/Controller.php(241): craft\web\View->renderPageTemplate('login', Array, 'cp')
#34 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate('login', Array)
#35 [internal function]: craft\controllers\TemplatesController->actionRender('login', Array)
#36 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#37 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#38 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('render', Array)
#39 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#40 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('templates/rende...', Array)
#41 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#42 /srv/app/aflaflafl/htdocs/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#43 /srv/app/aflaflafl/htdocs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#44 /srv/app/aflaflafl/htdocs/html/index.php(21): yii\base\Application->run()
#45 {main}
2020-11-12 10:30:32 [-][-][08ba9ffb13caed054e9794d713757354][info][application] $_GET = [
    'p' => 'admin/login'
]
```

**Comment by brandonkelly** [comment]
Sounds like maybe Craft wasn’t fully deployed properly on staging. Try nuking the `vendor/` folder and running `composer install`.

**Comment by compass360** [comment]
Nailed it. Thanks Brandon. Staging was set up and running fine before the updates (done locally, then pushed up to staging) so something must not have deployed properly, as you assumed. Looks like we are up and running again with no errors.
