### ISSUE TITLE
Garbage collection error

### ISSUE THREAD

**Issue by beeldr** [craftcms/cms#7356]
### Description
When running garbage collection the task crashes, seems related to https://github.com/craftcms/cms/issues/5820

```
./craft gc/run
Delete all trashed items? (yes|no) [no]:
Running garbage collection ... Exception 'yii\base\InvalidConfigException' with message 'Invalid section ID: 20'

in /var/www/vhosts/website.com/httpdocs/vendor/craftcms/cms/src/elements/Entry.php:1021

Stack trace:
#0 /var/www/vhosts/website.com/httpdocs/vendor/yiisoft/yii2/base/Component.php(139): craft\elements\Entry->getSection()
#1 /var/www/vhosts/website.com/httpdocs/vendor/craftcms/cms/src/base/Element.php(1440): yii\base\Component->__get('section')
#2 /var/www/vhosts/website.com/httpdocs/vendor/twentyfourhoursmedia/poll/src/services/PollService.php(300): craft\base\Element->__get('section')
#3 /var/www/vhosts/website.com/httpdocs/vendor/twentyfourhoursmedia/poll/src/Poll.php(160): twentyfourhoursmedia\poll\services\PollService->isAPollEntry(Object(craft\elements\Entry))
#4 [internal function]: twentyfourhoursmedia\poll\Poll::twentyfourhoursmedia\poll\{closure}(Object(yii\base\Event))
#5 /var/www/vhosts/website.com/httpdocs/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#6 /var/www/vhosts/website.com/httpdocs/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\elements\\...', 'afterDelete', Object(yii\base\Event))
#7 /var/www/vhosts/website.com/httpdocs/vendor/craftcms/cms/src/base/Element.php(3256): yii\base\Component->trigger('afterDelete')
#8 /var/www/vhosts/website.com/httpdocs/vendor/craftcms/cms/src/services/Elements.php(1497): craft\base\Element->afterDelete()
#9 /var/www/vhosts/website.com/httpdocs/vendor/craftcms/cms/src/services/Drafts.php(502): craft\services\Elements->deleteElement(Object(craft\elements\Entry), true)
#10 /var/www/vhosts/website.com/httpdocs/vendor/craftcms/cms/src/services/Gc.php(57): craft\services\Drafts->purgeUnsavedDrafts()
#11 /var/www/vhosts/website.com/httpdocs/vendor/craftcms/cms/src/console/controllers/GcController.php(56): craft\services\Gc->run(true)
#12 [internal function]: craft\console\controllers\GcController->actionRun()
#13 /var/www/vhosts/website.com/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /var/www/vhosts/website.com/httpdocs/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#15 /var/www/vhosts/website.com/httpdocs/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('run', Array)
#16 /var/www/vhosts/website.com/httpdocs/vendor/craftcms/cms/src/console/Controller.php(188): yii\console\Controller->runAction('run', Array)
#17 /var/www/vhosts/website.com/httpdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('run', Array)
#18 /var/www/vhosts/website.com/httpdocs/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('gc/run', Array)
#19 /var/www/vhosts/website.com/httpdocs/vendor/craftcms/cms/src/console/Application.php(88): yii\console\Application->runAction('gc/run', Array)
#20 /var/www/vhosts/website.com/httpdocs/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('gc/run', Array)
#21 /var/www/vhosts/website.com/httpdocs/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#22 /var/www/vhosts/website.com/httpdocs/craft(22): yii\base\Application->run()
#23 {main}
```

### Steps to reproduce

1. run ./craft gc/run

### Additional info

- Craft version: Craft Pro 3.5.17.1
- PHP version: 7.3.19
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
Looks like that error is coming from the [Poll](https://github.com/24hoursmedia-craftcms/poll) plugin. You’ll have to bring it up with them.
