### ISSUE TITLE
Unable to run craft update after upgrading to 3.6

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/cms#7469]
After updating 2 sites to Craft 3.6 I am no longer able to run the `craft update` CLI command.

When attempting to do so, I get the following error.

```
Exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET https://api.craftcms.com/v1/updates` resulted in a `400 Bad Request` response:
{"message":"Missing X-Craft-User-Email Header"}
```

### Steps to reproduce

1. Update to Craft 3.6
2. Try to use the update CLI command

### Additional info

- Craft version: 3.6.1
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25

**Comment by fantasticmachine** [comment]
Visiting the Updates section of the CP and having it poll for updates seems to solve this problem in the CLI.

**Comment by brandonkelly** [comment]
Are you able to find that error in `storage/logs/console.log`? If so can you please post the stack trace?

**Comment by fantasticmachine** [comment]
Yep, here you go.

```
2021-01-29 16:54:44 [-][-][-][error][GuzzleHttp\Exception\ClientException] GuzzleHttp\Exception\ClientException: Client error: `GET https://api.craftcms.com/v1/updates` resulted in a `400 Bad Request` response:
{"message":"Missing X-Craft-User-Email Header"}
 in /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Promise\Promise->wait()
#10 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/craftcms/cms/src/services/Api.php(126): GuzzleHttp\Client->request('GET', 'updates', Array)
#11 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/craftcms/cms/src/services/Api.php(84): craft\services\Api->request('GET', 'updates', Array)
#12 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/craftcms/cms/src/console/controllers/UpdateController.php(615): craft\services\Api->getUpdates(Array)
#13 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/craftcms/cms/src/console/controllers/UpdateController.php(95): craft\console\controllers\UpdateController->_getUpdates()
#14 [internal function]: craft\console\controllers\UpdateController->actionInfo()
#15 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#17 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('info', Array)
#18 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/craftcms/cms/src/console/Controller.php(193): yii\console\Controller->runAction('info', Array)
#19 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/craftcms/cms/src/console/controllers/UpdateController.php(148): craft\console\Controller->runAction('info')
#20 [internal function]: craft\console\controllers\UpdateController->actionUpdate(NULL)
#21 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#23 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('', Array)
#24 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/craftcms/cms/src/console/Controller.php(193): yii\console\Controller->runAction('', Array)
#25 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/yiisoft/yii2/base/Module.php(534): craft\console\Controller->runAction('', Array)
#26 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('update', Array)
#27 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('update', Array)
#28 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('update', Array)
#29 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#30 /Users/pete/Projects/FantasticMachine/pcn/dev/build/app/craft(22): yii\base\Application->run()
#31 {main}
```

**Comment by brandonkelly** [comment]
Got to the bottom of this. It was a bug on the API’s end. Deploying a fix now.
