### ISSUE TITLE
webp animation can not be uploaded

### ISSUE THREAD

**Issue by bitboxfw** [craftcms/cms#7544]
### Description
When we try to upload a wep animation, an exception is thrown. We have tried it on different servers with different projects and different webp animations. It seems to be a problem since Craft 3.5, as it still works with Craft 3.3 on the same server.

### Steps to reproduce

1. Try to upload an webp animation in CP (example file is attached as zip, because git does not allow webp - [webp-animation.zip](https://github.com/craftcms/cms/files/5963734/webp-animation.zip))

### Additional info

- Craft version: 3.5.18
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7.33
- Plugins & versions: 
CP Clear Cache	1.0.7
Dumper	2.0.0
Error Notifier	1.0.4
Logs	3.0.3
MatrixMate	1.2.7
Minifier	2.0.5
Redactor	2.8.5
Redactor Anchors	1.1.0
Smith	1.1.10
XML Sitemap	1.3.1

### Exception

```Imagine\Exception\RuntimeException: Unable to open image /var/www/project/storage/runtime/temp/webp-animation.webp in /var/www/project/vendor/pixelandtonic/imagine/src/Gd/Imagine.php:95
Stack trace:
#0 /var/www/project/vendor/craftcms/cms/src/image/Raster.php(166): Imagine\Gd\Imagine->open()
#1 /var/www/project/vendor/craftcms/cms/src/services/Images.php(207): craft\image\Raster->loadImage()
#2 /var/www/project/vendor/craftcms/cms/src/services/Images.php(324): craft\services\Images->loadImage()
#3 /var/www/project/vendor/craftcms/cms/src/helpers/Image.php(178): craft\services\Images->cleanImage()
#4 /var/www/project/vendor/craftcms/cms/src/elements/Asset.php(1798): craft\helpers\Image::cleanImageByPath()
#5 /var/www/project/vendor/craftcms/cms/src/services/Elements.php(2454): craft\elements\Asset->afterSave()
#6 /var/www/project/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal()
#7 /var/www/project/vendor/craftcms/cms/src/controllers/AssetsController.php(350): craft\services\Elements->saveElement()
#8 [internal function]: craft\controllers\AssetsController->actionUpload()
#9 /var/www/project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /var/www/project/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#11 /var/www/project/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#12 /var/www/project/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#13 /var/www/project/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#14 /var/www/project/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction()
#15 /var/www/project/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest()
#16 /var/www/project/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#17 /var/www/project/web/index.php(21): yii\base\Application->run()
#18 {main}

Next craft\errors\ImageException: The file “/var/www/project/storage/runtime/temp/webp-animation.webp“ does not appear to be an image.”. in /var/www/project/vendor/craftcms/cms/src/image/Raster.php:168
Stack trace:
#0 /var/www/project/vendor/craftcms/cms/src/services/Images.php(207): craft\image\Raster->loadImage()
#1 /var/www/project/vendor/craftcms/cms/src/services/Images.php(324): craft\services\Images->loadImage()
#2 /var/www/project/vendor/craftcms/cms/src/helpers/Image.php(178): craft\services\Images->cleanImage()
#3 /var/www/project/vendor/craftcms/cms/src/elements/Asset.php(1798): craft\helpers\Image::cleanImageByPath()
#4 /var/www/project/vendor/craftcms/cms/src/services/Elements.php(2454): craft\elements\Asset->afterSave()
#5 /var/www/project/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal()
#6 /var/www/project/vendor/craftcms/cms/src/controllers/AssetsController.php(350): craft\services\Elements->saveElement()
#7 [internal function]: craft\controllers\AssetsController->actionUpload()
#8 /var/www/project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#9 /var/www/project/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#10 /var/www/project/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#11 /var/www/project/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#12 /var/www/project/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#13 /var/www/project/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction()
#14 /var/www/project/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest()
#15 /var/www/project/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#16 /var/www/project/web/index.php(21): yii\base\Application->run()
#17 {main}

**Comment by brandonkelly** [comment]
I’m not able to reproduce using PHP’s 7.4.15-fpm-alpine Docker image, however it looks like its GD wasn’t installed with the `--with-webp` flag. Can you tell me what environment you’re using?

Most likely the issue is that PHP’s GD library doesn’t support animated webp images yet. It doesn’t look like ImageMagick does either, AFAICT.

Imgix does [say it supports animated webp](https://docs.imgix.com/apis/rendering/format/fm#webp), so maybe that’s your best bet, using a plugin like [Imager X](https://plugins.craftcms.com/imager-x) or [ImageOptimize](https://plugins.craftcms.com/image-optimize) to connect Craft to it.

You’ll likely need to disable the [sanitizeCpImageUploads](https://craftcms.com/docs/3.x/config/config-settings.html#sanitizecpimageuploads) config setting, which will avoid this error on initial upload.
