### ISSUE TITLE
CP Dashboard Crash after Update

### ISSUE THREAD

**Issue by SanboKyo** [craftcms/cms#7550]
### Description
After the update (3.6.2 -> 3.6.5.1) I wanted to add the widget "My Drafts" to the dashboard, but an error ocurred (red error notice at the top edge). Since then I can no longer call the dashboard - everything else works.

The error message: 

```
Invalid Configuration – yii\base\InvalidConfigException
Invalid section ID: 1
```

### Additional info

- Craft version: 3.6.5.1 
- PHP version: 7.3
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Please search for that error in `storage/logs/web.log` and post the stack trace that follows it.

**Comment by SanboKyo** [comment]
```
2021-02-11 17:03:48 [-][1][e5ltruuekbv0bsq2co0humfnj5][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid section ID: 1 in /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/elements/Entry.php:1049
Stack trace:
#0 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/elements/Entry.php(1197): craft\elements\Entry->getSection()
#1 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/helpers/ElementHelper.php(335): craft\elements\Entry->getIsEditable()
#2 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/helpers/Cp.php(327): craft\helpers\ElementHelper::isElementEditable(Object(craft\elements\Entry))
#3 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/widgets/MyDrafts.php(91): craft\helpers\Cp::elementHtml(Object(craft\elements\Entry))
#4 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/controllers/DashboardController.php(508): craft\widgets\MyDrafts->getBodyHtml()
#5 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/controllers/DashboardController.php(107): craft\controllers\DashboardController->_getWidgetInfo(Object(craft\widgets\MyDrafts))
#6 [internal function]: craft\controllers\DashboardController->actionIndex()
#7 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#9 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('index', Array)
#10 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('index', Array)
#11 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('dashboard/index', Array)
#12 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('dashboard/index', Array)
#13 /Applications/MAMP/htdocs/.../vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#14 /Applications/MAMP/htdocs/.../vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /Applications/MAMP/htdocs/.../web/index.php(22): yii\base\Application->run()
#16 /Users/admin/.composer/vendor/laravel/valet/server.php(214): require('/Applications/M...')
#17 {main}
```

**Comment by brandonkelly** [comment]
Try going to **Utilities** → **Project Config** and click the **Rebuild** button. Does that fix this for you?

**Comment by SanboKyo** [comment]
Rebuild did not fix the error.

But I deleted two(!?) entries of "My Drafts" in the widgets table (MySQL) and the dashboard works again.

However, when I want to add the widget again, the same thing happens: red error notice at the top edge, dashboard does not work, delete the entry in the widgets table (only one entry) and the dashboard works again!?

**Comment by brandonkelly** [comment]
Can you please send a database backup and your Composer files over to support@craftcms.com?

**Comment by brandonkelly** [comment]
Thanks for sending those files in. We tracked this down to a bug where Craft wasn’t soft-deleting unpublished drafts when a section/entry type was deleted.

It’s fixed now for the next release. In the meantime, you can fix on your end by running the following command:

```bash
> php craft gc --delete-all-trashed
```

**Comment by SanboKyo** [comment]
Thank you, Brandon!

🙏

Kind regards,

Henning

**Comment by brandonkelly** [comment]
Craft 3.6.6 is out now with that bugfix. Thanks again for your help!
