### ISSUE TITLE
PDOException when simple text field placeholder contains emoji

### ISSUE THREAD

**Issue by sebastiannoell** [craftcms/cms#7629]
### Description

When accidently copy pasted an emoji to a placeholder field and submitting the change, this trace stack occurred. 

### Steps to reproduce

1. Create a Matrix block field
2. A sub-block contains an emoji like 💪 (noticed that in a placeholder field for simple text)

```
PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x92\xAA",...' for column 'settings' at row 1 in /app/vendor/yiisoft/yii2/db/Command.php:1299
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1299): PDOStatement->execute()
#1 /app/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('INSERT INTO `fi...')
#2 /app/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute()
#3 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert('{{%fields}}', Array)
#4 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#5 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(false, NULL)
#6 /app/vendor/craftcms/cms/src/services/Fields.php(1714): yii\db\BaseActiveRecord->save(false)
#7 /app/vendor/craftcms/cms/src/services/Matrix.php(323): craft\services\Fields->applyFieldSave('cdc8cffb-a705-4...', Array, 'matrixBlockType...')
#8 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1654): craft\services\Matrix->handleChangedBlockType(Object(craft\events\ConfigEvent))
#9 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1166): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#10 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#11 /app/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#12 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(728): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#13 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(510): craft\services\ProjectConfig->_processConfigChangesInternal('matrixBlockType...', true, 'Save matrix blo...')
#14 /app/vendor/craftcms/cms/src/services/Matrix.php(247): craft\services\ProjectConfig->set('matrixBlockType...', Array, 'Save matrix blo...')
#15 /app/vendor/craftcms/cms/src/services/Matrix.php(591): craft\services\Matrix->saveBlockType(Object(craft\models\MatrixBlockType), false)
#16 /app/vendor/craftcms/cms/src/fields/Matrix.php(959): craft\services\Matrix->saveSettings(Object(craft\fields\Matrix), false)
#17 /app/vendor/craftcms/cms/src/services/Fields.php(1746): craft\fields\Matrix->afterSave(false)
#18 /app/vendor/craftcms/cms/src/services/Fields.php(867): craft\services\Fields->applyFieldSave('067bdb91-d926-4...', Array, 'global')
#19 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1654): craft\services\Fields->handleChangedField(Object(craft\events\ConfigEvent))
#20 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1166): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#21 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#22 /app/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#23 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(731): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#24 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(510): craft\services\ProjectConfig->_processConfigChangesInternal('fields.067bdb91...', true, 'Save field \xE2\x80\x9Cs...')
#25 /app/vendor/craftcms/cms/src/services/Fields.php(809): craft\services\ProjectConfig->set('fields.067bdb91...', Array, 'Save field \xE2\x80\x9Cs...')
#26 /app/vendor/craftcms/cms/src/controllers/FieldsController.php(328): craft\services\Fields->saveField(Object(craft\fields\Matrix))
#27 [internal function]: craft\controllers\FieldsController->actionSaveField()
#28 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#29 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#30 /app/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save-field', Array)
#31 /app/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('save-field', Array)
#32 /app/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('fields/save-fie...', Array)
#33 /app/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('fields/save-fie...', Array)
#34 /app/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#35 /app/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#36 /app/web/index.php(22): yii\base\Application->run()
#37 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x92\xAA",...' for column 'settings' at row 1
The SQL being executed was: INSERT INTO `fields` (`uid`, `groupId`, `name`, `handle`, `context`, `instructions`, `searchable`, `translationMethod`, `translationKeyFormat`, `type`, `settings`, `dateCreated`, `dateUpdated`) VALUES ('cdc8cffb-a705-4efb-8109-9143a644b54c', NULL, 'Überschrift', 'headline', 'matrixBlockType:9a8cfa2c-abf7-4e31-9b43-c60e97c20790', '', 0, 'none', NULL, 'craft\\fields\\PlainText', '{\"byteLimit\":null,\"charLimit\":null,\"code\":\"\",\"columnType\":null,\"initialRows\":\"4\",\"multiline\":\"\",\"placeholder\":\"Wir supporten 💪\",\"uiMode\":\"normal\"}', '2021-02-27 10:25:33', '2021-02-27 10:25:33') in /app/vendor/yiisoft/yii2/db/Schema.php:678
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `fi...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('INSERT INTO `fi...')
#2 /app/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute()
#3 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert('{{%fields}}', Array)
#4 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#5 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(false, NULL)
#6 /app/vendor/craftcms/cms/src/services/Fields.php(1714): yii\db\BaseActiveRecord->save(false)
#7 /app/vendor/craftcms/cms/src/services/Matrix.php(323): craft\services\Fields->applyFieldSave('cdc8cffb-a705-4...', Array, 'matrixBlockType...')
#8 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1654): craft\services\Matrix->handleChangedBlockType(Object(craft\events\ConfigEvent))
#9 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1166): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#10 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#11 /app/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#12 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(728): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#13 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(510): craft\services\ProjectConfig->_processConfigChangesInternal('matrixBlockType...', true, 'Save matrix blo...')
#14 /app/vendor/craftcms/cms/src/services/Matrix.php(247): craft\services\ProjectConfig->set('matrixBlockType...', Array, 'Save matrix blo...')
#15 /app/vendor/craftcms/cms/src/services/Matrix.php(591): craft\services\Matrix->saveBlockType(Object(craft\models\MatrixBlockType), false)
#16 /app/vendor/craftcms/cms/src/fields/Matrix.php(959): craft\services\Matrix->saveSettings(Object(craft\fields\Matrix), false)
#17 /app/vendor/craftcms/cms/src/services/Fields.php(1746): craft\fields\Matrix->afterSave(false)
#18 /app/vendor/craftcms/cms/src/services/Fields.php(867): craft\services\Fields->applyFieldSave('067bdb91-d926-4...', Array, 'global')
#19 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1654): craft\services\Fields->handleChangedField(Object(craft\events\ConfigEvent))
#20 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1166): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#21 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#22 /app/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#23 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(731): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#24 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(510): craft\services\ProjectConfig->_processConfigChangesInternal('fields.067bdb91...', true, 'Save field \xE2\x80\x9Cs...')
#25 /app/vendor/craftcms/cms/src/services/Fields.php(809): craft\services\ProjectConfig->set('fields.067bdb91...', Array, 'Save field \xE2\x80\x9Cs...')
#26 /app/vendor/craftcms/cms/src/controllers/FieldsController.php(328): craft\services\Fields->saveField(Object(craft\fields\Matrix))
#27 [internal function]: craft\controllers\FieldsController->actionSaveField()
#28 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#29 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#30 /app/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save-field', Array)
#31 /app/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('save-field', Array)
#32 /app/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('fields/save-fie...', Array)
#33 /app/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('fields/save-fie...', Array)
#34 /app/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#35 /app/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#36 /app/web/index.php(22): yii\base\Application->run()
#37 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 1366
    [2] => Incorrect string value: '\xF0\x9F\x92\xAA",...' for column 'settings' at row 1
)

```

### Additional info

- Craft version: Craft CMS 3.6.7
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7.33
- Plugins & versions: Craft Solo 3.6.7 
  - Craft Commerce 3.2.16
  - Redactor: 2.8.5
  - SEO: 3.6.7

**Comment by sebastiannoell** [comment]
<img width="951" alt="Bildschirmfoto 2021-02-27 um 11 35 52" src="https://user-images.githubusercontent.com/2744471/109384879-0a95b680-78f0-11eb-856a-d5d9835e7f30.png">

**Comment by successgo** [comment]
hello, what is the character set you are using ? Is it `utf8mb4` ?

**Comment by sebastiannoell** [comment]
Hey there! It's `utf8_unicode_ci`
<img width="1159" alt="Bildschirmfoto 2021-02-27 um 20 59 54" src="https://user-images.githubusercontent.com/2744471/109398719-bf56c480-793e-11eb-86ca-fa69c7d60087.png">

**Comment by brandonkelly** [comment]
Guessing your charset is `utf8`, which is the default, but does not support 4-byte characters such as emoji. (`utf8_unicode_ci` is the collation.) `utf8mb4` is the charset required for 4-byte characters, which you can switch to using the `craft db/convert-charset` command, however that may not be an option if you have a lot of fields, as the higher byte count reduces the maximum index and table sizes.

Craft works around `utf8`’s 3-byte limit by converting emoji in specific values to `:shortcodes:`. I just added shortcode support to Plain Text fields’ Placeholder settings, so this is resolved for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.8 is out now with that change.
