### ISSUE TITLE
Error when trying to log into admin panel

### ISSUE THREAD

**Issue by JordanMed** [craftcms/cms#7655]
### Description
My staging site is receiving an error after upgrading to 3.6.8 but my production site and local host aren't receiving the same error. 

Twig Syntax Error – Twig\Error\SyntaxError
Unknown "boolean" test.

  in /var/www/vendor/craftcms/cms/src/templates/_includes/forms/text.html
   class: class,
    type: type,
    id: id ?? false,
    inputmode: inputmode ?? false,
    size: size ?? false,
    name: name ?? false,
    value: value ?? false,
    maxlength: maxlength ?? false,
    autofocus: (autofocus ?? false) and not craft.app.request.isMobileBrowser(true),
    autocomplete: autocomplete is boolean ? (autocomplete ? 'on' : 'off') : autocomplete,
    autocorrect: (autocorrect ?? true) ? false : 'off',
    autocapitalize: (autocapitalize ?? true) ? false : 'off',
    disabled: disabled ?? false,
    readonly: readonly ?? false,
    title: title ?? false,
    placeholder: placeholder ?? false,
    step: step ?? false,
    min: min ?? false,
    max: max ?? false,

```
Twig\Error\SyntaxError: Unknown "boolean" test. in /var/www/vendor/craftcms/cms/src/templates/_includes/forms/text.html:20
Stack trace:
#0 /var/www/vendor/twig/twig/src/ExpressionParser.php(694): Twig\ExpressionParser->getTest(20)
#1 /var/www/vendor/twig/twig/src/ExpressionParser.php(79): Twig\ExpressionParser->parseTestExpression(Object(Twig\Node\Expression\NameExpression))
#2 /var/www/vendor/twig/twig/src/ExpressionParser.php(389): Twig\ExpressionParser->parseExpression()
#3 /var/www/vendor/twig/twig/src/ExpressionParser.php(281): Twig\ExpressionParser->parseHashExpression()
#4 /var/www/vendor/twig/twig/src/ExpressionParser.php(175): Twig\ExpressionParser->parsePrimaryExpression()
#5 /var/www/vendor/twig/twig/src/ExpressionParser.php(70): Twig\ExpressionParser->getPrimary()
#6 /var/www/vendor/twig/twig/src/ExpressionParser.php(677): Twig\ExpressionParser->parseExpression()
#7 /var/www/vendor/twig/twig/src/TokenParser/SetTokenParser.php(38): Twig\ExpressionParser->parseMultitargetExpression()
#8 /var/www/vendor/twig/twig/src/Parser.php(185): Twig\TokenParser\SetTokenParser->parse(Object(Twig\Token))
#9 /var/www/vendor/twig/twig/src/Parser.php(98): Twig\Parser->subparse(NULL, false)
#10 /var/www/vendor/twig/twig/src/Environment.php(563): Twig\Parser->parse(Object(Twig\TokenStream))
#11 /var/www/vendor/twig/twig/src/Environment.php(595): Twig\Environment->parse(Object(Twig\TokenStream))
#12 /var/www/vendor/craftcms/cms/src/web/twig/Environment.php(60): Twig\Environment->compileSource(Object(Twig\Source))
#13 /var/www/vendor/twig/twig/src/Environment.php(408): craft\web\twig\Environment->compileSource(Object(Twig\Source))
#14 /var/www/vendor/twig/twig/src/Environment.php(381): Twig\Environment->loadClass('__TwigTemplate_...', '_includes/forms...', NULL)
#15 /var/www/vendor/craftcms/cms/src/web/twig/Environment.php(41): Twig\Environment->loadTemplate('_includes/forms...', NULL)
#16 /var/www/vendor/twig/twig/src/Environment.php(513): craft\web\twig\Environment->loadTemplate('_includes/forms...')
#17 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1224): Twig\Environment->resolveTemplate(Array)
#18 /var/www/storage/runtime/compiled_templates/21/21606e7ca23d081a8542e476f40b06976f19fb80519dfffcfe887ae6499bb251.php(806): twig_include(Object(craft\web\twig\Environment), Array, '_includes/forms...', Array)
#19 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1110): __TwigTemplate_3d84e997f4aa580d76b1dddfc011b97e406c617f80623f266878806d35eaf67b->macro_field(Array, 'template:_inclu...')
#20 /var/www/storage/runtime/compiled_templates/21/21606e7ca23d081a8542e476f40b06976f19fb80519dfffcfe887ae6499bb251.php(840): twig_call_macro(Object(__TwigTemplate_3d84e997f4aa580d76b1dddfc011b97e406c617f80623f266878806d35eaf67b), 'macro_field', Array, 133, Array, Object(Twig\Source))
#21 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1110): __TwigTemplate_3d84e997f4aa580d76b1dddfc011b97e406c617f80623f266878806d35eaf67b->macro_textField(Array)
#22 /var/www/storage/runtime/compiled_templates/97/9753b4501ff3406e99929a811ab20c779f4801f25f14f06918c0b04f52fddcae.php(46): twig_call_macro(Object(__TwigTemplate_3d84e997f4aa580d76b1dddfc011b97e406c617f80623f266878806d35eaf67b), 'macro_textField', Array, 4, Array, Object(Twig\Source))
#23 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_4c6a66c2404f5408beca54279c4b827e83b627324a4742585b320c9c1b58443e->doDisplay(Array, Array)
#24 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /var/www/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#26 /var/www/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#27 /var/www/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#28 /var/www/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('_components/wid...', Array)
#29 /var/www/vendor/craftcms/cms/src/widgets/Feed.php(85): craft\web\View->renderTemplate('_components/wid...', Array)
#30 /var/www/vendor/craftcms/cms/src/controllers/DashboardController.php(80): craft\widgets\Feed->getSettingsHtml()
#31 [internal function]: craft\controllers\DashboardController->actionIndex()
#32 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#33 /var/www/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#34 /var/www/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('index', Array)
#35 /var/www/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('index', Array)
#36 /var/www/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('dashboard/index', Array)
#37 /var/www/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('dashboard/index', Array)
#38 /var/www/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#39 /var/www/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#40 /var/www/html/index.php(21): yii\base\Application->run()
#41 {main}
```

### Steps to reproduce

1. I updated the 3.6.8 on local host, pushed changes to staging tested with zero errors. pushed to production with zero errors.
2. Logged out of staging admin dashboard and when I went to sign back in received error. The error is showing up on staging.website.ca/admin and staging.website.ca/admin/dashboard
3. error isn't showing up on production account (even in dev mode) or local host. 
4. if you are logged into staging before this change is pushed you can still access the settings and utilities panel staging.website.ca/admin/settings

### Additional info

- Craft version: 3.6.8
- PHP version: 7.4.15
- Database driver & version: mysql
- Plugins & versions: amazon S3 1.2.11, redactor 2.8.5, redirect manager 1.1.1, super table 2.6.7

**Comment by brandonkelly** [comment]
Open up `vendor/craftcms/cms/src/web/twig/Extension.php` and check lines 289–291. Do they look like this?

https://github.com/craftcms/cms/blob/61a3206f209f86f1c1d855bbf8f3a3bdfe73d65c/src/web/twig/Extension.php#L289-L291

If not, perhaps the new update wasn’t fully deployed to the server.

If they’re there, perhaps OPcache didn’t recognize that the file was replaced, or something. Not really sure…

In any case, you should be able to resolve by nuking your `vendor/` folder and running `composer install`.
