### ISSUE TITLE
Exception thrown on garbage collection with string purgeUnsavedDraftsDuration

### ISSUE THREAD

**Issue by dralshehri** [craftcms/cms#7714]
### Description

```php
Running garbage collection ... Exception 'TypeError' with message 'Argument 1 passed to craft\helpers\DateTimeHelper::secondsToInterval() must be of the type int, string given, called in /app/vendor/craftcms/cms/src/services/Drafts.php on line 524'

in /app/vendor/craftcms/cms/src/helpers/DateTimeHelper.php:490

Stack trace:
#0 /app/vendor/craftcms/cms/src/services/Drafts.php(524): craft\helpers\DateTimeHelper::secondsToInterval('P1W')
#1 /app/vendor/craftcms/cms/src/services/Gc.php(64): craft\services\Drafts->purgeUnsavedDrafts()
#2 /app/vendor/craftcms/cms/src/console/controllers/GcController.php(56): craft\services\Gc->run(true)
#3 [internal function]: craft\console\controllers\GcController->actionRun()
#4 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#6 /app/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('run', Array)
#7 /app/vendor/craftcms/cms/src/console/Controller.php(192): yii\console\Controller->runAction('run', Array)
#8 /app/vendor/yiisoft/yii2/base/Module.php(534): craft\console\Controller->runAction('run', Array)
#9 /app/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('gc/run', Array)
#10 /app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('gc/run', Array)
#11 /app/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('gc/run', Array)
#12 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#13 /app/craft(23): yii\base\Application->run()
#14 {main}
ERROR: 1
```

### Steps to reproduce

1. Set `purgeUnsavedDraftsDuration` config to a string duration interval e.g. `P1W`
2. Run `./craft gc/run` console command

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4.15

Also, `purgeUnsavedDraftsDuration` is somehow missing from the docs.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.11 is out now with that fix.
