### ISSUE TITLE
Job priority is not supported in the driver (Redis queue)

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#7719]
### Description
We are using the yii redis queue:

```
'queue' => [
    'class'   => yii\queue\redis\Queue::class,
    'redis'   => 'redis',
    'channel' => 'queue',
    'ttr'     => 60 * 60 * 6 // 6 hours
],
```

We all of a sudden started getting the following error when applying project config changes via CLI:

```
  - updating entryTypes.f40d7e94-fa6d-4001-92e2-a177aa1a3a00 ... 
error: Job priority is not supported in the driver.
```

We also noticed this happens when we removed an entry from an entries field and then saved the entry:

```
yii\base\NotSupportedException: Job priority is not supported in the driver. in /var/www/mwi/production/releases/20210323165926/vendor/yiisoft/yii2-queue/src/drivers/redis/Queue.php:191
Stack trace:
#0 /var/www/mwi/production/releases/20210323165926/vendor/yiisoft/yii2-queue/src/Queue.php(196): yii\queue\redis\Queue->pushMessage()
#1 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/helpers/Queue.php(56): yii\queue\Queue->push()
#2 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/services/Elements.php(2575): craft\helpers\Queue::push()
#3 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal()
#4 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/services/Matrix.php(729): craft\services\Elements->saveElement()
#5 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/fields/Matrix.php(997): craft\services\Matrix->saveField()
#6 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/base/Element.php(3359): craft\fields\Matrix->afterElementPropagate()
#7 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/elements/Entry.php(1580): craft\base\Element->afterPropagate()
#8 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/services/Elements.php(2520): craft\elements\Entry->afterPropagate()
#9 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal()
#10 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/controllers/EntriesController.php(382): craft\services\Elements->saveElement()
#11 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#12 /var/www/mwi/production/releases/20210323165926/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#13 /var/www/mwi/production/releases/20210323165926/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#14 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#15 /var/www/mwi/production/releases/20210323165926/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#16 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#17 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction()
#18 /var/www/mwi/production/releases/20210323165926/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest()
#19 /var/www/mwi/production/releases/20210323165926/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#20 /var/www/mwi/production/releases/20210323165926/web/index.php(22): yii\base\Application->run()
#21 {main}
```

And when saving an entry type:

```
yii\base\NotSupportedException: Job priority is not supported in the driver. in /var/www/html/vendor/yiisoft/yii2-queue/src/drivers/redis/Queue.php:191
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2-queue/src/Queue.php(196): yii\queue\redis\Queue->pushMessage('O:31:"craft\\que...', 21600, 0, 2049)
#1 /var/www/html/vendor/craftcms/cms/src/helpers/Queue.php(56): yii\queue\Queue->push(Object(craft\queue\jobs\PruneRevisions))
#2 /var/www/html/vendor/craftcms/cms/src/services/Revisions.php(196): craft\helpers\Queue::push(Object(craft\queue\jobs\PruneRevisions), 2049)
#3 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1584): craft\services\Revisions->createRevision(Object(craft\elements\Entry), 2, NULL)
#4 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2520): craft\elements\Entry->afterPropagate(false)
#5 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), false, false, true)
#6 /var/www/html/vendor/craftcms/cms/src/services/Sections.php(1525): craft\services\Elements->saveElement(Object(craft\elements\Entry), false)
#7 /var/www/html/vendor/craftcms/cms/src/services/Sections.php(1221): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section))
#8 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1664): craft\services\Sections->handleChangedEntryType(Object(craft\events\ConfigEvent))
#9 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1181): craft\web\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#10 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#11 /var/www/html/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#12 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(744): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#13 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(517): craft\services\ProjectConfig->_processConfigChangesInternal('entryTypes.0944...', true, 'Save entry type...')
#14 /var/www/html/vendor/craftcms/cms/src/services/Sections.php(1117): craft\services\ProjectConfig->set('entryTypes.0944...', Array, 'Save entry type...')
#15 /var/www/html/vendor/craftcms/cms/src/controllers/SectionsController.php(344): craft\services\Sections->saveEntryType(Object(craft\models\EntryType))
#16 [internal function]: craft\controllers\SectionsController->actionSaveEntryType()
#17 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#19 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save-entry-type', Array)
#20 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('save-entry-type', Array)
#21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('sections/save-e...', Array)
#22 /var/www/html/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('sections/save-e...', Array)
#23 /var/www/html/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /var/www/html/web/index.php(22): yii\base\Application->run()
#26 {main}
```

### Steps to reproduce

1. Use the `yiisoft/yii2-redis` queue component
2. Try to do any of the 3 actions above

### Additional info

- Craft version: Craft Pro 3.6.11
- PHP version: 7.4.16
- Database driver & version: MySQL 8.0.23
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Amazon S3</th>
                        <td>1.2.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Classnames</th>
                        <td>1.0.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Command Palette</th>
                        <td>3.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Craft Commerce</th>
                        <td>3.2.15.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Feed Me</th>
                        <td>4.3.5.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Imgix</th>
                        <td>2.1.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Linkit</th>
                        <td>1.1.12.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Navigation</th>
                        <td>1.4.14</td>
                    </tr>
                                    <tr>
                        <th class="light">Ray</th>
                        <td>1.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.8.5</td>
                    </tr>
                                    <tr>
                        <th class="light">Scout</th>
                        <td>2.3.1</td>
                    </tr>
                                    <tr>
                        <th class="light">SEOmatic</th>
                        <td>3.3.35</td>
                    </tr>
                                    <tr>
                        <th class="light">Super Table</th>
                        <td>2.6.7</td>
                    </tr>
                                    <tr>
                        <th class="light">Table Maker</th>
                        <td>2.0.1</td>
                    </tr>
                            </tbody>
        </table>

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released 3.6.11.1 with a fix.
