### ISSUE TITLE
If multi-site has a different domain per site, live preview crashes the system when used on a new, unsaved entry

### ISSUE THREAD

**Issue by toddpadwick** [craftcms/cms#7782]
### Description
Our site has a different domain for each site:
https://www.thewriter.com/ - en-US
https://www.thewriter.co.uk/ - en-GB

Our admin is only accessible via https://www.thewriter.com/admin

We've discovered that if you create a brand new entry, with the site set to en-GB, and then click live preview, we get an internal server error. The admin then continues to bug out such as logging the user out regularly after that.

### Steps to reproduce

1. assign a different domain to two multi-sites
2. access the admin from one multi-site but switch the site drop down the other inside the CMS.
3. create a new entry assigned to that other site (whose domain is not the CMS domain), and click live preview without saving

### Additional info

- Craft version:Craft Pro 3.6.5.1
- PHP version:8.0.2
- Database driver & version:MySQL 8.0.20
- Plugins & versions:

<details open>
<summary>Logs</summary>

These are the two logs that seem relevant:

```
apache_access  108.162.229.250 - - [09/Apr/2021:13:06:28 +0000] "POST /index.php?p=admin/actions/preview/create-token HTTP/1.1" 403 1676 "https://www.thewriter.com/admin/entries/whitepapers/19097?site=default&draftId=201&fresh=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
apache_access  108.162.229.250 - - [09/Apr/2021:13:06:27 +0000] "POST /index.php?p=admin/actions/entry-revisions/save-draft HTTP/1.1" 200 1702 "https://www.thewriter.com/admin/entries/whitepapers/19097?site=default&draftId=201&fresh=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
apache_access  108.162.229.250 - - [09/Apr/2021:13:06:28 +0000] "POST /index.php?p=admin/actions/preview/create-token HTTP/1.1" 403 1676 "https://www.thewriter.com/admin/entries/whitepapers/19097?site=default&draftId=201&fresh=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"

```
</details>

**Comment by brandonkelly** [comment]
Clear out your `storage/logs/` directory (or directories, if each site has its own `storage/` directory), reproduce the error, and then search the `storage/logs/web.log` file(s) for “`[error]`”. Any occurrences? If so please post the full error log including the stack trace.

**Comment by toddpadwick** [comment]
Hi @brandonkelly .
We're using Fortrabbit which merges crafts web log with all other php errors. and here are the resulting errors:
This occured when I first opened a new 'create entry instance':
```
apache_access  172.70.35.15 - - [04/May/2021:06:54:19 +0000] "GET /sitemaps-1-section-blog-1-sitemap.xml?p=sitemaps-1-section-blog-1-sitemap.xml HTTP/1.1" 503 846 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
```

And these bunch of errors occurred when I clicked live preview:
```
apache_access  162.158.159.36 - - [04/May/2021:06:55:05 +0000] "GET /index.php?p=admin/actions/debug/default/toolbar&tag=6090efc6d48fd HTTP/1.1" 404 35118 "https://www.thewriter.com/admin/entries/blog/19741?site=default&draftId=210&fresh=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
web_php_error  2021-05-04T06:55:11Z '1031b8c41dfff97a311a7ac99863bdc5__id' => 1
apache_access  162.158.159.36 - - [04/May/2021:06:55:11 +0000] "POST /index.php?p=admin/actions/preview/create-token HTTP/1.1" 403 1648 "https://www.thewriter.com/admin/entries/blog/19741?site=theWriterUS&draftId=210" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
web_php_error  2021-05-04T06:55:11Z 2021-05-04 07:55:11 [-][1][-][error][yii\web\HttpException:403] yii\web\ForbiddenHttpException: User is not authorized to perform this action in /srv/app/thewriter-prod/htdocs/vendor/craftcms/cms/src/web/Controller.php:344
web_php_error  2021-05-04T06:55:11Z Stack trace:
web_php_error  2021-05-04T06:55:11Z #1 [internal function]: craft\controllers\PreviewController->actionCreateToken()
web_php_error  2021-05-04T06:55:11Z #0 /srv/app/thewriter-prod/htdocs/vendor/craftcms/cms/src/controllers/PreviewController.php(62): craft\web\Controller->requireAuthorization('previewDraft:21...')
web_php_error  2021-05-04T06:55:11Z #2 /srv/app/thewriter-prod/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
web_php_error  2021-05-04T06:55:11Z #3 /srv/app/thewriter-prod/htdocs/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
web_php_error  2021-05-04T06:55:11Z #5 /srv/app/thewriter-prod/htdocs/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('create-token', Array)
web_php_error  2021-05-04T06:55:11Z #4 /srv/app/thewriter-prod/htdocs/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('create-token', Array)
web_php_error  2021-05-04T06:55:11Z #6 /srv/app/thewriter-prod/htdocs/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('preview/create-...', Array)
web_php_error  2021-05-04T06:55:11Z #7 /srv/app/thewriter-prod/htdocs/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('preview/create-...', Array)
web_php_error  2021-05-04T06:55:11Z #9 /srv/app/thewriter-prod/htdocs/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
web_php_error  2021-05-04T06:55:11Z #8 /srv/app/thewriter-prod/htdocs/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
web_php_error  2021-05-04T06:55:11Z #11 {main}
web_php_error  2021-05-04T06:55:11Z #10 /srv/app/thewriter-prod/htdocs/web/index.php(21): yii\base\Application->run()
web_php_error  2021-05-04T06:55:11Z ]
web_php_error  2021-05-04T06:55:11Z 2021-05-04 07:55:11 [-][1][-][info][application] $_GET = [
web_php_error  2021-05-04T06:55:11Z 'p' => 'admin/actions/preview/create-token'
web_php_error  2021-05-04T06:55:11Z 'siteId' => '5'
web_php_error  2021-05-04T06:55:11Z  
web_php_error  2021-05-04T06:55:11Z $_POST = [
web_php_error  2021-05-04T06:55:11Z 'elementType' => 'craft\\elements\\Entry'
web_php_error  2021-05-04T06:55:11Z 'sourceId' => '19741'
web_php_error  2021-05-04T06:55:11Z '_ga' => 'GA1.2.1074172289.1615990675'
web_php_error  2021-05-04T06:55:11Z 'draftId' => '210'
web_php_error  2021-05-04T06:55:11Z 'revisionId' => ''
web_php_error  2021-05-04T06:55:11Z ]
web_php_error  2021-05-04T06:55:11Z  
web_php_error  2021-05-04T06:55:11Z $_FILES = []
web_php_error  2021-05-04T06:55:11Z  
web_php_error  2021-05-04T06:55:11Z $_COOKIE = [
web_php_error  2021-05-04T06:55:11Z '1031b8c41dfff97a311a7ac99863bdc5__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
web_php_error  2021-05-04T06:55:11Z '_hjid' => '9c2e9077-6414-4c98-b14a-25786f1c11e4'
web_php_error  2021-05-04T06:55:11Z '1031b8c41dfff97a311a7ac99863bdc5_username' => '18e4e07de0d348fcf0f4a669b3fae2800ba128e39b70dc87f845807cf08344b0a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_username\";i:1;s:27:\"admin@functionandform.co.uk\";}'
web_php_error  2021-05-04T06:55:11Z 'form_posted_3' => '1616004784'
web_php_error  2021-05-04T06:55:11Z '__cfduid' => 'd28bd7b147c79998201b2be7c52cfbbc81618911197'
web_php_error  2021-05-04T06:55:11Z 'CRAFT_CSRF_TOKEN' => '•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
web_php_error  2021-05-04T06:55:11Z 'CraftSessionId' => '8204e469aedee22868179afc52d4c85b'
web_php_error  2021-05-04T06:55:11Z '1031b8c41dfff97a311a7ac99863bdc5_identity' => 'd33d9bfb09853f59d354270418e687e5cfd668ad448d73c11c47742cd7cf18b4a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_identity\";i:1;s:250:\"[1,\"[\\\"jrSbep0TAoU9U6welbEgV7R56Op1UXaaWysNUU4_DvYqhxVZWYjd1sPgfPkMNnr7lghgmCw2Il_LDzwvP1VefH77zRKljuzSLJhF\\\",null,\\\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36\\\"]\",1209600]\";}'
web_php_error  2021-05-04T06:55:11Z ]
web_php_error  2021-05-04T06:55:11Z  
web_php_error  2021-05-04T06:55:11Z $_SESSION = [
web_php_error  2021-05-04T06:55:11Z 'bd62416aa8538ede709019a5e113eea5__flash' => []
```

Does this help?

**Comment by brandonkelly** [comment]
@toddpadwick Any chance we can get access to the box and control panel? If so please send credentials over to support@craftcms.com.

**Comment by toddpadwick** [comment]
Hi @brandonkelly  I sent access via email

**Comment by toddpadwick** [comment]
Hi @brandonkelly  i've activated the account so you should be able to use the forgot password link now for thewriter.com/admin. I had trouble creating the activate account link - it kept returning an internal server error. haven't had time to check logs yet.

**Comment by brandonkelly** [comment]
@toddpadwick Alright I’ve logged in. Which section + site can I reproduce this with?

**Comment by toddpadwick** [comment]
Hi @brandonkelly  the client first noticed the issue with the **Whitepapers** section. But I have experienced it with other channel entries too.

**Comment by brandonkelly** [comment]
@toddpadwick I’m seeing it inconsistently. Sometimes EN works, sometimes GB works. Seems to me like maybe your session data isn’t being saved/persisted correctly. If this is a load-balanced environment, you will need to make sure the session data is stored in a central place – [Configuring Craft for Load Balanced Environments](https://craftcms.com/knowledge-base/configuring-load-balanced-environments).

**Comment by webrgp** [comment]
@brandonkelly I found a very similar error while working on a headless craft + gatsby locally. Here is the setup:

- Craft is running on Nitro 2.0.8, with (http://headless-craft.test)
- Gatsby is running on http://localhost:8000

Here is the config:

- baseUrl: http://localhost:8000
- baseCpUrl: http://headless-craft.test
- headlessMode: true

The preview target is hitting a client-only route in gatsby, with uid and section:

`live-preview/?uid={sourceUid}&section={section.handle}`

That route in turn queries Craft GraphQL API with the proper tokens:

`http://headless-craft.test/api?section=blog&uid=f5db6077-a916-435e-8eca-1955b20b0b24&x-craft-live-preview=EPir2chqht`

Live preview is working when the entry is in "Current". It's when I make changes that I get:

```
2021-09-24 06:36:21 [-][1][-][trace][craft\web\Application::_processActionRequest] Route requested: 'preview/create-token'
2021-09-24 06:36:21 [-][1][-][trace][yii\base\Controller::runAction] Route to run: preview/create-token
2021-09-24 06:36:21 [-][1][-][trace][yii\base\InlineAction::runWithParams] Running action: craft\controllers\PreviewController::actionCreateToken()
2021-09-24 06:36:21 [-][1][-][error][yii\web\HttpException:403] yii\web\ForbiddenHttpException: User is not authorized to perform this action in /app/vendor/craftcms/cms/src/web/Controller.php:349
```

A quick way to reproduce is to have Craft running on Nitro with `baseUrl` running in another domain.

**Comment by brandonkelly** [comment]
> That route in turn queries Craft GraphQL API with the proper tokens:
> 
> `http://headless-craft.test/api?section=blog&uid=f5db6077-a916-435e-8eca-1955b20b0b24&x-craft-live-preview=EPir2chqht`

Not seeing a `token` param in there, which is the important one. `x-craft-live-preview` is more just for cache busting and aiding `Craft::$app->request->getIsPreview()`.
