### ISSUE TITLE
Migration error from 3.4.30 to 3.5.0

### ISSUE THREAD

**Issue by krizzzly** [craftcms/cms#7869]
### Description

This is the dump.
```m200606_231117_migration_tracks.php``` is actually clearing NULL values in LINE 48. but maybe its not working.

```
Yii Migration Tool (based on Yii v2.0.36)

    > add column enabled boolean NOT NULL DEFAULT TRUE AFTER `primary` to table {{%sites}} ... done (time: 0.152s)
    > delete from {{%templatecaches}} ... done (time: 1.355s)
    > add column track string AFTER `id` to table {{%migrations}} ... done (time: 0.134s)
    > update in {{%migrations}} ... done (time: 0.016s)
    > update in {{%migrations}} ... done (time: 0.000s)
    > update in {{%migrations}} ... done (time: 0.009s)
    > update in {{%migrations}} ... done (time: 0.004s)
    > update in {{%migrations}} ... done (time: 0.000s)
    > update in {{%migrations}} ... done (time: 0.000s)
    > update in {{%migrations}} ... done (time: 0.000s)
    > update in {{%migrations}} ... done (time: 0.000s)
    > update in {{%migrations}} ... done (time: 0.009s)
    > update in {{%migrations}} ... done (time: 0.000s)
    > update in {{%migrations}} ... done (time: 0.005s)
    > update in {{%migrations}} ... done (time: 0.000s)
    > update in {{%migrations}} ... done (time: 0.000s)
    > update in {{%migrations}} ... done (time: 0.000s)
    > update in {{%migrations}} ... done (time: 0.004s)
    > update in {{%migrations}} ... done (time: 0.004s)
    > update in {{%migrations}} ... done (time: 0.003s)
    > update in {{%migrations}} ... done (time: 0.003s)
    > update in {{%migrations}} ... done (time: 0.000s)
    > alter column track in table {{%migrations}} to string NOT NULL ...Exception: SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value
The SQL being executed was: ALTER TABLE `k4_migrations` CHANGE `track` `track` varchar(255) NOT NULL (/home/test/domains/xyz/vendor/yiisoft/yii2/db/Schema.php:677)
#0 /home/test/domains/xyz/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException()
#1 /home/test/domains/xyz/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute()
#2 /home/test/domains/xyz/vendor/yiisoft/yii2/db/Migration.php(420): yii\db\Command->execute()
#3 /home/test/domains/xyz/vendor/craftcms/cms/src/migrations/m200606_231117_migration_tracks.php(53): yii\db\Migration->alterColumn()
#4 /home/test/domains/xyz/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m200606_231117_migration_tracks->safeUp()
#5 /home/test/domains/xyz/vendor/craftcms/cms/src/db/MigrationManager.php(228): craft\db\Migration->up()
#6 /home/test/domains/xyz/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp()
#7 /home/test/domains/xyz/vendor/craftcms/cms/src/services/Updates.php(220): craft\db\MigrationManager->up()
#8 /home/test/domains/xyz/vendor/craftcms/cms/src/console/controllers/MigrateController.php(328): craft\services\Updates->runMigrations()
#9 [internal function]: craft\console\controllers\MigrateController->actionAll()
#10 /home/test/domains/xyz/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#11 /home/test/domains/xyz/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#12 /home/test/domains/xyz/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction()
#13 /home/test/domains/xyz/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#14 /home/test/domains/xyz/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#15 /home/test/domains/xyz/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction()
#16 /home/test/domains/xyz/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#17 /home/test/domains/xyz/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#18 /home/test/domains/xyz/craft(22): yii\base\Application->run()
#19 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Craft CMS.'

```

### Steps to reproduce

1. $ /usr/bin/php7.4 craft update craft:3.5.0

### Additional info

- Craft version: Craft Pro 3.4.30
- PHP version: 7.4
- Database driver & version: Mysql 8.0.23
- Plugins & versions:

**Comment by brandonkelly** [comment]
This has been fixed in Craft 3.6. If you restore your 3.4 database backup and then go straight to 3.6.12.1, the migration should complete successfully.
