### ISSUE TITLE
SQL Error when previewing entries in Admin Panel

### ISSUE THREAD

**Issue by peimansh** [craftcms/cms#7886]
### Description
On Craft 3.6.12 we had a SQL error which prevented us from even opening entries.
But I saw that it is fixed in 3.6.13. So we installed 3.6.13 and we are now able to open and edit entries but when previewing the entries, we're getting the same SQL error we got before when trying to open/edit entries

### Additional info

- Craft version: 3.6.13
- PHP version: 7.4.18
- Database driver & version: Pgsql 11.10

**Comment by peimansh** [comment]
![Screenshot 2021-05-05 at 10 29 12](https://user-images.githubusercontent.com/32059257/117114978-c65de100-ad8c-11eb-8caa-bf9fe9116f5a.png)

**Comment by peimansh** [comment]
It's weird. Neither preview nor the entry link are working
![Screenshot 2021-05-05 at 12 25 12](https://user-images.githubusercontent.com/32059257/117127942-0d53d280-ad9d-11eb-81ea-b2606fddf609.png)

**Comment by brandonkelly** [comment]
Can you search for that error in your logs (`craft/storage/logs/`) and paste the full stack trace that follows it?

**Comment by peimansh** [comment]
I have already sent it in the conversation with Support.
But will sure paste it here too:


This is the stack trace in 3.6.12 getting the error when trying to open the entry for edit in CP:

```
PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 3: WHERE ("elementId"=$1) AND ("enabled"=$2)
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. in /var/www/vendor/yiisoft/yii2/db/Command.php:1299
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(1299): PDOStatement->execute()
#1 /var/www/vendor/yiisoft/yii2/db/Command.php(1165): yii\db\Command->internalExecute('SELECT "siteId"...')
#2 /var/www/vendor/yiisoft/yii2/db/Command.php(450): yii\db\Command->queryInternal('fetchAll', 7)
#3 /var/www/vendor/yiisoft/yii2/db/Query.php(320): yii\db\Command->queryColumn()
#4 /var/www/vendor/craftcms/cms/src/db/Query.php(202): yii\db\Query->column(NULL)
#5 /var/www/vendor/craftcms/cms/src/services/Elements.php(690): craft\db\Query->column()
#6 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1507): craft\services\Elements->getEnabledSiteIdsForElement(596565)
#7 /var/www/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\Elements), 'getEnabledSiteI...', Array, 'method', false, false)
#8 /var/www/storage/runtime/compiled_templates/e8/e8b0f5b7d2ca212f1dc340b1c6cfd9b73984fd452eab3c3899963fee9d9bc5de.php(174): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\Elements), 'getEnabledSiteI...', Array, 'method')
#9 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c2844a90785b67111a4214b7d43a8b25b35b32c7fd1a559ba2508e9b62faec9d->doDisplay(Array, Array)
#10 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /var/www/storage/runtime/compiled_templates/db/dba7b7503c5144557016ad19173e7417f1ad98476a409cec040acb7526699f75.php(356): Twig\Template->display(Array)
#12 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_0326e4bebd2acda5fef8da67e0c27cbeec7b60fe4dea18ae5c7939a60af521e5->block_contextMenu(Array, Array)
#13 /var/www/storage/runtime/compiled_templates/db/dba7b7503c5144557016ad19173e7417f1ad98476a409cec040acb7526699f75.php(331): Twig\Template->displayBlock('contextMenu', Array, Array)
#14 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_0326e4bebd2acda5fef8da67e0c27cbeec7b60fe4dea18ae5c7939a60af521e5->block_header(Array, Array)
#15 /var/www/storage/runtime/compiled_templates/de/de354e8c9afcc84d1d4b9b20c39f79a076f4134673df8c52cddcae6485ffde39.php(279): Twig\Template->displayBlock('header', Array, Array)
#16 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_29b212535390e630353200f1553590b96e04be646d99ff662c013c046e590250->block_body(Array, Array)
#17 /var/www/storage/runtime/compiled_templates/e3/e3b3572baea82d7affd3724beb65ded4713b1ed54ab2befeca7dc72cbc11a521.php(90): Twig\Template->displayBlock('body', Array, Array)
#18 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_73af18171a4143f2eb22f8836ce52d89843c7241267c4fc8b39baee6b567020f->doDisplay(Array, Array)
#19 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /var/www/storage/runtime/compiled_templates/05/055e5529a25221540c325292030390431e2a05db8aafe2bc1d79e580469affe1.php(56): Twig\Template->display(Array, Array)
#21 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c95f8aedd8ebe5558b0470c69449bdaec5f012b2efa303e96ceef99dfb624cdc->doDisplay(Array, Array)
#22 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /var/www/storage/runtime/compiled_templates/de/de354e8c9afcc84d1d4b9b20c39f79a076f4134673df8c52cddcae6485ffde39.php(158): Twig\Template->display(Array, Array)
#24 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_29b212535390e630353200f1553590b96e04be646d99ff662c013c046e590250->doDisplay(Array, Array)
#25 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /var/www/storage/runtime/compiled_templates/db/dba7b7503c5144557016ad19173e7417f1ad98476a409cec040acb7526699f75.php(314): Twig\Template->display(Array, Array)
#27 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_0326e4bebd2acda5fef8da67e0c27cbeec7b60fe4dea18ae5c7939a60af521e5->doDisplay(Array, Array)
#28 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /var/www/storage/runtime/compiled_templates/2a/2a65e23acc022406bb10418905561a5580451fa336f426f0ea4716c1293a21da.php(124): Twig\Template->display(Array, Array)
#30 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_58e98cbad7e351720fca71ad27147f3504d1703ae1b39de9a8680e2c689ee5ed->doDisplay(Array, Array)
#31 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#32 /var/www/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#33 /var/www/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#34 /var/www/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#35 /var/www/vendor/craftcms/cms/src/web/View.php(390): Twig\Environment->render('entries/_edit', Array)
#36 /var/www/vendor/craftcms/cms/src/web/View.php(451): craft\web\View->renderTemplate('entries/_edit', Array)
#37 /var/www/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('entries/_edit', Array, 'cp')
#38 /var/www/vendor/craftcms/cms/src/controllers/EntriesController.php(250): craft\web\Controller->renderTemplate('entries/_edit', Array)
#39 [internal function]: craft\controllers\EntriesController->actionEditEntry(Object(craft\models\Section), 596565, NULL, NULL, Object(craft\models\Site), Object(craft\elements\Entry))
#40 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#41 /var/www/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#42 /var/www/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-entry', Array)
#43 /var/www/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-entry', Array)
#44 /var/www/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('entries/edit-en...', Array)
#45 /var/www/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('entries/edit-en...', Array)
#46 /var/www/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#47 /var/www/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#48 /var/www/web/index.php(16): yii\base\Application->run()
#49 {main}
 
Next yii\db\Exception: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 3: WHERE ("elementId"=$1) AND ("enabled"=$2)
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
The SQL being executed was: SELECT "siteId"
FROM "craft_elements_sites"
WHERE ("elementId"=596565) AND ("enabled"=1) in /var/www/vendor/yiisoft/yii2/db/Schema.php:678
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'SELECT "siteId"...')
#1 /var/www/vendor/yiisoft/yii2/db/Command.php(1165): yii\db\Command->internalExecute('SELECT "siteId"...')
#2 /var/www/vendor/yiisoft/yii2/db/Command.php(450): yii\db\Command->queryInternal('fetchAll', 7)
#3 /var/www/vendor/yiisoft/yii2/db/Query.php(320): yii\db\Command->queryColumn()
#4 /var/www/vendor/craftcms/cms/src/db/Query.php(202): yii\db\Query->column(NULL)
#5 /var/www/vendor/craftcms/cms/src/services/Elements.php(690): craft\db\Query->column()
#6 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1507): craft\services\Elements->getEnabledSiteIdsForElement(596565)
#7 /var/www/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\Elements), 'getEnabledSiteI...', Array, 'method', false, false)
#8 /var/www/storage/runtime/compiled_templates/e8/e8b0f5b7d2ca212f1dc340b1c6cfd9b73984fd452eab3c3899963fee9d9bc5de.php(174): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\Elements), 'getEnabledSiteI...', Array, 'method')
#9 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c2844a90785b67111a4214b7d43a8b25b35b32c7fd1a559ba2508e9b62faec9d->doDisplay(Array, Array)
#10 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /var/www/storage/runtime/compiled_templates/db/dba7b7503c5144557016ad19173e7417f1ad98476a409cec040acb7526699f75.php(356): Twig\Template->display(Array)
#12 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_0326e4bebd2acda5fef8da67e0c27cbeec7b60fe4dea18ae5c7939a60af521e5->block_contextMenu(Array, Array)
#13 /var/www/storage/runtime/compiled_templates/db/dba7b7503c5144557016ad19173e7417f1ad98476a409cec040acb7526699f75.php(331): Twig\Template->displayBlock('contextMenu', Array, Array)
#14 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_0326e4bebd2acda5fef8da67e0c27cbeec7b60fe4dea18ae5c7939a60af521e5->block_header(Array, Array)
#15 /var/www/storage/runtime/compiled_templates/de/de354e8c9afcc84d1d4b9b20c39f79a076f4134673df8c52cddcae6485ffde39.php(279): Twig\Template->displayBlock('header', Array, Array)
#16 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_29b212535390e630353200f1553590b96e04be646d99ff662c013c046e590250->block_body(Array, Array)
#17 /var/www/storage/runtime/compiled_templates/e3/e3b3572baea82d7affd3724beb65ded4713b1ed54ab2befeca7dc72cbc11a521.php(90): Twig\Template->displayBlock('body', Array, Array)
#18 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_73af18171a4143f2eb22f8836ce52d89843c7241267c4fc8b39baee6b567020f->doDisplay(Array, Array)
#19 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /var/www/storage/runtime/compiled_templates/05/055e5529a25221540c325292030390431e2a05db8aafe2bc1d79e580469affe1.php(56): Twig\Template->display(Array, Array)
#21 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c95f8aedd8ebe5558b0470c69449bdaec5f012b2efa303e96ceef99dfb624cdc->doDisplay(Array, Array)
#22 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /var/www/storage/runtime/compiled_templates/de/de354e8c9afcc84d1d4b9b20c39f79a076f4134673df8c52cddcae6485ffde39.php(158): Twig\Template->display(Array, Array)
#24 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_29b212535390e630353200f1553590b96e04be646d99ff662c013c046e590250->doDisplay(Array, Array)
#25 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /var/www/storage/runtime/compiled_templates/db/dba7b7503c5144557016ad19173e7417f1ad98476a409cec040acb7526699f75.php(314): Twig\Template->display(Array, Array)
#27 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_0326e4bebd2acda5fef8da67e0c27cbeec7b60fe4dea18ae5c7939a60af521e5->doDisplay(Array, Array)
#28 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /var/www/storage/runtime/compiled_templates/2a/2a65e23acc022406bb10418905561a5580451fa336f426f0ea4716c1293a21da.php(124): Twig\Template->display(Array, Array)
#30 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_58e98cbad7e351720fca71ad27147f3504d1703ae1b39de9a8680e2c689ee5ed->doDisplay(Array, Array)
#31 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#32 /var/www/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#33 /var/www/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#34 /var/www/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#35 /var/www/vendor/craftcms/cms/src/web/View.php(390): Twig\Environment->render('entries/_edit', Array)
#36 /var/www/vendor/craftcms/cms/src/web/View.php(451): craft\web\View->renderTemplate('entries/_edit', Array)
#37 /var/www/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('entries/_edit', Array, 'cp')
#38 /var/www/vendor/craftcms/cms/src/controllers/EntriesController.php(250): craft\web\Controller->renderTemplate('entries/_edit', Array)
#39 [internal function]: craft\controllers\EntriesController->actionEditEntry(Object(craft\models\Section), 596565, NULL, NULL, Object(craft\models\Site), Object(craft\elements\Entry))
#40 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#41 /var/www/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#42 /var/www/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-entry', Array)
#43 /var/www/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-entry', Array)
#44 /var/www/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('entries/edit-en...', Array)
#45 /var/www/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('entries/edit-en...', Array)
#46 /var/www/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#47 /var/www/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#48 /var/www/web/index.php(16): yii\base\Application->run()
#49 {main}
Additional Information:
Array
(
    [0] => 42883
    [1] => 7
    [2] => ERROR:  operator does not exist: boolean = integer
LINE 3: WHERE ("elementId"=$1) AND ("enabled"=$2)
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
)
```


And this is the stack trace in 3.6.13 when trying to open the entry URL /and/or preview:

```
PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character varying = integer
LINE 3: ...ndle" IS NULL) OR ("handle" IS NULL) OR ("handle" IN ($1, $2...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. in /var/www/vendor/yiisoft/yii2/db/Command.php:1299
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(1299): PDOStatement->execute()
#1 /var/www/vendor/yiisoft/yii2/db/Command.php(1165): yii\db\Command->internalExecute('SELECT "id"\nFRO...')
#2 /var/www/vendor/yiisoft/yii2/db/Command.php(450): yii\db\Command->queryInternal('fetchAll', 7)
#3 /var/www/vendor/yiisoft/yii2/db/Query.php(320): yii\db\Command->queryColumn()
#4 /var/www/vendor/craftcms/cms/src/db/Query.php(202): yii\db\Query->column(NULL)
#5 /var/www/vendor/craftcms/cms/src/elements/db/EntryQuery.php(309): craft\db\Query->column()
#6 /var/www/vendor/craftcms/cms/src/elements/db/EntryQuery.php(219): craft\elements\db\EntryQuery->section(Object(craft\models\EntryType))
#7 /var/www/vendor/yiisoft/yii2/BaseYii.php(558): craft\elements\db\EntryQuery->__set('section', Object(craft\models\EntryType))
#8 /var/www/vendor/craftcms/cms/src/web/twig/variables/CraftVariable.php(243): yii\BaseYii::configure(Object(craft\elements\db\EntryQuery), Array)
#9 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1507): craft\web\twig\variables\CraftVariable->entries(Array)
#10 /var/www/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\twig\variables\CraftVariable), 'entries', Array, 'method', false, false)
#11 /var/www/storage/runtime/compiled_templates/3b/3badea26c19b1f93d42c033bb9f1c19c66a157c25cb247aa7439d716cd7e983b.php(102): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\twig\variables\CraftVariable), 'entries', Array, 'method')
#12 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1110): __TwigTemplate_6e99f73693e309c999f92242e2cfd92f4bc45eb27750913261785a3a639b63c3->macro_getRelatedContent(Object(craft\elements\Entry))
#13 /var/www/storage/runtime/compiled_templates/2f/2f7c78c4abe61244eea84275fabc71f719b266783d270184636ceda986f0b0ea.php(94): twig_call_macro(Object(__TwigTemplate_6e99f73693e309c999f92242e2cfd92f4bc45eb27750913261785a3a639b63c3), 'macro_getRelate...', Array, 24, Array, Object(Twig\Source))
#14 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_4b2c428a932a4f34ca7a6cb7866c5b449af06306af7b0f03841b9d0536417ac8->block_content(Array, Array)
#15 /var/www/storage/runtime/compiled_templates/b7/b75dc0264e7e3fcf15867c440d644e7faf00707ee485f562a5c7a749ebc72eb9.php(133): Twig\Template->displayBlock('content', Array, Array)
#16 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_cd933664fdc0c76598e1e2c57fc597b699832665292a90d5e6d690d26e81e56e->doDisplay(Array, Array)
#17 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /var/www/storage/runtime/compiled_templates/2f/2f7c78c4abe61244eea84275fabc71f719b266783d270184636ceda986f0b0ea.php(54): Twig\Template->display(Array, Array)
#19 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_4b2c428a932a4f34ca7a6cb7866c5b449af06306af7b0f03841b9d0536417ac8->doDisplay(Array, Array)
#20 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#22 /var/www/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#23 /var/www/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#24 /var/www/vendor/craftcms/cms/src/web/View.php(390): Twig\Environment->render('routes/news/art...', Array)
#25 /var/www/vendor/craftcms/cms/src/web/View.php(451): craft\web\View->renderTemplate('routes/news/art...', Array)
#26 /var/www/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('routes/news/art...', Array, 'site')
#27 /var/www/vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate('routes/news/art...', Array)
#28 [internal function]: craft\controllers\TemplatesController->actionRender('routes/news/art...', Array)
#29 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /var/www/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#31 /var/www/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('render', Array)
#32 /var/www/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('render', Array)
#33 /var/www/vendor/craftcms/cms/src/web/Application.php(279): yii\base\Module->runAction('templates/rende...', Array)
#34 /var/www/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('templates/rende...', Array)
#35 /var/www/vendor/craftcms/cms/src/web/Application.php(264): yii\web\Application->handleRequest(Object(craft\web\Request))
#36 /var/www/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#37 /var/www/web/index.php(16): yii\base\Application->run()
#38 {main}
 
Next yii\db\Exception: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character varying = integer
LINE 3: ...ndle" IS NULL) OR ("handle" IS NULL) OR ("handle" IN ($1, $2...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
The SQL being executed was: SELECT "id"
FROM "craft_sections"
WHERE ("handle" IS NULL) OR ("handle" IS NULL) OR ("handle" IN (15, 10, 112, 'News Article', 'newsArticle', 1, TRUE, '', 'b50cc764-3357-4319-9490-0684a651a170')) in /var/www/vendor/yiisoft/yii2/db/Schema.php:678
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'SELECT "id"\nFRO...')
#1 /var/www/vendor/yiisoft/yii2/db/Command.php(1165): yii\db\Command->internalExecute('SELECT "id"\nFRO...')
#2 /var/www/vendor/yiisoft/yii2/db/Command.php(450): yii\db\Command->queryInternal('fetchAll', 7)
#3 /var/www/vendor/yiisoft/yii2/db/Query.php(320): yii\db\Command->queryColumn()
#4 /var/www/vendor/craftcms/cms/src/db/Query.php(202): yii\db\Query->column(NULL)
#5 /var/www/vendor/craftcms/cms/src/elements/db/EntryQuery.php(309): craft\db\Query->column()
#6 /var/www/vendor/craftcms/cms/src/elements/db/EntryQuery.php(219): craft\elements\db\EntryQuery->section(Object(craft\models\EntryType))
#7 /var/www/vendor/yiisoft/yii2/BaseYii.php(558): craft\elements\db\EntryQuery->__set('section', Object(craft\models\EntryType))
#8 /var/www/vendor/craftcms/cms/src/web/twig/variables/CraftVariable.php(243): yii\BaseYii::configure(Object(craft\elements\db\EntryQuery), Array)
#9 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1507): craft\web\twig\variables\CraftVariable->entries(Array)
#10 /var/www/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\twig\variables\CraftVariable), 'entries', Array, 'method', false, false)
#11 /var/www/storage/runtime/compiled_templates/3b/3badea26c19b1f93d42c033bb9f1c19c66a157c25cb247aa7439d716cd7e983b.php(102): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\twig\variables\CraftVariable), 'entries', Array, 'method')
#12 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1110): __TwigTemplate_6e99f73693e309c999f92242e2cfd92f4bc45eb27750913261785a3a639b63c3->macro_getRelatedContent(Object(craft\elements\Entry))
#13 /var/www/storage/runtime/compiled_templates/2f/2f7c78c4abe61244eea84275fabc71f719b266783d270184636ceda986f0b0ea.php(94): twig_call_macro(Object(__TwigTemplate_6e99f73693e309c999f92242e2cfd92f4bc45eb27750913261785a3a639b63c3), 'macro_getRelate...', Array, 24, Array, Object(Twig\Source))
#14 /var/www/vendor/twig/twig/src/Template.php(182): __TwigTemplate_4b2c428a932a4f34ca7a6cb7866c5b449af06306af7b0f03841b9d0536417ac8->block_content(Array, Array)
#15 /var/www/storage/runtime/compiled_templates/b7/b75dc0264e7e3fcf15867c440d644e7faf00707ee485f562a5c7a749ebc72eb9.php(133): Twig\Template->displayBlock('content', Array, Array)
#16 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_cd933664fdc0c76598e1e2c57fc597b699832665292a90d5e6d690d26e81e56e->doDisplay(Array, Array)
#17 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /var/www/storage/runtime/compiled_templates/2f/2f7c78c4abe61244eea84275fabc71f719b266783d270184636ceda986f0b0ea.php(54): Twig\Template->display(Array, Array)
#19 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_4b2c428a932a4f34ca7a6cb7866c5b449af06306af7b0f03841b9d0536417ac8->doDisplay(Array, Array)
#20 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#22 /var/www/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#23 /var/www/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#24 /var/www/vendor/craftcms/cms/src/web/View.php(390): Twig\Environment->render('routes/news/art...', Array)
#25 /var/www/vendor/craftcms/cms/src/web/View.php(451): craft\web\View->renderTemplate('routes/news/art...', Array)
#26 /var/www/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('routes/news/art...', Array, 'site')
#27 /var/www/vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate('routes/news/art...', Array)
#28 [internal function]: craft\controllers\TemplatesController->actionRender('routes/news/art...', Array)
#29 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /var/www/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#31 /var/www/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('render', Array)
#32 /var/www/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('render', Array)
#33 /var/www/vendor/craftcms/cms/src/web/Application.php(279): yii\base\Module->runAction('templates/rende...', Array)
#34 /var/www/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('templates/rende...', Array)
#35 /var/www/vendor/craftcms/cms/src/web/Application.php(264): yii\web\Application->handleRequest(Object(craft\web\Request))
#36 /var/www/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#37 /var/www/web/index.php(16): yii\base\Application->run()
#38 {main}
Additional Information:
Array
(
    [0] => 42883
    [1] => 7
    [2] => ERROR:  operator does not exist: character varying = integer
LINE 3: ...ndle" IS NULL) OR ("handle" IS NULL) OR ("handle" IN ($1, $2...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
)
```

**Comment by brandonkelly** [comment]
Strange. Can you send your 3.6.12 database backup + Composer files over to support@craftcms.com so we can look into it?

**Comment by peimansh** [comment]
I think we can close the issue, as 3.6.13 has solved it actually. Even if the first time after I got it running on 3.6.13 it didn't work, but I cannot reproduce it any more!
