### ISSUE TITLE
Getting sites via SiteGroup record results in SQL error

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#7914]
### Description
Given a site group name, and then attempting to fetch the sites contained within gives an SQL error. This is both for the magic sites property or via the `getSites()` query builder method;

`SiteGroup::findOne(['name' => $groupName])->sites;`
`SiteGroup::findOne(['name' => $groupName])->getSites()->all();`

This results in the following SQL error:

```
Exception 'yii\db\Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'siteId' in 'where clause'
The SQL being executed was: SELECT *
FROM `sites`
WHERE (`sites`.`dateDeleted` IS NULL) AND (`siteId`=2)'

in /var/www/html/craft/vendor/yiisoft/yii2/db/Schema.php:678

Error Info:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'siteId' in 'where clause'
)

Caused by: Exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'siteId' in 'where clause''
```

### Additional info

- Craft version: 3.6.12.1
- PHP version: 7.4
- Database driver & version: MySQL 8
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Just released Craft 3.6.14 with a fix for this. Thanks for reporting!

**Comment by FreekVR** [comment]
Thanks! I was just playing around with this again, but still ran into a similar issue, this time using a site record already loaded, though I figure it's pretty much the same scenario as before:

`$siteRecord->group->sites`

This gives me a similar error on 3.6.14:

```
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: craft\records\Site::siteId'

in /var/www/html/craft/vendor/yiisoft/yii2/base/Component.php:155

Stack trace:
#0 /var/www/html/craft/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('siteId')
#1 /var/www/html/craft/vendor/yiisoft/yii2/base/Model.php(1027): yii\db\BaseActiveRecord->__get('siteId')
#2 /var/www/html/craft/vendor/yiisoft/yii2/db/ActiveRelationTrait.php(526): yii\base\Model->offsetGet('siteId')
#3 /var/www/html/craft/vendor/yiisoft/yii2/db/ActiveQuery.php(196): yii\db\ActiveQuery->filterByModels(Array)
#4 /var/www/html/craft/vendor/yiisoft/yii2/db/QueryBuilder.php(227): yii\db\ActiveQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#5 /var/www/html/craft/vendor/yiisoft/yii2/db/ActiveQuery.php(328): yii\db\QueryBuilder->build(Object(craft\db\ActiveQuery))
#6 /var/www/html/craft/vendor/yiisoft/yii2/db/Query.php(249): yii\db\ActiveQuery->createCommand(Object(craft\db\Connection))
#7 /var/www/html/craft/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
```

**Comment by brandonkelly** [comment]
Thanks – fixed that as well, for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.15 is out now with the additional fix.
