### ISSUE TITLE
[3.7.0-beta.5] Structure ordering lost, entries push to bottom of list after draft is created and saved

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#9123]
### Description
After saving entries in a structure it seems like they're being push to the bottom of the list.

### Steps to reproduce

1. Find an element at the bottom of the list in a structure
2. Move it up the list, refresh and see it remain in place
3. Edit that entry
4. See it pushed to the bottom of the list

https://user-images.githubusercontent.com/39560/124495282-d5263b80-ddaf-11eb-9d97-f679fd2116b7.mov

### Additional info

- Craft version: 3.7.0-beta.5
- PHP version: 8.0.2

**Comment by nickdunn** [comment]
I've found a way to recreate this reliably.

When I go to edit the entry (per the video) and I edit a field... if I wait for the draft to be saved (i.e. the spinner appears and becomes a tick) and then save the entry, the order is lost. However if I edit a field and then immediately hit cmd+S to trigger a save before the spinner has a chance to appear, the order is maintained.

So it looks like it's something to do with saving a new draft that's losing the order.

Not sure if it's related, but I'm sometimes seeing this in my console when cmd+S during this testing:

<img width="999" alt="Screenshot 2021-07-06 at 16 55 28" src="https://user-images.githubusercontent.com/39560/124632024-dae95300-de7b-11eb-8580-b313a17a586d.png">

**Comment by nickdunn** [comment]
I've also seen this happen a few times... but this has been happening since I first installed Craft so I think a red herring. But thought worth mentioning it as it's related to the table that stores order. Sometimes, very rarely (maybe 10 times ever) the table locks entirely and I have to restart MySQL.

```
php_1     | 2021-07-06 16:48:34 [172.18.0.1][7516][e2aa0a86002c33e94e796cd740905444][error][yii\db\Exception] PDOException: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction in /var/www/craft/vendor/yiisoft/yii2/db/Command.php:1302
php_1     | Stack trace:
php_1     | #0 /var/www/craft/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
php_1     | #1 /var/www/craft/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('UPDATE `structu...')
php_1     | #2 /var/www/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(332): yii\db\Command->execute()
php_1     | #3 /var/www/craft/vendor/creocoder/yii2-nested-sets/src/NestedSetsBehavior.php(663): yii\db\ActiveRecord::updateAll(Array, Array)
php_1     | #4 /var/www/craft/vendor/creocoder/yii2-nested-sets/src/NestedSetsBehavior.php(394): creocoder\nestedsets\NestedSetsBehavior->shiftLeftRightAttribute(1602, 2)
php_1     | #5 /var/www/craft/vendor/creocoder/yii2-nested-sets/src/NestedSetsBehavior.php(350): creocoder\nestedsets\NestedSetsBehavior->beforeInsertNode(1602, 0)
php_1     | #6 [internal function]: creocoder\nestedsets\NestedSetsBehavior->beforeInsert(Object(yii\base\ModelEvent))
php_1     | #7 /var/www/craft/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(yii\base\ModelEvent))
php_1     | #8 /var/www/craft/vendor/yiisoft/yii2/db/BaseActiveRecord.php(974): yii\base\Component->trigger('beforeInsert', Object(yii\base\ModelEvent))
php_1     | #9 /var/www/craft/vendor/craftcms/cms/src/db/ActiveRecord.php(85): yii\db\BaseActiveRecord->beforeSave(true)
php_1     | #10 /var/www/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(596): craft\db\ActiveRecord->beforeSave(true)
php_1     | #11 /var/www/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(571): yii\db\ActiveRecord->insertInternal(NULL)
php_1     | #12 /var/www/craft/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
php_1     | #13 /var/www/craft/vendor/creocoder/yii2-nested-sets/src/NestedSetsBehavior.php(147): yii\db\BaseActiveRecord->save(true, NULL)
php_1     | #14 [internal function]: creocoder\nestedsets\NestedSetsBehavior->insertAfter(Object(craft\records\StructureElement))
php_1     | #15 /var/www/craft/vendor/yiisoft/yii2/base/Component.php(298): call_user_func_array(Array, Array)
php_1     | #16 /var/www/craft/vendor/craftcms/cms/src/services/Structures.php(505): yii\base\Component->__call('insertAfter', Array)
php_1     | #17 /var/www/craft/vendor/craftcms/cms/src/services/Structures.php(398): craft\services\Structures->_doIt(3, Object(craft\elements\Entry), Object(craft\records\StructureElement), 'insertAfter', 'insert')
php_1     | #18 /var/www/craft/vendor/craftcms/cms/src/services/Elements.php(1216): craft\services\Structures->moveAfter(3, Object(craft\elements\Entry), Object(craft\elements\Entry), 'insert')
php_1     | #19 /var/www/craft/vendor/craftcms/cms/src/services/Revisions.php(167): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
php_1     | #20 /var/www/craft/vendor/craftcms/cms/src/elements/Entry.php(1655): craft\services\Revisions->createRevision(Object(craft\elements\Entry), 7516, '')
php_1     | #21 /var/www/craft/vendor/craftcms/cms/src/services/Elements.php(2673): craft\elements\Entry->afterPropagate(false)
php_1     | #22 /var/www/craft/vendor/craftcms/cms/src/services/Elements.php(773): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
php_1     | #23 /var/www/craft/vendor/craftcms/cms/src/controllers/EntriesController.php(379): craft\services\Elements->saveElement(Object(craft\elements\Entry))
php_1     | #24 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
php_1     | #25 /var/www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
php_1     | #26 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
php_1     | #27 /var/www/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save-entry', Array)
php_1     | #28 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('save-entry', Array)
php_1     | #29 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(271): yii\base\Module->runAction('entries/save-en...', Array)
php_1     | #30 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(574): craft\web\Application->runAction('entries/save-en...', Array)
php_1     | #31 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(250): craft\web\Application->_processActionRequest(Object(craft\web\Request))
php_1     | #32 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
php_1     | #33 /var/www/craft/web/index.php(22): yii\base\Application->run()
php_1     | #34 {main}
php_1     | 
php_1     | Next yii\db\Exception: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
php_1     | The SQL being executed was: UPDATE `structureelements` SET `lft`=`lft`+2, `dateUpdated`='2021-07-06 15:47:43' WHERE (`lft` >= 1602) AND (`root`=1) in /var/www/craft/vendor/yiisoft/yii2/db/Schema.php:678
php_1     | Stack trace:
php_1     | #0 /var/www/craft/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'UPDATE `structu...')
php_1     | #1 /var/www/craft/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('UPDATE `structu...')
php_1     | #2 /var/www/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(332): yii\db\Command->execute()
php_1     | #3 /var/www/craft/vendor/creocoder/yii2-nested-sets/src/NestedSetsBehavior.php(663): yii\db\ActiveRecord::updateAll(Array, Array)
php_1     | #4 /var/www/craft/vendor/creocoder/yii2-nested-sets/src/NestedSetsBehavior.php(394): creocoder\nestedsets\NestedSetsBehavior->shiftLeftRightAttribute(1602, 2)
php_1     | #5 /var/www/craft/vendor/creocoder/yii2-nested-sets/src/NestedSetsBehavior.php(350): creocoder\nestedsets\NestedSetsBehavior->beforeInsertNode(1602, 0)
php_1     | #6 [internal function]: creocoder\nestedsets\NestedSetsBehavior->beforeInsert(Object(yii\base\ModelEvent))
php_1     | #7 /var/www/craft/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(yii\base\ModelEvent))
php_1     | #8 /var/www/craft/vendor/yiisoft/yii2/db/BaseActiveRecord.php(974): yii\base\Component->trigger('beforeInsert', Object(yii\base\ModelEvent))
php_1     | #9 /var/www/craft/vendor/craftcms/cms/src/db/ActiveRecord.php(85): yii\db\BaseActiveRecord->beforeSave(true)
php_1     | #10 /var/www/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(596): craft\db\ActiveRecord->beforeSave(true)
php_1     | #11 /var/www/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(571): yii\db\ActiveRecord->insertInternal(NULL)
php_1     | #12 /var/www/craft/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
php_1     | #13 /var/www/craft/vendor/creocoder/yii2-nested-sets/src/NestedSetsBehavior.php(147): yii\db\BaseActiveRecord->save(true, NULL)
php_1     | #14 [internal function]: creocoder\nestedsets\NestedSetsBehavior->insertAfter(Object(craft\records\StructureElement))
php_1     | #15 /var/www/craft/vendor/yiisoft/yii2/base/Component.php(298): call_user_func_array(Array, Array)
php_1     | #16 /var/www/craft/vendor/craftcms/cms/src/services/Structures.php(505): yii\base\Component->__call('insertAfter', Array)
php_1     | #17 /var/www/craft/vendor/craftcms/cms/src/services/Structures.php(398): craft\services\Structures->_doIt(3, Object(craft\elements\Entry), Object(craft\records\StructureElement), 'insertAfter', 'insert')
php_1     | #18 /var/www/craft/vendor/craftcms/cms/src/services/Elements.php(1216): craft\services\Structures->moveAfter(3, Object(craft\elements\Entry), Object(craft\elements\Entry), 'insert')
php_1     | #19 /var/www/craft/vendor/craftcms/cms/src/services/Revisions.php(167): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
php_1     | #20 /var/www/craft/vendor/craftcms/cms/src/elements/Entry.php(1655): craft\services\Revisions->createRevision(Object(craft\elements\Entry), 7516, '')
php_1     | #21 /var/www/craft/vendor/craftcms/cms/src/services/Elements.php(2673): craft\elements\Entry->afterPropagate(false)
php_1     | #22 /var/www/craft/vendor/craftcms/cms/src/services/Elements.php(773): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
php_1     | #23 /var/www/craft/vendor/craftcms/cms/src/controllers/EntriesController.php(379): craft\services\Elements->saveElement(Object(craft\elements\Entry))
php_1     | #24 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
php_1     | #25 /var/www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
php_1     | #26 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
php_1     | #27 /var/www/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save-entry', Array)
php_1     | #28 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('save-entry', Array)
php_1     | #29 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(271): yii\base\Module->runAction('entries/save-en...', Array)
php_1     | #30 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(574): craft\web\Application->runAction('entries/save-en...', Array)
php_1     | #31 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(250): craft\web\Application->_processActionRequest(Object(craft\web\Request))
php_1     | #32 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
php_1     | #33 /var/www/craft/web/index.php(22): yii\base\Application->run()
php_1     | #34 {main}
php_1     | Additional Information:
php_1     | Array
php_1     | (
php_1     |     [0] => HY000
php_1     |     [1] => 1205
php_1     |     [2] => Lock wait timeout exceeded; try restarting transaction
php_1     | )
```

**Comment by nickdunn** [comment]
Maybe related to https://github.com/craftcms/cms/issues/9104

**Comment by brandonkelly** [comment]
Just got that fixed for the next release. Thanks for reporting!

**Comment by brandonkelly** [comment]
3.7.0-beta.6 is out now with that fix.
