### ISSUE TITLE
Setting unknown property: craft\fields\Matrix::propagationKeyFormat

### ISSUE THREAD

**Issue by brambeekman** [craftcms/cms#9146]
### Description

After I ran `composer update it gives me this error

### Steps to reproduce

1. Remove vendor en install again

### Log file 

```
2021-07-09 01:07:10 [-][-][k2v32980vk2mtcpbbb6o14dq5g][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: craft\fields\Matrix::propagationKeyFormat in /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/base/Component.php:210
Stack trace:
#0 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set()
#1 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure()
#2 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/fields/Matrix.php(154): yii\base\BaseObject->__construct()
#3 [internal function]: craft\fields\Matrix->__construct()
#4 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs()
#5 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build()
#6 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#7 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/helpers/Component.php(111): yii\BaseYii::createObject()
#8 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/services/Fields.php(580): craft\helpers\Component::createComponent()
#9 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/services/Fields.php(605): craft\services\Fields->createField()
#10 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/services/Fields.php(634): craft\services\Fields->_fields()
#11 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2089): craft\services\Fields->getAllFields()
#12 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1408): craft\elements\db\ElementQuery->customFields()
#13 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
#14 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
#15 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand()
#16 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one()
#17 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1562): craft\db\Query->one()
#18 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/elements/User.php(437): craft\elements\db\ElementQuery->one()
#19 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/web/User.php(700): craft\elements\User::findIdentity()
#20 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/web/User.php(522): yii\web\User->renewAuthStatus()
#21 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#22 /home/forge/genvdienstverlening.nl/vendor/verbb/knock-knock/src/KnockKnock.php(72): yii\web\User->getIdentity()
#23 [internal function]: verbb\knockknock\KnockKnock->verbb\knockknock\{closure}()
#24 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#25 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger()
#26 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/services/Plugins.php(279): yii\base\Component->trigger()
#27 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/base/ApplicationTrait.php(1442): craft\services\Plugins->loadPlugins()
#28 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/src/web/Application.php(93): craft\web\Application->_postInit()
#29 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#30 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct()
#31 [internal function]: yii\base\Application->__construct()
#32 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs()
#33 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build()
#34 /home/forge/genvdienstverlening.nl/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#35 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject()
#36 /home/forge/genvdienstverlening.nl/vendor/craftcms/cms/bootstrap/web.php(51): require('/home/forge/gen...')
#37 /home/forge/genvdienstverlening.nl/web/index.php(20): require('/home/forge/gen...')
#38 {main}
```

**Comment by brandonkelly** [comment]
`craft\fields\Matrix::$propagationKeyFormat` was added in Craft 3.7. So you must have updated this site to 3.7 Beta and then downgraded back to an earlier version.

You can see which version is currently installed by searching your `composer.lock` file for:

```
"name": "craftcms/cms"
```

**Comment by brambeekman** [comment]
> `craft\fields\Matrix::$propagationKeyFormat` was added in Craft 3.7. So you must have updated this site to 3.7 Beta and then downgraded back to an earlier version.
> 
> 
> 
> You can see which version is currently installed by searching your `composer.lock` file for:
> 
> 
> 
> ```
> 
> "name": "craftcms/cms"
> 
> ```

Yeah, I did... What's the best option to fix this and to stay on the 3.7 and not the beta?

**Comment by brandonkelly** [comment]
Make sure your `crafcms/cms` requirement in `composer.json` is set to `"^3.7.0-beta.1"` or higher, then run `composer update`.

**Comment by brambeekman** [comment]
> Make sure your `crafcms/cms` requirement in `composer.json` is set to `"^3.7.0-beta.1"` or higher, then run `composer update`.

Thanks! This works perfectly for me.
