### ISSUE TITLE
Cannot change Section from channel to structure - DB::each closes the current PDO instance and cancels pending transactions

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#9149]
### Description

**EDIT - TL/DR**<br>
your new `DB:each` closes the current DB connection, thus pending transactions are gone and changing a section from channel to structure doesn't work anymore

<hr>

I've the latest beta release of Craft Pro 3.7.0-beta.5.
When I try to change a section from channel to structure it always fails with the message:
```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`craft3_db_mietzsch`.`structureelements`, CONSTRAINT `structureelements_structureId_fk` FOREIGN KEY (`structureId`) REFERENCES `structures` (`id`) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO `structureelements` (`structureId`, `dateCreated`, `dateUpdated`, `uid`, `lft`, `rgt`, `level`) VALUES (25, '2021-07-09 09:33:26', '2021-07-09 09:33:26', 'de5eb16f-6826-4569-aae1-80886e51b130', 1, 2, 0)
```

When I look at the debug toolbar everything seemed to be correct.... at least at the first sight.
I've striped not interesting things and found something odd...
```
Running action: craft\controllers\SectionsController::actionSaveSection()
Begin transaction
Set savepoint 1
```

```sql
INSERT INTO `structures` (`maxLevels`, `uid`, `dateCreated`, `dateUpdated`) VALUES (NULL, 'b0ad47d7-cff4-4f85-afde-b118be8ced2d', '2021-07-09 09:33:26', '2021-07-09 09:33:26')
```

I uncluded a custom log to check the id)-> 25
update the section -> set a structure id

```sql
UPDATE `sections` SET `structureId`=25, `type`='structure', `dateUpdated`='2021-07-09 09:33:26' WHERE `id`=26
```

now the strange things start... usually there should be a commit transaction somewhere or at least a new savepoint. However the next line is this
```
Closing DB connection: mysql:host=127.0.0.1;port=3306;dbname=craft3_db_mietzsch;
Opening DB connection: mysql:host=127.0.0.1;port=3306;dbname=craft3_db_mietzsch;
````

after some queries the same thing again

```
Closing DB connection: mysql:host=127.0.0.1;port=3306;dbname=craft3_db_mietzsch;
SHOW FULL COLUMNS FROM `structureelements`
Opening DB connection: mysql:host=127.0.0.1;port=3306;dbname=craft3_db_mietzsch;
```

a new transaction begins? The other one is not done?
```
Begin transaction
```

resave entries, save them into the newly created structure with ID 25
```
INSERT INTO `structureelements` (`structureId`, `dateCreated`, `dateUpdated`, `uid`, `lft`, `rgt`, `level`) VALUES (25, '2021-07-09 09:33:26', '2021-07-09 09:33:26', 'de5eb16f-6826-4569-aae1-80886e51b130', 1, 2, 0)
Roll back transaction
Closing DB connection: mysql:host=127.0.0.1;port=3306;dbname=craft3_db_mietzsch;
```

I don't know why but it seems like the connection is closed  any MySQL kinda doesn't "commit" the above changes internally.
I attached the downloaded version of the debug toolbar 
[Debugger.zip](https://github.com/craftcms/cms/files/6790510/Debugger.zip) (ignore the FOOOOO, this is just to find my custom log faster)

### Additional info

- Craft version: Craft Pro 3.7.0-beta.5
- PHP version: 7.3
- Database driver & version: MySQL 5.5.5

**Edit**
A little bit more research, I guess it's really due to the closing of the transaction
```
#0 /var/www/mietzsch/page/htdocs/vendor/craftcms/cms/src/db/Connection.php(186): yii\db\Connection->close()
#1 /var/www/mietzsch/page/htdocs/vendor/craftcms/cms/src/helpers/Db.php(1365): craft\db\Connection->close()
#2 [internal function]: craft\helpers\Db::craft\helpers\{closure}(Object(yii\base\Event))
#3 /var/www/mietzsch/page/htdocs/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Object(Closure), Object(yii\base\Event))
#4 /var/www/mietzsch/page/htdocs/vendor/yiisoft/yii2/db/BatchQueryResult.php(110): yii\base\Component->trigger('reset')
#5 /var/www/mietzsch/page/htdocs/vendor/yiisoft/yii2/db/BatchQueryResult.php(119): yii\db\BatchQueryResult->reset()
#6 /var/www/mietzsch/page/htdocs/vendor/craftcms/cms/src/services/Sections.php(1580): yii\db\BatchQueryResult->rewind()
#7 /var/www/mietzsch/page/htdocs/vendor/craftcms/cms/src/services/Sections.php(699): craft\services\Sections->_populateNewStructure(Object(craft\records\Section))
#8 /var/www/mietzsch/page/htdocs/vendor/craftcms/cms/src/base/ApplicationTrait.php(1668): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
```

When I change the following 
```PHP
    private function _populateNewStructure(SectionRecord $sectionRecord)
    {
        // Add all of the entries to the structure
        $query = Entry::find()
            ->sectionId($sectionRecord->id)
            ->siteId('*')
            ->unique()
            ->anyStatus()
            ->orderBy(['elements.id' => SORT_ASC])
            ->withStructure(false);

        $structuresService = Craft::$app->getStructures();

        /** @var Entry $entry */
        foreach (DB::each($query) as $entry) {
            $structuresService->appendToRoot($sectionRecord->structureId, $entry, Structures::MODE_INSERT);
        }
    }
```
to
```PHP
foreach ($query->each() as $entry) {
```
everything is good again

**Comment by brandonkelly** [comment]
Are you overriding the `db` component definition from `config/app.php` by chance? If so, can you post your code?

**Comment by Anubarak** [comment]
No I don't. I only overwrite `mailer`, `log`, and `i18n`.

**Comment by brandonkelly** [comment]
I’m not able to reproduce this on my end, so not really sure what’s going on, but clearly it’s a result of the changes related to #7338. So I’ve just made that opt-in, by adding a new `useUnbufferedConnections` database setting, which is `false` by default.

**Comment by brandonkelly** [comment]
3.7.0-beta.6 is out now with that change.
