### ISSUE TITLE
Exception: Setting unknown property: craft\records\Section::defaultPlacement (/home/vagrant/tessera/vendor/yiisoft/yii2/base/Component.php:210)

### ISSUE THREAD

**Issue by brianjhanson** [craftcms/cms#9624]
### Description
When trying to update from an older version of Craft (3.4.10 in this case) up to 3.7.X an error is thrown about the `defaultPlacement` property on a section.

<details>
<summary>Full Exception</summary>

```
*** applying m200620_230205_field_layout_changes
    > add column elements text AFTER `name` to table {{%fieldlayouttabs}} ... done (time: 0.002s)
    > drop column titleLabel from table {{%entrytypes}} ... done (time: 0.002s)
Exception: Setting unknown property: craft\records\Section::defaultPlacement (/home/vagrant/project-folder/vendor/yiisoft/yii2/base/Component.php:210)
#0 /home/vagrant/project-folder/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set()
#1 /home/vagrant/project-folder/vendor/craftcms/cms/src/db/ActiveRecord.php(54): yii\db\BaseActiveRecord->__set()
#2 /home/vagrant/project-folder/vendor/craftcms/cms/src/services/Sections.php(586): craft\db\ActiveRecord->__set()
#3 /home/vagrant/project-folder/vendor/craftcms/cms/src/base/ApplicationTrait.php(1668): craft\services\Sections->handleChangedSection()
#4 /home/vagrant/project-folder/vendor/craftcms/cms/src/services/ProjectConfig.php(1189): craft\console\Application->craft\base\{closure}()
#5 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#6 /home/vagrant/project-folder/vendor/yiisoft/yii2/base/Component.php(628): call_user_func()
#7 /home/vagrant/project-folder/vendor/craftcms/cms/src/services/ProjectConfig.php(752): yii\base\Component->trigger()
#8 /home/vagrant/project-folder/vendor/craftcms/cms/src/services/ProjectConfig.php(1179): craft\services\ProjectConfig->_processConfigChangesInternal()
#9 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#10 /home/vagrant/project-folder/vendor/yiisoft/yii2/base/Component.php(628): call_user_func()
#11 /home/vagrant/project-folder/vendor/craftcms/cms/src/services/ProjectConfig.php(752): yii\base\Component->trigger()
#12 /home/vagrant/project-folder/vendor/craftcms/cms/src/services/ProjectConfig.php(521): craft\services\ProjectConfig->_processConfigChangesInternal()
#13 /home/vagrant/project-folder/vendor/craftcms/cms/src/migrations/m200620_230205_field_layout_changes.php(87): craft\services\ProjectConfig->set()
#14 /home/vagrant/project-folder/vendor/craftcms/cms/src/migrations/m200620_230205_field_layout_changes.php(36): craft\migrations\m200620_230205_field_layout_changes->_updateEntryTypeFieldLayouts()
#15 /home/vagrant/project-folder/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m200620_230205_field_layout_changes->safeUp()
#16 /home/vagrant/project-folder/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): craft\db\Migration->up()
#17 /home/vagrant/project-folder/vendor/craftcms/cms/src/console/controllers/MigrateController.php(379): yii\console\controllers\BaseMigrateController->migrateUp()
#18 [internal function]: craft\console\controllers\MigrateController->actionAll()
#19 /home/vagrant/project-folder/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#20 /home/vagrant/project-folder/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#21 /home/vagrant/project-folder/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#22 /home/vagrant/project-folder/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction()
#23 /home/vagrant/project-folder/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#24 /home/vagrant/project-folder/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction()
#25 /home/vagrant/project-folder/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction()
#26 /home/vagrant/project-folder/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#27 /home/vagrant/project-folder/craft(25): yii\base\Application->run()
#28 {main}
```

</details>

This seems to be because `handleChangedSection()` assumes that the `defaultPlacement` property is already in place, but the migration for that property hasn't run quite yet. 

### Steps to reproduce

1. Update from 3.4 to 3.7
2. Attempt to run `m200620_230205_field_layout_changes` migration.

### Additional info

- Craft version: 3.4.10
- PHP version: 7.3
- Database driver & version: MySQL / 5.7
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.4"` and run `composer update`.

**Comment by brianjhanson** [comment]
🎉  Thanks for the quick response & fix!

**Comment by brandonkelly** [comment]
Craft 3.7.5 is out now with that fix.

**Comment by markhuot** [comment]
Confirming that I experienced the same bug on `3.7.4` but updating to `3.7.5` fixed it up. Thank you!
