### ISSUE TITLE
Setting unknown property: craft\fields\Matrix::propagationKeyFormat

### ISSUE THREAD

**Issue by bengreenbank** [craftcms/cms#9678]
### Description

I need to update the search indexes on my site. I used this command: `./craft resave/entries --section businessDirectory --update-search-index`. Locally (using Nitro) this worked, however on my remote NGINX server it throws an error. Interestingly, when I also try to apply project config it throws this error too.

```
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: craft\fields\Matrix::propagationKeyFormat'

in /var/www/york/vendor/yiisoft/yii2/base/Component.php:210

Stack trace:
#0 /var/www/york/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set()
#1 /var/www/york/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure()
#2 /var/www/york/vendor/craftcms/cms/src/fields/Matrix.php(154): yii\base\BaseObject->__construct()
#3 [internal function]: craft\fields\Matrix->__construct()
#4 /var/www/york/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs()
#5 /var/www/york/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build()
#6 /var/www/york/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#7 /var/www/york/vendor/craftcms/cms/src/helpers/Component.php(111): yii\BaseYii::createObject()
#8 /var/www/york/vendor/craftcms/cms/src/services/Fields.php(580): craft\helpers\Component::createComponent()
#9 /var/www/york/vendor/craftcms/cms/src/services/Fields.php(605): craft\services\Fields->createField()
#10 /var/www/york/vendor/craftcms/cms/src/services/Fields.php(634): craft\services\Fields->_fields()
#11 /var/www/york/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2089): craft\services\Fields->getAllFields()
#12 /var/www/york/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1408): craft\elements\db\ElementQuery->customFields()
#13 /var/www/york/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
#14 /var/www/york/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
#15 /var/www/york/vendor/yiisoft/yii2/db/Query.php(480): yii\db\Query->createCommand()
#16 /var/www/york/vendor/craftcms/cms/src/db/Query.php(259): yii\db\Query->queryScalar()
#17 /var/www/york/vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar()
#18 /var/www/york/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1531): yii\db\Query->count()
#19 /var/www/york/vendor/craftcms/cms/src/console/controllers/ResaveController.php(278): craft\elements\db\ElementQuery->count()
#20 /var/www/york/vendor/craftcms/cms/src/console/controllers/ResaveController.php(186): craft\console\controllers\ResaveController->saveElements()
#21 [internal function]: craft\console\controllers\ResaveController->actionEntries()
#22 /var/www/york/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#23 /var/www/york/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#24 /var/www/york/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#25 /var/www/york/vendor/craftcms/cms/src/console/Controller.php(192): yii\console\Controller->runAction()
#26 /var/www/york/vendor/yiisoft/yii2/base/Module.php(534): craft\console\Controller->runAction()
#27 /var/www/york/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#28 /var/www/york/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction()
#29 /var/www/york/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction()
#30 /var/www/york/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#31 /var/www/york/craft(27): yii\base\Application->run()
#32 {main}
```

### Steps to reproduce

1. Run command mentioned above

### Additional info

- Craft version: 3.7.4
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7
- Plugins & versions:

**Comment by brandonkelly** [comment]
`craft\fields\Matrix::$propagationKeyFormat` was added in 3.7.0. So you must have reverted back to a prior version of Craft, or maybe just that one file. Not sure how that would have happened though.

Open your `composer.json` file and set your `craftcms/cms` requirement to something like `"^3.7.7"`, then run `composer update`. That should get you sorted.

**Comment by bengreenbank** [comment]
My current craft version is set to `craftcms/cms": "3.7.4` in `composer.json`. So should I still run `composer update` locally? Or will I need to update to a newer CraftCMS version like `3.7.7`?

**Comment by bengreenbank** [comment]
I tried updating to CraftCMS `3.7.7` and also rebuilding Project Config, however this did not work.

**Comment by brandonkelly** [comment]
Anything over 3.7.0 should work.

Open up `vendor/craftcms/cms/src/fields/Matrix.php` in a code editor. Do you see any instances of `propagationKeyFormat` in there?

**Comment by bengreenbank** [comment]
This seems to have been due to an unrelated issue on my staging server. This has now been resolved. Thanks for your help.
