### ISSUE TITLE
Template not found: $PRIMARY_SITE_URL/$PRIMARY_SITE_URL

### ISSUE THREAD

**Issue by alexsanderson** [craftcms/cms#9691]
### Description

Occasionally (once or twice a month), when previewing a page, the 404 page is shown with `$PRIMARY_SITE_URL` in the URL, e.g., https://dev.redacted.com/$PRIMARY_SITE_URL/$PRIMARY_SITE_URL/faq when it should be https://dev.redacted.com/faq

This happened when editing the homepage and viewing the preview:

<img width="402" alt="Screenshot_2021-08-09_15 48 11@2x" src="https://user-images.githubusercontent.com/25802369/128726120-c4838c25-d28a-465f-ba0a-261313758d28.png">

Here's the `web-404s.log` for that request:

```
2021-08-09 13:50:33 [-][76][7affc1646d963a99dd02dce5be389b70][error][yii\web\HttpException:404] yii\web\NotFoundHttpException: Template not found: $PRIMARY_SITE_URL/$PRIMARY_SITE_URL in /home/customer/www/dev.redacted.com/vendor/craftcms/cms/src/controllers/TemplatesController.php:92
Stack trace:
#0 [internal function]: craft\controllers\TemplatesController->actionRender('$PRIMARY_SITE_U...', Array)
#1 /home/customer/www/dev.redacted.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /home/customer/www/dev.redacted.com/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#3 /home/customer/www/dev.redacted.com/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('render', Array)
#4 /home/customer/www/dev.redacted.com/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('render', Array)
#5 /home/customer/www/dev.redacted.com/vendor/craftcms/cms/src/web/Application.php(276): yii\base\Module->runAction('templates/rende...', Array)
#6 /home/customer/www/dev.redacted.com/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('templates/rende...', Array)
#7 /home/customer/www/dev.redacted.com/vendor/craftcms/cms/src/web/Application.php(261): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /home/customer/www/dev.redacted.com/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /home/customer/www/dev.redacted.com/public_html/index.php(22): yii\base\Application->run()
#10 {main}
2021-08-09 13:50:33 [-][76][7affc1646d963a99dd02dce5be389b70][info][application] $_GET = [
    'p' => 'admin/$PRIMARY_SITE_URL/$PRIMARY_SITE_URL'
    'x-craft-live-preview' => 'dhxPyPm5t7'
]

$_POST = []

$_FILES = []

$_COOKIE = [
    ... (trimmed)
]

$_SESSION = [
    '9937fe22cd2386714db13f0c0ecda44a__flash' => []
    '9937fe22cd2386714db13f0c0ecda44a__auth_access' => [
        0 => 'seomaticPreviewAuthorizationKey2'
        1 => 'previewElement:2'
        2 => 'saveAssetInVolume:2'
        3 => 'previewDraft:2'
        4 => 'seomaticPreviewAuthorizationKey2997'
        5 => 'seomaticPreviewAuthorizationKey2888'
        6 => 'previewElement:2888'
        7 => 'seomaticPreviewAuthorizationKey3010'
        8 => 'previewDraft:3'
        9 => 'seomaticPreviewAuthorizationKey58'
        10 => 'previewElement:58'
        11 => 'seomaticPreviewAuthorizationKey3011'
        12 => 'previewDraft:4'
        13 => 'previewElement:3011'
        14 => 'seomaticPreviewAuthorizationKey2201'
        15 => 'previewElement:2201'
        16 => 'editStructure:4'
        17 => 'previewElement:2784'
        18 => 'editStructure:2'
        19 => 'editStructure:3'
        20 => 'editStructure:1'
    ]
    'c41e90ef77e973eb365370c81aebc1cf__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'c41e90ef77e973eb365370c81aebc1cf__id' => 76
    '__authKey' => '•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'c41e90ef77e973eb365370c81aebc1cf__expire' => 1628517033
    '__duration' => 3600
]

$_SERVER = [
    'REDIRECT_HTTPS' => 'on'
    'REDIRECT_UNIQUE_ID' => 'YREkmUBJki8jRnZqOWQgoAAAAAM'
    'REDIRECT_STATUS' => '200'
    'HTTPS' => 'on'
    'UNIQUE_ID' => 'YREkmUBJki8jRnZqOWQgoAAAAAM'
    'HTTP_X_PORT' => '58573'
    'HTTP_X_REAL_IP' => 'redacted'
    'HTTP_X_FORWARDED_PROTO' => 'https'
    'HTTP_HOST' => 'dev.redacted.com'
    'HTTP_X_ACCEPT_ENCODING' => 'gzip, deflate, br'
    'HTTP_CONNECTION' => 'close'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.3 Safari/605.1.15'
    'HTTP_ACCEPT_LANGUAGE' => 'en-gb'
    'HTTP_REFERER' => 'https://dev.redacted.com/admin/entries/homepage/2-home'
    'HTTP_COOKIE' => '...'
    'PATH' => '/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin'
    'SERVER_SIGNATURE' => ''
    'SERVER_SOFTWARE' => 'Apache'
    'SERVER_NAME' => 'dev.redacted.com'
    'SERVER_ADDR' => 'redacted'
    'SERVER_PORT' => '443'
    'REMOTE_ADDR' => 'redacted'
    'DOCUMENT_ROOT' => '/home/customer/www/dev.redacted.com/public_html'
    'REQUEST_SCHEME' => 'https'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => '/home/customer/www/dev.redacted.com/public_html'
    'SERVER_ADMIN' => '[no address given]'
    'SCRIPT_FILENAME' => '/home/customer/www/dev.redacted.com/public_html/index.php'
    'REMOTE_PORT' => '12136'
    'REDIRECT_URL' => '/admin/$PRIMARY_SITE_URL/$PRIMARY_SITE_URL'
    'REDIRECT_QUERY_STRING' => 'p=admin/$PRIMARY_SITE_URL/$PRIMARY_SITE_URL&x-craft-live-preview=dhxPyPm5t7'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.0'
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => 'p=admin/$PRIMARY_SITE_URL/$PRIMARY_SITE_URL&x-craft-live-preview=dhxPyPm5t7'
    'REQUEST_URI' => '/admin/$PRIMARY_SITE_URL/$PRIMARY_SITE_URL?x-craft-live-preview=dhxPyPm5t7'
    'SCRIPT_NAME' => '/index.php'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1628513433.2836
    'REQUEST_TIME' => 1628513433
    'ENVIRONMENT' => 'staging'
    'APP_ID' => 'redacted'
    'SECURITY_KEY' => '••••••••••••••••••••••••••••••••'
    'DB_DRIVER' => 'mysql'
    'DB_SERVER' => '127.0.0.1'
    'DB_PORT' => '3306'
    'DB_DATABASE' => 'redacted'
    'DB_USER' => 'redacted'
    'DB_PASSWORD' => '••••••••••••'
    'DB_SCHEMA' => ''
    'DB_TABLE_PREFIX' => ''
    'PRIMARY_SITE_URL' => 'https://dev.redacted.com/'
]
```

### Steps to reproduce

I can't as the bug is intermittent, happening once/twice a month. A simple page refresh resolves it.

Is there anything I can do to try and pinpoint the problem?

### Additional info

- Craft version: Craft Pro 3.7.7
- PHP version: 7.4.22
- Database driver & version: MySQL 5.7.32
- Plugins & versions: Formie 1.4.12, Navigation 1.4.20, Redactor 2.8.8, SEOmatic 3.3.46, Super Table 2.6.8

**Comment by brandonkelly** [comment]
What is the preview target’s URL format, in your section’s settings?

**Comment by alexsanderson** [comment]
For all sections the (one) preview target's URL is `{url}`

**Comment by brandonkelly** [comment]
- For a section where this error occurs, what is the entry URI format?
- What is the site’s Base URL?
- What are your `$PRIMARY_SITE_URL` and `$RY_SITE_URI` environment variables supposed to be set to?

**Comment by alexsanderson** [comment]
Both the homepage and FAQ have experienced it:

<img width="421" alt="Screenshot_2021-08-10_16 20 52@2x" src="https://user-images.githubusercontent.com/25802369/128915525-091bbe21-b972-4814-a78f-268733c42c4a.png">
<img width="565" alt="Screenshot_2021-08-10_16 21 10@2x" src="https://user-images.githubusercontent.com/25802369/128915572-706d2e94-4ab6-43f9-a921-0b85337fabc5.png">

The base URL is `$PRIMARY_SITE_URL`:

<img width="418" alt="Screenshot_2021-08-10_16 23 50@2x" src="https://user-images.githubusercontent.com/25802369/128915681-025be734-0e13-49bf-9176-76704ea15637.png">

The `$PRIMARY_SITE_URL` is set in the .env file as https://dev.redacted.com/ (excuse the redaction) and it looks from the log (above) that it's loaded as expected:
```
'PRIMARY_SITE_URL' => 'https://dev.redacted.com/'
```

Is the `$RY_SITE_URI` a typo?

**Comment by angrybrad** [comment]
@alexsanderson can you describe the environment you're seeing this in? Is it load-balanced web servers? A Docker/containerized environment?

**Comment by alexsanderson** [comment]
Sure @angrybrad. It's a single server running a LAMP stack. It's not load-balanced, nor is it containerised. There's a NGINX cache that fronts it, but I've seen that the CP sends the 'no-cache' header.

**Comment by alexsanderson** [comment]
Here's an example from the HTTP request log:

```
[09/Aug/2021 12:51:38] "GET /admin/$PRIMARY_SITE_URL/$PRIMARY_SITE_URL/faq?x-craft-live-preview=pSDMYXzYVX HTTP/2.0" 404 10117 "https://dev.redacted.com/admin/entries/faq/2873-faq"
```

**Comment by angrybrad** [comment]
@alexsanderson odd... any chance we could get SSH and Craft control panel access to the box? If so, can you send over to support@craftcms.com and reference this ticket? I realize you said it happens rarely, but would like to glance over how the site is configured and check through some logs.
