### ISSUE TITLE
Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'dateCreated' at row 56

### ISSUE THREAD

**Issue by sjoulbak** [craftcms/cms#9701]
### Description

When running migrations from 2.9.2 up to 3.7.8 in the `m180321_233505_small_ints` migration the `sortOrder` in table `craft_relations` cannot be altered to smallint UNSIGNED due to some rows in that table which have the value `0000-00-00 00:00:00` in column `dateCreated`.

<details>
   <summary>Full stack trace</summary>
  
```bash
*** applying m180321_233505_small_ints
    > alter column sortOrder in table {{%entrytypes}} to smallint UNSIGNED ... done (time: 0.002s)
    > alter column sortOrder in table {{%fieldlayoutfields}} to smallint UNSIGNED ... done (time: 0.002s)
    > alter column sortOrder in table {{%fieldlayouttabs}} to smallint UNSIGNED ... done (time: 0.002s)
    > alter column sortOrder in table {{%matrixblocks}} to smallint UNSIGNED ... done (time: 0.002s)
    > alter column sortOrder in table {{%matrixblocktypes}} to smallint UNSIGNED ... done (time: 0.002s)
    > alter column sortOrder in table {{%relations}} to smallint UNSIGNED ...Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'dateCreated' at row 56
The SQL being executed was: ALTER TABLE `craft_relations` CHANGE `sortOrder` `sortOrder` smallint(6) UNSIGNED (/app/user/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /app/user/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `cr...')
#1 /app/user/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE `cr...')
#2 /app/user/vendor/yiisoft/yii2/db/Migration.php(420): yii\db\Command->execute()
#3 /app/user/vendor/craftcms/cms/src/migrations/m180321_233505_small_ints.php(23): yii\db\Migration->alterColumn('{{%relations}}', 'sortOrder', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /app/user/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m180321_233505_small_ints->safeUp()
#5 /app/user/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): craft\db\Migration->up()
#6 /app/user/vendor/craftcms/cms/src/console/controllers/MigrateController.php(379): yii\console\controllers\BaseMigrateController->migrateUp('m180321_233505_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /app/user/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#10 /app/user/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('all', Array)
#11 /app/user/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('all', Array)
#12 /app/user/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('migrate/all', Array)
#13 /app/user/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#14 /app/user/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('migrate/all', Array)
#15 /app/user/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /app/user/craft(35): yii\base\Application->run()
#17 {main}
*** failed to apply m180321_233505_small_ints (time: 0.037s)
```
</details>

### Steps to reproduce

1. Update from 2.9.2 to 3.7.8
2. Attempt to run m180321_233505_small_ints migration

### Additional info

- Craft version: 2.9.2
- PHP version: 7.4.5
- Database driver & version: MYSQL 5.7.35
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Not really sure what to make of that… the migration doesn’t touch the `dateCreated` column, so the invalid value must have already been in there. Maybe it was entered manually, and has just been a sitting landmine ever since, waiting for the first thing to touch the row.

Restore the Craft 2 DB backup, and sniff out any such invalid date values and correct them, then try updating to Craft 3 again.

If you’re still struggling, please send an email into support@craftcms.com and we can help you further from there.

**Comment by sjoulbak** [comment]
Thank you for your feedback @brandonkelly! I will correct those date values manually
