### ISSUE TITLE
Can't edit entries with multiple sites due to a TypeError

### ISSUE THREAD

**Issue by Marcuzz** [craftcms/cms#9965]
### Description

I just updated from 3.7.8 to 3.7.16 and noticed I'm no longer able to edit any entries.

When attempting to edit an entry with `?site=x` as a URL query parameter Craft throws a 500 internal server error. If we remove `?site=x` from the query params we're able to load the page and edit it as usual. It appears to happen with any site specified in `?site=`, regardless of whether they exist or not.

An observation I made was that for some reason removing the type definition of `$draftId` and `$revisionId` in `actionEditEntry()` appears to have fixed the problem, but making them `int|string` does not work. It's obviously unrelated to these function argument types, since they have not been touched for the past 3 years, but it could help with finding where the problem occurs 😅

### Steps to reproduce

1. With multiple sites enabled, attempt to edit any entry
2. The site should throw a 500 internal server error

### Additional info

```
TypeError: craft\controllers\EntriesController::actionEditEntry(): Argument #3 ($draftId) must be of type ?int, string given in /app/vendor/craftcms/cms/src/controllers/EntriesController.php:63
Stack trace:
#0 [internal function]: craft\controllers\EntriesController->actionEditEntry('investors', 977, 'en', NULL)
#1 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#3 /app/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('edit-entry', Array)
#4 /app/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-entry', Array)
#5 /app/vendor/craftcms/cms/src/web/Application.php(277): yii\base\Module->runAction('entries/edit-en...', Array)
#6 /app/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('entries/edit-en...', Array)
#7 /app/vendor/craftcms/cms/src/web/Application.php(262): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /app/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /app/web/index.php(21): yii\base\Application->run()
#10 {main}
```

Extra image for additional context:

![image](https://user-images.githubusercontent.com/3168421/137329450-40b1f7f3-9135-4c38-89ed-067670a2b223.png)

- Craft version: `3.7.16`
- PHP version: `8.0.9`
- Database driver & version: `PostgreSQL 13`
- Plugins & versions: `spicyweb/craft-neo 2.11.14`

**Comment by Marcuzz** [comment]
Thank you, that works for now 😃
